### ISSUE TITLE
Tx always pending with NodeJS, using my own bsc node 

### ISSUE THREAD

**Issue by banlieu451** [bnb-chain/bsc#1000]
Hello everybody i have a missunderstood, i run my own bsc full node and it work ... with some troubles

My server config is :

i9
2 TB NVME
4x RAM 32768 MB DDR4
1000 mb/s

i run this command on geth : 

./geth --config ./config.toml --datadir ./node --cache 18000 --rpc.allow-unprotected-txs --txlookuplimit 0 --syncmode 'fast' --ws --ws.port 8546 --ws.addr (ip) --http --http.port 8545 --http.addr (ip) --rpc --diffsync console

eth.syncing > return false 

Sometime it work like 2/10 but many time my tx was send but always pending, and when i add another wss endpoint (public) the scrypt run and execute all my old tx and confirm it.

I'm asking how to fix this problem need i prune or change mode to full or light ? 

Sincerely Mickaël

**Comment by yutianwu** [comment]
can you refer to this https://github.com/bnb-chain/bsc/issues/502 first?

**Comment by banlieu451** [comment]
> can you refer to this #502 first?

Thanks for your reply i do it this message appear : 

<img width="637" alt="Capture d’écran 2022-07-19 221004" src="https://user-images.githubusercontent.com/76543738/179839455-10a80e27-bbdb-4a4a-875d-b2db207ad08f.png">

**Comment by banlieu451** [comment]
> can you refer to this #502 first?

Try to prune - 100 block of header i get this : 

<img width="941" alt="Capture d’écran 2022-07-19 221004" src="https://user-images.githubusercontent.com/76543738/179843620-f375fbe0-32a2-4d3a-b6cf-ead544c4b4ea.png">
