### ISSUE TITLE
BSC FULLNODE SYNC

### ISSUE THREAD

**Issue by Githugutech** [bnb-chain/bsc#1012]
##### Hello. Could you help me please. I used the following procedure:

Geth version: `V1.1.8`
OS & Version: Ubuntu 20

#### Expected behaviour
I fully expected the syncing process to run successful and faster. I synced ETH node and it took me 4 hours to sync data from 6 years and 6 months.

#### Actual behaviour

. Failed with the following error
`WARN [07-22|11:59:44.642] Config field is deprecated and won't have an effect name=ethconfig.Config.EWASMInterpreter
Fatal: ./config.toml, line 35: field 'OracleThreshold' is not defined in gasprice.Config, see https://godoc.org/github.com/ethereum/go-ethereum/eth/gasprice#Config for available fields`

#### Steps to reproduce the behaviour
. I download geth and mainnet using wget version 1.1.8
. Made the geth_linux downloaded executable using `chmod +x geth_linux`
. Unzipped the mainnet `to get the config.tomol and genesis.json`
. Move config.toml and genesis.json to the root folder
. Run the command ./geth_linux --datadir ./mainnet init genesis.json `to generate genesis`
. Download the latest snapshot
. Deleted the chaindata and triecache data from the datadir folder (mainnet) incase it already exists to sync afresh. 
. Move the chaindata and triecache data of the downloaded snapshot to my datadir (mainnet) using the commands below
. `rm -rf mainnet/geth/chaindata` 
. `rm -rf mainnet/geth/triecache`
. `mv server/data-seed/geth/chaindata mainnet/geth/chaindata`
. `mv server/data-seed/geth/triecache mainnet/geth/triecache`

. Removed logs settings from config.toml so that I can see logs in the terminal in real-time. `I deleted the last part of the config.toml file.`
. Then started node sync using  `./geth_linux --config ./config.toml --datadir ./mainnet --cache 100000 --rpc.allow-unprotected-txs --txlookuplimit 0 --http --maxpeers 100 --ws --syncmode=full --snapshot=false --diffsync`

Help me please, I don't know how to solve it.

**Comment by SomeGuyCalledBru** [comment]
Your version seems outdated-newest is v1.1.11. If that does not fix it, simply remove the config line causing the error

**Comment by Githugutech** [comment]
still doesn't work, i have tried even the old versions but i have the same problem

**Comment by forcodedancing** [comment]
@Githugutech Can you try the config files and binary in the release https://github.com/bnb-chain/bsc/releases ? 

If you still encounter issues with them, please share the config and command you you using. Thanks.

**Comment by forcodedancing** [comment]
Hello @Githugutech I will close this issue for inactivity of it. It you still have issues, please reopen it or create a new one. Thanks.

**Comment by Githugutech** [comment]
Thanks i got a different option from friends on discord and it worked like magic

**Comment by Githugutech** [comment]
Thanks for the assistance

**Comment by Githugutech** [comment]
If you would like me to share the new method that syncs fully within 4 hours from start to finish, i will gladly share.

**Comment by arthurwolf** [comment]
Please share what you did to fix this, I am running into the same issue and can't find a solution.
