### ISSUE TITLE
I have been running fullnode for more than 7 days but still not done.please help

### ISSUE THREAD

**Issue by hophat** [bnb-chain/bsc#1021]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

![image](https://user-images.githubusercontent.com/21335957/181198068-93d094dc-4b2c-4127-ace1-aa2f332d5f02.png)
the sync has reached over 2TB.
I have tried many ways but still not sure where I went wrong. Please help
![image](https://user-images.githubusercontent.com/21335957/181198670-b5f8cbd3-4f95-4db4-a995-e735386215e9.png)
![image](https://user-images.githubusercontent.com/21335957/181198760-ddcb92c0-983f-456d-a6b6-8c99aa1d39c8.png)
![image](https://user-images.githubusercontent.com/21335957/181198809-e4645606-1b90-4df7-9a27-a4de29f5bc67.png)

**Comment by SomeGuyCalledBru** [comment]
You have not done anything wrong. This is just how long it takes. Send your eth.syncing output for an approximation

**Comment by guagualvcha** [comment]
It is recommended to download from latest snapshot https://github.com/bnb-chain/bsc-snapshots.

**Comment by forcodedancing** [comment]
@hophat I will close this issue for inactivity of it. It you still have issues, please reopen it or create a new one. Thanks.
