### ISSUE TITLE
Why a fresh new smart contract address has transactions before ? Is it valid for blockchain?

### ISSUE THREAD

**Issue by pthor11** [bnb-chain/bsc#1022]
We've deployed a new smartcontract at https://testnet.bscscan.com/address/0xd07e82440a395f3f3551b42da9210cd1ef4f8b24.

But it does have a log of previously transactions that existed before. Why is that?

**Comment by SomeGuyCalledBru** [comment]
It is valid, addresses exist before contract code gets assigned to them. That being said, this is insanely, insanely, crazily unlikely and someone probably derived the contract address using the address you used to deploy.

**Comment by pthor11** [comment]
Thank you
