### ISSUE TITLE
Geth does not start after updating to v1.1.12

### ISSUE THREAD

**Issue by mj-dcb** [bnb-chain/bsc#1027]
Hello,

I just updated the geth client from v1.1.10 to v1.1.12. I can't started geth somehow, I use the same command as before:
`./geth --config ./config.toml --datadir ./mainnet --diffsync --cache 21000 --rpc.allow-unprotected-txs --txlookuplimit 0 --ws --ws.addr "0.0.0.0" --ws.port=8545  --ws.origins='*' --pruneancient` I added --pruneancient to reduce the used disk space.

This is what I get in the console:
```
root@Ubuntu-2204-jammy-amd64-base /home/geth # ./geth --config ./config.toml --datadir ./mainnet --diffsync --cache 21000 --rpc.allow-unprotected-txs --txlookuplimit 0 --ws --ws.addr "0.0.0.0" --ws.port=8545  --ws.origins='*' --pruneancient
INFO [07-28|14:33:13.655] Starting Geth on Ethereum mainnet... 
INFO [07-28|14:33:13.658] Maximum peer count                       ETH=30 LES=0 total=30
INFO [07-28|14:33:13.659] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [07-28|14:33:13.659] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable
```

0 lines are added to bsc.log. I have not changed mainnet or config files, I replaced geth that's it. Maybe I'm missing something.

Who can help me with this? :)

**Comment by forcodedancing** [comment]
@mj-dcb is there any other logs? Do you mean that geth was stuck?

**Comment by JayMaree** [comment]
There is no log file. It creates the log file but there is no content.

**Comment by joeylichang** [comment]
try add --syncmode full

**Comment by KyloYang888** [comment]
Hi @mj-dcb . Have you solved this problem? I have the same problem

**Comment by forcodedancing** [comment]
> Hi @mj-dcb . Have you solved this problem? I have the same problem

Did you also use this flat `--pruneancient` ?

**Comment by forcodedancing** [comment]
Hello @mj-dcb I will close this issue for inactivity of it. It you still have issues, please reopen it or create a new one. Thanks.

**Comment by panella87** [comment]
same problem, did you solved it?
