### ISSUE TITLE
About the new version v1.1.12

### ISSUE THREAD

**Issue by xsm19** [bnb-chain/bsc#1028]
hello everyone

1. If I use fast node #926  --diffsync and --pipecommit, which one should I choose to achieve faster synchronization speed?

2. Can I specify a block to start synchronization? For example: startingblock:100000000 I don't need too much data, and I don't want to synchronize from the genesis block.

**Comment by PPianAIC** [comment]
me too, I want to know

**Comment by James19903** [comment]
Good question

**Comment by guagualvcha** [comment]
@xsm19 ,  `fastnode` mode is encouraged, once the node is running in fastnode mode, `diffsync` and `pipecommit` will be disabled automatically .

**Comment by PPianAIC** [comment]
@guagualvcha I used fast mode before, but some history blocks cannot be found. Now I'm ready to switch to full. How can I start from 0, not continue 19573855?
> eth.syncing
{
  currentBlock: 19573856,
  highestBlock: 20048662,
  startingBlock: 19573855
}

**Comment by forcodedancing** [comment]
You can download the recent snapshot from https://github.com/bnb-chain/bsc-snapshots and sync using full mode.

**Comment by PPianAIC** [comment]
root@admin:~# geth version
Geth
Version: 1.1.12
Git Commit: f68965a615fdc8deaeb41e6b18fce2a7c60c2419
Git Commit Date: 20220728
Architecture: amd64
Go Version: go1.18.4
Operating System: linux
GOPATH=
GOROOT=go

t=2022-08-04T01:42:33+0000 lvl=info msg="Imported new chain segment"             blocks=53   txs=312  mgas=34.292  elapsed=8.106s      mgasps=4.230  number=2,613,143 hash=0x4ee6dea157b3762415bdb4a5537964e366aaf96450624d4f56ccaf24db9d594e age=1y8mo2w  dirty="34.12 KiB"
t=2022-08-04T01:42:41+0000 lvl=info msg="Imported new chain segment"             blocks=72   txs=504  mgas=45.200  elapsed=8.003s      mgasps=5.647  number=2,613,215 hash=0xee14be83045d2fa80353adade8d46a5ad14a74d99ce6ebc67410fbf21f59dc8b age=1y8mo2w  dirty="69.01 KiB"
t=2022-08-04T01:42:52+0000 lvl=info msg="Imported new chain segment"             blocks=35   txs=258  mgas=35.276  elapsed=11.644s     mgasps=3.029  number=2,613,250 hash=0xaa02602793bee16bd7d9ede3fda85cf0e83d94012b193a91d2222dfcbf3a09de age=1y8mo2w  dirty="1.23 MiB"
t=2022-08-04T01:43:00+0000 lvl=info msg="Imported new chain segment"             blocks=76   txs=551  mgas=59.573  elapsed=8.204s      mgasps=7.261  number=2,613,326 hash=0x1ce5d165a06219d90e9d5c271957dc029e94e8ad84ffb1e55e3ffd88750d6c2b age=1y8mo2w  dirty="204.63 KiB"
t=2022-08-04T01:43:12+0000 lvl=info msg="Deep froze chain segment"               blocks=307  elapsed=89.238ms    number=2,523,356 hash=0x18eb8f3272ed21541c9900af66dbe674ff8a4061de6b71a06ff852a793da3ca5
t=2022-08-04T01:43:17+0000 lvl=info msg="Imported new chain segment"             blocks=31   txs=241  mgas=42.498  elapsed=16.726s     mgasps=2.541  number=2,613,357 hash=0x833ff4a5047667e10d1449d869fd81a2f6fabc53304556c71dfed4c35e9214ba age=1y8mo2w  dirty="1.85 MiB"
t=2022-08-04T01:43:38+0000 lvl=info msg="Imported new chain segment"             blocks=10   txs=70   mgas=28.795  elapsed=20.993s     mgasps=1.372  number=2,613,367 hash=0xecea298cec1ca5d073e54b3e2538eff888e99378868bb3697d510cae4fdee809 age=1y8mo2w  dirty="2.03 MiB"
t=2022-08-04T01:43:57+0000 lvl=info msg="Imported new chain segment"             blocks=3    txs=42   mgas=23.681  elapsed=18.919s     mgasps=1.252  number=2,613,370 hash=0x3dfe32d7112c6e86f513e0d37b4f5e1f0cd9accba04c495ce058e0c55467f455 age=1y8mo2w  dirty="1.89 MiB"
t=2022-08-04T01:44:12+0000 lvl=info msg="Deep froze chain segment"               blocks=15   elapsed=3.508ms     number=2,523,371 hash=0x1d8eb2683061bcb58920b7e86640066afe88a28370b666186326dffea369b4e7
t=2022-08-04T01:44:19+0000 lvl=info msg="Imported new chain segment"             blocks=2    txs=13   mgas=27.596  elapsed=21.906s     mgasps=1.260  number=2,613,372 hash=0x0d05ffbf616a3b2792bddccc908b6296769dc09454309bc406259031118a20ba age=1y8mo2w  dirty="1.92 MiB"
t=2022-08-04T01:44:35+0000 lvl=info msg="Imported new chain segment"             blocks=2    txs=12   mgas=21.470  elapsed=16.358s     mgasps=1.312  number=2,613,374 hash=0x5f61a782b6492434e25afd55ce5123562a26037f4293fe0a9c1d1fa334dd5a8b age=1y8mo2w  dirty="1.89 MiB"
t=2022-08-04T01:44:53+0000 lvl=info msg="Imported new chain segment"             blocks=2    txs=14   mgas=21.870  elapsed=18.010s     mgasps=1.214  number=2,613,376 hash=0x9745189127994ad2cc9a829d8647906023b8970ec789fbad32ca77fe2fb385c2 age=1y8mo2w  dirty="1.93 MiB"
t=2022-08-04T01:45:11+0000 lvl=info msg="Imported new chain segment"             blocks=2    txs=9    mgas=25.268  elapsed=17.381s     mgasps=1.454  number=2,613,378 hash=0x412596e6f1a00d83a567334e9c0c0f808c9315cc2cf59bf0e2d5136eb3dcf4e1 age=1y8mo2w  dirty="1.90 MiB"
t=2022-08-04T01:45:12+0000 lvl=info msg="Deep froze chain segment"               blocks=7    elapsed=3.265ms     number=2,523,378 hash=0x1aa1b3aabb1bc2851706a21e946667c83f6167dec09571224c18bdf8b49cba31
t=2022-08-04T01:45:30+0000 lvl=info msg="Imported new chain segment"             blocks=1    txs=6    mgas=20.933  elapsed=19.083s     mgasps=1.097  number=2,613,379 hash

geth --config /data/bsc1/config.toml --datadir /data/bsc1/node --http --diffsync --snapshot=true --syncmode=full --gcmode archive --cache 10240 --rpc.allow-unprotected-txs --txlookuplimit 0

The above is the version and sync information. Is the speed normal and can it be improved? Currently, it may take a long time to synchronize to the latest block. Thank you

**Comment by forcodedancing** [comment]
@PPianAIC are you trying to setup an archive node (`--gcmode archive`) ? Is it your purpose?

**Comment by PPianAIC** [comment]
I want to implement a full node that contains all data

**Comment by forcodedancing** [comment]
There is a big difference on a full node and archive node. The requirement of archive node is much higher than full node. You can refer to this: https://forum.bnbchain.org/t/how-to-run-a-archive-node-on-bnb-smart-chain/264 
If you do not need archive node (for most users), you can remove `--gcmode archive` and add `--pipecommit` to achieve better sync performance.

**Comment by PPianAIC** [comment]
I may need is an archive node, because I need all the historical data of the blockchain starting from the genesis block. Can I speed up sync？

**Comment by PPianAIC** [comment]
I have another question, How do I set ending block height that a segment archive node is a node which has all the data from one starting block height to one ending block height?
