### ISSUE TITLE
running node error, I can't solve the problem

### ISSUE THREAD

**Issue by PPianAIC** [bnb-chain/bsc#1029]
internal/poll.(*FD).Read(0xc000125180, {0xc02f3e5e20, 0x20, 0x20})
        internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000125180, {0xc02f3e5e20?, 0x1003e3090a97f?, 0x7ffa380421a8?})
        net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000206f18, {0xc02f3e5e20?, 0xc01815a430?, 0x46b212?})
        net/net.go:183 +0x45
io.ReadAtLeast({0x1a00080, 0xc000206f18}, {0xc02f3e5e20, 0x20, 0x20}, 0x20)
        io/io.go:331 +0x9a
io.ReadFull(...)
        io/io.go:350
github.com/ethereum/go-ethereum/p2p/rlpx.(*handshakeState).readFrame(0xc0103c0460, {0x1a00080, 0xc000206f18})
        github.com/ethereum/go-ethereum/p2p/rlpx/rlpx.go:140 +0x6d
github.com/ethereum/go-ethereum/p2p/rlpx.(*Conn).Read(0xc02e452bd0)
        github.com/ethereum/go-ethereum/p2p/rlpx/rlpx.go:112 +0x65
github.com/ethereum/go-ethereum/p2p.(*rlpxTransport).ReadMsg(0xc01daedf00)
        github.com/ethereum/go-ethereum/p2p/transport.go:64 +0x13f
github.com/ethereum/go-ethereum/p2p.(*Peer).readLoop(0xc02d3558c0, 0xc000276500?)
        github.com/ethereum/go-ethereum/p2p/peer.go:319 +0xd0
created by github.com/ethereum/go-ethereum/p2p.(*Peer).run
        github.com/ethereum/go-ethereum/p2p/peer.go:256 +0xf8

goroutine 1034 [select]:
github.com/ethereum/go-ethereum/p2p.(*Peer).pingLoop(0xc02d3558c0)
        github.com/ethereum/go-ethereum/p2p/peer.go:303 +0x11d
created by github.com/ethereum/go-ethereum/p2p.(*Peer).run
        github.com/ethereum/go-ethereum/p2p/peer.go:257 +0x13c

goroutine 1036 [select]:
github.com/ethereum/go-ethereum/eth/protocols/eth.(*Peer).broadcastBlocks(0xc02d48f960)
        github.com/ethereum/go-ethereum/eth/protocols/eth/broadcast.go:45 +0xd9
created by github.com/ethereum/go-ethereum/eth/protocols/eth.NewPeer
        github.com/ethereum/go-ethereum/eth/protocols/eth/peer.go:113 +0x425

goroutine 1037 [select]:
github.com/ethereum/go-ethereum/eth/protocols/eth.(*Peer).broadcastTransactions(0xc02d48f960)
        github.com/ethereum/go-ethereum/eth/protocols/eth/broadcast.go:106 +0x19b
created by github.com/ethereum/go-ethereum/eth/protocols/eth.NewPeer
        github.com/ethereum/go-ethereum/eth/protocols/eth/peer.go:114 +0x465

goroutine 1038 [select]:
github.com/ethereum/go-ethereum/eth/protocols/eth.(*Peer).announceTransactions(0xc02d48f960)
        github.com/ethereum/go-ethereum/eth/protocols/eth/broadcast.go:176 +0x18f
created by github.com/ethereum/go-ethereum/eth/protocols/eth.NewPeer
        github.com/ethereum/go-ethereum/eth/protocols/eth/peer.go:116 +0x4b0

**Comment by guagualvcha** [comment]
hi, would you provide the complete log files?

**Comment by guagualvcha** [comment]
@PPianAIC

**Comment by PPianAIC** [comment]
t=2022-08-02T01:27:15+0000 lvl=warn msg="Sanitizing cache to Go's GC limits" provided=10240 updated=6662
t=2022-08-02T01:27:15+0000 lvl=info msg="Enabling recording of key preimages since archive mode is used"
t=2022-08-02T01:27:15+0000 lvl=info msg="Set global gas cap"                 cap=25,000,000
t=2022-08-02T01:27:15+0000 lvl=info msg="Allocated trie memory caches"       clean="1.95 GiB" dirty="0.00 B"
t=2022-08-02T01:27:15+0000 lvl=info msg="Allocated cache and file handles"   database=/data/bsc/node/geth/chaindata cache="2.60 GiB" handles=524,288
t=2022-08-02T01:27:22+0000 lvl=info msg="Opened ancient database"            database=/data/bsc/node/geth/chaindata/ancient readonly=false
t=2022-08-02T01:27:23+0000 lvl=info msg="Initialised chain configuration"    config="{ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Berlin: <nil>, YOLO v3: <nil>, Euler: 18907621, Engine: parlia}"
t=2022-08-02T01:27:23+0000 lvl=info msg="Deep froze chain segment"           blocks=2 elapsed=693.893ms number=19,485,520 hash=0xc19740b2d2548a7706bca67b7758d3ef87377aabb80c83ef8953e187ca9a8e9f
t=2022-08-02T01:29:41+0000 lvl=info msg="Unprotected transactions allowed"
t=2022-08-02T01:29:41+0000 lvl=info msg="Initialising Ethereum protocol"     network=56 dbversion=8
t=2022-08-02T01:30:01+0000 lvl=info msg="Loaded most recent local header"    number=19,575,520 hash=0x7d8ae4d0577fc8e1b81f07f7e8f9033d22bf500e9f41dd277547db9fb59529d8 td=38,920,902 age=2w3d10h
t=2022-08-02T01:30:01+0000 lvl=info msg="Loaded most recent local full block" number=19,575,520 hash=0x7d8ae4d0577fc8e1b81f07f7e8f9033d22bf500e9f41dd277547db9fb59529d8 td=38,920,902 age=2w3d10h
t=2022-08-02T01:30:01+0000 lvl=info msg="Loaded most recent local fast block" number=19,575,520 hash=0x7d8ae4d0577fc8e1b81f07f7e8f9033d22bf500e9f41dd277547db9fb59529d8 td=38,920,902 age=2w3d10h
t=2022-08-02T01:30:01+0000 lvl=info msg="Loaded last fast-sync pivot marker"  number=18,122,881
t=2022-08-02T01:30:01+0000 lvl=info msg="Snapshot loaded"                     diskRoot=0xe3062116c9cb6b96841cb59eeae8fa229d0fc120fcc66c2b4bf78841e3e42f17 root=0x9608aac9e5dc5a545ca2d9b25d480dfb884276ac2b9e0663fdf8647a6249f4fa
t=2022-08-02T01:30:01+0000 lvl=warn msg="Sanitizing invalid txpool reannounce time" provided=0s    updated=1m0s
t=2022-08-02T01:30:01+0000 lvl=info msg="Resuming state snapshot generation"  root=0xe3062116c9cb6b96841cb59eeae8fa229d0fc120fcc66c2b4bf78841e3e42f17 at=0x1d4531c492880e3bbf1757f5916b32a643328e5e3f98e53485541f06918da61b accounts=10,473,569 slots=178,906,273 storage="13.28 GiB" elapsed="121.488碌s"
t=2022-08-02T01:30:01+0000 lvl=warn msg="Sanitizing invalid gasprice oracle price cap" provided=<nil> updated=500,000,000,000
t=2022-08-02T01:30:01+0000 lvl=warn msg="Old unclean shutdowns found"         count=10
t=2022-08-02T01:30:01+0000 lvl=warn msg="Unclean shutdown detected"           booted=2022-07-28T10:27:05+0000 age=4d15h2m
t=2022-08-02T01:30:01+0000 lvl=warn msg="Unclean shutdown detected"           booted=2022-07-28T10:27:45+0000 age=4d15h2m
t=2022-08-02T01:30:01+0000 lvl=warn msg="Unclean shutdown detected"           booted=2022-07-29T02:05:16+0000 age=3d23h24m
t=2022-08-02T01:30:01+0000 lvl=warn msg="Unclean shutdown detected"           booted=2022-07-29T03:33:34+0000 age=3d21h56m
t=2022-08-02T01:30:01+0000 lvl=warn msg="Unclean shutdown detected"           booted=2022-07-29T03:49:31+0000 age=3d21h40m
t=2022-08-02T01:30:01+0000 lvl=warn msg="Unclean shutdown detected"           booted=2022-07-29T06:04:24+0000 age=3d19h25m
t=2022-08-02T01:30:01+0000 lvl=warn msg="Unclean shutdown detected"           booted=2022-07-29T06:05:32+0000 age=3d19h24m
t=2022-08-02T01:30:01+0000 lvl=warn msg="Unclean shutdown detected"           booted=2022-07-29T08:11:42+0000 age=3d17h18m
t=2022-08-02T01:30:01+0000 lvl=warn msg="Unclean shutdown detected"           booted=2022-07-29T09:13:13+0000 age=3d16h16m
t=2022-08-02T01:30:01+0000 lvl=warn msg="Unclean shutdown detected"           booted=2022-08-01T02:34:14+0000 age=22h55m47s
t=2022-08-02T01:30:01+0000 lvl=info msg="Starting peer-to-peer node"          instance=Geth/v1.1.11-de4abf9d-20220613/linux-amd64/go1.18.4
t=2022-08-02T01:30:02+0000 lvl=info msg="New local node record"               seq=2434 id=2f64e09d6e0eba09cac703dc80872fea7912c99177febc31d7a7d8a32387b8a4 ip=127.0.0.1 udp=30311 tcp=30311
t=2022-08-02T01:30:02+0000 lvl=info msg="Started P2P networking"              self=enode://fff04848f5199bdf579dd27cfa2596c020221d1c9893d466183eec598775c85f4e0289583b134d9b4384ea833e634265d00f8aa20437fd0d06d1061d1edc2e77@127.0.0.1:30311
t=2022-08-02T01:30:02+0000 lvl=info msg="IPC endpoint opened"                 url=/data/bsc/node/geth.ipc
t=2022-08-02T01:30:02+0000 lvl=info msg="HTTP server started"                 endpoint=[::]:8545 prefix= cors= vhosts=*
t=2022-08-02T01:30:09+0000 lvl=info msg="Generating state snapshot"           root=0xe3062116c9cb6b96841cb59eeae8fa229d0fc120fcc66c2b4bf78841e3e42f17 in=0x1d4640b1a703d41b0eb3cd6ae8508b043ac0794c135f6144be5ab3564f0095fa at=0x89649fbf404121886ad126866cb001b566eabe0616a8dc24f157667ff018fbd1 accounts=10,475,014 slots=178,910,241 storage="13.28 GiB" elapsed=8.019s      eta=122h10m49.371s
t=2022-08-02T01:30:12+0000 lvl=info msg="Block synchronisation started"
t=2022-08-02T01:30:12+0000 lvl=info msg="New local node record"               seq=2435 id=2f64e09d6e0eba09cac703dc80872fea7912c99177febc31d7a7d8a32387b8a4 ip=113.68.149.111 udp=21789 tcp=30311
t=2022-08-02T01:30:12+0000 lvl=info msg="Looking for peers"                   peercount=2 tried=96 static=36
t=2022-08-02T01:30:17+0000 lvl=info msg="Generating state snapshot"           root=0xe3062116c9cb6b96841cb59eeae8fa229d0fc120fcc66c2b4bf78841e3e42f17 at=0x1d47c83bb1657b9b870c00dd0fe83b49f87e13cfe98aaf62924e6b9fd5a65ebc accounts=10,477,027 slots=178,913,293 storage="13.28 GiB" elapsed=16.122s     eta=100h26m59.389s
t=2022-08-02T01:30:20+0000 lvl=info msg="Downloader queue stats"              receiptTasks=0 blockTasks=565 itemSize="7.69 KiB" throttle=8192
t=2022-08-02T01:30:21+0000 lvl=info msg=------------------------------------------------ LOG15_ERROR=
t=2022-08-02T01:30:21+0000 lvl=info msg=------------------------------------------------ LOG15_ERROR=
t=2022-08-02T01:30:21+0000 lvl=info msg=------------------------------------------------ LOG15_ERROR=
t=2022-08-02T01:30:22+0000 lvl=info msg="Looking for peers"                   peercount=2 tried=23 static=36

Then directly panic, not err info

**Comment by forcodedancing** [comment]
@PPianAIC Are you using v1.1.11, can you try with the latest binary https://github.com/bnb-chain/bsc/releases/tag/v1.1.12 ?

**Comment by PPianAIC** [comment]
OK, I'll try

**Comment by guagualvcha** [comment]
I will close this issue, feel free to open new one if any concern.
