### ISSUE TITLE
new feature `--pruneancient` panics when syncmode is snap

### ISSUE THREAD

**Issue by barryz** [bnb-chain/bsc#1031]
Release notes should notice this message to user who want to upgrade version to v0.1.12.

**Comment by forcodedancing** [comment]
@barryz can you share the panic logs? thanks

**Comment by joeylichang** [comment]
only under ‘--syncmode full’ mode supports --pruneancient flag

For pruneancient, you can check the newest command here: https://github.com/bnb-chain/bsc/releases
