### ISSUE TITLE
Full node broadcasts transactions 2 block late

### ISSUE THREAD

**Issue by halilhaninan** [bnb-chain/bsc#1032]
Hey Folks,  I am running a full node and whenever I send a transaction, it’s always 2 blocks late. How can I resolve the issue? The full node is on AWS and comply with the requirements. Actually, I went the extra mile and get the better hardwire.

Also, how can I find BootstrapNodes so that my node perform better to broadcast my transactions?

**Comment by psdlt** [comment]
hi. x+2 is expected behaviour. nothing that can be done about that.

**Comment by halilhaninan** [comment]
> 

thank you for your answer bro :)

**Comment by tomekozlowski** [comment]
Only Binance can land t+1
