### ISSUE TITLE
flag provided but not defined: -puneancient

### ISSUE THREAD

**Issue by ntminh611** [bnb-chain/bsc#1033]
#### System information

Geth version: `1.1.12-f68965a6`
OS & Version: Linux

#### Expected behaviour
Run ok with argument -puneancient

#### Actual behaviour
flag provided but not defined: -puneancient

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by psdlt** [comment]
@ntminh611 have your tried -p**r**uneancient ?

**Comment by heki-ru** [comment]
It's a typo in docs

**Comment by guagualvcha** [comment]
There is a typo in the docs, fixed.
