### ISSUE TITLE
For new version of geth

### ISSUE THREAD

**Issue by kugimiya530** [bnb-chain/bsc#1035]
if i am using v1.1.11

after updated to v1.1.12 

how to set startup command to be best for us

there is too many new thing , fast node ,verify node, and pruneancient .. etc

**Comment by forcodedancing** [comment]
For fast/verify node, you check this to see whether you want to enable it or not. https://docs.bnbchain.org/docs/BSC-separate-node/

For pruneancient, you can check the command here: https://github.com/bnb-chain/bsc/releases

**Comment by KyloYang888** [comment]
Hi @forcodedancing . Can you help with this? Thanks

https://github.com/bnb-chain/bsc/issues/1039

**Comment by forcodedancing** [comment]
> Hi @forcodedancing . Can you help with this? Thanks
> 
> #1039

sure, commented in the issue
