### ISSUE TITLE
Concern: Validator is running front run bot and not broadcasting transactions

### ISSUE THREAD

**Issue by Chiray1** [bnb-chain/bsc#1036]
Look at the contract https://bscscan.com/address/0xa182c77ff2efa4ed737d1af6c137691f05bcb027. All the transactions aren't being broadcast to the network, instead they are being put in the block directly by the validator which is BNB48 club. 
I don't think validators should abuse validating to make even more profit.

https://bscscan.com/address/0xffffffffff2005d56b30d1a8686171d0afb4584d
another front run bot by them

**Comment by 48ClubIan** [comment]
> 

Hello, I am from BNB48 Club.
These two bot mentioned are not run by us.  Actually we **do not** take exclusively advantage to run arb bot at all.

They might be users of our **Puissant** service, which provides private transaction(s) strictly following these rules:

1. Respect gasPrice priority, i.e. tx with lower gasPrice always gets served later than those with higher one.
2. Discrimination-free transparently public accessible for everyone.
3. All payment occurs on chain as gas fee only, thus all extra profit will be distributed to delegators just as normal profit.

You may check https://docs.bnb48.club/buidl/infrastructure/bsc-validator/ for details.

**Comment by Chiray1** [comment]
Ok sorry, I was unaware of the Puissant service

**Comment by asobazol2** [comment]
The Puissant service doesn't allow gas price below 15 gwei. How to explain frontruns with 5 gwei gas price? Have seen in BNB48 and Avengers blocks.
