### ISSUE TITLE
geth does not work properly after upgrading to v1.1.12

### ISSUE THREAD

**Issue by KyloYang888** [bnb-chain/bsc#1039]
Hi team, geth does not work properly after upgrading to v1.1.12. Can anyone help me? Thanks～

Start command：
geth --config=./config.toml --datadir=/data --cache=18000  --ws  --tries-verify-mode none

Logs：
<img width="1769" alt="image" src="https://user-images.githubusercontent.com/88371425/182292886-be66c031-1e54-4402-be0b-de19c89155ea.png">

Block synchronization no longer continues and the computer gets stuck

**Comment by forcodedancing** [comment]
@KyloYang888 From logs, it was syncing from old blocks (you can see it from `ago`). Before using new version, did it catch up to the latest block?

**Comment by KyloYang888** [comment]
> @KyloYang888 From logs, it was syncing from old blocks (you can see it from `ago`). Before using new version, did it catch up to the latest block?

Hi @forcodedancing . Thanks~ Before the upgrade, the nodes were able to keep up with the latest blocks properly. It was only because v1.1.12 stopped itself a few times that it fell behind the main network.

**Comment by KyloYang888** [comment]
> @KyloYang888 From logs, it was syncing from old blocks (you can see it from `ago`). Before using new version, did it catch up to the latest block?

v1.1.11 is working properly：
Command:  geth --config=./config.toml --datadir=/data --cache=18000 --rpc.allow-unprotected-txs --ws --txlookuplimit=0 --diffsync --persistdiff --pipecommit   --snapshot=false

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/88371425/182432233-b6e289ed-00af-4cf5-811d-30f07242760a.png">

Then upgrade to v1.1.12:
Command: geth --config=./config.toml --datadir=/data --cache=18000  --ws  --tries-verify-mode none 
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/88371425/182432954-cc7ed3f5-8176-4919-b356-ad3c23f76ebb.png">
Block synchronization no longer continues and the computer gets stuck

**Comment by forcodedancing** [comment]
@KyloYang888 Can you remove the flag `--tries-verify-mode none` (`--snapshot=false` if use v1.1.11), then start the node. After running for a while, you can start it with `geth --config=./config.toml --datadir=/data --cache=18000 --ws --tries-verify-mode none` (do not add `--snapshot=false`).

Fastnode depends on snapshot for syncing, so we need to make sure snapshots are generated before turning on it.

**Comment by KyloYang888** [comment]
> @KyloYang888 Can you remove the flag `--tries-verify-mode none` (`--snapshot=false` if use v1.1.11), then start the node. After running for a while, you can start it with `geth --config=./config.toml --datadir=/data --cache=18000 --ws --tries-verify-mode none` (do not add `--snapshot=false`).
> 
> Fastnode depends on snapshot for syncing, so we need to make sure snapshots are generated before turning on `--tries-verify-mode none`.

Hi @forcodedancing . I tried to start the node as you suggested, but it still doesn't work properly.

Version:
<img width="625" alt="image" src="https://user-images.githubusercontent.com/88371425/182515438-e6fad13c-147d-4082-b982-cd44f454d703.png">

Block synchronization no longer continues:
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/88371425/182515489-67a93134-42fd-4ed7-b4dd-fea98a172c30.png">

**Comment by forcodedancing** [comment]
Did it just hang there? Can you change the log level to `debug` or `trace` (in config file) to collect more info, to see it hangs on where? Thanks

**Comment by forcodedancing** [comment]
Hi @KyloYang888 I will close this issue for inactivity of it. It you still have issues, please reopen it or create a new one. Thanks.
