### ISSUE TITLE
Syncmode = fast not working with version 1.1.12-f68965a6

### ISSUE THREAD

**Issue by singhsahilzeeve** [bnb-chain/bsc#1040]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
Geth process to be running without any error.

#### Actual behaviour
Geth process stops with the following error.

> 

invalid value "fast" for flag -syncmode: unknown sync mode "fast", want "full", "snap" or "light"

![Screenshot from 2022-08-03 00-05-55](https://user-images.githubusercontent.com/98091886/182448820-17c2f5c1-4f3c-4465-84e0-8c8e625d37f7.png)
#### Steps to reproduce the behaviour

1. Download latest geth binary 
2. Run the following command
`/geth_linux --syncmode 'fast' `
#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by forcodedancing** [comment]
In release v1.1.12, `--syncemode` `fast` has been removed. Please refer to: https://github.com/bnb-chain/bsc/releases
