### ISSUE TITLE
Using multiple nvme storages for node

### ISSUE THREAD

**Issue by GABASTAR** [bnb-chain/bsc#1041]
Hi guys, if I want to set up a node, do I need to have one 2TB nvme storage, or I can get two with 1TB each and that's will be ok?

**Comment by CNSumi** [comment]
yes, you could use multiple disk with raid, such as btrfs or lvm

```shell
# create raid with btrfs
mkfs.btrfs -m raid0 -d single /dev/nvme0n1 /dev/nvme1n1 ...

mount /dev/nvme0n1 /dst/path

# run node
geth --datadir /dst/path/datadir ...
```

**Comment by GABASTAR** [comment]
Thank you for comment
