### ISSUE TITLE
Linux arm binaries?

### ISSUE THREAD

**Issue by blissend** [bnb-chain/bsc#1043]
I noticed since https://github.com/bnb-chain/bsc/issues/712 we've been including arm binaries for Linux. The latest release doesn't have one anymore. Happy to compile myself but wondering why the change to not include. Is it not going to be included going forward?

**Comment by forcodedancing** [comment]
@blissend No, arm version will not be included. The reason is that cross compiling is removed, and Github does not provide arm machines for us to release arm binaries. If you want arm version, you still can build it on an arm machine.

**Comment by giovannirco** [comment]
This will motivate 3rd party ARM builds that will be used by a lot of people I suppose, specially now with M1 macbooks and this brings a lot of other concerns. Isnt there anything else BSC team can do? Perhaps moving away from github actions since they dont provide all the tools necessary for the CI testing and builds?

**Comment by du5** [comment]
> @blissend No, arm version will not be included. The reason is that cross compiling is removed, and Github does not provide arm machines for us to release arm binaries. If you want arm version, you still can build it on an arm machine.

try this: 

```bash
GOOS=linux GOARCH=arm go build --
```

**Comment by terianil** [comment]
> @blissend No, arm version will not be included. The reason is that cross compiling is removed, and Github does not provide arm machines for us to release arm binaries. If you want arm version, you still can build it on an arm machine.

What is the problem with cross compiling?

**Comment by forcodedancing** [comment]
https://github.com/bnb-chain/bsc/releases Added
