### ISSUE TITLE
failed to pass unit test: bsc/cmd/geth/pruneblock_test.go

### ISSUE THREAD

**Issue by wangtsiao** [bnb-chain/bsc#1046]
I found `maxFeePerGas` and `baseFee` fields are not adopted in bsc when i recently reading reposity. 

so why not remove this `baseFee` check in unit tests?

```
--- FAIL: TestOfflineBlockPrune (0.06s)
panic: max fee per gas less than block base fee: address 0x71562b71999873DB5b286dF957af199Ec94617F7, maxFeePerGas: 0 baseFee: 875000000 [recovered]
        panic: max fee per gas less than block base fee: address 0x71562b71999873DB5b286dF957af199Ec94617F7, maxFeePerGas: 0 baseFee: 875000000
```

**Comment by j75689** [comment]
`maxFeePerGas` and `baseFee` is merged from go-ethereum, if it is to be completely removed, it will require relatively large changes, and there are no plans to do so at the moment

But we can fix this uint-test
