### ISSUE TITLE
node crashed when switch tries-verify-mode

### ISSUE THREAD

**Issue by bitrocks** [bnb-chain/bsc#1050]
#### System information

Geth version: `geth version`
1.1.12
OS & Version: Windows/Linux/OSX
Linux
Commit hash : (if `develop`)
f68965a615fdc8deaeb41e6b18fce2a7c60c2419

#### Expected behaviour
Sync correct

#### Steps to reproduce the behaviour

1. I follow the guide in https://github.com/BNB48Club/bsc-snapshots to set up a node, with command options: `--txlookuplimit=0 --diffsync=true --syncmode=full --tries-verify-mode=none --pruneancient=true --diffblock=5000`
2. with `diffsync` mode, I subscribe the newHeads event, but can't getBlock correctly, `{'code': -32000, 'message': 'header not found'}`,  suspect it as a sync problem, so I want to disable diffsync
3. remove the `--diffsync=true` and `--tries-verify-mode=none`, but node crashed as it show in Backtrace
4. switch back to diffsync mode, but it shows `Fast Sync not finish, can't enable pruneancient mode`
5. remove the `--pruneancient=true`,  get `Fatal: Failed to register the Ethereum service: pruneancient was set, please add pruneancient parameter`

BTW: I want to sync the latest block ASAP(latency matters), which sync mode is preferred in this case?

Update:  I tried to remove `--tries-verify-mode=none` only in step 2, it also crashed with the same msg. Any chance it's the problem of snapshot? It's 575.55 gb, much smaller than the official snapshot.

#### Backtrace

````
t=2022-08-14T14:08:12+0000 lvl=info msg="Set global gas cap" cap=50,000,000
t=2022-08-14T14:08:12+0000 lvl=info msg="Allocated trie memory caches" clean="2.93 GiB" dirty="4.88 GiB"
t=2022-08-14T14:08:12+0000 lvl=info msg="Allocated cache and file handles" database=/data/blockchain/geth/chaindata cache="7.81 GiB" handles=32767
t=2022-08-14T14:08:14+0000 lvl=info msg="Read last offline prune-block start block number" offset=19,914,348
t=2022-08-14T14:08:14+0000 lvl=info msg="Read ancientdb item counts"       items=1040
t=2022-08-14T14:08:14+0000 lvl=info msg="Opened ancientdb with nodata mode" database=/data/blockchain/geth/chaindata/ancient frozen=20,346,025
t=2022-08-14T14:08:14+0000 lvl=info msg="Initialised chain configuration"   config="{ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Berlin: <nil>, YOLO v3: <nil>, CatalystBlock: <nil>, London: <nil>, ArrowGlacier: <nil>, MergeFork:<nil>, Euler: 18907621, Engine: parlia}"
t=2022-08-14T14:08:14+0000 lvl=info msg="Deep froze chain segment"          blocks=9 elapsed="415.139µs" number=20,346,033 hash=0xff74d62dcc5bc79e6b80d2111eeb18df2945dca7b26263d6435d7ed6f3a9be84
t=2022-08-14T14:08:14+0000 lvl=info msg="Unprotected transactions allowed"
t=2022-08-14T14:08:14+0000 lvl=info msg="Initialising Ethereum protocol"    network=56 dbversion=8
t=2022-08-14T14:08:14+0000 lvl=info msg="Loaded most recent local header"   number=20,436,033 hash=0x589a90cab5217c926310d034f32eea59e9c164b4eb8cd93dfdc8ac9d318ba04b td=40,638,633 age=45s
t=2022-08-14T14:08:14+0000 lvl=info msg="Loaded most recent local full block" number=20,436,033 hash=0x589a90cab5217c926310d034f32eea59e9c164b4eb8cd93dfdc8ac9d318ba04b td=40,638,633 age=45s
t=2022-08-14T14:08:14+0000 lvl=info msg="Loaded most recent local fast block" number=20,436,033 hash=0x589a90cab5217c926310d034f32eea59e9c164b4eb8cd93dfdc8ac9d318ba04b td=40,638,633 age=45s
t=2022-08-14T14:08:14+0000 lvl=info msg="Loaded last fast-sync pivot marker"  number=18,122,881
t=2022-08-14T14:08:14+0000 lvl=warn msg="Head state missing, repairing"       number=20,436,033 hash=0x589a90cab5217c926310d034f32eea59e9c164b4eb8cd93dfdc8ac9d318ba04b snaproot=0x2b663aaa467d397b0615839b7616c0b56d401913b80e24276466ff15d65af69c
t=2022-08-14T14:09:18+0000 lvl=eror msg="Missing block in the middle, aiming genesis" number=20,346,033 hash=0xff74d62dcc5bc79e6b80d2111eeb18df2945dca7b26263d6435d7ed6f3a9be84
t=2022-08-14T14:09:18+0000 lvl=info msg="Loaded most recent local header"     number=20,436,033 hash=0x589a90cab5217c926310d034f32eea59e9c164b4eb8cd93dfdc8ac9d318ba04b td=40,638,633 age=1m49s
t=2022-08-14T14:09:18+0000 lvl=info msg="Loaded most recent local full block" number=0          hash=0x0d21840abff46b96c84b2ac9e10e4f5cdaeb5693cb665db62a2f3b02d2d57b5b td=1          age=2y4mo6d
t=2022-08-14T14:09:18+0000 lvl=info msg="Loaded most recent local fast block" number=20,436,033 hash=0x589a90cab5217c926310d034f32eea59e9c164b4eb8cd93dfdc8ac9d318ba04b td=40,638,633 age=1m49s
t=2022-08-14T14:09:18+0000 lvl=info msg="Loaded last fast-sync pivot marker"  number=18,122,881
t=2022-08-14T14:09:18+0000 lvl=warn msg="Enabling snapshot recovery"          chainhead=0 diskbase=20,435,839
t=2022-08-14T14:09:18+0000 lvl=warn msg="Snapshot is not continuous with chain" snaproot=0xbf05cd0e29fc44d7e9dfca0c7180d2a085f5239c1abd315434e7410c3e11afc2 chainroot=0x919fcc7ad870b53db0aa76eb588da06bacb6d230195100699fc928511003b422
t=2022-08-14T14:09:18+0000 lvl=info msg="Snapshot loaded"                       diskRoot=0x2b663aaa467d397b0615839b7616c0b56d401913b80e24276466ff15d65af69c root=0x919fcc7ad870b53db0aa76eb588da06bacb6d230195100699fc928511003b422
t=2022-08-14T14:09:18+0000 lvl=warn msg="Sanitizing invalid txpool reannounce time" provided=0s updated=1m0s
=================node crashed here===============

````

When submitting logs: please submit them as text and not screenshots.

**Comment by bitrocks** [comment]
Use the official snapshot now.

**Comment by 48ClubIan** [comment]
> Use the official snapshot now.

BNB48's snapshot is fine, you just misoperate about how the new `pruneacient` feature and all other flags works.

`pruneacient` only keeps latest blocks, so if you want to query more blocks out of the range, it may fail. `--diffsync` has nothing to do with it.

Another thing you did wrong is remove `--tries-verify-mode=none` while leaving `pruneacient`, it's not supposed.

At last, `pruneacient` doesn't provide backward compatibility cause the db is pruned apparently.

Snapshot from bsc core team didn't enabled pruneacient, that's why it works in your case.

**Comment by gitloverr** [comment]
hi, how did you solve this problem?

My node has this problem now. what should I do?

thank u

**Comment by BrokedTV** [comment]
How was this issues solved? Which flags did you use to get a quick syncing node?

**Comment by duynkt** [comment]
I got same error when luanch from snapshot (get Fatal: Failed to register the Ethereum service: pruneancient was set, please add pruneancient parameter). Run command: geth --config ./config.toml --datadir ./node --diffsync --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0
Anyone help, please. Thanks~

**Comment by jasonyic** [comment]
--txlookuplimit=0 --syncmode=full --tries-verify-mode=none --pruneancient=true --diffblock=5000
