### ISSUE TITLE
JSON RPC getBlockByHash  returns header not found frequently

### ISSUE THREAD

**Issue by bitrocks** [bnb-chain/bsc#1054]
#### System information

Geth version: `geth version`
1.1.12
OS & Version: Windows/Linux/OSX
Linux
Commit hash : (if `develop`)

#### Expected behaviour
I called the getBlockByHash/getBlockByNumber after receiving `newHeads` event immediately, expecting it returns the latest chain head block.

#### Actual behaviour
 It frequently returns `{'code': -32000, 'message': 'header not found'}` error.

#### Steps to reproduce the behaviour
in previous issue https://github.com/bnb-chain/bsc/issues/1050, I encountered the problem, though it was the sync mode. But after I download the official snapshot and start the node with flags: `--txlookuplimit=0 --syncmode=full --rpc.allow-unprotected-txs --pipecommit` , the `header not found` problem still exits.

Does the error mean the block is not persisted while the `newHeads` event already fired? How to make sure the chain head block can be retrieved after receiving `newHeads` ASAP?

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by bnb-tw** [comment]
@bitrocks is this still an issue for you?
