### ISSUE TITLE
rpc service should distinguish between trie not exist and zero value

### ISSUE THREAD

**Issue by zhiqiangxu** [bnb-chain/bsc#1072]
Currently if one tries to fetch any state beyond snapshot, the result will be all zero instead of an explicit trie node error.

This can cause confusion when using tools like cast:

```
cast run -r https://bsc-dataseed1.ninicoin.io 0x12311882bda5d0e61d4baad4f4f72feb7b9ffc2cf80bc576df2ff7d45ab6637c






Executing previous transactions from the block.
Traces:
  [0] 0x0000…0000::fallback() 
    └─ ← ()


Transaction failed.

```

The reason is that balance api returns zero so the tx run is failed as a result of out of gas

**Comment by owen-reorg** [comment]
The public RPC endpoints do not support archive data queries. Try to use 3rd party RPC service which supports this feature, e.g. [Meganode](https://meganode.nodereal.io/).

I tried the exact command with Meganode RPC and it worked.

**Comment by owen-reorg** [comment]
The protocol or RPC spec does not specify how should it return for state beyond snapshot.
In BSC, most node will prune historical blocks and state as they need to reduce disk space usage. There are many modes and commands to do this.
It's hard for the RPC implementation to distinguish trie not exist and zero value.

Thank you for your PR and better idea about this is warmly welcomed.
