### ISSUE TITLE
When trying to prune with pruneancient, the program cannot continue and the error message is wrong

### ISSUE THREAD

**Issue by ottodevs** [bnb-chain/bsc#1074]
Hi, It seems confusing logging this as a warning, when it is causing an unrecoverable error, so why not directly an error?

The message, seems cryptic, I think it can be improved to be human readable? What does it mean "can add pruneancient parameter resolve"???, Interpreting and following the recommended advice does not work, `geth snapshot prune-state` does not accept any `pruneancient` parameter at all...

Apart from that, the message contains a typo "ancinet"

So I guess this logic was added without proper review, at least the message is not telling a valid way to solve the issue...
https://github.com/bnb-chain/bsc/blob/723863ee564e6b10d5c0218aad56aa287bdfa2f9/core/rawdb/database.go#L215

Is there an actual correct way to launch `geth snapshot prune-state` when regular geth execution contains `pruneancient=true` ?

**Comment by ottodevs** [comment]
By reading the code, I see there is no an actual way to prune the node with `pruneancient` enabled, maybe I am missing something or is not needed at all, but those lines of code check if the db is `PruneFreezerType` then throws the error, there doesn't seem to be any alternative logic to bypass this error based on any extra parameter, so it seems the error I quoted it is just misleading the node operator.

**Comment by ottodevs** [comment]
Related to #1034

**Comment by owen-reorg** [comment]
It seems this issue had been fixed by https://github.com/bnb-chain/bsc/pull/1053 and released in [v1.1.13](https://github.com/bnb-chain/bsc/releases/tag/v1.1.13).

Please try with the new binary. 

And we'll optimize the error message to make it more clear in further releases.
