### ISSUE TITLE
what's the max size of a block?

### ISSUE THREAD

**Issue by yasyzb** [bnb-chain/bsc#1075]
I find the max size of transaction is 128KB in source code, but can't find the max size of block, can you tell me?

**Comment by owen-reorg** [comment]
There is no size limit for blocks. Block size is limited by the block gas limit.

Another soft limit is the network packets of P2P protocol, which is 10MB.

references:
- https://github.com/ethereum/go-ethereum/issues/20588
- https://github.com/ethereum/go-ethereum/issues/23920
- https://github.com/ethereum/EIPs/blob/master/EIPS/eip-4488.md

**Comment by yasyzb** [comment]
thank you
