### ISSUE TITLE
Please Provide Right Way to Sync Geth Client with command  After merging network with Beacon

### ISSUE THREAD

**Issue by lokeshratnam09** [bnb-chain/bsc#1085]
My Geth Command To Sync - 

./geth   --syncmode snap  --http  --datadir "/home/ubuntu/MainNet_14.09.2022" --http.api eth,net,db,web3,debug,miner,admin,personal,engine,txpool  --authrpc.jwtsecret /home/ubuntu/ethereum/prysm/jwt.hex --allow-insecure-unlock 

My Beacon Command To Sync - 

./prysm.sh beacon-chain  --checkpoint-sync-url https://beaconstate.info/ --datadir "/home/ubuntu/MainNetttt_15.09.2022" --accept-terms-of-use  --execution-endpoint=http://localhost:8551/ --jwt-secret=/home/ubuntu/ethereum/prysm/jwt.hex

Is this right way to sync Geth Node because i am not using any syncmode because after merging with beacon node light mode does not exist and snap mode shows stealing error after importing all blocks and full mode  is very slow.

So please help any one  with command who can successfully synced their geth node after merging with beacon node .
Please help. i am struggling to sync my node

**Comment by KeefeL** [comment]
BSC does not need to sync with the beacon node.
