### ISSUE TITLE
Scam report

### ISSUE THREAD

**Issue by Alarrab9** [bnb-chain/bsc#1086]
Hi support team
Plz i want to report scam coin 
The team of this project stole it from my wallet , the assist value was more than $450000 I store it for 330 day's.. and when i talked to the admin he sent me alink to give him the seeds of the wallet .. clearly he want to stole the wallet ,only stopped Will give him his wallet seeds , so this is my broplem and besid all of that i have the conversation proves..
This is the name of the coin and contract through BSC chain: WEIUP  0xd0f08610b9Bb66395b0d2679F749bBE8A12cC0BB
Also the hash of the transaction in my wallet: 0xf1d9a76b5b07d8bc372a2567803694387b63426467a2fa38659340d164d85efd

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by KeefeL** [comment]
Could you report this to the BNB chain's telegram, I will gonna to close this issue here.
