### ISSUE TITLE
A lot of tx will be submitted at the same time, and then many cannot be packaged. Is this normal

### ISSUE THREAD

**Issue by E0001** [bnb-chain/bsc#1088]
A lot of tx will be submitted at the same time, and then many cannot be packaged. Is this normal ，How can I solve this problem？

**Comment by guagualvcha** [comment]
hi, @E0001  can you give more details about how you find `A lot of tx will be submitted at the same time` and how it impact your service?  In general, to avoid unready transaction to accumulated in tx pool, you can try adjust the following settings in config.toml:

```
[Eth.TxPool]
Locals = []
AccountSlots = 512
GlobalSlots = 10000
AccountQueue = 256
GlobalQueue = 5000
```

**Comment by E0001** [comment]
> 你好， @E0001你能提供更多关于你如何找到的细节吗 `A lot of tx will be submitted at the same time`以及它如何影响您的服务？ 一般来说，为了避免未准备好的交易累积在 tx 池中，您可以尝试调整 config.toml 中的以下设置：
> 
> ```
> [Eth.TxPool]
> Locals = []
> AccountSlots = 512
> GlobalSlots = 10000
> AccountQueue = 256
> GlobalQueue = 5000
> ```

Let me check. Thank you

**Comment by E0001** [comment]
> 你好， @E0001你能提供更多关于你如何找到的细节吗 `A lot of tx will be submitted at the same time`以及它如何影响您的服务？ 一般来说，为了避免未准备好的交易累积在 tx 池中，您可以尝试调整 config.toml 中的以下设置：
> 
> ```
> [Eth.TxPool]
> Locals = []
> AccountSlots = 512
> GlobalSlots = 10000
> AccountQueue = 256
> GlobalQueue = 5000
> ```

Is there any document about the configuration file? I don't know what many configurations mean

**Comment by du5** [comment]
> > 你好， @E0001你能提供更多关于你如何找到的细节吗 `A lot of tx will be submitted at the same time`以及它如何影响您的服务？ 一般来说，为了避免未准备好的交易累积在 tx 池中，您可以尝试调整 config.toml 中的以下设置：
> > ```
> > [Eth.TxPool]
> > Locals = []
> > AccountSlots = 512
> > GlobalSlots = 10000
> > AccountQueue = 256
> > GlobalQueue = 5000
> > ```
> 
> Is there any document about the configuration file? I don't know what many configurations mean


```bash 
> geth --help
TRANSACTION POOL OPTIONS:
  --txpool.locals value               Comma separated accounts to treat as locals (no flush, priority inclusion)
  --txpool.nolocals                   Disables price exemptions for locally submitted transactions
  --txpool.journal value              Disk journal for local transaction to survive node restarts (default: "transactions.rlp")
  --txpool.rejournal value            Time interval to regenerate the local transaction journal (default: 1h0m0s)
  --txpool.pricelimit value           Minimum gas price limit to enforce for acceptance into the pool (default: 1)
  --txpool.pricebump value            Price bump percentage to replace an already existing transaction (default: 10)
  --txpool.accountslots value         Minimum number of executable transaction slots guaranteed per account (default: 16)
  --txpool.globalslots value          Maximum number of executable transaction slots for all accounts (default: 5120)
  --txpool.accountqueue value         Maximum number of non-executable transaction slots permitted per account (default: 64)
  --txpool.globalqueue value          Maximum number of non-executable transaction slots for all accounts (default: 1024)
  --txpool.lifetime value             Maximum amount of time non-executable transaction are queued (default: 3h0m0s)
  --txpool.reannouncetime value       Duration for announcing local pending transactions again (default = 10 years, minimum = 1 minute) (default: 87600h0m0s)
  
```
