### ISSUE TITLE
Is there a field to specify a block can not be rollback?

### ISSUE THREAD

**Issue by yasyzb** [bnb-chain/bsc#1096]
Is there a field to specify a block can not be rollback?
ETH2 can use "finalized" to refer to the latest finalized block.

**Comment by guagualvcha** [comment]
Hi, for BSC right now it is probabilistic finality, we suggest 11 blocks.

And we will launch BSC fast finality by end of 2022, it is similar to ETH2 Casper FFG finality, until then, the finality blocks will be 2-3 blocks in most cases.

**Comment by yasyzb** [comment]
thanks
