### ISSUE TITLE
VerifyNodes in p2p

### ISSUE THREAD

**Issue by wangtsiao** [bnb-chain/bsc#1102]
I  saw below code piece from p2p/server.go. Since they didn't appear in go-ethereum, I want to understand what role `VerifyNodes` plays in binance chain network. What's the difference between `VerifyNodes` and `TrustNodes` or `StaticNodes`?
```go
// Verify nodes are used as pre-configured connections which are always
// maintained and re-connected on disconnects.
VerifyNodes []*enode.Node
```

**Comment by guagualvcha** [comment]
Please refer to this document: https://docs.bnbchain.org/docs/BSC-separate-node
