### ISSUE TITLE
WebSocket connection is systematically terminated. Starting from version 1.1.12

### ISSUE THREAD

**Issue by jsdavid** [bnb-chain/bsc#1105]
#### System information

Geth version: `v1.1.14`
OS & Version: `Debian-1011-buster-64-minimal`

#### Expected behaviour
WebSocket connection should never drop. In version `v1.1.11`, the connection never dropped. I've been seeing this issue for a long time now. Please pay attention to this.

#### Actual behaviour
Starting from version `v1.1.12`, the WebSocket connection is systematically terminated

#### Steps to reproduce the behaviour

Run the following code through PM2 (preferably multiple processes), and watch the uptime. The connection may not break immediately, but after a long time.
```
import { ethers } from 'ethers'

const provider = new ethers.providers.WebSocketProvider('')
provider._websocket.once('open', () => console.log('Connection opened'))
provider._websocket.once('close', () => {
  console.log('Connection closed')
  setTimeout(() => process.exit(1), 0)
})
```
I'll attach a skin where 4 processes were launched at the same time. But in some processes, the connection was broken several times. (look at the uptime)

![](https://i.postimg.cc/QMTT6ZJc/ws.png)

**Comment by haliliceylan** [comment]
its also happening in ipc too

**Comment by j75689** [comment]
thanks, the team will dig into this issue

**Comment by bnb-tw** [comment]
@alexlucaci can you take a look?

**Comment by alexlucaci** [comment]
Hello,

I am not able to replicate the issue, I am now running a local node and spawned 7 different instance of your node script that are connected to the node for 22 hours without any reconnects.

<img width="928" alt="image" src="https://github.com/bnb-chain/bsc/assets/118174763/575428da-29a2-4aed-895d-79d0c7ce643e">

**Comment by alexlucaci** [comment]
> this error no longer persists on my side.

did you update to a newer version?

**Comment by bnb-tw** [comment]
closing, looks to be resolved
