### ISSUE TITLE
bsc node fast synchronization failed

### ISSUE THREAD

**Issue by maef2018** [bnb-chain/bsc#1116]
#### System information

Geth version: v1.1.3
OS & Version: Ubuntu 20.04.5 LTS
AWS:m5d.4xlarge   16vCPU 64Gib 16 cores,  and 2.5T ssd disk

#### Expected behaviour

currentBlock == highestBlock

curl -s -X --location --request POST 'localhost:8545/' --header 'Content-Type:application/json' --data-raw '{"jsonrpc":"2.0", "method":"eth_syncing", "params":[],"id":1}'
{"jsonrpc":"2.0","id":1,"result":{"currentBlock":"0x14f1d5b","healedBytecodeBytes":"0x4c7d2ff1","healedBytecodes":"0x240be","healedTrienodeBytes":"0xfc3e26953","healedTrienodes":"0x197a33ba","healingBytecode":"0x0","healingTrienodes":"0x7d1","highestBlock":"0x14f1da9","startingBlock":"0xd34146","syncedAccountBytes":"0x5947d8197","syncedAccounts":"0x6191991","syncedBytecodeBytes":"0x34d088db4","syncedBytecodes":"0x1979e1","syncedStorage":"0x81bf620e","syncedStorageBytes":"0x6d63e8a178”}}

#### Actual behaviour

My problem is: the bsc fast node I deployed has been synchronized for more than ten days, and I still cannot get the latest block data. The machine I use to deploy the node is configured with 16 cores, 64G memory, and 2.5T ssd disk。

currentBlock has always been more than a hundred less than highestBlock, and will never catch up

echo $((`curl -s -X --location --request POST 'localhost:8545/' --header 'Content-Type:application/json' --data-raw '{"jsonrpc":"2.0", "method":"eth_syncing", "params":[],"id":1}' |jq .result.currentBlock |awk -F'"' '{print $(NF-1)}'`))
21962075

echo $((`curl -s -X --location --request POST 'localhost:8545/' --header 'Content-Type:application/json' --data-raw '{"jsonrpc":"2.0", "method":"eth_syncing", "params":[],"id":1}' |jq .result.highestBlock |awk -F'"' '{print $(NF-1)}'`))
21962153

du -sh data
1.6T    data

curl -s -X --location --request POST 'localhost:8545/' --header 'Content-Type:application/json' --data-raw '{"jsonrpc":"2.0", "method":"eth_syncing", "params":[],"id":1}'
{"jsonrpc":"2.0","id":1,"result":{"currentBlock":"0x14f1d5b","healedBytecodeBytes":"0x4c7d2ff1","healedBytecodes":"0x240be","healedTrienodeBytes":"0xfc3e26953","healedTrienodes":"0x197a33ba","healingBytecode":"0x0","healingTrienodes":"0x7d1","highestBlock":"0x14f1da9","startingBlock":"0xd34146","syncedAccountBytes":"0x5947d8197","syncedAccounts":"0x6191991","syncedBytecodeBytes":"0x34d088db4","syncedBytecodes":"0x1979e1","syncedStorage":"0x81bf620e","syncedStorageBytes":"0x6d63e8a178”}}

My deployment reference documentation is：https://docs.bnbchain.org/docs/BSC-fast-node

##My steps are as follows：

wget   $(curl -s https://api.github.com/repos/bnb-chain/bsc/releases/latest |grep browser_ |grep geth_linux |cut -d\" -f4)

wget   $(curl -s https://api.github.com/repos/bnb-chain/bsc/releases/latest |grep browser_ |grep mainnet |cut -d\" -f4)
unzip mainnet.zip
mkdir config
mv config.toml genesis.json ./config/

vim config.toml
HTTPHost = "0.0.0.0"

/data/geth --datadir data init /data/config/genesis.json

INFO [09-25|07:44:52.276] Maximum peer count                       ETH=50 LES=0 total=50
INFO [09-25|07:44:52.276] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [09-25|07:44:52.277] Set global gas cap                       cap=50,000,000
INFO [09-25|07:44:52.277] Allocated cache and file handles         database=/data/data/geth/chaindata cache=16.00MiB handles=16
INFO [09-25|07:44:52.282] Writing custom genesis block
INFO [09-25|07:44:52.284] Persisted trie from memory database      nodes=15 size=2.32KiB time="79.322_s" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [09-25|07:44:52.284] Successfully wrote genesis state         database=chaindata                 hash=0d2184..d57b5b
INFO [09-25|07:44:52.284] Allocated cache and file handles         database=/data/data/geth/lightchaindata cache=16.00MiB handles=16
INFO [09-25|07:44:52.290] Writing custom genesis block
INFO [09-25|07:44:52.290] Persisted trie from memory database      nodes=15 size=2.32KiB time="45.696_s" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [09-25|07:44:52.290] Successfully wrote genesis state         database=lightchaindata                 hash=0d2184..d57b5b

start node：
/data/geth --tries-verify-mode none --config /data/config/config.toml --datadir /data/data  --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0

The log information is as follows:
t=2022-10-07T07:20:34+0000 lvl=warn msg="Served eth_coinbase"                    conn=195.123.222.16:52506 reqid=1                         t="12.325µs"               err="etherbase must be explicitly specified" X-Forwarded-For=nil
t=2022-10-07T07:20:34+0000 lvl=warn msg="Served eth_coinbase"                    conn=195.123.222.16:52506 reqid=1                         duration="11.508µs"  err="etherbase must be explicitly specified"
t=2022-10-07T07:20:34+0000 lvl=warn msg="Served eth_coinbase"                    conn=195.123.222.16:56140 reqid=1                         t="14.67µs"                err="etherbase must be explicitly specified" X-Forwarded-For=nil
t=2022-10-07T07:20:34+0000 lvl=warn msg="Served eth_coinbase"                    conn=195.123.222.16:56140 reqid=1                         duration="13.898µs"  err="etherbase must be explicitly specified"
t=2022-10-07T07:20:36+0000 lvl=info msg="State heal in progress"                 accounts=35,866,730@1.85GiB    slots=175,977,839@12.48GiB    codes=147,646@1.20GiB    nodes=427,381,392@63.06GiB pending=33708
t=2022-10-07T07:20:37+0000 lvl=warn msg="Served eth_coinbase"                    conn=195.123.222.16:49056 reqid=1                         t="18.06µs"                err="etherbase must be explicitly specified" X-Forwarded-For=nil
t=2022-10-07T07:20:37+0000 lvl=warn msg="Served eth_coinbase"                    conn=195.123.222.16:49056 reqid=1                         duration="17.05µs"   err="etherbase must be explicitly specified"
t=2022-10-07T07:20:44+0000 lvl=info msg="State heal in progress"                 accounts=35,866,730@1.85GiB    slots=175,979,880@12.48GiB    codes=147,646@1.20GiB    nodes=427,384,404@63.06GiB pending=33232
t=2022-10-07T07:20:52+0000 lvl=info msg="State heal in progress"                 accounts=35,866,730@1.85GiB    slots=175,982,031@12.48GiB    codes=147,646@1.20GiB    nodes=427,387,546@63.06GiB pending=33262
t=2022-10-07T07:21:01+0000 lvl=info msg="State heal in progress"                 accounts=35,866,730@1.85GiB    slots=175,984,223@12.48GiB    codes=147,646@1.20GiB    nodes=427,390,640@63.06GiB pending=32737
t=2022-10-07T07:21:09+0000 lvl=info msg="State heal in progress"                 accounts=35,866,730@1.85GiB    slots=175,986,292@12.48GiB    codes=147,646@1.20GiB    nodes=427,393,616@63.06GiB pending=32842

**Comment by j75689** [comment]
I suggest you download [snapshot](https://github.com/BNB48Club/bsc-snapshots)

If your machine is not powerful, syncing from the genesis block will take you a long time

**Comment by maef2018** [comment]
successed

**Comment by Skim45** [comment]
@maef2018,

How did you solve it?
