### ISSUE TITLE
bsc crosschain convert malfunctioning

### ISSUE THREAD

**Issue by s-mohammad-dabir** [bnb-chain/bsc#1118]
I made a cross-chain convert from the BSC network to the bnb-chain. My bnb from the BSC address was deducted and the balance on the bnb-chain address has not increased. I think this is because of this last nanofork merge.

Would you please help?
Here is the transaction:
https://bscscan.com/tx/0x58c058d2447bb4fc8405aeab522ebb9a844381b28037b3c3e54672c3e1b38140
The transaction is not reverted and it is successful. 

My bnb-chain address:
bnb1u2e98arlu4smjm68vhwa03xv7jd5mvqc8586ms

As you can see there is no oracle claim transaction initiated after my conversion.
<img width="366" alt="tx" src="https://user-images.githubusercontent.com/20028160/194550212-b76d2e39-c2d1-4226-82f7-ef8dedfcf22a.png">

**Comment by KaffinPX** [comment]
Your funds are stuck until next hard fork.

**Comment by dgdeivid** [comment]
v1.1.15:

All cross chain transfers (Beacon Chain <-> Smart Chain) will be stopped. If you really do cross chain transfers, your tokens will be frozen and released after the resume of relayers. If you do want to transfer your tokens to any side (Beacon Chain or Smart Chain), you can utilise central exchanges.

**Comment by j75689** [comment]
Hello, cross-chain packets will be restored at block height 22,107,423. The current block generation rate predicts this will happen around 8:00AM (UTC) on October 12, 2022.

Please remind to upgrade your node to v1.1.16, thanks
https://github.com/bnb-chain/bsc/releases/tag/v1.1.16
