### ISSUE TITLE
error: no suitable peers available

### ISSUE THREAD

**Issue by osizadmin** [bnb-chain/bsc#1122]
We got this issue in since morning.
err="getDeleteStateObject (b02a90bcb447736bde2cbca4102d49dc6f727f7b) error: no suitable peers available

net.peerCount;
83

Kindly check and advise us.

**Comment by guagualvcha** [comment]
I believe you are running a light client, however many p2p nodes are running in fast node. Please check what is a fast node here: https://docs.bnbchain.org/docs/BSC-separate-node

So unless your light node connect to a ndoe with full MTP data, it can response properly.

**Comment by j75689** [comment]
I'll close this question first, feel free to reopen it if you have any questions, thanks
