### ISSUE TITLE
"blacklist account detected" with Synchronisation failed

### ISSUE THREAD

**Issue by daron4ever** [bnb-chain/bsc#1131]
#### System information

Geth version: 1.1.15
OS & Version: Linux
Commit hash : (if `develop`)

Node suddenly stopped and had the following errors:

t=2022-10-12T10:10:42+0000 lvl=info msg="New local node record"               seq=17 id=8cf509b120cbe2ff48376e550743a72cd7aa56bb4fd62930128bd31bef2179c9 ip=178.63.94.52 udp=30311 tcp=30311
t=2022-10-12T10:10:49+0000 lvl=info msg="Block synchronisation started"
t=2022-10-12T10:11:02+0000 lvl=warn msg="Snapshot extension registration failed" peer=2b236036 err="peer connected on snap without compatible eth support"
t=2022-10-12T10:11:04+0000 lvl=warn msg="Snapshot extension registration failed" peer=2b87dc19 err="peer connected on snap without compatible eth support"
t=2022-10-12T10:11:30+0000 lvl=warn msg="Snapshot extension registration failed" peer=089e2e46 err="peer connected on snap without compatible eth support"
t=2022-10-12T10:11:35+0000 lvl=info msg="Imported new chain segment"             blocks=1 txs=161 mgas=18.981 elapsed=332.640ms mgasps=57.060 number=22,107,423 hash=0x34c81d5ea5128cc8659973dff27243dd6725b99b741ab0bb57230ac792eec516 age=1h14m37s dirty="0.00 B"
t=2022-10-12T10:11:35+0000 lvl=eror msg="Invalid merkle root"                    remote=0x780101d8836c97249fde97563f4208a10a8193d018c0e054abf9e18828531027 local=0x75b98a5bfc6c94c6bd0fc61bc523ee7e4831a7708b1c40e518ebe6f922f719b4
t=2022-10-12T10:11:35+0000 lvl=warn msg="current block verified failed, rewind to its parent" height=22,107,423 hash=0x34c81d5ea5128cc8659973dff27243dd6725b99b741ab0bb57230ac792eec516
t=2022-10-12T10:11:35+0000 lvl=info msg="Skip duplicated bad block"              number=22,107,423 hash=0x34c81d5ea5128cc8659973dff27243dd6725b99b741ab0bb57230ac792eec516
t=2022-10-12T10:11:35+0000 lvl=eror msg="\n########## BAD BLOCK #########\nChain config: {ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Berlin: <nil>, YOLO v3: <nil>, CatalystBlock: <nil>, London: <nil>, ArrowGlacier: <nil>, MergeFork:<nil>, Euler: 18907621, Gibbs: <nil>, Nano: 21962149, Engine: parlia}\n\nNumber: 22107423\nHash: 0x34c81d5ea5128cc8659973dff27243dd6725b99b741ab0bb57230ac792eec516\n\n\nError: state root verification failed\n##############################\n"
t=2022-10-12T10:11:35+0000 lvl=warn msg="Rewinding blockchain"                   target=22,107,422
t=2022-10-12T10:11:35+0000 lvl=info msg="Loaded most recent local header"        number=22,107,422 hash=0xb50234729d2003a501d4a6ef0f59a38c01e53d1d1f4083bb7d7d960dfafeaad3 td=43,961,966 age=1h14m40s
t=2022-10-12T10:11:35+0000 lvl=info msg="Loaded most recent local full block"    number=22,107,422 hash=0xb50234729d2003a501d4a6ef0f59a38c01e53d1d1f4083bb7d7d960dfafeaad3 td=43,961,966 age=1h14m40s
t=2022-10-12T10:11:35+0000 lvl=info msg="Loaded most recent local fast block"    number=22,107,422 hash=0xb50234729d2003a501d4a6ef0f59a38c01e53d1d1f4083bb7d7d960dfafeaad3 td=43,961,966 age=1h14m40s
t=2022-10-12T10:11:35+0000 lvl=info msg="Loaded last fast-sync pivot marker"     number=18,122,881
t=2022-10-12T10:11:35+0000 lvl=eror msg="state verification failed"              err="invalid merkle root (remote: 780101d8836c97249fde97563f4208a10a8193d018c0e054abf9e18828531027 local: 75b98a5bfc6c94c6bd0fc61bc523ee7e4831a7708b1c40e518ebe6f922f719b4)"
t=2022-10-12T10:11:52+0000 lvl=eror msg="blacklist account detected"             account=0x489A8756C18C0b8B24EC2a2b9FF3D4d447F79BEc tx=0x93e7d8969598d838a9583e81f40db8f67437a7c596d84659380a661f9a3371d8
t=2022-10-12T10:12:14+0000 lvl=warn msg="Snapshot extension registration failed" peer=d348bda2 err="peer connected on snap without compatible eth support"
t=2022-10-12T10:12:17+0000 lvl=eror msg="Expired request does not exist"         peer=d435c07f8be2eed89c4af91612571b9124b217f90ca2906959489cc5790b52b5
t=2022-10-12T10:12:39+0000 lvl=eror msg="Expired request does not exist"         peer=c3cef4d4a57a8967b4fba04ae47107382fcc38cdad60d8b6a613f7dd3150396a
t=2022-10-12T10:12:42+0000 lvl=warn msg="Snapshot extension registration failed" peer=eec7c316 err="peer connected on snap without compatible eth support"
t=2022-10-12T10:12:43+0000 lvl=eror msg="Expired request does not exist"         peer=c4d6e1bbd6eb6757da6adce39c9b4db1747e05a1f96d90ba3dbe5e7ee3bad188
t=2022-10-12T10:12:43+0000 lvl=eror msg="Pending request exists for joining peer" peer=15187dbb
t=2022-10-12T10:12:43+0000 lvl=eror msg="Pending request exists for joining peer" peer=0762a94d
t=2022-10-12T10:12:43+0000 lvl=eror msg="Pending request exists for joining peer" peer=17628a40
t=2022-10-12T10:12:43+0000 lvl=eror msg="Pending request exists for joining peer" peer=174e3677
t=2022-10-12T10:12:43+0000 lvl=eror msg="Pending request exists for joining peer" peer=8526c808
t=2022-10-12T10:12:43+0000 lvl=eror msg="Pending request exists for joining peer" peer=d591ca7e
t=2022-10-12T10:12:43+0000 lvl=eror msg="Pending request exists for joining peer" peer=d581e741
t=2022-10-12T10:12:43+0000 lvl=eror msg="Pending request exists for joining peer" peer=c4749fe8
t=2022-10-12T10:12:43+0000 lvl=eror msg="Pending request exists for joining peer" peer=c4fe776b
t=2022-10-12T10:12:43+0000 lvl=eror msg="Pending request exists for joining peer" peer=c4efc946
t=2022-10-12T10:12:43+0000 lvl=eror msg="Pending request exists for joining peer" peer=6fae11f2
t=2022-10-12T10:12:43+0000 lvl=eror msg="Expired request does not exist"         peer=c3cef4d4a57a8967b4fba04ae47107382fcc38cdad60d8b6a613f7dd3150396a
t=2022-10-12T10:12:43+0000 lvl=eror msg="Pending request exists for joining peer" peer=ee27fb1e
t=2022-10-12T10:12:43+0000 lvl=eror msg="Pending request exists for joining peer" peer=ee1afd18
t=2022-10-12T10:12:43+0000 lvl=eror msg="Pending request exists for joining peer" peer=ef16f0f2
t=2022-10-12T10:12:43+0000 lvl=eror msg="Pending request exists for joining peer" peer=ee2224a1
t=2022-10-12T10:12:45+0000 lvl=info msg="Imported new chain segment"             blocks=1 txs=161 mgas=18.981 elapsed=29.487ms  mgasps=643.677 number=22,107,423 hash=0x34c81d5ea5128cc8659973dff27243dd6725b99b741ab0bb57230ac792eec516 age=1h15m47s dirty="0.00 B"
t=2022-10-12T10:12:45+0000 lvl=eror msg="Invalid merkle root"                    remote=0x780101d8836c97249fde97563f4208a10a8193d018c0e054abf9e18828531027 local=0x75b98a5bfc6c94c6bd0fc61bc523ee7e4831a7708b1c40e518ebe6f922f719b4
t=2022-10-12T10:12:45+0000 lvl=warn msg="current block verified failed, rewind to its parent" height=22,107,423 hash=0x34c81d5ea5128cc8659973dff27243dd6725b99b741ab0bb57230ac792eec516
t=2022-10-12T10:12:45+0000 lvl=info msg="Skip duplicated bad block"              number=22,107,423 hash=0x34c81d5ea5128cc8659973dff27243dd6725b99b741ab0bb57230ac792eec516
t=2022-10-12T10:12:45+0000 lvl=eror msg="\n########## BAD BLOCK #########\nChain config: {ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Berlin: <nil>, YOLO v3: <nil>, CatalystBlock: <nil>, London: <nil>, ArrowGlacier: <nil>, MergeFork:<nil>, Euler: 18907621, Gibbs: <nil>, Nano: 21962149, Engine: parlia}\n\nNumber: 22107423\nHash: 0x34c81d5ea5128cc8659973dff27243dd6725b99b741ab0bb57230ac792eec516\n\n\nError: state root verification failed\n##############################\n"
t=2022-10-12T10:12:45+0000 lvl=warn msg="Rewinding blockchain"                   target=22,107,422
t=2022-10-12T10:12:45+0000 lvl=info msg="Loaded most recent local header"        number=22,107,422 hash=0xb50234729d2003a501d4a6ef0f59a38c01e53d1d1f4083bb7d7d960dfafeaad3 td=43,961,966 age=1h15m50s
t=2022-10-12T10:12:45+0000 lvl=info msg="Loaded most recent local full block"    number=22,107,422 hash=0xb50234729d2003a501d4a6ef0f59a38c01e53d1d1f4083bb7d7d960dfafeaad3 td=43,961,966 age=1h15m50s
t=2022-10-12T10:12:45+0000 lvl=info msg="Loaded most recent local fast block"    number=22,107,422 hash=0xb50234729d2003a501d4a6ef0f59a38c01e53d1d1f4083bb7d7d960dfafeaad3 td=43,961,966 age=1h15m50s
t=2022-10-12T10:12:45+0000 lvl=info msg="Loaded last fast-sync pivot marker"     number=18,122,881
t=2022-10-12T10:12:45+0000 lvl=eror msg="state verification failed"              err="invalid merkle root (remote: 780101d8836c97249fde97563f4208a10a8193d018c0e054abf9e18828531027 local: 75b98a5bfc6c94c6bd0fc61bc523ee7e4831a7708b1c40e518ebe6f922f719b4)"
t=2022-10-12T10:12:59+0000 lvl=warn msg="Snapshot extension registration failed" peer=e118b10a err="peer connected on snap without compatible eth support"
t=2022-10-12T10:13:00+0000 lvl=eror msg="Expired request does not exist"         peer=15187dbb872c15317b317739c546d79f8551678804597d84f6bb8d134f8c76d8
t=2022-10-12T10:13:03+0000 lvl=eror msg="Expired request does not exist"         peer=c3e8b035d655e1bae8e623f09f189ff20f08f7159830936c90d1daffe50df4b3
t=2022-10-12T10:13:03+0000 lvl=eror msg="Expired request does not exist"         peer=c4efc94622f68bddf79031b03439178660a7c18ab1cf91ecb9e905cf40dc8698
t=2022-10-12T10:13:05+0000 lvl=eror msg="Expired request does not exist"         peer=9c2c9a4028eae5cf1fa390a267d57017f7b7de25d490eb265d33c1f2dc16df49
t=2022-10-12T10:13:27+0000 lvl=eror msg="Expired request does not exist"         peer=ef16f0f2302396376cfb26317a0a148c5ee7261d6a3d947bfd8b8dda2c88cb9a
t=2022-10-12T10:13:27+0000 lvl=eror msg="Expired request does not exist"         peer=6fae11f2e6d97c5d7f32d370d5a5336a308feceb37a7e62c2a324c661562753f
t=2022-10-12T10:13:27+0000 lvl=eror msg="Expired request does not exist"         peer=6fae11f2e6d97c5d7f32d370d5a5336a308feceb37a7e62c2a324c661562753f
t=2022-10-12T10:13:39+0000 lvl=eror msg="Expired request does not exist"         peer=044171212956b65d07b0f7277532b5ac1c1a6593796b88eab3c52eada020a60d
t=2022-10-12T10:13:39+0000 lvl=eror msg="Pending request exists for joining peer" peer=16ea9b69
t=2022-10-12T10:13:39+0000 lvl=eror msg="Pending request exists for joining peer" peer=16d3b3ae
t=2022-10-12T10:13:50+0000 lvl=warn msg="Snapshot extension registration failed" peer=7bcee16b err="peer connected on snap without compatible eth support"
t=2022-10-12T10:13:51+0000 lvl=eror msg="blacklist account detected"             account=0x489A8756C18C0b8B24EC2a2b9FF3D4d447F79BEc tx=0x1fddde4e48a8aab33534c909847868a41a12af51ba63be3399469077ef4f2e7e
t=2022-10-12T10:13:52+0000 lvl=eror msg="blacklist account detected"             account=0x489A8756C18C0b8B24EC2a2b9FF3D4d447F79BEc tx=0x2ef32945aed8ccc66a8f3166d52e3463aa3587d7f6a3ac4e6713b3cb25944c2e
t

**Comment by reg2005** [comment]
You must upgrade to 1.1.16

**Comment by j75689** [comment]
please upgrade to v1.1.16, https://github.com/bnb-chain/bsc/releases/tag/v1.1.16
