### ISSUE TITLE
How to specify the number of blocks to maintain for the --pruneancient flag?

### ISSUE THREAD

**Issue by litebarb** [bnb-chain/bsc#1142]
How do we specify the number of blocks we want to maintain for the --pruneancient flag? Is diffblock the command to use with this? For example, I would like the realtime pruning command to only prune blocks that are older than 2 weeks. However, when I used --diffblock 403200 (around 2 weeks worth of data), I can only query up to ~90000 blocks from current highest block. Any block receipts older than 90000 blocks gets deleted in realtime, and returns a _NULL_ when I query for block receipts.

I am using BNB48Club snapshot with the following commands:

```
--rpc.allow-unprotected-txs --txlookuplimit 0 --diffsync=true --tries-verify-mode=none --pruneancient=true --diffblock=403200
```

**Comment by cosinlink** [comment]
`--diffblock` is not related with `--pruneancient`.  If this flag `--pruneancient` is used, only the last `90,000` blocks can be saved

**Comment by Johnny0song** [comment]
在Binance Smart Chain（BSC）中，--diffblock是一个用于命令行的参数，它用于指定BSC节点与其他节点的块高度差异。当您运行一个BSC节点并同步到最新块时，节点需要从其他节点获取缺失的块数据。--diffblock参数允许您设置节点开始请求缺失块数据的块高度差异。例如，如果您将--diffblock设置为1000，则节点将从其他节点请求比当前块低1000个块的数据。这可以帮助您更快地同步到当前块。

**Comment by Johnny0song** [comment]
> How do we specify the number of blocks we want to maintain for the --pruneancient flag? Is diffblock the command to use with this? For example, I would like the realtime pruning command to only prune blocks that are older than 2 weeks. However, when I used --diffblock 403200 (around 2 weeks worth of data), I can only query up to ~90000 blocks from current highest block. Any block receipts older than 90000 blocks gets deleted in realtime, and returns a _NULL_ when I query for block receipts.
> 
> I am using BNB48Club snapshot with the following commands:
> 
> ```
> --rpc.allow-unprotected-txs --txlookuplimit 0 --diffsync=true --tries-verify-mode=none --pruneancient=true --diffblock=403200
> ```

我也有这个疑问，怎么来配置只保留最近一周或两周的疑问，你找到参数配置了么

**Comment by hoangthanhtung1910** [comment]
So, we cannot change the number 90000 when maintain for the --pruneancient flag ?
