### ISSUE TITLE
eth_getlogs hangs on the first blocks

### ISSUE THREAD

**Issue by mikhail-khalizev** [bnb-chain/bsc#1143]
#### System information

Geth version: 1.1.16
OS & Version: Linux
Commit hash : cb131fabe5fb9570180e7030a293a984f17c2446

#### Steps to reproduce the behaviour

1. Download a snapshot from https://github.com/bnb-chain/bsc-snapshots.
I use https://pub-10cd0733ed3540f1a5bd893cdcaf4027.r2.dev/geth-20221014-not-fastnode.tar.lz4

3. Download bsc release. I use https://github.com/bnb-chain/bsc/releases/tag/v1.1.16 for linux.

4. Start bsc:

```
./geth_linux --datadir $DATADIR
```

6. Attach to bsc.

```
./geth_linux attach $DATADIR/geth.ipc
```

7.  Make `eth_getLogs` request. Let's try the last blocks first - no hangs.
```
> eth.getLogs({fromBlock: "0x153CEA0", toBlock: "0x153CEAF", topics: ["0x0d3648bd0f6ba80134a33ba9275ac585d9d315f0ad8355cddefde31afa28d0e9"]})
[]
```

8. Try the first blocks.
```
> eth.getLogs({fromBlock: "0x100", toBlock: "0x105", topics: ["0x0d3648bd0f6ba80134a33ba9275ac585d9d315f0ad8355cddefde31afa28d0e9"]})

// Hangs up. There is no error message or successful response.
```

9. Let's try to stop bsc from step 3 with Ctrl + C.
Fails: "Already shutting down, interrupt more to panic" messages are displayed, but bsc does not stop.

**Comment by mikhail-khalizev** [comment]
Yes, it is the same.

**Comment by cosinlink** [comment]
follow up this issue, https://github.com/bnb-chain/bsc/issues/1125
