### ISSUE TITLE
bsc highestBlock stuck on old blocks

### ISSUE THREAD

**Issue by qbittex** [bnb-chain/bsc#1150]
i setup latest release and its stuck on highestBlock and currentblock

instance: Geth/v1.1.16-cb131fab/linux-amd64/go1.17.13

{
  currentBlock: 20778855,
  healedBytecodeBytes: 0,
  healedBytecodes: 0,
  healedTrienodeBytes: 0,
  healedTrienodes: 0,
  healingBytecode: 0,
  healingTrienodes: 0,
  highestBlock: 20778920,
  startingBlock: 0,
  syncedAccountBytes: 268148753,
  syncedAccounts: 2335281,
  syncedBytecodeBytes: 206788504,
  syncedBytecodes: 26483,
  syncedStorage: 12188128,
  syncedStorageBytes: 2651009323
}

**Comment by cosinlink** [comment]
what is the `bsc` binary version

**Comment by qbittex** [comment]
i still see this after add --tries-verify-mode=none my complate flag is

geth --config ./config.toml --datadir ./node --pprof.addr 0.0.0.0 --metrics --pprof --http --http.corsdomain "*" --diffsync --cache 18000 --tries-verify-mode=none

i use 128gb ram and 3 TB nvme server

WARN [10-26|01:44:57.351] Synchronisation failed, dropping peer    peer=a0c0ed1ffa3abc521e1bfb59f92955b755cd52a7f3aab44db035796dc6796547 err="peer is stalling"
WARN [10-26|01:44:57.352] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
WARN [10-26|01:44:57.356] Synchronisation failed, dropping peer    peer=5ce8c22cefee691e232de969d7e94de8eefed8433e7f37a6038cfa215840daeb err="peer is stalling"
WARN [10-26|01:44:57.356] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
WARN [10-26|01:44:57.356] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
WARN [10-26|01:44:57.361] Synchronisation failed, dropping peer    peer=fb07c9647d498f0714c15534f5e2e469e61e665c83b48cb92f0945453878a3aa err="peer is stalling"
WARN [10-26|01:44:57.362] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
