### ISSUE TITLE
should host docker image for bsc node in docker hub or public registry

### ISSUE THREAD

**Issue by jasonyic** [bnb-chain/bsc#1156]
# Rationale
BSC repo currently provide a dockerfile, but does not build & publish the docker image to docker hub, which seems a piece for the pipeline and convenient for node runner to run the BSC node in docker, very similar style as other blockchain network.

# Implementation

should add a step in pipeline to build the multi-arch docker image for `amd64` & `arm64` and publish the image to docker hub or any public registry.

**Comment by guagualvcha** [comment]
Hi, you can always get the bsc docker image from: https://github.com/bnb-chain/bsc/pkgs/container/bsc
And for the arm64 and amd64 binary, it will be support in next release.

**Comment by jasonyic** [comment]
cool, thanks

**Comment by phpmac** [comment]
agree
