### ISSUE TITLE
BNB faucet giving insufficient funds for gas error

### ISSUE THREAD

**Issue by proditneg** [bnb-chain/bsc#1157]
For a couple of days now BNB faucet is giving an error about insufficient funds for gas * price + value. i see that this issue has happened in the past to other people. if someone could look into it would be great.

**Comment by guagualvcha** [comment]
Hi, the faucet is back now, thanks for report.

**Comment by m-waqas88** [comment]
@guagualvcha 
 I am facing the same error. I have to submit my project for a Hackathon and I need tBnB tokens for testing. Its urgent. The deadline is very close. Can you guys plz look into this on priority?
