### ISSUE TITLE
BNB Testnet Faucet

### ISSUE THREAD

**Issue by burakben** [bnb-chain/bsc#1168]
Hi, I know this may not be the best place for this question, but I couldn't find a better one.

Our team is building a cross-chain protocol including BSC. It relies heavily on liquid pools (native asset/our token) on every chain.
I wanted to know if I can get testnet BNB on this address `0xffc6b1712670279752E00562A81D144608Cd922f`,  something around **3000**, up to **10000**, to set the pool in PancakeSwap.

Thank you.

**Comment by guagualvcha** [comment]
3k tBNB sent

**Comment by burakben** [comment]
> 3k tBNB sent

thank you sir 🥇
