### ISSUE TITLE
0x00000000000cc1ffb95df1486af6dacb26d6d1af0 How can you do what you want? The lowest price of geth is 5gwei.

### ISSUE THREAD

**Issue by meke168** [bnb-chain/bsc#1169]
0x00,000,000,000cc1ffb95df1486af6dacb26d6d1af0, the authentication node, has gone to sea. Does bsc have a future? It's so blatant to eat.
hash : 0x6bd699ddbcd4b3ca026c4aa265a32869d8dda054d39efa3655afda8df7a54ed7

**Comment by meke168** [comment]
The minimum limit of geth is 5gwei. How did his 1gwei broadcast? Are there other possibilities besides verifying nodes?

**Comment by perwpqwe** [comment]
"The minimum limit of geth is 5gwei."
There is no such rule, I suppose.
