### ISSUE TITLE
Validators that do not obey gasPrice ordering rules

### ISSUE THREAD

**Issue by Classical1956** [bnb-chain/bsc#1170]
This validator does not obey the gasprice collation!

Here is one of the blocks:
`https://bscscan.com/txs?block=22895318`

txs:
`https://bscscan.com/tx/0x1196db2f974098e9ca071b205185fcf5e37e4164dcde971264075b8bd525e092` (gasPrice: 5 Gwei  index: 211)

`https://bscscan.com/tx/0x9b20d03ba56011c27c837fb5e8fe14367f9f02172e95a2170ea4cdbd0f3560c5` (gasPrice: 5.453165044 Gwei index: 212)

This behavior is due to its own benefit, since it can be clearly seen that it is front-running on the same token to other swaps, ignoring the gas.

`0x61Dd481A114A2E761c554B641742C973867899D3` must be jailed for it's malicious behavior

**Comment by mas1337** [comment]
Yes, almost all blocks validated by that validator don't rate gasprice. I think the validator is doing a fraudulent way to profit from some transactions, should be jailed

**Comment by 0xLyon** [comment]
@Classical1956 Thanks for providing the information. Currently it seems that some validators are using customised code to adjust the order in which they process pending transactions. As of yet, this behaviour on its own does not seem malicious but we will continue to monitor.

**Comment by mas1337** [comment]
@48ClubIan That's right, validators have to respect gasprice, disadvantage for those who pay more expensive gasprice but the order is below the cheaper gasprice.

**Comment by kmalloc** [comment]
> @Classical1956 Thanks for providing the information. Currently it seems that some validators are using customised code to adjust the order in which they process pending transactions. As of yet, this behaviour on its own does not seem malicious but we will continue to monitor.

it is malicious, txs ordering matters and someone can profit a lot from this.

**Comment by mas1337** [comment]
@0xLyon if such a thing is allowed, in the future all validators will follow it to take profit. and there will be no more healthy competition

**Comment by iamman2021** [comment]
@mas1337 Can't agree any more

**Comment by wardhunt** [comment]
someone developed or use this pr：https://github.com/bnb-chain/bsc/pull/1152 , which caused problems

**Comment by TheUnknownDeveloper** [comment]
https://bscscan.com/txs?block=23102230

Position 11: 5 Gwei
https://bscscan.com/tx/0x21ca34e160fd514e7393c7b3a7444f41f42d98e13e24ca3da5ae2e47a6943200

Position  22: 10 Gwei
https://bscscan.com/tx/0x2f82b56f5b7166723f8f117af33d6f47cfd8c5a3c4f9895ad096b6c8cb264843

Validator:
0x61dd481a114a2e761c554b641742c973867899d3

Is this a new "feature"? How are the transaction sorted?

**Comment by 0xLyon** [comment]
> 

This is not a new feature. This is nodes performing customized sorting for picking up transactions. We are aware of this and are checking with the respective developers to get a solution soon.

**Comment by TheUnknownDeveloper** [comment]
@0xLyon thanks for the quick response!

**Comment by teebaumcrypto** [comment]
I'm also interested in the updates.
Just had a tx > 30gwei sorted nearly at the end of the block, rather than beeing first.

Same Validator:
0x61dd481a114a2e761c554b641742c973867899d3

Also based on research on p2p traffic, I see more validators not playing fairly (providing private endpoints to specific bots).

**Comment by DeepBorys** [comment]
The validator: 0xD1d6bF74282782B0b3eb1413c901D6eCF02e8e28 is working together with a MEV bot https://bscscan.com/address/0x319c6e576d7894cc99228ae361a84f19e5fcac82 and is doing sandwich attacks.

**Comment by nikolinsko** [comment]
noticed the same behavior on this [block](https://bscscan.com/txs?block=37358767&p=5) -  validator: 0xebe0b55ad7bb78309180cada12427d120fdbcc3a

[position 3](https://bscscan.com/tx/0x06dff52dfb3e5c22cdb27d090ee7eb6e926b81e2f6b5036ea785827932a3544d) - 86.22776381  GWEI
[position 4](https://bscscan.com/tx/0xb4b9145644600a410763a093c76444bcf0f21ad19ea61e4a66dc96f2a6af77ea) - 1 GWEI
[position 5](https://bscscan.com/tx/0x0bd08d3d0fe5af5494940b12cc840e369097ea37de21ea3dc4c73033c2f4ded8) - 86.22776381  GWEI
