### ISSUE TITLE
Fast sync stuck at State heal for 3 days.

### ISSUE THREAD

**Issue by Thrisul-K** [bnb-chain/bsc#1172]
Could anyone suggest what would be the suggested specs to run a node considering the current data. 
I tried with AWS m5zn3x.large with 10k IOPS it doesnt seem to catchup with current block even after 3 days.
just stuck at state heal in progress (below log for reference)

lvl=info msg="State heal in progress" accounts=2,797,558@164.39MiB slots=1,961,139@143.59MiB codes=1875@16.24MiB nodes=30,732,105@10.01GiB pending=161,822

i had observed below log during state sync
lvl=info msg="State sync in progress" synced=100.00% state="518.41 GiB" accounts=135,781,417@27.48GiB slots=2,371,626,607@476.15GiB codes=1,864,926@14.77GiB eta=-7m31.069s

does this mean heal phase should run till the accounts in this phase reach 135,781,417 ?

**Comment by Thrisul-K** [comment]
@kris-ss Thanks for the response, node is still the same and to answer your question I was syncing from Genesis block. 
At first i tried to sync from snapshot, but the node was stuck at "Looking for peers" for hours. so i shifted to syncing from Genesis block.

As per your suggestion i will try again to sync from Snapshot.
but is it normal to see "Looking for peers" for long time? and if it is, how long should i expect for the node to find peers.

**Comment by isaacyuno** [comment]
Could you share the start up command of your geth? And which snapshot do you use?

**Comment by Thrisul-K** [comment]
Hi, i was using ./build/bin/geth --config ./config.toml --datadir ./node -cache 60000 --txlookuplimit 0 --ws --wsapi="eth,net,rpc,web3,txpool,personal,debug" as startup command for geth.

luckily Snap sync found peers and the sync was done. Now my node is fully synced with BSC network. 
But none of the transactions which i'm submitting on this node are going beyond pending transactions list.
They just stay in Pending pool forever.
Any idea on why this could happen?

**Comment by Thrisul-K** [comment]
The transactions were stuck in pending as i was not setting gas price, and it is taken as 1 Gwei (by default i guess). post changing the gas price everything was fine.
Closing the ticket
