### ISSUE TITLE
Can't open faucet-smart 

### ISSUE THREAD

**Issue by JimYan** [bnb-chain/bsc#1175]
When I use browser open the faucet url:  https://testnet.binance.org/faucet-smart

got this error:

<img width="703" alt="图片" src="https://user-images.githubusercontent.com/4209007/201454571-df554723-6605-4b96-8a51-d0e3d87fd81c.png">

Please Fix it.

**Comment by kris-ss** [comment]
Hello, are you still having the same error? 
I tried on my end and it's all good. 

![Screen Shot 2022-11-13 at 10 42 20 AM](https://user-images.githubusercontent.com/113088090/201509427-e30dcef1-71c6-4915-a701-65fbca48809f.png)

**Comment by JimYan** [comment]
> Hello, are you still having the same error? I tried on my end and it's all good.
> 
> ![Screen Shot 2022-11-13 at 10 42 20 AM](https://user-images.githubusercontent.com/113088090/201509427-e30dcef1-71c6-4915-a701-65fbca48809f.png)

It's ok now. Tks :)
