### ISSUE TITLE
Call node coin withdrawal, the chain can not find the transaction information

### ISSUE THREAD

**Issue by liuhongfei0517** [bnb-chain/bsc#1176]
System Information
Geth version: 1.1.17
Startup parameters: toml --cache=45000 --diffsync --metrics --metrics.addr="0.0.0.0" --ws./geth --datadir./node -- config. /config.toml --cache=45000 --diffsync --metrics --metrics --ws.addr="0.0.0.0" --ws.origins="*" --rpc.allow-unprotected -TXS --txlookuplimit 0 --allow-insecure-unlock

When I called my full node for coin withdrawal, I did not know the relevant transaction information in the block browser, and the transaction submission log in the bsc log. I would like to know whether this is the Bug of bsc node or the problem of my node. I would appreciate any advice, thank you!
t=2022-11-12T15:00:32+0000 lvl=info msg="Submitted transaction"                 hash=0x44fa389ca69088a2a315fabc6d392a91ed8e38b545ea07ed64a7d1a5ff8e9082 from=0x1eaD99052A5F3c2E7676F3B4081ae8244A0CD1E1 nonce=3323 recipient=0xd819D96f9D28Ea85C1DD78e66d7241134E8d4aB4 value=0 x-forward-ip=nil

**Comment by kris-ss** [comment]
Hello, 

Sorry, I'm not sure if I understand you correctly. What are the transaction information that are missing from the block explorer? I can see the transaction here - https://bscscan.com/tx/0x44fa389ca69088a2a315fabc6d392a91ed8e38b545ea07ed64a7d1a5ff8e9082

As for the bsc.log entries, you can adjust the Level to "trace" if you want to show the trace logs. 

[Node.LogConfig]
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""

**Comment by liuhongfei0517** [comment]
> Hello,
> 
> Sorry, I'm not sure if I understand you correctly. What are the transaction information that are missing from the block explorer? I can see the transaction here - https://bscscan.com/tx/0x44fa389ca69088a2a315fabc6d392a91ed8e38b545ea07ed64a7d1a5ff8e9082
> 
> As for the bsc.log entries, you can adjust the Level to "trace" if you want to show the trace logs.
> 
> [Node.LogConfig] FilePath = "bsc.log" MaxBytesSize = 10485760 Level = "info" FileRoot = ""

**Comment by liuhongfei0517** [comment]
> Hello,
> 
> Sorry, I'm not sure if I understand you correctly. What are the transaction information that are missing from the block explorer? I can see the transaction here - https://bscscan.com/tx/0x44fa389ca69088a2a315fabc6d392a91ed8e38b545ea07ed64a7d1a5ff8e9082
> 
> As for the bsc.log entries, you can adjust the Level to "trace" if you want to show the trace logs.
> 
> [Node.LogConfig] FilePath = "bsc.log" MaxBytesSize = 10485760 Level = "info" FileRoot = ""

Thank you for your reply. I found the relevant information one hour after the submission information appeared in bsc.log. I can confirm that my block synchronization is the latest
