### ISSUE TITLE
Ratthakorn2509

### ISSUE THREAD

**Issue by Ratthakorn250999** [bnb-chain/bsc#1178]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by forcodedancing** [comment]
@Ratthakorn250999 The issue you submitted only contains the template, without any specific information. I will close this one, and if you have any specific issues, please create a new one. Thanks.
