### ISSUE TITLE
We need some more BNB as part of our work. TESTNET

### ISSUE THREAD

**Issue by burakben** [bnb-chain/bsc#1180]
We need some more BNB as part of our work.

Hi, I know this may not be the best place for this question, but I couldn't find a better one.

Our team is building a cross-chain protocol including BSC. It relies heavily on liquid pools (native asset/our token) on every chain.
I wanted to know if I can get testnet BNB on this address `0xffc6b1712670279752E00562A81D144608Cd922f`, something around 4000, up to 7500, to set the pool in PancakeSwap.

Thank you.

**Comment by forcodedancing** [comment]
@burakben Can you join the discord https://discord.com/invite/z2VpC455eU to seek help?

**Comment by forcodedancing** [comment]
@burakben test bnb send, please check this https://testnet.bscscan.com/tx/0xf2815f4e24051708f237315d95d8554860346e98d774182e924244d220d1002d

**Comment by burakben** [comment]
> @burakben test bnb sent, please check this https://testnet.bscscan.com/tx/0xf2815f4e24051708f237315d95d8554860346e98d774182e924244d220d1002d

thank u mate 🥇
