### ISSUE TITLE
Some validators adds more transactions to the block & gains more reward.

### ISSUE THREAD

**Issue by BrainTR** [bnb-chain/bsc#1183]
Normally validators adds transactions to the block which between (Block.Timestamp - 6000ms~) and (Block.Timestamp - 3000ms~). #107 #239
But some validator adds transactions to the block which between (Block.Timestamp - 6000ms~) and (Block.Timestamp - 500ms~).
Because of this, some validators adds more transactions to the block than other validators and gains more reward.

I wrote a simple script and detected some of those validators:
```
0xD1d6bF74282782B0b3eb1413c901D6eCF02e8e28 - Richard Feynman
0x295e26495CEF6F69dFA69911d9D8e4F3bBadB89B - Legend
0x72b61c6014342d914470eC7aC2975bE345796c2b - BNB48 Club
0x0BAC492386862aD3dF4B666Bc096b0505BB694Da - Claude Shannon
0xa6f79B60359f141df90A0C745125B131cAAfFD12 - Avengers
0x3f349bBaFEc1551819B8be1EfEA2fC46cA749aA1 - Legend II
0x8b6C8fd93d6F4CeA42Bbb345DBc6F0DFdb5bEc73 - Legend III
0x61Dd481A114A2E761c554B641742C973867899D3 - Synclub
```
Their APRs are higher than the others. https://www.bnbchain.org/en/staking
Some validators in this list also mentioned in the following issues: #1101 #1170

I think they are using a patch something like #1151 for their custom geth.

## **Example Data**
{BlockNumber} - {ValidatorAddress} - ...

### _**Normal Block Flow**_

![normal-flow](https://user-images.githubusercontent.com/11800715/202057934-640b418f-027c-4cf0-bc70-c4851fe5ac9a.jpg)
------------
### _**Abnormal Block Flow**_

![abnormal-flow-1](https://user-images.githubusercontent.com/11800715/202057929-af990a63-173e-4fc2-a20c-ec1395c4a556.jpg)
![abnormal-flow-2](https://user-images.githubusercontent.com/11800715/202057924-dd45241e-66ef-4c17-b7f4-b53a3a9d4448.jpg)
------------
These validators is sort of stealing transactions (and rewards) from the next validator.
Is this normal and acceptable?

**Comment by brilliant-lx** [comment]
There is a PR try to eliminate the problem, make mining more fair and follow the GasPrice rule as well.
You may check: https://github.com/bnb-chain/bsc/pull/1186/

**Comment by alexbrownf1** [comment]
If it is not fair and not acceptable, since the validators are elected by BNB holders, why not anyone propose to vote down these BAD validators or even slash them?

**Comment by brilliant-lx** [comment]
Slash them may not be a good solution. Although they got more rewards, they have not broken the law right now.
We will work out other solution to make it more fair between validators.

**Comment by alexbrownf1** [comment]
Fair enough. It would be better if we can solve the problem through code.
Just want to bring up that sometimes we can utilize the power of PoS, especially when some behavior is bad for the chain healthy and the code is not ready. It's also a threat to those who want to do bad things.

I have another concern is that with the bug fix, can we really stop these validators broadcast their blocks for about 1-2 seconds late to package even more transactions. In theory if a validator A broadcasts a block too late, other validators will propose blocks trying to replace the late block. Then there will be a competition and several reorgs maybe. But actually the candidate block most likely would be proposed by the 8 validators motioned above (maybe they also changed the code to propose the candidate earlier)

**Comment by soltrac** [comment]
There are MANY things some validators are doing to increase the rewards. Reorganizing transactions to own benefit, etc.

I've noticed also some chainlink oracles are starting to expose their transactions only to Avengers and friends validators, having not competition to liquidation bots. That's the problem when you have only 21 validators, it is easy to cheat.

I think there is not much to do.

**Comment by BrainTR** [comment]
After the #[v1.1.18](https://github.com/bnb-chain/bsc/releases/tag/v1.1.18) update, this issue looks like resolved.
