### ISSUE TITLE
Can we remove these snapshot from BSC (Binance Smart Chain)in the Parlia consensus? 

### ISSUE THREAD

**Issue by AsadullahSoomro** [bnb-chain/bsc#1187]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

**Comment by forcodedancing** [comment]
Can you explain more on this? Which `snapshot` you mean in specific?

**Comment by AsadullahSoomro** [comment]
@forcodedancing I mean Parlia Snapshotting Can we remove these snapshots for simplifying the Parlia Consensus Mechanism of BSC(Binance Smart Chain)

**Comment by forcodedancing** [comment]
> @forcodedancing I mean Parlia Snapshotting Can we remove these snapshots for simplifying the Parlia Consensus Mechanism of BSC(Binance Smart Chain)

IMO, the purposes are to serve pending request and for revert states. You are also share the codes you mentioned or even submit a pr to contribute your ideas. Thanks.

**Comment by forcodedancing** [comment]
I will close this issue for now. If you have further ones, please create new issues. Thanks
