### ISSUE TITLE
Which setup needed to include tx into same block as response to mempool tx?

### ISSUE THREAD

**Issue by Defianer** [bnb-chain/bsc#1194]
Hi all,

as I've learned here, for BSC Chain (ID 56) it's expected behavior that it will take >= 2 blocks for a newly broadcasted transaction to be included into a block. (cf. topic here: https://github.com/bnb-chain/bsc/issues/107)

However, I've seen plenty examples where it is obvious that based on a mempool tx (anticipated to be included into a block), there's another, second tx inserted into the identical block.

Which setup would be economic and feasible to be able to find most tx instantly on BSC chain mempool, filter for needed criteria and then to broadcast an own tx instantly that makes it into the identical block as the original tx?
Would appreciate pointer on where to get started and how this could work.
Thx in advance!

**Comment by teebaumcrypto** [comment]
expected behavior that it will take >= 2 blocks

This is wrong per se. You can broadcast in the same block, it depends how fast you get the initial tx.
If you want to compete with other people for something, have fun.

**Comment by forcodedancing** [comment]
@Defianer Usually it will take 2 blocks as mentioned in other threads. For the speed, it may depend on network topology, speed and so on.
