### ISSUE TITLE
Reduce Disk Space after sync from snapshot?

### ISSUE THREAD

**Issue by James19903** [bnb-chain/bsc#1197]
I have synced up my node using the BNB48 Snapshot. The snapshot size is currently 1.7 TB which insane....
I only have 2 TB on my machine.
Is it possible to remove of the node data after my node has synced?

**Comment by kris-ss** [comment]
Hello, you can try the storage optimization steps mentioned here - https://github.com/bnb-chain/bsc/issues/875

**Comment by James19903** [comment]
> Hello, you can try the storage optimization steps mentioned here - #875

Thanks for this! Any idea how much data this will actually save?

**Comment by forcodedancing** [comment]
@James19903 If you do not need old blocks, then you can do both the 2 options.

**Comment by forcodedancing** [comment]
@James19903 The issue will be closed for in-activity. If you still have issues, please reopen it or create new ones.
