### ISSUE TITLE
What exactly do "diffblock" in startup config for geth

### ISSUE THREAD

**Issue by marcinborecki** [bnb-chain/bsc#1206]
What exactly means and do diffblock.
So many times I have seen config like this:

--syncmode full --pruneancient=true --diffblock=5000

Thank you

**Comment by kris-ss** [comment]
This determines the number of blocks that should be persisted in the db when the flag **persistdiff** is enabled. 
This is not related to the **pruneancient** flag.

**Comment by marcinborecki** [comment]
Thank you @kris-ss .

So having --syncmode full --pruneancient=true 
...

and no setting for persistdiff = true

the diffblock do nothing?

**Comment by kris-ss** [comment]
@marcinborecki Yes, should be. But let me confirm that with the team to be sure. I will get back to you when I have updates.

**Comment by Tronglx** [comment]
I have same config for our node: --diffsync=true --syncmode=full --tries-verify-mode=none --pruneancient=true --diffblock=5000 without persistdiff = true but it's seem old blocks has been deleted. When executing getBlock(blockNumber), the result is null for old blocks.

**Comment by forcodedancing** [comment]
> @marcinborecki Yes, should be. But let me confirm that with the team to be sure. I will get back to you when I have updates.

Yes.
