### ISSUE TITLE
BSC node misbehaves when sending batched RPC calls

### ISSUE THREAD

**Issue by archerkeyboard** [bnb-chain/bsc#1214]
Hey, I've been using local forked BSC network to try some contract calls, but a bottleneck error has occurred. The details are in https://github.com/NomicFoundation/hardhat/issues/3379, but I'll summarize it here:

Given this two calls:
`curl https://bsc-dataseed2.binance.org -s -X POST -H 'Content-Type: application/json' --data '{"jsonrpc": "2.0", "id": 1, "method": "eth_getCode", "params": ["0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c", "0x165e2be"]}'
curl https://bsc-dataseed2.binance.org -s -X POST -H 'Content-Type: application/json' --data '[{"jsonrpc":"2.0", "id": 1, "method": "eth_getCode", "params": ["0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c", "0x165e2be"]}]'`

The difference here is that the second is a batch request, because it's inside an array.

The first one always returns the right value (or at least most of the time, sometimes it returns an error). But the second one has a very curious behavior:

- At the beginning, it returns the right value
- After a while it starts returning `0x`; that is, it acts as if the address had no code. This causes the issue where Hardhat tells you that you are calling an account which is not a contract.
- After even more time, the method just starts consistently failing.

The issue appears not only using hardhat, but also ganache. The node is not reliable and sometimes returns an error, even if the transaction should not fail.

**Comment by isaacyuno** [comment]
Hi, have you tried other RPCs from 
https://www.bnbchainlist.org/

**Comment by Pythonberg1997** [comment]
Hello @archerkeyboard , I tried your cmd many times, it always return the right value. I will dig into it. And a more reliable failed example will help with the debug

**Comment by Pythonberg1997** [comment]
Issue closed. You can reopen it anytime you get questions.
