### ISSUE TITLE
eth_getLogs limit exceeded (-32005)

### ISSUE THREAD

**Issue by twilightrus** [bnb-chain/bsc#1215]
On official public bsc nodes (https://bsc-dataseed.binance.org/) eth_getLogs fails with error:

`
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32005,
        "message": "limit exceeded"
    }
}
`

Request:

`
{"method":"eth_getLogs","params":[{"fromBlock": 23441385, "toBlock": 23441385}],"id":1,"jsonrpc":"2.0"}
`

**Comment by TheUnknownDeveloper** [comment]
The same error occurs with the other "official" endpoints:

https://bsc-dataseed.binance.org/
https://bsc-dataseed1.defibit.io/
https://bsc-dataseed1.ninicoin.io/
https://bsc.nodereal.io/

Source: https://docs.bnbchain.org/docs/rpc

**Comment by kris-ss** [comment]
The eth_getLogs api has been turned off in the public RPCs. This api allow users to view events that occurred on the blockchain. That's why you are getting the "limit exceeded" error. 

Please try the other 3rd Party RPCs like the nodereal one  (https://bsc-mainnet.nodereal.io/v1/64a9df0874fb4a93b9d0a3849de012d3)

**Comment by claasahl** [comment]
@kris-ss thanks for highlighting that the `eth_getLogs` calls were turned off. Is there some official post / article to which you can point me?

I have been trying to figure what limit I exceeded for quite some time now... and not realized that the limit changed. I would like to have a way of learning about these things ideally ahead of time in case something like it happens again.

**Comment by phucbienvan** [comment]
@kris-ss hi, Have you got any solutions yet?

**Comment by phucbienvan** [comment]
Do you have a better solution?
My project deadline is coming up.

**Comment by isaacyuno** [comment]
> @kris-ss thanks for highlighting that the `eth_getLogs` calls were turned off. Is there some official post / article to which you can point me?
> 
> I have been trying to figure what limit I exceeded for quite some time now... and not realized that the limit changed. I would like to have a way of learning about these things ideally ahead of time in case something like it happens again.

Rate limit for official endpoints are 10K/5min

**Comment by isaacyuno** [comment]
> Do you have a better solution? My project deadline is coming up.

Try 3rd party endpoints from https://chainlist.org/chain/56

**Comment by phucbienvan** [comment]
@isaacyuno thanks, it works

**Comment by ClarkChenc** [comment]
> The eth_getLogs api has been turned off in the public RPCs. This api allow users to view events that occurred on the blockchain. That's why you are getting the "limit exceeded" error.
> 
> Please try the other 3rd Party RPCs like the nodereal one (https://bsc-mainnet.nodereal.io/v1/64a9df0874fb4a93b9d0a3849de012d3)

Is there any official report about this? Or is there any community will report things like this? I think many developers need to keep track of changes like this.

**Comment by ClarkChenc** [comment]
> The eth_getLogs api has been turned off in the public RPCs. This api allow users to view events that occurred on the blockchain. That's why you are getting the "limit exceeded" error.
> 
> Please try the other 3rd Party RPCs like the nodereal one (https://bsc-mainnet.nodereal.io/v1/64a9df0874fb4a93b9d0a3849de012d3)

@kris-ss, I wonder is there any report about such change or is there any community will report changes like this? I think many developer need to keep track of such changes. Wish you reply.

**Comment by claasahl** [comment]
@isaacyuno I thought so too. The [documentation](https://docs.bnbchain.org/docs/rpc) doesn't mention that `eth_getLogs` requests have been turned off, yet I also started to receive "limit exceeded" responses while staying well below 10k requests / 5min. Hence my question to @kris-ss  about an official source for this change.

**Comment by isaacyuno** [comment]
> @isaacyuno I thought so too. The [documentation](https://docs.bnbchain.org/docs/rpc) doesn't mention that `eth_getLogs` requests have been turned off, yet I also started to receive "limit exceeded" responses while staying well below 10k requests / 5min. Hence my question to @kris-ss about an official source for this change.

Official doc will be updated soon. https://github.com/BNB-Chain-Support/bnb-chain.github.io/commit/9604cecb3d56c832f9c7fc85e7565937537d0c72 on the way to merge

**Comment by claasahl** [comment]
thanks @isaacyuno

Do you, by any chance, know of a way how I could have learnt about this change ahead of time?

**Comment by phucbienvan** [comment]
Hi, guys, Can you recommend the best RPCs

**Comment by OptimisticQuan** [comment]
> > @isaacyuno I thought so too. The [documentation](https://docs.bnbchain.org/docs/rpc) doesn't mention that `eth_getLogs` requests have been turned off, yet I also started to receive "limit exceeded" responses while staying well below 10k requests / 5min. Hence my question to @kris-ss about an official source for this change.
> 
> Official doc will be updated soon. [BNB-Chain-Support/bnb-chain.github.io@9604cec](https://github.com/BNB-Chain-Support/bnb-chain.github.io/commit/9604cecb3d56c832f9c7fc85e7565937537d0c72) on the way to merge

Is websocket disabled too?

**Comment by kiaroskuro** [comment]
I get the same error listening to events using .on() - is this the same problem or something different?
