### ISSUE TITLE
eth.syncing always false

### ISSUE THREAD

**Issue by kledgold** [bnb-chain/bsc#1219]
#### System information

Geth version: `1.1.17`
OS & Version: centos7
Commit hash : (if `develop`)

#########################
instance: Geth/v1.1.17-790f6e76-20221102/linux-amd64/go1.18
at block: 22677209 (Tue Nov 01 2022 18:03:24 GMT+0800 (CST))
 modules: eth:1.0 net:1.0 rpc:1.0 txpool:1.0 web3:1.0

To exit, press ctrl-d or type exit
> net.peerCount
187
> eth.blockNumber
22677209
> eth.syncing
false
>

**Comment by kris-ss** [comment]
Hello,

Can you share your start-up command and bsc.log entries please?
Also are you syncing from a snapshot? If yes, which one?

I would advise you to update to the latest version - https://github.com/bnb-chain/bsc/releases/tag/v1.1.18

**Comment by kris-ss** [comment]
Also I suggest to use Discord if you need a more interactive support.

https://discord.gg/bnbchain

**Comment by kledgold** [comment]
> 



> Hello,
> 
> Can you share your start-up command and bsc.log entries please? Also are you syncing from a snapshot? If yes, which one?
> 
> I would advise you to update to the latest version - https://github.com/bnb-chain/bsc/releases/tag/v1.1.18

the snapshot is
https://pub-10cd0733ed3540f1a5bd893cdcaf4027.r2.dev/geth-20221101-not-fastnode.tar.lz4
because 
https://download.bsc-snapshot.workers.dev/geth-20221128.tar.lz4 
The system will report an error: 
the connection is closed at 50776244224 bytes. Retrying.

--2022-11-30 17:11:21 -- (Number of attempts: 2) https://download.bsc-snapshot.workers.dev/geth-20221128.tar.lz4

Connecting to download.bsc-snapshot.workers Dev (download. bsc snapshot. workers. dev) | 172.67.219.254 |: 443... Connected.

HTTP request issued, waiting for response... 500 Internal Server Error

2022-11-30 17:11:21 Error 500: Internal Server Error.

**Comment by kris-ss** [comment]
Hello, can you try geth-20221128.tar.lz4 again? You can download using below script.

aria2c -o geth.tar.lz4 -s14 -x14 -k100M https://download.bsc-snapshot.workers.dev/geth-20221128.tar.lz4 -o geth.tar.lz4

So, what you can do is
1) Upgrade to the new geth version (1.1.18)
2) Sync from above snapshot.

Here is the guide https://docs.bnbchain.org/docs/validator/fullnode/#sync-from-snapshot-recommended for reference.
