### ISSUE TITLE
prometheus-metrics

### ISSUE THREAD

**Issue by xuboatom** [bnb-chain/bsc#1221]
#### System information

Geth version: `v1.1.18`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
api: /debug/metrics/prometheus
# TYPE build_info gauge
build_info{"architecture":"amd64","git-commit":"03ff2992ab467

!!!!! build-info is invalid metric type .
#### Actual behaviour
api: /debug/metrics/prometheus
# TYPE build-info gauge
build-info{"architecture":"amd64","git-commit":"03ff2992ab467

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by Pythonberg1997** [comment]
We fix that in https://github.com/bnb-chain/bsc/pull/1217. Will update our release soon
