### ISSUE TITLE
Wahy thoes blocks only contains a few of tranactions

### ISSUE THREAD

**Issue by wangtsiao** [bnb-chain/bsc#1225]
Such as 
`https://bscscan.com/block/23550876`
`https://bscscan.com/block/23550955`
`https://bscscan.com/block/23550989`

seems validator (Certik, Namelix, Ankr)

**Comment by brilliant-lx** [comment]
That is because they haven't upgraded to the latest release v1.1.18, it should be recovered once they upgraded.
We are notifying them to upgrade as soon as possible, so close it.
