### ISSUE TITLE
Link for "web3 methods" in Readme out of date

### ISSUE THREAD

**Issue by emailtovamos** [bnb-chain/bsc#1227]
The current link mentioned in [this](https://github.com/bnb-chain/bsc#hardware-requirements) section of Readme for "web3 methods" points to https://web3js.readthedocs.io/en/ which shows a 404 page. 

Perhaps this needs to be changed to https://web3js.readthedocs.io/en/v1.8.1/ ?

**Comment by mosinb** [comment]
> this

You are right, we will look into that. Thanks!
