### ISSUE TITLE
Name tags for my Wallet Addresses

### ISSUE THREAD

**Issue by AdamLeye** [bnb-chain/bsc#1228]
I sent a Public Tag Application for my 4 separate wallet addresses where my project's reserves are located, I wonder when it will be approved and can be viewed on the bscscan site?

**Comment by mosinb** [comment]
> I sent a Public Tag Application for my 4 separate wallet addresses where my project's reserves are located, I wonder 

Hi, Did you do that on bscscan? If so please reach out to bscscan support https://bscscan.com/contactus

**Comment by Pythonberg1997** [comment]
Close the issue. Feel free to reopen it anytime you need.
