### ISSUE TITLE
txs from WS stucked 

### ISSUE THREAD

**Issue by BNB666666666** [bnb-chain/bsc#1229]
#### System information
16cores cpu
72g RAM
Geth version: `1.1.18`
OS & Version: Windows
Commit hash : (if `develop`)

#### Expected behaviour
Smoothly attain txs from wss://127.0.0.1:7888

#### Actual behaviour
config.toml:

(about [NODE] settings):

[Node]
IPCPath = "geth.ipc"
HTTPHost = "localhost"
NoUSB = true
InsecureUnlockAllowed = false
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]
WSPort = 7888
WSModules = ["net", "web3", "eth", "txpool", "parlia"]
WSHost = "localhost"

log:
t=2022-12-04T00:43:05+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=104   mgas=9.928    elapsed=29.500ms  mgasps=336.539 number=23,592,342 hash=0x056349f480cc987a1b7b95be48e76218ecaa851efd900a5a46da83c9ae39eade dirty="0.00 B"
t=2022-12-04T00:43:08+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=105   mgas=8.599    elapsed=41.015ms  mgasps=209.658 number=23,592,343 hash=0x409c95c2ab63c1e83fba75efe8152f5cf789748d2b582593652a2c736724eaba dirty="0.00 B"
t=2022-12-04T00:43:09+0800 lvl=info msg="Deep froze chain segment"               blocks=39  elapsed=2.597ms   number=23,502,343 hash=0x11dbef67561a5260cbd1e1f68a0d3ace2eed5d2eb497f9c42c40cea3688ef657
t=2022-12-04T00:43:12+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=113   mgas=10.506   elapsed=32.689ms  mgasps=321.388 number=23,592,344 hash=0x51ec9cef047f819b241c0d993fd5c29cf396419c056df246127a7b07440e24fd dirty="0.00 B"
t=2022-12-04T00:43:14+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=121   mgas=21.620   elapsed=90.359ms  mgasps=239.265 number=23,592,345 hash=0xac7f6cd570776ccedb8158e75153289118ac95d203cccef9b16557211d3f8ceb dirty="0.00 B"
t=2022-12-04T00:43:16+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=32    mgas=1.718    elapsed=16.994ms  mgasps=101.105 number=23,592,346 hash=0x3d9151c198f6b88cb0b32b4523d1a1b35ec49e7b8468f1275b68787dfcf87efe dirty="0.00 B"
t=2022-12-04T00:43:21+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=205   mgas=22.594   elapsed=75.302ms  mgasps=300.042 number=23,592,347 hash=0xcde4fb9858d53c5ee47bd7641b076c6b2e4478e7e97446345489ff61f6ddd1ce dirty="0.00 B"
t=2022-12-04T00:43:24+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=85    mgas=10.146   elapsed=92.122ms  mgasps=110.137 number=23,592,348 hash=0x168d0415f6bcca9417ca39a372a05f1ee9c89380b3ceac5f026b8095543f34aa dirty="0.00 B"
t=2022-12-04T00:43:27+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=130   mgas=11.192   elapsed=40.323ms  mgasps=277.561 number=23,592,349 hash=0x027cedbafe2656b4a91e07e9f245ccba8f99510200beb5c055ab4a06f2cc3918 dirty="0.00 B"
t=2022-12-04T00:43:30+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=105   mgas=35.588   elapsed=193.609ms mgasps=183.813 number=23,592,350 hash=0x20e15f72c59377cb26b4a17b178e6350fb48017f7b9371462fa50d4736333b38 dirty="0.00 B"
t=2022-12-04T00:43:31+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=48    mgas=7.244    elapsed=62.688ms  mgasps=115.557 number=23,592,351 hash=0xab3c3e17e12c786e8dbcd6d4183dd7679f3750cc2c9d614bf9920eaa23e494cd dirty="0.00 B"
t=2022-12-04T00:43:36+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=73    mgas=6.477    elapsed=86.279ms  mgasps=75.067  number=23,592,352 hash=0x12e3c693ae5932c382d77969e148da78fa7b9e2e064949fb2465c410220efbce dirty="0.00 B"
t=2022-12-04T00:43:40+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=174   mgas=16.487   elapsed=58.073ms  mgasps=283.893 number=23,592,353 hash=0xfbda02463868cd536f3450e8cbbaf9fce09dfb770816796eebbda86280d432ad dirty="0.00 B"
t=2022-12-04T00:43:42+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=147   mgas=13.249   elapsed=35.129ms  mgasps=377.148 number=23,592,354 hash=0xd902540afcb33fb287d2eb6daf419b43093d664da28d7627685f0c51f9776574 dirty="0.00 B"
t=2022-12-04T00:43:45+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=111   mgas=10.638   elapsed=33.533ms  mgasps=317.232 number=23,592,355 hash=0x7ec83212bcc2e83eb8986a4dbe1fd62ec156e82dcf1f51198d5e3074e3a547e9 dirty="0.00 B"
t=2022-12-04T00:43:49+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=109   mgas=11.654   elapsed=39.583ms  mgasps=294.424 number=23,592,356 hash=0xe322374c2c8be0c8814be282a608aa7ebb77a76b81d7f7670fc1e5ac9598c11e dirty="0.00 B"
t=2022-12-04T00:43:51+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=128   mgas=17.407   elapsed=80.589ms  mgasps=215.991 number=23,592,357 hash=0x872c717af3abdeaf7b72938cfb83bbb256df25f9cb5f440b05538fc1c290ce3e dirty="0.00 B"
t=2022-12-04T00:43:52+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=8     mgas=1.184    elapsed=11.806ms  mgasps=100.288 number=23,592,358 hash=0x3d84a5ea37426f1f904edafa1445f976476e058d169403e8eedfb88fe3f4fe4d dirty="0.00 B"
t=2022-12-04T00:43:57+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=116   mgas=9.840    elapsed=32.972ms  mgasps=298.427 number=23,592,359 hash=0xb44dc8e8ef992b6b1f78e7eccdc584685dbe68db68b0af99a11b3eb879620427 dirty="0.00 B"
t=2022-12-04T00:44:00+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=221   mgas=21.975   elapsed=83.157ms  mgasps=264.265 number=23,592,360 hash=0xb7b6ca9acd3bf91525c76ff4d5d76ad5f24845367ac0351e6d3d4acfbb5aaf5f dirty="0.00 B"
t=2022-12-04T00:44:02+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=129   mgas=12.188   elapsed=56.220ms  mgasps=216.783 number=23,592,361 hash=0x7e0f9527dcd167f140e47b45c2882a09267a35fd35dd0f22c7e6e225a287dfc4 dirty="0.00 B"
t=2022-12-04T00:44:07+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=135   mgas=15.604   elapsed=94.063ms  mgasps=165.888 number=23,592,362 hash=0xbbe93ca7c061988559021fb524fcf56f159a137580e50f89c6c313fbe959e0cb dirty="0.00 B"
t=2022-12-04T00:44:09+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=102   mgas=12.574   elapsed=69.226ms  mgasps=181.632 number=23,592,363 hash=0x0fc84a69e1dd8029c0837e4f741659eda8563e5f0d15fe577fa62d8f954b9ed5 dirty="0.00 B"
t=2022-12-04T00:44:09+0800 lvl=info msg="Deep froze chain segment"               blocks=20  elapsed=1.542ms   number=23,502,363 hash=0xec7a4c67d2eb85b40c229b9196dc88dcf7403923cb5890f4121e63b41bca5134
t=2022-12-04T00:44:11+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=117   mgas=12.936   elapsed=45.951ms  mgasps=281.514 number=23,592,364 hash=0xb6f3c53a9992e027ebe9d22cc1ea7a6010ed17c753bb317083bf84395005c297 dirty="0.00 B"
t=2022-12-04T00:44:15+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=93    mgas=9.079    elapsed=58.322ms  mgasps=155.671 number=23,592,365 hash=0x8eb2e3c3de88aa54c495b1101e6960d7d597aabff91c372139671480158d59b1 dirty="0.00 B"
t=2022-12-04T00:44:18+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=134   mgas=15.731   elapsed=86.634ms  mgasps=181.582 number=23,592,366 hash=0x7c30d706dd672be1449a23abee63804757af8b339f5045a0105a98b7fea35a79 dirty="0.00 B"
t=2022-12-04T00:44:19+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=5     mgas=0.310    elapsed=3.077ms   mgasps=100.616 number=23,592,367 hash=0xc6dac53ad7888228204c5526d8e7772dfa2a2fc8e947a3e76ef609bec59fe224 dirty="0.00 B"
t=2022-12-04T00:44:25+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=213   mgas=18.877   elapsed=67.266ms  mgasps=280.627 number=23,592,368 hash=0x84e4071546f655ef34fc9dc36daa01a81335bb27e67c4131b415be80b8eecdf4 dirty="0.00 B"
t=2022-12-04T00:44:27+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=97    mgas=15.604   elapsed=88.122ms  mgasps=177.072 number=23,592,369 hash=0xf80f5ad93811d94e9693196553b64547efe26ffd38f63ca09e834adf4df0a6b7 dirty="0.00 B"
t=2022-12-04T00:44:29+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=106   mgas=12.220   elapsed=50.235ms  mgasps=243.255 number=23,592,370 hash=0xa96d7638ff764c4fc03e6d2c1f9251b4ede89c959de5f4ca367a9441ce2a5ba0 dirty="0.00 B"
t=2022-12-04T00:44:32+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=108   mgas=13.875   elapsed=37.690ms  mgasps=368.135 number=23,592,371 hash=0x93bdee057a62a0306a15ec0764d960013616346e2f0b0bd8419db75a0fc8d87a dirty="0.00 B"
t=2022-12-04T00:44:35+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=7     mgas=0.274    elapsed=8.671ms   mgasps=31.638  number=23,592,372 hash=0x32400cb35471548b8593b70002484fd66aca63ade92555afd149ebcec035b83b dirty="0.00 B"

"pending" txs attained:
0xdcf9e159a1aef4927607117f7d663d2da2c19bbddf2cabf8ece90f072d25e2fd
run.js:79
2022/12/4 00:43:15
run.js:78
0xda542c57e3a52addbb248bda8cc515205eed22b1b97869ce75286fec4f51ac30
run.js:79
2022/12/4 00:43:18
run.js:78
0x4444023c1b706e32e32ea48db6ae7c713cc228ec0cc711ea6ed45a34afe87299
run.js:79
2022/12/4 00:43:20
run.js:78
0x913f6797c40d2ae9d6ddbe2c922b40f937e7145194f61d6b009363057595d606
run.js:79
2022/12/4 00:43:20
run.js:78
0x14ccc915a89114837c1a51f7cb62dba4e8cdf5fb315b5b16d26887290ee6023a
run.js:79
2022/12/4 00:43:21
run.js:78
0x576dd703d5cc7eb61769bb2376b76d25fd37c1d7f8f938bac00ad51186645df9
run.js:79
2022/12/4 00:43:21
run.js:78
0x370b4dc3a2124ca002ce0d6413726d664dd028c831b43f0a3498e8d0b9d67a02
run.js:79
2022/12/4 00:43:21
run.js:78
0x25e376cae005a4c5921d0766b287d87bbeef117830b392e49585b616495e7f8b
run.js:79
2022/12/4 00:43:21
run.js:78
0x628ff38c28bded1c1b6e64852e7326398c9d41e754d14835f213b0894bee4f59
run.js:79
2022/12/4 00:43:21
run.js:78
0xa9ef977f787bcc5212cffe61350f453c0c8ccca406586439fe5b7878118468ce
run.js:79
2022/12/4 00:43:21
run.js:78
0xab242f88feebc6af819126324f9fa39690c5b06059e2b361cb6cc20030f659a6
run.js:79
2022/12/4 00:43:43
run.js:78
0xe3605339058e762131781b982214d910b09b6b5667ab314f24d8e13a25662ee6
run.js:79
2022/12/4 00:43:43
run.js:78
0xd4579eeb84952239536d4ec57adbec97b08e2c444784dc03a93ae4fbcf558d56
run.js:79
2022/12/4 00:43:55
run.js:78
0x32a651a4fffc136a96c055f6c16e7fd5624cf3efabfce977043183a0fa2b1444
run.js:79
2022/12/4 00:43:55
run.js:78
0x7e008cc7162a07b0f1ef1661c88a0708eabc139caa7860a3b5a066c883d9dbe6
run.js:79
2022/12/4 00:44:28
run.js:78
0x0a02f2254b145afb6fe4101f6d70c1b7103de9567dab17eed89a944b15fa4a74
run.js:79
2022/12/4 00:44:28
run.js:78
0xe7be504c74c7559c810080634a0431d9e3716274a06ebb1b1ea5eed387195dfe
run.js:79
2022/12/4 00:44:28
run.js:78
0xf207075ddc69709cf57f8b069e28b288c52a928adcd392b6c3e68ca39070c1fb
run.js:79
2022/12/4 00:44:28
run.js:78
0xb174184b313a15d101e4bebb787f93edcc9071c361f49d622c9c8353d9162ced
run.js:79

#### Steps to reproduce the behaviour
geth.exe --metrics --metrics.addr 0.0.0.0 --config ./config.toml --datadir ./node --syncmode full --cache 68000 --tries-verify-mode=none --txlookuplimit=0 --pruneancient=true --diffblock=5000 --rpc.allow-unprotected-txs 

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by BNB666666666** [comment]
sometimes the BLOCK goes regularly, But the txs from ws comes so incoherently.

**Comment by BNB666666666** [comment]
![image](https://user-images.githubusercontent.com/117515691/205452676-f96dbe8f-510a-4fe4-b0e5-713b4d64f213.png)

**Comment by BNB666666666** [comment]
![image](https://user-images.githubusercontent.com/117515691/205452795-74fc953f-b16e-4703-8a09-dc80fe572a46.png)

**Comment by BNB666666666** [comment]
Does it make sense ? Who can help me ?

**Comment by mosinb** [comment]
Hi there, I am not sure I understand what is wrong with your node. You are not seeing the blocks when connecting through WebSocket?

**Comment by BNB666666666** [comment]
> 你好，我不确定我明白你的节点出了什么问题。通过WebSocket连接时，您没有看到块？

Thanks for reply.I use  wssProvider.on("block",)  ,it seems regular.But  when I use the  wssProvider.on("pending",)   the txs comes slowly  and even stucked

**Comment by BNB666666666** [comment]
![1670115448326](https://user-images.githubusercontent.com/117515691/205468655-7b151517-e5d3-40a5-ac53-49d563b8e9f8.jpg)

![1670115477289](https://user-images.githubusercontent.com/117515691/205468666-57e8cfd3-3884-4e13-98b3-14b9549b332e.jpg)

**Comment by BNB666666666** [comment]
well.I figure it out .  my node get block with 3-5s delay  :(
