### ISSUE TITLE
eth_getlogs old data

### ISSUE THREAD

**Issue by Grigoriy555** [bnb-chain/bsc#1230]
I have my node synchronized from the BNB48Clu snapshot.

Execute command:
./geth --config ./config.toml --datadir ./mainnet --cache 100000 --rpc.allow-unprotected-txs --txlookuplimit 0 --http --maxpeers 100 --ws --syncmode=full --snapshot=true --diffsync --pruneancient=true --diffblock=5000 --tries-verify-mode=none 

The problem is that there is no data for geth_logs on old transactions (required about 12 months ago). Can I somehow add the necessary data without synchronization the node from begin? Or do i need a full resync without a snapshot?

**Comment by kris-ss** [comment]
Unfortunately the official snapshot (https://github.com/bnb-chain/bsc-snapshots) that we have is also pruned. So it won't be able to satisfy the your 12 month data requirement.

**Comment by Grigoriy555** [comment]
Ok, thanks for the quick replies!
