### ISSUE TITLE
BSC Node storage requirement and ancient folder

### ISSUE THREAD

**Issue by daica75** [bnb-chain/bsc#1231]
The storage requirement for a BSC node has been getting out of hand with the ancient folder taking up more than 1TB now :(

It seems like the ancient folder is not really needed and is used for historical data only... so my question is can we mount the ancient folder from a network share instead of having it on the node computer itself so that the data in the chaindata folder excluding that ancient folder is usually just around 500GB and not over 1TB.

I know for the chaindata data the speed of the storage it is on needs to be very fast, but what about the ancient folder.... TIA

**Comment by Pythonberg1997** [comment]
Yes you can create one directory in a mounted disk and try with one soft link folder to ancient. Soft link only works in the same file system. And you can try prune-block to reduce ancient folder's size.
