### ISSUE TITLE
what is the purpose of nextForkHash in parlia.go?

### ISSUE THREAD

**Issue by readygo67** [bnb-chain/bsc#1232]
In the line632 code, nextForkHash is calculated and fill the last 4 bytes of extraVanity. What is it for?

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/78890754/205861835-8ce8e091-48cb-4678-909b-9cfaab45b4dc.png">

**Comment by Pythonberg1997** [comment]
It represents the next fork number

**Comment by Pythonberg1997** [comment]
Close the issue. Feel free to reopen it anytime you need.
