### ISSUE TITLE
Can you please explain how it works

### ISSUE THREAD

**Issue by akboolz** [bnb-chain/bsc#1236]

**Comment by akboolz** [comment]
Whatever. Time to kill my self.

**Comment by kris-ss** [comment]
Hello, sorry to hear about this.  What the error means there was a contract function executed with error but the rest of the transaction was successful. 

Both the contracts do not have source codes so we can't readily check what happened. Did you receive any request from your end any approval requests? 

You can check for approvals here https://bscscan.com/tokenapprovalchecker and revoke as needed.

Also, you can raise this issue in the https://discord.gg/bnbchain discord for a more interactive support.
