### ISSUE TITLE
BSC node stuck after HF

### ISSUE THREAD

**Issue by grocon** [bnb-chain/bsc#1237]
#### System information

Geth version: git_tag=v2.31.0-rc.4
OS & Version: Debian/Linux

#### Expected behaviour
BSC chain should not be stuck

#### Actual behaviour
BSC chain is stuck at block 23846018

#### Steps to reproduce the behaviour
I did multiple times an unwind
`build/bin/integration stage_headers --unwind=100 --chain=bsc --datadir /home/bscnode/.bsc`
then start erigon
`erigon --chain=bsc --prune=hrtc --db.pagesize=16k --http --private.api.addr= --http.api=eth,web3,trace,txpool --snap.stop --torrent.port 42070 --http.port 18545 --port 30404 --datadir /home/bscnode/.bsc --maxpeers 256`

then it says 
`WARN[12-13|09:23:38.490] [7/16 Execution] Execution failed        block=23846019 hash=0xef64dbe0ffe29689184c4a5c075f8d23fd6f9463c4cdc2ccc64eabda7354a1f6 err="expected system tx (hash 0xb492578c0742f89c5fac41cdd72d244b1758063319bd074df43e761088ce1e25, nonce 41216, to 0x0000000000000000000000000000000000001000, value 0x109286049017740, gas 9223372036854775807, gasPrice 0x0, data f340fa01000000000000000000000000d1d6bf74282782b0b3eb1413c901d6ecf02e8e28), actual tx (hash 0xd9fcd3f24acf6855ce04d3bec42f8188b56b8a5dcb27434cc7ed23c2062ce58d, nonce 41216, to 0x0000000000000000000000000000000000001000, value 0x1092907ec599740, gas 9223372036854775807, gasPrice 0x0, data f340fa01000000000000000000000000d1d6bf74282782b0b3eb1413c901d6ecf02e8e28)"`

it is then stuck and logs repeat saying
`INFO[12-13|09:25:20.785] [2/16 Headers] No block headers to write in this log period block number=23846018`

**Comment by kris-ss** [comment]
Hello, sorry we don't have much experience with Erigon client. But I can see from BNB48Club, the actually have a snapshot from block 23861329. Can you use this for your setup instead? 

https://github.com/BNB48Club/bsc-snapshots#download-1

**Comment by grocon** [comment]
Sorry. I meant to create this issue @erigon
anyway, thanks for the advice. I will try the snapshot if I can't restart it.
