### ISSUE TITLE
Websocket on same port as http server Unexepected server response: 200

### ISSUE THREAD

**Issue by pleaseshutup** [bnb-chain/bsc#1239]
Pretty sure it's the same bug described here
https://github.com/ethereum/go-ethereum/issues/21668

I imagine the patches to fix that could be applied here?

Geth version: `geth version`
OS & Version: Windows/Linux/OSX

Geth/v1.1.18-cb9e50bd/linux-amd64/go1.17.13

#### Expected behaviour
Should accept http requests and websocket requests on same port

#### Actual behaviour
error: Unexpected server response: 200

#### Steps to reproduce the behaviour
Configure bnb geth to have http json rpc server on same port as websocket server.  Try to connect over websocket

NOTE!!!
It may be a proxy issue as well, so if the bug cannot be replicated try throwing a proxy in front of the json rpc server and connect with a custom hostname.

**Comment by ZiyuanStar** [comment]
wss uses port 8546

**Comment by pleaseshutup** [comment]
> wss uses port 8546

Yes, however, I am using a cloudflared tunnel so I can have a nice public URL with ssl termination handled by cloudflare into my private network where my bsc get node is running.

I have already configured this to work with the current version of geth and ethereum, however, I suspect that this forked version of geth is behind in the patches that made this feature possible.


The tunnel config allows me to specify a host and port and is only available on ports 80 or 443 so I cannot configure separate ports for the same host. 

http and ws can and should live on the same port, websockets are just an 'upgrade' on the connection.

**Comment by bnb-tw** [comment]
@pleaseshutup is this still an issue for you? We've patched BSC with a lot of upstream changes since this issue was created.
