### ISSUE TITLE
Syncing not working

### ISSUE THREAD

**Issue by ToXaHo** [bnb-chain/bsc#1243]
Current block: 22960161

Log:
`WARN [12-15|23:35:55.863] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
WARN [12-15|23:36:04.044] Synchronisation failed, dropping peer    peer=7aaf2c89de4b84792e7b9f0d92d345f373fbc9cf258b798f862f8823be5b836b err=timeout
WARN [12-15|23:36:43.567] Ancestor below allowance                 peer=05928829 number=0          hash=0d2184..d57b5b allowance=22,870,161
WARN [12-15|23:36:43.567] Synchronisation failed, dropping peer    peer=059288294e3777e19692a53580a9f816184a3e30184e92c60c604b56948e5787 err="retrieved ancestor is invalid"
WARN [12-15|23:36:43.568] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
WARN [12-15|23:37:25.939] Multiple headers for single request      peer=fb1b13da headers=0
WARN [12-15|23:37:25.939] Synchronisation failed, dropping peer    peer=fb1b13da5aaa43456100e8ce5b4d8481fb98578c55cc263c6c5b517c549c08d0 err="action from bad peer ignored: multiple headers (0) for single request"
WARN [12-15|23:37:25.940] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
`

**Comment by cosinlink** [comment]
upgrade the geth version to the latest

**Comment by ToXaHo** [comment]
> upgrade the geth version to the latest

Is this not the latest version?

`Geth
Version: 1.1.17
Git Commit: 790f6e767a3c0c3a113bc38e69e9c02cf7f46b49
Git Commit Date: 20221102`

**Comment by ToXaHo** [comment]
Updated geth, now this log

`WARN [12-17|03:40:10.446] Snapshot extension registration failed   peer=a90b10c7 err="peer connected on snap without compatible eth support"
WARN [12-17|03:41:03.581] Snapshot extension registration failed   peer=98998f1a err="peer connected on snap without compatible eth support"
WARN [12-17|03:41:08.987] Snapshot extension registration failed   peer=409e2bcc err="peer connected on snap without compatible eth support"
WARN [12-17|03:41:45.432] Snapshot extension registration failed   peer=845d9aff err="peer connected on snap without compatible eth support"
WARN [12-17|03:41:50.610] Snapshot extension registration failed   peer=b504b033 err="peer connected on snap without compatible eth support"
WARN [12-17|03:42:32.383] Snapshot extension registration failed   peer=5450e190 err="peer connected on snap without compatible eth support"
WARN [12-17|03:43:29.415] Snapshot extension registration failed   peer=cb5b9771 err="peer connected on snap without compatible eth support"
WARN [12-17|03:44:37.960] Snapshot extension registration failed   peer=a90b10c7 err="peer connected on snap without compatible eth support"
WARN [12-17|03:45:25.174] Snapshot extension registration failed   peer=bc8af532 err="peer connected on snap without compatible eth support"
WARN [12-17|03:45:27.585] Snapshot extension registration failed   peer=93cf0652 err="peer connected on snap without compatible eth support"
WARN [12-17|03:45:30.205] Snapshot extension registration failed   peer=41c336eb err="peer connected on snap without compatible eth support"
WARN [12-17|03:47:09.996] Snapshot extension registration failed   peer=63cbe74f err="peer connected on snap without compatible eth support"
WARN [12-17|03:47:44.724] Snapshot extension registration failed   peer=7501eaab err="peer connected on snap without compatible eth support"
WARN [12-17|03:50:29.724] Snapshot extension registration failed   peer=e5da3a6c err="peer connected on snap without compatible eth support"
WARN [12-17|03:51:46.810] Snapshot extension registration failed   peer=92a3f6f8 err="peer connected on snap without compatible eth support"
WARN [12-17|03:52:15.818] Snapshot extension registration failed   peer=6a0bcd3f err="peer connected on snap without compatible eth support"
WARN [12-17|03:53:44.195] Snapshot extension registration failed   peer=98998f1a err="peer connected on snap without compatible eth support"
WARN [12-17|03:55:10.121] Snapshot extension registration failed   peer=94a3e001 err="peer connected on snap without compatible eth support"
WARN [12-17|03:57:06.309] Snapshot extension registration failed   peer=aab3bbde err="peer connected on snap without compatible eth support"
WARN [12-17|03:57:07.944] Snapshot extension registration failed   peer=bc8af532 err="peer connected on snap without compatible eth support"
WARN [12-17|03:57:47.154] Snapshot extension registration failed   peer=6de7b40a err="peer connected on snap without compatible eth support"
WARN [12-17|03:57:59.149] Snapshot extension registration failed   peer=d348bda2 err="peer connected on snap without compatible eth support"
WARN [12-17|03:59:24.487] Snapshot extension registration failed   peer=d5a6c885 err="peer connected on snap without compatible eth support"
WARN [12-17|04:00:37.148] Snapshot extension registration failed   peer=bc8af532 err="peer connected on snap without compatible eth support"`

**Comment by isaacyuno** [comment]
Which snapshot do you use? What's your startup command?

**Comment by KeefeL** [comment]
> Which snapshot do you use? What's your startup command?

You can refer to this https://github.com/bnb-chain/bsc/issues/1193
