### ISSUE TITLE
Did someone win to sync ? Impossible to do .. 

### ISSUE THREAD

**Issue by banlieu451** [bnb-chain/bsc#1249]
Hello everybody i can't sync my node currently with the lastest version and the version -1 too.

Config :
- 12 cores Xeon 
- 32 RAM DDR4
- Internet = LAN 4 Gb/s
- 2 NVMe 2TB - RAID 0 
1st NVME = KINGSTON 2TB / Read = 3500 Mo/s / Write = 2800 Mo/s      <<<<<<<<<<<<<< NOT ENOUGHT FAST ????
2nd NVME = CRUTIAL  2TB / Read = 4200 Mo/s    |      Write = 5000 Mo/s 

Command :
- ./geth --config ./config.toml --datadir ./node --cache 10646 --rpc.allow-unprotected-txs --txlookuplimit 0 --diffsync --syncmode full --ws --ws.port 8546 --ws.addr localhost console

Info : 
- I always sync my node with only 1 NVME (CRUTIAL) without snapshot and only for 1 week after SSD is full so reinstall it with one more NVME and RAID 0 and without snapshot but it don't work for me actually

<img width="950" alt="Capture d’écran 2022-12-20 144754" src="https://user-images.githubusercontent.com/76543738/208683911-577ac184-5479-443d-a2ae-17a01ced9b96.png">

**Comment by isaacyuno** [comment]
Hi, I need to confirm, are you trying to sync from the Genesis block? If so disk with 5K IOPS is not able to do that. Syncing from the Genesis block will need at least 60K IOPS by recent test. I would suggest you use the official snapshot https://github.com/bnb-chain/bsc-snapshots

**Comment by banlieu451** [comment]
> Hi, I need to confirm, are you trying to sync from the Genesis block? If so disk with 5K IOPS is not able to do that. Syncing from the Genesis block will need at least 60K IOPS by recent test. I would suggest you use the official snapshot https://github.com/bnb-chain/bsc-snapshots

Ok so you say to us : reinstall node with snapshot ? But we always run full node with the lowest nvme (KINGSTON) and without snapshot.
What to understand ? We lost really

**Comment by isaacyuno** [comment]
> > Hi, I need to confirm, are you trying to sync from the Genesis block? If so disk with 5K IOPS is not able to do that. Syncing from the Genesis block will need at least 60K IOPS by recent test. I would suggest you use the official snapshot https://github.com/bnb-chain/bsc-snapshots
> 
> Ok so you say to us : reinstall node with snapshot ? But we always run full node with the lowest nvme (KINGSTON) and without snapshot. What to understand ? We lost really

"always run full node without snapshot." Did you ever get success?

**Comment by banlieu451** [comment]
> > > Hi, I need to confirm, are you trying to sync from the Genesis block? If so disk with 5K IOPS is not able to do that. Syncing from the Genesis block will need at least 60K IOPS by recent test. I would suggest you use the official snapshot https://github.com/bnb-chain/bsc-snapshots
> > 
> > 
> > Ok so you say to us : reinstall node with snapshot ? But we always run full node with the lowest nvme (KINGSTON) and without snapshot. What to understand ? We lost really
> 
> "always run full node without snapshot." Did you ever get success?

Yes of course i run many full node without snapshot ! Only first time it didn't work i don't undertsand what is wrong with our server

**Comment by banlieu451** [comment]
<img width="948" alt="Capture d’écran 2022-12-20 144754" src="https://user-images.githubusercontent.com/76543738/209024353-03b98d37-6932-4915-8d31-f384f9fa737d.png">

**Comment by banlieu451** [comment]
> "run many full node without snapshot" Are they BSC node?

Please dear friend be logic we are in bsc issue not another of course my friend of course

**Comment by banlieu451** [comment]
![Uploading Capture d’écran 2022-12-20 144754.png…]()

**Comment by banlieu451** [comment]
<img width="957" alt="Capture d’écran 2022-12-20 144754" src="https://user-images.githubusercontent.com/76543738/209042139-93a59071-bad7-4b6d-8510-c5e1cb4c38c0.png">

**Comment by isaacyuno** [comment]
Sorry I misread your disk performance. How long have you been syncing?

**Comment by Erik4569** [comment]
Very kong tíme


Dňa št 22. 12. 2022, 4:24 isaacyuno ***@***.***> napísal(a):

**Comment by banlieu451** [comment]
With only the KINGSTON NVME i get sync in  like 7 days from the genesis block and actually with KINGSTON and CRUTIAL NVME in RAID0 im trying to sync from 9 days now still not ...

**Comment by banlieu451** [comment]
<img width="947" alt="Capture d’écran 2022-12-20 144754" src="https://user-images.githubusercontent.com/76543738/209194933-428abd61-43c6-4960-9036-d47eb1e64c1e.png">

**Comment by banlieu451** [comment]
OK i think the problem is from the NVME KINGSTON not enought speed ! ...

**Comment by banlieu451** [comment]
<img width="932" alt="Capture d’écran 2022-12-23 222202" src="https://user-images.githubusercontent.com/76543738/209406604-cbd4c565-2839-41d7-817c-4b800055302e.png">

**Comment by AayushCurious** [comment]
The issue can be solved by trying on multiple nodes!

**Comment by banlieu451** [comment]
> The issue can be solved by trying on multiple nodes!

That is absulutly true !

Actually problem solve when the node switch to the 2nd nvme (CRUTIAL) more fast ... it return false :D

Disk space was 49.5 % on nvme KINGSTON(too low) and right now its 52.2% more 50% so storage switch to nvme CRUTIAL and its good :)
