### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by natrix5369** [bnb-chain/bsc#1255]
Hello. I apologize for creating a request in this repository, but I have not found how to contact you.

You created a thread: https://github.com/thestr4ng3r/chiaki/issues/279

Please contact me on telegram: @natrixon or reply in this thread. Were you able to create bindings for python ?

**Comment by kris-ss** [comment]
Hello. Sorry, this request does not seem to be related to BSC. Please close and post to appropriate repository.

**Comment by natrix5369** [comment]
> Hello. Sorry, this request does not seem to be related to BSC. Please close and post to appropriate repository.

That repository is in the archive. + the author just asked a question. Can I contact the author of that repository?

**Comment by kris-ss** [comment]
I'm afraid I cannot advise on that. What I suggest is you start looking from the new repository location as mentioned here - https://github.com/thestr4ng3r/chiaki
