### ISSUE TITLE
if sync from Snapshot is require init genesis.json?

### ISSUE THREAD

**Issue by RauliIn** [bnb-chain/bsc#1259]
if node sync from Snapshot is require execute the following command?
geth --datadir node init genesis.json

**Comment by kris-ss** [comment]
Hello, no it is not required. You only execute "geth --datadir node init genesis.json" if you want to sync from genesis block.

For syncing from snapshot, please follow - https://docs.bnbchain.org/docs/validator/fullnode/#sync-from-snapshot-recommended

**Comment by RauliIn** [comment]
> Hello, no it is not required. You only execute "geth --datadir node init genesis.json" if you want to sync from genesis block.
> 
> For syncing from snapshot, please follow - https://docs.bnbchain.org/docs/validator/fullnode/#sync-from-snapshot-recommended

ok
