### ISSUE TITLE
Random distribution issue: BEP-131 implementation failed to allocate block producing possibility equally

### ISSUE THREAD

**Issue by 48ClubIan** [bnb-chain/bsc#1272]
We made a statistic on how many blocks are produced by each validators during an entire day. We expected it to be very close numbers but it was not the case.

Data for last 3 days are attached at the bottom of this post.

For cabinet validators, top validator could produce **15%** more blocks than the bottom.
For candidate validators, this gap is even larger, top validator produces **54%** more.

However, as designed in BEP-131, there should be no such difference among validators.
I think this is a bug regarding randomization.

20230107
```
count | addr
-- | --
1331 | 0x2465176c461afb316ebc773c61faee85a6515daa
1299 | 0xe9ae3261a475a27bb1028f140bc2a7c843318afd
1281 | 0x2d4c407bbe49438ed859fe965b140dcf1aab71a9
1277 | 0xcc8e6d00c17eb431350c6c50d8b8f05176b90b11
1266 | 0x70f657164e5b75689b64b7fd1fa275f334f28e18
1260 | 0x0bac492386862ad3df4b666bc096b0505bb694da
1259 | 0xee226379db83cffc681495730c11fdde79ba4c0c
1258 | 0xb218c5d6af1f979ac42bc68d98a5a0d796c6ab01
1251 | 0x3f349bbafec1551819b8be1efea2fc46ca749aa1
1248 | 0xea0a6e3c511bbd10f4519ece37dc24887e11b55d
1242 | 0x685b1ded8013785d6623cc18d214320b6bb64759
1232 | 0x72b61c6014342d914470ec7ac2975be345796c2b
1229 | 0xef0274e31810c9df02f98fafde0f841f4e66a1cd
1223 | 0xbe807dddb074639cd9fa61b47676c064fc50d62c
1223 | 0x7ae2f5b9e386cd1b50a4550696d957cb4900f03a
1206 | 0xa6f79b60359f141df90a0c745125b131caaffd12
1197 | 0x295e26495cef6f69dfa69911d9d8e4f3bbadb89b
1197 | 0xb4dd66d7c2c7e57f628210187192fb89d4b99dd4
1194 | 0x8b6c8fd93d6f4cea42bbb345dbc6f0dfdb5bec73
1175 | 0xe2d3a739effcd3a99387d015e260eefac72ebea1
1163 | 0x61dd481a114a2e761c554b641742c973867899d3
435 | 0x733fda7714a05960b7536330be4dbb135bef0ed6
362 | 0xac0e15a038eedfc68ba3c35c73fed5be4a07afb5
333 | 0x73564052d8e469ed0721c4e53379dc3c91228930
332 | 0xce2fd7544e0b2cc94692d4a704debef7bcb61328
311 | 0xd1d6bf74282782b0b3eb1413c901d6ecf02e8e28
298 | 0x9bb832254baf4e8b4cc26bd2b52b31389b56e98b
297 | 0xfe6e72b223f6d6cf4edc6bff92f30e84b8258249
282 | 0x9f8ccdafcc39f3c7d6ebf637c9151673cbc36b88
```

20230106
```
count | addr
-- | --
1307 | 0xcc8e6d00c17eb431350c6c50d8b8f05176b90b11
1276 | 0xa6f79b60359f141df90a0c745125b131caaffd12
1275 | 0xb218c5d6af1f979ac42bc68d98a5a0d796c6ab01
1272 | 0x8b6c8fd93d6f4cea42bbb345dbc6f0dfdb5bec73
1272 | 0xef0274e31810c9df02f98fafde0f841f4e66a1cd
1270 | 0x7ae2f5b9e386cd1b50a4550696d957cb4900f03a
1265 | 0x3f349bbafec1551819b8be1efea2fc46ca749aa1
1253 | 0x295e26495cef6f69dfa69911d9d8e4f3bbadb89b
1249 | 0x0bac492386862ad3df4b666bc096b0505bb694da
1247 | 0x685b1ded8013785d6623cc18d214320b6bb64759
1244 | 0x72b61c6014342d914470ec7ac2975be345796c2b
1227 | 0x2d4c407bbe49438ed859fe965b140dcf1aab71a9
1224 | 0x70f657164e5b75689b64b7fd1fa275f334f28e18
1218 | 0xea0a6e3c511bbd10f4519ece37dc24887e11b55d
1212 | 0xbe807dddb074639cd9fa61b47676c064fc50d62c
1211 | 0xe9ae3261a475a27bb1028f140bc2a7c843318afd
1188 | 0x2465176c461afb316ebc773c61faee85a6515daa
1172 | 0xee226379db83cffc681495730c11fdde79ba4c0c
1166 | 0xb4dd66d7c2c7e57f628210187192fb89d4b99dd4
1156 | 0x61dd481a114a2e761c554b641742c973867899d3
1155 | 0xac0e15a038eedfc68ba3c35c73fed5be4a07afb5
357 | 0xe2d3a739effcd3a99387d015e260eefac72ebea1
353 | 0x9bb832254baf4e8b4cc26bd2b52b31389b56e98b
336 | 0xfe6e72b223f6d6cf4edc6bff92f30e84b8258249
331 | 0x73564052d8e469ed0721c4e53379dc3c91228930
314 | 0xce2fd7544e0b2cc94692d4a704debef7bcb61328
299 | 0x9f8ccdafcc39f3c7d6ebf637c9151673cbc36b88
287 | 0xd1d6bf74282782b0b3eb1413c901d6ecf02e8e28
276 | 0x733fda7714a05960b7536330be4dbb135bef0ed6
```

20230105
```
count | addr
-- | --
1307 | 0xcc8e6d00c17eb431350c6c50d8b8f05176b90b11
1276 | 0xa6f79b60359f141df90a0c745125b131caaffd12
1275 | 0xb218c5d6af1f979ac42bc68d98a5a0d796c6ab01
1272 | 0x8b6c8fd93d6f4cea42bbb345dbc6f0dfdb5bec73
1272 | 0xef0274e31810c9df02f98fafde0f841f4e66a1cd
1270 | 0x7ae2f5b9e386cd1b50a4550696d957cb4900f03a
1265 | 0x3f349bbafec1551819b8be1efea2fc46ca749aa1
1253 | 0x295e26495cef6f69dfa69911d9d8e4f3bbadb89b
1249 | 0x0bac492386862ad3df4b666bc096b0505bb694da
1247 | 0x685b1ded8013785d6623cc18d214320b6bb64759
1244 | 0x72b61c6014342d914470ec7ac2975be345796c2b
1227 | 0x2d4c407bbe49438ed859fe965b140dcf1aab71a9
1224 | 0x70f657164e5b75689b64b7fd1fa275f334f28e18
1218 | 0xea0a6e3c511bbd10f4519ece37dc24887e11b55d
1212 | 0xbe807dddb074639cd9fa61b47676c064fc50d62c
1211 | 0xe9ae3261a475a27bb1028f140bc2a7c843318afd
1188 | 0x2465176c461afb316ebc773c61faee85a6515daa
1172 | 0xee226379db83cffc681495730c11fdde79ba4c0c
1166 | 0xb4dd66d7c2c7e57f628210187192fb89d4b99dd4
1156 | 0x61dd481a114a2e761c554b641742c973867899d3
1155 | 0xac0e15a038eedfc68ba3c35c73fed5be4a07afb5
357 | 0xe2d3a739effcd3a99387d015e260eefac72ebea1
353 | 0x9bb832254baf4e8b4cc26bd2b52b31389b56e98b
336 | 0xfe6e72b223f6d6cf4edc6bff92f30e84b8258249
331 | 0x73564052d8e469ed0721c4e53379dc3c91228930
314 | 0xce2fd7544e0b2cc94692d4a704debef7bcb61328
299 | 0x9f8ccdafcc39f3c7d6ebf637c9151673cbc36b88
287 | 0xd1d6bf74282782b0b3eb1413c901d6ecf02e8e28
276 | 0x733fda7714a05960b7536330be4dbb135bef0ed6
```

**Comment by zzphust** [comment]
> We made a statistic on how many blocks are produced by each validators during an entire day. We expected it to be very close numbers but it was not the case.
> 
> Data for last 3 days are attached at the bottom of this post.
> 
> For cabinet validators, top validator could produce **15%** more blocks than the bottom. For candidate validators, this gap is even larger, top validator produces **54%** more.
> 
> However, as designed in BEP-131, there should be no such difference among validators. I think this is a bug regarding randomization.
> 
> 20230107
> 
> ```
> count | addr
> -- | --
> 1331 | 0x2465176c461afb316ebc773c61faee85a6515daa
> 1299 | 0xe9ae3261a475a27bb1028f140bc2a7c843318afd
> 1281 | 0x2d4c407bbe49438ed859fe965b140dcf1aab71a9
> 1277 | 0xcc8e6d00c17eb431350c6c50d8b8f05176b90b11
> 1266 | 0x70f657164e5b75689b64b7fd1fa275f334f28e18
> 1260 | 0x0bac492386862ad3df4b666bc096b0505bb694da
> 1259 | 0xee226379db83cffc681495730c11fdde79ba4c0c
> 1258 | 0xb218c5d6af1f979ac42bc68d98a5a0d796c6ab01
> 1251 | 0x3f349bbafec1551819b8be1efea2fc46ca749aa1
> 1248 | 0xea0a6e3c511bbd10f4519ece37dc24887e11b55d
> 1242 | 0x685b1ded8013785d6623cc18d214320b6bb64759
> 1232 | 0x72b61c6014342d914470ec7ac2975be345796c2b
> 1229 | 0xef0274e31810c9df02f98fafde0f841f4e66a1cd
> 1223 | 0xbe807dddb074639cd9fa61b47676c064fc50d62c
> 1223 | 0x7ae2f5b9e386cd1b50a4550696d957cb4900f03a
> 1206 | 0xa6f79b60359f141df90a0c745125b131caaffd12
> 1197 | 0x295e26495cef6f69dfa69911d9d8e4f3bbadb89b
> 1197 | 0xb4dd66d7c2c7e57f628210187192fb89d4b99dd4
> 1194 | 0x8b6c8fd93d6f4cea42bbb345dbc6f0dfdb5bec73
> 1175 | 0xe2d3a739effcd3a99387d015e260eefac72ebea1
> 1163 | 0x61dd481a114a2e761c554b641742c973867899d3
> 435 | 0x733fda7714a05960b7536330be4dbb135bef0ed6
> 362 | 0xac0e15a038eedfc68ba3c35c73fed5be4a07afb5
> 333 | 0x73564052d8e469ed0721c4e53379dc3c91228930
> 332 | 0xce2fd7544e0b2cc94692d4a704debef7bcb61328
> 311 | 0xd1d6bf74282782b0b3eb1413c901d6ecf02e8e28
> 298 | 0x9bb832254baf4e8b4cc26bd2b52b31389b56e98b
> 297 | 0xfe6e72b223f6d6cf4edc6bff92f30e84b8258249
> 282 | 0x9f8ccdafcc39f3c7d6ebf637c9151673cbc36b88
> ```
> 
> 20230106
> 
> ```
> count | addr
> -- | --
> 1307 | 0xcc8e6d00c17eb431350c6c50d8b8f05176b90b11
> 1276 | 0xa6f79b60359f141df90a0c745125b131caaffd12
> 1275 | 0xb218c5d6af1f979ac42bc68d98a5a0d796c6ab01
> 1272 | 0x8b6c8fd93d6f4cea42bbb345dbc6f0dfdb5bec73
> 1272 | 0xef0274e31810c9df02f98fafde0f841f4e66a1cd
> 1270 | 0x7ae2f5b9e386cd1b50a4550696d957cb4900f03a
> 1265 | 0x3f349bbafec1551819b8be1efea2fc46ca749aa1
> 1253 | 0x295e26495cef6f69dfa69911d9d8e4f3bbadb89b
> 1249 | 0x0bac492386862ad3df4b666bc096b0505bb694da
> 1247 | 0x685b1ded8013785d6623cc18d214320b6bb64759
> 1244 | 0x72b61c6014342d914470ec7ac2975be345796c2b
> 1227 | 0x2d4c407bbe49438ed859fe965b140dcf1aab71a9
> 1224 | 0x70f657164e5b75689b64b7fd1fa275f334f28e18
> 1218 | 0xea0a6e3c511bbd10f4519ece37dc24887e11b55d
> 1212 | 0xbe807dddb074639cd9fa61b47676c064fc50d62c
> 1211 | 0xe9ae3261a475a27bb1028f140bc2a7c843318afd
> 1188 | 0x2465176c461afb316ebc773c61faee85a6515daa
> 1172 | 0xee226379db83cffc681495730c11fdde79ba4c0c
> 1166 | 0xb4dd66d7c2c7e57f628210187192fb89d4b99dd4
> 1156 | 0x61dd481a114a2e761c554b641742c973867899d3
> 1155 | 0xac0e15a038eedfc68ba3c35c73fed5be4a07afb5
> 357 | 0xe2d3a739effcd3a99387d015e260eefac72ebea1
> 353 | 0x9bb832254baf4e8b4cc26bd2b52b31389b56e98b
> 336 | 0xfe6e72b223f6d6cf4edc6bff92f30e84b8258249
> 331 | 0x73564052d8e469ed0721c4e53379dc3c91228930
> 314 | 0xce2fd7544e0b2cc94692d4a704debef7bcb61328
> 299 | 0x9f8ccdafcc39f3c7d6ebf637c9151673cbc36b88
> 287 | 0xd1d6bf74282782b0b3eb1413c901d6ecf02e8e28
> 276 | 0x733fda7714a05960b7536330be4dbb135bef0ed6
> ```
> 
> 20230105
> 
> ```
> count | addr
> -- | --
> 1307 | 0xcc8e6d00c17eb431350c6c50d8b8f05176b90b11
> 1276 | 0xa6f79b60359f141df90a0c745125b131caaffd12
> 1275 | 0xb218c5d6af1f979ac42bc68d98a5a0d796c6ab01
> 1272 | 0x8b6c8fd93d6f4cea42bbb345dbc6f0dfdb5bec73
> 1272 | 0xef0274e31810c9df02f98fafde0f841f4e66a1cd
> 1270 | 0x7ae2f5b9e386cd1b50a4550696d957cb4900f03a
> 1265 | 0x3f349bbafec1551819b8be1efea2fc46ca749aa1
> 1253 | 0x295e26495cef6f69dfa69911d9d8e4f3bbadb89b
> 1249 | 0x0bac492386862ad3df4b666bc096b0505bb694da
> 1247 | 0x685b1ded8013785d6623cc18d214320b6bb64759
> 1244 | 0x72b61c6014342d914470ec7ac2975be345796c2b
> 1227 | 0x2d4c407bbe49438ed859fe965b140dcf1aab71a9
> 1224 | 0x70f657164e5b75689b64b7fd1fa275f334f28e18
> 1218 | 0xea0a6e3c511bbd10f4519ece37dc24887e11b55d
> 1212 | 0xbe807dddb074639cd9fa61b47676c064fc50d62c
> 1211 | 0xe9ae3261a475a27bb1028f140bc2a7c843318afd
> 1188 | 0x2465176c461afb316ebc773c61faee85a6515daa
> 1172 | 0xee226379db83cffc681495730c11fdde79ba4c0c
> 1166 | 0xb4dd66d7c2c7e57f628210187192fb89d4b99dd4
> 1156 | 0x61dd481a114a2e761c554b641742c973867899d3
> 1155 | 0xac0e15a038eedfc68ba3c35c73fed5be4a07afb5
> 357 | 0xe2d3a739effcd3a99387d015e260eefac72ebea1
> 353 | 0x9bb832254baf4e8b4cc26bd2b52b31389b56e98b
> 336 | 0xfe6e72b223f6d6cf4edc6bff92f30e84b8258249
> 331 | 0x73564052d8e469ed0721c4e53379dc3c91228930
> 314 | 0xce2fd7544e0b2cc94692d4a704debef7bcb61328
> 299 | 0x9f8ccdafcc39f3c7d6ebf637c9151673cbc36b88
> 287 | 0xd1d6bf74282782b0b3eb1413c901d6ecf02e8e28
> 276 | 0x733fda7714a05960b7536330be4dbb135bef0ed6
> ```

**Comment by zzphust** [comment]
The motivation for choosing candidates randomly instead of by round-robin is to avoid the candidate being selected in always the same subset. It is to reduce the chance of collusion and improve the security of the network.

In order to ensure that the randomness can not be manipulated, epochNumber = BlockHeight / 200 is chosen as the random source. epochNumber is a fixed value within one epoch and is incremental across the epoch. The randomness can actually be predicted. But since consensusAddr are limited to change and epochNumber is incremental across the epoch, the randomness can not be manipulated by anyone.

The daily statistical data is counted here, but when the data of the last 7 days and the last month are counted, the gap between the cabinet validators is actually very small. In the last 7 days, the NO.1 validator produced 4% more blocks than the NO.20 and the NO.23 validator produced 6% more blocks than the NO.29.  As we think that the validators ranked 21 to 22 both have a high chance to become cabinet validators, so their counts have no reference value. So we think it will be fair in the long run.

https://bscscan.com/validators

<img width="972" alt="截屏2023-01-12 16 07 27" src="https://user-images.githubusercontent.com/45141191/212037275-8c1645ea-3fdd-4858-a93b-2be62e332b0a.png">

**Comment by 48ClubIan** [comment]
So we agree to the fact that producing opportunity is not fairly distributed in daily-basis, although I agree that the random algo is not manipulated. One day is just not long enough.

It may also be true that it will be fair in long run. However the validator set doesn't last for long run, it could change every day. Since the consensus doesn't guarantee a stable validators set for long run, I don't think it is a good idea to rely on statisticly fairness in long run.

Do you mind elaborate why round-robin is not good?  To be specific, I mean

'''
for every 200blocks-epoch:
    select 19 out of working cabinet validators following round-robin
    select 2 out of working candidate validators following round-robin
    19 + 2 => 21-validator set
'''
It doesn't bring collusion nor daily unfairness. So far so perfect.

**Comment by zzphust** [comment]
Using round-robin will make the candidates selected for each epoch fixed, and the attacker can control it at a lower cost than using random.

**Comment by guagualvcha** [comment]
@48ClubIan any more comments?

**Comment by guagualvcha** [comment]
I will close this issue, since I have talked with @48ClubIan, I thought we reach a consensus that the current design make sense. Will close this, @48ClubIan  please open new one if any further concern, thanks.
