### ISSUE TITLE
Get older data with no MTP data node ?

### ISSUE THREAD

**Issue by liczn** [bnb-chain/bsc#1273]
Hello, I run a node with the `--tries-verify-mode=none` option and I am not exactly sure of what it gets rid of.

I am trying to get data from a contract view method at an older block state but get an error. I use the ethers library for that in this way:
```contract.foo(param, { blockTag: 24231512 })```

Note that the syntax works well with a nodereal node.

Is it normal that I get an error because older states are not kept by this kind of node ? Or is there something else ?

**Comment by kris-ss** [comment]
A node running with --tries-verify-mode=none does not perform merkle state root verification at all and does not contain MPT data.

The nodereal node you tested this probably was a full node that's why it worked. 

For more details, please check here - https://docs.bnbchain.org/docs/BSC-separate-node#roles

**Comment by liczn** [comment]
Okay because from my understanding, the node with --tries-verify-mode=none doesn't have data for state consistency checks but has all the rest, including state data. Am I wrong ?

**Comment by kris-ss** [comment]
Yes, you are right. Can you share your full start-up command please? Also, when you set up your node, did you use the https://github.com/48Club/bsc-snapshots here?

**Comment by liczn** [comment]
Here is my startup command
`./geth_bsc --config ./config.toml --datadir ./bsc --http --http.api admin,net,eth --ws --cache 6000 --syncmode full --tries-verify-mode none --pruneancient=true --diffblock=5000 --txlookuplimit 0 --rpc.allow-unprotected-txs`
I did use the snapshot from them

**Comment by kris-ss** [comment]
Got that. From your command, take note of the flag --pruneancient=true. If this flag is used, then your node will only keep latest 90k blocks (~3 days worth). So you will also not be able to search for blocks older than 90k.

**Comment by liczn** [comment]
Indeed I have some of the latest blocks data available. More only something like the 100 last.

**Comment by CocoStarZ** [comment]
No more follow-up, close it for now
