### ISSUE TITLE
Monitoring mempool as blocknative with logs 'pending Tx'

### ISSUE THREAD

**Issue by banlieu451** [bnb-chain/bsc#1276]
Hello everybody, i have a bug in my BSC FULL NODE

My geth command is : 
`./geth --config ./config.toml --datadir ./node --cache 18000 --rpc.allow-unprotected-txs --txlookuplimit 0 --maxpeers 60000 --syncmode full --ws --ws.port 8546 --ws.addr localhost console`

When i'm listening mempool for pending TX it return me this : 

<img width="354" alt="a" src="https://user-images.githubusercontent.com/76543738/212944199-61fd307f-cbe4-4ecd-ad87-7f7e418e491f.png">

What is geth command to increase my node and return me **path** like this : 

![b](https://user-images.githubusercontent.com/76543738/212945263-812e2408-d4a1-45fa-ba72-ac3bfe42bcee.jpg)

As you can see we can monitoring events and logs so how can i do it to fix the bug please ?

**Comment by iGloom** [comment]
Blocknative just parses the input for you, its not part of core functionality. 
All this info you want can be found inside the input string - find method signature and decode it.

**Comment by banlieu451** [comment]
> Blocknative just parses the input for you, its not part of core functionality. All this info you want can be found inside the input string - find method signature and decode it.

how can i parse the input from a 'pending Tx' as you say please ???

**Comment by guagualvcha** [comment]
@banlieu451  May I ask how you get the second figure? It seems not from geth directly.

**Comment by guagualvcha** [comment]
The transaction in the tx pool will not be executed and so no no logs at all,  have to modify the geth to implement this.

**Comment by iGloom** [comment]
> @banlieu451 May I ask how you get the second figure? It seems not from geth directly.

The second figure is custom tx decoder from blocknative.com mempool explorer 





> The transaction in the tx pool will not be executed and so no no logs at all, have to modify the geth to implement this.

In fact, there's a way, I'm personally using https://stackoverflow.com/questions/72064656/extracting-emitted-events-logs-from-geth-transaction-trace-debug-tracecall





> Thanks but nope because we can decode logs as pending but how ?
> 
> We can decode input data for sure i know how to do it but i'm seaching to get **logs as pending** as the picture or monitoring constract function, i know how to monitoring USDT transfert for example but i want monitoring **function** from a contract as **pending** i know this is possible **without decoding** input data this is the bug actually i'm **trying** to solve because some geth node provide logs like the picture

Same link for you, you can get logs using debug_traceCall https://stackoverflow.com/questions/72064656/extracting-emitted-events-logs-from-geth-transaction-trace-debug-tracecall

**Comment by banlieu451** [comment]
> La transaction dans le pool tx ne sera pas exécutée et donc pas de journaux du tout, vous devez modifier le geth pour l'implémenter.

How to proceed this please ?

**Comment by banlieu451** [comment]
> > @banlieu451Puis-je vous demander comment vous obtenez le deuxième chiffre ? Cela ne semble pas directement de geth.
> 
> Le deuxième chiffre est le décodeur tx personnalisé de l'explorateur mempool blocknative.com
> 
> > La transaction dans le pool tx ne sera pas exécutée et donc pas de journaux du tout, vous devez modifier le geth pour l'implémenter.
> 
> En fait, il y a un moyen, j'utilise personnellement https://stackoverflow.com/questions/72064656/extracting-emitted-events-logs-from-geth-transaction-trace-debug-tracecall
> 
> > Merci mais non car on peut décoder les logs en attente mais comment ?
> > Nous pouvons décoder les données d'entrée à coup sûr, je sais comment le faire, mais je cherche à obtenir des **journaux aussi en attente** que l'image ou la fonction de contrat de surveillance, je sais comment surveiller le transfert USDT par exemple, mais je veux la **fonction** de surveillance d'un contrat en **attente** je sais que c'est possible **sans décoder** les données d'entrée c'est le bogue que **j'essaie** de résoudre car certains nœuds geth fournissent des journaux comme l'image
> 
> Même lien pour vous, vous pouvez obtenir des journaux en utilisant debug_traceCall https://stackoverflow.com/questions/72064656/extracting-emitted-events-logs-from-geth-transaction-trace-debug-tracecall

I'm gonna check this let me come back

**Comment by banlieu451** [comment]
> @banlieu451 May I ask how you get the second figure? It seems not from geth directly.

Get it from blocknative mempool pending tx example

**Comment by banlieu451** [comment]
Still cannot see events following your tutorial there is not enought code please provide a full code working

**Comment by banlieu451** [comment]
up

**Comment by CocoStarZ** [comment]
> up

Do you still have the problem? if no will close the issue
