### ISSUE TITLE
Endless "State heal in progress"

### ISSUE THREAD

**Issue by kapisolec** [bnb-chain/bsc#1277]
Hello, I've been trying to synchronize my fullnode from scratch for about 3 weeks now. Every time I try to do that, after it gets really close to the current highest block it starts spitting errors like `\n########## BAD BLOCK #########\n` and after that it rewinds the blockchain. Despite this bad block error, I constantly get `State heal in progres` warn, and I dont really know why. I tried syncing the node from scratch as well as from the snapshot - the same thing happens. Thats my startup command:

```
--cache 8000 --txpool.reannouncetime 5m --rpc.allow-unprotected-txs --txlookuplimit 0 --tries-verify-mode none --pprof.addr 0.0.0.0 --metrics --pprof --http --http.addr 0.0.0.0 --http.corsdomain '*' --http.api eth,net,web3,txpool,debug --ws --ws.addr 0.0.0.0 --ws.origins '*' --ws.api eth,net,web3,txpool,debug --nousb --diffsync --snapshot=false
```
And it's been working before (like 6 months ago)

My machine is:
* 128 GB DDR4 ECC
* 8TB SSD NVMe
* AMD Ryzen™ 9 5950X
* Guaranteed 1Gbit/s bandwith

**Comment by ZiyuanStar** [comment]
dup issue, pls refer to this:
https://github.com/bnb-chain/bsc/issues/1198

**Comment by guagualvcha** [comment]
Please use snapshot directly: https://github.com/bnb-chain/bsc-snapshots
