### ISSUE TITLE
how to add Sentinel Node

### ISSUE THREAD

**Issue by xiaozanooo** [bnb-chain/bsc#1278]
how to add Sentinel Node or validators Node

**Comment by kris-ss** [comment]
Hi @xiaozanooo please refer to https://docs.bnbchain.org/docs/validator/run-val for the steps on how to run a validator node. 
You can also reach out to our discord (https://discord.gg/bnbchain) channel #validator-support in case you have further questions.

**Comment by guagualvcha** [comment]
Or this doc: https://docs.bnbchain.org/docs/validator/create-val
