### ISSUE TITLE
I have downloaded all the latest snap data but still it's been 10 hours my node is not fully updated?

### ISSUE THREAD

**Issue by EngineBusd** [bnb-chain/bsc#1280]
What I have done is follow all the rules of them.
https://docs.bnbchain.org/docs/validator/fullnode/

As I extracted the snaps I renamed them as node. Inside it was holding a big file called chaindata. 

then I have run 
./geth --config ./config.toml --datadir ./node/chaindata  --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0

Now it's been 10 hours and it's still showing me that. 
"
t=2023-01-23T15:01:51+0000 lvl=info msg="Imported new state entries"             count=768  elapsed=2.296ms     processed=260,910,910 pending=27199 trieretry=0   coderetry=0 duplicate=199 unexpected=573
t=2023-01-23T15:01:51+0000 lvl=info msg="Imported new state entries"             count=1152 elapsed=3.860ms     processed=260,912,062 pending=26923 trieretry=0   coderetry=0 duplicate=199 unexpected=573

"
I am confused what should I do now? wait or i am doing something wrong any is here who can guide me?

**Comment by kris-ss** [comment]
Hello, the --datadir should point to the folder where the chaindata is in. So in your case, it should be:

./geth --config ./config.toml --datadir ./node--cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0

Please try with above and let us know.

**Comment by EngineBusd** [comment]
> Hello, the --datadir should point to the folder where the chaindata is in. So in your case, it should be:
> 
> ./geth --config ./config.toml --datadir ./node--cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0
> 
> Please try with above and let us know.

Suppose if my snapchat folder name is snapData so I should run this command?
./geth --config ./config.toml --datadir ./snapData --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0

**Comment by EngineBusd** [comment]
> ./geth --config ./config.toml --datadir ./snapData --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0

I am facing now this error
INFO [01-23|15:47:19.166] Starting Geth on Ethereum mainnet... 
INFO [01-23|15:47:19.169] Maximum peer count                       ETH=30 LES=0 total=30
INFO [01-23|15:47:19.170] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [01-23|15:47:19.170] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable 
INFO [01-23|15:47:19.170] Set global gas cap                       cap=50,000,000
INFO [01-23|15:47:19.170] Allocated trie memory caches             clean=1.17GiB dirty=1.95GiB
WARN [01-23|15:47:19.170] Using deprecated resource file /root/bsc/geth/chaindata, please move this file to the 'geth' subdirectory of datadir. 
INFO [01-23|15:47:19.170] Allocated cache and file handles         database=/root/bsc/geth/chaindata cache=3.12GiB handles=524,288
WARN [01-23|15:47:20.690] prune ancinet flag is set, may start fail, can add pruneancient parameter resolve 
Fatal: Failed to register the Ethereum service: pruneancient was set, please add pruneancient parameter

**Comment by kris-ss** [comment]
Hello, which snapshot did you use? Is it the bnb48club one? If yes, please use the suggested flags for the bnb48club snapshot (https://github.com/48Club/bsc-snapshots#flags)

--txlookuplimit=0 --syncmode=full --tries-verify-mode=none --pruneancient=true --diffblock=5000

**Comment by EngineBusd** [comment]
> Hello, which snapshot did you use? Is it the bnb48club one? If yes, please use the suggested flags for the bnb48club snapshot (https://github.com/48Club/bsc-snapshots#flags)
> 
> --txlookuplimit=0 --syncmode=full --tries-verify-mode=none --pruneancient=true --diffblock=5000

Okay I have done it's fully done but I want to use my ws IP in my dapps how to use it? and how would I run the node in the background?

**Comment by EngineBusd** [comment]
Helped and resolved my error with --txlookuplimit=0 --syncmode=full --tries-verify-mode=none --pruneancient=true --diffblock=5000
