### ISSUE TITLE
My Node is Fully  Synchronize but it's running on my Ubuntu VPS how should i run in the background?  

### ISSUE THREAD

**Issue by EngineBusd** [bnb-chain/bsc#1281]
I want to run my VPS in the background so I can go and do more things with my VPS. 

Also anybody would help me how to enable my ws and https so I can use in my dapps?

I have downloaded the snapshot and now my node is completely running. I just need a guide how to run in the background and also I need a guide about WS and HTTPS so I can use these URL in my DAPPS

**Comment by isaacyuno** [comment]
For running in background, you could use "nohup &" with your geth. See https://www.digitalocean.com/community/tutorials/nohup-command-in-linux#:~:text=Output-,Starting%20a%20process%20in%20the%20background%20using%20Nohup,-To%20start%20a

To enable ws and https, add these flags to your geth command 
--http --http.port 8545
--ws --ws.port 8546 --ws.api eth,net,web3
You might need to change HTTPHost to "0.0.0.0" in [Node] section in config.toml file first if your dapp is from other network. port 8545/8546 are customizable.
See more from https://geth.ethereum.org/docs/interacting-with-geth/rpc#http-server
