### ISSUE TITLE
Geth attach with Visual Studio Code

### ISSUE THREAD

**Issue by banlieu451** [bnb-chain/bsc#1283]
Hello everybody, hope al are good ?
I have a pb with my BSC FULL NODE i can't connect it with my **nodeJs files**

My geth command is : `./geth console --config ./config.toml --datadir ./node --cache 8000 --maxpeers 500000000 --rpc.allow-unprotected-txs --txlookuplimit 0 --syncmode full --ws --ws.addr **0.0.0.0** authws.port 8546 --wsorigins '*'  --wsapi web3,shh,txpool,debug
` 

My server have : ssh **22** / port **8546** 

My files return : 
<img width="678" alt="Capture d’écran 2023-01-26 012700" src="https://user-images.githubusercontent.com/76543738/214726731-eeb303ce-ee20-4f9b-8d09-02bc2ec3af7c.png">

I **can't connect** with my node can someone explain me please why ?

Sincerely Mike

**Comment by yutianwu** [comment]
can you try `./geth attach ws://urip` first

**Comment by banlieu451** [comment]
> 

Thanks for answer my command is in **ROOT**: 
`./geth attach ws://IPoFNODE:8546`

Geth return me : 
`Fatal: Unable to attach to remote geth: dial tcp      IPoFNODE:8546:        connect: connection refused`

My geth rules : 
<img width="384" alt="Capture d’écran 2023-01-26 012700" src="https://user-images.githubusercontent.com/76543738/214887627-b491d52b-7907-49b0-8897-5df40e8b17a0.png">

**Comment by banlieu451** [comment]
> try start ur node with simple flags like `--ws --ws.port 8546 --ws.addr 0.0.0.0`

I do it and right now :  

- I **can't** attach with my IP when doing :
`./geth attach ws://MYIP:8546` _i get_  `Fatal: Unable to attach to remote geth: dial tcp MYIP:8546: connect: connection refused`

- I **can** attach to my local when doing :
`./geth attach ws://127.0.0.1:8546`  its ok but when i call from my JS : 

_________________________________________________

i do : 
<img width="530" alt="1" src="https://user-images.githubusercontent.com/76543738/215356222-5ce17c54-37fb-48b3-87fe-324cfe7c6cbb.png">
 
i get : 
<img width="550" alt="2" src="https://user-images.githubusercontent.com/76543738/215356250-c1dfe680-50bd-4cbd-8258-08756b20e67f.png">

**Comment by CocoStarZ** [comment]
> banlieu451

Do you still have the issue? if no will close it
