### ISSUE TITLE
Consider to follow strict tag / release naming pattern

### ISSUE THREAD

**Issue by kucharskim** [bnb-chain/bsc#1285]
# Rationale

We have an automation building framework which follows strict naming pattern, what tags in particular repo to build. 

It is not exactly, but something a long the lines of `git tag | grep -e '^v[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$' | sort -V` and if build artifact is missing on our infrastructure, it's build.

Recent release is not following that pattern and was not automatically rebuild on our end:
```
$ git tag | sort -V | tail -n1 
v1.1.18_hf
```

We kindly request, if you could follow strict naming pattern of '^v[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$' in your release process, not matter how small or big a change between releases is. From human perspective we don't believe it makes any difference, but from automation perspective it makes for us huge difference.

**Comment by kucharskim** [comment]
This came to our attention as we didn't receive Prometheus fix from https://github.com/bnb-chain/bsc/releases/tag/v1.1.18_hf as it was not automatically built.

**Comment by brilliant-lx** [comment]
thank you for your advice, I think we can follow the tag naming rule.

**Comment by kucharskim** [comment]
> `v1.1.18_hf` will have to be named like `v1.1.19`

If you would implement in your process naming pattern which I mentioned here, yes that would be the case, next release would be `v1.1.19`. We don't need `v1.1.19` as we manually worked around the issue on our end, but this was just for your future consideration.

I botched the regex in the description, in the second instance of the regex, but I imagine you get the idea (`^v[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$`)
