### ISSUE TITLE
Request old block logs, eth_getLogs adds address parameter function does not return

### ISSUE THREAD

**Issue by daog1** [bnb-chain/bsc#1291]
#### System information

Geth version: `1.1.18-cb9e50bd`
OS & Version: Linux
Commit hash : (if `develop`)

#### function returns immediately
````
curl -s -X POST -H "Content-Type":application/json --data '{"jsonrpc":"2.0","id":1,"method":"eth_getLogs","params":[{"fromBlock":"0x171a812","toBlock":"0x171abf9","topics":[]}]}' localhost:3104
````
#### function does not return，added address parameter
````
curl -s -X POST -H "Content-Type":application/json --data '{"jsonrpc":"2.0","id":1,"method":"eth_getLogs","params":[{"fromBlock":"0x171a812","toBlock":"0x171abf9","address":"0x1781b39517080eBBEB8f0d66Da204B2C26f814fc","topics":[]}]}' localhost:31041

````

When submitting logs: please submit them as text and not screenshots.

**Comment by daog1** [comment]
The main reason is that the function does not return, you can use an event address, such as: 0x5dA0E4398c18FFc2FeBd3cc390c1e2f1Ddc092F2,
If you don't want the address, he will reply immediately:
{"jsonrpc":"2.0","id":1,"result":[]}

**Comment by isaacyuno** [comment]
The function does not return because there is no data to return with your parameters
`{"fromBlock":"0x171a812","toBlock":"0x171abf9","address":"0x1781b39517080eBBEB8f0d66Da204B2C26f814fc","topics":[]}]}`

Use your second example 0x5dA0E4398c18FFc2FeBd3cc390c1e2f1Ddc092F2, this will return because this SC generated events during below blocks
`curl -s -X POST -H "Content-Type":application/json --data '{"jsonrpc":"2.0","id":1,"method":"eth_getLogs","params":[{"fromBlock":"0x181c9dc","toBlock":"0x181caba","address":"0x5dA0E4398c18FFc2FeBd3cc390c1e2f1Ddc092F2","topics":[]}]}' localhost:[your port]`

**Comment by daog1** [comment]
> 0x1781b39517080eBBEB8f0d66Da204B2C26f814fc

Old block, instead of using new one, my new block chain can also return, my node has used Prune to prune old data

**Comment by isaacyuno** [comment]
> > 0x1781b39517080eBBEB8f0d66Da204B2C26f814fc
> 
> Old block, instead of using new one, my new block chain can also return, my node has used Prune to prune old data

Not sure if I'm understanding you correctly, if you are querying events from SC 0x1781b39517080eBBEB8f0d66Da204B2C26f814fc with block range 0x171a812 to 0x171abf9, you won't get a result because this SC didn't generate any events. It is not related to your node being pruned or not. Below is a public RPC with old data that you could try
curl -s -X POST -H "Content-Type":application/json --data '{"jsonrpc":"2.0","id":1,"method":"eth_getLogs","params":[{"fromBlock":"0x171a812","toBlock":"0x171abf9","address":"0x1781b39517080eBBEB8f0d66Da204B2C26f814fc","topics":[]}]}' 'https://bscrpc.com'

**Comment by daog1** [comment]
> Not sure if I'm understanding you correctly, if you are querying events from SC 0x1781b39517080eBBEB8f0d66Da204B2C26f814fc with block range 0x171a812 to 0x171abf9, you won't get a result because this SC didn't generate any events. It is not related to your node being pruned or not. Below is a public RPC with old data that you could try
> curl -s -X POST -H "Content-Type":application/json --data '{"jsonrpc":"2.0","id":1,"method":"eth_getLogs","params":[{"fromBlock":"0x171a812","toBlock":"0x171abf9","address":"0x1781b39517080eBBEB8f0d66Da204B2C26f814fc","topics":[]}]}'

I mean, my own node calls this rpc, it doesn’t return, it’s not that there is no result

**Comment by isaacyuno** [comment]
On any other nodes, won't have results as well for `{"fromBlock":"0x171a812","toBlock":"0x171abf9","address":"0x1781b39517080eBBEB8f0d66Da204B2C26f814fc","topics":[]}`

**Comment by daog1** [comment]
> "address":"0x1781b39517080eBBEB8f0d66Da204B2C26f814fc"
What I mean is this, look at the screenshot I sent, if I don’t ctrl+c, curl won’t end
![1675235499132](https://user-images.githubusercontent.com/1438562/215975645-8f9678db-ef5d-40ae-837c-3c2361d43f0d.png)

**Comment by isaacyuno** [comment]
ok, got your point. You could turn your log level to debug and restart, call again and see what you get in your bsc.log see if you could figure out why it is hung

**Comment by daog1** [comment]
> ok, got your point. You could turn your log level to debug and restart, call again and see what you get in your bsc.log see if you could figure out why it is hung

`
Feb 01 07:31:24 node-Buffalo-Sola-1 geth_bsc[1919715]: DEBUG[02-01|07:31:24.048] Fetching batch of transactions           id=a7a6748b61f7cd9b conn=dyndial         count=1
Feb 01 07:31:24 node-Buffalo-Sola-1 geth_bsc[1919715]: DEBUG[02-01|07:31:24.050] Executing EVM call finished              runtime=92.880556ms
Feb 01 07:31:24 node-Buffalo-Sola-1 geth_bsc[1919715]: DEBUG[02-01|07:31:24.050] Served eth_call                          conn=127.0.0.1:44553 reqid=000001860be321400f27238f7d75 duration=93.493088ms
Feb 01 07:31:24 node-Buffalo-Sola-1 geth_bsc[1919715]: WARN [02-01|07:31:24.127] Served eth_getLogs                       conn=127.0.0.1:24309 reqid=000001860be321400feb238f7da4 t="220.645µs" err="unknown block"                          X-Forwarded-For=nil
Feb 01 07:31:24 node-Buffalo-Sola-1 geth_bsc[1919715]: WARN [02-01|07:31:24.127] Served eth_getLogs                       conn=127.0.0.1:24309 reqid=000001860be321400feb238f7da4 duration="219.102µs"  err="unknown block"
`
startup parameters
`-diffsync --txlookuplimit=0 --tries-verify-mode=none --pruneancient=true --diffblock=5000`

**Comment by kyrie-yl** [comment]
> > ok, got your point. You could turn your log level to debug and restart, call again and see what you get in your bsc.log see if you could figure out why it is hung
> 
> `Feb 01 07:31:24 node-Buffalo-Sola-1 geth_bsc[1919715]: DEBUG[02-01|07:31:24.048] Fetching batch of transactions id=a7a6748b61f7cd9b conn=dyndial count=1 Feb 01 07:31:24 node-Buffalo-Sola-1 geth_bsc[1919715]: DEBUG[02-01|07:31:24.050] Executing EVM call finished runtime=92.880556ms Feb 01 07:31:24 node-Buffalo-Sola-1 geth_bsc[1919715]: DEBUG[02-01|07:31:24.050] Served eth_call conn=127.0.0.1:44553 reqid=000001860be321400f27238f7d75 duration=93.493088ms Feb 01 07:31:24 node-Buffalo-Sola-1 geth_bsc[1919715]: WARN [02-01|07:31:24.127] Served eth_getLogs conn=127.0.0.1:24309 reqid=000001860be321400feb238f7da4 t="220.645µs" err="unknown block" X-Forwarded-For=nil Feb 01 07:31:24 node-Buffalo-Sola-1 geth_bsc[1919715]: WARN [02-01|07:31:24.127] Served eth_getLogs conn=127.0.0.1:24309 reqid=000001860be321400feb238f7da4 duration="219.102µs" err="unknown block"` startup parameters `-diffsync --txlookuplimit=0 --tries-verify-mode=none --pruneancient=true --diffblock=5000`

Can you provide the profile of routines when hung after call your command?

**Comment by daog1** [comment]
> > > ok, got your point. You could turn your log level to debug and restart, call again and see what you get in your bsc.log see if you could figure out why it is hung
> > 
> > 
> > `Feb 01 07:31:24 node-Buffalo-Sola-1 geth_bsc[1919715]: DEBUG[02-01|07:31:24.048] Fetching batch of transactions id=a7a6748b61f7cd9b conn=dyndial count=1 Feb 01 07:31:24 node-Buffalo-Sola-1 geth_bsc[1919715]: DEBUG[02-01|07:31:24.050] Executing EVM call finished runtime=92.880556ms Feb 01 07:31:24 node-Buffalo-Sola-1 geth_bsc[1919715]: DEBUG[02-01|07:31:24.050] Served eth_call conn=127.0.0.1:44553 reqid=000001860be321400f27238f7d75 duration=93.493088ms Feb 01 07:31:24 node-Buffalo-Sola-1 geth_bsc[1919715]: WARN [02-01|07:31:24.127] Served eth_getLogs conn=127.0.0.1:24309 reqid=000001860be321400feb238f7da4 t="220.645µs" err="unknown block" X-Forwarded-For=nil Feb 01 07:31:24 node-Buffalo-Sola-1 geth_bsc[1919715]: WARN [02-01|07:31:24.127] Served eth_getLogs conn=127.0.0.1:24309 reqid=000001860be321400feb238f7da4 duration="219.102µs" err="unknown block"` startup parameters `-diffsync --txlookuplimit=0 --tries-verify-mode=none --pruneancient=true --diffblock=5000`
> 
> Can you provide the profile of routines when hung after call your command?

/node/full/bsc/bin/geth_bsc --networkid 56 --config /node/full/bsc/config.toml --datadir /node/full/bsc/ --syncmode "full" --gcmode full --diffsync --txlookuplimit=0 --tries-verify-mode=none --pruneancient=true --diffblock=5000 --http.vhosts=* --http.corsdomain=* --http --http.api=eth,web3,net,debug,txpool --http.addr 127.0.0.1 --ws --ws.api=eth,web3,net,debug,txpool --ws.addr 127.0.0.1 --metrics --metrics.addr 127.0.0.1 --port 31040 --http.port 31041 --ws.port 31042 --metrics.port 31045 

We have not changed the configuration file of the mainnet

**Comment by kyrie-yl** [comment]
> > > > ok, got your point. You could turn your log level to debug and restart, call again and see what you get in your bsc.log see if you could figure out why it is hung
> > > 
> > > 
> > > `Feb 01 07:31:24 node-Buffalo-Sola-1 geth_bsc[1919715]: DEBUG[02-01|07:31:24.048] Fetching batch of transactions id=a7a6748b61f7cd9b conn=dyndial count=1 Feb 01 07:31:24 node-Buffalo-Sola-1 geth_bsc[1919715]: DEBUG[02-01|07:31:24.050] Executing EVM call finished runtime=92.880556ms Feb 01 07:31:24 node-Buffalo-Sola-1 geth_bsc[1919715]: DEBUG[02-01|07:31:24.050] Served eth_call conn=127.0.0.1:44553 reqid=000001860be321400f27238f7d75 duration=93.493088ms Feb 01 07:31:24 node-Buffalo-Sola-1 geth_bsc[1919715]: WARN [02-01|07:31:24.127] Served eth_getLogs conn=127.0.0.1:24309 reqid=000001860be321400feb238f7da4 t="220.645µs" err="unknown block" X-Forwarded-For=nil Feb 01 07:31:24 node-Buffalo-Sola-1 geth_bsc[1919715]: WARN [02-01|07:31:24.127] Served eth_getLogs conn=127.0.0.1:24309 reqid=000001860be321400feb238f7da4 duration="219.102µs" err="unknown block"` startup parameters `-diffsync --txlookuplimit=0 --tries-verify-mode=none --pruneancient=true --diffblock=5000`
> > 
> > 
> > Can you provide the profile of routines when hung after call your command?
> 
> /node/full/bsc/bin/geth_bsc --networkid 56 --config /node/full/bsc/config.toml --datadir /node/full/bsc/ --syncmode "full" --gcmode full --diffsync --txlookuplimit=0 --tries-verify-mode=none --pruneancient=true --diffblock=5000 --http.vhosts=* --http.corsdomain=* --http --http.api=eth,web3,net,debug,txpool --http.addr 127.0.0.1 --ws --ws.api=eth,web3,net,debug,txpool --ws.addr 127.0.0.1 --metrics --metrics.addr 127.0.0.1 --port 31040 --http.port 31041 --ws.port 31042 --metrics.port 31045
> 
> We have not changed the configuration file of the mainnet
I got your point. But because you use prune while our environment doesn't, I need to start a node with prune which will take a long time. Could you help provide the routine profile when the hung occurs?
