### ISSUE TITLE
Bsc chain has an uncle/stale block? 

### ISSUE THREAD

**Issue by yj0x0x** [bnb-chain/bsc#1293]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

I have seen the bsc scan has the [re-org section](https://bscscan.com/blocks_forked). 
But I think that bsc consensus is clique which is proof of authority.  
This is pbft,  so fork couldn't happen IMO. 
And Polygon chain also doesn't have re-org even if their explorer show about relevant data. 

Is this for sure that bsc chain has uncle/stable block while running?

**Comment by CocoStarZ** [comment]
Too old issue, close it for now.
