### ISSUE TITLE
Prune error: Could not open database: gap

### ISSUE THREAD

**Issue by arpluta** [bnb-chain/bsc#1295]
#### System information

Geth version: `v1.1.18_hf`
OS & Version: Ubuntu 20.04.5 LTS 

#### Expected behaviour

The database should be pruned

#### Actual behaviour

Throws an db error: `Could not open database: gap (#21580814) in the chain between ancients and leveldb`

#### Steps to reproduce the behaviour

`sudo ./geth snapshot prune-state --datadir=node`

#### Backtrace

````
INFO [02-02|09:12:40.619] Maximum peer count                       ETH=50 LES=0 total=50
INFO [02-02|09:12:40.619] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [02-02|09:12:40.620] Set global gas cap                       cap=50,000,000
INFO [02-02|09:12:40.620] Allocated cache and file handles         database=/opt/geth/node/geth/chaindata cache=408.00MiB handles=524,288
INFO [02-02|09:12:46.772] AncientDB item count                     items=21,580,814
INFO [02-02|09:12:46.773] Opened ancient database                  database=/opt/geth/node/geth/chaindata/ancient readonly=false frozen=21,580,814
Fatal: Could not open database: gap (#21580814) in the chain between ancients and leveldb
````

When submitting logs: please submit them as text and not screenshots.

**Comment by isaacyuno** [comment]
Did you get this error after prune-state?

**Comment by CocoStarZ** [comment]
No more follow-up, close the issue for now
