### ISSUE TITLE
Is sha256sum of testnet.zip wrong?

### ISSUE THREAD

**Issue by dai1975** [bnb-chain/bsc#1304]
On [release page](https://github.com/bnb-chain/bsc/releases), sha256sum of testnet.zip is: 

> testnet.zip | c9c20ceb98911cc3fa7ceda3e5efbf17a3791fdc46f2f6ab13af7ac77f1a65eb

but actually I get
> $ curl -sL https://github.com/bnb-chain/bsc/releases/download/v1.1.18_hf/testnet.zip | sha256sum
> bea96c7577f7ff8fe25384a3975059350fe2955e5b953180b26bc8944b6b9542  -

mainnet.zip is ok
> curl -sL https://github.com/bnb-chain/bsc/releases/download/v1.1.18_hf/mainnet.zip  | sha256sum                                                                                                   
> 6dd6976b9c8d407e95ed99cd46f7badfa410f3f374ea3e360defab0f63fa3ed2  -

**Comment by kris-ss** [comment]
Hello, looks like you are correct. Let me check with the team and get back to you.
