### ISSUE TITLE
(node:3429850) UnhandledPromiseRejectionWarning: Error: Returned error: execution aborted (timeout = 5s)

### ISSUE THREAD

**Issue by osizadmin** [bnb-chain/bsc#1313]
we got this error

(node:3429850) UnhandledPromiseRejectionWarning: Error: Returned error: execution aborted (timeout = 5s)

while to get the balance of BEP20 token.

Kindly give the solution to solve this issue.

**Comment by blxdyx** [comment]
what dose this "node" mean? How can i reproduce this problem?

**Comment by osizadmin** [comment]
We are using own node server.

**Comment by blxdyx** [comment]
BEP20 is compatible with ERC20, all BEP20 tokens have a balanceOf method that returns the balance of a given wallet address. 
Maybe you can refer to this: 
https://ethereum.org/en/developers/docs/standards/tokens/erc-20/

**Comment by blxdyx** [comment]
If there is no problem anymore, I am gonna to close this issue.
