### ISSUE TITLE
BSC Synchronisation failed[bsc fast node]

### ISSUE THREAD

**Issue by maef2018** [bnb-chain/bsc#1314]
#### System information

Geth version: geth_v1.1.18
OS & Version: ubuntu

Hello, my startup method is: ./geth_v1.1.18 --config /data/config/config.toml --datadir /data/data --txlookuplimit=0 --syncmode=full --tries-verify-mode= none --prune ancient=true --diffblock=5000. The node I deployed could not successfully synchronize to the block data. I downloaded the data from here (https://snapshots.48.club/geth.25615705.tar.lz4). After I started the program, the data was synchronized normally. Two hours later, I checked the logs and found the following information:

t=2023-02-15T17:21:56+0800 lvl=warn msg="Synchronisation failed, retrying"      err="peer is unknown or unhealthy"
t=2023-02-15T17:21:56+0800 lvl=warn msg="Synchronisation failed, retrying"      err="peer is unknown or unhealthy"
t=2023-02-15T17:21:56+0800 lvl=warn msg="Synchronisation failed, retrying"      err="peer is unknown or unhealthy"
t=2023-02-15T17:21:56+0800 lvl=warn msg="Synchronisation failed, retrying"      err="peer is unknown or unhealthy"
t=2023-02-15T17:21:56+0800 lvl=warn msg="Synchronisation failed, retrying"      err="peer is unknown or unhealthy"

**Comment by pybfinger** [comment]
I was having the same issue.

Read #1106 :

- Replaced StaticNodes with https://api.binance.org/v1/discovery/peers
- Changed max peers from 30 to 100 in config.toml

My fast node is now synching!

**Comment by maef2018** [comment]
> I was having the same issue.
> 
> Read #1106 :
> 
> * Replaced StaticNodes with https://api.binance.org/v1/discovery/peers
> * Changed max peers from 30 to 100 in config.toml
> 
> My fast node is now synching!

Thank you! I will try!

**Comment by maef2018** [comment]
Success!
