### ISSUE TITLE
how to use debug module

### ISSUE THREAD

**Issue by PPianAIC** [bnb-chain/bsc#1315]
### System information
> Geth
Version: 1.1.19
Git Commit: 6587671e748805a438c4c617e766ce168a38e5e6
Git Commit Date: 20230213
Architecture: arm64
Go Version: go1.18.8
Operating System: linux
GOPATH=
GOROOT=go

### Config file
[config.txt](https://github.com/bnb-chain/bsc/files/10741498/config.txt)

### Command
> ./geth --datadir /data/bsc/node --config /data/bsc/config.toml --cache=10240 --rpc.allow-unprotected-txs --txlookuplimit 0 --allow-secure-unlock --http  --maxpeers=2000 --rpc.gascap 0 --rpc.txfeecap 0 --gcmode archive --diffsync

### Question
> debug.traceBlockByNumber("0x1660", {"tracer": "callTracer"})
Error: required historical state unavailable (reexec=128)
        at web3.js:6365:9(45)
        at send (web3.js:5099:62(34))
        at <eval>:1:25(7)
> debug.traceBlockByNumber("0x1660")
Error: required historical state unavailable (reexec=128)
        at web3.js:6365:9(45)
        at send (web3.js:5099:62(34))
        at <eval>:1:25(4)
> debug.traceBlockByNumber("0x1660", {"tracer": "callTracer", "reexec":20000})
Error: stateAtBlock commit failed, number 1 root 0x1db428ea79cb2e8cc233ae7f4db7c3567adfcb699af668a9f583fdae98e95588: invalid merkle root (remote: 0000000000000000000000000000000000000000000000000000000000000000 local: 1db428ea79cb2e8cc233ae7f4db7c3567adfcb699af668a9f583fdae98e95588)
        at web3.js:6365:9(45)
        at send (web3.js:5099:62(34))
        at <eval>:1:25(9)
### Requirement
I want to know how to use debug module,  modify the configuration file? Add command parameters? Or other?

**Comment by blxdyx** [comment]
Have you init genesis? 
You must try below command before sync from genesis block.
./geth --datadir node init genesis.json

**Comment by PPianAIC** [comment]
> 你有创世记吗？ 在从创世块同步之前，您必须尝试以下命令。 ./geth init genesis.json --datadir 数据文件夹
> 
> 如果你想为 BSC 主网运行一个存档节点，你可以下载我们的快照： https: [//docs.bnbchain.org/docs/archivenode](https://docs.bnbchain.org/docs/archivenode)

我下载了genesis.json，并初始了创世块
[genesis.txt](https://github.com/bnb-chain/bsc/files/10752188/genesis.txt)
我想知道存档节点怎么使用debug模式的方法？是因为我运行存档节点的方式不对么？
谢谢

**Comment by blxdyx** [comment]
Yes, you must set   --syncmode full.

**Comment by blxdyx** [comment]
If there is no problem anymore, I am gonna to close this issue.

**Comment by PPianAIC** [comment]
@blxdyx There is no problem at the moment. I will ask you for advice when I encounter problems. Thanks!
