### ISSUE TITLE
"method": "debug_traceCall"   我配置了withLog": true ，但是输出中没有日志相关信息

### ISSUE THREAD

**Issue by xiaozanooo** [bnb-chain/bsc#1318]
{
    "jsonrpc": "2.0",
    "id": 108,
    "method": "debug_traceCall",
    "params": [
        {
      "from":"0xxxx",
      "to": "0xxxx",
      "data":"0xxxxx"
         },
         "pending",
        {
            "tracer": "callTracer",
            "tracerConfig": { "onlyTopCall": true,"withLog": true }
        }
    ]
}

上面是我的RPC请求，我加上了"withLog": true 这个参数，但是在输出信息中看不到日志相关数据。该参数具体是做什么用的。

需要补充一下，我模拟的交易是会触发emit event。

这是文档中的说明：
withLog: true instructs the tracer to also collect the logs emitted during each call.

**Comment by isaacyuno** [comment]
This feature has not yet been implemented on bsc geth https://github.com/bnb-chain/bsc/pull/1261

**Comment by xiaozanooo** [comment]
请问该功能有添加计划吗！

**Comment by isaacyuno** [comment]
有的，近期会发布
