### ISSUE TITLE
Binance binary Logs 

### ISSUE THREAD

**Issue by deepakjuit** [bnb-chain/bsc#1323]
by default, Binance stores logs on /node/bsc.log file and these logs is not showing by **journalctl** command.
But I want to change this default and want to store logs in journals.

`
**config.toml**
...
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[Node.LogConfig]
FileRoot = ""
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info" `

_**Any suggestion!!!**_

**Comment by deepakjuit** [comment]
I'm running the binance geth by using .service file

**Comment by deepakjuit** [comment]
this is my command
geth_linux --config /config.toml --datadir /binance/node --port 30311 --http --http.addr 0.0.0.0 --http.port 8545 --http.api debug,eth,net,txpool,web3 --http.vhosts * --http.corsdomain * --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.api debug,eth,net,txpool,web3 --pprof --metrics --metrics.expensive --ipcpath /binance/node/geth.ipc --syncmode full --gcmode full --txlookuplimit 2350000 --rpc.allow-unprotected-txs

**Comment by 0xLyon** [comment]
Hi there, I would suggest you try configuring your systemd service unit files to include the custom log you want to add into journalctl. As far as I am aware, there is no built-in function that will allow you to do this, but you can try this suggestion found in this thread:
https://unix.stackexchange.com/questions/337053/application-log-files-to-the-systemd-journal

**Comment by masayil** [comment]
just delete it
```
[Node.LogConfig]
FileRoot = ""
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info"
```
