### ISSUE TITLE
Current Full Node Size?

### ISSUE THREAD

**Issue by devatgo** [bnb-chain/bsc#1324]
Our company (blockchain indexing service) hasn't ran a BSC full node for ~1 year & are planning on adding BSC to our supported chains sometime soon, what is the current full node size (present within chaindata dir) when syncing from scratch using snap sync? We have a server with 7.6TB (NVMe), would this be enough or would we need to add more storage?

**Comment by brilliant-lx** [comment]
7.6TB is enough to run a BSC full node.
It is even enough to run a archive node with Erigon.
Currently, snap sync is not quite stable, you'd better do full sync base on https://github.com/bnb-chain/bsc-snapshots

**Comment by devatgo** [comment]
Thanks @brilliant-lx, we're starting the syncing process now.
