### ISSUE TITLE
Crash 1.1.19

### ISSUE THREAD

**Issue by 0x090909** [bnb-chain/bsc#1327]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Actual behaviour

![crash](https://user-images.githubusercontent.com/16927059/221436410-4aa0b03c-256b-4e5d-a9b5-4a732f0ccace.jpg)

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by cosinlink** [comment]
Could you provide the whole logs as text ?

**Comment by 0x090909** [comment]
@cosinlink I dont even know ho,  the crash is so long it overflows the buffer of tmux. I think problem might be an unhadled type of message from a peer

**Comment by cosinlink** [comment]
> Can you provide the first paragraph of the error message?

**Comment by guagualvcha** [comment]
will close this one. feel free to open new one if any concern
