### ISSUE TITLE
Txpool always dies out or stalls

### ISSUE THREAD

**Issue by etGitOne** [bnb-chain/bsc#1330]
#### System information

Geth version: 1.1.19 & 1.1.18
OS & Version: Ubuntu 20.04

#### Expected behaviour
Txpool continuously gets most of new pending transactions when full node is synced

#### Actual behaviour
Txpool stops receiving majority of new pending transactions, receives only up to about 30 transactions per block on a synced full node

#### Steps to reproduce the behaviour
Bring up a full node and wait for until its synced as per https://docs.bnbchain.org/docs/validator/fullnode/
- default config.toml from mainnet.zip from https://github.com/bnb-chain/bsc/releases
- 16-core CPU, 128 GB RAM, 7 TB NVMe dedicated

#### Txpool.status from console - example of responses when called every ~3s:
> txpool.status
{
  pending: 23,
  queued: 94
}
> txpool.status
{
  pending: 32,
  queued: 91
}
> txpool.status
{
  pending: 16,
  queued: 89
}
> txpool.status
{
  pending: 24,
  queued: 89
}

#### Log entries example from synced node
t=2023-03-01T14:31:59+0100 lvl=info msg="Imported new chain segment"             blocks=1  txs=207  mgas=17.028  elapsed=91.485ms    mgasps=186.128 number=26,088,402 hash=0x5a82b82b4ff0368e2ffb4bcf15950a92c6d21cd7fce6a70ba3c6c18ad342bc63 dirty="1.63 GiB"
t=2023-03-01T14:32:02+0100 lvl=info msg="Imported new chain segment"             blocks=1  txs=168  mgas=21.748  elapsed=69.267ms    mgasps=313.972 number=26,088,403 hash=0x6e07beaa895adec145949a2ae27af0d7d4cad2d44a39a96f902ff65f897df9ac dirty="1.63 GiB"
t=2023-03-01T14:32:05+0100 lvl=info msg="Imported new chain segment"             blocks=1  txs=130  mgas=20.024  elapsed=49.399ms    mgasps=405.360 number=26,088,404 hash=0x8bf962376373235995922da448252b913fd540ed3c3307978c9bfb757c5fd1e2 dirty="1.63 GiB"
t=2023-03-01T14:32:08+0100 lvl=info msg="Imported new chain segment"             blocks=1  txs=172  mgas=18.950  elapsed=56.272ms    mgasps=336.749 number=26,088,405 hash=0x76221b7520c968f1a12e53be38fbf2162884dc9fc89cd7a21ef60b74819c5d51 dirty="1.63 GiB"
t=2023-03-01T14:32:10+0100 lvl=info msg="Imported new chain segment"             blocks=1  txs=175  mgas=18.134  elapsed=51.728ms    mgasps=350.559 number=26,088,406 hash=0x0daf57a0476abaa3901fac22a73e4ce33da62544cf2491a5ee956ab6eed8e345 dirty="1.63 GiB"
t=2023-03-01T14:32:14+0100 lvl=info msg="Imported new chain segment"             blocks=1  txs=177  mgas=16.812  elapsed=50.951ms    mgasps=329.972 number=26,088,407 hash=0x6b35613187362a640814da79bd692207eb9bd61b5f323f08a3152356b2f703d2 dirty="1.63 GiB"
t=2023-03-01T14:32:17+0100 lvl=info msg="Imported new chain segment"             blocks=1  txs=136  mgas=16.910  elapsed=46.623ms    mgasps=362.680 number=26,088,408 hash=0x6a75cf9646308c2caa23255ea602cad05db2e18b6bf39570b79443acc980dd6f dirty="1.63 GiB"
t=2023-03-01T14:32:19+0100 lvl=info msg="Imported new chain segment"             blocks=1  txs=141  mgas=16.080  elapsed=53.961ms    mgasps=298.000 number=26,088,409 hash=0xcd5af71851c932dfd0aa254942904418ceae19b8e5fd2d836fd2b490209b6204 dirty="1.63 GiB"
t=2023-03-01T14:32:23+0100 lvl=info msg="Imported new chain segment"             blocks=1  txs=131  mgas=11.811  elapsed=42.381ms    mgasps=278.697 number=26,088,410 hash=0xcb265cffc63aff1cd5ceb995ab9dcb2165a67127fa4922ead43d26aab0056c99 dirty="1.63 GiB"
t=2023-03-01T14:32:26+0100 lvl=info msg="Imported new chain segment"             blocks=1  txs=112  mgas=14.420  elapsed=42.092ms    mgasps=342.574 number=26,088,411 hash=0x2531ee0acbf2a647672c8e1483631b56a4cfdc2cb64072f977d5d0cf9af503e9 dirty="1.63 GiB"

**Comment by cosinlink** [comment]
checking

**Comment by cosinlink** [comment]
It seems ok, current tps is about 30, the node looks perfectly normal
