### ISSUE TITLE
Transaction cannot be confirmed normally

### ISSUE THREAD

**Issue by jackz010** [bnb-chain/bsc#1334]
#### System information

Geth version: 1.1.18
OS & Version: Linux
Commit hash : 0xb413c06c4a52357336a4b68301d49c2ffd8ad6ee4ac794a2d4b3113ee375812d

#### Expected behaviour
Normal confirmation of transactions on blockchain

#### Actual behaviour
Nodes are synchronizing blocks normally, but the received transaction uplink blocks are far behind

![image](https://user-images.githubusercontent.com/98305759/222485478-a979bb14-b14a-4dc2-ab02-02775e27f300.png)

[bsc.log.2023-03-01_17.txt](https://github.com/bnb-chain/bsc/files/10873283/bsc.log.2023-03-01_17.txt)

**Comment by isaacyuno** [comment]
0xb413c06c4a52357336a4b68301d49c2ffd8ad6ee4ac794a2d4b3113ee375812d was in block 26091380 which is 1.5 minutes behind, seems it took sometime to route to validators. Did you find more txns like this one?

**Comment by jackz010** [comment]
> 0xb413c06c4a52357336a4b68301d49c2ffd8ad6ee4ac794a2d4b3113ee375812d was in block 26091380 which is 1.5 minutes behind, seems it took sometime to route to validators. Did you find more txns like this one?

At present, there is only one transaction

**Comment by dwjorgeb** [comment]
we're encountering similar issues, where TXs issued from the our BSC node are either never broadcasted or take a long time

**Comment by isaacyuno** [comment]
[0xa607a555ee81ce59553c8c8d901c6ca3b51ae7e5e9472308b1ae496f5d570c0c](https://bscscan.com/tx/0xa607a555ee81ce59553c8c8d901c6ca3b51ae7e5e9472308b1ae496f5d570c0c) was on chain 3 hours later according to your screenshot time. Could you try to restart your Geth with maxpeers 200 to see if this issue persists?

**Comment by kashirin-dm** [comment]
I have a similar issue. Related topic: https://github.com/bnb-chain/bsc/issues/941
