### ISSUE TITLE
CONNECTION ERROR: Couldn't connect to node

### ISSUE THREAD

**Issue by A2DNEW** [bnb-chain/bsc#1335]
I use this tutorial for run BSC node:

`https://docs.bnbchain.org/docs/beaconchain/light-client`

But with web3 I get error:

`Uncaught (in promise) Error: CONNECTION ERROR: Couldn't connect to node`

My code:

```
const web3 = new Web3();
web3.setProvider(new Web3.providers.HttpProvider('http://my-ip:27147'));
web3.eth.isSyncing().then(console.log);
```

**Comment by kris-ss** [comment]
Hello, 

To call the Beacon Chain API - please refer to this https://docs.bnbchain.org/docs/api-reference/node-rpc/, Beacon Chain is not an EVM compatible chain so you cannot use web3.js to call its API. 

In case you want to run a BSC node, please follow this tutorial - https://docs.bnbchain.org/docs/validator/fullnode/

**Comment by A2DNEW** [comment]
@kris-ss 
Thank you.
So, with light-client I can only use node-rpc?
And I can't create wallet address or get balance of address?
Because in [this link](https://docs.bnbchain.org/docs/api-reference/node-rpc/) I can't find any method for create wallet or send trx or get balance.

**Comment by isaacyuno** [comment]
Hi, light-client is only for beacon chain. Saw you are using web3js, it only works on BSC, so you need to set your geth node to web3js. Light-client of beacon chain is not used for this case.

**Comment by A2DNEW** [comment]
@isaacyuno thank you
is there any lightnode for BSC?
fullnode is very large and we need 2TR server host!

**Comment by isaacyuno** [comment]
BSC has fastnode now https://docs.bnbchain.org/docs/BSC-fast-node
with flag --pruneancient=true, it will only consume 500~600G disk, get snapshot from below
https://github.com/48Club/bsc-snapshots
