### ISSUE TITLE
Can't open the smart chain faucet

### ISSUE THREAD

**Issue by boxingcoder00** [bnb-chain/bsc#1336]
trying to use Bnb smart chain faucet for project  I am getting errors of " your a robot" and 
insufficient funds for gas * price + value, I get one or the other when i click "give me BNB"

Steps to reproduce the behaviour

1.go to : https://testnet.binance.org/faucet-smart
2.enter any bsc chain address
3. try to fund 0.5 bnb

**Comment by kris-ss** [comment]
Hello, thanks for the feedback. We are aware of this issue. If you need any tbnbs, we can provide you while waiting for the fix. Just send us your wallet address.

**Comment by boxingcoder00** [comment]
Hey kris,  0x5491b35199D37De0dfA8B317aA3b6325f212A343


Thanks

**Comment by cosinlink** [comment]
checking

**Comment by cosinlink** [comment]
The faucet is under attack, we are working on some alternatives and it will take some time.  You can contact the administrator of the community first if you need it urgently.

**Comment by kris-ss** [comment]
@boxingcoder00 Sent you some tbnbs

**Comment by boxingcoder00** [comment]
@kris-ss Appreciated thank you

**Comment by andywong418** [comment]
@kris-ss would you be able to send some to 0xcDA094Bf48988fA872F17d5581fB33280cE7b4D0? Thank you

**Comment by kris-ss** [comment]
> @kris-ss would you be able to send some to 0xcDA094Bf48988fA872F17d5581fB33280cE7b4D0? Thank you

@andywong418 The faucet is working now. Please have a try.

**Comment by codesinging** [comment]
@kris-ss I need some to test. would youu be able to send some to me? thank you
0x323Dc86Eec1CA7c0Ab4E0b53fa95731C41A0C6c8

**Comment by acoronadov** [comment]
Hello, can you help me load some tbnbs please, I'm testing but the tap doesn't work, thank you very much.
Addrres is
0x511d4a322f4AfB85C2fB0DfC0eaff67B781c3DD30

**Comment by Alessandro-Cavaliere** [comment]
> > @kris-ss would you be able to send some to 0xcDA094Bf48988fA872F17d5581fB33280cE7b4D0? Thank you
> 
> @andywong418 The faucet is working now. Please have a try.

The faucet is not working, could you send me some tbnbs here, please? --> 0x47637c934116331Ce75948A47BC8A5855d72f9F7

**Comment by phucbui** [comment]
Can you send me some tbnbs please: 0x7343c48B1e3F42aD4F61340cf8f5825cE099Ae4F

**Comment by LaCk-yt** [comment]
Hi, having the same issue, can you send me some TBNB please, 0xef9f2382837110BD89826348e849dB1D0Ca03ffE

**Comment by 1693146833** [comment]
please give me some tbnb please 0x58d2861d7cDA32b5a909c2D5E90F6fddBE71D715

**Comment by seewanrdd** [comment]
please give me some at 0x9CD61dBACfCf32C9b1f0eB1B648413BdB4aBc282

**Comment by bigwhiterice** [comment]
@kris-ss  
bro, faucets not working now,
can send some tbnb at address 0xF5be7c66cAB8c9ee5913DD500BA2416A8CBe5A1D,
i  want to make some test at BNB Greenfield,
thank you  very much!

**Comment by simoven** [comment]
@kris-ss Faucet is not working at the moment, could you please send me some test bnb ? :(
0xed76415D267D7E6C9948b866E1b7D3116f4C3D9E

**Comment by SakonLight90** [comment]
@kris-ss Faucet is not working, could you please send me some tbnb ? 0x88184214AE1E8AeD2C3E732A25Bd7e5D09A4a0a0

**Comment by mehdikashi1991** [comment]
Please give me some test bnb
0xBF1b60f54eF6B51F7e5ea66F63AF32dbBA7829d8

**Comment by RonnyValdivieso** [comment]
@kris-ss Hi! Can you send me some tbnb? Please. Faucet is not working.
0x1c992b93b71252d8d4cbc5082cb2d079ca05f60f

**Comment by Lachheb1** [comment]
I need some to test. would youu be able to send some to me? thank you
0xc7229Efb20415b9d879Bfeb6318bEfcAc168973f
