### ISSUE TITLE
Can anyone please fix Binance Smart Chain testnet Faucet ?

### ISSUE THREAD

**Issue by redmouseindia** [bnb-chain/bsc#1338]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
Binance faucet is not working as it should : https://testnet.bnbchain.org/faucet-smart

#### Actual behaviour
Binance faucet should fund BNB on testnet

#### Steps to reproduce the behaviour
go to : https://testnet.binance.org/faucet-smart
enter any bsc chain address
try to fund 1 bnb

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by kris-ss** [comment]
The team is looking into it - https://github.com/bnb-chain/bsc/issues/1336

**Comment by cosinlink** [comment]
The faucet is under attack, we are working on some alternatives and it will take some time. You can contact the administrator of the community first if you need it urgently.

**Comment by cosinlink** [comment]
same issue from https://github.com/bnb-chain/bsc/issues/1336
