### ISSUE TITLE
bsc broadcast transaction fail by my node, but ok by bscscan.com

### ISSUE THREAD

**Issue by lcgogo** [bnb-chain/bsc#1362]
bsc broadcast transaction fail by my node, but ok by bscscan.com
error shows
```
BSC_BNB 10009 BSC_BNB nonce too high to broadcast transaction, delay it. 	
```
my bsc node version is 1.1.19

The node config I use the followed one
```
wget   $(curl -s https://api.github.com/repos/bnb-chain/bsc/releases/latest |grep browser_ |grep mainnet |cut -d\" -f4)
```

Is there any config need modify?

**Comment by yutianwu** [comment]
please add more details for this issue
