### ISSUE TITLE
Noobie Question: Can you get pending transactions while running a fast node?

### ISSUE THREAD

**Issue by drydesertdry** [bnb-chain/bsc#1365]
I'm running a fast node but when I go in the geth console and look at eth.pendingTransactions, it's empty, and also the txpool command is empty. Is it not possible to get pending transcations in a fast node or am I doing something wrong? Details below

 using a snapshot from here:
https://github.com/48Club/bsc-snapshots#geth-snapshots

Version:
1.1.20-fc4303c6

command:

./geth --tries-verify-mode none --config ./config.toml --datadir ./data  --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0

config.toml:

[Eth]
NetworkId = 56
NoPruning = false
NoPrefetch = false
LightPeers = 100
UltraLightFraction = 75
TrieTimeout = 100000000000
EnablePreimageRecording = false
EWASMInterpreter = ""
EVMInterpreter = ""

[Eth.Miner]
GasFloor = 30000000
GasCeil = 40000000
GasPrice = 1000000000
Recommit = 10000000000
Noverify = false

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 512
GlobalSlots = 10000
AccountQueue = 256
GlobalQueue = 5000
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 20

[Node]
IPCPath = "geth.ipc"
HTTPHost = "localhost"
NoUSB = true
InsecureUnlockAllowed = false
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]

**Comment by isaacyuno** [comment]
Hi there, you need to get your node synced to the latest block then you could get pending txns

**Comment by drydesertdry** [comment]
My node already is synced to the last block though....

**Comment by isaacyuno** [comment]
eth.pendingTransactions are the transactions that your local Geth node has, that haven't been mined to a block.
I have a fast node with maxpeers = 200 and I could get global txn pool by txpool.status
<img width="1003" alt="Screen Shot 2023-03-21 at 09 05 41" src="https://user-images.githubusercontent.com/110881390/226497053-dff704f6-2468-4ca4-9e50-93dbd16cb40c.png">
