### ISSUE TITLE
Noobie Question: Can't sync bsc geth node

### ISSUE THREAD

**Issue by hoangthanhtung1910** [bnb-chain/bsc#1366]
I sync bsc geth with command:
geth --config /root/config.toml --datadir /root/node --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0

It finished syncing the state within 3 days, then start the state healing process.
It's been 1 week since the state heal started and the current block is always behind the last block around 100 blocks.
Is there any problem here? When is the sync complete? :(
This is output:
![image](https://user-images.githubusercontent.com/21260638/226100585-953aac10-ca27-465d-8681-bd89f7cf0d1f.png)
![image](https://user-images.githubusercontent.com/21260638/226100614-0678ae58-fa5d-45d5-a047-ef76c560cae4.png)

**Comment by isaacyuno** [comment]
It looks like you are syncing from the genesis block, this will require high-performance servers which should be at least 60K IOPS above, otherwise, it will be hard to sync up

**Comment by guagualvcha** [comment]
Please refer to https://github.com/bnb-chain/bsc-snapshots
