### ISSUE TITLE
Implement SubscribeFullPendingTransactions from go-etherium

### ISSUE THREAD

**Issue by it-devel-att-hais** [bnb-chain/bsc#1387]
# Rationale
Method `SubscribePendingTransactions` of geth client curently returning only hash of transaction and to know more information about transaction we should do additional rpc request for each transaction which can lead in the end to latency problem and huge lag between currently processed transaction from mempool and actual mempool transactions. It would be nice if `bsc` will have `SubscribeFullPendingTransactions` as `go-etherium` have to return full transaction information instead of only hash of it

# Implementation
This method is already exist in go-etherium repo:
[Method on go-etherium repo](https://github.com/ethereum/go-ethereum/blob/master/ethclient/gethclient/gethclient.go#L175)

**Comment by emailtovamos** [comment]
The link to go-ethereum repo needs to be updated.

**Comment by zzzckck** [comment]
SubscribeFullPendingTransactions  was supported since v1.3.0.
