### ISSUE TITLE
BSC geth hangs. Bug in codebase, or malicious peers?

### ISSUE THREAD

**Issue by devatgo** [bnb-chain/bsc#1388]
Geth version: v1.1.20
OS & Version: Ubuntu

**upon further debugging, we isolated the cause of the aforementioned issue. In order to prevent this issue from reoccurring we've made a few changes to the bsc geth codebase, upon recompilation the issue no longer persists. Pull requests seem to be rejected quite frequently so we'll keep the fix private for now.

**Comment by ZiyuanStar** [comment]
Set max peers = 100 and add below link's enode at staticnode in your config.toml. Then restart nodes.

https://api.binance.org/v1/discovery/peers
https://api.binance.org/v2/discovery/peers

**Comment by kugimiya530** [comment]
> Set max peers = 100 and add below link's enode at staticnode in your config.toml. Then restart nodes.
> 
> https://api.binance.org/v1/discovery/peers https://api.binance.org/v2/discovery/peers

Hi ,may I ask what different between v1 and v2 ?

**Comment by ZiyuanStar** [comment]
> > Set max peers = 100 and add below link's enode at staticnode in your config.toml. Then restart nodes.
> > https://api.binance.org/v1/discovery/peers https://api.binance.org/v2/discovery/peers
> 
> Hi ,may I ask what different between v1 and v2 ?

both work
