### ISSUE TITLE
execution reverted. What exactly is it doing?

### ISSUE THREAD

**Issue by airstring** [bnb-chain/bsc#1391]
#### System information
Geth version:  v1.1.20
OS & Version: linux
hardware: aws m6i.4xlarge (cpu/memory: 16C/64G,  disk io/throughput: 8000/500M)

#### Question
The block is out of sync. Log as follows：
`
bsc    | WARN [03-24|09:46:00.801] Served eth_estimateGas                   conn=10.1.6.58:41650  reqid=15               duration=1.128836ms   err="execution reverted"

bsc    | WARN [03-24|09:47:00.692] Served eth_estimateGas                   conn=10.1.6.58:38732  reqid=153              t=1.122064ms   err="execution reverted"                   X-Forwarded-For="3.0.178.157, 162.158.107.19"

bsc    | WARN [03-24|09:47:00.692] Served eth_estimateGas                   conn=10.1.6.58:38732  reqid=153              duration=1.121306ms   err="execution reverted"

bsc    | WARN [03-24|09:48:01.003] Served eth_estimateGas                   conn=10.1.6.192:56086 reqid=486              t=1.049237ms   err="execution reverted"                   X-Forwarded-For="3.0.178.157, 162.158.107.20"

bsc    | WARN [03-24|09:48:01.003] Served eth_estimateGas                   conn=10.1.6.192:56086 reqid=486              duration=1.048363ms   err="execution reverted"

bsc    | WARN [03-24|09:49:00.633] Served eth_estimateGas                   conn=10.1.6.192:56452 reqid=870              t=1.171384ms   err="execution reverted"                   X-Forwarded-For="3.0.178.157, 162.158.107.19"

bsc    | WARN [03-24|09:49:00.633] Served eth_estimateGas
`
Block synchronization was normal for the last hour.
Restart the node application and the blocks will start synchronizing normally.

**Comment by devatgo** [comment]
Looks like someone is remotely connecting to your node and executing rpc methods (in this case the "eth_estimateGas" rpc method). If you need remote access to your nodes rpc methods you should configure your iptables/ufw rules to only allow connections from whitelisted ips on geths HTTP/WS ports.

**Comment by airstring** [comment]
executing rpc methods (in this case the "eth_estimateGas" rpc method) ，Isn't it a normal operation？Why can't blocks synchronize properly？

**Comment by isaacyuno** [comment]
If you open your RPC to others, then someone else will be able to execute through API like eth_estimateGas, and the result is only related to their txn, not related to your node. Also it won't cause sync issue on your node
