### ISSUE TITLE
v1.1.21 has a hard time peering / staying in sync

### ISSUE THREAD

**Issue by yorickdowne** [bnb-chain/bsc#1397]
#### System information

Geth version: `v1.1.21`
OS & Version: Linux

#### Config and hardware

This is a full node, upgraded from `v1.1.20`. Snap sync, no `--diffsync`, trie verify mode is default `local`. 12 cores, 64 GiB RAM, 2TB NVMe drive on baremetal / dedicated server. Geth compiled from source with Go 1.20.

#### Observed behavior

After upgrading to `v1.1.21`, geth has a hard time staying in sync. Symptoms are a lot of "Synchronization failed, retrying" messages (sample below), and importing multiple blocks close to head, instead of 1 at a time.

We have two nodes. We restarted one a few times, and that seemed to improve things for a bit.

We then downgraded the other node to `v1.1.20`, and it immediately caught up to chain head and has been healthy.

Sample logs

```
bsc-docker-geth-1  | WARN [03-27|19:32:26.279] Synchronisation failed, retrying         peer=8525dc242e108cae00229a9a968e064a3be1d670ac47490d32c6dee250b25ecf err="peer is unknown or unhealthy"
bsc-docker-geth-1  | WARN [03-27|19:32:31.915] Synchronisation failed, retrying         peer=eae1b254836d21c69652d68c05028c0253805c98fe126af185ce75650a2ab432 err="write tcp 172.20.0.2:44206->34.251.95.115:30311: use of closed network connection"
```

```
bsc-docker-geth-1  | INFO [03-27|18:37:23.734] Imported new chain segment               blocks=10 txs=1353 mgas=135.762 elapsed=422.380ms mgasps=321.421 number=26,835,370 hash=92a4d2..493d30 dirty=362.75MiB ignored=1
bsc-docker-geth-1  | WARN [03-27|18:37:31.930] Synchronisation failed, retrying         peer=54f5e8ff3faaf75fdc76769ce0028f2100724594dc42ab4d20f041b241f569a0 err="peer is unknown or unhealthy"
bsc-docker-geth-1  | INFO [03-27|18:38:05.371] Deep froze chain segment                 blocks=10 elapsed=5.554ms   number=26,745,370 hash=dfd58a..fa1f59
bsc-docker-geth-1  | WARN [03-27|18:38:20.645] Synchronisation failed, dropping peer    peer=a014bfd6bcfd98c80d77772e041ae420332b43845ec43656fff81071e29a7671 err=timeout
bsc-docker-geth-1  | WARN [03-27|18:38:22.938] Synchronisation failed, retrying         peer=702b5fe3a0ff88db573565da8859587191d3e821c4d50b84c74f6d958fb7f1ea err="peer is unknown or unhealthy"
bsc-docker-geth-1  | INFO [03-27|18:38:28.211] Downloader queue stats                   receiptTasks=0 blockTasks=0 itemSize=32.11KiB throttle=8164
bsc-docker-geth-1  | INFO [03-27|18:38:29.277] Imported new chain segment               blocks=21 txs=2189 mgas=211.030 elapsed=1.066s    mgasps=197.957 number=26,835,391 hash=0da5a6..040ce0 dirty=369.94MiB ignored=1
bsc-docker-geth-1  | WARN [03-27|18:38:39.150] Synchronisation failed, retrying         peer=3856d7a0620f40fa1a82acd5685a03e6d8a17acf32d5cd5e8ba23df4b6896932 err="write tcp 172.20.0.2:34248->54.229.26.251:30311: use of closed network connection"
bsc-docker-geth-1  | WARN [03-27|18:38:39.500] Synchronisation failed, retrying         peer=929c732d9e9dc3088998bd00667125d98ef72db3139cda32a622b58abd347b86 err="peer is unknown or unhealthy"
bsc-docker-geth-1  | WARN [03-27|18:38:55.590] Synchronisation failed, retrying         peer=9086a4586d53f611243af7a12510fb4918808b5783e0668567dcd108c43658f4 err="peer is unknown or unhealthy"
bsc-docker-geth-1  | WARN [03-27|18:38:55.646] Synchronisation failed, retrying         peer=20aa71a03b6791f0952a105028ede566dc562f1351ba27577d4856352cbe602e err="shutting down"
bsc-docker-geth-1  | INFO [03-27|18:39:05.381] Deep froze chain segment                 blocks=21 elapsed=9.750ms   number=26,745,391 hash=1453e4..08e424
bsc-docker-geth-1  | WARN [03-27|18:39:13.199] Synchronisation failed, retrying         peer=a2407d505b469b3ebed05a6bb397477a195f8f0d2d420b7ba89d761e749261b8 err="shutting down"
bsc-docker-geth-1  | WARN [03-27|18:39:28.466] Synchronisation failed, retrying         peer=54b4266fdcdceed4377e5363cc932b639e7ca9e7affd77260d1233052ca1fcd5 err="peer is unknown or unhealthy"
bsc-docker-geth-1  | WARN [03-27|18:39:28.833] Synchronisation failed, retrying         peer=442f373e7664b529446f45f7df5b470496e6c7c9a535f0066efc529b7f7e1987 err="shutting down"
bsc-docker-geth-1  | WARN [03-27|18:39:32.727] Synchronisation failed, retrying         peer=8525dc242e108cae00229a9a968e064a3be1d670ac47490d32c6dee250b25ecf err="peer is unknown or unhealthy"
bsc-docker-geth-1  | WARN [03-27|18:39:35.230] Synchronisation failed, retrying         peer=92187535d4f8d80ddbbe7faf62ea02cf9ee6ca7f23e9b2c1d1edef89c6f9dd8a err="peer is unknown or unhealthy"
bsc-docker-geth-1  | INFO [03-27|18:40:00.305] Downloader queue stats                   receiptTasks=0 blockTasks=0 itemSize=30.08KiB throttle=8192
bsc-docker-geth-1  | INFO [03-27|18:40:01.983] Imported new chain segment               blocks=31 txs=2982 mgas=300.642 elapsed=1.677s    mgasps=179.211 number=26,835,422 hash=a2eddb..a0b7c4 dirty=376.83MiB ignored=1
```

#### Expected behaviour

Geth gets to chain head and imports blocks one at a time, example logs on `v1.1.20` where this works correctly:

```
bsc-docker-geth-1  | INFO [03-27|19:55:24.834] Imported new chain segment               blocks=1    txs=97    mgas=9.719    elapsed=49.421ms  mgasps=196.651 number=26,836,929 hash=bf0ef7..2661d7 dirty=596.21MiB
bsc-docker-geth-1  | INFO [03-27|19:55:28.155] Imported new chain segment               blocks=1    txs=295   mgas=20.311   elapsed=62.739ms  mgasps=323.737 number=26,836,930 hash=4c527f..a96ca9 dirty=597.54MiB
bsc-docker-geth-1  | INFO [03-27|19:55:30.920] Imported new chain segment               blocks=1    txs=82    mgas=12.123   elapsed=40.757ms  mgasps=297.445 number=26,836,931 hash=d901b5..8dc866 dirty=597.52MiB
bsc-docker-geth-1  | INFO [03-27|19:55:33.767] Imported new chain segment               blocks=1    txs=58    mgas=4.291    elapsed=24.261ms  mgasps=176.867 number=26,836,932 hash=0a8b45..e384a7 dirty=596.07MiB
bsc-docker-geth-1  | WARN [03-27|19:55:35.838] Synchronisation failed, dropping peer    peer=a2407d505b469b3ebed05a6bb397477a195f8f0d2d420b7ba89d761e749261b8 err=timeout
bsc-docker-geth-1  | INFO [03-27|19:55:36.752] Imported new chain segment               blocks=1    txs=77    mgas=5.969    elapsed=33.506ms  mgasps=178.149 number=26,836,933 hash=4bca5f..686fdc dirty=595.91MiB
bsc-docker-geth-1  | INFO [03-27|19:55:39.893] Imported new chain segment               blocks=1    txs=109   mgas=18.128   elapsed=51.370ms  mgasps=352.881 number=26,836,934 hash=ffc106..20c851 dirty=597.04MiB
bsc-docker-geth-1  | INFO [03-27|19:55:42.792] Imported new chain segment               blocks=1    txs=60    mgas=6.572    elapsed=30.741ms  mgasps=213.765 number=26,836,935 hash=44834a..758966 dirty=597.27MiB
bsc-docker-geth-1  | INFO [03-27|19:55:42.793] Deep froze chain segment                 blocks=20   elapsed=7.293ms   number=26,746,934 hash=951fbe..e547b6
bsc-docker-geth-1  | INFO [03-27|19:55:45.812] Imported new chain segment               blocks=1    txs=78    mgas=7.672    elapsed=35.254ms  mgasps=217.622 number=26,836,936 hash=73f5ae..67795b dirty=597.41MiB
```

Note unhealthy and healthy logs were taken on the same machine: Healthy on `v1.1.20`, unhealthy on `v1.1.21`

#### Full parameters

```
      - geth
      - --config
      - /home/bsc/config.toml
      - --datadir
      - /home/bsc/data
      - --cache
      - "8000"
      - --metrics
      - --metrics.addr
      - 0.0.0.0
      - --metrics.port
      - "6060"
      - --http
      - --http.addr
      - 0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.port
      - ${RPC_PORT:-8545}
      - --ws
      - --ws.addr
      - 0.0.0.0
      - --ws.port
      - ${WS_PORT:-8546}
      - --ws.api
      - web3,eth,net
      - --txlookuplimit
      - "0"
```

#### Next steps

I'll give this a rest for the day, and then bring the machine back to `v1.1.21` tomorrow and get debug logs, provided we can reproduce the issue. As fellow node operators report similar issues, I expect we will be able to reproduce.

**Comment by 0x1un** [comment]
I hava same problem in v1.1.21 .

**Comment by yorickdowne** [comment]
This may be unrelated to 1.1.21, now seeing it on 1.1.20. Will resync and see

**Comment by shiziwen** [comment]
I got the same problem, how can we fix it?

**Comment by zhy827827** [comment]
I hava same problem in v1.1.21 .

**Comment by ayrat555** [comment]
we're experiencing the same problem

**Comment by kaber2** [comment]
Same here, on 16 nodes, all running with a fresh snapshot. A few blocks are imported one block at a time, then it stalls, importing between 2 and 10 blocks afterwards. All of them have plenty of connected peers and running on 64 core server with very high IOPS and 512GB memory.

**Comment by gaiyaa** [comment]
> Visit https://api.binance.org/v1/discovery/peers and append the peer info to the StaticNodes in the config.toml, see if this helps?

can't open the link

**Comment by handsomevvv** [comment]
same problem

**Comment by yorickdowne** [comment]
Adding `StaticNodes` and `TrustedNodes` does not help. When this happens, `admin.peers` shows 50 peers, including incoming. It's not a lack of peers.

**Comment by yorickdowne** [comment]
Fellow NOs tell me that 1.1.18_hf is the last release that reliably syncs. I am wondering whether #1301 had an unwanted side effect. I reverted it and am trying that right now, https://github.com/yorickdowne/bsc/tree/synctrial

I have two nodes that are in sync with that change. I'll need to observe it longer. It'd be interesting to hear how it behaves for other people.

That fix in 1301 is desirable, so if this works, then the task for BSC devs would be to fix the fix.

**Comment by axpvx** [comment]
The same problem. For me it seems it starts working when I allow all incoming traffic in firewall. I don't know which port is missing.

**Comment by yorickdowne** [comment]
It's not a firewalling issue for us. You want the P2P ports open incoming, UDP and TCP both. You'll see inbound peers in `admin.peers` if the firewall is configured correctly. The default P2P port is 30311 UDP/TCP.

**Comment by kaber2** [comment]
> So at least in my case it appears to be related to event delivery. As soon as subscriptions are registered, the stalls start. I'd guess that a channel gets stuck somewhere. Debugging now, should have a fix shortly I hope.

So while I found the bug, I'm afraid it was due to local changes in my tree, so this won't help any of you guys, sorry. I'll keep monitoring it and see if I'm actually affected by the same problem as the others here.

**Comment by zhy827827** [comment]
i use `--tries-verify-mode none`   parameter to synchronize   

if you want high performance and care little about state consistency

**Comment by isaacyuno** [comment]
Try appending below StaticNodes to your config.toml, some users reported it solved the issue

StaticNodes = ["enode://f56dcbe59ddcf52e2abe5d5f5fded28bf823e7e2fb887cebbfe3c540ed0dfbbd778872e6b0c9c6243fcb79fdf3e1805ae98a7c389091e9cc55bfe6dedfce04b8@3.115.208.145:30311","enode://b4feb14a8247917f25a4603a0a3a58827e6e3954fa1fc0499f3e084476dcb2dc32e444e7c51cecbc1066d2c94062fc16aa80da1a008c94e576b67b84a3a111c5@13.112.103.141:30311","enode://7fed0d5ebfec2d68106cf91d4bbf2c794a22f12a11c18ef643818e8b8a5022f63abccfa50cb34fd30343530f67a70523525d94247b4f8d143dca7524d2ba8630@52.194.28.137:30311","enode://64e87612bf91e145e019a2cf877891973151ba0acfe822346d5f6876feb4b031f80b6ff2334d9fccc7522d4c27f4a0003cfc29e20db25f6eb89fc72f5d058d89@99.80.96.58:30311","enode://c67e08daecbef6e78832a1fb7eef09725ee6671aeb6dd63cd880b9a2075b945df64b4a6181bf8ed31d43bd7b77587c5380d61095e6d7989e3880656b2fb9448d@54.76.80.25:30311","enode://45ad31700cfd9bce487b912d4b10d8f657a6b4a12f46a71707a351f350a28ea9183fe38f8e4cbd4371972bd6f096072fa65bcf59c0ffb719a8ef83f403b4d656@52.18.62.124:30311","enode://935d02d00d9c5ecdc3bee7a56201eb68c9a9e2fc684ff1e606d56bebcb45722b3812df2c408bd74495140b92214e4bd28a00853641e581cbc3ebbe6ee6b2f794@50.17.94.194:30311","enode://8e68f76aef70929084fbcdc527357aa97cf0091ed80639ba8e5c35933e50034c22a0c6d30775ec9bfdeef21fc029bb895ac2221b97e1595d35110a5a27589089@54.157.26.59:30311","enode://3da255f8abdeaafe3e8acd8e861314782aec365216948f203b5da5fa5457e92ac7dd7519e2e95487d99d7158a1b47e276c6a23efefbe8da423dfe090578d3bec@3.218.173.35:30311"]

**Comment by yorickdowne** [comment]
@isaacyuno These are different from https://api.binance.org/v1/discovery/peers. What's the source for these StaticNodes?

**Comment by yorickdowne** [comment]
Reverting 1301 may have been a red herring, or maybe just made it more likely to get the "right peers"

I added isaac's StaticNodes, also as TrustedNodes, and monitoring.

**Comment by brilliant-lx** [comment]
> Debug logs from 1.1.21
> [bsc-geth-sync-issue.debug.log.gz](https://github.com/bnb-chain/bsc/files/11090028/bsc-geth-sync-issue.debug.log.gz)

Did not see any log relevant to [PR](https://github.com/bnb-chain/bsc/pull/1301)
<img width="1758" alt="image" src="https://user-images.githubusercontent.com/92799281/229405232-2d271d9c-918e-45de-a793-c27566a088d1.png">

**Comment by yorickdowne** [comment]
Thanks! Yes, I think 1301 was unrelated. This is tough to pin down. So far adding the StaticNodes that have now been ... removed from comments again?!? ... helped here. I also add them as TrustedNodes

Given an env var
```
EXTRA_STATIC_NODES=["enode://f56dcbe59ddcf52e2abe5d5f5fded28bf823e7e2fb887cebbfe3c540ed0dfbbd778872e6b0c9c6243fcb79fdf3e1805ae98a7c389091e9cc55bfe6dedfce04b8@3.115.208.145:30311","enode://b4feb14a8247917f25a4603a0a3a58827e6e3954fa1fc0499f3e084476dcb2dc32e444e7c51cecbc1066d2c94062fc16aa80da1a008c94e576b67b84a3a111c5@13.112.103.141:30311","enode://7fed0d5ebfec2d68106cf91d4bbf2c794a22f12a11c18ef643818e8b8a5022f63abccfa50cb34fd30343530f67a70523525d94247b4f8d143dca7524d2ba8630@52.194.28.137:30311","enode://64e87612bf91e145e019a2cf877891973151ba0acfe822346d5f6876feb4b031f80b6ff2334d9fccc7522d4c27f4a0003cfc29e20db25f6eb89fc72f5d058d89@99.80.96.58:30311","enode://c67e08daecbef6e78832a1fb7eef09725ee6671aeb6dd63cd880b9a2075b945df64b4a6181bf8ed31d43bd7b77587c5380d61095e6d7989e3880656b2fb9448d@54.76.80.25:30311","enode://45ad31700cfd9bce487b912d4b10d8f657a6b4a12f46a71707a351f350a28ea9183fe38f8e4cbd4371972bd6f096072fa65bcf59c0ffb719a8ef83f403b4d656@52.18.62.124:30311","enode://935d02d00d9c5ecdc3bee7a56201eb68c9a9e2fc684ff1e606d56bebcb45722b3812df2c408bd74495140b92214e4bd28a00853641e581cbc3ebbe6ee6b2f794@50.17.94.194:30311","enode://8e68f76aef70929084fbcdc527357aa97cf0091ed80639ba8e5c35933e50034c22a0c6d30775ec9bfdeef21fc029bb895ac2221b97e1595d35110a5a27589089@54.157.26.59:30311","enode://3da255f8abdeaafe3e8acd8e861314782aec365216948f203b5da5fa5457e92ac7dd7519e2e95487d99d7158a1b47e276c6a23efefbe8da423dfe090578d3bec@3.218.173.35:30311"]
```

I can use a little jq and dasel to update the config.toml from mainnet.zip

```
if [ -n "${EXTRA_STATIC_NODES}" ]; then
  for string in $(echo "${EXTRA_STATIC_NODES}" | jq -r .[]); do
    dasel put -v $(echo $string) -f config.toml 'Node.P2P.StaticNodes.[]'
    dasel put -v $(echo $string) -f config.toml 'Node.P2P.TrustedNodes.[]'
  done
fi
```
Given that mainnet.zip exists and already has StaticNodes, if we need additional for reliable sync, I'd expect the team to add them to the ZIP so we don't need to guess at which nodes are good to have.

**Comment by brilliant-lx** [comment]
> Thanks! Yes, I think 1301 was unrelated. This is tough to pin down. So far adding the StaticNodes that have now been ... removed from comments again?!? ... helped here. I also add them as TrustedNodes
> 
> Given an env var
> 
> ```
> EXTRA_STATIC_NODES=["enode://f56dcbe59ddcf52e2abe5d5f5fded28bf823e7e2fb887cebbfe3c540ed0dfbbd778872e6b0c9c6243fcb79fdf3e1805ae98a7c389091e9cc55bfe6dedfce04b8@3.115.208.145:30311","enode://b4feb14a8247917f25a4603a0a3a58827e6e3954fa1fc0499f3e084476dcb2dc32e444e7c51cecbc1066d2c94062fc16aa80da1a008c94e576b67b84a3a111c5@13.112.103.141:30311","enode://7fed0d5ebfec2d68106cf91d4bbf2c794a22f12a11c18ef643818e8b8a5022f63abccfa50cb34fd30343530f67a70523525d94247b4f8d143dca7524d2ba8630@52.194.28.137:30311","enode://64e87612bf91e145e019a2cf877891973151ba0acfe822346d5f6876feb4b031f80b6ff2334d9fccc7522d4c27f4a0003cfc29e20db25f6eb89fc72f5d058d89@99.80.96.58:30311","enode://c67e08daecbef6e78832a1fb7eef09725ee6671aeb6dd63cd880b9a2075b945df64b4a6181bf8ed31d43bd7b77587c5380d61095e6d7989e3880656b2fb9448d@54.76.80.25:30311","enode://45ad31700cfd9bce487b912d4b10d8f657a6b4a12f46a71707a351f350a28ea9183fe38f8e4cbd4371972bd6f096072fa65bcf59c0ffb719a8ef83f403b4d656@52.18.62.124:30311","enode://935d02d00d9c5ecdc3bee7a56201eb68c9a9e2fc684ff1e606d56bebcb45722b3812df2c408bd74495140b92214e4bd28a00853641e581cbc3ebbe6ee6b2f794@50.17.94.194:30311","enode://8e68f76aef70929084fbcdc527357aa97cf0091ed80639ba8e5c35933e50034c22a0c6d30775ec9bfdeef21fc029bb895ac2221b97e1595d35110a5a27589089@54.157.26.59:30311","enode://3da255f8abdeaafe3e8acd8e861314782aec365216948f203b5da5fa5457e92ac7dd7519e2e95487d99d7158a1b47e276c6a23efefbe8da423dfe090578d3bec@3.218.173.35:30311"]
> ```
> 
> I can use a little jq and dasel to update the config.toml from mainnet.zip
> 
> ```
> if [ -n "${EXTRA_STATIC_NODES}" ]; then
>   for string in $(echo "${EXTRA_STATIC_NODES}" | jq -r .[]); do
>     dasel put -v $(echo $string) -f config.toml 'Node.P2P.StaticNodes.[]'
>     dasel put -v $(echo $string) -f config.toml 'Node.P2P.TrustedNodes.[]'
>   done
> fi
> ```
> 
> Given that mainnet.zip exists and already has StaticNodes, if we need additional for reliable sync, I'd expect the team to add them to the ZIP so we don't need to guess at which nodes are good to have.

@yorickdowne the StaticNodes were updated,  https://github.com/bnb-chain/bsc/releases/tag/v1.1.21
These new nodes should be reliable

**Comment by ayrat555** [comment]
@brilliant-lx hey. we tried a new config. it seems it still has problems. some of our txs are not propagated using ` v1.1.21`.

https://github.com/bnb-chain/bsc/issues/1413

**Comment by brilliant-lx** [comment]
> we tried a new config. it seems it still has problems. some of our txs are not propagated using  v1.1.21.
no issues with 1.1.19

You tried a new config.toml that I suggested in https://github.com/bnb-chain/bsc/releases/tag/v1.1.21?
And still have the problem?
Could you help dump the peer list that you connect?
You can get the peer list by:
> geth attach geth.ipc
> admin.peers

**Comment by yorickdowne** [comment]
A little more anecdotal evidence. One of our fellow NOs has had no concerns with 1.1.21 - and still uses the config.toml from 1.1.18-hf, which has a different set of staticnodes.

we use 50 max peers; another NO who was at default also went to 50 and it helped.

There is some evidence it has to do with peering, and that having the “right set” of StaticNodes helps, as does having a higher max peer value.

**Comment by brilliant-lx** [comment]
Yes, it could be the p2p peers issue, it will be traced here: https://github.com/bnb-chain/bsc/issues/1419
The P2P connection reached the up limit, which will reject new P2P connections.

**Comment by yorickdowne** [comment]
Interesting. To keep the binance-supplied StaticNodes from "getting flushed out", I am adding them to TrustedNodes as well, which isn't subject to the max peer limit.

Something like this:
```
# Duplicate binance-supplied static nodes to trusted nodes
for string in $(dasel -f config.toml -w json 'Node.P2P.StaticNodes' | jq -r .[]); do
  dasel put -v $(echo $string) -f config.toml 'Node.P2P.TrustedNodes.[]'
done

# Set user-supplied static nodes, and also as trusted nodes
if [ -n "${EXTRA_STATIC_NODES}" ]; then
  for string in $(jq -r .[] <<< "${EXTRA_STATIC_NODES}"); do
    dasel put -v $(echo $string) -f config.toml 'Node.P2P.StaticNodes.[]'
    dasel put -v $(echo $string) -f config.toml 'Node.P2P.TrustedNodes.[]'
  done
fi
```

**Comment by brilliant-lx** [comment]
> Interesting. To keep the binance-supplied StaticNodes from "getting flushed out", I am adding them to TrustedNodes as well, which isn't subject to the max peer limit.
> 
> Something like this:
> 
> ```
> # Duplicate binance-supplied static nodes to trusted nodes
> for string in $(dasel -f config.toml -w json 'Node.P2P.StaticNodes' | jq -r .[]); do
>   dasel put -v $(echo $string) -f config.toml 'Node.P2P.TrustedNodes.[]'
> done
> 
> # Set user-supplied static nodes, and also as trusted nodes
> if [ -n "${EXTRA_STATIC_NODES}" ]; then
>   for string in $(jq -r .[] <<< "${EXTRA_STATIC_NODES}"); do
>     dasel put -v $(echo $string) -f config.toml 'Node.P2P.StaticNodes.[]'
>     dasel put -v $(echo $string) -f config.toml 'Node.P2P.TrustedNodes.[]'
>   done
> fi
> ```

The problems is that, these binance-supplied nodes already face the same problem, there are too many "Erigon Nodes" connected, which makes them already reached the MaxPeer limit, so new connections to them will be rejected as well.

**Comment by yorickdowne** [comment]
Fun. The allegedly fake Erigon nodes that might not actually be Erigon.
Never a dull moment in crypto.

**Comment by brilliant-lx** [comment]
> 

I think we will figure out a solution to GC these peers when connection is at a high level, but may take time.

**Comment by yorickdowne** [comment]
Closing this. Copying StaticNodes to TrustedNodes and adding a few additional Static/Trusted nodes from "tribal knowledge" has stabilized our sync on 1.1.21 and 1.1.22, as well as for our fellow NOs. Thanks for engaging!
