### ISSUE TITLE
Error when executing "make devtools" - Makefile pointing to a wrong repo.

### ISSUE THREAD

**Issue by nmiceli-simtlix** [bnb-chain/bsc#1399]
BSC v1.1.21

When executing "make devtools" I get the following error:
```
go: github.com/kevinburke/go-bindata/go-bindata@latest: module github.com/kevinburke/go-bindata@latest found (v1.1.0), but does not contain package github.com/kevinburke/go-bindata/go-bindata
make: *** [Makefile:77: devtools] Error 1
```
This line is wrong:
https://github.com/bnb-chain/bsc/blob/master/Makefile#L77

It should be:
`env GOBIN= go install github.com/kevinburke/go-bindata@latest`

**Comment by ZiyuanStar** [comment]
will fix this, thx for the feedback

**Comment by brilliant-lx** [comment]
fixed in: https://github.com/bnb-chain/bsc/pull/1403
