### ISSUE TITLE
wrong command installing `go-bindata` in Makefile

### ISSUE THREAD

**Issue by yutianwu** [bnb-chain/bsc#1402]
The command installing `go-bindata` in Makefile is outdated:

https://github.com/bnb-chain/bsc/blob/master/Makefile#L77

it should be `github.com/kevinburke/go-bindata@latest` instead of `github.com/kevinburke/go-bindata/go-bindata@latest`.

**Comment by deepcrazy** [comment]
> The command installing `go-bindata` in Makefile is outdated:
> 
> https://github.com/bnb-chain/bsc/blob/master/Makefile#L77
> 
> it should be `github.com/kevinburke/go-bindata@latest` instead of `github.com/kevinburke/go-bindata/go-bindata@latest`.

Hi there, Thanks for the feedback. We've informed the team and will update you once we receive further updates on this. Thanks.

**Comment by VOITURE90** [comment]
Hi tanck you 🙂
