### ISSUE TITLE
请问debug_tracecall和debug_tracetransaction在轻节点、全节点、存档节点上执行有什么区别？

### ISSUE THREAD

**Issue by xiaozanooo** [bnb-chain/bsc#1404]
请问debug_tracecall和debug_tracetransaction在轻节点和全节点上执行有什么区别？
我本地部署轻节点，使用这2个功能都有些奇怪的问题，比如tracecall中设置固定区块号，感觉没用效果。
使用tracetransaction只有在刚生成TX时可以使用，过一段时间再调试同一条TX会提示，有更高的NONCE生成，大概这个意思。

**Comment by ZiyuanStar** [comment]
轻节点应该不可以， 如果trace的话需要先在disk存储全部的交易数据和一些其他数据，这些目前轻节点还做不到。建议你使用全节点试下
