### ISSUE TITLE
BSC faucet with problems. BSC has problems that need to be solved

### ISSUE THREAD

**Issue by italoHonoratoSA** [bnb-chain/bsc#1407]
# rationale

The Binance Smart Chain network is getting more and more complicated to use. If it continues like this, BSC will go bankrupt and lose space to other blockchains.

The BNB faucet is getting more and more horrible. 3 years ago we could claim something like 20 BNB for testing. This amount has been decreasing and is currently at 0.1 BNB. **Sounds like a joke**, but those responsible for the faucet are actually providing 0.1 BNB for developers to work and develop.

**_The BSC will die if this continues like this. Without BNB testnet there is no incentive for software development, testing and improvement. Also, it makes everything more difficult for the developer._**

Some might say we can test on local network with local test BNB, but the work is just as big as a contract often needs to interact with other contracts on the test network. Example, interacting with the Uniswap V2 contract, farm contracts...

In addition, other factors are hampering development at the BSC:

- mainnet RPC endpoint is constantly unstable in recent months
- endpoint RPC testnet lately it seems that it doesn't work right, with very frequent drops, and with that we need to keep looking for other RPC that is working
- Remix Ethereum made updates that are hampering development (eg, they removed the error message display when reverting, making debugging difficult)
- user experience with metamask is not easy and practical. Compared to other blockchain wallets, the metamask falls far short of expectations

I understand and I know perfectly well that these last two examples are something that is not within the scope of this conversation, but it serves to help this discussion about the increasing difficulty of using the network.

When developers open a pull to report issues with the faucet, there isn't any due attention:

https://github.com/bnb-chain/bsc/issues/1340
https://github.com/bnb-chain/bsc/issues/900
https://github.com/bnb-chain/bsc/issues/1338

So because of faucet attacks they will only release 0.1 BNB for testing?

# Suggestion
The faucet should once again provide a decent amount of BNB.

Faucet should stop going offline because of attacks. A mere spam attack to drain the faucet's balance shouldn't take it offline. It is constantly offline and with the following error message:

If the attack is not infrastructure related, taking the system offline only hurts the developers.

![image](https://user-images.githubusercontent.com/89170101/229381927-0f98d81c-1fff-45cc-9997-2658350a7442.png)

Those responsible for the faucet should not make life difficult for developers, they should facilitate and make it possible.

**If the faucet is being attacked or whatever the excuse**, this shouldn't be a justification for providing 0.1 BNB, as just deploying a contract can cost something like 0.07 BNB and drains all balance quickly.

I don't know exactly how it works, but you have some freedom to MINT/CREATE BNB testnet or get them somehow, but even then it seems that you prefer to punish the developer who needs a few test BNB to work.

**Comment by edgeofthegame2** [comment]
Test on Mainnet.

**Comment by italoHonoratoSA** [comment]
> Teste na rede principal.

Hello. Test what? Like this?

**Comment by SonderRill** [comment]
the same
![image](https://github.com/bnb-chain/bsc/assets/49909245/2a12691f-adcd-48d7-a3ff-c71506fde749)

**Comment by italoHonoratoSA** [comment]
> the same ![image](https://user-images.githubusercontent.com/49909245/237821923-2a12691f-adcd-48d7-a3ff-c71506fde749.png)

The faucet makers think 0.1 BNB a day is enough for us developers to spend all day working and testing code. Deploying a contract is costing between 0.08 and 0.15 BNB. They are a bad joke.

They still haven't responded to this thread and haven't even given it any attention. What maintains the BSC are the developers. If BSC dies they will be to blame.

**Comment by zzzckck** [comment]
faucet is ok now.

**Comment by italoHonoratoSA** [comment]
> faucet is ok now, it provides 0.3BNB each time.

It was ok when you accessed the website. But it keeps falling down and out of the air.

0.3 BNB remains insufficient. So nothing has changed. Have you been to the faucets of other altcoins? They are not a bad joke like the BSC Faucet.

**Comment by zzzckck** [comment]
> > faucet is ok now, it provides 0.3BNB each time.
> 
> It was ok when you accessed the website. But it keeps falling down and out of the air.
> 
> 0.3 BNB remains insufficient. So nothing has changed. Have you been to the faucets of other altcoins? They are not a bad joke like the BSC Faucet.

0.3BNB should be sufficient to run hundreds of transaction, no enough? How much BNB do you need?
