### ISSUE TITLE
Tx Propagation Issues

### ISSUE THREAD

**Issue by 0xprincess** [bnb-chain/bsc#1409]
#### System information

Geth version: `Geth/v1.1.18`
OS & Version: Linux

#### Expected behaviour
Transaction gets propagated from the local txpool and included in the `latest block + 2`
When mined, tx is removed from the local txpool

#### Actual behaviour
Transaction doesn't get propagated from the local txpool for a long (currently unknown) time.
Transaction is not removed from the local txpool when minted.

The issue didn't appear instantly, but after a long time of running the node. Currently, after the node restart, first tx sent from a certain address propagates fine, all the next transactions are stuck as described.

#### Steps to reproduce the behaviour
?

Most probably related to these reported issues https://github.com/bnb-chain/bsc/issues/1334 and https://github.com/bnb-chain/bsc/issues/1362 and this PR https://github.com/bnb-chain/bsc/pull/1348

Transactions seems to not be propagated / leave local txpool on block inclusion for a long time. We're sending transactions from multiple accounts quite frequently, multiple times per minute, but recently we started to get "replacement transaction underpriced" errors, as our txs don't leave the local txpool for a long time, even when they're included in the new blocks and the node is fully synced. It seems like it's not related to node sync, our node is always up-to-date with the chain, has 600 peers in config and ~200 real peers connected.
To debug the issue, I removed the tx replacement check in `txList.Add` function and the error seems to be gone on the local node, as txs started to replace each other in the local txpool, but they're seem to be not propagating / stuck on other nodes as well and being rejected.

**Comment by kris-ss** [comment]
Hello, your geth client version (v1.1.18) is outdated. Can you update to the latest one and see if it can still be reproduced?
