### ISSUE TITLE
track: there could be a potential bug in transaction propagation.

### ISSUE THREAD

**Issue by brilliant-lx** [bnb-chain/bsc#1413]
#### System information

Geth version: v1.1.21
OS & Version: Linux
Commit hash : tag v1.1.21

#### Expected behavior
transactions could be propagated to other peers.

#### Actual behavior
transactions were not propagated to other peers, while block fetch is working.

#### Steps to reproduce the behavior
its configured `static nodes` may unhealthy any more, restart the client, send transaction to the client, you will see the txpool keeps growing and reach a very high level.
It seems the received transactions were not propagated, so they are accumulating in the txpool, not consumed...

but after the client updated its static nodes to healthy ones, the problem disappear.
likely, there could be a potential bug, when connected to some `bad` node, in which case, the node can import block, but not able to propagate the transaction.

#### Backtrace
No backtrace

**Comment by ayrat555** [comment]
we're experiencing the same issue with v1.1.21, not sure about v1.1.18. 

I think it's related to https://github.com/bnb-chain/bsc/issues/1397

**Comment by brilliant-lx** [comment]
> we're experiencing the same issue with v1.1.21, not sure about v1.1.18

Have you tried to update your StaticNodes setting?

**Comment by leoenes** [comment]
> > we're experiencing the same issue with v1.1.21, not sure about v1.1.18
> 
> Have you tried to update your StaticNodes setting?

Hey man, I work in the same company from @ayrat555. Do you mean trying to run 1.1.21 with the staticNodes  from 1.1.19?

**Comment by brilliant-lx** [comment]
I mean, try v1.1.21 with the config.toml in v1.1.21's mainnet.zip, the StaticNodes in config.toml was updated today.
https://github.com/bnb-chain/bsc/releases/tag/v1.1.21
<img width="851" alt="image" src="https://user-images.githubusercontent.com/92799281/230109075-e552a4d5-acd0-40ba-9e3c-a6bfdb3e14d9.png">

**Comment by leoenes** [comment]
> I mean, try v1.1.21 with the config.toml in v1.1.21's mainnet.zip, the StaticNodes in config.toml was updated today. https://github.com/bnb-chain/bsc/releases/tag/v1.1.21 <img alt="image" width="851" src="https://user-images.githubusercontent.com/92799281/230109075-e552a4d5-acd0-40ba-9e3c-a6bfdb3e14d9.png">

Yes, We are talking about this mainnet.zip version. The problematic version was this one.

**Comment by nikolinsko** [comment]
just as a side note:

I'm experiencing the same behaviour on the node-real fork of erigon, had a transaction in limbo for 14 hours yesterday.

**Comment by zzzckck** [comment]
v1.2.x will no longer be supported, clean up these issue.
