### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by tushkaty** [bnb-chain/bsc#1415]
There seems to be some new security flaw in the BSC. 

I have been using BSC from many years and have done many tranctions. 

I sold some coins to BUSD -> https://bscscan.com/tx/0x02b41ff72adbfaa441ff7934acb23c57832e2f8f79f2da3c6ba70aadca0b712a

The BUSD came to my wallet and went automatically to some other wallet. 

https://bscscan.com/token/0xe9e7cea3dedca5984780bafc599bd69add087d56?a=0x1f049002e4d68ad8a072bf71d1690fabad33cfeb (See last 2 transactions)

https://bscscan.com/token/0xe9e7cea3dedca5984780bafc599bd69add087d56?a=0xebc27890512474411ee7d894d27c75cdb2082a60
This is the bot which is scamming many wallets where my BUSD went automatically. 

App used - MetaMask iOS
Dex - Poocoin.app

**Comment by kris-ss** [comment]
Hello, I suggest you check and review token spend approvals here - **https://bscscan.com/tokenapprovalchecker?search=0x1f049002e4d68ad8a072bf71d1690fabad33cfeb**

I believe you may have provided approvals to malicious contracts that would drain your tokens the moment they are deposited to your wallet.

**Comment by tushkaty** [comment]
I have only approved 1 transaction to sell $BSCS and I went to my wallet after success, I saw no tokens. Upon checking I found this https://bscscan.com/tx/0x0110119fc42236623f4d2b627752e059e590d038e0a2477bf3384dce427ca4e0

It happened same time. See the timestamp when I sold BSCS for BUSD https://bscscan.com/tx/0x02b41ff72adbfaa441ff7934acb23c57832e2f8f79f2da3c6ba70aadca0b712a

**Comment by zzzckck** [comment]
seems like it is not a chain issue.
