### ISSUE TITLE
Can't properly get new pending tx

### ISSUE THREAD

**Issue by liczn** [bnb-chain/bsc#1435]
Hello, my node used to get new pending tx proprely. But since I moved to a new location, I only get very few new pending transaction with it.

It is weird because the bandwidth of the new location is way enough, the binaries are up to date and the node is synced.

Any idea what could cause that and how to fix it ? What infos could I share to help you ?

**Comment by isaacyuno** [comment]
Hi, what's your start up command? geth version?

**Comment by isaacyuno** [comment]
I have a fast node as well and my txpool.status is
  pending: 470,
  queued: 68

I think it is related to your peers. What's your txpool.status and net.peerCount?

**Comment by liczn** [comment]
I've been able to check.

txpool.status
{
  pending: 0,
  queued: 0
}

net.peerCount
o

**Comment by liczn** [comment]
Fixed by adding those peers to static nodes [https://api.binance.org/v1/discovery/peers](url).
I also increased the max peers value in the config to 200. I now have 66 peers when checking net.peerCount.

**Comment by crypt0inf0** [comment]
@isaacyuno Can you tell me your fast node start up command? geth version?
