### ISSUE TITLE
get trace is particularly slow

### ISSUE THREAD

**Issue by dg123lzk** [bnb-chain/bsc#1442]
After upgrading to the latest version, the response time to get trace is particularly slow

**Comment by brilliant-lx** [comment]
traceTransaction?
Could you provide more information?

**Comment by kemorebiyyj** [comment]
After upgrading to the latest version,the syncing blocks very slow ,anybody  know how to solve it?
![image](https://github.com/bnb-chain/bsc/assets/125997533/dcf3239b-85aa-449c-b584-081cd8458ed2)

**Comment by kemorebiyyj** [comment]
54s sync 2 blocks,my geth shell is:
![c553e54e7ad74ed2d0c2c3fbf3e9b39](https://github.com/bnb-chain/bsc/assets/125997533/2a21c91c-1407-4ab2-8018-59539984ab93)
