### ISSUE TITLE
How to run archieve bsc node

### ISSUE THREAD

**Issue by duongvansang** [bnb-chain/bsc#1454]
Erigon is no longer support bsc, 

I am trying to find document to run bsc archieve node with geth, but not found yet.
I see also nn binance doc website mention about multi segment node (each node host only less than 4TB or old data), but there is no detail information.

Please give advice about it

**Comment by ZiyuanStar** [comment]
erigon is now supported by nodereal, pls check it out:
https://github.com/node-real/bsc-erigon

**Comment by duongvansang** [comment]
Thank you @ZiyuanStar, just build and sync from beginning right? we I need to download snapshot from S3 also?

**Comment by yongjun925** [comment]
I also want to know how to perform segmented synchronization, and whether snapshots can still be used.

**Comment by duongvansang** [comment]
Hi @ZiyuanStar, when I run erigon for ethereum node, I have issue that contract event cannot fetch, it's always return empty array. did you face with that issue on bsc fork?
