### ISSUE TITLE
Can't open the smart chain faucet

### ISSUE THREAD

**Issue by ale-fuentes-ar** [bnb-chain/bsc#1457]
I cannot get BNB smart cain... after set my address, and click the 'Give me BNB' nothing do and show next msg "Beep-bop, you're a robot!"

your can help me please?

**Comment by 0xLyon** [comment]
The faucet is experiencing some issues today. We have reported this internally and are awaiting feedback.
You can share your wallet address here or join our discord server(https://discord.gg/bnbchain) and share your address there, whereby I can fund your wallet in the meanwhile.

**Comment by ale-fuentes-ar** [comment]
my wallet is: 0xE48f7F8De62AcBD713eE027Bd873DC45FFE8fdEF

**Comment by 0xLyon** [comment]
Thanks, I have funded your provided address.

**Comment by brilliant-lx** [comment]
Faucet should have been recovered, right? I will close the issue.
