### ISSUE TITLE
is BSC base gas set to 3 from 5 ?

### ISSUE THREAD

**Issue by kugimiya530** [bnb-chain/bsc#1478]
is BSC base gas set to 3 from 5 ?

**Comment by kris-ss** [comment]
Hello. No, it is still at 5 gwei. You can refer to https://bscscan.com/gastracker to track the current gas price on BSC.

There is a proposal though to lower the transaction fee on BSC - you can follow/comment on this thread - https://forum.bnbchain.org/t/a-proposal-for-adopting-a-lower-transaction-fee-cost-on-bnb-smart-chain-to-enhance-competitiveness/977/6

**Comment by kris-ss** [comment]
@kugimiya530 Just to update, some of the validators already changed to 3 while some are still on 5 - https://forum.bnbchain.org/t/a-proposal-for-adopting-a-lower-transaction-fee-cost-on-bnb-smart-chain-to-enhance-competitiveness/977/42?u=kris-ss

**Comment by kugimiya530** [comment]
> @kugimiya530 Just to update, some of the validators already changed to 3 while some are still on 5 - https://forum.bnbchain.org/t/a-proposal-for-adopting-a-lower-transaction-fee-cost-on-bnb-smart-chain-to-enhance-competitiveness/977/42?u=kris-ss

thx
