### ISSUE TITLE
Imported new chain segment Problem

### ISSUE THREAD

**Issue by kugimiya530** [bnb-chain/bsc#1497]
geth version is 1.1.23

and never happen this problem before  hardfork

for example block was array like  20005000 20005001 20005002 20005003

but today first time i issue this problem

check the timestamp 

t=2023-04-20T22:17:36+0800 lvl=info msg="Imported new chain segment"             blocks=1  txs=2832 mgas=123.837 elapsed=333.487ms   mgasps=371.339  number=27,515,210 

t=2023-04-20T22:17:36+0800 lvl=info msg="Imported new chain segment"             blocks=1  txs=4786 mgas=138.632 elapsed=231.398ms   mgasps=599.106  number=27,515,209 

t=2023-04-20T22:17:39+0800 lvl=info msg="Imported new chain segment"             blocks=1  txs=4779 mgas=138.629 elapsed=1.129s      mgasps=122.682  number=27,515,209 

t=2023-04-20T22:17:39+0800 lvl=info msg="Imported new chain segment"             blocks=1  txs=0    mgas=0.000   elapsed=5.373ms     mgasps=0.000    number=27,515,211 

t=2023-04-20T22:17:42+0800 lvl=info msg="Imported new chain segment"             blocks=1  txs=4782 mgas=138.633 elapsed=216.924ms   mgasps=639.082  number=27,515,209 

what will cause this problem

also , this is happen on my different 2 node , and even the blocknumber and time is same。

**Comment by deepcrazy** [comment]
I can see that your node is getting synced in this case and doesn't have an issue. 
Also, As mentioned, it is not usual and could happen due to network congestion or chain reorganizations. It should get resolved automatically by nodes.
