### ISSUE TITLE
Problem with eth_subscribe after updating to version 1.1.23

### ISSUE THREAD

**Issue by rootsoklahoma** [bnb-chain/bsc#1506]
After upgrading to v1.1.23 the number of responses returned to eth_subscribe has become much lower.
We use the method **eth_subscribe** with params **["newHeads"]** via websockets. When we used it with v1.1.21 we had about 100 replies per second but after upgrading to v1.1.23 the number can be anywhere from 1-5 per 5-60 seconds. Sometimes it can be 1 response and then we have to reconnect to websockets to get a response again.
We tried to downgrade to v1.1.21 but it did not work, the number of subscriptions remained the same.
Node is always at the current height at the moment when we execute requests.

Could this be a geth client problem or might we need to resync the node on actual snapshot?

**Comment by 0xLyon** [comment]
@rootsoklahoma Can you provide more details to the specific subscribe that you are performing?
Would it also be possible to provide some samples of the previous expected responses that you received before this issue took place, vs how you are experiencing it currently?

**Comment by rootsoklahoma** [comment]
@0xLyon 
We use request with
`{"id":1,"jsonrpc":"2.0","method":"eth_subscribe","params":["newHeads"]}`
and get a valid response to it, like this one:
`{
	"jsonrpc": "2.0",
	"method": "eth_subscription",
	"params": {
		"subscription": "0xbb26f4beab511f6f62497e0d5bd018eb",
		"result": {
			"parentHash": "0x4797ee6c2c82c8433aac621c9bdd4942469895081609979424133e748d42d0fb",
			"sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
			"miner": "0xbe807dddb074639cd9fa61b47676c064fc50d62c",
			"stateRoot": "0x25163bf8ced6ec2d987e0b77437fe6be8e14d30ca956f294e04cf1ee35441633",
			"transactionsRoot": "0x15e6253b7d0ae5bad74a01b14d9b9c3bbedb4174fda6a6cc480d538b3a6d91c2",
			"receiptsRoot": "0x42ec3011c3ac0edc283a8ecf2df5b22b30273d6fec80008ddc01ea5760ca73d7",
			"logsBloom": "0xacf72e16497631fb05dae497f324bdff957e5f63cd6ffeee5fc4d9f53417f9d2e7ac5fbef9ff28ab8dfcfdb12a77b1f6ffb3f229b7fb37b171dba8dfcf7cab9d6641dffaff79ef3b9ffffde99decd138fcf2bce653e5fb0ffbf6b6349da1fbade904a8af1ed286674eff5df6b79cfe6fc888ccf752bc7f311426bbb6edbc0e4299beb775c3bdfaf5ed9b9709f8ab1fbdde3495a56de7380b7c3995d53f06de2d22fecdcb77a5f3fbaa4671d522427ecca7a90ecdbbcc1a7f0b74fa7dc99daa7ebdc7febf3f861dfff7a191a5f89e9db9a953df76fdcd261fdbfbd5a66009fc7ef474e45b53e9f258ebd74fcb9b2bbe2e587e63feae94f758b73f7d6f5ca40ed1",
			"difficulty": "0x2",
			"number": "0x1a49839",
			"gasLimit": "0x84fd227",
			"gasUsed": "0x15a51f9",
			"timestamp": "0x64438786",
			"extraData": "0xd883010117846765746888676f312e31392e38856c696e7578000000f98d1072e2b0539bf71787c4250d3b3ea30601bedf565f7c9420379b7f413210ac662c720eae1f438dc9171864e08e1a3e93c8534177a0df0174f3b295f664e6e80a3f9f00",
			"mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
			"nonce": "0x0000000000000000",
			"baseFeePerGas": null,
			"hash": "0x0a99c2f957c79b69bdf18deba0f900c1f36d5bd466ed9704a001e5ce8db40359"
		}
	}
}`

On v1.1.21 and earlier we got about 1000 responses per minute, but now on v1.1.23 we get about 25 responses per minute
