### ISSUE TITLE
Impossible to init GENESIS.JSON

### ISSUE THREAD

**Issue by banlieu451** [bnb-chain/bsc#1513]
**in folder /bsc/build/bin/
i do :** 

`wget https://github.com/binance-chain/bsc/releases/download/v1.1.23/mainnet.zip && unzip mainnet.zip`
`./geth --datadir node init genesis.json `
 _**return**_
`Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.`

`geth --datadir node init genesis.json `
**_return_**
`Fatal: Failed to read genesis file: open genesis.json: permission denied`

with root sudo or not same issue

![Sans titre](https://user-images.githubusercontent.com/76543738/233873740-50a6d940-733d-4cef-805e-784519417493.png)

**Comment by isaacyuno** [comment]
What's your go version? Could you update your go then build geth again?

**Comment by banlieu451** [comment]
up

**Comment by brilliant-lx** [comment]
same issue, pls refer: https://github.com/bnb-chain/bsc/issues/1521

**Comment by banlieu451** [comment]
OK it work ! Just try last version do : 

- wget https://github.com/binance-chain/bsc/releases/download/v1.2.0/mainnet.zip && unzip mainnet.zip
and launch ./geth

**Comment by banlieu451** [comment]
Still don't work we use a INTEL XEON processeur 24 cores this materials is out of using bsc incredible ?

**Comment by brilliant-lx** [comment]
still have the problem?
