### ISSUE TITLE
Frequent 503

### ISSUE THREAD

**Issue by aiwujiwudeguyue** [bnb-chain/bsc#1517]
Frequent 503
![微信截图_20230424143412](https://user-images.githubusercontent.com/104301173/233917288-2e95b71a-9291-4b50-bbff-38f0d4bb7e37.png)

**Comment by isaacyuno** [comment]
How did you get this error?

**Comment by aiwujiwudeguyue** [comment]
Occasionally occurs when the node is running

isaacyuno ***@***.***> 于2023年4月25日周二 08:34写道：

**Comment by isaacyuno** [comment]
Are you getting it from your bsc.log? Or from RPC call?

**Comment by aiwujiwudeguyue** [comment]
RPC call

isaacyuno ***@***.***> 于2023年4月25日周二 12:46写道：

**Comment by isaacyuno** [comment]
When you get the error, did you find any error/warning on your node bsc.log?

**Comment by aiwujiwudeguyue** [comment]
No, 503 is only returned when called on the chain

isaacyuno ***@***.***> 于2023年4月25日周二 12:49写道：

**Comment by brilliant-lx** [comment]
@aiwujiwudeguyue do you still have the problem?
