### ISSUE TITLE
Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md. 

### ISSUE THREAD

**Issue by banlieu451** [bnb-chain/bsc#1521]
Hello i can't still launch from this new version i need help

go version is the lastest
**in folder /bsc/build/bin/
i do :** 

`wget https://github.com/binance-chain/bsc/releases/download/v1.1.23/mainnet.zip && unzip mainnet.zip`
`./geth --datadir node init genesis.json `
 _**return**_
`Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.`

`geth --datadir node init genesis.json `
**_return_**
`Fatal: Failed to read genesis file: open genesis.json: permission denied`

with root sudo or not same issue

![Sans titre](https://user-images.githubusercontent.com/76543738/233873740-50a6d940-733d-4cef-805e-784519417493.png)

**Comment by brilliant-lx** [comment]
https://github.com/bnb-chain/bsc/tree/develop#building-the-source
```
export CGO_CFLAGS="-O -D__BLST_PORTABLE__" 
export CGO_CFLAGS_ALLOW="-O -D__BLST_PORTABLE__"
```
Pls try with the above env set.
`blst` has problem in some old cpu, could cause SIGILL.

**Comment by banlieu451** [comment]
Im gonna try but the CPU is good i run full node from 1 year it just dont work with this new version something have change

**Comment by banlieu451** [comment]
> ```
> export CGO_CFLAGS_ALLOW="-O -D__BLST_PORTABLE__"
> ```

I do it and don't work need help please

**Comment by banlieu451** [comment]
OK it work ! Just try last version do : 

- wget https://github.com/binance-chain/bsc/releases/download/v1.2.0/mainnet.zip && unzip mainnet.zip
and launch ./geth

**Comment by banlieu451** [comment]
Still don't work we use a INTEL XEON processeur 24 cores this materials is out of using bsc incredible ?

**Comment by plansten** [comment]
> Still don't work we use a INTEL XEON processeur 24 cores this materials is out of using bsc incredible ?

Not working if processor don`t have "3dnowprefetch" flag.

**Comment by GBBx** [comment]
Hi,

I've had this issue before with some other software that has the blst dependency.
The key is to set the variables as @brilliant-lx mentioned:
```
export CGO_CFLAGS="-O -D__BLST_PORTABLE__" 
export CGO_CFLAGS_ALLOW="-O -D__BLST_PORTABLE__"
```
and **build it on a machine that does not have the CPU flag** (e.g. the machine where bnb-bsc will be running).
I hope it helps.
