### ISSUE TITLE
new release v1.2.0 geth_linux is not works

### ISSUE THREAD

**Issue by m1iktea** [bnb-chain/bsc#1525]
#### Expected behaviour
geth ok

#### Actual behaviour
```bash
[root@k8s-123-95 bsc]# sha256sum geth_linux 
75f50ce27b8ea080d6adfb18b223d355f42298f740f734c1e40d0134c409847c  geth_linux
[root@k8s-123-95 bsc]# chmod +x ./geth_linux 
[root@k8s-123-95 bsc]# ./geth_linux -h
Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.
[root@k8s-123-95 bsc]# 
```

i download it from [release page](https://github.com/bnb-chain/bsc/releases/download/v1.2.0/geth_linux)

**Comment by kris-ss** [comment]
hi @m1iktea,

Tried on my end, did not get the same error.

![Screenshot 2023-04-25 at 3 01 00 PM](https://user-images.githubusercontent.com/113088090/234257496-634e0242-5beb-4079-8406-9fb32884b700.png)

 Please try chmod -v u+x geth_linux and ./geth_linux -h again.
 
 Also please note that **this version is not recommend for mainnet to use this version, especially validator, since more test is needed to make sure it is stable**.

**Comment by zoulja** [comment]
The same problem here:
```
$ uname -a
Linux testhost 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux
$ wget https://github.com/bnb-chain/bsc/releases/download/v1.2.0/geth_linux
$ chmod +x geth_linux
$ sha256sum geth_linux
75f50ce27b8ea080d6adfb18b223d355f42298f740f734c1e40d0134c409847c  geth_linux
$ ./geth_linux version
Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.

```

**Comment by kris-ss** [comment]
Hi @zoulja Please refer to this https://github.com/bnb-chain/bsc/issues/1521#issuecomment-1521025294


Pls try with the below env set and try again

export CGO_CFLAGS="-O -D__BLST_PORTABLE__" 
export CGO_CFLAGS_ALLOW="-O -D__BLST_PORTABLE__"

**Comment by zoulja** [comment]
Hi @kris-ss, thanks for cheking this
```
$ export CGO_CFLAGS="-O -D__BLST_PORTABLE__"
$ export CGO_CFLAGS_ALLOW="-O -D__BLST_PORTABLE__"
$ ./geth_v1.2.0 version
Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.
```

Previous version is working fine on this host

**Comment by banlieu451** [comment]
> Hi @zoulja Please refer to this [#1521 (comment)](https://github.com/bnb-chain/bsc/issues/1521#issuecomment-1521025294)
> 
> Pls try with the below env set and try again
> 
> export CGO_CFLAGS="-O -D__BLST_PORTABLE__" export CGO_CFLAGS_ALLOW="-O -D__BLST_PORTABLE__"

It don't work

**Comment by banlieu451** [comment]
OK it work ! Just try last version do : 

- wget https://github.com/binance-chain/bsc/releases/download/v1.2.0/mainnet.zip && unzip mainnet.zip
and launch ./geth

**Comment by banlieu451** [comment]
it work for me when deleting last golang-go version and downgrade it when doing this : 

- sudo apt remove golang-go
- sudo apt update && apt upgrade -y
- curl -LO https://go.dev/dl/go1.18beta1.linux-amd64.tar.gz
- sudo tar -C /usr/local -xzf go1.18beta1.linux-amd64.tar.gz
- export GOROOT=/usr/local/go
- export GOPATH=$HOME/go
- export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
- source ~/.bashrc
- go version
Normaly it gonna be : 1.18

**Comment by kris-ss** [comment]
@banlieu451 This is ok. You can ignore the warning messages. It will be resolved here -  https://github.com/bnb-chain/bsc/pull/1527

**Comment by m1iktea** [comment]
wait a second, This means that i cant just download the geth_linux in release page and use it? Do i have to download the build file and build the geth_linux by myself?

**Comment by banlieu451** [comment]
Do like this dear friend : (i use server linux unbuntu)

- git clone https://github.com/bnb-chain/bsc
- cd bsc
- **make all** 

- cd build/bin
-  wget https://github.com/binance-chain/bsc/releases/download/v1.2.0/mainnet.zip 
-  unzip mainnet.zip 
-  ./geth --datadir node init genesis.json
- ./geth .... yours commands ...
 _(ex: ./geth --config ./config.toml --datadir ./node --cache 18000 --rpc.allow-unprotected-txs --txlookuplimit 0 --maxpeers 60000 --syncmode snap --ws --ws.port 8546 --ws.addr localhost console )_

**Comment by zoulja** [comment]
Thanks for the workaround @banlieu451 but it doesn't solve the initial issue - broken official binary published in Release area, so typical upgrade procedure (just by replacing binary) can't be used anymore

**Comment by plansten** [comment]
Read my issue: https://github.com/bnb-chain/bsc/issues/1562

**Comment by GBBx** [comment]
I managed to fix this issue. Please see my comment here:
https://github.com/bnb-chain/bsc/issues/1521#issuecomment-1532850937

**Comment by m1iktea** [comment]
Thank you for your concern, this issue has been resolved, I cant download geth_linux form release page and it  works! 😊😊
```bash
wget https://github.com/bnb-chain/bsc/releases/download/v1.2.4/geth_linux
chmod +x geth_linux
./geth_linux -help
NAME:
   geth_linux - the go-ethereum command line interface

   Copyright 2013-2021 The go-ethereum Authors

USAGE:
   geth_linux [options] [command] [command options] [arguments...]
   
VERSION:
   1.2.4-3c5f54fc-20230523
...
```
