### ISSUE TITLE
V1.2.1 Can't Compile On Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by swlfigo** [bnb-chain/bsc#1535]
#### System information

Geth version: `v1.2.1`
OS & Version: Ubuntu
Commit hash : (542bb5b32e7250d98226702b8c1dbac14cb01cdc)

#### Expected behaviour
`make all` can compile geth

#### Actual behaviour
`make all` can't compile

#### Backtrace

````
[backtrace]
````
<img width="494" alt="iShot_2023-04-26_22 06 23" src="https://user-images.githubusercontent.com/6550691/234601325-bf26ad23-830c-4982-a7d9-f1feeff706ff.png">

I clone the last commit on master branch, install Go1.20.3 on my Ubuntu 22.04LTS server.After I execute command `make all`,then I get error. Is there any compile logs I can find or any tips about why it can't compile?

**Comment by isaacyuno** [comment]
You need to download the source code file from https://github.com/bnb-chain/bsc/releases/tag/v1.2.1 and build from there

**Comment by swlfigo** [comment]
> You need to download the source code file from https://github.com/bnb-chain/bsc/releases/tag/v1.2.1 and build from there

Same Problem, I download zip from https://github.com/bnb-chain/bsc/archive/refs/tags/v1.2.1.zip and unzip.`make all`, same problem(All New VPS Server with new installed Go1.20.3)

**Comment by FatTigerWang** [comment]
The same problem occurs in debain 11, go version go1.20.2 linux/amd64 And go version go1.20.3 linux/amd64

```bash
➜  bsc git:(master) make geth
env GO111MODULE=on go run build/ci.go install ./cmd/geth
>>> /usr/local/go/bin/go build -ldflags -X main.gitCommit=542bb5b32e7250d98226702b8c1dbac14cb01cdc -X main.gitDate=20230425 -extldflags -Wl,-z,stack-size=0x800000 -trimpath -v -o /home/chain/bsc/geth/bsc/build/bin/geth ./cmd/geth
github.com/herumi/bls-eth-go-binary/bls
# github.com/herumi/bls-eth-go-binary/bls
/root/go/pkg/mod/github.com/herumi/bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e/bls/cast.go:9:28: undefined: SecretKey
/root/go/pkg/mod/github.com/herumi/bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e/bls/cast.go:9:40: undefined: Fr
/root/go/pkg/mod/github.com/herumi/bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e/bls/cast.go:13:26: undefined: Fr
/root/go/pkg/mod/github.com/herumi/bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e/bls/cast.go:13:31: undefined: SecretKey
/root/go/pkg/mod/github.com/herumi/bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e/bls/cast.go:19:28: undefined: PublicKey
/root/go/pkg/mod/github.com/herumi/bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e/bls/cast.go:19:40: undefined: G1
/root/go/pkg/mod/github.com/herumi/bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e/bls/cast.go:23:26: undefined: G1
/root/go/pkg/mod/github.com/herumi/bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e/bls/cast.go:23:31: undefined: PublicKey
/root/go/pkg/mod/github.com/herumi/bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e/bls/cast.go:29:23: undefined: Sign
/root/go/pkg/mod/github.com/herumi/bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e/bls/cast.go:29:30: undefined: G2
/root/go/pkg/mod/github.com/herumi/bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e/bls/cast.go:29:30: too many errors
github.com/supranational/blst/bindings/go
# github.com/supranational/blst/bindings/go
/root/go/pkg/mod/github.com/supranational/blst@v0.3.8-0.20220526154634-513d2456b344/bindings/go/rb_tree.go:130:18: undefined: Message
github.com/prysmaticlabs/prysm/v3/encoding/bytesutil
# github.com/prysmaticlabs/prysm/v3/encoding/bytesutil
/root/go/pkg/mod/github.com/prysmaticlabs/prysm/v3@v3.2.1/encoding/bytesutil/bytes_go120.go:12:17: cannot convert PadTo(x, 4) (value of type []byte) to type [4]byte: conversion of slices to arrays requires go1.20 or later (-lang was set to go1.19; check go.mod)
/root/go/pkg/mod/github.com/prysmaticlabs/prysm/v3@v3.2.1/encoding/bytesutil/bytes_go120.go:19:18: cannot convert PadTo(x, 20) (value of type []byte) to type [20]byte: conversion of slices to arrays requires go1.20 or later (-lang was set to go1.19; check go.mod)
/root/go/pkg/mod/github.com/prysmaticlabs/prysm/v3@v3.2.1/encoding/bytesutil/bytes_go120.go:26:18: cannot convert PadTo(x, 32) (value of type []byte) to type [32]byte: conversion of slices to arrays requires go1.20 or later (-lang was set to go1.19; check go.mod)
/root/go/pkg/mod/github.com/prysmaticlabs/prysm/v3@v3.2.1/encoding/bytesutil/bytes_go120.go:33:18: cannot convert PadTo(x, 48) (value of type []byte) to type [48]byte: conversion of slices to arrays requires go1.20 or later (-lang was set to go1.19; check go.mod)
/root/go/pkg/mod/github.com/prysmaticlabs/prysm/v3@v3.2.1/encoding/bytesutil/bytes_go120.go:40:18: cannot convert PadTo(x, 64) (value of type []byte) to type [64]byte: conversion of slices to arrays requires go1.20 or later (-lang was set to go1.19; check go.mod)
/root/go/pkg/mod/github.com/prysmaticlabs/prysm/v3@v3.2.1/encoding/bytesutil/bytes_go120.go:47:18: cannot convert PadTo(x, 96) (value of type []byte) to type [96]byte: conversion of slices to arrays requires go1.20 or later (-lang was set to go1.19; check go.mod)
github.com/lucas-clemente/quic-go/internal/qtls
# github.com/lucas-clemente/quic-go/internal/qtls
/root/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.31.0/internal/qtls/go120.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declarationutil.go:46: exit status 1
exit status 1
make: *** [Makefile:15: geth] Error 1
```

**Comment by yangyangduo** [comment]
> 

have you resolve this problem, i have the same question

**Comment by yangyangduo** [comment]
# github.com/herumi/bls-eth-go-binary/bls
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:9:28: undefined: SecretKey
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:9:40: undefined: Fr
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:13:26: undefined: Fr
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:13:31: undefined: SecretKey
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:19:28: undefined: PublicKey
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:19:40: undefined: G1
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:23:26: undefined: G1
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:23:31: undefined: PublicKey
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:29:23: undefined: Sign
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:29:30: undefined: G2
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:29:30: too many errors
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:19:28: undefined: PublicKey
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:19:40: undefined: G1
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:23:26: undefined: G1
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:23:31: undefined: PublicKey
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:29:23: undefined: Sign
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:29:30: undefined: G2
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:29:30: too many errors
# github.com/supranational/blst/bindings/go
..\..\go\src\pkg\mod\github.com\supranational\blst@v0.3.8-0.20220526154634-513d2456b344\bindings\go\rb_tree.go:130:18: undefined: Message

**Comment by ZiyuanStar** [comment]
Please downgrade to go 1.19 and retry

**Comment by FatTigerWang** [comment]
> Please downgrade to go 1.19 and retry

Why downgrade?  the original 1.20.2 can be compiled success.

**Comment by FatTigerWang** [comment]
https://github.com/bnb-chain/bsc#building-the-source

The documentation states that as long as go >= 1.19 is satisfied

**Comment by swlfigo** [comment]
> Please downgrade to go 1.19 and retry

Same Problem With Go 1.19

**Comment by isaacyuno** [comment]
<img width="239" alt="Screenshot 2023-04-28 at 16 26 34" src="https://user-images.githubusercontent.com/110881390/235096726-4170d125-3e64-49eb-8d2f-cad43bb7c804.png">
I tried on go 1.19.3 to build without a problem, use either  Source code zip or tar.gz

**Comment by FatTigerWang** [comment]
When I rolled back the go version to 1.19.3, I compiled it and it prompted me that `gcc` was missing, so I installed the `gcc` environment:
```bash
apt install build-essential
apt-get install manpages-dev
```
Then execute `make geth` to compile successfully.

Then switch back to go version 1.20.3, the compilation still fails, which is unacceptable.

**Comment by buddh0** [comment]
golang v1.20.x would be supported in the incoming release v1.2.2

**Comment by swlfigo** [comment]
Fix in New Release 🍻🍻🍻

**Comment by constwz** [comment]
How did it work out

**Comment by swlfigo** [comment]
> How did it work out

I just pull master branch and compile (run command `make all`)

Ps: After update go version above 1.20+, I also config some building tool env on Ubuntu, run `sudo apt-get install build-essential`. Try config building env before compile Geth
