### ISSUE TITLE
v1.1.22 每天增长30G的数据有啥办法可以解决不

### ISSUE THREAD

**Issue by handsomevvv** [bnb-chain/bsc#1537]
bsc 节点的数据已经接近3.8TB 还在以每天30G左右的速度增长

**Comment by isaacyuno** [comment]
if you don't need historical blocks, you could use --pruneancient to keep only recent 90000 blocks

**Comment by handsomevvv** [comment]
> 

Thank you for your reply.
I have another question. My node has been running for half a year. If this command is added, will the historical data be pruned until it is completed before it can be synchronized?
Or start synchronization at startup and prune historical data during synchronization

**Comment by kris-ss** [comment]
Hi @handsomevvv, those historical data will not be pruned. The --pruneancient flag will only keep your node from adding additional historical data. To prune historical data, use the prune-block offline tool instead.

This is what I suggest you should do:
1) Stop your node
2) Use prune-block tool to prune ancient data https://docs.bnbchain.org/docs/validator/node-maintenance/#prune-block-tools
3) Once pruning is completed, you can start your node again, and this time with the --pruneancient=true added

**Comment by handsomevvv** [comment]
> Hi @handsomevvv, those historical data will not be pruned. The --pruneancient flag will only keep your node from adding additional historical data. To prune historical data, use the prune-block offline tool instead.
> 
> This is what I suggest you should do:
> 
> 1. Stop your node
> 2. Use prune-block tool to prune ancient data https://docs.bnbchain.org/docs/validator/node-maintenance/#prune-block-tools
> 3. Once pruning is completed, you can start your node again, and this time with the --pruneancient=true added

Thank you , bro

**Comment by handsomevvv** [comment]
done
