### ISSUE TITLE
Erigon v2.43.0 removed support BSC

### ISSUE THREAD

**Issue by 0x1un** [bnb-chain/bsc#1538]
Will bnb-chain maintain an erigon fork repo in the future?

**Comment by kris-ss** [comment]
Hello, we don't have information on that at the moment.

Right now, erigon will be supported by Nodereal, for more details please check https://nodereal.io/blog/en/bnb-smartchain/
Repository- https://github.com/node-real/bsc-erigon

**Comment by harveyff** [comment]
The branch maintained by node_real is not easy to use, the synchronization stability is too poor, it is difficult to apply to the production environment, please be cautious
