### ISSUE TITLE
Is there a best practice for synchronizing archive nodes?

### ISSUE THREAD

**Issue by harveyff** [bnb-chain/bsc#1539]
Hi guys,

Thank you for your great work,

Because erigon-bsc stopped updating, we had to abandon it (although node-real continued to maintain a new branch, we found that it was not stable enough to be used in a production environment after 2 weeks of use).

So we want to run a geth version of the bsc archive node. I know it is not easy. We have prepared 50T of storage space and corresponding equipment. Is there a good synchronization solution? We do need an archive node of our own.

I mean is there a reliable archive node geth snapshot? If the synchronization starts from the genesis block, I guess it may not be possible to complete the synchronization in 3 months.

I would be very grateful if you could provide some help.

**Comment by 0xLyon** [comment]
Hi @harveyff I believe the previously used archive node snapshots that was made available here (https://github.com/allada/bsc-archive-snapshot) is no longer maintained.
Let me check if there are any other available solutions for syncing a new archive node and I will update you accordingly.
