### ISSUE TITLE
Faster than eth_getLogs?

### ISSUE THREAD

**Issue by michaelr524** [bnb-chain/bsc#1541]
Indexing all erc20 transfers from the first block to the last with eth_getLogs is very slow.
CPU and io on the server is not highly utilized by the node.
We tried in different sizes of block batches - 100, 1000 etc..
Is there a configuration that could improve the speed of this?
Is there a different method to fetch these logs from the node, which is faster?

**Comment by deepcrazy** [comment]
Hi there, Could you provide more details like:
- Are you running your own node and then calling `eth_getLogs` method on your node? If so, which node are you running?
- What is your geth version?
- `geth` startup command?

Can you also share the logs when making `eth_getLogs` calls please.

Ideally, If you're running your own full node, then you can try out the following steps:
- Make sure to use latest geth version v1.2.9 or above from here: https://github.com/bnb-chain/bsc/releases
- increase the max peers to 200 or 300 by adding maxpeers in your geth startup command
- add the static nodes from here: https://api.binance.org/v1/discovery/peers in your config file.
