### ISSUE TITLE
v1.2.1 hangs for hours on exit

### ISSUE THREAD

**Issue by eyooooo** [bnb-chain/bsc#1544]
when trying to exit the latest release the node hangs, reporting `Looking for peers` for hours until finally exiting.

**Comment by deepcrazy** [comment]
Hi there, Can you provide more info please like running testnet node or mainnet? As this version is supposed to be used for running testnet node only. Please have a look on these versions: https://github.com/bnb-chain/bsc/releases/tag/v1.2.1 and https://github.com/bnb-chain/bsc/releases/tag/v1.2.0.

Also, please share more logs? And follow this guide for stopping the node gracefully: https://docs.bnbchain.org/docs/validator/upgrade-fullnode/#step-2-stop-geth

Please also share your geth startup command too.

**Comment by eyooooo** [comment]
> Hi there, Can you provide more info please like running testnet node or mainnet? As this version is supposed to be used for running testnet node only. Please have a look on these versions: https://github.com/bnb-chain/bsc/releases/tag/v1.2.1 and https://github.com/bnb-chain/bsc/releases/tag/v1.2.0.
> 
> Also, please share more logs? And follow this guide for stopping the node gracefully: https://docs.bnbchain.org/docs/validator/upgrade-fullnode/#step-2-stop-geth
> 
> Please also share your geth startup command too.

thanks for the info - which version should i use?

**Comment by deepcrazy** [comment]
Hi there, You can use the latest version v1.2.9 or above from here: https://github.com/bnb-chain/bsc/releases

Also, Try out the following steps after upgrading geth:
- increase the max peers to 200 or 300 by adding maxpeers in your geth startup command
- add the static nodes from here: https://api.binance.org/v1/discovery/peers in your config file.

**Comment by deepcrazy** [comment]
Hi there, Please upgrade geth to latest version v1.2.9 or above from here: https://github.com/bnb-chain/bsc/releases

Also, Try out the following steps after upgrading geth:
- increase the max peers to 200 or 300 by adding maxpeers in your geth startup command
- add the static nodes from here: https://api.binance.org/v1/discovery/peers in your config file.
