### ISSUE TITLE
1.2.1 Can not compile and binary data from github also doesn't running

### ISSUE THREAD

**Issue by zhaoyang777** [bnb-chain/bsc#1546]
#### System information

Geth version: `1.2.1`
OS & Version: Linux (Both)
Commit hash : (if `develop`)

On BSC Testnet Geth Node always show  'Looking for peers',
And then i try to download the newest version 1.2.1, i have some problems
1: First i couldn't compile linux version from windows device, and before is ok, there is a lot of errors from "herumi/bls-eth-go-binary"
2: I download the the binary geth_linux and start to running at Centos, it's can not startup.
I see this error "Caught SIGILL in blst_cgo_init"

So, old version can not use,  new version can not compile and also the binrary can not running!

**Comment by yangyangduo** [comment]
this is my command:
```
env GO111MODULE=on CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-X main.gitCommit= -X main.gitDate=" -o build/bin/geth-linux ./cmd/geth
``` 

<details><summary>Details</summary>
<p>

# github.com/herumi/bls-eth-go-binary/bls
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:9:28: undefined: SecretKey
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:9:40: undefined: Fr
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:13:26: undefined: Fr
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:13:31: undefined: SecretKey
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:19:28: undefined: PublicKey
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:19:40: undefined: G1
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:23:26: undefined: G1
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:23:31: undefined: PublicKey
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:29:23: undefined: Sign
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:29:30: undefined: G2
..\..\go\src\pkg\mod\github.com\herumi\bls-eth-go-binary@v0.0.0-20210917013441-d37c07cfda4e\bls\cast.go:29:30: too many errors

</p>
</details>

**Comment by ZiyuanStar** [comment]
you can simply download the binary and run it. please refer to here regarding for detailed steps:
https://docs.bnbchain.org/docs/validator/fullnode#steps-to-run-a-fullnode

**Comment by ZiyuanStar** [comment]
please downgrade to go 1.19 and retry

**Comment by ZiyuanStar** [comment]
please try to add the following environment variables and build again:

export CGO_CFLAGS="-O -D__BLST_PORTABLE__" 
export CGO_CFLAGS_ALLOW="-O -D__BLST_PORTABLE__"

**Comment by banlieu451** [comment]
Try downgrade to 1.19 (golang-go) and put command from Ziyuan  👍  and build again as Ziyuan say and it work

**Comment by brilliant-lx** [comment]
fixed by these 2 PRs:
SIGILL: https://github.com/bnb-chain/bsc/pull/1575
golang v1.20 compile: https://github.com/bnb-chain/bsc/pull/1576
