### ISSUE TITLE
v1.2.1 cannot compile with Go 1.20

### ISSUE THREAD

**Issue by yorickdowne** [bnb-chain/bsc#1549]
#### System information

Geth version: `1.2.1`
OS & Version: Linux

#### Expected behaviour

Geth can be built with Go 1.20, as the docs state "Building geth requires both a Go (version 1.19 or later)"

#### Actual behaviour

Building with Go 1.20 fails on `quic-go` with this error message:

```
#0 103.9 # github.com/lucas-clemente/quic-go/internal/qtls
#0 103.9 /go/pkg/mod/github.com/lucas-clemente/quic-go@v0.31.0/internal/qtls/go120.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declaration
```

Updating the quic-go dependency would likely solve this.

**Comment by yorickdowne** [comment]
I used to 1.19 and it built fine

**Comment by brilliant-lx** [comment]
quic-go was include by prysm, prysm v4 will use recent release of quic-go.
We may upgrade the prysm to solve it.

**Comment by brilliant-lx** [comment]
fixed, will be included in next release.
