### ISSUE TITLE
Node is not syncing after update to 1.21

### ISSUE THREAD

**Issue by adastreamer** [bnb-chain/bsc#1554]
#### System information

Geth
Version: 1.2.0
Git Commit: 542bb5b32e7250d98226702b8c1dbac14cb01cdc
Architecture: amd64

#### Expected/Actual behaviour

Node was always synced, except the last update.

#### Backtrace

````
t=2023-05-01T22:45:39+0000 lvl=warn msg="Database compacting, degraded performance" database=/bsc/node/geth/chaindata
t=2023-05-01T22:46:39+0000 lvl=warn msg="Database compacting, degraded performance" database=/bsc/node/geth/chaindata
t=2023-05-01T22:47:39+0000 lvl=warn msg="Database compacting, degraded performance" database=/bsc/node/geth/chaindata
t=2023-05-01T22:48:42+0000 lvl=warn msg="Database compacting, degraded performance" database=/bsc/node/geth/chaindata
t=2023-05-01T22:49:42+0000 lvl=warn msg="Database compacting, degraded performance" database=/bsc/node/geth/chaindata
t=2023-05-01T22:50:42+0000 lvl=warn msg="Database compacting, degraded performance" database=/bsc/node/geth/chaindata
t=2023-05-01T22:51:42+0000 lvl=warn msg="Database compacting, degraded performance" database=/bsc/node/geth/chaindata
````

**Comment by isaacyuno** [comment]
Do you still have enough disk space?

**Comment by adastreamer** [comment]
> Do you still have enough disk space?

Yes, of course

**Comment by brilliant-lx** [comment]
There could a potential deadlock, could you restart your node? the log is useless, it is just a periodical GC meesage

**Comment by driops** [comment]
We have this same issue. It has only affected one of our nodes so far, started this morning. We waited for compaction to finish, it took around 6 hours. Restarted at around 14 hours behind, compaction resumed once it got up to 9 hours behind. Filesystem is zfs, running on a pool with 2x SAMSUNG MZQL23T8HCLS-00A07 3.84TB nvme ssd's. 44% utilized.

Are downgrades of bsc client supported to 1.1.23 or will this corrupt database?
