### ISSUE TITLE
"Transaction was not mined within..." with increased gas price

### ISSUE THREAD

**Issue by stasionok** [bnb-chain/bsc#1556]
#### System information

Geth version: `1.23` and prev
OS & Version: Linux

#### Expected behaviour
I sometimes got `Transaction was not mined within 50/750 ...` and after increase gas price (now try with 15gwei) it should place trx correct

#### Actual behaviour
But I allready get that issue. 

Some time that failed transaction stuck in pool but other don't even get there.
I check that when try cancel stucked and get nonce too low

#### Steps to reproduce the behaviour
It appear with simple transfer erc20
I use web3.eth.sendSignedTransaction
```
txConfig = {
        from: account.address,
        to,
        value: 0,
        nonce: Contracts.nonce,
        data: data
      }

      let gasLimit = await this.web3Http.eth.estimateGas(txConfig)

      gasLimit = Math.floor(gasLimit * 1.5)
      txConfig.chainId = 56
      txConfig.gasPrice = toWei('15', 'gwei')
      txConfig.gas = gasLimit
```

I try my own nodes (with http and ws), try public http nodes. With all of them I get that issue. But not all time, it may be some amount of fails once by week, may be once by a few days. 
Transactions per day near 100-150

I see in explorer that same transactions successfully processed with 3-5 gwei

**Comment by stasionok** [comment]
update: I remove from txConfig nonce at all, remove gasPrice and now all transaction successfully mined with standart gas price.
What wrong with nonce, I took latest nonce [web3.eth.getTransactionCount()](https://web3js.readthedocs.io/en/v1.2.2/web3-eth.html#eth-gettransactioncount) and increase +1 per transaction without any error like 'nonce to low' etc.

**Comment by alexlucaci** [comment]
Hi! Can we close the issue? or there is something else to be clarified?

**Comment by stasionok** [comment]
Not clear why custom nonce throw too much **was not mined** but for me without setting custom nonce works for now

**Comment by zzzckck** [comment]
close for now, could reopen if still have the issue with latest v1.3.x releases.
