### ISSUE TITLE
smatchain node `stuck`

### ISSUE THREAD

**Issue by kasrakhamesi** [bnb-chain/bsc#1570]
![image](https://user-images.githubusercontent.com/80700084/236327646-691f2a4c-ebe2-4dc5-90a2-4995c3170291.png)

after 4 days,smartchain node only show me New local node record message and can't import new block,
last syncing is : {
currentBlock: 26799399,
highestBlock: 27921507,
knownStates: 297473485,
pulledStates: 297473485,
startingBlock: 26799399
}

I using https://github.com/bnb-chain/bsc-snapshots chaindata

I using this command to get config.toml and genesis.json file :

wget $(curl -s https://api.github.com/repos/bnb-chain/bsc/releases/latest |grep browser_ |grep mainnet |cut -d" -f4)
unzip mainnet.zip

and trying with this mainnet config too :
https://github.com/bnb-chain/bsc/releases/download/v1.1.8/mainnet.zip

my docker command for running node :

docker run -v /root/chaindata/smartchain/config:/home/config -v /root/chaindata/smartchain/server/data-seed:/home/node -p 8545:8545 -p 8546:8546 --rm --name bsc -it dysnix/bsc:v1.1.8 --config /home/config/config.toml --http.addr 0.0.0.0 --http.vhosts '*' --datadir /home/node

please help me :((

**Comment by kasrakhamesi** [comment]
> please upgrade your geth version to the latest and retry

that snapshot only work with geth v1.1.8

so, if I update node to latest version,chaindata can't using and should resync from genesis block.

I want sync from chaindata

**Comment by isaacyuno** [comment]
> > please upgrade your geth version to the latest and retry
> 
> that snapshot chaindata only work with geth v1.1.8
> 
> so, if I update node to latest version,chaindata can't using and should resync from genesis block.
> 
> I want sync from chaindata

You should use the latest version which is 1.2.1. (that 1.1.8 is just telling you about the prune feature.) You also need to use the correct config files. Please strictly follow this doc. https://docs.bnbchain.org/docs/validator/fullnode

**Comment by kasrakhamesi** [comment]
> > > please upgrade your geth version to the latest and retry
> > 
> > 
> > that snapshot chaindata only work with geth v1.1.8
> > so, if I update node to latest version,chaindata can't using and should resync from genesis block.
> > I want sync from chaindata
> 
> You should use the latest version which is 1.2.1. (that 1.1.8 is just telling you about the prune feature.) You also need to use the correct config files. Please strictly follow this doc. https://docs.bnbchain.org/docs/validator/fullnode

docker run -v /root/chaindata/smartchain/config:/bsc/config -v /root/chaindata/smartchain/server/data-seed:/bsc/node -p 8545:8545 --rm --name bsc -it ghcr.io/bnb-chain/bsc --http.addr 0.0.0.0 --http.port 8545 --http.vhosts '*'

I using this docker command but can't start sync

**Comment by kasrakhamesi** [comment]
> > > please upgrade your geth version to the latest and retry
> > 
> > 
> > that snapshot chaindata only work with geth v1.1.8
> > so, if I update node to latest version,chaindata can't using and should resync from genesis block.
> > I want sync from chaindata
> 
> You should use the latest version which is 1.2.1. (that 1.1.8 is just telling you about the prune feature.) You also need to use the correct config files. Please strictly follow this doc. https://docs.bnbchain.org/docs/validator/fullnode

still have problem ,

I Using docker run --rm -v /root/chaindata/smartchain/config:/bsc/config -v /root/chaindata/smartchain/node:/node -p 8545:8545 --rm --name bsc -it ghcr.io/bnb-chain/bsc --config /bsc/config/config.toml --datadir ./node --http.addr 0.0.0.0 --http.port 8545 --http.vhosts '*'

this command and get Fatal: Failed to create the protocol stack: open /bsc/node/geth/LOCK: permission denied,

but when running node without docker,successfully start,

please help me to improve my docker command to running node

I login with root user and docker has write and read permission and 2 directory are exists
