### ISSUE TITLE
not sync with latest block 

### ISSUE THREAD

**Issue by ashu1211** [bnb-chain/bsc#1591]
hii,
i have an issue with syncing, in mainnet, i am not able sync with latest block even with snapshot. in my case it reaches on current block then after some time it goes behind 120-130 block, and again repeat the same steps again and again.

**Comment by Liamlu28** [comment]
I have the same problem too.v1.2.3 unable to catch up with the latest block.

**Comment by kemorebiyyj** [comment]
me too.are you solved it?

**Comment by Liamlu28** [comment]
@kemorebiyyj  NuN. I've given up the BSC client

**Comment by CocoStarZ** [comment]
Pls refer to here https://github.com/bnb-chain/bsc/issues/1437#issuecomment-1504672203
