### ISSUE TITLE
error build

### ISSUE THREAD

**Issue by YudaAdiPratama** [bnb-chain/bsc#1593]
#### System information

Geth version: `v1.2.1`
OS & Version: OSX

Hello, I get an error at make all

#### log error

```
make all                                                                  ─╯
env GO111MODULE=on go run build/ci.go install
>>> /usr/local/go/bin/go build -ldflags -X main.gitCommit=542bb5b32e7250d98226702b8c1dbac14cb01cdc -X main.gitDate=20230425 -s -trimpath -v -o /Users/yuda/Documents/bsc/build/bin/abidump ./cmd/abidump
github.com/prysmaticlabs/gohashtree
# github.com/prysmaticlabs/gohashtree
asm: illegal combination: 23984 (/Users/yuda/go/pkg/mod/github.com/prysmaticlabs/gohashtree@v0.0.2-alpha/hash_arm64.s:604)	VMOV	$0, V16.S4 ZCON NONE NONE ARNG, 4 7
asm: illegal combination: 23984 (/Users/yuda/go/pkg/mod/github.com/prysmaticlabs/gohashtree@v0.0.2-alpha/hash_arm64.s:604)	VMOV	$0, V16.S4 ZCON NONE NONE ARNG, 4 7
asm: illegal combination: 23984 (/Users/yuda/go/pkg/mod/github.com/prysmaticlabs/gohashtree@v0.0.2-alpha/hash_arm64.s:604)	VMOV	$0, V16.S4 ZCON NONE NONE ARNG, 4 7
asm: illegal combination: 23984 (/Users/yuda/go/pkg/mod/github.com/prysmaticlabs/gohashtree@v0.0.2-alpha/hash_arm64.s:604)	VMOV	$0, V16.S4 ZCON NONE NONE ARNG, 4 7
asm: assembly failed
util.go:46: exit status 1
exit status 1
make: *** [all] Error 1
```

this error occurs on my Apple silicon.
please help me for solving this problem

**Comment by buddh0** [comment]
it has been fixed in the coming release v1.2.2

**Comment by YudaAdiPratama** [comment]
> it has been fixed in the coming release v1.2.2

I don't see tag v1.2.2 on the repository

**Comment by mcoelho80** [comment]
Same here with v1.2.3:

# make geth
env GO111MODULE=on go run build/ci.go install ./cmd/geth
>>> /usr/local/go120/bin/go build -trimpath -v -o /usr/home/admin/setup/bsc/1.2.3/build/bin/geth ./cmd/geth
github.com/prysmaticlabs/prysm/v4/crypto/bls
# github.com/prysmaticlabs/prysm/v4/crypto/bls
/root/go/pkg/mod/github.com/prysmaticlabs/prysm/v4@v4.0.2/crypto/bls/bls.go:19:14: undefined: blst.SecretKeyFromBytes
/root/go/pkg/mod/github.com/prysmaticlabs/prysm/v4@v4.0.2/crypto/bls/bls.go:24:14: undefined: blst.PublicKeyFromBytes
/root/go/pkg/mod/github.com/prysmaticlabs/prysm/v4@v4.0.2/crypto/bls/bls.go:29:14: undefined: blst.SignatureFromBytes
/root/go/pkg/mod/github.com/prysmaticlabs/prysm/v4@v4.0.2/crypto/bls/bls.go:34:14: undefined: blst.MultipleSignaturesFromBytes
/root/go/pkg/mod/github.com/prysmaticlabs/prysm/v4@v4.0.2/crypto/bls/bls.go:39:14: undefined: blst.AggregatePublicKeys
/root/go/pkg/mod/github.com/prysmaticlabs/prysm/v4@v4.0.2/crypto/bls/bls.go:44:14: undefined: blst.AggregateMultiplePubkeys
/root/go/pkg/mod/github.com/prysmaticlabs/prysm/v4@v4.0.2/crypto/bls/bls.go:49:14: undefined: blst.AggregateSignatures
/root/go/pkg/mod/github.com/prysmaticlabs/prysm/v4@v4.0.2/crypto/bls/bls.go:54:14: undefined: blst.AggregateCompressedSignatures
/root/go/pkg/mod/github.com/prysmaticlabs/prysm/v4@v4.0.2/crypto/bls/bls.go:59:14: undefined: blst.VerifySignature
/root/go/pkg/mod/github.com/prysmaticlabs/prysm/v4@v4.0.2/crypto/bls/bls.go:64:14: undefined: blst.VerifyMultipleSignatures
/root/go/pkg/mod/github.com/prysmaticlabs/prysm/v4@v4.0.2/crypto/bls/bls.go:64:14: too many errors
github.com/cometbft/cometbft/votepool
# github.com/cometbft/cometbft/votepool
/root/go/pkg/mod/github.com/bnb-chain/greenfield-tendermint@v0.0.0-20230417032003-4cda1f296fb2/votepool/verifier.go:89:25: undefined: blst.PublicKeyFromBytes
/root/go/pkg/mod/github.com/bnb-chain/greenfield-tendermint@v0.0.0-20230417032003-4cda1f296fb2/votepool/verifier.go:93:25: undefined: blst.SignatureFromBytes
util.go:46: exit status 1
exit status 1
*** Error code 1

Stop.
make: stopped in /usr/home/admin/setup/bsc/1.2.3

**Comment by alexlucaci** [comment]
@YudaAdiPratama 
Hi,

Everything looks good on Apple M2 Silicon
Geth version: `1.2.4`
Go version: `go1.20.4 darwin/arm64`

**Comment by 0xwhatly** [comment]
I alse have the same error

**Comment by mcoelho80** [comment]
> I alse have the same error

Same error with FreeBSD 13.2, go version go1.20.3 and geth 1.2.4.

**Comment by mcoelho80** [comment]
Same problem with 1.2.8. It seems developers don't care about FreeBSD compatibility.

**Comment by bnb-alexlucaci** [comment]
FreeBSD is not supported for now.
