### ISSUE TITLE
What's the difficulty to maintain `geth version` info aligned with release version number? 

### ISSUE THREAD

**Issue by 48ClubIan** [bnb-chain/bsc#1613]
```
$ sha256sum geth_linux.1.2.3
2716e21602d2ec11d0813a2fdcd29f2a5d676925e5d20d378d387551fa6c6746  geth_linux.1.2.3

$ ./geth_linux.1.2.3 version
Geth
Version: 1.2.2
Git Commit: 33e6f840d25edb95385d23d284846955327b0fcd
Git Commit Date: 20230512
Architecture: amd64
Go Version: go1.19.9
Operating System: linux
GOPATH=
GOROOT=/opt/hostedtoolcache/go/1.19.9/x64
```

What is so difficult ??????????????????

**Comment by brilliant-lx** [comment]
sorry and you are right, the current [v1.2.3](https://github.com/bnb-chain/bsc/releases/tag/v1.2.3) should be named v1.2.2
it is a manual mis-operation, will double check before trigger the release.
If it costs inconvenience to you, we can schedule a version fix up release: v1.2.4, if it is ok for you.
