### ISSUE TITLE
Re-queue blocks loop

### ISSUE THREAD

**Issue by masayil** [bnb-chain/bsc#1631]
![image](https://github.com/bnb-chain/bsc/assets/65291464/2c121f81-abe5-44ea-86b3-4f5efc339f57)
network: mainnet
version: v1.1.23
command:`/usr/local/bin/geth_linux  --cache 24000  --datadir /home/ankr/bsc-main/node --config /home/ankr/bsc-main/config.toml --tries-verify-mode none   --txlookuplimit 0 --rpc.txfeecap 0 --rpc.evmtimeout 10s  --txpool.reannouncetime 5m`
Nodes with fastnode enabled sometimes get stuck in a loop of Re-queue blocks.

**Comment by deepcrazy** [comment]
Hi there, Are you using BNB official snapshot (https://github.com/bnb-chain/bsc-snapshots#endpoint) or 48Club's fast node snapshot (https://github.com/48Club/bsc-snapshots#fast-node)? 

Also, If you're trying to run fast node, please add these flags too: `--syncmode=full --pruneancient=true` as suggested over here: https://github.com/48Club/bsc-snapshots#flags
P.S: `--diffblock=5000` is not required as shown in the above mentioned flags link.
