### ISSUE TITLE
How can free up space ?

### ISSUE THREAD

**Issue by hoangthanhtung1910** [bnb-chain/bsc#1632]
My hard drive has a capacity of 2 TB. After running the command it only dropped to 1.8TB:
./geth snapshot prune-block --datadir /root/node --datadir.ancient /root/node/geth/chaindata/ancient --block-amount-reserved 1000000
Is there any solution to free up more hard drive space?

**Comment by ZiyuanStar** [comment]
If you want to keep a really light storage, I'd suggest you use fast node. You can find the steps here:
https://docs.bnbchain.org/docs/BSC-fast-node

**Comment by hoangthanhtung1910** [comment]
> If you want to keep a really light storage, I'd suggest you use fast node. You can find the steps here: https://docs.bnbchain.org/docs/BSC-fast-node
Thanks you but i need full node. The first time i run prune block, the drive drops to 800gb, the second time, the decrease was not significant. What is problem here ?
