### ISSUE TITLE
How can running bsc-node with `docker`?

### ISSUE THREAD

**Issue by kasrakhamesi** [bnb-chain/bsc#1639]
I used https://docs.bnbchain.org/docs/validator/docker/ document for running bsc with docker

download bsc chaindata and ...
this is my docker command : 

sudo docker run --rm -v /root/chaindata/smartchain/config:/bsc/config -v /root/chaindata/smartchain/node:/bsc/node -p 8545:8545 --rm --name bsc -it ghcr.io/bnb-chain/bsc --datadir /bsc/node --config /bsc/config/config.toml --http.addr 0.0.0.0 --http.port 8545 --http.vhosts '*'

But I get this error always : `Fatal: Failed to create the protocol stack: open /bsc/node/geth/LOCK: permission denied`
1.all the directory in volume has exist.
2.I always login with root user and the root user has permissions

without docker,I can running bsc node successfully and problem only happened when using docker

can you help me for fix my problem ?

**Comment by ZiyuanStar** [comment]
docker should not be run under root account. you can refer to here to find how to run bsc node in docker:
https://docs.bnbchain.org/docs/validator/docker/

**Comment by kasrakhamesi** [comment]
> docker should not be run under root account. you can refer to here to find how to run bsc node in docker: https://docs.bnbchain.org/docs/validator/docker/

tried that but still have problem :(

**Comment by kasrakhamesi** [comment]
> > docker should not be run under root account. you can refer to here to find how to run bsc node in docker: https://docs.bnbchain.org/docs/validator/docker/
> 
> tried that but still have problem :(

I fixed that with create personal dockerFile for that,but have newProblem

I get this error `BadBlock` : Error: invalid merkle root (remote: 2cd28b231c7130aafb72febb7712f2b87377f497239e55de313e783a3983f08f local: 0a6225b4880bc58fbc701fb55f96726a34e0b4d55c1899b79945294978088b87)
##############################


when using https://github.com/bnb-chain/bsc-snapshots chaindata and geth version 1.2.3 or 1.2.4
