### ISSUE TITLE
Database compacting cause not syncing height

### ISSUE THREAD

**Issue by xiaorenshan** [bnb-chain/bsc#1665]
#### System information

Geth version: `1.2.4`
OS & Version: Linux
Commit hash : (if `develop`)

#### Actual behaviour
All of my archive node(--gcmode archive) occurs the database compacting cause the node height not increase and http no response after upgrade to 1.2.4

#### Log:
t=2023-06-01T02:52:25+0000 lvl=warn msg="Database compacting, degraded performance" database=/data/geth/chaindata
t=2023-06-01T02:53:25+0000 lvl=warn msg="Database compacting, degraded performance" database=/data/geth/chaindata
t=2023-06-01T02:54:28+0000 lvl=warn msg="Database compacting, degraded performance" database=/data/geth/chaindata

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by weiihann** [comment]
Can you share more of the following details?

- startup command
- hardware specs
- additional logs at the time when the node stopped syncing

thanks

**Comment by oggy95** [comment]
Maybe will helps my solution
Start prune state:
`nohup ./geth_linux snapshot prune-state --datadir . &`
And after completing task (even with error), start node normally

**Comment by weiihann** [comment]
> Maybe will helps my solution Start prune state: `nohup ./geth_linux snapshot prune-state --datadir . &` And after completing task (even with error), start node normally

this helps with the non-archive nodes, but since @xiaorenshan is running an archive node then it's not supposed to be pruned.

**Comment by weiihann** [comment]
@xiaorenshan you may refer to #229 and [geth-issue-22056](https://github.com/ethereum/go-ethereum/issues/22056) for the same issue.

could you also try showing the chaindata `LOG` file? here's a code snippet:
```
cat geth/chaindata/LOG | grep com
```
