### ISSUE TITLE
bridge from BSC mainnet to testnet or maybe listing the testnet on exchange or maybe where to buy or free minting scheme

### ISSUE THREAD

**Issue by haidarabdillah** [bnb-chain/bsc#1673]
# Rationale

too hard to get the coin from faucet, only get 0.1bnb per 1 discord account, but sometimes we need deploy and testing on testnet with 100-1000 transaction.
some people drain the faucet and sell his coin

# Implementation

making wrapped BSC testnet on mainnet 
or maybe listing the BSC testnet on exchange 
or bridge from mainnet to testnet

as developer, im confuse why so hard to get "test coin", it's just free token /coin, why not just everyone can "minting" his bsc test without any limitation

**Comment by ZiyuanStar** [comment]
Pls contact us on discord about getting more tBNB tokens: https://discord.gg/bnbchain

**Comment by zzzckck** [comment]
Good idea, mark in FAQ: https://github.com/bnb-chain/bsc/issues/1947

**Comment by vecocoin** [comment]
For really desperate people: I have seen that you can sometimes buy Testnet BNB for a few cents USDT (Polygon) by using the Atomic DEX of the Komodo Wallet (https://atomicdex.io/en/desktop/). But it only works in the desktop wallet and only in Pro and not Simple swap mode. You need a tiny amount of MATIC, USDT and BNBT in your wallet but it works.
