### ISSUE TITLE
Finalized block can go backward

### ISSUE THREAD

**Issue by maoueh** [bnb-chain/bsc#1683]
#### System information

Geth version: `geth version` 1.2.4
OS & Version: Linux
Commit hash : <modified 1.2.4 tag>

#### Actual behaviour

> **Note** I'll be using `LIB` here and there, this means last irreversible block which is == to last finalized block

It appears that the finalized block of the chain can go backwards in some occasion which is unexpected. I instrumented the `blockchain` core engine at https://github.com/bnb-chain/bsc/blob/v1.2.4/core/blockchain.go#L1995 (after `ValidateState` has been called).

Code is:

```
finalizedBlock := bc.getFinalizedHeader(block.Header(), true)

var headFinalizedBlock *types.Header
currentHeader := bc.CurrentHeader()
if currentHeader != nil {
    headFinalizedBlock = bc.getFinalizedHeader(currentHeader, false)
}

fmt.Fprintf(os.Stderr, "BSC_Finality: Ingested block %q LIB is %q\n", (*header)(block.Header()), (*header)(finalizedBlock))
fmt.Fprintf(os.Stderr, "BSC_Finality: Head block %q LIB is %q\n", (*header)(currentHeader), (*header)(headFinalizedBlock))
```

It appears that sometimes, the LIB goes backward for block that seems at first sight linear (see attached collected logs):

```
...
  Head block "#30492314 (0x9a9c57...5bc42b)" LIB is "#30492312 (0xa27647...3563e6)"
  Head block "#30492315 (0x93e01f...5f7031)" LIB is "#30492313 (0x606627...d3aadf)"
  Head block "#30492316 (0x1b2643...ce5e61)" LIB is "#30492313 (0x606627...d3aadf)"
> Head block "#30492317 (0xc36bc9...d32350)" LIB is "#30492312 (0xa27647...3563e6)"
  Head block "#30492318 (0xebcae7...2eaeb2)" LIB is "#30492316 (0x1b2643...ce5e61)"
  Head block "#30492319 (0x509e5b...dba6d2)" LIB is "#30492317 (0xc36bc9...d32350)"
  Head block "#30492320 (0x4f779d...d1c9ee)" LIB is "#30492318 (0xebcae7...2eaeb2)"
  Head block "#30492321 (0x337802...0a3b80)" LIB is "#30492319 (0x509e5b...dba6d2)"
  Head block "#30492322 (0x729ee7...fa98ac)" LIB is "#30492320 (0x4f779d...d1c9ee)"
...
```

As you can see here, for block `#30492317` the reported LIB is `#30492312` but it's parent LIB was reported to be `#30492313`.

This is unexpected to me, I have a hard time understanding why `30492313` was reported as the LIB but a newer block built on top of the previous determines the final block is one lower. What does that implies for `30492313` in that case?

This can be also observed through the RPC (which make sense, the `blockchain` and `RPC` resolves to the same call). With the command:

```
while true; do echo -n "Checking current finalized block ... "; curl -s -H 'Content-Type: application/json' 'http://localhost:8545/' --data '{"params":["finalized",false],"method":"eth_getBlockByNumber","jsonrpc":"2.0","id":"0x1"}' | jq -r '.result.number'; sleep 2; done | tee /tmp/out.log
```

After some time you should see one happening:

```
...
  Checking current finalized block ... 0x1d19f54
  Checking current finalized block ... 0x1d19f55
  Checking current finalized block ... 0x1d19f56
  Checking current finalized block ... 0x1d19f56
  Checking current finalized block ... 0x1d19f57
  Checking current finalized block ... 0x1d19f57
  Checking current finalized block ... 0x1d19f57
> Checking current finalized block ... 0x1d19f56
  Checking current finalized block ... 0x1d19f5a
  Checking current finalized block ... 0x1d19f5b
  Checking current finalized block ... 0x1d19f5b
...
```

#### Expected behaviour

The finalized block should never go backward.

#### Steps to reproduce the behaviour

Sync BSC Testnet with live blocks and perform the RPC call above. Instrumentation shows the same, see above. I can show a particular fork commit, but it's for Firehose instrumented BSC I maintain (see https://github.com/streamingfast/go-ethereum/tree/release/bsc-finality-print-fh2).

**Comment by deepcrazy** [comment]
Hi there, Afaik, This release is mainly for mainnet as per the description in here: https://github.com/bnb-chain/bsc/releases/tag/v1.2.4 (`It is a hard-fork release for BSC mainnet.`)
 
Is this same issue coming up for v1.2.3 as well? I would suggest to use https://github.com/bnb-chain/bsc/releases/tag/v1.2.3 for BSC testnet. Thanks.

**Comment by maoueh** [comment]
> Is this same issue coming up for v1.2.3 as well? I would suggest to use https://github.com/bnb-chain/bsc/releases/tag/v1.2.3 for BSC testnet. Thanks.

It's the same code, 1.2.4 just activate the right block for Mainnet fork, there is essentially no differences with 1.2.3 see the diff https://github.com/bnb-chain/bsc/compare/v1.2.3...v1.2.4

**Comment by deepcrazy** [comment]
Let me check this out with the team internally then and get back to you post any updates. Thanks.

**Comment by maoueh** [comment]
@MatusKysel Thanks, I will review that and report.

While I have you. I have a question. While ingesting a new block, I would like to obtain the finalized block relative to the ingested block. The extraction of that would go at https://github.com/bnb-chain/bsc/blob/v1.2.4/core/blockchain.go#L1995

Now, when I use the `getFinalizedHeader` function with the block to be ingested, I often received that the block is not found. I think it's because the block is not fully ingested everywhere and `p.snapshot` call in:

```
	snap, err := p.snapshot(chain, header.Number.Uint64(), header.Hash(), nil)
	if err != nil {
		log.Error("Unexpected error when getting snapshot",
			"error", err, "blockNumber", header.Number.Uint64(), "blockHash", header.Hash())
		return nil
	}
```

Returns `ErrUnknownAncestor`. Right now I'm relying on taking the finalized block of the `CurrentHeader` (so normally the parent of the ingested block). Do you know I could get the finalized block relative to the current ingested block received in `blockchain.go`?

**Comment by NathanBSC** [comment]
It's safe to getFinalizedHeader based on CurrentHeader.
Because if the newest ingested block has a valid vote attestation, it will be the next CurrentHeader after verification.
But it may contains a fake vote attestation, so we can't getFinalizedHeader based on it without block header verification.

**Comment by NathanBSC** [comment]
> 

It's safe to getFinalizedHeader based on CurrentHeader.
Because if the newest ingested block has a valid vote attestation, it will be the next CurrentHeader after verification.
But it may contains a fake vote attestation, so we can't getFinalizedHeader based on it without block header verification.

**Comment by maoueh** [comment]
@NathanBSC Thanks for the extra precisions. I can also confirm the bug is fixed by the linked code.
