### ISSUE TITLE
节点启动时使用了pruneancient ，还有必要离线执行snapshot的prune-block和prune-state来修剪数据吗？ 

### ISSUE THREAD

**Issue by FerdyCai** [bnb-chain/bsc#1685]
节点启动时使用了pruneancient ，还有必要离线执行snapshot的prune-block和prune-state来修剪数据吗？

**Comment by jiangsheng6** [comment]
同问，使用了pruneancient并重启后，磁盘并没有少多少是怎么回事？

**Comment by ZiyuanStar** [comment]
pruneancient只保留最近九万个块的数据，如果需要light storage可以跑fastnode, 用48club的snapshot就行：
https://github.com/48Club/bsc-snapshots#flags
https://docs.bnbchain.org/docs/BSC-fast-node

**Comment by jiangsheng6** [comment]
最近九万个块的数据会占用4T的磁盘空间吗，这才是我觉得裁剪后没多大作用的原因

**Comment by brilliant-lx** [comment]
--pruneancient is only for block data, not the state.
You still need to use prune-state to remove the old world state data, which could be much larger than the block data.

**Comment by kemorebiyyj** [comment]
大家有遇到更新geth到1.2.5后，同步速率变得非常慢的情况吗，没更新之前还能追上最新区块。是我的更新geth步骤有问题吗，我只下载最新的geth后就直接启动了命令，datadir和config.toml都是用的之前的，启动命令是这个：./geth --config ./config.toml --datadir /data/BSC/server/data-seed --cache 40960 --maxpeers 9999 --maxpendpeers 100 --syncmode snap --gcmode archive --rpc.allow-unprotected-txs --txlookuplimit 0 --verbosity 5
