### ISSUE TITLE
Archive node not sync height 

### ISSUE THREAD

**Issue by xiaorenshan** [bnb-chain/bsc#1690]
#### System information

Geth version: `1.2.5`
OS & Version: Linux
Commit hash : (if `develop`)

#### Actual behaviour
archive node not sync height, log is:

INFO [06-09|13:56:59.502] Downloader queue stats                   receiptTasks=0 blockTasks=0    itemSize=53.53KiB throttle=4898
INFO [06-09|13:57:07.961] Imported new chain segment               blocks=14  txs=2164 mgas=296.651 elapsed=8.459s    mgasps=35.067  number=28,952,226 hash=90edb1.
.f5ca3a dirty=2.15MiB
INFO [06-09|13:57:10.240] Imported new chain segment               blocks=8   txs=1092 mgas=112.748 elapsed=2.278s    mgasps=49.474  number=28,952,234 hash=9a5b09.
.94477b dirty=3.27MiB
INFO [06-09|13:57:56.882] Deep froze chain segment                 blocks=22  elapsed=33.381ms  number=28,862,234 hash=2a3884..f06eef
INFO [06-09|14:46:01.521] Writing clean trie cache to disk         path=/server/data/geth/triecache threads=1
INFO [06-09|14:46:02.889] Persisted the clean trie cache           path=/server/data/geth/triecache elapsed=1.368s
INFO [06-09|15:46:01.521] Writing clean trie cache to disk         path=/server/data/geth/triecache threads=1
INFO [06-09|15:46:02.827] Persisted the clean trie cache           path=/server/data/geth/triecache elapsed=1.306s
INFO [06-09|16:46:01.521] Writing clean trie cache to disk         path=/server/data/geth/triecache threads=1
INFO [06-09|16:46:02.817] Persisted the clean trie cache           path=/server/data/geth/triecache elapsed=1.296s
INFO [06-09|17:46:01.521] Writing clean trie cache to disk         path=/server/data/geth/triecache threads=1
INFO [06-09|17:46:02.796] Persisted the clean trie cache           path=/server/data/geth/triecache elapsed=1.275s
INFO [06-09|18:46:01.521] Writing clean trie cache to disk         path=/server/data/geth/triecache threads=1

#### Steps to reproduce the behaviour
1. Download the latest snapshot
2. Start a archive node(--gcmode archive)
3. This will happen shortly after syncing to the latest height

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by ZiyuanStar** [comment]
Geth persists data after 1 hour worth of block processing, so the info should be fine. But archive node needs very high hardware requirement and erigon might be a better choice. you can check more details here:
https://github.com/node-real/bsc-erigon
