### ISSUE TITLE
node is killed by OOM

### ISSUE THREAD

**Issue by chengjiao** [bnb-chain/bsc#1699]
Jun 14 15:20:15 ip-xxx kernel: Out of memory: Kill process 23551 (geth-linux-arm6) score 602 or sacrifice child
Jun 14 15:20:15 ip-xxx kernel: Killed process 23551 (geth-linux-arm6) total-vm:24235380kB, anon-rss:20029580kB, file-rss:0kB, shmem-rss:0kB

the hardware configure: aws ec2 m6g.2xlarge, 8 cpu, 32gb memory

**Comment by deepcrazy** [comment]
Hi there, Can you provide some more details please? Like:
- Which node (full or fast) and which snapshot you used (official one for full or 48Club's one for fast node)
- Please share more logs (from bsc.log) during the time this happened.
- Which `geth` version?
- `geth` startup command?

Also, Make sure you've sufficient hardware resources as per this link: https://docs.bnbchain.org/docs/validator/fullnode#suggested-requirements. Currently, Just from high info, it seems like you're having limited hardware specs. Try to upgrade your hardware.
