### ISSUE TITLE
missing trie node for token contract state query

### ISSUE THREAD

**Issue by cliff0412** [bnb-chain/bsc#1705]
i am using the latest geth version v1.2.5
i am getting this error `missing trie node b5817a0479e4329ffc7e165b0c4c94b2918aad2c595c85c42f83ff92c5d71dd9` when making a contract state query with a block number within most recent 128 blocks. and the ws server is not pushing event for my subscription

anything wrong with my config? the issue does not occur with old geth version.
my start command is
```
./geth --ws --config ./config.toml --datadir ./node --cache 16000 --rpc.allow-unprotected-txs --txlookuplimit 0 --diffsync
```

**Comment by weiihann** [comment]
Can you show more logs?
also, `diffsync` is deprecated, you may want to remove that and try again

**Comment by cliff0412** [comment]
what does diffsync means? i turned it off, same error.
also, may i know what does --tries-verify-mode means? is it related to the problem? i feel my node is not caching the 128 block's trie

**Comment by weiihann** [comment]
You can refer to the following links for the explanation:
[diff sync protocol (deprecated)](https://github.com/bnb-chain/BEPs/blob/master/BEP93.md)
[--tries-verify-mode](https://docs.bnbchain.org/docs/BSC-separate-node/)

`--triesInMemory` refers to the in-memory snapshot diff layers. You can refer to [this](https://blog.ethereum.org/2020/07/17/ask-about-geth-snapshot-acceleration) if you want to learn more about how snapshot works.

**Comment by cliff0412** [comment]
thanks for your explanation. i am syncing with snapshot from club48's data ( there is only chain snapshot data after unzip, no trie data). i am syncing with --syncmode as snapshot, --tries-verify-mode full ( i cannot run as local alright as my node is not generating tries). however, it does not relate to the error `missing trie node b5817a0479e4329ffc7e165b0c4c94b2918aad2c595c85c42f83ff92c5d71dd9` as i have previously. does this mean my client is syncing too slow and haven't got the required trie from verify node for state query?

**Comment by weiihann** [comment]
It could be due to syncing problems or other issues such as a corrupted database. What's the output of `eth.syncing`?

Also, have you tried resyncing from scratch?

**Comment by cliff0412** [comment]
the client automatically resolved the issue already. i suspect it could be a corrupted database issue.
