### ISSUE TITLE
Snapshot extension registration failed and Snapshot extension registration failed docker image bsc:1.2.5

### ISSUE THREAD

**Issue by KayAlbertus** [bnb-chain/bsc#1707]
Good Day Team 

I have used the  following latest docker image to run a node

**ghcr.io/bnb-chain/bsc:1.2.5**

I start up my docker container using the following 

**docker run -v $(pwd)/config:/bsc/config -v $(pwd)/data/node:/bsc/node -p 8545:8545 --rm --name bsc-mainnet -it ghcr.io/bnb-chain/bsc:1.2.5 --http.addr 0.0.0.0 --http.port 8545 --http.vhosts '*'** 

however i cannot connect to any peers and sync my node which is running successfully 
 

t=2023-06-15T14:26:35+0000 lvl=info msg="Looking for peers"                      peercount=0 tried=37  static=30
t=2023-06-15T14:26:43+0000 lvl=eror msg="Bsc extension Handshake failed"         peer=4ee5da04 err=EOF
t=2023-06-15T14:26:43+0000 lvl=eror msg="Bsc extension Handshake failed"         peer=1b104cdb err=EOF
t=2023-06-15T14:26:44+0000 lvl=eror msg="Bsc extension Handshake failed"         peer=c7ae85f4 err=EOF
t=2023-06-15T14:26:45+0000 lvl=info msg="Looking for peers"                      peercount=0 tried=126 static=30
t=2023-06-15T14:26:48+0000 lvl=warn msg="Snapshot extension registration failed" peer=2b236036 err="peer connected on snap without compatible eth support"
t=2023-06-15T14:26:55+0000 lvl=info msg="Looking for peers"                      peercount=1 tried=64  static=30
t=2023-06-15T14:27:05+0000 lvl=info msg="Looking for peers"                      peercount=1 tried=55  static=30
t=2023-06-15T14:27:15+0000 lvl=info msg="Looking for peers"                      peercount=2 tried=69  static=30
t=2023-06-15T14:27:17+0000 lvl=eror msg="Bsc extension Handshake failed"         peer=49a51305 err=EOF
t=2023-06-15T14:27:18+0000 lvl=eror msg="Bsc extension Handshake failed"         peer=0c22b0cf err=EOF
t=2023-06-15T14:41:17+0000 lvl=eror msg="Bsc extension barrier failed"           id=4ee5da046a2380b9ff3593e4418aed90b30dda001529ef66f0e48519c30f7ea0 conn=staticdial err="peer wait timeout"

I have also tried 
**geth --datadir node init genesis.json**

and 

**geth --snapshot=false**

any assistance would be sincerely appreciated thank you team

**Comment by cliff0412** [comment]
same issue here.

mine also has 

```
t=2023-06-16T09:13:41+0000 lvl=warn msg="Synchronisation failed, dropping peer"  peer=762e0b1319b980884a41f0ab6bcca0d2d3195e711285cd06ccc74d03b276d971 err="retrieved hash chain is invalid: can't add block 1 hash: the append operation is out-order: have 1 want 28930050"
t=2023-06-16T09:13:41+0000 lvl=warn msg="Synchronisation failed, retrying"       peer=762e0b1319b980884a41f0ab6bcca0d2d3195e711285cd06ccc74d03b276d971 err="peer is unknown or unhealthy"
t=2023-06-16T09:13:41+0000 lvl=warn msg="Synchronisation failed, retrying"       peer=762e0b1319b980884a41f0ab6bcca0d2d3195e711285cd06ccc74d03b276d971 err="peer is unknown or unhealthy"

t=2023-06-16T09:13:51+0000 lvl=eror msg="Expired request does not exist"         peer=767485e3018c84b2bc238fd82b98a330a8cb8334eb4e6bbd520043c206cc59e8
t=2023-06-16T09:13:51+0000 lvl=eror msg="Expired request does not exist"         peer=767485e3018c84b2bc238fd82b98a330a8cb8334eb4e6bbd520043c206cc59e8
t=2023-06-16T09:13:51+0000 lvl=eror msg="Expired request does not exist"         peer=767485e3018c84b2bc238fd82b98a330a8cb8334eb4e6bbd520043c206cc59e8
```

**Comment by kemorebiyyj** [comment]
try use overseas network or overseas server.
