### ISSUE TITLE
How can I join the Discord group for support and discussions about the full node?

### ISSUE THREAD

**Issue by 0x1un** [bnb-chain/bsc#1710]
The link in the README only takes me to a basic interface without the option to ask questions or chat.

**Comment by deepcrazy** [comment]
You can first select the specific roles like Developer, Node Operator or all roles and see the respective channels and can post query over there. OR
You can also check steps to join in #start-here channel: [here](https://discord.com/channels/789402563035660308/912296655372562473/1041698643494846544)

**Comment by 0x1un** [comment]
> You can first select the specific roles like Developer, Node Operator or all roles and see the respective channels and can post query over there. OR You can also check steps to join in #start-here channel: [here](https://discord.com/channels/789402563035660308/912296655372562473/1041698643494846544)

I seem to understand how to use it, thank you very much ~
