### ISSUE TITLE
bsc geth is not respecting --txlookuplimit flag

### ISSUE THREAD

**Issue by rmlcu** [bnb-chain/bsc#1719]
#### System information

/srv/bsc/bsc-geth version
Geth
Version: 1.2.5
Git Commit: 53fef9e830fe55037e63ffe8abc1b564b9401784
Git Commit Date: 20230608
Architecture: amd64
Go Version: go1.19.9
Operating System: linux

16 vcpu 64 ram on ssd

#### Expected behaviour

i have next commandline string:
```
/srv/bsc/bsc-geth --config=/srv/bsc/config.toml --datadir=/srv/bsc --nat=extip:x.x.x.x \
        --txlookuplimit=5000000 --syncmode=full --tries-verify-mode=none --diffblock=5000 \
        --cache=18000 --rpc.allow-unprotected-txs
```
#### Actual behaviour

node has only ~80 days deep of tx history, not more, however 5kk blocks should give ~175 days depth of tx history

#### Steps to reproduce the behaviour

block  27235019, tx 0x62541a811c73a08a3f94e04413725a3f84336dd80fa7896108a3a832b363931a
```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x62541a811c73a08a3f94e04413725a3f84336dd80fa7896108a3a832b363931a"],"id":1}' http://localhost:8545

{"jsonrpc":"2.0","id":1,"result":{"blockHash":"0xa987b4591f10a3f5001a40fed9be6bc31e39396b09d33ddad9b00a1482e5cd79","blockNumber":"0x19f92cb","contractAddress":null,"cumulativeGasUsed":"0x5c2a17","effectiveGasPrice":"0x12a05f200","from":"0xf3ea7ca781ac32960e528cc288efff64c279d678","gasUsed":"0x79ed","logs":[{"address":"0x2e8799f0a26d8a9f37a0b4747fa534f039c2d234","topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef","0x000000000000000000000000f3ea7ca781ac32960e528cc288efff64c279d678","0x0000000000000000000000007004ecc7322fce9923ec6fc3ae2a4cfe4ea4d643"],"data":"0x00000000000000000000000000000000000000000000021fff99c44a94ec0001","blockNumber":"0x19f92cb","transactionHash":"0x62541a811c73a08a3f94e04413725a3f84336dd80fa7896108a3a832b363931a","transactionIndex":"0x34","blockHash":"0xa987b4591f10a3f5001a40fed9be6bc31e39396b09d33ddad9b00a1482e5cd79","logIndex":"0x8f","removed":false}],"logsBloom":"0x00000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000020000000100000000010000000000000000000000000000000000000000000000000000000000040000000000000004000000100000000000000000000000000000000000000080000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000004000000000000000000000000","status":"0x1","to":"0x2e8799f0a26d8a9f37a0b4747fa534f039c2d234","transactionHash":"0x62541a811c73a08a3f94e04413725a3f84336dd80fa7896108a3a832b363931a","transactionIndex":"0x34","type":"0x0"}}
```
block  26935019, tx 0xfdbca4ac7e25f544de8e25542a400959d3e5ea42246c299147b7c565fb799ac2
```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xfdbca4ac7e25f544de8e25542a400959d3e5ea42246c299147b7c565fb799ac2"],"id":1}' http://localhost:8545

{"jsonrpc":"2.0","id":1,"result":null}
```
------

how to get configured block depth?

**Comment by rmlcu** [comment]
hi 0xLyon

i used snapshot from 48bnbclub or something, initially i've had only 90000 block depth then i removed flag `--pruneancient`

**Comment by rmlcu** [comment]
oh i see, but anyway how did i get ~80 day's tx depth?

**Comment by rmlcu** [comment]
anyone?:)

**Comment by 0xLyon** [comment]
Hi there, sorry for delay in response as I seemed to have missed you additional comments in the post.

The most likely got tx's depth of 80 days due to the data that was included in the snapshot that you mentioned. The flag mentioned "txlookuplimit" does not define the amount of blocks that the node will store. You can see here for the flags and their respective definitions: 
https://github.com/bnb-chain/bsc/blob/7a19cd27b61b342d24a1584efc7fa00de4a5b4f5/cmd/utils/flags.go#L251C37-L251C37 

If you are still planning to prune your node, you can use the following flag "--block-amount-reserved xxx" to limit the amount of blocks that are kept after pruning:
https://docs.bnbchain.org/docs/validator/node-maintenance#how-to-prune-1
