### ISSUE TITLE
I can't build the project

### ISSUE THREAD

**Issue by Hossein-Teimouri** [bnb-chain/bsc#1731]
#### System information

Geth version: last version in GitHub
OS & Version: ubuntu 20.04
Commit hash : master
go version go1.13.8 linux/amd64

#### Backtrace

````
root@teymuri:~/bsc# make geth
env GO111MODULE=on go run build/ci.go install ./cmd/geth
# golang.org/x/crypto/openpgp/packet
../go/pkg/mod/golang.org/x/crypto@v0.5.0/openpgp/packet/opaque.go:28:21: undefined: io.ReadAll
../go/pkg/mod/golang.org/x/crypto@v0.5.0/openpgp/packet/private_key.go:135:26: undefined: io.ReadAll
../go/pkg/mod/golang.org/x/crypto@v0.5.0/openpgp/packet/userattribute.go:58:12: undefined: io.ReadAll
../go/pkg/mod/golang.org/x/crypto@v0.5.0/openpgp/packet/userid.go:68:12: undefined: io.ReadAll
note: module requires Go 1.17
make: *** [Makefile:15: geth] Error 2
root@teymuri:~/bsc#

````

When submitting logs: please submit them as text and not screenshots.

**Comment by weiihann** [comment]
> note: module requires Go 1.17

As mentioned in the logs, your Go version seems to be not compatible. Please double check and upgrade your Go package and try again.

**Comment by Hossein-Teimouri** [comment]
Thank you, the problem was solved with the Go update
