### ISSUE TITLE
prune problem, took more time than expected 

### ISSUE THREAD

**Issue by jiangsheng6** [bnb-chain/bsc#1744]
I use a shell "./bin/geth snapshot prune-state --datadir /data/block/bsc/data/" to prune  the storage, 24 hours has passed, and the eta is increasing in the log, is this normal?
<img width="1275" alt="image" src="https://github.com/bnb-chain/bsc/assets/32763668/49936308-1de5-49da-9322-f20f073c1aac">

**Comment by jiangsheng6** [comment]
After being stuck here for a day, I gave up on cropping, and the Stored data is not reduced

**Comment by weiihann** [comment]
Certainly that's not normal. May need more details to diagnose the problem. Could you provide details like:
- Which BSC version are you using?
- geth startup command
- Hardware details

**Comment by jiangsheng6** [comment]
hello:
I use geth version 1.2.7;
systemd start up, ExecStart=/data/block/bsc/bin/geth  --config /data/block/bsc/mainnet/config.toml --datadir /data/block/bsc/data/ --syncmode "full" --pruneancient=true  --cache 16000 --rpc.allow-unprotected-txs --txlookuplimit 0

The server Hardware -  aws 'm5.2xlarge' , 6T SSD Disk,  1.3T free disk left now.

**Comment by jiangsheng6** [comment]
And , I pruned 2 times, The first time stucked here, I killed the process
![image](https://github.com/bnb-chain/bsc/assets/32763668/b298b9d3-9111-4546-8185-f1c8cdd1b49c)

The second time stucked here,  I killed the process again.
![image](https://github.com/bnb-chain/bsc/assets/32763668/f776972d-10f2-4315-9f57-216067adf183)

I realized the second time probably shouldn't have killed the process so quickly, I've now started the third time after waiting for node to catch up
<img width="1150" alt="image" src="https://github.com/bnb-chain/bsc/assets/32763668/706de2e3-43e6-4805-beef-d3b9e82aa2bb">

**Comment by weiihann** [comment]
Let me know if you still face the same problem, I'll try it on my machine

**Comment by jiangsheng6** [comment]
The third prune is in progress, but the "eta" is increasing, I'm not sure whether this is normal
![image](https://github.com/bnb-chain/bsc/assets/32763668/238135a0-c916-4a90-b4cf-ed4f91a6f759)

**Comment by weiihann** [comment]
The pruning process should end after 4~6 hours. If the problem still persists, then somewhere went wrong (i.e. broken database). Just to ask a few more questions:
- Is the node stopped?
- Is this the first time pruning?
- Can the node be synced normally?

**Comment by jiangsheng6** [comment]
Yes, the node stopped

**Comment by weiihann** [comment]
It's stuck again at which log message? Pruning state data, Iterating state snapshot, Generating state snapshot, etc?

**Comment by jiangsheng6** [comment]
Stuck in Generating state snapshot, indeed.

**Comment by weiihann** [comment]
Perhaps you can try this:

1. Stop the pruning
2. Run the node and let it sync until it catches up to the latest block
3. Wait for 1 day (to make sure that the snapshot generation is completed and at least 128 blocks exist on top of it)
4. Try pruning again

Anyways, it seems like your situation could be a unique one, we can move to Discord and discuss further.

To join the discussion on Discord:
1. Join using the invitation link [here](https://discord.gg/p3GFmg6D)
2. Go to the `dev-support` channel
