### ISSUE TITLE
Error message displayed after a certain block in BSC private network mining schedule

### ISSUE THREAD

**Issue by WindowsHyun** [bnb-chain/bsc#1745]
I created a new account using geth and changed the wallet address of the new account to the previous wallet address in the genesis. Then, I proceeded with mining. Everything works fine until the height reaches around 200-300, and transactions are processed without any issues. However, after that point, I encounter the following error message, and mining stops, with the block height no longer increasing. I would greatly appreciate it if you could provide a solution to this problem. Please find the error message below.

`t=2023-06-30T17:55:20+0900 lvl=info msg="Successfully sealed new block"          number=399 sealhash=0xfc7af2338f9740cdae4711634d6b4fc8ade5b5173db3f640208456c97e14581e hash=0x2c44b389d9b8292a71e1878b9c087a0cd26f098f3d09280a2912f36060f31106 elapsed=11.895ms

t=2023-06-30T17:55:20+0900 lvl=info msg="🔗 block reached canonical chain"        number=388 hash=0x22b63a074749155a523131d2cf032303650e5dc79cce95ca7fabb7db3ad474b1

t=2023-06-30T17:55:20+0900 lvl=info msg="🔨 mined potential block"                number=399 hash=0x2c44b389d9b8292a71e1878b9c087a0cd26f098f3d09280a2912f36060f31106

t=2023-06-30T17:55:23+0900 lvl=eror msg="apply message failed"                   msg="\b\xc3y\xa0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00+only operator is allowed to call the method\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" err="execution reverted"

t=2023-06-30T17:55:30+0900 lvl=eror msg="apply message failed"                   msg="\b\xc3y\xa0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00+only operator is allowed to call the method\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" err="execution reverted"`

**Comment by deepcrazy** [comment]
Hi there, Can you also share the following details too:
- Which geth version you're using?
- `geth` startup command?
- Any link you followed for setting the private node?
- Can you share the file where you changed the account address?

Can you clarify this line: `changed the wallet address of the new account to the previous wallet address in the genesis` -> Do you mean: You've created the new wallet account and you've changed the address in genesis with this new wallet account address?

**Comment by WindowsHyun** [comment]
> 안녕하세요. 다음 세부 정보도 공유해 주시겠습니까?
> 
> * 사용 중인 geth 버전은 무엇입니까?
> * `geth`시작 명령?
> * 개인 노드를 설정하기 위해 따랐던 링크가 있습니까?
> * 계정 주소를 변경한 파일을 공유할 수 있나요?
> 
> 이 줄을 명확히 할 수 있습니까? `changed the wallet address of the new account to the previous wallet address in the genesis`-> 의미: 새 지갑 계정을 만들었고 이 새 지갑 계정 주소로 제네시스의 주소를 변경했습니까?



> Hi there, Can you also share the following details too:
> 
> * Which geth version you're using?
> * `geth` startup command?
> * Any link you followed for setting the private node?
> * Can you share the file where you changed the account address?
> 
> Can you clarify this line: `changed the wallet address of the new account to the previous wallet address in the genesis` -> Do you mean: You've created the new wallet account and you've changed the address in genesis with this new wallet account address?

For geth, I used the 1.2.8 linux binary.

My GETH command is below
geth --http --config /bnbsmartchain/config.toml --datadir /localnet --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0 --allow-insecure-unlock --unlock "$dev_address" - -password "$dev_address_pwd_file" --mine --miner.etherbase "$dev_address"


For dev_address
  (echo "windowshyun"; echo "windowshyun") | geth account new --datadir /localnet > output.txt
     dev_address=$(cat output.txt | awk '/Public address of the key:/ {print $6}')
     echo $dev_address > "$dev_address_file"
I got the account address in the same way as above.

In the case of the genesis file, I did the following
   # Create genesis.json file
     genesis_file="/bnbsmartchain/genesis.json"
     modified_genesis_file="/bnbsmartchain/modified_genesis.json"

     old_value="f3a43bb136a7ec60c8fd6d99a36e8139d6dce117"
     new_value="${dev_address#*x}"
     sed -i "s/$old_value/$new_value/g" "$genesis_file"

**Comment by deepcrazy** [comment]
Can you also share the link which you followed/used by setting up your BSC private node? 

From the error logs, it seems like you're trying to make a call to a function in your smart contract that is restricted and can only be called by the operator. Are you performing any smart contract operations and then getting these error logs?

**Comment by WindowsHyun** [comment]
> BSC 개인 노드를 설정하여 팔로우/사용한 링크를 공유할 수 있습니까?
> 
> 오류 로그에서 제한적이고 운영자만 호출할 수 있는 스마트 계약의 함수를 호출하려는 것으로 보입니다. 스마트 계약 작업을 수행한 다음 이러한 오류 로그를 받고 있습니까?

I created a private network through docker like this
Below is the address I made with my BSC Private Network docker.
https://github.com/WindowsHyun/bnbPrivateNetwork/tree/main

**Comment by deepcrazy** [comment]
Can you provide info on the other query as well asked earlier please? Are you performing any smart contract operations and then getting these error logs? (As From the error logs, it seems like you're trying to make a call to a function in your smart contract that is restricted and can only be called by the operator.)

Thanks for sharing your BSC private network docker link. I mean to say Which documentation you followed for creating your own BSC Private network? This one: https://github.com/bnb-chain/bsc-docker ?

**Comment by WindowsHyun** [comment]
> Can you provide info on the other query as well asked earlier please? Are you performing any smart contract operations and then getting these error logs? (As From the error logs, it seems like you're trying to make a call to a function in your smart contract that is restricted and can only be called by the operator.)
> 
> Thanks for sharing your BSC private network docker link. I mean to say Which documentation you followed for creating your own BSC Private network? This one: https://github.com/bnb-chain/bsc-docker ?


I made a combination of all of the following to create a private network docker
`https://github.com/bnb-chain/bsc#readme
https://github.com/bnb-chain/bsc-genesis-contract#readme`


In the case of bsc-docker, I couldn't use it because the build didn't work normally.
Every time I try to build I get an error...

This is my transaction related code.
I don't know if the import is correct because I imported it randomly...
There is no transaction and no separate smart contract operation with this code below.
`https://github.com/WindowsHyun/bnbPrivateNetwork/blob/main/example_transaction.go`


Sorry for the late reply.
