### ISSUE TITLE
types.Transaction use Hash() panic

### ISSUE THREAD

**Issue by sn00wman** [bnb-chain/bsc#1753]
My full node panics when receiving a transaction and calling tx.Hash(). I have encountered this issue several times. Here is the error log.

panic: runtime error: index out of range [0] with length 0

goroutine 1005656 [running]:
github.com/ethereum/go-ethereum/rlp.(*encBuffer).listEnd(...)
 github.com/ethereum/go-ethereum/rlp/encbuffer.go:160
github.com/ethereum/go-ethereum/rlp.makeStructWriter.func1({0x23ec580?, 0xc01a0e1620?, 0xc012914690?}, 0xc00dc0f9f0)
 github.com/ethereum/go-ethereum/rlp/encode.go:340 +0x21c
github.com/ethereum/go-ethereum/rlp.makePtrWriter.func1({0x23d9ee0?, 0xc01a0e1620?, 0x23d9ee0?}, 0xc00dc0f9f0)
 github.com/ethereum/go-ethereum/rlp/encode.go:379 +0xbd
github.com/ethereum/go-ethereum/rlp.(*encBuffer).encode(0xc010270408?, {0x23d9ee0?, 0xc01a0e1620?})
 github.com/ethereum/go-ethereum/rlp/encbuffer.go:175 +0x11c
github.com/ethereum/go-ethereum/rlp.Encode({0x7ff924681b60?, 0xc02018cfc0?}, {0x23d9ee0, 0xc01a0e1620})
 github.com/ethereum/go-ethereum/rlp/encode.go:65 +0x114
github.com/ethereum/go-ethereum/core/types.rlpHash({0x23d9ee0, 0xc01a0e1620})
 github.com/ethereum/go-ethereum/core/types/hashing.go:44 +0x12d
github.com/ethereum/go-ethereum/core/types.(*Transaction).Hash(0xc02513ab60)
 github.com/ethereum/go-ethereum/core/types/transaction.go:395 +0x131
github.com/ethereum/go-ethereum/eth/protocols/eth.handleTransactions({0x2dde5c0?, 0xc00295c340}, {0x2dc9a20, 0xc01a0e15c0}, 0xc007e8f9e0)
 github.com/ethereum/go-ethereum/eth/protocols/eth/handlers.go:724 +0x189
github.com/ethereum/go-ethereum/eth/protocols/eth.handleMessage({0x2dde5c0, 0xc00295c340}, 0xc007e8f9e0)
 github.com/ethereum/go-ethereum/eth/protocols/eth/handler.go:214 +0x395
github.com/ethereum/go-ethereum/eth/protocols/eth.Handle({0x2dde5c0, 0xc00295c340}, 0xc007e8f9e0)
 github.com/ethereum/go-ethereum/eth/protocols/eth/handler.go:153 +0x49
github.com/ethereum/go-ethereum/eth/protocols/eth.MakeProtocols.func1.1(0xc0062edd08?)
 github.com/ethereum/go-ethereum/eth/protocols/eth/handler.go:110 +0x27
github.com/ethereum/go-ethereum/eth.(*handler).runEthPeer(0xc00295c340, 0xc007e8f9e0, 0xc012628b28)
 github.com/ethereum/go-ethereum/eth/handler.go:527 +0xed1
github.com/ethereum/go-ethereum/eth.(*ethHandler).RunPeer(0x43?, 0xc01f376580?, 0x2dd78b8?)
 github.com/ethereum/go-ethereum/eth/handler_eth.go:44 +0x19
github.com/ethereum/go-ethereum/eth/protocols/eth.MakeProtocols.func1(0xc007d1cf38?, {0x2dd78b8, 0xc00b571970})
 github.com/ethereum/go-ethereum/eth/protocols/eth/handler.go:109 +0x122
github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1()
 github.com/ethereum/go-ethereum/p2p/peer.go:549 +0x98
created by github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
 github.com/ethereum/go-ethereum/p2p/peer.go:547 +0xb6

**Comment by CocoStarZ** [comment]
Hi there, what's your geth version?
