### ISSUE TITLE
Failed to prune node

### ISSUE THREAD

**Issue by nabilmahat** [bnb-chain/bsc#1771]
Hi, I try to prune the database using this command
`sudo nohup ./geth snapshot prune-state --datadir ./node > logs/20230717-prune.log &`
but then it kinda failed. Not sure why.

Prune output
![image](https://github.com/bnb-chain/bsc/assets/31288559/7046082e-7703-4a4e-b268-4ad2d1fe69e4)

Geth version
![image](https://github.com/bnb-chain/bsc/assets/31288559/76a74314-84fd-4df2-8e65-e22967a6f5f5)

Snapshot state verification
![image](https://github.com/bnb-chain/bsc/assets/31288559/8ee15f0d-75cb-44e8-a48b-becb3717dfb9)

**Comment by weiihann** [comment]
Hi 😄 Could you also provide the following details:
1. Node startup command
2. Is your node syncing properly (i.e. output of `eth.syncing` from geth CLI)?

**Comment by nabilmahat** [comment]
1. `/home/ubuntu/geth --config /home/ubuntu/config.toml --datadir /home/ubuntu/node --syncmode full --tries-verify-mode local --http --http.addr 0.0.0.0 --http.port 8545 --http.vhosts=* --http.api eth,net,web3,admin,debug --ws --ws.origins=* --port 30311 --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0`

2. I cannot run geth cli after this failed prune. But I assure you, my node already in full sync before I run prune command

**Comment by weiihann** [comment]
I'll look into it. In the meantime, try to resync your node and double-confirm that it has synced to the latest block. Let it sync for around 1 day so that the snapshot can be recovered properly. After that, try pruning again.

The worst case is that you'll have to wipe out your DB and resynced your node from scratch. But we'll see what we can do before that.

**Comment by nabilmahat** [comment]
I tried to resync the node, but it seems like failing.

`t=2023-07-18T03:11:32+0000 lvl=warn msg="Sanitizing cache to Go's GC limits" provided=8000 updated=5235
t=2023-07-18T03:11:32+0000 lvl=info msg="Set global gas cap"                 cap=50,000,000
t=2023-07-18T03:11:32+0000 lvl=info msg="Allocated trie memory caches"       clean="785.00 MiB" dirty="1.28 GiB"
t=2023-07-18T03:11:32+0000 lvl=info msg="Allocated cache and file handles"   database=/home/ubuntu/node/geth/chaindata cache="2.04 GiB" handles=262,144
t=2023-07-18T03:11:43+0000 lvl=warn msg="Sanitizing cache to Go's GC limits" provided=8000 updated=5235
t=2023-07-18T03:11:43+0000 lvl=info msg="Set global gas cap"                 cap=50,000,000
t=2023-07-18T03:11:43+0000 lvl=info msg="Allocated trie memory caches"       clean="785.00 MiB" dirty="1.28 GiB"
t=2023-07-18T03:11:43+0000 lvl=info msg="Allocated cache and file handles"   database=/home/ubuntu/node/geth/chaindata cache="2.04 GiB" handles=262,144
t=2023-07-18T03:11:53+0000 lvl=warn msg="Sanitizing cache to Go's GC limits" provided=8000 updated=5235
t=2023-07-18T03:11:53+0000 lvl=info msg="Set global gas cap"                 cap=50,000,000
t=2023-07-18T03:11:53+0000 lvl=info msg="Allocated trie memory caches"       clean="785.00 MiB" dirty="1.28 GiB"
t=2023-07-18T03:11:53+0000 lvl=info msg="Allocated cache and file handles"   database=/home/ubuntu/node/geth/chaindata cache="2.04 GiB" handles=262,144
t=2023-07-18T03:12:03+0000 lvl=warn msg="Sanitizing cache to Go's GC limits" provided=8000 updated=5235
t=2023-07-18T03:12:03+0000 lvl=info msg="Set global gas cap"                 cap=50,000,000
t=2023-07-18T03:12:03+0000 lvl=info msg="Allocated trie memory caches"       clean="785.00 MiB" dirty="1.28 GiB"
t=2023-07-18T03:12:03+0000 lvl=info msg="Allocated cache and file handles"   database=/home/ubuntu/node/geth/chaindata cache="2.04 GiB" handles=262,144
t=2023-07-18T03:12:14+0000 lvl=warn msg="Sanitizing cache to Go's GC limits" provided=8000 updated=5235
t=2023-07-18T03:12:14+0000 lvl=info msg="Set global gas cap"                 cap=50,000,000
t=2023-07-18T03:12:14+0000 lvl=info msg="Allocated trie memory caches"       clean="785.00 MiB" dirty="1.28 GiB"
t=2023-07-18T03:12:14+0000 lvl=info msg="Allocated cache and file handles"   database=/home/ubuntu/node/geth/chaindata cache="2.04 GiB" handles=262,144`

Consider db corrupted? :(

**Comment by weiihann** [comment]
Yeah... it should be able to sync correctly. Do try to resync from scratch then 🙁

I would recommend you sync from a snapshot. You may download the latest snapshot [here](https://github.com/bnb-chain/bsc-snapshots).

If you need more details, you can refer to [this link](https://docs.bnbchain.org/docs/validator/fullnode#sync-mode).
