### ISSUE TITLE
debug_traceCall is not available at testnet official rpc endpoints

### ISSUE THREAD

**Issue by jerry-cui** [bnb-chain/bsc#1774]
testnet official rpc endpoints are listed here: https://docs.bnbchain.org/docs/BSCtestnet
I tried debug_traceCall before and it was ok. Maybe debug commands were closed during recent updates?

**Comment by CocoStarZ** [comment]
Could you try this endpoint https://bsc-testnet.nodereal.io/v1/e9a36765eb8a40b9bd12e680a1fd2bc5 from https://www.bnbchainlist.org/?

**Comment by jerry-cui** [comment]
> Could you try this endpoint https://bsc-testnet.nodereal.io/v1/e9a36765eb8a40b9bd12e680a1fd2bc5 from https://www.bnbchainlist.org/?

it works. thx
