### ISSUE TITLE
Title: Issue with tx.gasprice method on Binance Smart Chain (Testnet)

### ISSUE THREAD

**Issue by amit-supraoracles** [bnb-chain/bsc#1779]
Hello Binance,

I need help with the **tx.gasprice** method in REMIX IDE on Binance Smart Chain. 
The gas price returned seems incorrect or unavailable when deploying and executing a verified contract: [Contract Address](https://testnet.bscscan.com/address/0xa7b0ca420be8933af4c02167bcdea18a5aafb3be#code).

Any insights or solutions would be appreciated.

Thank you,
Amit Kumar
[SupraOracles](https://supraoracles.com/)

**Comment by 0xLyon** [comment]
Hi there, I tested your mentioned contract and seems to be working fine when I raised the gas fee and limit for the "setGasPrice" function. You can it set now, when checking your read function -  https://testnet.bscscan.com/address/0xa7b0ca420be8933af4c02167bcdea18a5aafb3be#readContract#F1

**Comment by amit-supraoracles** [comment]
Thanks a lot! @0xLyon !!
