### ISSUE TITLE
BSC Node not syncing

### ISSUE THREAD

**Issue by sirgarfieldc** [bnb-chain/bsc#1781]
#### System information

Geth version: `geth version` 1.2.9
OS & Version: Windows/Linux/OSX  Linux 
Commit hash : (if `develop`)  34b065aecb80aa7733e1e6fe77b9b080dff1699a

#### Expected behaviour

Followed readme to start a full node.  Ran

```
./build/bin/geth --config ./config.toml --datadir ./node  --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0
```

#### Actual behaviour

Node got stuck and is not syncing

```
root@Ubuntu-2204-jammy-amd64-base ~/disk1/workspace/bsc # ./build/bin/geth --config ./config.toml --datadir ./node  --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0
INFO [07-25|10:38:31.834] Starting Geth on Ethereum mainnet... 
INFO [07-25|10:38:31.835] Maximum peer count                       ETH=30 LES=0 total=30
INFO [07-25|10:38:31.835] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [07-25|10:38:31.835] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable
```

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by 0xLyon** [comment]
Hi there, after starting geth, please see your log output in file /node/bsc.log.
Can you see there if your node is syncing and if not, please provide some log samples.

**Comment by sirgarfieldc** [comment]
I have deleted the [Node.Log] section from config.toml as suggested in here

https://ethereum.stackexchange.com/questions/77541/geth-smartcard-socket-not-found-disabling-warning-message

And the node is able to sync. 

./node/bsc.log contains the same log that I am seeing from console. 

Closing
