### ISSUE TITLE
--ancientdata option that enables splitting data across multiple disks

### ISSUE THREAD

**Issue by sirgarfieldc** [bnb-chain/bsc#1782]
Do we must have 2.5TB SSD space in 1 disk ?  Or is it possible to delegate ancient data onto a directory different from --datadir ( similar to how official geth client works nowadays)  ?

**Comment by 0xLyon** [comment]
I'm not aware of any current options to specify multiple "datadir" and also not advisable as this would affect node's performance and ability to stay in sync.
You can use the prune tools to keep your storage light, as detailed here - https://docs.bnbchain.org/docs/validator/node-maintenance#storage

**Comment by joseddg92** [comment]
Wouldn't you be able to use symlinks to move some folders to different disks?
