### ISSUE TITLE
more peer sending votes too much, votes dropped; it may be a ddos attack, please check!

### ISSUE THREAD

**Issue by afeijackcool** [bnb-chain/bsc#1785]
by v1.2.9 
got more warning 
t=2023-07-29T10:57:23+0800 lvl=warn msg="peer sending votes too much, votes dropped; it may be a ddos attack, please check!" peer=0ffb2028
t=2023-07-29T10:57:23+0800 lvl=warn msg="peer sending votes too much, votes dropped; it may be a ddos attack, please check!" peer=0ffb2028
t=2023-07-29T10:57:23+0800 lvl=warn msg="peer sending votes too much, votes dropped; it may be a ddos attack, please check!" peer=0ffb2028
t=2023-07-29T10:57:23+0800 lvl=warn msg="peer sending votes too much, votes dropped; it may be a ddos attack, please check!" peer=0ffb2028
t=2023-07-29T10:57:23+0800 lvl=warn msg="peer sending votes too much, votes dropped; it may be a ddos attack, please check!" peer=0ffb2028
t=2023-07-29T10:57:23+0800 lvl=warn msg="peer sending votes too much, votes dropped; it may be a ddos attack, please check!" peer=0ffb2028
t=2023-07-29T10:57:23+0800 lvl=warn msg="peer sending votes too much, votes dropped; it may be a ddos attack, please check!" peer=0ffb2028
t=2023-07-29T10:57:23+0800 lvl=warn msg="peer sending votes too much, votes dropped; it may be a ddos attack, please check!" peer=0ffb2028
t=2023-07-29T10:57:23+0800 lvl=warn msg="peer sending votes too much, votes dropped; it may be a ddos attack, please check!" peer=0ffb2028
t=2023-07-29T10:57:23+0800 lvl=warn msg="peer sending votes too much, votes dropped; it may be a ddos attack, please check!" peer=0ffb2028

Is there any fatal impact?

**Comment by sebkaluzny** [comment]
I'm having same logs

**Comment by brilliant-lx** [comment]
It is a know issue, but a DDos attack, already have a PR under review,  https://github.com/bnb-chain/bsc/pull/1780
We will merge it soon and schedule a new release.

You may ignore this message right now.
