### ISSUE TITLE
Poor performance for tracing of older transactions

### ISSUE THREAD

**Issue by sebkaluzny** [bnb-chain/bsc#1786]
I've been observing a noticeable difference in performance when using the debug_traceTransaction and debug_traceBlockByNumber methods on transactions/blocks that occurred some time ago, compared to the ones that occurred more recently.

**Steps to Reproduce:**
Run a debug_traceTransaction for a transaction that occurred about 15 days ago.
Run a debug_traceTransaction for a transaction that occurred about 1 day ago.

**Expected Behavior:**
Reasonably comparable performance for both the older and newer transactions.

**Actual Behavior:**
For a transaction that was ~15 days ago, the call takes approximately 20 seconds.
For a transaction that was ~1 day ago, the request completes in about 800ms.

**Environment:**
Geth version: v1.2.9
OS & Version: Ubuntu 22.04.2 LTS
CPU: AMD Ryzen 9 5950X
Disks: 3x 3.5T NVM in raid0

I understand that older data might require additional time for retrieval, but a 25x difference seems excessive and affects the usability when tracing older transactions.

**Comment by deepcrazy** [comment]
Hi there, Can you share the logs during the time of calls for both the scenarios? Any screenshot of time taken during both the calls.

Also, Can you try upgrading geth to latest version v1.2.10 or above from here: https://github.com/bnb-chain/bsc/releases and see if it works.
