### ISSUE TITLE
Syncing stuck due to lack of peers

### ISSUE THREAD

**Issue by sirgarfieldc** [bnb-chain/bsc#1794]
I am syncing my BSC node. 

Cmd

```
./build/bin/geth --config ./config.toml --datadir ./node  --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0
```

I was able to download all the block from genesis until 5 days from now.

Then, the syncing went into this loop without making further progress:

```
Very low number of peer drops to 0
->
Rewinding blockchain
->
Synchronisation failed
->
Roll back chain segment
->
Looking for peers ( with 0 peer)
->
Find some peer and download a bunch of blocks & receipt 

```
I am not able to sync block with age less than 5 days.

Example Console Printout:
![Screenshot 2023-08-02 at 9 52 15 PM](https://github.com/bnb-chain/bsc/assets/14815380/e9ad4c0a-2325-42ad-bd01-057bfe633268)

Questions:
1. What is wrong ?  Why can't I sync stuff within 5 days ? 
2. How should I crawl a list of high quality (healthy and synced) peers so that I can put it under the static node configuration ( under config.toml [Node.P2P] section) ?

**Comment by deepcrazy** [comment]
Hi there, Which `geth` version are you using? 
I would recommend to use latest geth version: https://github.com/bnb-chain/bsc/releases/tag/v1.2.9.

Secondly, you can `append` the static nodes from here: https://api.binance.org/v1/discovery/peers in your config.toml file.

In addition to this:
- Can you provide the output of `net.peerCount`? If it is less, then try to increase maxpeers value by adding this flag `--maxpeers 200` in your geth startup command and let your node run for a while.
- Can you provide your hardware specs? (Note: It should fulfill: https://docs.bnbchain.org/docs/validator/fullnode#suggested-requirements if running node using snapshot)
- Can you confirm if you're using snapshot and if so, which snapshot you used?

**Comment by sirgarfieldc** [comment]
using  1.2.9

` you can append the static nodes from here: https://api.binance.org/v1/discovery/peers in your config.toml file.`
Tried it. Didn't help

Not using snapshot.

Hardware spec:

16 core
128GB RAM

Disk is 3.5TB Nvme SSD

```
root@Ubuntu-2204-jammy-amd64-base ~/disk1/workspace/bsc # hdparm -tT /dev/nvme1n1

/dev/nvme1n1:
 Timing cached reads:   45976 MB in  2.00 seconds = 23021.61 MB/sec
 Timing buffered disk reads: 10384 MB in  3.00 seconds = 3460.90 MB/sec
```

**Comment by deepcrazy** [comment]
Hmm, Seems like you're having limited hardware resources. If you refer this doc: https://docs.bnbchain.org/docs/validator/fullnode#sync-from-genesis-block-not-recommended, then ideally you need heavy hardware specs and also more than 40K IOPS (my recommendation 60K IOPS)
The hardware specs, which you have, are suitable for running the full node using snapshot. So, I would recommend you running using node using snapshot from here: https://github.com/bnb-chain/bsc-snapshots#endpoint

If the hd specs are limited, then it will be hard to catch up the current block as the speed it will try to sync will not be to match with the blocks being generated.

JFYR: You can also refer this post: https://github.com/ethereum/go-ethereum/issues/16796#issuecomment-391649278

**Comment by sirgarfieldc** [comment]
I am trying to download the snapshot at 
https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-20230719.tar.lz4
with 3.8TB disk.

The process is not straightforward without further instruction.

If I use wget, then if the download errors out, i can use -c flag to continue the downlaod.

The problem is that after I download the zip file, there isn't enough space to host both the zip file and the un-compressed file. So it is not possible to decompress it.

Then I try to pipe the downloaded content to decompress process directly 
```
wget -O  - https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-20230719.tar.lz4 | lz4 -dc | tar xvf - -C ./node
```

but the issue is that once the download errors out it is not possible to continue where it left off --> never being able to download the file since it took too long and will error out at least once

**Comment by 0x090909** [comment]
@sirgarfieldc you can try to download bnb48 snapshots now they provide it with local trie verification which is the same as the one that youre downloading but without ancient data.

here it is:
https://github.com/48Club/bsc-snapshots

<img width="714" alt="Screenshot 2023-08-11 at 09 19 05" src="https://github.com/bnb-chain/bsc/assets/16927059/8e2b5d74-55f9-4e5a-a46b-6033162d213d">

**Comment by CocoStarZ** [comment]
No more follow-up, close it for now
