### ISSUE TITLE
chapel rpc does not work on graph-node indexer with same block deployment

### ISSUE THREAD

**Issue by chrisckwong821** [bnb-chain/bsc#1796]
#### System information
Ubuntu: 22.04

Geth version: NA

OS & Version: Linux - Ubuntu: 22.04

#### Expected behaviour
indexer rpc works with same block deployment

#### Actual behaviour
the code on the contract deployed within the same block is not synced, thus the handler that requires to read the contract fails.

#### Steps to reproduce the behaviour

Reproduce based on [this issue](https://github.com/graphprotocol/graph-node/issues/4251)

**Comment by 0xLyon** [comment]
Hi there, thanks for sharing. We are looking into this and will provide more feedback once available.

**Comment by zzzckck** [comment]
Hi, do you still got the issue?
