### ISSUE TITLE
Tried to prune the node, not working as well

### ISSUE THREAD

**Issue by edgeofthegame2** [bnb-chain/bsc#1813]
Command:
./geth snapshot prune-state --datadir ./node

Terminal:

INFO [08-10|13:02:06.362] Maximum peer count                       ETH=50 LES=0 total=50
INFO [08-10|13:02:06.362] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [08-10|13:02:06.362] Set global gas cap                       cap=50,000,000
WARN [08-10|13:02:06.362] Using deprecated resource file /bsc/node/chaindata, please move this file to the 'geth' subdirectory of datadir.
INFO [08-10|13:02:06.362] Allocated cache and file handles         database=/bsc/node/chaindata cache=408.00MiB handles=524,288
INFO [08-10|13:02:15.289] AncientDB item count                     items=13,337,111
INFO [08-10|13:02:15.289] Opened ancient database                  database=/bsc/node/chaindata/ancient readonly=false frozen=30,630,096
INFO [08-10|13:02:15.375] Snapshot loaded                          diskRoot=7cc140..4d0896 root=64f64a..679091
INFO [08-10|13:02:15.622] Initialized state bloom                  size=2.00GiB
ERROR[08-10|13:02:15.647] Failed to prune state                    err="no snapshot paired state"
no snapshot paired state

**Comment by 0xLyon** [comment]
Hi there, can you please try adding '--triesInMemory=32' when you do prune.

**Comment by edgeofthegame2** [comment]
The same error

**Comment by edgeofthegame2** [comment]
I synced till the end, stopped gracefully and used this command:
./geth snapshot insecure-prune-all --datadir ./node  ./genesis.json
I guess prune started.
Terminal is like this:
INFO [08-10|19:36:55.960] Maximum peer count                       ETH=50 LES=0 total=50
INFO [08-10|19:36:55.960] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [08-10|19:36:55.960] Set global gas cap                       cap=50,000,000
WARN [08-10|19:36:55.964] Using deprecated resource file /bsc/node/chaindata, please move this file to the 'geth' subdirectory of datadir.
INFO [08-10|19:36:55.964] Allocated cache and file handles         database=/bsc/node/chaindata cache=408.00MiB handles=524,288
INFO [08-10|19:37:04.861] AncientDB item count                     items=13,353,736
INFO [08-10|19:37:04.861] Opened ancient database                  database=/bsc/node/chaindata/ancient readonly=false frozen=30,646,721
WARN [08-10|19:37:04.866]

WARNING!

The clean trie cache is not found. Please delete it by yourself after the
pruning. Remember don't start the Geth without deleting the clean trie cache
otherwise the entire database may be damaged!

Check the command description "geth snapshot prune-state --help" for more details.

**Comment by edgeofthegame2** [comment]
Okay it seems to be successful

INFO [08-11|14:02:33.882] Compacting database                      range=0xf0-     elapsed=11h53m11.221s
INFO [08-11|14:27:48.478] Database compaction finished             elapsed=12h18m25.817s
INFO [08-11|14:27:48.488] Persisted trie from memory database      nodes=15             size=2.32KiB    time="98.289µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [08-11|14:27:48.488] State pruning successful                 pruned=2.65TiB elapsed=18h50m43.621s

**Comment by huangyisan** [comment]
> Okay it seems to be successful
> 
> INFO [08-11|14:02:33.882] Compacting database range=0xf0- elapsed=11h53m11.221s INFO [08-11|14:27:48.478] Database compaction finished elapsed=12h18m25.817s INFO [08-11|14:27:48.488] Persisted trie from memory database nodes=15 size=2.32KiB time="98.289µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B INFO [08-11|14:27:48.488] State pruning successful pruned=2.65TiB elapsed=18h50m43.621s


Hi，friend, could you tell me how to make it? Could you show me the final command please?
