### ISSUE TITLE
New type of front running bots?

### ISSUE THREAD

**Issue by Traianik** [bnb-chain/bsc#1820]
Hello guys! I need your help! Please look at this token - https://bscscan.com/token/0x9b638B45B2c60b7D22794386178340631D5c9AA1 , check where liquidity is added (page 201), exactly in the same block entered a lot of people assuming that they are some smart contract bots, how it is possible that they bought in the same block as liquidity in that much quantities? As I see all of them interacted with some encrypted smart contract and used strange methods like 0x11111111,Aquila DAS,SCATTER and etc.

**Comment by Pengelolatoko** [comment]
there's nothing weird from the bots, they just buying the token

**Comment by Pengelolatoko** [comment]
there's nothing weird, they just do buy in a loop in 1 tx

**Comment by Traianik** [comment]
> there's nothing weird, they just do buy in a loop in 1 tx

In that case, there should be a lot of tx with errors since they don't know in which exact block liquidity will be added or am I wrong?

**Comment by Pengelolatoko** [comment]
> > there's nothing weird, they just do buy in a loop in 1 tx
> 
> In that case, there should be a lot of tx with errors since they don't know in which exact block liquidity will be added or am I wrong?

how about watching mempool and send it when you find the target tx in mempool ? or there is no mempool anymore in bsc ? sorry if im wrong , been a long time im not in bsc
