### ISSUE TITLE
Chaindata sizes for archive nodes (active vs ancient)

### ISSUE THREAD

**Issue by DefiDebauchery** [bnb-chain/bsc#183]
I apologize for the new Issue, as this is slightly related to several other open threads, but wanted to have a direct answer under the specific parameters.

Could someone provide the current approximate size of `chaindata` under an **archive** node, but separately provide the size of `chaindata/ancient`? I am trying to determine whether a dedicated 2 TB NVMe drive is sufficient for operation if `--datadir.ancient` is set to a separate volume.

Thank you!

**Comment by koen84** [comment]
Maybe it's a config difference, but my archive nodes don't have a separate ancient folder.  Total size is currently 4.0 TiB (meaning a 4TB drive wouldn't cut it by approx 0.5 TiB).

**Comment by DefiDebauchery** [comment]
@koen84 - From the root of your `node` directory, you don't have `geth/chaindata/ancient`?  It's certainly possible I'm misunderstanding how archive nodes work, but would have thought it would still move some stuff out..

**Comment by koen84** [comment]
@DefiDebauchery i went to check back, maybe i missed it before amidst the massive amount of output in the chaindata, but there's indeed an ancient folder : 107 GB on both my archive nodes.

**Comment by DefiDebauchery** [comment]
So out of 4TB, only 107G is staged in the ancient folder? That's disappointing; I was expecting much more. I just bought a 4TB SSD hoping ancient could be offset.. I couldn't even use it for the full node if the space is over 4TB. How the heck are folks even running archive nodes at this point if IOPS is the bottleneck?

Anyway, thank you for looking into that for me.

**Comment by farmer69420** [comment]
It's growing pretty fast, it increased by almost 1TB during last 14 days
![image](https://user-images.githubusercontent.com/74717373/117552903-76ae3c80-b04e-11eb-99a5-678fbb795ca0.png)

**Comment by koen84** [comment]
RAID10 NVMe with 4x 4TB NVMe and it definitely grows like crazy.  I started at 0.9TiB something 2-3 months ago.

I don't know if the ancient blocks can be tweaked ?

**Comment by bnb-tw** [comment]
Given our block size increase and shorter block times, you will require significantly more than 4TB to run an archive node.

See the requirements from https://docs.bnbchain.org/docs/archivenode/#comparison-between-geth-and-erigon

Closing this issue.
