### ISSUE TITLE
1Gwei but  Position In Block 0 !!!

### ISSUE THREAD

**Issue by baijiahei888** [bnb-chain/bsc#1831]
fuck you

Completely tramples on normal collation rules

https://bscscan.com/tx/0x02a96d7e7f760a549ef9766fa9b6dd671b6bb79ff0249e14553a433d59d5f2ab

**Comment by baijiahei888** [comment]
bloxRoute joins nodes to do evil, and bloxRoute has already controlled bsc?

**Comment by keke520wowo** [comment]
so bad

**Comment by baijiahei888** [comment]
user 3gwei  at pos 0
https://bscscan.com/tx/0xbca93df9d6d219b5c5fe66e0ac50c99101b8ee1b7228491432e190a82e74945d

robot 466gwei at pos1
https://bscscan.com/tx/0xb1e8a336722687315e7a07351ab35f4dcd513b83e2ed8d15c7eef36726271b88


Validator: InfStones

**Comment by mas1337** [comment]
Is now BSC a centralized blockchain ? 🙄

**Comment by wuyouwangyue** [comment]
It's too disappointing

**Comment by baijiahei888** [comment]
@CocoStarZ  why?

**Comment by leeeddin** [comment]
any progress?
