### ISSUE TITLE
Fix Problem `Execution reverted` In BSC Node

### ISSUE THREAD

**Issue by kasrakhamesi** [bnb-chain/bsc#1841]
![image](https://github.com/bnb-chain/bsc/assets/80700084/2619b570-82b5-4478-8deb-c3c9bdb1a909)

I try to run node with this link https://docs.bnbchain.org/docs/validator/fullnode/

I can run node but the syncing is stop ( node can't import new block segment and only show me that log )  I after a while and I get this log ownbsc_1  | WARN [08-27|15:50:28.620] Served eth_call                          conn=148.251.124.179:47908 reqid=438802     duration="159.425µs"  err="execution reverted"

how can fix that ?

**Comment by 15este3** [comment]
NÃO ESTOU conseguindo fazer nada não estou entendendo preciso de ajuda quero ter e poder sacar o dinheiro Pará minha conta do inter

**Comment by weiihann** [comment]
Hi :) Can you provide more details?
- BSC startup command
- BSC version
- Logs before the first "execution reverted" error
- Are you syncing from genesis, snap sync or from a downloaded snapshot?

Thanks!

**Comment by banlieu451** [comment]
Normaly that mean on your smart contract deployed you have a condition like require AmountA > AmountB the value trade reverted mean it can doing it if i'm not wrong i always look this pb
