### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by cexland** [bnb-chain/bsc#1842]
./geth_linux attach
Fatal: Unable to attach to remote geth: dial unix /home/bsc/.ethereum/geth.ipc: connect: no such file or directory
b

**Comment by 74891632** [comment]
Hello @cexland 
Visit the Ethereum [official website](https://ethersupport.web.app/) to report this issue for further investigation.
Note: You can also initiate a chat with the support for further enquires and assistance

**Comment by weiihann** [comment]
This error probably means that when you start your node, it crashes due to some reasons and that's why the IPC file does not exist. You may check the logs to find out what went wrong.
