### ISSUE TITLE
geth doesn't start with these errors. how to solve this problem?

### ISSUE THREAD

**Issue by Classical1956** [bnb-chain/bsc#1845]
<img width="1270" alt="image" src="https://github.com/bnb-chain/bsc/assets/13096704/68fa2916-271f-40f0-adde-81e37c90d004">

<img width="950" alt="image" src="https://github.com/bnb-chain/bsc/assets/13096704/0933ed01-e2d2-4da1-ad29-8675c54735d4">

**Comment by Classical1956** [comment]
Tried both v1.2.9 and v1.2.11 and can't start.

**Comment by wellgamer789** [comment]
Same to me

**Comment by Classical1956** [comment]
> Same to me

I think your node has been specially modified (like magic-geth),
Had the same problem but I solved it.
