### ISSUE TITLE
Unable to build docker image

### ISSUE THREAD

**Issue by iw4p** [bnb-chain/bsc#1851]
#### System information

OS & Version: OSX - macOS 13 - M2

#### Expected behaviour

Successful build when I follow the [https://github.com/bnb-chain/bsc-docker](https://github.com/bnb-chain/bsc-docker) 

#### Actual behaviour

595.9 github.com/ethereum/go-ethereum/cmd/geth
608.1 # github.com/ethereum/go-ethereum/cmd/geth
608.1 /usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
608.1 /usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lstdc++: No such file or directory
608.1 collect2: error: ld returned 1 exit status
608.1
609.0 util.go:46: exit status 1
609.0 exit status 1
609.1 make: *** [Makefile:15: geth] Error 1
failed to solve: process "/bin/sh -c cd / && git clone ${GIT_SOURCE}     && cd ./bsc && git checkout ${GIT_CHECKOUT_REF} && make geth" did not complete successfully: exit code: 2
make: *** [build-bsc] Error 17

#### Steps to reproduce the behaviour

Clone the repo [https://github.com/bnb-chain/bsc-docker](https://github.com/bnb-chain/bsc-docker) 
make build-simple

#### What I tried?

I tried to test it with different image versions of Golang like
`FROM golang:1.19-alpine`
but I could not build it successfully.
I also tried `make reset` and `make build-cluster` the solution did not work.

**Comment by 0xLyon** [comment]
Hi there, I will look into this and update you once I have more details. Thanks

**Comment by iw4p** [comment]
```
FROM golang:1.18-alpine

ARG GIT_SOURCE
ARG GIT_CHECKOUT_REF

RUN apk update && apk add make gcc libc-dev binutils-gold musl-dev git

WORKDIR /
RUN git clone ${GIT_SOURCE}
WORKDIR /bsc/
RUN git checkout ${GIT_CHECKOUT_REF}
RUN make geth

RUN mv /bsc/build/bin/geth /usr/local/bin/

EXPOSE 30311 30311/udp
```

I tried different image and also seperate RUN line to debug better and faster.
While `make geth` is running, after a while I got this error:

```
#0 353.9 go.opencensus.io/stats
#0 354.5 go.opencensus.io/stats/view
#0 355.4 go.opencensus.io/plugin/ocgrpc
#0 356.8 util.go:46: exit status 2
#0 356.8 exit status 1
#0 356.9 make: *** [Makefile:15: geth] Error 1
------
failed to solve: process "/bin/sh -c make geth" did not complete successfully: exit code: 2
make[1]: *** [build-bsc] Error 17
make: *** [build-simple] Error 2
```

**Comment by iw4p** [comment]
I tested non-Alpine image to install packages using apt.

This is the Dockerfile:

```
FROM golang:1.18
# FROM golang:1.16-alpine

ARG GIT_SOURCE
ARG GIT_CHECKOUT_REF

RUN apt update && apt install make gcc libc-dev binutils-gold musl-dev git build-essential -y

WORKDIR /
RUN git clone ${GIT_SOURCE}
WORKDIR /bsc/
RUN git checkout ${GIT_CHECKOUT_REF}
RUN make geth

RUN mv /bsc/build/bin/geth /usr/local/bin/

EXPOSE 30311 30311/udp
```

And after that, I got this


```
#0 403.0 github.com/prysmaticlabs/prysm/v4/validator/db
#0 403.0 go.opencensus.io/stats
#0 403.5 go.opencensus.io/stats/view
#0 404.4 go.opencensus.io/plugin/ocgrpc
#0 406.1 util.go:46: exit status 2
#0 406.1 exit status 1
#0 406.2 make: *** [Makefile:15: geth] Error 1
------
failed to solve: process "/bin/sh -c make geth" did not complete successfully: exit code: 2
make[1]: *** [build-bsc] Error 17
make: *** [build-simple] Error 2
```

I can not understand what is wrong.

**Comment by wellgamer789** [comment]
> Hi there, I will look into this and update you once I have more details. Thanks

https://github.com/bnb-chain/bsc/issues/1849
Pls, look my problem

**Comment by iw4p** [comment]
> > Hi there, I will look into this and update you once I have more details. Thanks
> 
> #1849 Pls, look my problem

I fixed mine, finding the best and most compatible version of Golang. Here is the [pull request](https://github.com/bnb-chain/bsc-docker/pull/13).
The repo is also [here](https://github.com/iw4p/bsc-docker).

**Comment by zzzckck** [comment]
> > > Hi there, I will look into this and update you once I have more details. Thanks
> > 
> > 
> > #1849 Pls, look my problem
> 
> I fixed mine, finding the best and most compatible version of Golang. Here is the [pull request](https://github.com/bnb-chain/bsc-docker/pull/13). The repo is also [here](https://github.com/iw4p/bsc-docker).

thx, merged the PR, close this one
