### ISSUE TITLE
snapshots do not contain a triecache folder

### ISSUE THREAD

**Issue by bensacc** [bnb-chain/bsc#1864]
I've tried downloading several snapshots, most recently:

wget -q -O - https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-20230828.tar.lz4 | tar -I lz4 -xvf -

and after completing there is no triecache folder,   only server/data-seed/geth/chaindata and server/data-seed/geth/lightchaindata.
According to the https://github.com/bnb-chain/bsc-snapshots instructions I should have both.  Is the snapshopt bad, the instructions incorrect, or...???  any assistance would be greatly appreciated, thanks!

**Comment by weiihann** [comment]
If you can use the snapshot downloaded to sync your node, then it shouldn't be a problem. Will need to double-check on the correctness of the instruction.

**Comment by bensacc** [comment]
hello @weiihann , thank you so much for your response!  So, I migrated the chaindata to the data path, as per the instructions, just left the /data../triecache dir empty, and started the service.  It seems to be running successfully if I check the status, but nothing is actually happening in the logs.  it's basically just showb these four entries for almost an hour now:

<img width="1249" alt="image" src="https://github.com/bnb-chain/bsc/assets/10394068/0eef6827-93b0-4a12-a19e-c44ec5660488">

**Comment by bensacc** [comment]
ok, maybe disregard I can see activity in bsc.log, thanks again!
