### ISSUE TITLE
what should I see after downlaoding and unpacking a snapshot?

### ISSUE THREAD

**Issue by bensacc** [bnb-chain/bsc#1866]
I'm confused as to what I should have and do after downloading the most recent snapshot.  the directions here: https://github.com/bnb-chain/bsc-snapshots

imply that I should have two directories:
server/data-seed/geth/chaindata
server/data-seed/geth/triecache

and these should be copied to the corresponding datadir paths:

> 
> Step 3: Replace Data
> 
> First, stop the running bsc client if you have one by kill {pid}, and make sure the client has shut down.
> Consider backing up the original data: mv ${BSC_DataDir}/geth/chaindata ${BSC_DataDir}/geth/chaindata_backup; mv ${BSC_DataDir}/geth/triecache ${BSC_DataDir}/geth/triecache_backup
> Replace the data: mv server/data-seed/geth/chaindata ${BSC_DataDir}/geth/chaindata; mv server/data-seed/geth/triecache ${BSC_DataDir}/geth/triecache
> Start the bsc client again and check the logs

however I do not see a triecache directory, only /chaindata and /lightchaindata.  adding to the confusion, the directions from the bnb chain docs: https://docs.bnbchain.org/docs/validator/fullnode instruct to copy the chaindata to BOTH chaindata and triecache:

> Your --datadir flag should point to the folder where the extracted snapshot data is. In our case, we created a new folder named node, and we moved the extracted snapshot data to this folder.
> 
> mv server/data-seed/geth/chaindata node/geth/chaindata
> mv server/data-seed/geth/chaindata node/geth/triecache
>  

which instinctively does not seem right.    could someone please advise what, exactly, I should see after downloading/unpacking the most recent snapshot, and what I should do with resulting directory (or directories)??  Thanks so much for any assistance!

**Comment by bensacc** [comment]
anyone?  halp?

**Comment by weiihann** [comment]
> answer seems to be: copy chaindata to chaindata path, ignore the triecache instructions

Yes, you may ignore triecache. Your node should sync properly even without it.
