### ISSUE TITLE
JS tracer does not have actual gas refund value, it is always zero. 

### ISSUE THREAD

**Issue by Shifu-Liu** [bnb-chain/bsc#1869]
#### System information

Version: 1.2.11
Git Commit: 7a19cd27b61b342d24a1584efc7fa00de4a5b4f5
Architecture: amd64
Go Version: go1.19.13
Operating System: linux)

#### Expected behaviour
Base on this document: https://geth.ethereum.org/docs/developers/evm-tracing/custom-tracer
In the JS tracer step function, user should be able to use log.getRefund() to obtain the gas refund value.

#### Actual behaviour
log.refund is always 0 because the refund struct field is never been set in goja.go:

`

func (t *jsTracer) CaptureState(pc uint64, op vm.OpCode, gas, cost uint64, scope *vm.ScopeContext, rData []byte, depth int, err error) {

	if !t.traceStep {
		return
	}
	if t.err != nil {
		return
	}

	log := t.log
	log.op.op = op
	log.memory.memory = scope.Memory
	log.stack.stack = scope.Stack
	log.contract.contract = scope.Contract
	log.pc = uint(pc)
	log.gas = uint(gas)
	log.cost = uint(cost)
	log.depth = uint(depth)
	log.err = err
	if _, err := t.step(t.obj, t.logValue, t.dbValue); err != nil {
		t.onError("step", err)
	}
}

`
#### Steps to reproduce the behaviour
call a customized js tracer to obtain the refund
suggestion fix, add this into the code:
`
log.refund = uint(t.env.StateDB.GetRefund())
`
#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by deepcrazy** [comment]
Hi there, Can the provide more details what exactly you're trying to achieve.

Also, Can you share whole the code snippet you're trying to run via pastebin and steps to run it? 

Also, Are you running your own node? If so, is it full or fast node?

**Comment by Shifu-Liu** [comment]
Testing command:
`curl http://[rpc_node]:8545/ -H "content-type:application/json" -d '{"id":0, "jsonrpc": "2.0", "method": "debug_traceBlockByNumber", "params": ["0x1e3fb54", {"tracer": "{gasRefund: 0,step: function(log, db) { if(log.getDepth() == 1) {this.gasRefund = log.getRefund();} },result: function(ctx, db) {return { gasRefund: this.gasRefund }; },fault: function(log, db) {}}"}]}' `
I was expecting the value of gasRefund not zero for some transactions:
`
{"jsonrpc":"2.0","id":0,"result":[{"result":{"gasRefund":0}},{"result":{"gasRefund":0}},{"result":{"gasRefund":0}},{"result":{"gasRefund":0}},{"result":{"gasRefund":0}},{"result":{"gasRefund":19900}},{"result":{"gasRefund":0}},{"result":{"gasRefund":68100}},{"result":{"gasRefund":4800}},{"result":{"gasRefund":0}},{"result":{"gasRefund":4800}},{"result":{"gasRefund":22700}},{"result":{"gasRefund":8400}},{"result":{"gasRefund":4800}},{"result":{"gasRefund":0}},{"result":{"gasRefund":0}},{"result":{"gasRefund":4800}},{"result":{"gasRefund":5600}},{"result":{"gasRefund":0}},{"result":{"gasRefund":0}},{"result":{"gasRefund":0}},{"result":{"gasRefund":0}},{"result":{"gasRefund":5600}},{"result":{"gasRefund":0}},{"result":{"gasRefund":2800}},{"result":{"gasRefund":5600}},{"result":{"gasRefund":4800}},{"result":{"gasRefund":0}},{"result":{"gasRefund":0}},{"result":{"gasRefund":0}},{"result":{"gasRefund":2800}},{"result":{"gasRefund":0}},{"result":{"gasRefund":0}},{"result":{"gasRefund":25500}},{"result":{"gasRefund":0}},{"result":{"gasRefund":4800}},{"result":{"gasRefund":2800}},{"result":{"gasRefund":2800}},{"result":{"gasRefund":0}},{"result":{"gasRefund":0}},{"result":{"gasRefund":0}},{"result":{"gasRefund":27500}},{"result":{"gasRefund":0}},{"result":{"gasRefund":2800}},{"result":{"gasRefund":0}},{"result":{"gasRefund":0}},{"result":{"gasRefund":0}},{"result":{"gasRefund":0}},{"result":{"gasRefund":0}},{"result":{"gasRefund":2800}},{"result":{"gasRefund":5600}},{"result":{"gasRefund":2800}},{"result":{"gasRefund":0}},{"result":{"gasRefund":0}},{"result":{"gasRefund":0}},{"result":{"gasRefund":0}},{"result":{"gasRefund":0}},{"result":{"gasRefund":2800}},{"result":{"gasRefund":2800}},{"result":{"gasRefund":2800}},{"result":{"gasRefund":0}},{"result":{"gasRefund":0}}]}
`
But with the current geth code, it always returns zero on each transactions.

**Comment by deepcrazy** [comment]
I believe, this ideally can be possible using 3rd party rpc providers. Can you try out using Nodereal's api: https://docs.nodereal.io/reference/debug-traceblockbynumber?

Also, Was it working on older versions? If so, then Can you try to upgrade your geth to v1.2.12 (https://github.com/bnb-chain/bsc/releases/tag/v1.2.12) and see if it helps.

**Comment by Shifu-Liu** [comment]
> I believe, this ideally can be possible using 3rd party rpc providers. Can you try out using Nodereal's api: https://docs.nodereal.io/reference/debug-traceblockbynumber?

Nodereal still use the geth API, if underlying geth go code does not provide that value, I don't I can get from any other 3rd party. 
> Also, Was it working on older versions? If so, then Can you try to upgrade your geth to v1.2.12 (https://github.com/bnb-chain/bsc/releases/tag/v1.2.12) and see if it helps.

The code is missing there. It does not matter what release. If you visit the tree of tag v1.2.12, the code above I mentioned is same. 

So I shared my code and eh reproduce steps, I assume you know what does JS tracer do.  Did you reproduce that on your part?

**Comment by deepcrazy** [comment]
Hi there, This issue has been fixed in big merge's codebase here: https://github.com/bnb-chain/bsc/pull/1840/. Please wait until this big merge's codebase will be released in new version.
