### ISSUE TITLE
Excuse me but again and again it dont work

### ISSUE THREAD

**Issue by banlieu451** [bnb-chain/bsc#1872]
Excuse me but again and again it still dont work 
,when you release à version pléase hard reset à computer Install from start and try to run the node from start it still dont work again with lastest golang version and with old release every time time in 2023 yes WE are in 2023 and still have trouble incredible really

**MAKE DONT WORK**
Make geth 
Make all

Nothing work every time getting error with lastest go version and with old > 1.19 versions it confirm you for sure we cant run make on your blockchain  after doing and this pb is still appear from 5 months ago
 
Git clone bsc...
cd bsc 
HERE make all or make geth dont work 

#### System information

Geth version: `lastest`
OS & Version: /Linux/

**Comment by CocoStarZ** [comment]
could you provide a snapshot of the error. and also what's your geth and golang version?

**Comment by bdrhn9** [comment]
Here is my dockerfile for bsc client. Hope it will help.

```Dockerfile
# Build Geth in a stock Go builder container
FROM golang:1.19-alpine3.17 as builder

RUN apk add --no-cache make gcc musl-dev linux-headers git bash build-base libc-dev libstdc++

RUN cd / && git clone --branch v1.2.12 --single-branch https://github.com/binance-chain/bsc.git && cd ./bsc && make geth

# Pull Geth into a second stage deploy alpine container
FROM alpine:3.17

RUN apk add --no-cache ca-certificates curl jq tini bash bind-tools grep curl sed gcc
COPY --from=builder /bsc/build/bin/geth /usr/local/bin/bsc

ENTRYPOINT ["bsc"]

```

**Comment by banlieu451** [comment]
Thanks for help i'm at point **Caught SIGILL in blst_cgo_init, consult <blst>/bindings/go/README.md**.

**Comment by bdrhn9** [comment]
> Thanks for help i'm at point **Caught SIGILL in blst_cgo_init, consult /bindings/go/README.md**.

I highly recommend you to utilize docker for running node clients to prevent such conflicts. Other than that, I didn't encounter with this error 😞

**Comment by banlieu451** [comment]
Ok it work after download on linux : BSC : curl -LO geth-linux(url) > chmod +x gethlinux > ./geth_linux ...etc...
