### ISSUE TITLE
my block sync stopped after a while with v1.2.12

### ISSUE THREAD

**Issue by hardikd88** [bnb-chain/bsc#1886]
I am running BSC fullnode mainnet V1.2.12 on linux . My sync suddenly stopped and it is giving below logs . how to solve this plz help...
I upgraded recently few days back.  My current blocknumber is 31775399 and its stuck here.

config.toml file :

[Eth]
NetworkId = 56
LightPeers = 100
UltraLightFraction = 75
TrieTimeout = 150000000000

[Eth.Miner]
GasCeil = 140000000
GasPrice = 3000000000
Recommit = 10000000000

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 3000000000
PriceBump = 10
AccountSlots = 200
GlobalSlots = 8000
AccountQueue = 200
GlobalQueue = 4000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 1000

[Node]
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
InsecureUnlockAllowed = false
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 500
NoDiscovery = false
StaticNodes = []
ListenAddr = ":30311"
EnableMsgEvents = false

[Node.LogConfig]
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""

Here below is the log i am getting :- 

t=2023-09-22T09:59:09+0000 lvl=warn msg="Synchronisation failed, retrying"       peer=82b8f04f7357f80822593ccd7f7fa114b30d3319225ce804a299c7ca73f0dfd3 err="peer is unknown or unhealthy"
t=2023-09-22T09:59:09+0000 lvl=warn msg="Synchronisation failed, retrying"       peer=82b8f04f7357f80822593ccd7f7fa114b30d3319225ce804a299c7ca73f0dfd3 err="peer is unknown or unhealthy"
t=2023-09-22T09:59:11+0000 lvl=warn msg="Multiple headers for single request"    peer=119afe08 headers=0
t=2023-09-22T09:59:11+0000 lvl=warn msg="Synchronisation failed, dropping peer"  peer=119afe0873fbfb50ee384a48464f6826b0b6d05b21d775e9f4957864c6b8fb7e err="action from bad peer ignored: multiple headers (0) for single request"
t=2023-09-22T09:59:11+0000 lvl=warn msg="Synchronisation failed, retrying"       peer=119afe0873fbfb50ee384a48464f6826b0b6d05b21d775e9f4957864c6b8fb7e err="shutting down"
t=2023-09-22T09:59:34+0000 lvl=warn msg="Snapshot extension registration failed" peer=ad8a712b err="peer connected on snap without compatible eth support"
t=2023-09-22T09:59:36+0000 lvl=warn msg="Multiple headers for single request"    peer=ad841933 headers=0
t=2023-09-22T09:59:36+0000 lvl=warn msg="Synchronisation failed, dropping peer"  peer=ad8419331e7372027324ffac0cc558d92c173db3ca8ac77d4cc6f4b96e545896 err="action from bad peer ignored: multiple headers (0) for single request"
t=2023-09-22T09:59:36+0000 lvl=warn msg="Synchronisation failed, retrying"       peer=ad8419331e7372027324ffac0cc558d92c173db3ca8ac77d4cc6f4b96e545896 err="peer is unknown or unhealthy"
t=2023-09-22T09:59:36+0000 lvl=warn msg="Synchronisation failed, retrying"       peer=ad8419331e7372027324ffac0cc558d92c173db3ca8ac77d4cc6f4b96e545896 err="peer is unknown or unhealthy"
t=2023-09-22T09:59:40+0000 lvl=warn msg="Multiple headers for single request"    peer=ada4ff3e headers=0
t=2023-09-22T09:59:40+0000 lvl=warn msg="Synchronisation failed, dropping peer"  peer=ada4ff3e9df46eb8bd5dbb14135178670de92a3c6253f382d712b894d131c096 err="action from bad peer ignored: multiple headers (0) for single request"
t=2023-09-22T09:59:40+0000 lvl=warn msg="Synchronisation failed, retrying"       peer=ada4ff3e9df46eb8bd5dbb14135178670de92a3c6253f382d712b894d131c096 err="peer is unknown or unhealthy"
t=2023-09-22T09:59:40+0000 lvl=warn msg="Synchronisation failed, retrying"       peer=ada4ff3e9df46eb8bd5dbb14135178670de92a3c6253f382d712b894d131c096 err="peer is unknown or unhealthy"

t=2023-09-22T09:59:54+0000 lvl=eror msg="Unexpected error when getting snapshot" error="unknown ancestor" blockNumber=31,775,399 blockHash=0x2b5066ce21098aeb2154ffb29031b11c64b00696153a38879bd059fd17e4480e
t=2023-09-22T09:59:54+0000 lvl=eror msg="Unexpected error when getting snapshot" error="unknown ancestor" blockNumber=31,775,399 blockHash=0x2b5066ce21098aeb2154ffb29031b11c64b00696153a38879bd059fd17e4480e
t=2023-09-22T09:59:57+0000 lvl=eror msg="Unexpected error when getting snapshot" error="unknown ancestor" blockNumber=31,775,399 blockHash=0x2b5066ce21098aeb2154ffb29031b11c64b00696153a38879bd059fd17e4480e
t=2023-09-22T10:00:00+0000 lvl=eror msg="Unexpected error when getting snapshot" error="unknown ancestor" blockNumber=31,775,399 blockHash=0x2b5066ce21098aeb2154ffb29031b11c64b00696153a38879bd059fd17e4480e
t=2023-09-22T10:00:00+0000 lvl=eror msg="Unexpected error when getting snapshot" error="unknown ancestor" blockNumber=31,775,399 blockHash=0x2b5066ce21098aeb2154ffb29031b11c64b00696153a38879bd059fd17e4480e

**Comment by brilliant-lx** [comment]
@hardikd88 you can try this StaticNodes, it is a healthy P2P nodes, should be able to connect and sync from it:

```
[Node.P2P]
MaxPeers = 500
NoDiscovery = false
StaticNodes = [
"enode://87df685a762e3e25e8111d0a5957ecbe5756d34096703da5afa934f0e21de5ac9e60efd892aacd90aa4c792c7df0b1ebac0289a24d0cbcecfdee67305eee18a0@18.181.228.146:33311"
]
ListenAddr = ":30311"
EnableMsgEvents = false
```

**Comment by johnnyji-dev** [comment]
My testnet node also stopped, my logs is similar with upper logs.
On syncing block, I suddenly stopped and geth process killed.

**Comment by zzzckck** [comment]
sync issue several months ago, no longer to investigate the case seem the network state changes all the time
