### ISSUE TITLE
Finalizing a block for which no VoteData exists

### ISSUE THREAD

**Issue by yoshidan** [bnb-chain/bsc#1893]
While checking bscscan I see a block where VoteData is not present, 31894083.
If the latest number is 31894084, I am assuming that 31894081 is not Finalized, am I correct?

https://bscscan.com/block/31894084
```
VoteData : 
	SourceNumber  : 31894081
	SourceHash    : 0x94904149695c8adb89cd6f020cb278275a2fd4483cfc10d7d3dab8121f69f306
	TargetNumber  : 31894083
	TargetHash    : 0xcc482c7a97c2c547a7e1483c14e65bb6087ca7257c15ff673f946298c57e7d90
```

https://bscscan.com/block/31894083

```
Hex: 0xd88301020b846765746888676f312e31392e38856c696e7578000000b19df4a239e14e61ceb442e61edd782ed2e011994aca0236541d845851453ed45e1c950b3672dcc21546bd65e746c468b17a3722b7c529d64d9c3a4b41136ab03e48147e01

ExtraVanity  : ؃�geth�go1.19.8�linux������
ExtraSeal : 0x39e14e61ceb442e61edd782ed2e011994aca0236541d845851453ed45e1c950b3672dcc21546bd65e746c468b17a3722b7c529d64d9c3a4b41136ab03e48147e01
```

https://bscscan.com/block/31894082
```
VoteData : 
	SourceNumber  : 31894080
	SourceHash    : 0x793f4896c559772686c55bc1140baa291e62ef268061713080c9d02193ecd549
	TargetNumber  : 31894081
	TargetHash    : 0x94904149695c8adb89cd6f020cb278275a2fd4483cfc10d7d3dab8121f69f306
```

https://bscscan.com/block/31894081

```
VoteData : 
	SourceNumber  : 31894079
	SourceHash    : 0xcba1480655a9172eb8fc0a0ea9cd5a285b9fcea8489bde764a134c52a8cc0ff9
	TargetNumber  : 31894080
	TargetHash    : 0x793f4896c559772686c55bc1140baa291e62ef268061713080c9d02193ecd549
```

**Comment by CocoStarZ** [comment]
Do you mean 31894083 is not finalized? why 31894081?

**Comment by yoshidan** [comment]
We know that 31894083 is not Finalized at 31894084.

https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP126.md#413-finality-rules

```
There are two steps to finalize a block, the first step we call justify, the second step we call finalize.

A block is called justified if
  (1) it is the root, or
  (2) there exists attestation for this block in its direct child’s header, we call this block justified.
A block is called finalized if
  (1) it is the root, or
  (2) it is justified and its direct child is justified.
```

Based on the specifications, I believe it is the following in this case,
* 31894082 is direct child of 31894081
* 31894083 is direct child of 31894082

I thought that 31894082 was not justified because Attestation was not present in 31894083 and therefore 31894081 was not finalized.

I am thinking that 31894081 is Finalized when 31894083 becomes Finalized, i.e. when [31894085](https://bscscan.com/block/31894085) is generated, is that correct?

**Comment by zzphust** [comment]
Yes, you are correct

**Comment by yoshidan** [comment]
Thanks!
