### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by perwpqwe** [bnb-chain/bsc#1904]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Actual behaviour

t=2023-10-01T00:18:46+0800 lvl=eror msg="Impossible reorg, please file an issue" oldnum=32,194,923 oldhash=0x49e2418d72a83fdadad93b02b0c5f3e6943bf4776af99e7a289f937d133514c5 oldblocks=0 newnum=32,194,923 newhash=0x49e2418d72a83fdadad93b02b0c5f3e6943bf4776af99e7a289f937d133514c5 newblocks=0

#### Backtrace

````
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xd49d58]

goroutine 74324815 [running]:
github.com/ethereum/go-ethereum/core/state.(*StateDB).deleteStorage(0xca3cc9b440, {0xa5, 0x12, 0x36, 0xb9, 0x61, 0x87, 0x52, 0xc4, 0x10, ...}, ...)
	github.com/ethereum/go-ethereum/core/state/statedb.go:1363 +0x258
github.com/ethereum/go-ethereum/core/state.(*StateDB).handleDestruction(0xca3cc9b440, 0xcea769bfbf913e33?)
	github.com/ethereum/go-ethereum/core/state/statedb.go:1447 +0x305
github.com/ethereum/go-ethereum/core/state.(*StateDB).Commit.func1.1(0xca3cc9b440, 0x439faa?, 0xcccfcfb2a0, 0xd01b5165a0?, 0x439faa?, {0xcccfcfb290, 0x1, 0x18?})
	github.com/ethereum/go-ethereum/core/state/statedb.go:1530 +0x398
github.com/ethereum/go-ethereum/core/state.(*StateDB).Commit.func1()
	github.com/ethereum/go-ethereum/core/state/statedb.go:1637 +0x65
github.com/ethereum/go-ethereum/core/state.(*StateDB).Commit(0xca3cc9b440, 0x1eb416c, 0xc140ec97a0, {0xcccfcfb290, 0x1, 0x1})
	github.com/ethereum/go-ethereum/core/state/statedb.go:1741 +0x6bd
github.com/ethereum/go-ethereum/core.(*BlockChain).writeBlockWithState(0xc000325180, 0xcf8b827cc0, {0xd2f7bc3400, 0x70, 0x80}, 0xca3cc9b440)
	github.com/ethereum/go-ethereum/core/blockchain.go:1606 +0x4d0
github.com/ethereum/go-ethereum/core.(*BlockChain).writeBlockAndSetHead(0xc000325180, 0xcf8b827cc0, {0xd2f7bc3400?, 0x70?, 0xd2f7bc3400?}, {0xd01b5a8000, 0x10f, 0x200}, 0xcf8b827cc0?, 0x0)
	github.com/ethereum/go-ethereum/core/blockchain.go:1644 +0x5e
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc000325180, {0xcfe20543f0?, 0x1, 0x1}, 0x1)
	github.com/ethereum/go-ethereum/core/blockchain.go:2014 +0x2135
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc000325180, {0xcfe20543f0?, 0x1, 0x1})
	github.com/ethereum/go-ethereum/core/blockchain.go:1744 +0xb0e
github.com/ethereum/go-ethereum/eth.newHandler.func4({0xcfe20543f0?, 0x1, 0x1})
	github.com/ethereum/go-ethereum/eth/handler.go:328 +0x379
github.com/ethereum/go-ethereum/eth/fetcher.(*BlockFetcher).importBlocks.func1()
	github.com/ethereum/go-ethereum/eth/fetcher/block_fetcher.go:927 +0x8db
created by github.com/ethereum/go-ethereum/eth/fetcher.(*BlockFetcher).importBlocks
	github.com/ethereum/go-ethereum/eth/fetcher/block_fetcher.go:896 +0x3d5
````

When submitting logs: please submit them as text and not screenshots.

**Comment by weiihann** [comment]
Hello :) Can you provide more info such as below:
- Exact BSC version
- BSC startup command
- More logs before the "reorg" message

**Comment by perwpqwe** [comment]
Geth
Version: 1.3.0
Git Commit: 6932673003734d5927b3f2e98dec3d4030a68100
Git Commit Date: 20230929
--
geth --cache 256000 --config config.toml

[Eth]
NetworkId = 56
LightServ = 0
SyncMode = "full"
TriesVerifyMode = "none"
PruneAncientData = true
TxLookupLimit = 0

[Eth.TxPool]
PriceLimit = 1000000000

[Node.P2P]
MaxPeers = 10000
MaxPeersPerIP = 1
ListenAddr = ":30311"

[Node.LogConfig]
FileRoot = ""
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info"

--
t=2023-10-01T11:01:18+0800 lvl=info msg="Importing sidechain segment"            start=32,194,762 end=32,195,076
t=2023-10-01T11:01:18+0800 lvl=eror msg="Expired request does not exist"         peer=7dedcd67302c4f5081e3a5cbb974bc9276b00b8ce5feddc32a3d9da9c9c453a9
...
t=2023-10-01T11:01:24+0800 lvl=eror msg="Expired request does not exist"         peer=633937c12a4fdc1ecbaa90714d5fcc345af3a0928a614a467d0fd50bc6483548
t=2023-10-01T11:01:25+0800 lvl=eror msg="Impossible reorg, please file an issue" oldnum=32,194,923 oldhash=0x49e2418d72a83fdadad93b02b0c5f3e6943bf4776af99e7a289f937d133514c5 oldblocks=0 newnum=32,194,923 newhash=0x49e2418d72a83fdadad93b02b0c5f3e6943bf4776af99e7a289f937d133514c5 newblocks=0

**Comment by weiihann** [comment]
Some additional questions for better clarity:
- How did you encounter the error? Was the node syncing normally before it occurred?
- How much is your disk size?

**Comment by perwpqwe** [comment]
This error only occurred right after the upgrade.
Now I have reverted back to version 1.2.11, it is working normally.

**Comment by Tronglx** [comment]
Is there any update on this issue? I got same issue with version 1.3.7

**Comment by weiihann** [comment]
@Tronglx can you show your logs, start-up command and config?
