### ISSUE TITLE
Support for Solidity 0.8.20 and POSH0 Instruction on BNB Smart Chain

### ISSUE THREAD

**Issue by apollx-apx** [bnb-chain/bsc#1926]
# Rationale

**Why should this feature exist?**
The BNB Smart Chain is an EVM-compatible blockchain that has gained significant popularity among developers. However, it lacks support for the newly introduced POSH0 instruction in Solidity 0.8.20. This omission limits developers to using Solidity versions 0.8.19 and below for smart contract development on BNB Smart Chain. 

The problem arises when widely used libraries, such as OpenZeppelin, release new versions with Solidity 0.8.20 as the minimum required version. This means that developers on BNB Smart Chain are unable to leverage the latest features and improvements in these libraries, forcing them to rely on older, potentially less secure, and feature-limited 4.x versions.

This issue impacts the BNB Smart Chain's ability to keep up with the evolving DeFi and smart contract development ecosystem. To maintain its competitive edge and continue attracting developers, it's crucial to support the latest Solidity versions, including 0.8.20.

**What are the use-cases?**
- Developers on BNB Smart Chain need to access the latest features and enhancements introduced in Solidity 0.8.20 and libraries requiring this version.
- Keeping the BNB Smart Chain compatible with the broader Ethereum and DeFi ecosystem is essential to ensure the network's relevance and adoption.

# Implementation

**Do you have ideas regarding the implementation of this feature?**
Implementing support for Solidity 0.8.20 and its new instruction, POSH0, would require collaboration between the BNB Smart Chain development team and the broader community. The process may involve the following steps:
1. Update the BNB Smart Chain's compiler and tooling to be compatible with Solidity 0.8.20.
2. Ensure that the network is capable of handling smart contracts written in Solidity 0.8.20.
3. Provide clear documentation and guidelines for developers wishing to use Solidity 0.8.20 on BNB Smart Chain.
4. Coordination with popular smart contract development libraries, such as OpenZeppelin, to confirm compatibility and encourage the development of BNB-compatible versions.

**Are you willing to implement this feature?**
As a smart contract developer, my expertise primarily lies in creating and deploying smart contracts. While I may not have the direct capability to implement the underlying changes required to support Solidity 0.8.20 and POSH0 on BNB Smart Chain, I am ready to provide support, feedback, and assistance to help make this feature a reality. My role would be more oriented toward testing and adopting the new features once they are implemented.

Let's work together to enhance the BNB Smart Chain's compatibility with the broader Ethereum ecosystem and provide developers with the tools and features they need to create cutting-edge decentralized applications.

Thank you for considering this feature request.

**Comment by weiihann** [comment]
Just to be sure, you meant PUSH0 opcode right (EIP3855).

**Comment by weiihann** [comment]
If you look closely into the codebase, you'll notice that PUSH0-related codes are already actually included :)

The problem now is that we need a hard fork to enable this feature (alongside some other features introduced in the Shanghai hard fork). It'll probably be the next hard fork which is Kepler. AFAIK, there's no confirmed timeline for it yet.

Anyways, thanks for the suggestion! If you have more insights to share, do let us know in [this forum post](https://forum.bnbchain.org/t/bnb-chain-upgrades-mainnet/936). Thank you :)

**Comment by kevinProground** [comment]
Hi, this is a problem because
openzeppelin now has 0.8.20 as default in its wizard.
Do you still not have a timeline for this?

**Comment by haidarabdillah** [comment]
still have same issue, cause openzepelin upgrade their version to force use 8.20
