### ISSUE TITLE
abort to sync state data after restarting in snap sync mode

### ISSUE THREAD

**Issue by buddh0** [bnb-chain/bsc#1930]
#### System information

Geth version: `v1.3.0`
OS & Version: OSX
Commit hash : (b86459a`)

#### Expected behaviour
snap sync with chapel testnet
after restarting , continue to sync state if it's not done

#### Actual behaviour
snap sync with chapel testnet
after restarting , have high probability to abort syncing state even if it's not done

#### Steps to reproduce the behaviour
1. download [ testnet.zip
](https://github.com/bnb-chain/bsc/releases/download/v1.3.0/testnet.zip) && unzip
2. geth --datadir <datadir> init ./genesis.json
3. ./geth --config ./config.toml --datadir ./node  --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0
4. sync state data > 0.5%
5. restart geth with same params in step 3
    then state sync can't forward

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by 0xLyon** [comment]
Hi there, can you please share some log extracts of the issue mentioned once you restart your node. Can you also advise what version you are using?

**Comment by buddh0** [comment]
finally, after blocking 17 minutes, it sync state again
```
t=2023-10-18T17:15:31+0800 lvl=info msg="Block synchronisation started"
t=2023-10-18T17:15:34+0800 lvl=info msg="Syncing: state download in progress"    synced=0.82% state="1.61 GiB" accounts=727,304@43.85MiB slots=6,207,039@1.25GiB codes=41716@326.42MiB eta=-120.553ms
......
t=2023-10-18T17:32:25+0800 lvl=info msg="Syncing: state download in progress"    synced=0.82%  state="1.61 GiB" accounts=727,304@43.85MiB slots=6,207,039@1.25GiB codes=41716@326.42MiB eta=33h55m10.822s
t=2023-10-18T17:32:33+0800 lvl=info msg="Syncing: state download in progress"    synced=0.82%  state="1.61 GiB" accounts=733,108@43.85MiB slots=6,207,039@1.25GiB codes=41716@326.42MiB eta=34h12m36.919s
t=2023-10-18T17:32:33+0800 lvl=eror msg="Expired request does not exist"         peer=ed8f7a1eec31dc52d8ccd3aef0687ad8be5423dc56d6b61720a5aebee1b9fddb
t=2023-10-18T17:32:33+0800 lvl=eror msg="Expired request does not exist"         peer=ed8f7a1eec31dc52d8ccd3aef0687ad8be5423dc56d6b61720a5aebee1b9fddb
t=2023-10-18T17:32:34+0800 lvl=info msg="Syncing: chain download in progress"    synced=22.67% chain="6.93 GiB" headers=7,822,942@2.77GiB bodies=7,778,706@2.58GiB    receipts=7,778,706@1.58GiB    eta=2h57m23.010s
t=2023-10-18T17:32:42+0800 lvl=info msg="Syncing: state download in progress"    synced=0.82%  state="1.61 GiB" accounts=733,108@43.85MiB slots=6,207,586@1.25GiB codes=41716@326.42MiB eta=34h30m10.372s
```
