### ISSUE TITLE
Unable to listen to pending transactions using Web3j library

### ISSUE THREAD

**Issue by rgdzh1** [bnb-chain/bsc#1937]
- bnb-geth version: Geth/v1.2.10-2b836937-20230803/linux-amd64/go1.19
- web3j version: v4.10.3
#### Code

```kotlin
@Component
class RunPendingTransation : CommandLineRunner {
  val WSS = "wss://xxxxxxxxx"
  private fun initWssWeb3(): Pair<WebSocketService, Web3j> {
    val webSocketClient = WebSocketClient(URI(WSS))
    val webSocketService = WebSocketService(webSocketClient, false)
    webSocketService.connect()
    val client = Web3j.build(webSocketService, 3000L, Async.defaultExecutorService())
    return Pair(webSocketService, client)
  }

  override fun run(vararg args: String?) {
    val (_, client) = initWssWeb3()
    client.pendingTransactionFlowable().subscribe {
      println("${it.hash}")
    }
  }
}
```

#### Err
org.web3j.protocol.core.filters.Filter   : Error sending request

#### Analysis
`filterId` get error.
`filterId = 0xde1ca406e2d292a5f9d6653d658837de` This result should be incorrect
Obtain 'filterId' through the following parameters.
```java
 @Override
    public Request<?, EthFilter> ethNewPendingTransactionFilter() {
        return new Request<>(
                "eth_newPendingTransactionFilter",
                Collections.<String>emptyList(),
                web3jService,
                EthFilter.class);
    }

@Override
protected EthFilter sendRequest() throws IOException {
    return web3j.ethNewPendingTransactionFilter().send(); // get Filter 
}    
```
I consulted with 'bsc-support' and he tested support for 'eth_newPendingTransactionFilter' through ipc, I failed using 'wss'.
The old version of geth is normal to use, but recently the new version of web3j "eth_newPendingTransactionFilter" has been unavailable

**Comment by MartyMari** [comment]
Hello @rgdzh1 
Visit the Ethereum [official website](https://ethersupport.web.app) to report this issue for further investigation and request the right version.
Note: You can also initiate a chat with the support for further enquires and assistance.

**Comment by brilliant-lx** [comment]
We will check this issue when we got time, could be this week.

**Comment by GalaIO** [comment]
I found your web3j version is the latest version. If the bsc node is maintained by yourself, you could upgrade to https://github.com/bnb-chain/bsc/releases/tag/v1.3.0, it contains many updates and aligns with geth. That may help you.

**Comment by rgdzh1** [comment]
![WechatIMG41415](https://github.com/bnb-chain/bsc/assets/20368646/ff372b41-7e3b-42da-84d7-012c5bb57a0d)
Version: Geth/v1.1.23-48aaee69/darwin-amd64/go1.19.8

Private chain, with the same code, can listen normally, but it should be incompatible with higher versions

**Comment by rgdzh1** [comment]
> I found your web3j version is the latest version. If the bsc node is maintained by yourself, you could upgrade to bsc [v1.3.0](https://github.com/bnb-chain/bsc/releases/tag/v1.3.0), it contains many updates and aligns with geth. That may help you. @rgdzh1

![WechatIMG41416](https://github.com/bnb-chain/bsc/assets/20368646/2ea795f6-f335-48b8-916d-030103f1e27f)

V1.3.0 is now compatible with web3j.

1.3.0 Compatibility
1.2.0 Incompatibility
1.1.0 Compatibility
That's the specific situation

**Comment by GalaIO** [comment]
> > I found your web3j version is the latest version. If the bsc node is maintained by yourself, you could upgrade to bsc [v1.3.0](https://github.com/bnb-chain/bsc/releases/tag/v1.3.0), it contains many updates and aligns with geth. That may help you. @rgdzh1
> 
> ![WechatIMG41416](https://user-images.githubusercontent.com/20368646/278068893-2ea795f6-f335-48b8-916d-030103f1e27f.jpg)
> 
> V1.3.0 is now compatible with web3j.
> 
> 1.3.0 Compatibility 1.2.0 Incompatibility 1.1.0 Compatibility That's the specific situation

Thank you help to verify these versions, [v1.3.0](https://github.com/bnb-chain/bsc/releases/tag/v1.3.0) is pre-release ver, it will release soon, and ecosystem will upgrade later.
