### ISSUE TITLE
Validator Legend III has weird ordering in block 32910056

### ISSUE THREAD

**Issue by ana-prdekalo** [bnb-chain/bsc#1945]
[Block 32910056](https://bscscan.com/block/32910056) was validated by Legend III. And first couple of TXs are ordered improperly. 
Did the ordering of TXs change?  Are TXs not ordered by gas price anymore?

![CleanShot 2023-10-25 at 20 17 26@2x](https://github.com/bnb-chain/bsc/assets/126925611/648e19c7-5c98-4535-a704-f691072eff84)

[2nd TX in block](https://bscscan.com/tx/0x3674c359d3e8031ef5fc969f3a98fa415456b1849da27a4199de5a39ac6e3708) (indexed 1) and [3rd TX in block](https://bscscan.com/tx/0xd578cc6843aa30b5d8d4a1737c4bf4d83fb0d7ce31a4a5214520b1af78a77a2f) have paid gas price of only 3Gwei and they are 2nd and 3rd TXs. Placed before much "pricier"  TXs.

Then we have [4th TX](https://bscscan.com/tx/0x9b1a70c363bfd7257c1e406d5a77dc2d0a7444727386018d0bcf0c0313c6924b) of 7.smth Gwei, placed before [5th TX](https://bscscan.com/tx/0x4ed695fa23358941f9ca51c9d54e541d105632e354be4425f08b851a4b4cb204) of 46(!!) Gwei. 

Is this behavior allowed on BSC, aren't validators supposed to follow TX ordering rules (ordering by gas price)? Or have rules changed and I didn't know this. 

The aforementioned 2nd and 3rd TX were liquidity sniping (2nd was enabling new tokens for liquidity and 3rd one was bot which was the first buyer - how convenient for them).

And 4th & 5th look like arbitrage TXs where somehow lower paying bot was placed before higher paying one (again either super lucky or something shady is happening).

If the rules for TX ordering are the same as up till now, I think the team running validator Legend III has some explaining to do to the community.

**Comment by brilliant-lx** [comment]
see: https://github.com/bnb-chain/bsc/issues/1947
