### ISSUE TITLE
geth 1.3.0 an error

### ISSUE THREAD

**Issue by ifsayyes** [bnb-chain/bsc#1959]
#### System information

Geth version: `1.3.0`
OS & Version: Ubuntu 22.04.3 LTS
Commit hash : (if `develop`)

#### Expected behaviour

"geth 1.2.10 deployment is running normally. 
After updating to geth 1.3.0 and using the latest fastnode, 
https://snapshots.48.club/geth.fast.33085096.tar.zst
an error occurred during operation with the message: 
Fatal: Failed to register the Ethereum service: EOF."

#### Backtrace

````
[backtrace]
````
Has anyone else encountered the same issue with geth 1.3.0, 
where the error message is: Failed to register the Ethereum service: EOF? Can anyone assist in resolving this? Please contact [ifsayyes@foxmail.com].

When submitting logs: please submit them as text and not screenshots.
nohup: ignoring input
INFO [11-02|09:55:19.118] Starting Geth on Ethereum mainnet... 
INFO [11-02|09:55:19.119] Maximum peer count                       ETH=100 LES=0 total=100
Fatal: Failed to register the Ethereum service: EOF

**Comment by ifsayyes** [comment]
![a3b628cdacb7206b756a13b9a16c2e5](https://github.com/bnb-chain/bsc/assets/135924607/25d7d8a1-db89-4352-8fa3-a616f218c503)
![354f1e128d97a469b85bb0c0e550696](https://github.com/bnb-chain/bsc/assets/135924607/b9c463ca-8424-478e-a879-0b14f4fe03d2)

**Comment by CocoStarZ** [comment]
1.3 is pre-release, pls keep to use 1.2.10 for now
