### ISSUE TITLE
P2P: MaxPeers in config.toml, seems not work as expected

### ISSUE THREAD

**Issue by brilliant-lx** [bnb-chain/bsc#1966]
#### System information

Geth version: `geth v1.2.12`
OS & Version: Linux
Commit hash : bb6bdc055d1a7f1f049c924028ad8aaf04291b3b

#### Expected behaviour
in config.toml:
```
LightPeers = 100
...
MaxPeers = 900, 
```
The node should be able to serve 800 none les peers at maximum.

#### Actual behaviour
but actually the node only can serve 687, after that new p2p connect request will be rejected, with code: too many peers.
And if I increase `MaxPeers` to 2000, the node will be able to serve 1420 peers, after that same error: too many peers

#### Steps to reproduce the behaviour
update the config.tom and let more peers connect to your node.

#### Backtrace
NA

**Comment by weiihann** [comment]
This seems to be a normal behavior. Based on this [P2P code](https://github.com/bnb-chain/bsc/blob/master/p2p/server.go#L872-L885):
```
...
case !c.is(trustedConn) && c.is(inboundConn) && inboundCount >= srv.maxInboundConns():
   return DiscTooManyPeers
...
```
The number of inbound cannot exceed the max inbound connections. Max inbound connections are calculated by subtracting the number of max peers from the max dialed connections (see code [here](https://github.com/bnb-chain/bsc/blob/master/p2p/server.go#L668-L670)). Max dialed connections is calculated by dividing max peers with the dial ratio (see code [here](https://github.com/bnb-chain/bsc/blob/master/p2p/server.go#L676-L689)). Based on the example given, it seems that the dial ratio used is 3 ([default](https://github.com/bnb-chain/bsc/blob/master/p2p/server.go#L57)). The calculation works as follows:

MaxPeers = 900
MaxDialConns = 900 / 3 = 300
MaxInboundConns = 900 - 300 = 600
ObservedP2PConn - MaxInboundConns = 687 - 600 = 87

MaxPeers = 2000
MaxDialConns = 2000 / 3 = 666
MaxInboundConns = 2000 - 666 = 1334
ObservedP2PConn - MaxInboundConns = 1420 - 1334 = 86

In both examples, the difference between the MaxInboundConns and observed P2P conns is ~86, which suggests that these peers are connected via trusted connections.

The conclusion is if you want to stretch out the maximum number of connected peers and have minimal dialed connections, just set `DialRatio` in the config file to a large number.

**Comment by brilliant-lx** [comment]
make sense, thx
