### ISSUE TITLE
Nodes are no longer synchronized

### ISSUE THREAD

**Issue by 123wyl123** [bnb-chain/bsc#1967]
When I use the official snapshot on a 3.3T SSD drive, 20,000 IOPS, 16c64g machine, I use the following command for all three machines

geth --config /data/config.toml --datadir /workdir/execution --cache 4096 --syncmode=full --tries-verify-mode=local --networkid 56 --ulc. fraction 0 --miner.gaslimit 140000000 --miner.gasprice 3000000000 --miner.recommit 10s --txpool.nolocals=true --txpool.journal transaction. rlp --txpool.rejournal 1h0m0s --txpool.pricelimit 30000000000 --txpool.pricebump 10 --txpool.accountslots 200 --txpool.globalslot 8000 -- txpool.accountsqueue 200 --txpool.globalqueue 4000 --gpo.blocks 20 --gpo.percentile 60 --ipcpath geth.ipc --http --http.addr=pods.ip --http. port 8545 --port 30311 --http.api debug,eth,net,txpool,web3,admin --http.vhosts * --ws --ws.addr pods.ip --ws.port 8546 --ws. txpool,web3,admin --bootnodes enode:// 433c8bfdf53a3e2268ccb1b829e47f629793291cbddf0c76ae626da802f90532251fc558e2e0d10d6725e759088439bf1cd4714716b03a259a35d4b2e4acfa7f@ 52.69.102.73:30311,enode:// 571bee8fb902a625942f10a770ccf727ae2ba1bab2a2b64e121594a99c9437317f6166a395670a00b7d93647eacafe598b6bbcef15b40b6d1a10243865a3e80f@ 35.73.84.120:30311,enode:// fac42fb0ba082b7d1eebded216db42161163d42e4f52c9e47716946d64468a62da4ba0b1cac0df5e8bf1e5284861d757339751c33d51dfef318be5168803d0b5@ 18.203.152.54:30311,enode:// 3063d1c9e1b824cfbb7c7b6abafa34faec6bb4e7e06941d218d760acdd7963b274278c5c3e63914bd6d1b58504c59ec5522c56f883baceb8538674b92da48a96@ 34.250.32.100:30311,enode:// ad78c64a4ade83692488aa42e4c94084516e555d3f340d9802c2bf106a3df8868bc46eae083d2de4018f40e8d9a9952c32a0943cd68855a9bc9fd07aac982a6d@ 34.204.214.24:30311,enode:// 5db798deb67df75d073f8e2953dad283148133acb520625ea804c9c4ad09a35f13592a762d8f89056248f3889f6dcc33490c145774ea4ff2966982294909b37a@ 107.20.191.97:30311 --nat extip: pods.ip --maxpeers 200

One of them can be synchronized, mgasps about 20.，but will frequently print Database compacting degraded perfomance database=/work/exec/chaindata, then I expand the disk on this one from 3.3T to 3.8T, this machine began to synchronize normally, mgasps>50.

 The other two machines will just print writng clean trie cache to disk path = /workdir/execution/geth/triecache ，It lasted for a day or so，My node will be completely out of sync, it will keep printing  writing clean trie cache to disk, path = /work/exec/geth/triecache 

,but I can see that I can connect to 66 peers by geth attach geth.ipc,, then I tried to do a disk expansion on one of the machines and he started to be able to sync properly as well 

In the meantime I used another machine using an unofficial snapshot from 48club, ，This machine is 8c32g,2.5T disk, now with 324G remaining,I used the following command geth --datadir /workdir/node --rpc.allow-unprotected-txs --txlookuplimit 0 --syncmode=full --tries- verify-mode=local --cache 8000 --http --http.addr=podsip --http. port 8545 --port 30311 --http.api debug,eth,net,txpool,web3,admin --http. vhosts * --ws --ws.addr pods.ip --ws.port 8546 --ws. txpool,web3,admin --maxpeers 1000 --config config.toml 。At the same time I use another 16c32g machine with 48club snapshots, I use the command that I had problems syncing with before, at first it can sync normally, after a while it will not be able to sync, it only prints writng clean trie cache to disk path = /workdir/execution/geth/triecache, and at this time there is 420G left on the disk,

One of the config files I downloaded from the official source, which means that this machine has trietimeout configured, while the other machines with synchronisation problems do not have trietimeout configured, and use the default value in the client.

The flag I set is basically the same as configtoml. Am I to understand that if I use the default trietimeout in the client it will put a lot of pressure on my disk to cause this situation，

**Comment by 123wyl123** [comment]
Only 8c32g,2.5T is using geth1.2.11,the others are geth1.2.12, meanwhile I can get these stuck machines back in sync by rebooting.  At the same time I have some questions about how big we usually set the cache and peer parameters depending on our bandwidth, cpu, and memory.

**Comment by 123wyl123** [comment]
@brilliant-lx  @MatusKysel

**Comment by 123wyl123** [comment]
Meanwhile before it fails to synchronise again it prints

Synchronisation failed,dropping peer , peer = err="action from bad peer ignored: header request failed: timeout"

Multipe headers for single request

**Comment by weiihann** [comment]
That seems to be a lot of questions, it'll be great if you can organize them in order so that the team can check through it thoroughly. I'd suggest using the following template:
***
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour


#### Actual behaviour


#### Steps to reproduce the behaviour


#### Backtrace

````
[backtrace]
````
***
Please provide the relevant logs as much as possible. Thanks.
