### ISSUE TITLE
snapshot for fastnode not working with official latest BSC geth version (1.2.13)

### ISSUE THREAD

**Issue by ifsayyes** [bnb-chain/bsc#1974]
#### System information

Geth version:  geth 1.2.13
OS & Version:  Linux
Commit hash : (if `develop`)

#### Expected behaviour
BSC geth officialy rolled back to 1.2.13 because of 1.3 instability. (1.3 is considered as now as a pre-release)

Can you do the snapshot with 1.2.13 ? because actual snapshot not work with 1.2.13

i saw the msg from another dev, but the link not work
https://github.com/48Club/bsc-snapshots/tree/b6ce2b4d2393eb01a3650196034502517de89d06

#### Actual behaviour
![image](https://github.com/bnb-chain/bsc/assets/135924607/5a721b62-c6c0-48a7-9659-925fe3818379)

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.
![image](https://github.com/bnb-chain/bsc/assets/135924607/5fc2468b-1b77-4a41-a37d-e35d596d4e35)

**Comment by zzphust** [comment]
v1.13.0 not support to rolled back to v1.2.13.

**Comment by ifsayyes** [comment]
> v1.13.0 not support to rolled back to v1.2.13.

The nodedata from using geth1.3.0 cannot be rolled back to version geth1.2.13 because the snapshot data is not supported. Is it possible to release a version that supports 1.2.13 fastnode or fullnode ? 
Currently, the upgrade to 1.3.0 is unstable.

**Comment by zzphust** [comment]
Thy the snapshot: https://github.com/bnb-chain/bsc-snapshots#endpoint

**Comment by du5** [comment]
He works fine on v1.3.0, please fix it

<img width="1217" alt="image" src="https://github.com/bnb-chain/bsc/assets/54979375/edaf88b8-a9aa-426b-989b-b421021eb13c">

<img width="1274" alt="image" src="https://github.com/bnb-chain/bsc/assets/54979375/d4b1f21e-5f81-4f07-9cb4-7333e55d7273">

**Comment by zzphust** [comment]
v1.3.0 now seem stable.
