### ISSUE TITLE
debug_traceCall diff mode error v1.3.0

### ISSUE THREAD

**Issue by greyireland** [bnb-chain/bsc#1981]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Actual behaviour
t=2023-11-11T08:08:17+0100 lvl=warn msg="Served debug_traceCall"               conn=127.0.0.1:48334 reqid=34435 duration="187.482µs" err="tracing failed: insufficient funds for gas * price + value: address 0x8cEf22C6c7b4472e9F226dF16F8c4AE4b70998F0 have 0 want 480000000000000"
t=2023-11-11T08:08:17+0100 lvl=warn msg="Served debug_traceCall"               conn=127.0.0.1:48318 reqid=34436 t="106.851µs"              err="tracing failed: insufficient funds for gas * price + value: address 0xD6f4165829299d3C22DbC01f05E46c34f4110ACb have 0 want 240000000000000" X-Forwarded-For=nil
t=2023-11-11T08:08:17+0100 lvl=warn msg="Served debug_traceCall"               conn=127.0.0.1:48318 reqid=34436 duration="106.151µs" err="tracing failed: insufficient funds for gas * price + value: address 0xD6f4165829299d3C22DbC01f05E46c34f4110ACb have 0 want 240000000000000"
t=2023-11-11T08:08:17+0100 lvl=warn msg="Served debug_traceCall"               conn=127.0.0.1:48134 reqid=34437 t="157.432µs"              err="tracing failed: insufficient funds for gas * price + value: address 0xfba6DDD67236D44fBcfbB5D988Bd7eDBe671179e have 0 want 480000000000000" X-Forwarded-For=nil
t=2023-11-11T08:08:17+0100 lvl=warn msg="Served debug_traceCall"               conn=127.0.0.1:48134 reqid=34437 duration="156.372µs" err="tracing failed: insufficient funds for gas * price + value: address 0xfba6DDD67236D44fBcfbB5D988Bd7eDBe671179e have 0 want 480000000000000"
t=2023-11-11T08:08:17+0100 lvl=warn msg="Served debug_traceCall"               conn=127.0.0.1:48334 reqid=34438 t="156.131µs"              err="tracing failed: insufficient funds for gas * price + value: address 0xAd63D7a58a3aDeBDDDF83CBc7eaCFF8C2a3f04c7 have 0 want 360235017000000000" X-Forwarded-For=nil
t=2023-11-11T08:08:17+0100 lvl=warn msg="Served debug_traceCall"               conn=127.0.0.1:48318 reqid=34439 t="123.691µs"              err="tracing failed: insufficient funds for gas * price + value: address 0xd98e0D185bA96A2C986b8182f17b3fba112955D1 have 0 want 480000000000000" X-Forwarded-For=nil
t=2023-11-11T08:08:17+0100 lvl=warn msg="Served debug_traceCall"               conn=127.0.0.1:48318 reqid=34439 duration="122.991µs" err="tracing failed: insufficient funds for gas * price + value: address 0xd98e0D185bA96A2C986b8182f17b3fba112955D1 have 0 want 480000000000000"

#### Steps to reproduce the behaviour
rust ethers-rs code
```
let tx = tx.clone();
let opt = GethDebugTracingCallOptions {
    tracing_options: GethDebugTracingOptions {
        disable_storage: None,
        disable_stack: None,
        enable_memory: None,
        enable_return_data: None,
        tracer: Some(BuiltInTracer(PreStateTracer)),
        tracer_config: Some(GethDebugTracerConfig::BuiltInTracer(
            GethDebugBuiltInTracerConfig::PreStateTracer(PreStateConfig {
                diff_mode: Some(true),
            }),
        )),
        timeout: None,
    },
    state_overrides: None,
};
let block_traces = match client
    .debug_trace_call(tx.clone(), Some(BlockId::from(block_num)), opt)
    .await
```

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by CocoStarZ** [comment]
Please use https://github.com/bnb-chain/bsc/releases/tag/v1.2.13 instead

**Comment by zzphust** [comment]
Seems it's not bugs. This roc test ok for me

**Comment by greyireland** [comment]
> Seems it's not bugs. This rpc test ok for me

Can you share a calling example?
@zzphust
