### ISSUE TITLE
v1.3.1-beta stuck, updated from v1.3.0

### ISSUE THREAD

**Issue by tebeletbl** [bnb-chain/bsc#1982]
i just tried to update my geth from v1.3.0 to v.1.3.1 
![image](https://github.com/bnb-chain/bsc/assets/102418244/f57fb3dc-50eb-4ad7-a576-8e4537b1f0c0)
but stuck here

**Comment by CocoStarZ** [comment]
could you pls provide more info? are you able to upgrade to 1.2.13?

**Comment by tebeletbl** [comment]
1.2.13 working just fine, i tried 1.3.0 but sometimes misses few pending tx, then i updated to 1.3.1 and node wont start, now i downgraded to 1.2.13 since 1.3.1 wont start and 1.3.0 seems unstable

**Comment by weiihann** [comment]
I just tried starting up a new node with v1.3.1-beta and it works fine. Perhaps there are some configurations previously that caused the issue. Can you provide the following details:
1. Node start-up command
2. Logs with trace enabled (i.e. --verbosity=5)

**Comment by tebeletbl** [comment]
this is my start up command 
for 1.3.0 and 1.2.13, is there anything i need to change for 1.3.1
./geth_linux --config ./config.toml --datadir ./mainnet --cache 48000 --rpc.allow-unprotected-txs --txlookuplimit 0 --http --maxpeers 850 --ws --syncmode=full --snapshot=true --tries-verify-mode=none --pruneancient=true --diffblock=5000

**Comment by weiihann** [comment]
can you try to run it again with `--verbosity=5` can show the logs?

**Comment by tebeletbl** [comment]
Nov 13 15:21:01 mine2 bash[55126]: Fatal: Could not open database: open /home/geth/mainnet/geth/chaindata/ancient/bodies.cidx: no such file or directory
Nov 13 15:21:01 mine2 systemd[1]: geth.service: Main process exited, code=exited, status=1/FAILURE
Nov 13 15:21:01 mine2 systemd[1]: geth.service: Failed with result 'exit-code'.

**Comment by tebeletbl** [comment]
thanks, waiting for next update
