### ISSUE TITLE
Failed to register the Ethereum service: ethash is only supported as a historical component of already merged networks

### ISSUE THREAD

**Issue by Alexvojander** [bnb-chain/bsc#1989]
Geth version: geth version 1.3.1-1dca4866-20231109
Ubuntu
node not working

Hi guys, so, downloaded binaries & config files from this repo
and node snapshot, but getting ethhash error
 
 after running this command:

~/bsc$ ./geth --config ./config.toml --datadir ./node  --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0

getting this error:

INFO [11-16|16:54:08.324] Starting Geth on Ethereum mainnet... 
INFO [11-16|16:54:08.330] Maximum peer count                       ETH=200 LES=0 total=200
INFO [11-16|16:54:08.333] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
Fatal: Failed to register the Ethereum service: ethash is only supported as a historical component of already merged networks
 

My server also runs with ethnode with another geth version, but for bsc one I'm specifying the correct one ./geth

any idea how to solve this issue, smb encountered with it?

I also saw that ethhash PoW algo was removed from geth few version ago, so I completely don't understand why I'm getting this error.... 
Thanks for answer

**Comment by weiihann** [comment]
It could be something that went wrong with the configuration setup. Essentially if the node can't detect the Parlia configuration, it'll default to ethash, which returns the error. 

Can you walk me through the exact steps that you followed?

**Comment by CocoStarZ** [comment]
No response. Close now
