### ISSUE TITLE
When we will have support of leveldb metrics as Geth now has?

### ISSUE THREAD

**Issue by Aracki** [bnb-chain/bsc#1995]
Geth implemented metrics like `tables_level.*`, `eth_db_chaindata_tables_level.*`,...

Can bsc support these as well?

**Comment by weiihann** [comment]
Are you referring to https://github.com/ethereum/go-ethereum/pull/28271 and https://github.com/ethereum/go-ethereum/pull/27904?

If yes, from v1.3.0 version onwards already implemented **27904**, perhaps **28271** will follow. But v.1.3.0 versions are still not stable and might have some issues, so do stay tuned for the stable releases.
