### ISSUE TITLE
v1.3.1-beta personal_signTransaction error

### ISSUE THREAD

**Issue by bossikkk** [bnb-chain/bsc#2001]
Hello. After update node to v1.3.1-beta I can't use personal_signTransaction, because error:
"Returned error: the method personal_signTransaction does not exist/is not available"
In my config.toml I have "personal" in HTTPModules.

**Comment by smithdodo** [comment]
It seems that the personal namespace has been deprecated. However, you can still enable it by using the command line flag --rpc.enabledeprecatedpersonal
