### ISSUE TITLE
pruneancient command line argument flag vs config.toml flag

### ISSUE THREAD

**Issue by zhk101** [bnb-chain/bsc#2003]
I was under the impression that all the flags that can be passed via command line arguments to geth can be instead set in the config.toml

I was having the same issues that were fixed by #1986 but having the `PruneAncientData = true` in config.tml did nothing.
Instead I had to add the --pruneancient=true command line argument and the node started working fine with the latest bnb48club fast snapshot.

My question essentially is if this is expected behaviour and if it is, if there are other flags that behaves the same?

**Comment by CocoStarZ** [comment]
Please use this tag in command line not config file.
