### ISSUE TITLE
v1.3.2 can't start with flags `--pruneancient=true`

### ISSUE THREAD

**Issue by du5** [bnb-chain/bsc#2016]
@weiihann  请在 [v1.3.2](https://github.com/bnb-chain/bsc/tree/v1.3.2) 分支应用此修复，并更新版本号至 1.3.2

https://github.com/bnb-chain/bsc/issues/1984
https://github.com/bnb-chain/bsc/blob/v1.3.2/cmd/utils/flags.go#L2353-L2362
https://github.com/bnb-chain/bsc/pull/1986/files

**Comment by weiihann** [comment]
Check out [v1.3.3](https://github.com/bnb-chain/bsc/releases/tag/v1.3.3)
