### ISSUE TITLE
Lower mgasps with PBSS

### ISSUE THREAD

**Issue by kaber2** [bnb-chain/bsc#2022]
Hello,

I'm seeing reduced mgasps with PBSS and I'm wondering if that is (currently) expected. While I haven't done proper measurements, just by observing the logs I noticed that with the hash based scheme and leveldb, I'm usually seeing something between 400 and 600 mgasps on block import, with PBSS and Pebble the numbers are in the range of 300 to 450 mgasps. Comparing 2 running nodes also shows that the one with PBSS constantly has a lower mgasps on each block.

Is that something that is currently to be expected?

**Comment by kaber2** [comment]
The machines are identical in both hardware and software, except for PBSS being used on one of them. Let me see if I can capture some data over time.

**Comment by flywukong** [comment]
@kaber2 We have recently updated the geth version v.13.5 ([](https://github.com/bnb-chain/bsc/releases/tag/v1.3.5)) and BSC snapshot [](https://github.com/bnb-chain/bsc-snapshots) (including hbss+leveldb and pbss+pebble). It is recommended to test with the latest version of geth and snapshot.
