### ISSUE TITLE
Hardfork confusion

### ISSUE THREAD

**Issue by kaber2** [bnb-chain/bsc#2029]
Hello guys. I'm not sure what to make out of the current hardfork mess.

- In release 1.3.2 (and the corresponding 1.2.x release), you silently added a hardfork, without stating it in the release notes.
- When googling for the old HF blocknumber, I find this entry on twitter, which states the unannounced HF has been postponed: https://twitter.com/BNBCHAIN/status/1730258869861990683
- The new release contains the postponed hardfork, three days after the last hardfork has already activated.

So what's up with this?

**Comment by CocoStarZ** [comment]
pls check the update here: https://www.bnbchain.org/en/blog/hotfix-hardfork-for-bsc-mainnet-upgrade-bsc-geth-to-v1-2-14-or-1-3-2

**Comment by alfaori1977** [comment]
I'm trying with proposed version [BSC geth v1.2.15](https://github.com/bnb-chain/bsc/releases/tag/v1.2.15?ref=bnbchain.ghost.io) and it's being impossible to be synced again:

I attach the logs from the last launch (5 minutes ago) and an screenshot.

`root@rpc:~/testnet/node# tail -1000  bsc.log
t=2023-12-05T07:28:11+0100 lvl=warn msg="The --diffsync flag is deprecated and will be removed in the future!"
t=2023-12-05T07:28:11+0100 lvl=info msg="Set global gas cap" cap=50,000,000
t=2023-12-05T07:28:11+0100 lvl=info msg="Allocated trie memory caches" clean="1.17 GiB" dirty="1.95 GiB"
t=2023-12-05T07:28:11+0100 lvl=info msg="Allocated cache and file handles" database=/root/testnet/node/geth/chaindata cache="3.12 GiB" handles=524,288
root@rpc:~/testnet/node# tail -F  bsc.log
t=2023-12-05T07:28:11+0100 lvl=warn msg="The --diffsync flag is deprecated and will be removed in the future!"
t=2023-12-05T07:28:11+0100 lvl=info msg="Set global gas cap" cap=50,000,000
t=2023-12-05T07:28:11+0100 lvl=info msg="Allocated trie memory caches" clean="1.17 GiB" dirty="1.95 GiB"
t=2023-12-05T07:28:11+0100 lvl=info msg="Allocated cache and file handles" database=/root/testnet/node/geth/chaindata cache="3.12 GiB" handles=524,288


t=2023-12-05T07:28:30+0100 lvl=info msg="AncientDB item count"             items=28,738,203
t=2023-12-05T07:28:30+0100 lvl=info msg="Opened ancient database"          database=/root/testnet/node/geth/chaindata/ancient readonly=false frozen=28,738,203
t=2023-12-05T07:28:30+0100 lvl=info msg="Initialised chain configuration"  config="{ChainID: 97 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 1010000, Niels: 1014369, MirrorSync: 5582500, Bruno: 13837000, Berlin: 31103030, YOLO v3: <nil>, CatalystBlock: <nil>, London: 31103030, ArrowGlacier: <nil>, MergeFork:<nil>, Euler: 19203503, Gibbs: 22800220, Nano: 23482428, Moran: 23603940, Planck: 28196022,Luban: 29295050, Plato: 29861024, Hertz: 31103030, Hertzfix: 35682300, Engine: parlia}"
t=2023-12-05T07:28:30+0100 lvl=info msg="Unprotected transactions allowed"
t=2023-12-05T07:28:30+0100 lvl=info msg="Initialising Ethereum protocol"   network=97 dbversion=8
t=2023-12-05T07:28:32+0100 lvl=info msg="Loaded most recent local header"  number=28,738,201 hash=0x7f1fd98cd093814430e256120b1944aa23e33b89c4078d35f94c034d60639f15 td=57,299,902 age=8mo1d8h
t=2023-12-05T07:28:32+0100 lvl=info msg="Loaded most recent local full block" number=28,215,525 hash=0x993beeb0d362acc16a83c286ed2486d02aec0192d417d3ada920a73a2bcbf2f7 td=56,257,980 age=8mo2w5d
t=2023-12-05T07:28:32+0100 lvl=info msg="Loaded most recent local fast block" number=28,738,201 hash=0x7f1fd98cd093814430e256120b1944aa23e33b89c4078d35f94c034d60639f15 td=57,299,902 age=8mo1d8h
t=2023-12-05T07:28:32+0100 lvl=info msg="Loaded last fast-sync pivot marker"  number=28,215,525
t=2023-12-05T07:28:32+0100 lvl=eror msg="Truncating ancient chain"            from=28,738,201 to=28,215,525
t=2023-12-05T07:28:32+0100 lvl=warn msg="Rewinding blockchain"                target=28,215,525
t=2023-12-05T07:28:32+0100 lvl=warn msg="Truncating freezer table"            database=/root/testnet/node/geth/chaindata/ancient table=diffs items=28,738,203 limit=28,738,201
t=2023-12-05T07:28:32+0100 lvl=warn msg="Truncating freezer table"            database=/root/testnet/node/geth/chaindata/ancient table=headers items=28,738,203 limit=28,738,201
t=2023-12-05T07:28:32+0100 lvl=warn msg="Truncating freezer table"            database=/root/testnet/node/geth/chaindata/ancient table=hashes  items=28,738,203 limit=28,738,201
t=2023-12-05T07:28:32+0100 lvl=warn msg="Truncating freezer table"            database=/root/testnet/node/geth/chaindata/ancient table=bodies  items=28,738,203 limit=28,738,201
t=2023-12-05T07:28:32+0100 lvl=warn msg="Truncating freezer table"            database=/root/testnet/node/geth/chaindata/ancient table=receipts items=28,738,203 limit=28,738,201

`

<img width="965" alt="image" src="https://github.com/bnb-chain/bsc/assets/122934282/1150eb06-9eeb-4605-9c5b-81344853bdc0">

**Comment by kaber2** [comment]
> pls check the update here: https://www.bnbchain.org/en/blog/hotfix-hardfork-for-bsc-testnet-and-mainnet

Thanks, but generally, the proper place to announce anything important for node operators is  right here. I don't have time to read random blogs or twitter feeds. This is where the software is released, and this is where important information for running the software should be as well.

I realize you might this might have just been an oversight, but please keep this in mind for future updates.

**Comment by CocoStarZ** [comment]
We have both twitter and blog for this hardfork. Please kindly follow either one of them. Sorry for the inconvenience. Close the issue now.
