### ISSUE TITLE
Fast node open OOM

### ISSUE THREAD

**Issue by lichao1991** [bnb-chain/bsc#2031]
#### System information

Geth version:  v1.2.15
OS & Version: ubuntu
Commit hash : (if `develop`)

#### Steps to reproduce the behaviour
nohup /data/bsc/build/bin/geth_linux  --config ./config.toml --datadir ./node  --txlookuplimit=0   --syncmode=full --tries-verify-mode=none --pruneancient=true  --cache 8000 &

#### Backtrace
INFO [12-04|16:09:09.233] Starting Geth on Ethereum mainnet... 
INFO [12-04|16:09:09.235] Maximum peer count                       ETH=200 LES=0 total=200
INFO [12-04|16:09:09.235] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
fatal error: runtime: out of memory

runtime stack:
runtime.throw({0x262c303?, 0x10000?})
	/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/panic.go:1047 +0x5d fp=0x7fe9caa7b868 sp=0x7fe9caa7b838 pc=0x43b6fd
runtime.sysMapOS(0xc031800000, 0x59c8400000?)
	/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/mem_linux.go:187 +0x11b fp=0x7fe9caa7b8b0 sp=0x7fe9caa7b868 pc=0x419efb
runtime.sysMap(0x4882620?, 0x7fe9f6312000?, 0x42f380?)
	/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/mem.go:142 +0x35 fp=0x7fe9caa7b8e0 sp=0x7fe9caa7b8b0 pc=0x4198d5
runtime.(*mheap).grow(0x4882620, 0x2ce40a8?)
	/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/mheap.go:1468 +0x23d fp=0x7fe9caa7b950 sp=0x7fe9caa7b8e0 pc=0x42c37d
runtime.(*mheap).allocSpan(0x4882620, 0x2ce40a8, 0x0, 0x1)
	/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/mheap.go:1199 +0x1be fp=0x7fe9caa7b9e8 sp=0x7fe9caa7b950 pc=0x42babe
runtime.(*mheap).alloc.func1()
	/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/mheap.go:918 +0x65 fp=0x7fe9caa7ba30 sp=0x7fe9caa7b9e8 pc=0x42b545
runtime.systemstack()
	/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/asm_amd64.s:492 +0x49 fp=0x7fe9caa7ba38 sp=0x7fe9caa7ba30 pc=0x46e169
````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by CocoStarZ** [comment]
Which snapshot do you use? 48Club?

**Comment by lichao1991** [comment]
> Which snapshot do you use? 48Club?

yes, [33660414](https://bscscan.com/block/33660414) (Nov-20-2023 02:40:35 PM +UTC)

**Comment by weiihann** [comment]
What's your machine specs?

**Comment by weiihann** [comment]
Duplicated issue found: https://github.com/48Club/bsc-snapshots/issues/127
