### ISSUE TITLE
 'UltraLightFraction' is not defined in ethconfig.Config

### ISSUE THREAD

**Issue by Joter271** [bnb-chain/bsc#2038]
#### System information

Geth version: v1.3.X
OS & Version: Windows

####
Fatal: D:\geth bnb\geth\config.toml, line 11: field 'UltraLightFraction' is not defined in ethconfig.Config, see https://godoc.org/github.com/ethereum/go-ethereum/eth/ethconfig#Config for available fields

###
Same config works fine with v1.2.15

**Comment by zzzckck** [comment]
check: https://github.com/bnb-chain/bsc/releases/tag/v1.3.0
it was removed since v1.3.0, does it useful to you?
<img width="1059" alt="image" src="https://github.com/bnb-chain/bsc/assets/152148891/8ad3b7e7-4175-4b36-9739-40b2691799e5">
