### ISSUE TITLE
When will you start supporting EIP-1559 and EIP-4337 ?

### ISSUE THREAD

**Issue by BillInUK** [bnb-chain/bsc#2062]
When will you start supporting EIP-1559 and EIP-4337 ?

**Comment by zzzckck** [comment]
EIP-1559 has already been supported since the [Hertz](https://forum.bnbchain.org/t/bnb-chain-upgrades-mainnet/936#hertzenabled-11) hard fork, but currently the BaseFee is zero on BSC

**Comment by BillInUK** [comment]
thank you for reply
