### ISSUE TITLE
Testnet fullnode sync error："########## BAD BLOCK ######### Block: 19249200 

### ISSUE THREAD

**Issue by xiaowangba2dai** [bnb-chain/bsc#2069]
Hello, I ran a testnet full node. Since there was no snapshot, I started running from the genesis block. The geth version is 1.3.5. The following is my startup command and log. What should I do so that I can Sync smoothly.

./geth_1.3.5 --config ./config.toml --datadir ./node --cache 2048 --syncmode full --tries-verify-mode local --networkid 97 --miner.gaslimit 40000000 --miner.gasprice 1000000000 --miner.recommit 10s --txpool.nolocals=true --txpool.journal transactions.rlp --txpool.rejournal 1h0m0s --txpool.pricelimit 1000000000 --txpool.pricebump 10 --txpool.accountslots 16 --txpool.globalslots 4096 --txpool.accountqueue 64 --txpool.globalqueue 1024 --gpo.blocks 20 --gpo.percentile 60 --ipcpath geth.ipc --http --http.addr=192.168.0.78 --http.port 8545 --http.api debug,eth,net,txpool,web3,admin --http.vhosts * --http.corsdomain localhost --ws --ws.addr 192.168.0.78 --ws.port 8546 --ws.api debug,eth,net,txpool,web3 --ws.origins * --port 30311 --bootnodes enode://0637d1e62026e0c8685b1db0ca1c767c78c95c3fab64abc468d1a64b12ca4b530b46b8f80c915aec96f74f7ffc5999e8ad6d1484476f420f0c10e3d42361914b@52.199.214.252:30311,enode://df1e8eb59e42cad3c4551b2a53e31a7e55a2fdde1287babd1e94b0836550b489ba16c40932e4dacb16cba346bd442c432265a299c4aca63ee7bb0f832b9f45eb@52.51.80.128:30311,enode://ecd664250ca19b1074dcfbfb48576a487cc18d052064222a363adacd2650f8e08fb3db9de7a7aecb48afa410eaeb3285e92e516ead01fb62598553aed91ee15e@3.209.122.123:30311,enode://665cf77ca26a8421cfe61a52ac312958308d4912e78ce8e0f61d6902e4494d4cc38f9b0dd1b23a427a7a5734e27e5d9729231426b06bb9c73b56a142f83f6b68@52.72.123.113:30311 --nat extip:192.168.0.78 --maxpeers 100 --datadir.minfreedisk 0 --history.transactions 0 --state.scheme path --db.engine pebble

**the geth log:**
t=2023-12-15T08:59:34+0800 lvl=warn msg="Snapshot extension registration failed" peer=b7b20f01 err="peer connected on snap without compatible eth support"
t=2023-12-15T08:59:37+0800 lvl=info msg="Skip duplicated bad block"              number=19,249,200 hash=0xa680b2ac156470bdb8f3a2bf7b33fe5c375060d8a3f71a2a41d667fb786c8dc0
t=2023-12-15T08:59:37+0800 lvl=eror msg="\n########## BAD BLOCK #########\nBlock: 19249200 (0xa680b2ac156470bdb8f3a2bf7b33fe5c375060d8a3f71a2a41d667fb786c8dc0)\nError: mismatching validator list on epoch block\nPlatform: geth (devel) go1.20.11 amd64 linux\nVCS: fe928d47-20231208 (dirty)\nChain config: &params.ChainConfig{ChainID:97, HomesteadBlock:0, DAOForkBlock:<nil>, DAOForkSupport:false, EIP150Block:0, EIP155Block:0, EIP158Block:0, ByzantiumBlock:0, ConstantinopleBlock:0, PetersburgBlock:0, IstanbulBlock:0, MuirGlacierBlock:0, BerlinBlock:31103030, YoloV3Block:<nil>, CatalystBlock:<nil>, LondonBlock:31103030, ArrowGlacierBlock:<nil>, GrayGlacierBlock:<nil>, MergeNetsplitBlock:<nil>, ShanghaiTime:(*uint64)(0xc000056560), KeplerTime:(*uint64)(0xc000056568), CancunTime:(*uint64)(nil), PragueTime:(*uint64)(nil), VerkleTime:(*uint64)(nil), TerminalTotalDifficulty:<nil>, TerminalTotalDifficultyPassed:false, RamanujanBlock:1010000, NielsBlock:1014369, MirrorSyncBlock:5582500, BrunoBlock:13837000, EulerBlock:19203503, GibbsBlock:22800220, NanoBlock:23482428, MoranBlock:23603940, PlanckBlock:28196022, LubanBlock:29295050, PlatoBlock:29861024, HertzBlock:31103030, HertzfixBlock:35682300, Ethash:(*params.EthashConfig)(nil), Clique:(*params.CliqueConfig)(nil), Parlia:(*params.ParliaConfig)(0x496da90), IsDevMode:false}\nReceipts: \n  0: cumulative: 793712 gas: 793712 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xb5dd5e91c9d25baf7578be22e9c7e19b271da2aabccfe3f6b3ffccbf41dcdb05 logs: [0xc03c553c30 0xc066d926e0 0xc08b6dc0b0 0xc03d3622c0] bloom: 00020000080000040000200000002000000000000000000000000000000000200000000000000010000000000000000000000000000000000000001000100000000000001000000000000008000000000000000000000000000000000000000000000000000004000000000000000000000200000000000000000010000000000000000000000000000000000000000000000000400000000200000000000000000000010000000000000000010000400000000020000000000000000000000000000212000000000000000001000000000000000000001000010000000200080000000000000040000000000000000000000800000000000000000000000000 state: \n  1: cumulative: 821835 gas: 28123 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x6e9821124ac17afdb8fb67e830cb988f39549a811c0ea3763bd82bc97ec62310 logs: [0xc03d362420] bloom: 00000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000010240000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000040000000800000000000000000020000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000100004000000000000000000000000000000000000000000000000000000000000000000000000000040000010000000000400000000000008000000000000000000000000000000000000 state: \n  2: cumulative: 1139664 gas: 317829 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x72b1f3927b2b175ef01cbd8d2806e8f345f8913117a22d002376d81532dcf956 logs: [] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state: \n  3: cumulative: 1208663 gas: 68999 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xc5e2110a0e21f25a55651d8dba17885a50b6cbfd932f970ccd4e812adbd8e600 logs: [0xc03d362630 0xc03d362c60 0xc03d362d10] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000100000000000000000000000000000400000000000000108000000000000000000000000000000000000000000000000000010000001000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000080000000000000000002000000000000000000000020000000000000000000000000000000000000000000000000080000000000000000000000400000000000000000000200 state: \n  4: cumulative: 1245546 gas: 36883 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x824ed14256b56ef227ab5f1adad76923a9707792122f22d162aabc6debc1ee18 logs: [0xc03d362e70] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000020000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000080000000000000000010000000000000000000000000000010000000000000000000000000000000800000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000400000002000080000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state: \n##############################\n"
t=2023-12-15T08:59:37+0800 lvl=warn msg="Synchronisation failed, dropping peer"  peer=477bb318d8bc6b2a040b5de9313b4edc8e978a5ecbf8fd75f5590e2a07fa21fc err="retrieved hash chain is invalid: mismatching validator list on epoch block"
t=2023-12-15T08:59:39+0800 lvl=warn msg="Snapshot extension registration failed" peer=4ba692d3 err="peer connected on snap without compatible eth support"
t=2023-12-15T08:59:40+0800 lvl=warn msg="Snapshot extension registration failed" peer=7d21bf53 err="peer connected on snap without compatible eth support"
t=2023-12-15T08:59:40+0800 lvl=warn msg="Snapshot extension registration failed" peer=272c9f42 err="peer connected on snap without compatible eth support"
t=2023-12-15T08:59:42+0800 lvl=warn msg="Snapshot extension registration failed" peer=e0a82c7f err="peer connected on snap without compatible eth support"
t=2023-12-15T08:59:42+0800 lvl=warn msg="Snapshot extension registration failed" peer=239e48bd err="peer connected on snap without compatible eth support"
t=2023-12-15T08:59:44+0800 lvl=warn msg="Snapshot extension registration failed" peer=2aef1844 err="peer connected on snap without compatible eth support"
t=2023-12-15T08:59:45+0800 lvl=warn msg="Snapshot extension registration failed" peer=932447c1 err="peer connected on snap without compatible eth support"
t=2023-12-15T08:59:46+0800 lvl=warn msg="Snapshot extension registration failed" peer=900e1401 err="peer connected on snap without compatible eth support"
t=2023-12-15T08:59:47+0800 lvl=warn msg="Snapshot extension registration failed" peer=4c37225a err="peer connected on snap without compatible eth support"
t=2023-12-15T08:59:48+0800 lvl=warn msg="Snapshot extension registration failed" peer=919a41a6 err="peer connected on snap without compatible eth support"
t=2023-12-15T08:59:49+0800 lvl=info msg="Skip duplicated bad block"              number=19,249,200 hash=0xa680b2ac156470bdb8f3a2bf7b33fe5c375060d8a3f71a2a41d667fb786c8dc0
t=2023-12-15T08:59:49+0800 lvl=eror msg="\n########## BAD BLOCK #########\nBlock: 19249200 (0xa680b2ac156470bdb8f3a2bf7b33fe5c375060d8a3f71a2a41d667fb786c8dc0)\nError: mismatching validator list on epoch block\nPlatform: geth (devel) go1.20.11 amd64 linux\nVCS: fe928d47-20231208 (dirty)\nChain config: &params.ChainConfig{ChainID:97, HomesteadBlock:0, DAOForkBlock:<nil>, DAOForkSupport:false, EIP150Block:0, EIP155Block:0, EIP158Block:0, ByzantiumBlock:0, ConstantinopleBlock:0, PetersburgBlock:0, IstanbulBlock:0, MuirGlacierBlock:0, BerlinBlock:31103030, YoloV3Block:<nil>, CatalystBlock:<nil>, LondonBlock:31103030, ArrowGlacierBlock:<nil>, GrayGlacierBlock:<nil>, MergeNetsplitBlock:<nil>, ShanghaiTime:(*uint64)(0xc000056560), KeplerTime:(*uint64)(0xc000056568), CancunTime:(*uint64)(nil), PragueTime:(*uint64)(nil), VerkleTime:(*uint64)(nil), TerminalTotalDifficulty:<nil>, TerminalTotalDifficultyPassed:false, RamanujanBlock:1010000, NielsBlock:1014369, MirrorSyncBlock:5582500, BrunoBlock:13837000, EulerBlock:19203503, GibbsBlock:22800220, NanoBlock:23482428, MoranBlock:23603940, PlanckBlock:28196022, LubanBlock:29295050, PlatoBlock:29861024, HertzBlock:31103030, HertzfixBlock:35682300, Ethash:(*params.EthashConfig)(nil), Clique:(*params.CliqueConfig)(nil), Parlia:(*params.ParliaConfig)(0x496da90), IsDevMode:false}\nReceipts: \n  0: cumulative: 793712 gas: 793712 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xb5dd5e91c9d25baf7578be22e9c7e19b271da2aabccfe3f6b3ffccbf41dcdb05 logs: [0xc0481d5550 0xc04d0820b0 0xc04d082210 0xc04d082370] bloom: 00020000080000040000200000002000000000000000000000000000000000200000000000000010000000000000000000000000000000000000001000100000000000001000000000000008000000000000000000000000000000000000000000000000000004000000000000000000000200000000000000000010000000000000000000000000000000000000000000000000400000000200000000000000000000010000000000000000010000400000000020000000000000000000000000000212000000000000000001000000000000000000001000010000000200080000000000000040000000000000000000000800000000000000000000000000 state: \n  1: cumulative: 821835 gas: 28123 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x6e9821124ac17afdb8fb67e830cb988f39549a811c0ea3763bd82bc97ec62310 logs: [0xc04d0826e0] bloom: 00000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000010240000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000040000000800000000000000000020000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000100004000000000000000000000000000000000000000000000000000000000000000000000000000040000010000000000400000000000008000000000000000000000000000000000000 state: \n  2: cumulative: 1139664 gas: 317829 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x72b1f3927b2b175ef01cbd8d2806e8f345f8913117a22d002376d81532dcf956 logs: [] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state: \n  3: cumulative: 1208663 gas: 68999 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xc5e2110a0e21f25a55651d8dba17885a50b6cbfd932f970ccd4e812adbd8e600 logs: [0xc04d082dc0 0xc04d082fd0 0xc04d0833f0] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000100000000000000000000000000000400000000000000108000000000000000000000000000000000000000000000000000010000001000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000080000000000000000002000000000000000000000020000000000000000000000000000000000000000000000000080000000000000000000000400000000000000000000200 state: \n  4: cumulative: 1245546 gas: 36883 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x824ed14256b56ef227ab5f1adad76923a9707792122f22d162aabc6debc1ee18 logs: [0xc04d083550] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000020000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000080000000000000000010000000000000000000000000000010000000000000000000000000000000800000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000400000002000080000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state: \n##############################\n"
t=2023-12-15T08:59:49+0800 lvl=warn msg="Synchronisation failed, dropping peer"  peer=dc988fd68204a652ddbc45a21982da576fc37c77f33fb837455561f991e5d5cf err="retrieved hash chain is invalid: mismatching validator list on epoch block"
t=2023-12-15T08:59:51+0800 lvl=warn msg="Snapshot extension registration failed" peer=039a3184 err="peer connected on snap without compatible eth support"
t=2023-12-15T08:59:51+0800 lvl=warn msg="Snapshot extension registration failed" peer=052962ab err="peer connected on snap without compatible eth support"
t=2023-12-15T08:59:54+0800 lvl=warn msg="Snapshot extension registration failed" peer=85252060 err="peer connected on snap without compatible eth support"
t=2023-12-15T08:59:56+0800 lvl=eror msg="Expired request does not exist"         peer=37d7ad094f4637b8a9794cb08e97ef5a4ea98d72a413dc42f68c2a350c148a6a
t=2023-12-15T08:59:56+0800 lvl=info msg="Skip duplicated bad block"              number=19,249,200 hash=0xa680b2ac156470bdb8f3a2bf7b33fe5c375060d8a3f71a2a41d667fb786c8dc0
t=2023-12-15T08:59:56+0800 lvl=eror msg="\n########## BAD BLOCK #########\nBlock: 19249200 (0xa680b2ac156470bdb8f3a2bf7b33fe5c375060d8a3f71a2a41d667fb786c8dc0)\nError: mismatching validator list on epoch block\nPlatform: geth (devel) go1.20.11 amd64 linux\nVCS: fe928d47-20231208 (dirty)\nChain config: &params.ChainConfig{ChainID:97, HomesteadBlock:0, DAOForkBlock:<nil>, DAOForkSupport:false, EIP150Block:0, EIP155Block:0, EIP158Block:0, ByzantiumBlock:0, ConstantinopleBlock:0, PetersburgBlock:0, IstanbulBlock:0, MuirGlacierBlock:0, BerlinBlock:31103030, YoloV3Block:<nil>, CatalystBlock:<nil>, LondonBlock:31103030, ArrowGlacierBlock:<nil>, GrayGlacierBlock:<nil>, MergeNetsplitBlock:<nil>, ShanghaiTime:(*uint64)(0xc000056560), KeplerTime:(*uint64)(0xc000056568), CancunTime:(*uint64)(nil), PragueTime:(*uint64)(nil), VerkleTime:(*uint64)(nil), TerminalTotalDifficulty:<nil>, TerminalTotalDifficultyPassed:false, RamanujanBlock:1010000, NielsBlock:1014369, MirrorSyncBlock:5582500, BrunoBlock:13837000, EulerBlock:19203503, GibbsBlock:22800220, NanoBlock:23482428, MoranBlock:23603940, PlanckBlock:28196022, LubanBlock:29295050, PlatoBlock:29861024, HertzBlock:31103030, HertzfixBlock:35682300, Ethash:(*params.EthashConfig)(nil), Clique:(*params.CliqueConfig)(nil), Parlia:(*params.ParliaConfig)(0x496da90), IsDevMode:false}\nReceipts: \n  0: cumulative: 793712 gas: 793712 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xb5dd5e91c9d25baf7578be22e9c7e19b271da2aabccfe3f6b3ffccbf41dcdb05 logs: [0xc03e138f20 0xc03e138fd0 0xc03e139290 0xc03e139340] bloom: 00020000080000040000200000002000000000000000000000000000000000200000000000000010000000000000000000000000000000000000001000100000000000001000000000000008000000000000000000000000000000000000000000000000000004000000000000000000000200000000000000000010000000000000000000000000000000000000000000000000400000000200000000000000000000010000000000000000010000400000000020000000000000000000000000000212000000000000000001000000000000000000001000010000000200080000000000000040000000000000000000000800000000000000000000000000 state: \n  1: cumulative: 821835 gas: 28123 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x6e9821124ac17afdb8fb67e830cb988f39549a811c0ea3763bd82bc97ec62310 logs: [0xc03e139600] bloom: 00000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000010240000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000040000000800000000000000000020000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000100004000000000000000000000000000000000000000000000000000000000000000000000000000040000010000000000400000000000008000000000000000000000000000000000000 state: \n  2: cumulative: 1139664 gas: 317829 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x72b1f3927b2b175ef01cbd8d2806e8f345f8913117a22d002376d81532dcf956 logs: [] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state: \n  3: cumulative: 1208663 gas: 68999 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xc5e2110a0e21f25a55651d8dba17885a50b6cbfd932f970ccd4e812adbd8e600 logs: [0xc03e139ef0 0xc07a344160 0xc07a3442c0] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000100000000000000000000000000000400000000000000108000000000000000000000000000000000000000000000000000010000001000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000080000000000000000002000000000000000000000020000000000000000000000000000000000000000000000000080000000000000000000000400000000000000000000200 state: \n  4: cumulative: 1245546 gas: 36883 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x824ed14256b56ef227ab5f1adad76923a9707792122f22d162aabc6debc1ee18 logs: [0xc07a344580] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000020000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000080000000000000000010000000000000000000000000000010000000000000000000000000000000800000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000400000002000080000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state: \n##############################\n"
t=2023-12-15T08:59:56+0800 lvl=warn msg="Synchronisation failed, dropping peer"  peer=594b6d28bf31b2336f3fdff7853efb54decf48031560d396574ed42494f03219 err="retrieved hash chain is invalid: mismatching validator list on epoch block"
t=2023-12-15T08:59:57+0800 lvl=warn msg="Snapshot extension registration failed" peer=2ecda637 err="peer connected on snap without compatible eth support"
t=2023-12-15T08:59:58+0800 lvl=warn msg="Snapshot extension registration failed" peer=278428ae err="peer connected on snap without compatible eth support"
t=2023-12-15T08:59:58+0800 lvl=warn msg="Snapshot extension registration failed" peer=557c6359 err="peer connected on snap without compatible eth support"
t=2023-12-15T08:59:59+0800 lvl=warn msg="Snapshot extension registration failed" peer=501f6112 err="peer connected on snap without compatible eth support"

**Comment by weiihann** [comment]
That's an odd issue. Did you start syncing from genesis using v1.3.5, or during the syncing process you've changed the BSC versions?

**Comment by xiaowangba2dai** [comment]
> That's an odd issue. Did you start syncing from genesis using v1.3.5, or during the syncing process you've changed the BSC versions?

No, but it synced normally after I restarted. .
