### ISSUE TITLE
The time for importing blocks on different mainnet nodes unexpectedly increased

### ISSUE THREAD

**Issue by Jony321** [bnb-chain/bsc#2075]
Today the block import time on both my nodes has increased significantly.
One node is located in the USA, the other in Europe, but at the same time they began to lag behind in blocks, without any changes in the OS or software.
Can you help explain this behavior?

Run BSC in docker
cli options
```
            "--",
            "./docker-entrypoint.sh",
            "--http.api",
            "eth,web3,miner,net,admin,personal,debug",
            "--http.addr",
            "0.0.0.0",
            "--http.vhosts=*",
            "--metrics",
            "--ws",
            "--ws.addr",
            "0.0.0.0",
            "--unlock",
            "SomeString",
            "--allow-insecure-unlock",
            "--password",
            "SomePath",
            "--cache",
            "8000",
            "--snapshot=false",
            "--syncmode=full"
```

#### System information

Geth version: `1.2.15`
OS & Version: Linux

#### Expected behaviour

Usual import time
```
t=2023-12-16T17:52:15+0000 elapsed=337.316ms                                                                                           [35/2573]
t=2023-12-16T17:52:18+0000 elapsed=298.673ms                                                                                                    
t=2023-12-16T17:52:21+0000 elapsed=382.911ms                                                                                                    
t=2023-12-16T17:52:24+0000 elapsed=481.358ms                                                                                                    
t=2023-12-16T17:52:28+0000 elapsed=1.019s                                                                                                       
t=2023-12-16T17:52:33+0000 elapsed=2.082s                                                                                                       
t=2023-12-16T17:52:33+0000 elapsed=579.089ms                                                                                                    
t=2023-12-16T17:52:36+0000 elapsed=207.783ms                                                                                                    
t=2023-12-16T17:52:39+0000 elapsed=426.771ms                                                                                                    
t=2023-12-16T17:52:42+0000 elapsed=277.077ms                                                                                                    
t=2023-12-16T17:52:45+0000 elapsed=242.773ms 
```

#### Actual behaviour
Then
```
t=2023-12-16T18:00:01+0000 elapsed=8.060s 
t=2023-12-16T18:00:09+0000 elapsed=8.176s 
t=2023-12-16T18:00:17+0000 elapsed=8.043s 
t=2023-12-16T18:00:25+0000 elapsed=7.618s 
t=2023-12-16T18:00:25+0000 elapsed=1.323ms
t=2023-12-16T18:00:25+0000 elapsed=12.359ms
t=2023-12-16T18:00:25+0000 elapsed=9.010ms
t=2023-12-16T18:00:34+0000 elapsed=8.710s 
t=2023-12-16T18:00:42+0000 elapsed=8.026s   
t=2023-12-16T18:00:50+0000 elapsed=8.132s
```

a little later and so far
```
t=2023-12-16T18:28:50+0000 elapsed=35.167s
t=2023-12-16T18:29:26+0000 elapsed=35.725s
t=2023-12-16T18:29:34+0000 elapsed=8.013s 
t=2023-12-16T18:29:42+0000 elapsed=8.093s 
t=2023-12-16T18:30:16+0000 elapsed=34.310s
t=2023-12-16T18:30:54+0000 elapsed=37.961s
t=2023-12-16T18:31:30+0000 elapsed=35.927s
t=2023-12-16T18:32:06+0000 elapsed=35.930s
t=2023-12-16T18:32:48+0000 elapsed=42.040s
t=2023-12-16T18:33:23+0000 elapsed=34.738s
t=2023-12-16T18:33:58+0000 elapsed=34.579s
t=2023-12-16T18:34:35+0000 elapsed=37.288s
t=2023-12-16T18:35:11+0000 elapsed=36.219s
t=2023-12-16T18:35:49+0000 elapsed=37.675s
```

#### Steps to reproduce the behaviour
There are no changes that can be repeated

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by zzzckck** [comment]
Could you provide information?
1.Node's HW configure: CPU, Mem, Disk
2.The block height numbers that take large time to import.

**Comment by Jony321** [comment]
@zzzckck 
Sure. I have QEMU VM
1. CPU - 32 threads  of `Intel(R) Xeon(R) Gold 6230R CPU @ 2.10GHz`
2. Mem - 64 gb
3. Disk - samsung nvme (I can't tell you the model right now.)
Here are the specifications from the official website that I still have
```
Capacity      15.36 TB
Sequential Read    2100 MB/s
Sequential Write  1800 MB/s
Random Read      400K IOPS
Random Write    65K IOPS
```

**Comment by huangyisan** [comment]
My node, upgrade to v1.3.6, face the same issue, it is takes a long time.
------------
 number=34,323,359 hash=0x402c13bb880dddc8b4b1b54ac292ac48705962090bfab3271bc5823c7dce2922
t=2023-12-17T00:57:02+0000 lvl=info msg="Imported new chain segment"           number=34,413,360 hash=0x01da0c9ffa79e125c62c0cd7521bed841fc5d6e0a19a5b7140ef6222f218ef03 miner=0x72b61c6014342d914470eC7aC2975bE345796c2b blocks=5  txs=569  mgas=121.506 elapsed=32.751s   mgasps=3.710  age=4h51m56s triedirty="643.27 MiB"
t=2023-12-17T00:57:35+0000 lvl=info msg="Imported new chain segment"           number=34,413,361 hash=0xff4cbde105ee294e06c47def95e56372964145d928b9a4fe6caae52998d05c5b miner=0x8b6C8fd93d6F4CeA42Bbb345DBc6F0DFdb5bEc73 blocks=1  txs=167  mgas=80.864  elapsed=33.105s   mgasps=2.443  age=4h52m26s triedirty="603.56 MiB"
t=2023-12-17T00:58:00+0000 lvl=info msg="Deep froze chain segment"             blocks=3  elapsed=10.244ms  number=34,323,362 hash=0x2e65db023b860dc88f77a5fe3b2590573c78e0867fb6f18afcc13cc1784491c1
t=2023-12-17T00:58:06+0000 lvl=info msg="Imported new chain segment"           number=34,413,363 hash=0xe5518702f076294ac5c24552a074cbb085079da2c08de22253311b5bb5ab05a4 miner=0xb218C5D6aF1F979aC42BC68d98A5A0D796C6aB01 blocks=2  txs=256  mgas=88.501  elapsed=31.161s   mgasps=2.840  age=4h52m50s triedirty="615.62 MiB"
t=2023-12-17T00:58:39+0000 lvl=info msg="Imported new chain segment"           number=34,413,369 hash=0x6c455a7f13dbed332b884383cc031fecc5b4a159df1c0020046d878161ae4228 miner=0xea0A6E3c511bbD10f4519EcE37Dc24887e11b55d blocks=6  txs=777  mgas=139.891 elapsed=32.888s   mgasps=4.253  age=4h52m59s triedirty="629.44 MiB"
t=2023-12-17T00:59:00+0000 lvl=info msg="Deep froze chain segment"             blocks=7  elapsed=20.764ms  number=34,323,369 hash=0x6f46ba1039fb5102de055153d6c1da9d553633a846fb30ee5de8301dbec7986a
t=2023-12-17T00:59:10+0000 lvl=info msg="Imported new chain segment"           number=34,413,370 hash=0x44344647d90ca35cb0af1281c7b8fd54e1298f5d76c7544885953eed5274070f miner=0xee226379dB83CfFC681495730c11fDDE79BA4c0C blocks=1  txs=179  mgas=78.158  elapsed=31.561s   mgasps=2.476  age=4h53m27s triedirty="639.86 MiB"
t=2023-12-17T01:00:00+0000 lvl=info msg="Deep froze chain segment"             blocks=3  elapsed=6.399ms   number=34,323,372 hash=0x6783695e5cd4706d6d38e467ad93714408b81106b8af323228f430e0a65f939b
-----------------


before upgrade, it was v1.3.5, and it can reach the highest block number.
-----------------

aws ec2:
ec2 type: r6g.2xlarge
storage :  2T gp2

**Comment by wdstorer-bg** [comment]
Same thing happened to us today. We were on `v1.3.5` and our `Imported new chain segment`  logs went from `elapsed=388.870ms` to `elapsed=58.093s`. This started at around 18:00  UTC and hasn't improved.

**Comment by GalaIO** [comment]
> @zzzckck Sure. I have QEMU VM
> 
> 1. CPU - 32 threads  of `Intel(R) Xeon(R) Gold 6230R CPU @ 2.10GHz`
> 2. Mem - 64 gb
> 3. Disk - samsung nvme (I can't tell you the model right now.)
>    Here are the specifications from the official website that I still have
> 
> ```
> Capacity      15.36 TB
> Sequential Read    2100 MB/s
> Sequential Write  1800 MB/s
> Random Read      400K IOPS
> Random Write    65K IOPS
> ```
> 
> And a part of log with block number and elapsed time
> 
> ```
> t=2023-12-17T01:36:36+0000 lvl=info msg="Deep froze chain segment"              blocks=6   elapsed=12.766ms  number=34,325,543 hash=0xcf319aca07b00d86b95985b1f4f8caa1f8f35e2570d3af308d19ec9928103c40
> t=2023-12-17T01:36:58+0000 lvl=info msg="Imported new chain segment"            blocks=3   txs=303  mgas=95.607  elapsed=36.908s   mgasps=2.590  number=34,415,544 hash=0xa97f65254f23bb0d8e1f3b7e5a94cb5cc8695fe6ae9070d6d13f46bf118e9564 age=3h37m22s dirty="511.19 MiB"
> t=2023-12-17T01:37:31+0000 lvl=info msg="Imported new chain segment"            blocks=1   txs=89   mgas=73.291  elapsed=33.642s   mgasps=2.179  number=34,415,545 hash=0xc9d2cd9844cbc6c559cce87a23ccae177bb2fd23151bc57a348683acbb21979c age=3h37m52s dirty="521.54 MiB"
> t=2023-12-17T01:37:32+0000 lvl=info msg="Persisted trie from memory database"   nodes=15142   size="5.36 MiB"   time=261.848935ms gcnodes=4807    gcsize="2.00 MiB"   gctime=40.142403ms  livenodes=1,135,103 livesize="411.65 MiB"
> t=2023-12-17T01:37:36+0000 lvl=info msg="Deep froze chain segment"              blocks=12  elapsed=13.762ms  number=34,325,555 hash=0xa9630e7db1ff2883d1e62c8b653e1200b294d95ca6b002716111a44ddafa847b
> t=2023-12-17T01:38:12+0000 lvl=info msg="Imported new chain segment"            blocks=12  txs=1420 mgas=188.435 elapsed=40.166s   mgasps=4.691  number=34,415,557 hash=0x571ad7845885c6c492cbca6a0ff9ceeb1ce89f89971358b2f8e402f93c430764 age=3h37m57s dirty="534.58 MiB"
> t=2023-12-17T01:38:36+0000 lvl=info msg="Deep froze chain segment"              blocks=2   elapsed=13.745ms  number=34,325,557 hash=0xa819a6c99f525e4d9ffa0ce05c2ff851356ea5913b653e2938ed884cd20f15b2
> t=2023-12-17T01:38:46+0000 lvl=info msg="Imported new chain segment"            blocks=1   txs=103  mgas=71.843  elapsed=34.690s   mgasps=2.071  number=34,415,558 hash=0x241529ce696123e3390df82fdacc635697759dbd87a7f6943ea98856a547cf5a age=3h38m28s dirty="544.71 MiB"
> t=2023-12-17T01:39:22+0000 lvl=info msg="Imported new chain segment"            blocks=4   txs=428  mgas=99.486  elapsed=35.694s   mgasps=2.787  number=34,415,562 hash=0xf6c5c0a3b65dd998ec744d1e60e47011f026352b715b4e49fe979f6dac69eaf7 age=3h38m52s dirty="549.98 MiB"
> t=2023-12-17T01:39:24+0000 lvl=info msg="Persisted trie from memory database"   nodes=124,675 size="42.27 MiB"  time=2.291335257s gcnodes=27195   gcsize="12.70 MiB"  gctime=254.562227ms livenodes=1,090,591 livesize="395.68 MiB"
> t=2023-12-17T01:39:36+0000 lvl=info msg="Deep froze chain segment"              blocks=7   elapsed=13.265ms  number=34,325,564 hash=0x4d7618626bed6a66529e75f92ebf0c2e92b70933d86037451bd060fa225dd6d8
> t=2023-12-17T01:40:00+0000 lvl=info msg="Imported new chain segment"            blocks=3   txs=292  mgas=88.147  elapsed=37.659s   mgasps=2.341  number=34,415,565 hash=0xe7c12d4aa3f38d8c373466d4429c6d771ac4af0b989d2a6b0fe0a133d4ffae98 age=3h39m21s dirty="508.33 MiB"
> t=2023-12-17T01:40:33+0000 lvl=info msg="Imported new chain segment"            blocks=1   txs=68   mgas=74.126  elapsed=33.040s   mgasps=2.243  number=34,415,566 hash=0x8e0ebb38f6b2ad0a29598bac92dde9953f05d942ada45835cfa9260617f6a675 age=3h39m51s dirty="518.45 MiB"
> t=2023-12-17T01:40:36+0000 lvl=info msg="Deep froze chain segment"              blocks=7   elapsed=18.126ms  number=34,325,571 hash=0xb989b1d923320a0c1d962cb9de9f83122b8b50caafa025cecf4ea78f7aded5c1
> t=2023-12-17T01:41:10+0000 lvl=info msg="Imported new chain segment"            blocks=6   txs=629  mgas=119.699 elapsed=37.216s   mgasps=3.216  number=34,415,572 hash=0xa46e2bec839b2c27fdb488b2045c9570d6443b5722663d2f07c1f6ad2d34955f age=3h40m10s dirty="530.11 MiB"
> t=2023-12-17T01:41:11+0000 lvl=info msg="Persisted trie from memory database"   nodes=61482   size="21.52 MiB"  time=1.042164608s gcnodes=11020   gcsize="4.73 MiB"   gctime=89.769541ms  livenodes=1,104,249 livesize="400.68 MiB"
> ```

Your machine is good enough, it's unusual to see that low performance. Could you provide the CPU profile the next time? You can fetch from the below command:
```bash
go tool pprof -proto -output $(date +"%Y%m%d_%H%M")_pprof_cpu_$(hostname).pb.gz -seconds 300 http://127.0.0.1:6060/debug/pprof/profile
```

By the way, we also found the node costs more time in the Import phase, It may up to 15s to import a block at around 12/16 20:00 UTC & 12/16 22:00 UTC, it runs with 8C64G 4T gp3 Disk, geth v1.2.15. Up to 9s with  8C64G 4T gp3 Disk, geth v1.3.4. Up to 3s with 16C64G 7T Local DIsk, geth v1.3.4.

**Comment by huangyisan** [comment]
> My node, upgrade to v1.3.6, face the same issue, it is takes a long time.
> 
> logs: number=34,323,359 hash=0x402c13bb880dddc8b4b1b54ac292ac48705962090bfab3271bc5823c7dce2922 t=2023-12-17T00:57:02+0000 lvl=info msg="Imported new chain segment" number=34,413,360 hash=0x01da0c9ffa79e125c62c0cd7521bed841fc5d6e0a19a5b7140ef6222f218ef03 miner=0x72b61c6014342d914470eC7aC2975bE345796c2b blocks=5 txs=569 mgas=121.506 elapsed=32.751s mgasps=3.710 age=4h51m56s triedirty="643.27 MiB" t=2023-12-17T00:57:35+0000 lvl=info msg="Imported new chain segment" number=34,413,361 hash=0xff4cbde105ee294e06c47def95e56372964145d928b9a4fe6caae52998d05c5b miner=0x8b6C8fd93d6F4CeA42Bbb345DBc6F0DFdb5bEc73 blocks=1 txs=167 mgas=80.864 elapsed=33.105s mgasps=2.443 age=4h52m26s triedirty="603.56 MiB" t=2023-12-17T00:58:00+0000 lvl=info msg="Deep froze chain segment" blocks=3 elapsed=10.244ms number=34,323,362 hash=0x2e65db023b860dc88f77a5fe3b2590573c78e0867fb6f18afcc13cc1784491c1 t=2023-12-17T00:58:06+0000 lvl=info msg="Imported new chain segment" number=34,413,363 hash=0xe5518702f076294ac5c24552a074cbb085079da2c08de22253311b5bb5ab05a4 miner=0xb218C5D6aF1F979aC42BC68d98A5A0D796C6aB01 blocks=2 txs=256 mgas=88.501 elapsed=31.161s mgasps=2.840 age=4h52m50s triedirty="615.62 MiB" t=2023-12-17T00:58:39+0000 lvl=info msg="Imported new chain segment" number=34,413,369 hash=0x6c455a7f13dbed332b884383cc031fecc5b4a159df1c0020046d878161ae4228 miner=0xea0A6E3c511bbD10f4519EcE37Dc24887e11b55d blocks=6 txs=777 mgas=139.891 elapsed=32.888s mgasps=4.253 age=4h52m59s triedirty="629.44 MiB" t=2023-12-17T00:59:00+0000 lvl=info msg="Deep froze chain segment" blocks=7 elapsed=20.764ms number=34,323,369 hash=0x6f46ba1039fb5102de055153d6c1da9d553633a846fb30ee5de8301dbec7986a t=2023-12-17T00:59:10+0000 lvl=info msg="Imported new chain segment" number=34,413,370 hash=0x44344647d90ca35cb0af1281c7b8fd54e1298f5d76c7544885953eed5274070f miner=0xee226379dB83CfFC681495730c11fDDE79BA4c0C blocks=1 txs=179 mgas=78.158 elapsed=31.561s mgasps=2.476 age=4h53m27s triedirty="639.86 MiB" t=2023-12-17T01:00:00+0000 lvl=info msg="Deep froze chain segment" blocks=3 elapsed=6.399ms number=34,323,372 hash=0x6783695e5cd4706d6d38e467ad93714408b81106b8af323228f430e0a65f939b
> 
> before upgrade, it was v1.3.5, and it can reach the highest block number.
> 
> aws ec2: ec2 type: r6g.2xlarge storage : 2T gp2

My node had fetch the last block two days ago, and work well now.
