### ISSUE TITLE
Errors in logs after updating testnet from 1.2.15 to .1.3.6

### ISSUE THREAD

**Issue by Jony321** [bnb-chain/bsc#2076]
There are errors in the logs after updating the node to 1.3.6 and switching to PBSS. The logs confuse me because... there are imports of new blocks, but it looks like the node is not working.
Can you help diagnose the problem?
I want to test the transition to the new version on the testnet before migrating the main nodes.

#### System information

Geth version: `v1.3.6`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
Logs without errors

#### Actual behaviour
Errors and Imports together
```
t=2023-12-17T00:00:02+0000 lvl=info msg="Imported new chain segment"             number=36,020,637 hash=0xdfa226dc4fc064fb1cbe3ba6ccc79c8f807e305135cd0ab8e3efd48bdbbf78ec miner=0x96C5D20b2a975c050e4220BE276ACe4892f4b41A blocks=1   txs=5    mgas=0.430   elapsed=10.716ms  mgasps=40.097  triediffs="5.73 MiB" triedirty="123.89 MiB" trieimutabledirty="0.00 B"
t=2023-12-17T00:00:02+0000 lvl=warn msg="Snapshot extension registration failed" peer=6a48c1ef err="peer connected on snap without compatible eth support"
t=2023-12-17T00:00:03+0000 lvl=warn msg="Snapshot extension registration failed" peer=582e6698 err="peer connected on snap without compatible eth support"
t=2023-12-17T00:00:04+0000 lvl=warn msg="Snapshot extension registration failed" peer=58b0fbcf err="peer connected on snap without compatible eth support"
t=2023-12-17T00:00:05+0000 lvl=info msg="Imported new chain segment"             number=36,020,638 hash=0x208326e53bda18478817b879ee976958d12c8217099731599836d0c4891366c2 miner=0x980A75eCd1309eA12fa2ED87A8744fBfc9b863D5 blocks=1   txs=11   mgas=0.726   elapsed=17.031ms  mgasps=42.639  triediffs="5.79 MiB" triedirty="123.89 MiB" trieimutabledirty="0.00 B"
t=2023-12-17T00:00:07+0000 lvl=info msg="Imported new chain segment"             number=36,020,639 hash=0xa3def4ccdeaea86a9a2ee3d69d9461d27552fb6da107a3a44c5e33122d5f05b2 miner=0xA2959D3F95eAe5dC7D70144Ce1b73b403b7EB6E0 blocks=1   txs=10   mgas=1.385   elapsed=32.258ms  mgasps=42.936  triediffs="5.90 MiB" triedirty="123.89 MiB" trieimutabledirty="0.00 B"

```
#### Steps to reproduce the behaviour
Download snapshot from [there](https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-testnet-pbss-pebble-20231215.tar.lz4), like described [there](https://forum.bnbchain.org/t/faq-pbss-pebbledb/2260#q3-how-to-try-pbss-pebbledb-7)

```
docker stop bsc
mv /data/bsc/node/geth /data/backup/geth_hbss_leveldb_16.12.23.bak # Store old node
mv /data/snapshot/server/testnet/node/geth /data/bsc/node/geth # Put new node from snapshot
```
Then I deployed the BSC image with geth 1.3.6 and added the options `--state.scheme path --db.engine pebble`

All options
```
        "Args": [
            "--",
            "./docker-entrypoint.sh",
            "--http.api",
            "eth,web3,miner,net,admin,personal,debug",
            "--http.addr",
            "0.0.0.0",
            "--http.vhosts=*",
            "--metrics",
            "--ws",
            "--ws.addr",
            "0.0.0.0",
            "--unlock",
            "[SomeString]",
            "--allow-insecure-unlock",
            "--password",
            "[SomePath]",
            "--state.scheme",
            "path",
            "--db.engine",
            "pebble"
        ],

```

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by CocoStarZ** [comment]
Could you pls try restarting it and see if it works? A known issue has been found for the first time upgrade: https://github.com/bnb-chain/bsc/issues/2071

**Comment by Jony321** [comment]
@CocoStarZ 
Restarting the container with bsc does not help.

@buddh0 
Ok, thanks for the clarification.
I expect that after switching to the path schema, these messages will disappear or decrease.

Thank you all for your help and responsiveness, I’m closing the ticket because... no problem.
