### ISSUE TITLE
########## BAD BLOCK ######### on mainnet, after upgrading v1.2.9 -> v1.2.15.

### ISSUE THREAD

**Issue by johnnyji-dev** [bnb-chain/bsc#2077]
![image](https://github.com/bnb-chain/bsc/assets/125259310/59695d5c-8e4d-4d0c-9f95-80e7b06ec5b4)

```########## BAD BLOCK #########
Chain config: {ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Berlin: 31302048, YOLO v3: <nil>, CatalystBlock: <nil>, London: 31302048, ArrowGlacier: <nil>, MergeFork:<nil>, Euler: 18907621, Gibbs: 23846001, Nano: 21962149, Moran: 22107423, Planck: 27281024,Luban: 29020050, Plato: 30720096, Hertz: 31302048, Engine: parlia}

Number: 34,440,490

Error: could not apply tx 0 [0x931...f8d]: nonce too high: address 0x4693772e8b2Bb8BB62060383d977399ccfEf518D, tx: 844 state: 0
##############################

Q) How can I fix it? Is it need to reinstall with snapshot?

**Comment by johnnyji-dev** [comment]
![geth command](https://github.com/bnb-chain/bsc/assets/125259310/a515a399-6f7d-48a3-b42f-3b64168e2504)
I got a "BAD BLOCK" issue running above command.

After removing --diffsync and --pruneancient=true and then revert block like below link(I additionally deleted --pruneancient")
https://github.com/bnb-chain/bsc/issues/1037#issuecomment-1200826973

![geth command2](https://github.com/bnb-chain/bsc/assets/125259310/5d65346e-c28d-4ad1-9b32-b0df3bfb27c3)

"BAD BLOCK" disappeared, but still need to sync(State sync in progress) !!
![image](https://github.com/bnb-chain/bsc/assets/125259310/2093ddab-9815-4292-bc60-00ae32334177)

I'm worried that I need to enough time to syncing and than someone got a stuck syncing and than not syncing after long time.

Is there any problem on get command and log file?

**Comment by NathanBSC** [comment]
Chain config: {ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Berlin: 31302048, YOLO v3: <nil>, CatalystBlock: <nil>, London: 31302048, ArrowGlacier: <nil>, MergeFork:<nil>, Euler: 18907621, Gibbs: 23846001, Nano: 21962149, Moran: 22107423, Planck: 27281024,Luban: 29020050, Plato: 30720096, Hertz: 31302048, Engine: parlia}

It's strange that there is no HertzFix hardfork configured.
can you double check it?

**Comment by zzzckck** [comment]
Did you run in fast node mode?

**Comment by johnnyji-dev** [comment]
> Did you run in fast node mode?

No, syncmode=full

**Comment by buddh0** [comment]
suggest to use the newest version v1.3.7 to run again

**Comment by buddh0** [comment]
several days passed and no more infomation, I close this issue for now.
if you run v1.3.7 and encounter same issue, file new an issue then

**Comment by johnnyji-dev** [comment]
> several days passed and no more infomation, I close this issue for now. if you run v1.3.7 and encounter same issue, file new an issue then

After changing to v1.3.6, I succeed to install bsc-node. thx~
