### ISSUE TITLE
fast node这么升级到v1.3.6，并使用PBSS 和 PBSS Pebble数据库。

### ISSUE THREAD

**Issue by FerdyCai** [bnb-chain/bsc#2081]
当前我的节点运行的是快速节点 --tries-verify-mode none，版本是1.3.4，现在看到1.3.5版里面说到“BSC 将逐步切换至PBSS + PebbleDB模式”，请问当前我的v1.3.4的快速节点要怎么升级成为PBSS + PebbleDB模式的最新版本（v1.3.6）？

**Comment by sysvm** [comment]
You can download PBSS+PebbleDB snapshot from [Path-Base-State-Scheme](https://github.com/bnb-chain/bsc-snapshots?tab=readme-ov-file#endpoint). And set `--state.scheme path` when starting your node.

**Comment by FerdyCai** [comment]
@sysvm 请问v1.3.5的PBSS+PebbleDB快照 可以使用 ./geth snapshot insecure-prune-all --datadir ./node  ./genesis.json 来裁剪数据吗？

**Comment by zzzckck** [comment]
> @sysvm 请问PBSS+PebbleDB快照 可以使用 ./geth snapshot insecure-prune-all --datadir ./node ./genesis.json 来裁剪数据吗？ 使用上面的命令裁剪数据之后启动程序： nohup ./geth --tries-verify-mode none --config ./config.toml --datadir ./node --state.scheme path --cache 8000 --rpc.allow-unprotected-txs --history.transactions 0 --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.api eth,net,web3,txpool --http.vhosts=* >./console.log 2>&1 & 无法启动，日志如下： INFO [12-20|23:23:47.914] Starting Geth on BSC mainnet... INFO [12-20|23:23:47.917] Maximum peer count ETH=200 LES=0 total=200 INFO [12-20|23:23:47.918] Smartcard socket not found, disabling err="stat /run/pcscd/pcscd.comm: no such file or directory" Fatal: incompatible state scheme, stored: path, config: hash, CLI: path
> 
> 这是为什么呢？

https://forum.bnbchain.org/t/faq-pbss-pebbledb/2260
<img width="737" alt="image" src="https://github.com/bnb-chain/bsc/assets/152148891/98de0a46-0ecf-475c-a24e-50d2d9211429">
did you update the config.toml?

**Comment by FerdyCai** [comment]
@zzzckck It's work.
