### ISSUE TITLE
v1.3.7,Fatal: Could not open database: MemTableSize (4.0GB) must be < 4.0GB

### ISSUE THREAD

**Issue by niocm** [bnb-chain/bsc#2091]
#### System information

Geth
Version: 1.3.7
Git Commit: f28b98a9947b52816714f90326b2545b08606b1a
Git Commit Date: 20231219
Architecture: amd64
Go Version: go1.20.2
Operating System: linux

#### Expected behaviour
Running below command：
`geth --config ./config.toml --datadir ./node  --cache 51200 --rpc.allow-unprotected-txs --history.transactions=0 --syncmode=full --tries-verify-mode=local --pruneancient --db.engine=pebble --rpc.txfeecap 0 --rpc.gascap 0`

#### Actual behaviour

```
root@Ubuntu-2204-jammy-amd64-base /jiedian/bsc # geth --config ./config.toml --datadir ./node  --cache 86016 --rpc.allow-unprotected-txs --history.transactions=0 --syncmode=full --tries-verify-mode=local --pruneancient --db.engine=pebble --rpc.txfeecap 0 --rpc.gascap 0
INFO [12-19|15:25:12.298] Starting Geth on BSC mainnet...
INFO [12-19|15:25:12.299] Maximum peer count                       ETH=200 LES=0 total=200
INFO [12-19|15:25:12.300] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [12-19|15:25:12.300] Using pebble as db engine
Fatal: Could not open database: MemTableSize (4.0GB) must be < 4.0GB
```

#### Steps to reproduce the behaviour

When submitting logs: please submit them as text and not screenshots.

**Comment by serfiraz21** [comment]
remove `--cache` flag or reduce to under 4gib

**Comment by flywukong** [comment]
Please lower you cache setting -cache to run . The issue is cause by the upstream pebble. we will  have a temp fix on it.
