### ISSUE TITLE
v1.3.7 Fatal: incompatible state scheme, stored: path, config: hash, CLI: path

### ISSUE THREAD

**Issue by marsbible** [bnb-chain/bsc#2092]
After download geth-pbss-pebble-20231210.tar.lz4 and run in path mode with v1.3.7, it always reports 'Fatal: incompatible state scheme, stored: path, config: hash, CLI: path', v1.3.6 works well.

#### System information

Geth version: v1.3.7
OS & Version: Linux
Commit hash : 

#### Expected behaviour
FullNode could sync data normally.

#### Actual behaviour
Fatal error.

#### Steps to reproduce the behaviour
Download geth-pbss-pebble-20231210.tar.lz4 and run in path mode with v1.3.7

#### Backtrace

When submitting logs: please submit them as text and not screenshots.

**Comment by sysvm** [comment]
You can add this config your config.toml:
```toml
[Eth]
StateScheme = "path"
```
This problem will be fixed in next release.

**Comment by 0xbundler** [comment]
Hi, I also found `db compact` return this err.
```bash
INFO [12-22|03:18:58.152] Maximum peer count                       ETH=50 LES=0 total=50
INFO [12-22|03:18:58.155] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [12-22|03:18:58.157] Using deprecated resource file, please move this file to the 'geth' subdirectory of datadir. file=/server/state-sharding/node/server/data-seed/nodekey
INFO [12-22|03:18:58.178] Using pebble as the backing database 
INFO [12-22|03:18:58.179] Allocated cache and file handles         database=/server/state-sharding/node/server/data-seed/chaindata cache=409.00MiB handles=4096 "memory table"=102.25MiB
INFO [12-22|03:19:04.119] Opened ancient database                  database=/server/state-sharding/node/server/data-seed/chaindata/ancient/chain readonly=true frozen=34,145,593
Fatal: incompatible state scheme, stored: path, config: hash
```

`db compact` cannot start with flag `--state.scheme path`, there are also many tools not include this flag. It seems a strict check with stored vs config.toml vs flags? Could you help to resolve it?

**Comment by yzhaoyu** [comment]
> Hi, I also found `db compact` return this err.
> 
> ```shell
> INFO [12-22|03:18:58.152] Maximum peer count                       ETH=50 LES=0 total=50
> INFO [12-22|03:18:58.155] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
> WARN [12-22|03:18:58.157] Using deprecated resource file, please move this file to the 'geth' subdirectory of datadir. file=/server/state-sharding/node/server/data-seed/nodekey
> INFO [12-22|03:18:58.178] Using pebble as the backing database 
> INFO [12-22|03:18:58.179] Allocated cache and file handles         database=/server/state-sharding/node/server/data-seed/chaindata cache=409.00MiB handles=4096 "memory table"=102.25MiB
> INFO [12-22|03:19:04.119] Opened ancient database                  database=/server/state-sharding/node/server/data-seed/chaindata/ancient/chain readonly=true frozen=34,145,593
> Fatal: incompatible state scheme, stored: path, config: hash
> ```
> 
> `db compact` cannot start with flag `--state.scheme path`, there are also many tools not include this flag. It seems a strict check with stored vs config.toml vs flags? Could you help to resolve it?
> 
> By the way, It's ok in v1.3.6 to compact PBSS data.

config.toml contains a default value: hash, so you should specify `StateScheme = "path"` in config.toml. I'll remove this default value in next release.

**Comment by sysvm** [comment]
> Hi, I also found `db compact` return this err.
> 
> ```shell
> INFO [12-22|03:18:58.152] Maximum peer count                       ETH=50 LES=0 total=50
> INFO [12-22|03:18:58.155] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
> WARN [12-22|03:18:58.157] Using deprecated resource file, please move this file to the 'geth' subdirectory of datadir. file=/server/state-sharding/node/server/data-seed/nodekey
> INFO [12-22|03:18:58.178] Using pebble as the backing database 
> INFO [12-22|03:18:58.179] Allocated cache and file handles         database=/server/state-sharding/node/server/data-seed/chaindata cache=409.00MiB handles=4096 "memory table"=102.25MiB
> INFO [12-22|03:19:04.119] Opened ancient database                  database=/server/state-sharding/node/server/data-seed/chaindata/ancient/chain readonly=true frozen=34,145,593
> Fatal: incompatible state scheme, stored: path, config: hash
> ```
> 
> `db compact` cannot start with flag `--state.scheme path`, there are also many tools not include this flag. It seems a strict check with stored vs config.toml vs flags? Could you help to resolve it?
> 
> By the way, It's ok in v1.3.6 to compact PBSS data.

config.toml contains a default value: hash, so you should specify StateScheme = "path" in config.toml. I'll remove this default value in next release.

**Comment by 0xbundler** [comment]
> > Hi, I also found `db compact` return this err.
> > ```shell
> > INFO [12-22|03:18:58.152] Maximum peer count                       ETH=50 LES=0 total=50
> > INFO [12-22|03:18:58.155] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
> > WARN [12-22|03:18:58.157] Using deprecated resource file, please move this file to the 'geth' subdirectory of datadir. file=/server/state-sharding/node/server/data-seed/nodekey
> > INFO [12-22|03:18:58.178] Using pebble as the backing database 
> > INFO [12-22|03:18:58.179] Allocated cache and file handles         database=/server/state-sharding/node/server/data-seed/chaindata cache=409.00MiB handles=4096 "memory table"=102.25MiB
> > INFO [12-22|03:19:04.119] Opened ancient database                  database=/server/state-sharding/node/server/data-seed/chaindata/ancient/chain readonly=true frozen=34,145,593
> > Fatal: incompatible state scheme, stored: path, config: hash
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `db compact` cannot start with flag `--state.scheme path`, there are also many tools not include this flag. It seems a strict check with stored vs config.toml vs flags? Could you help to resolve it?
> > By the way, It's ok in v1.3.6 to compact PBSS data.
> 
> config.toml contains a default value: hash, so you should specify `StateScheme = "path"` in config.toml. I'll remove this default value in next release.

I had tried it, but got below error.
```bash
Incorrect Usage: flag provided but not defined: -config

NAME:
   geth db compact - Compact leveldb database. WARNING: May take a very long time

USAGE:
   geth db compact command [command options] [arguments...]

DESCRIPTION:
   This command performs a database compaction.
   WARNING: This operation may take a very long time to finish, and may cause database
   corruption if it is aborted during execution'!
....
```

**Comment by sysvm** [comment]
Try this command: `./geth  --config ./config.toml db compact`

**Comment by sysvm** [comment]
Please see [2107](https://github.com/bnb-chain/bsc/pull/2107) to know how to use `StateScheme` in `CLI`, `config` and `db meta`.
