### ISSUE TITLE
can't start bsc - Fatal: Could not open database: open /srv/bsc/geth/chaindata/ancient/chain/bodies.cidx: no such file or directory

### ISSUE THREAD

**Issue by rmlcu** [bnb-chain/bsc#2110]
#### System information

bsc-node:~$ sudo /srv/bsc/bsc-geth version
Geth
Version: 1.3.6
Git Commit: 5ee77bbe8bba2f1e9b7bc9368347fd531891ec7e
Git Commit Date: 20231214
Architecture: amd64
Go Version: go1.20.11
Operating System: linux
GOPATH=
GOROOT=/opt/hostedtoolcache/go/1.20.11/x64

bsc-node:~$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian

bsc-node:~$ sudo cat /etc/systemd/system/bsc-geth.service
[Unit]
Description=bsc geth go client
After=syslog.target network-online.target

[Service]
User=geth
Group=geth
#Type=simple
ExecStart=/srv/bsc/bsc-geth --config=/srv/bsc/config.toml --datadir=/srv/bsc --nat=extip:1.2.3.4 \
        --history.transactions=5000000 --syncmode=full --tries-verify-mode=none --diffblock=5000 \
        --cache=18000 --rpc.allow-unprotected-txs --db.engine=pebble
#KillMode=process
KillSignal=SIGINT
TimeoutStopSec=90
Restart=on-failure
RestartSec=10s

[Install]
WantedBy=multi-user.target

#### Expected behaviour

node successfully starting

#### Actual behaviour

node is failing to start:
```
-- Boot 6f5a36d8fb0a45ff894b0834f496879c --
Dec 26 17:01:46 bsc-node systemd[1]: Started bsc geth go client.
Dec 26 17:01:47 bsc-node bsc-geth[28939]: INFO [12-26|17:01:47.135] Starting Geth on BSC mainnet...
Dec 26 17:01:47 bsc-node bsc-geth[28939]: WARN [12-26|17:01:47.136] Config field is deprecated and won't have an effect name=ethconfig.Config.EWASMInterpreter
Dec 26 17:01:47 bsc-node bsc-geth[28939]: WARN [12-26|17:01:47.139] Config field is deprecated and won't have an effect name=ethconfig.Config.EVMInterpreter
Dec 26 17:01:47 bsc-node bsc-geth[28939]: INFO [12-26|17:01:47.144] Maximum peer count                       ETH=256 LES=0 total=256
Dec 26 17:01:47 bsc-node bsc-geth[28939]: INFO [12-26|17:01:47.150] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
Dec 26 17:01:47 bsc-node bsc-geth[28939]: WARN [12-26|17:01:47.150] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable
Dec 26 17:01:47 bsc-node bsc-geth[28939]: INFO [12-26|17:01:47.150] Using pebble as db engine
Dec 26 17:01:47 bsc-node bsc-geth[28939]: INFO [12-26|17:01:47.833] Using pebble as the backing database
Dec 26 17:01:47 bsc-node bsc-geth[28939]: INFO [12-26|17:01:47.834] Allocated cache and file handles         database=/srv/bsc/geth/chaindata cache=7.03GiB handles=262,144 "memory table"=1.76GiB
Dec 26 17:01:54 bsc-node bsc-geth[28939]: Chain metadata
Dec 26 17:01:54 bsc-node bsc-geth[28939]:   databaseVersion: 8 (0x8)
Dec 26 17:01:54 bsc-node bsc-geth[28939]:   headBlockHash: 0x6130a6f6754de4af55a2dd6d69f996ad53e1f7b7e4b0f598c02e5b331ee6f173
Dec 26 17:01:54 bsc-node bsc-geth[28939]:   headFastBlockHash: 0x6130a6f6754de4af55a2dd6d69f996ad53e1f7b7e4b0f598c02e5b331ee6f173
Dec 26 17:01:54 bsc-node bsc-geth[28939]:   headHeaderHash: 0x6130a6f6754de4af55a2dd6d69f996ad53e1f7b7e4b0f598c02e5b331ee6f173
Dec 26 17:01:54 bsc-node bsc-geth[28939]:   lastPivotNumber: 31706311 (0x1e3ccc7)
Dec 26 17:01:54 bsc-node bsc-geth[28939]:   len(snapshotSyncStatus): 286 bytes
Dec 26 17:01:54 bsc-node bsc-geth[28939]:   snapshotDisabled: false
Dec 26 17:01:54 bsc-node bsc-geth[28939]:   snapshotJournal: 8343476 bytes
Dec 26 17:01:54 bsc-node bsc-geth[28939]:   snapshotRecoveryNumber: 33620042 (0x201004a)
Dec 26 17:01:54 bsc-node bsc-geth[28939]:   snapshotRoot: 0x5b748d890a88bb8d5f714786c72d4e48c3b84b9bb98a4a12c9e2b8e9315bc64d
Dec 26 17:01:54 bsc-node bsc-geth[28939]:   txIndexTail: 29371693 (0x1c02d2d)
Dec 26 17:01:54 bsc-node bsc-geth[28939]:   fastTxLookupLimit: 2350000 (0x23dbb0)
Dec 26 17:01:54 bsc-node bsc-geth[28939]: Fatal: Could not open database: open /srv/bsc/geth/chaindata/ancient/chain/bodies.cidx: no such file or directory
Dec 26 17:01:54 bsc-node systemd[1]: bsc-geth.service: Main process exited, code=exited, status=1/FAILURE
Dec 26 17:01:54 bsc-node systemd[1]: bsc-geth.service: Failed with result 'exit-code'.
Dec 26 17:01:54 bsc-node systemd[1]: bsc-geth.service: Consumed 14.277s CPU time.
```

#### Steps to reproduce the behaviour

download 48club snapshot (https://snapshots.48.club/geth.full.34148567.tar.zst) and move unpacked data into the needed folder

**Comment by web3dev2023** [comment]
I am using the official pbss pebble snapshot. I get the same error if I use `--tries-verify-mode=none` after running with `--pruneancient`
https://github.com/bnb-chain/bsc-snapshots/issues/324#issuecomment-1869634240

**Comment by joeylichang** [comment]
start from a `snapshot`? could you offer the snapshot link?

**Comment by joeylichang** [comment]
use the flag `--history.transactions=0 --syncmode=full --tries-verify-mode=local --pruneancient --db.engine=pebble` try again?

**Comment by joeylichang** [comment]
@rmlcu @web3dev2023 , the snapshot((https://snapshots.48.club/geth.full.34148567.tar.zst)) use the `--pruneancient` flag, it is irreversible, and no ancientdb data, please add `--pruneancient` to try again.

Not related to the ‘--tries-verify-mode’ flag. And we test the cmd can run normal:
``` ./geth --config config.toml --datadir ./geth.full/ --cache 18000 --history.transactions=5000000 --syncmode=full --tries-verify-mode=none --pruneancient --db.engine=pebble --diffblock=5000 --rpc.allow-unprotected-txs ```

It is recommended to use official snapshot data to avoid more similar problems(https://github.com/bnb-chain/bsc-snapshots?tab=readme-ov-file#endpoint)

**Comment by web3dev2023** [comment]
@joeylichang Thanks for the reply!

Using the 3 flags together works for me: `--syncmode=full --pruneancient --tries-verify-mode=none` (`pruneancient` only works on `full` sync mode, while the default sync mode is `snap`)

I think the real problem is, we cannot use `--tries-verify-mode=none` without `--syncmode=full --pruneancient`, which used to work on Hash-Base-State-Scheme snapshots.

**Comment by joeylichang** [comment]
> @joeylichang Thanks for the reply!
> 
> Using the 3 flags together works for me: `--syncmode=full --pruneancient --tries-verify-mode=none` (`pruneancient` only works on `full` sync mode, while the default sync mode is `snap`)
> 
> I think the real problem is, we cannot use `--tries-verify-mode=none` without `--syncmode=full --pruneancient` on a pruned snapshot (`--tries-verify-mode=none` can be used alone if the snapshot is not pruned), which used to work on Hash-Base-State-Scheme snapshots.

I think the snapshot data is the latest data, it is unnecessary to --syncmode=snap(default), the --syncmode=snap is suitable for catching from genesis.

the --pruneancient is a must, because the snapshot is pruned.

**Comment by sysvm** [comment]
@web3dev2023 As you said that you can run geth in a pruned hash base db, so can you provide your `running CLI`, `geth version` and `snapshot version`?
In addition, why you want to run geth without `--pruneancient`?

**Comment by sysvm** [comment]
I use 48club `geth.full.34882141.tar.zst`pruned snapshot to test in hash mode. cli: `nohup ./geth_linux --config config.toml --datadir ./geth.full --history.transactions=0 --syncmode=full --tries-verify-mode=local --diffblock=5000 -rpc.allow-unprotected-txs --db.engine=pebble >> nohup.out 2>&1&`.
The result is `Fatal: Could not open database: open /data/dylan/hbss/geth.full/geth/chaindata/ancient/chain/diffs.ridx: no such file or directory`.

**Comment by rmlcu** [comment]
> @rmlcu @web3dev2023 , the snapshot((https://snapshots.48.club/geth.full.34148567.tar.zst)) use the `--pruneancient` flag, it is irreversible, and no ancientdb data that caused `Fatal: Could not open database: open xxxx/ancient` error, please add `--pruneancient` flag to try again.

hi @joeylichang

isn't it supposed to be not pruned node with name "geth.full.xxx..."?

**Comment by sysvm** [comment]
> > @rmlcu @web3dev2023 , the snapshot((https://snapshots.48.club/geth.full.34148567.tar.zst)) use the `--pruneancient` flag, it is irreversible, and no ancientdb data that caused `Fatal: Could not open database: open xxxx/ancient` error, please add `--pruneancient` flag to try again.
> 
> hi @joeylichang
> 
> isn't it supposed to be not pruned node with name "geth.full.xxx..."?

You can use [this](https://github.com/bnb-chain/bsc-snapshots?tab=readme-ov-file#endpoint). They are not pruned.
