### ISSUE TITLE
the faucets not working, can not get tbnb

### ISSUE THREAD

**Issue by bigwhiterice** [bnb-chain/bsc#2117]
hi bro, i want to make some test at BNB Greenfield testnet,  but can get tbnb from the https://testnet.binance.org/faucet-smart,
what should i  do,  thank you very much for the answer

**Comment by zzzckck** [comment]
it works for me? pls provide more information, what is the your issue?

**Comment by bigwhiterice** [comment]
@zzzckck  
i can`t open the website  https://testnet.binance.org/faucet-smart，is it due to regional restriction?

**Comment by bigwhiterice** [comment]
@zzzckck
the send button is disable，i use MateMask wallet

<img width="759" alt="image" src="https://github.com/bnb-chain/bsc/assets/18457832/c679eb4f-c6c0-4236-ba55-33acbf55a5e8">

can your help me get some tbnb,
my wallet address is 0xF5be7c66cAB8c9ee5913DD500BA2416A8CBe5A1D, 
thank you very much!

**Comment by zzzckck** [comment]
> @zzzckck the send button is disable，i use MateMask wallet
> 
> <img alt="image" width="759" src="https://private-user-images.githubusercontent.com/18457832/293300024-c679eb4f-c6c0-4236-ba55-33acbf55a5e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM4MjQwMDYsIm5iZiI6MTcwMzgyMzcwNiwicGF0aCI6Ii8xODQ1NzgzMi8yOTMzMDAwMjQtYzY3OWViNGYtYzZjMC00MjM2LWJhNTUtMzNhY2JmNTVhNWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDA0MjE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NTFjZTBhY2Q0YmY3MjBjY2U2NTEwNDBiYjU3ZDY1NjI3ODNiOWJlNjU2OGZmN2ZiZjYwZmIyNTRhZDgzODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4ns-LYVemeQeYY4rsEfkiWyw_Y3P4BZFwDfiDiGjaQw">
> can your help me get some tbnb, my wallet address is 0xF5be7c66cAB8c9ee5913DD500BA2416A8CBe5A1D, thank you very much!

<img width="764" alt="image" src="https://github.com/bnb-chain/bsc/assets/152148891/1a0bd947-50ab-4d2e-b7d6-d00c3486b672">
Seems you have claimed within 24hours?

**Comment by zzzckck** [comment]
https://testnet.bnbchain.org/faucet-smart/
Can you try this one?

**Comment by bigwhiterice** [comment]
@zzzckck  it works, thank you very much !
