### ISSUE TITLE
prioritize in propagate transaction

### ISSUE THREAD

**Issue by mohsen158** [bnb-chain/bsc#2125]
How can I ensure that my local transactions are prioritized for immediate propagation to other peers over other transactions, using the latest version of Geth? Additionally, is there a way to filter specific transactions for broadcast and place my transaction at the forefront of the queue?

**Comment by 397368856** [comment]
I don't think anyone will tell you the result

**Comment by weiihann** [comment]
There's no such feature (for now) to prioritize the immediate propagation of local transactions to other peers. However, there's this config parameter called `NoLocals` when disabled, ensures that all local transactions will be included in the node's transaction pool, skipping through the validations steps. This might get close to the idea of "immediate propagation".

To disable NoLocals, simply put `NoLocals = false` in your config.toml file and restart your node.
