### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Lwx7832** [bnb-chain/bsc#2126]
OS & Version: Ubuntu 22.04.3 LTS
GO Version 1.20.12
<img width="368" alt="1704025730908" src="https://github.com/bnb-chain/bsc/assets/22617861/2d0a86c7-d297-4383-9483-2f3247ade247">

I tried to update these two libraries, but compiling again still reported an error
```
go get -u github.com/herumi/bls-eth-go-binary/bls 
go get -u github.com/supranational/blst/bindings/go
```
<img width="569" alt="1704025745541" src="https://github.com/bnb-chain/bsc/assets/22617861/dbeba72b-189b-42b5-824d-5b53096653f1">

But in the same environment, it's normal for me to compile go-ethereum
<img width="527" alt="1704025798900" src="https://github.com/bnb-chain/bsc/assets/22617861/31a33933-6ed3-4c9c-87ea-dfaf83e1e95f">

**Comment by NathanBSC** [comment]
can you try these following [README.md](https://github.com/bnb-chain/bsc/blob/master/README.md)? 
![image](https://github.com/bnb-chain/bsc/assets/122502194/7eca4556-c8f3-47bc-88e0-6ede9cdb3a20)

**Comment by buddh0** [comment]
can you try these following [README.md](https://github.com/bnb-chain/bsc/blob/master/README.md) ?
![image](https://github.com/bnb-chain/bsc/assets/7995985/7af9fd25-f5a4-4432-8a03-a36dd4682113)

**Comment by buddh0** [comment]
have you tried above solution? @Lwx7832 
2 days passed, I will close this issue now, if any question, you can open a new one
