### ISSUE TITLE
Value of gasUsed is different on "eth_getTransactionReceipt" and "debug_traceTransaction"?

### ISSUE THREAD

**Issue by Aracki** [bnb-chain/bsc#2143]
I'm running several binance nodes (bsc 1.3.7 version), but I discovered differences for `gasUsed` value between these two methods.

Transaction with this problem: `0x7eba4edc7c1806d6ee1691d43513838931de5c94f9da56ec865721b402f775b0`.

```
curl --request POST \
  --url http://node-bsc:8545 \
  --header 'Content-Type: application/json' \
  --data '{
	"jsonrpc": "2.0",
	"id": 1,
	"method": "eth_getTransactionReceipt",
	"params": [
		"0x7eba4edc7c1806d6ee1691d43513838931de5c94f9da56ec865721b402f775b0"
	]
}'
```
returns:
```
"gasUsed":"0x1afd3"
```

although, this one:
```
curl --request POST \
  --url http://node-bsc:8545 \
  --header 'Content-Type: application/json' \
  --data '{
	"jsonrpc": "2.0",
	"id": 123,
	"method": "debug_traceTransaction",
	"params": [
		"0x7eba4edc7c1806d6ee1691d43513838931de5c94f9da56ec865721b402f775b0",
		{"tracer": "callTracer"}
	]
}'
```
returns:
```
"gasUsed":"0x412c3"
```

Here are some additional flags used for running nodes:

```
            "--networkid=56",
            "--syncmode=full",
            "--gcmode=archive",
            "--history.transactions=0",
            "--rpc.allow-unprotected-txs",
            "--cache.preimages",    
```

**Comment by deepcrazy** [comment]
Hi there, Can you provide your full geth startup command too? Also, please share the logs by setting log level to `debug`.

**Comment by qybdyx** [comment]
It's know issue of hertzfix. There is no good solution for it, just ignore it.

**Comment by Aracki** [comment]
@deepcrazy Unfortunately, I've lost logs older than 30 days. And block `33851236` happened before ~40days. 

@qybdyx I have to ignore it, but I'm more interested whether the unwind would help potentially? Or downloading some old archive snapshot?

**Comment by zzzckck** [comment]
> @deepcrazy Unfortunately, I've lost logs older than 30 days. And block `33851236` happened before ~40days.
> 
> @qybdyx I have to ignore it, but I'm more interested whether the unwind would help potentially? Or downloading some old archive snapshot?

unwind will not help, neither download old archive snapshot. Actually, it is a bug that makes RPC call's result different from on chain, which is quite a corner case that trigger by this transaction.
It has been fixed after hertzFix, but before hertzFix, we have no good solution but add a hotfix patch for RPC call.

**Comment by brilliant-lx** [comment]
About the hertzFix: https://forum.bnbchain.org/t/about-the-hertzfix/2400

**Comment by Aracki** [comment]
Thanks for explanation!
