### ISSUE TITLE
Fast Sync not finish, can't enable pruneancient mode

### ISSUE THREAD

**Issue by printhellow** [bnb-chain/bsc#2146]
geth --config ./config.toml --datadir ./node --cache 8000 --maxpendpeers 400 --rpc.allow-unprotected-txs --snapshot=true --txlookuplimit 0 --history.transactions=0 --syncmode=full --tries-verify-mode=local --pruneancient --db.engine=pebble

**Comment by printhellow** [comment]
error log:
t=2024-01-10T08:53:35+0800 lvl=warn msg="Sanitizing invalid txpool lifetime"    provided=0s updated=3h0m0s
t=2024-01-10T08:53:35+0800 lvl=warn msg="Sanitizing invalid txpool reannounce time" provided=0s updated=1m0s
t=2024-01-10T08:53:35+0800 lvl=info msg="Initialized transaction indexer"       limit=0
t=2024-01-10T08:53:35+0800 lvl=crit msg="Fast Sync not finish, can't enable pruneancient mode"

**Comment by zzzckck** [comment]
one question: why it is "fast sync" when you have specified "syncmode=full"? Has your database been conducted with incomplete "snap sync" before?

**Comment by printhellow** [comment]
> 一个问题：为什么指定了“syncmode=full”时是“快速同步”？您的数据库以前是否在不完整的“快照同步”下执行过？

I don't know, I see that the node hangs and I restart, and then this error appears on startup, how should I fix it?

**Comment by joeylichang** [comment]
under fast sync, the `pruneancient` will take no effective
the core is full sync transfer to snap sync, maybe data error occurred. pls check the data?

**Comment by joeylichang** [comment]
@printhellow from genesis? or snapshot data?

**Comment by printhellow** [comment]
> snapshot data

 snapshot data

**Comment by printhellow** [comment]
> @printhellow from genesis? or snapshot data?

Yesterday it was still running normally, and this morning I woke up and saw that the node was hanging, and I restarted it and I got this error

**Comment by joeylichang** [comment]
the sync update the snapblock meta, but the fullblock is 0, so will chang to snapsync, you can do one of thins:
1. resync from snapshot again
2. cancle pruneancient flag, and continue to sync, after completing sync, use the 'snapshot prune block' cmd to prune the ancient data, and restart the bsc with prunancient flag.

**Comment by printhellow** [comment]
delete pruneancient flag，There is a new error in the startup

Fatal: Could not open database: open /root/geth/jiedian/node/geth/chaindata/ancient/chain/receipts.cidx: no such file or directory

**Comment by printhellow** [comment]
> delete pruneancient flag，There is a new error in the startup
> 
> Fatal: Could not open database: open /root/geth/jiedian/node/geth/chaindata/ancient/chain/receipts.cidx: no such file or directory

INFO [01-10|11:54:20.996] Starting Geth on BSC mainnet... 
INFO [01-10|11:54:20.997] Maximum peer count                       ETH=200 LES=0 total=200
WARN [01-10|11:54:20.998] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable 
INFO [01-10|11:54:20.998] Using pebble as db engine 
Chain metadata
  databaseVersion: 8 (0x8)
  headBlockHash: 0x0d21840abff46b96c84b2ac9e10e4f5cdaeb5693cb665db62a2f3b02d2d57b5b
  headFastBlockHash: 0xd529d6ff39dd20dcc60dc475b825b3aba5aa6ead8cfa521c0be893dc25d5a2c2
  headHeaderHash: 0xd529d6ff39dd20dcc60dc475b825b3aba5aa6ead8cfa521c0be893dc25d5a2c2
  lastPivotNumber: 31706311 (0x1e3ccc7)
  len(snapshotSyncStatus): 286 bytes
  snapshotDisabled: false
  snapshotJournal: 7195685 bytes
  snapshotRecoveryNumber: 35061430 (0x216feb6)
  snapshotRoot: 0x653e07c20417428e109da2063d016298d6435ebbe139790b8e7a952cee0c27b3
  txIndexTail: 29371693 (0x1c02d2d)
  fastTxLookupLimit: 2350000 (0x23dbb0)


Fatal: Could not open database: open /root/geth/jiedian/node/geth/chaindata/ancient/chain/receipts.cidx: no such file or directory

**Comment by printhellow** [comment]
this my start command：
geth --config ./config.toml --datadir ./node --cache 8000 --maxpendpeers 400 --rpc.allow-unprotected-txs --snapshot=true --txlookuplimit 0 --history.transactions=0 --syncmode=full --tries-verify-mode=local  --db.engine=pebble

**Comment by joeylichang** [comment]
Oh, this issue is fixing, it belong to new and old ancient compatibility, coule you choose the first way to resync from snapshot?

**Comment by printhellow** [comment]
> 呵呵，这个问题是解决的，它属于新旧古相容，你选择第一种方式从快照重新同步吗？

ok，What should I do

**Comment by joeylichang** [comment]
delete the data dir and mv the previous snapshot data ，and restart.
