### ISSUE TITLE
v1.3.7(pebbledb + PBSS) It will take a long time to find the peer node after restarting

### ISSUE THREAD

**Issue by FerdyCai** [bnb-chain/bsc#2148]
start shell: nohup ./geth --syncmode full --tries-verify-mode none --config ./config.toml --datadir ./node --state.scheme path --db.engine pebble --history.transactions 0 --pruneancient --cache 8000 --rpc.allow-unprotected-txs --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.api eth,net,web3,txpool --http.vhosts=*  >./console.log 2>&1 &

config.toml:
`[Eth]
NetworkId = 56
LightPeers = 100
TrieTimeout = 150000000000
StateScheme = "path"

[Eth.Miner]
GasCeil = 140000000
GasPrice = 3000000000
Recommit = 10000000000

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 3000000000
PriceBump = 10
AccountSlots = 200
GlobalSlots = 8000
AccountQueue = 200
GlobalQueue = 4000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 1000

[Node]
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
InsecureUnlockAllowed = false
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 200
NoDiscovery = false
StaticNodes = []
ListenAddr = ":30311"
EnableMsgEvents = false
DialRatio = 2

[Node.LogConfig]
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "debug"
FileRoot = ""
`
log file:
[bsc.log](https://github.com/bnb-chain/bsc/files/13882723/bsc.log)

After restarting the node program, I hope to quickly synchronize the blocks, but I found that peer nodes always take a long time to connect. How do we solve this problem?

**Comment by weiihann** [comment]
Similar issue to #2145, let's move the discussion there.
