### ISSUE TITLE
BSC Snapshot without prune ancient data

### ISSUE THREAD

**Issue by codpoint** [bnb-chain/bsc#2156]
Is it possible to find a snapshot without prune ancient blocks somewhere?

I used full node v1.2.X and upgraded to v 1.3.7. I used snapshot from 48club. But I can't get logs for old blocks.

I'm not considering an archive node because the disk size for a full node with history since the first block is half that of an archive node.

**Comment by du5** [comment]
It is too big and is not conducive to distribution. If your hard drive is large enough, it is recommended to start synchronization from the genesis block. It will take about 20 days.

**Comment by codpoint** [comment]
Thanks for your reply.

But this seems a little strange.

A full node with the ability to get logs for a frist block takes 5TB unpacked.

Full node synchronized with snapshot takes up 3TB unpacked. But it is impossible to get logs even for a block of 33 mln.

Is it really possible that a packed snapshot with the ability to get logs for all blocks takes too much, if in unpacked form it takes no more than 2 times?

**Comment by du5** [comment]
I thought about it, it might take 8-10T NVMe of free space to package it. For a non-profit project, this expense is undoubtedly huge

**Comment by zzzckck** [comment]
> Thanks for your reply.
> 
> But this seems a little strange.
> 
> A full node with the ability to get logs for a frist block takes 5TB unpacked.
> 
> Full node synchronized with snapshot takes up 3TB unpacked. But it is impossible to get logs even for a block of 33 mln.
> 
> Is it really possible that a packed snapshot with the ability to get logs for all blocks takes too much, if in unpacked form it takes no more than 2 times?

Would the official snapshot works for you? https://github.com/bnb-chain/bsc-snapshots, it is a full node with intact blocks.

You: A full node with the ability to get logs for a frist block takes 5TB unpacked.
Q1: what do you mean: " get logs for a frist block takes 5TB unpacked."?,what kind of log?

You: Full node synchronized with snapshot takes up 3TB unpacked
Q2: as I know the official bsc-snapshot with intact blocks is around 2.5TB, check https://github.com/bnb-chain/bsc-snapshots

**Comment by zzzckck** [comment]
> Q1: what do you mean: " get logs for a frist block takes 5TB unpacked."?,what kind of log?
> 
> I meant that the node takes up 5tb space (~unpacked snapshot, if I understand correctly). And on such a node when using eth_getLogs json rpc method with block parameter 1, you will get data. After the official snapshot, there is no data for the first block, or even for the 30 000 000 block.
> 
> Q2: I just used the official snapshot. I also used snapshot from 48club. The result is the same.

It works for me, I used this cmd:
```
curl -X POST http://127.0.0.1:8545 -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"fromBlock":"0x1", "toBlock":"0x2"}],"id":74}'
```
here is the output:
```
{"jsonrpc":"2.0","id":74,"result":[{"address":"0x0000000000000000000000000000000000001003","topics":["0x5ac9b37d571677b80957ca05693f371526c602fd08042b416a29fdab7efefa49"],"data":"0x0000000000000000000000000000000000000000000000000000000006915167cedaf7bbf7df47d932fdda630527ee648562cf3e52c5e5f46156a3a971a4ceb4","blockNumber":"0x1","transactionHash":"0x9ebc5237eabb339a103a34daf280db3d9498142b49fa47f1af71f64a605acffa","transactionIndex":"0x2","blockHash":"0x04055304e432294a65ff31069c4d3092ff8b58f009cdb50eba5351e0332ad0f6","logIndex":"0x0","removed":false},{"address":"0x0000000000000000000000000000000000001001","topics":["0xddb6012116e51abf5436d956a4f0ebd927e92c576ff96d7918290c8782291e3e","0x0000000000000000000000002d4c407bbe49438ed859fe965b140dcf1aab71a9"],"data":"0x","blockNumber":"0x2","transactionHash":"0x1d06a9d52255a2a4385d55093aec7671f3d7f6d83d4cd438991be8b6588e9b91","transactionIndex":"0x0","blockHash":"0xe9296d312a937cdefc201a8fe80dbfa8a9c958ada9e863ddbb324804722f1de0","logIndex":"0x0","removed":false}]}
```
How did you start your node? Your RPC cmd? And the return error?

**Comment by codpoint** [comment]
I'm sorry for the late reply. I downloaded the archive again and launched the node.

The screenshot shows the result.
![image](https://github.com/bnb-chain/bsc/assets/73311664/8bb7929f-eaf2-4157-89fa-602edb6746ce)


geth run command:
`/opt/bsc/geth --graphql --ws --ws.addr 0.0.0.0 --ws.origins '*' --config /opt/bsc/config.toml --datadir /opt/bsc/node  --cache 32000 --rpc.allow-unprotected-txs --rpc.gascap 0 --history.transactions 0 --state.scheme path --db.engine pebble --syncmode full --tries-verify-mode local --pruneancient`

config.toml:
```
[Eth]
NetworkId = 56
LightPeers = 100
TrieTimeout = 150000000000
StateScheme = "path"

[Eth.Miner]
GasCeil = 140000000
GasPrice = 3000000000
Recommit = 10000000000

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 3000000000
PriceBump = 10
AccountSlots = 200
GlobalSlots = 8000
AccountQueue = 200
GlobalQueue = 4000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 1000

[Node]
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
NoUSB = true
InsecureUnlockAllowed = false
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia", "debug"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 200
NoDiscovery = false
StaticNodes = []
ListenAddr = ":30311"
EnableMsgEvents = false

[Node.LogConfig]
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""
```

**Comment by du5** [comment]
pruneancient only 90k data

<img width="1062" alt="image" src="https://github.com/bnb-chain/bsc/assets/54979375/5975a7d1-3685-492b-bfc8-034e7f3943f8">

**Comment by codpoint** [comment]
I realized that the node cleans up the data after starting.

Therefore, the problem is not in the snapshot, but in the config.

It seems the problem is that I left the flag --pruneancient...

**Comment by zzzckck** [comment]
> I realized that the node cleans up the data after starting.
> 
> Therefore, the problem is not in the snapshot, but in the config.
> 
> It seems the problem is that I left the flag --pruneancient...

yea, `--pruneancient` would delete blocks beyond 90K, you may not use this flag if you wanna the whole historical blocks.
Pls close this issue, if everything is ok with you, thx.
