### ISSUE TITLE
"geth dump" on fast node snapshot gives "missing trie node"

### ISSUE THREAD

**Issue by sns-sem** [bnb-chain/bsc#2157]
**Geth Verion:** Geth v1.3.7 
**Go Version:** Go v1.20.12

Cmd used: `geth dump --datadir /mnt/nvme/geth.fast/geth --db.engine=pebble`

Gives output:
> missing trie node 7bf7ccc199a77e7c298c263b7eb341704a07c66ade46d069b17ea50c6c11d596 (path ) state 0x7bf7ccc199a77e7c298c263b7eb341704a07c66ade46d069b17ea50c6c11d596 is not available, not found

When using 48Club bsc-snapshot "Geth fast node" for block 35,088,932.

I'm just looking to dump latest state from the snapshot.

**Comment by zzzckck** [comment]
https://github.com/48Club/bsc-snapshots?tab=readme-ov-file
<img width="369" alt="image" src="https://github.com/bnb-chain/bsc/assets/152148891/d8092bdb-7445-4b2e-9ab8-eafb7485104c">
if you wanna to dump state, then don't use `Geth fast node`, you need full node.

**Comment by sns-sem** [comment]
> https://github.com/48Club/bsc-snapshots?tab=readme-ov-file <img alt="image" width="369" src="https://private-user-images.githubusercontent.com/152148891/296417474-d8092bdb-7445-4b2e-9ab8-eafb7485104c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxNzgyOTIsIm5iZiI6MTcwNTE3Nzk5MiwicGF0aCI6Ii8xNTIxNDg4OTEvMjk2NDE3NDc0LWQ4MDkyYmRiLTc0NDUtNGIyZS05YWI4LWVhZmI3NDg1MTA0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExM1QyMDMzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hN2JiMTY2ZGQxNWNhZmExNDg5MGJmNDVmMGJmNjEzNzFhOTc2N2NkODQxM2ZkZTIyYmZjYjg3MzE4ZmRmZDNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.759yi_zU1I8rI54JZ9ZqOwrKD1_qf3jgezI2lpYrCwQ"> if you wanna to dump state, then don't use `Geth fast node`, you need full node.

After downloading the `Geth full node` snapshot instead, I'm able to run the command: 

`geth dump --datadir /mnt/nvme/geth.full/geth --db.engine=pebble`

Which gives the following output, but does nothing afterwards. Ran it for ~4 hours and nothing happened:

```
INFO [01-13|17:51:04.964] Using pebble as the backing database
INFO [01-13|17:51:04.964] Allocated cache and file handles         database=/mnt/nvme/geth.full/geth/chaindata cache=409.00MiB handles=524,288 "memory table"=102.25MiB
INFO [01-13|17:51:07.309] State scheme set to already existing     scheme=hash
INFO [01-13|17:51:07.338] Set global gas cap                       cap=50,000,000
INFO [01-13|17:51:07.339] Initializing the KZG library             backend=gokzg
INFO [01-13|17:51:07.484] Using pebble as the backing database
INFO [01-13|17:51:07.484] Allocated cache and file handles         database=/mnt/nvme/geth.full/geth/chaindata cache=409.00MiB handles=524,288 "memory table"=102.25MiB
INFO [01-13|17:51:09.711] State dump configured                    block=35,152,552 hash=0xefc5b1d776ef8cbc30a6533743d36c2a42629fd43463d8118904c8ebe55d7a67 skipcode=false skipstorage=false start=0x0000000000000000000000000000000000000000000000000000000000000000 limit=0
INFO [01-13|17:51:09.714] State scheme set to already existing     scheme=hash
INFO [01-13|17:51:09.714] Trie dumping started                     root=4218a7..cf34dd
```

How am I supposed to get the dumped state?

**Comment by cecuabin** [comment]
j^ns-1/2)N!5 = -d0*.dmb
1:5000rnab = 213 Kpc . sh^3H + (2n - 1/2Hen)*.rsc

**Comment by zzzckck** [comment]
> > https://github.com/48Club/bsc-snapshots?tab=readme-ov-file <img alt="image" width="369" src="https://private-user-images.githubusercontent.com/152148891/296417474-d8092bdb-7445-4b2e-9ab8-eafb7485104c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxNzgyOTIsIm5iZiI6MTcwNTE3Nzk5MiwicGF0aCI6Ii8xNTIxNDg4OTEvMjk2NDE3NDc0LWQ4MDkyYmRiLTc0NDUtNGIyZS05YWI4LWVhZmI3NDg1MTA0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExM1QyMDMzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hN2JiMTY2ZGQxNWNhZmExNDg5MGJmNDVmMGJmNjEzNzFhOTc2N2NkODQxM2ZkZTIyYmZjYjg3MzE4ZmRmZDNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.759yi_zU1I8rI54JZ9ZqOwrKD1_qf3jgezI2lpYrCwQ"> if you wanna to dump state, then don't use `Geth fast node`, you need full node.
> 
> After downloading the `Geth full node` snapshot instead, I'm able to run the command:
> 
> `geth dump --datadir /mnt/nvme/geth.full/geth --db.engine=pebble`
> 
> Which gives the following output, but does nothing afterwards. Ran it for ~4 hours and nothing happened:
> 
> ```
> INFO [01-13|17:51:04.964] Using pebble as the backing database
> INFO [01-13|17:51:04.964] Allocated cache and file handles         database=/mnt/nvme/geth.full/geth/chaindata cache=409.00MiB handles=524,288 "memory table"=102.25MiB
> INFO [01-13|17:51:07.309] State scheme set to already existing     scheme=hash
> INFO [01-13|17:51:07.338] Set global gas cap                       cap=50,000,000
> INFO [01-13|17:51:07.339] Initializing the KZG library             backend=gokzg
> INFO [01-13|17:51:07.484] Using pebble as the backing database
> INFO [01-13|17:51:07.484] Allocated cache and file handles         database=/mnt/nvme/geth.full/geth/chaindata cache=409.00MiB handles=524,288 "memory table"=102.25MiB
> INFO [01-13|17:51:09.711] State dump configured                    block=35,152,552 hash=0xefc5b1d776ef8cbc30a6533743d36c2a42629fd43463d8118904c8ebe55d7a67 skipcode=false skipstorage=false start=0x0000000000000000000000000000000000000000000000000000000000000000 limit=0
> INFO [01-13|17:51:09.714] State scheme set to already existing     scheme=hash
> INFO [01-13|17:51:09.714] Trie dumping started                     root=4218a7..cf34dd
> ```
> 
> How am I supposed to get the dumped state?

It needs lots of time to dump the latest worldstate, not sure the exact time needed, but could far more the 4 houts.
But seems there do have a bug to dump state with PBSS + Pebble, we will investigate on it.
And maybe we can print some about the dump progress, so user could know if the process is stuck or not.

**Comment by zzzckck** [comment]
> > > https://github.com/48Club/bsc-snapshots?tab=readme-ov-file <img alt="image" width="369" src="https://private-user-images.githubusercontent.com/152148891/296417474-d8092bdb-7445-4b2e-9ab8-eafb7485104c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxNzgyOTIsIm5iZiI6MTcwNTE3Nzk5MiwicGF0aCI6Ii8xNTIxNDg4OTEvMjk2NDE3NDc0LWQ4MDkyYmRiLTc0NDUtNGIyZS05YWI4LWVhZmI3NDg1MTA0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExM1QyMDMzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hN2JiMTY2ZGQxNWNhZmExNDg5MGJmNDVmMGJmNjEzNzFhOTc2N2NkODQxM2ZkZTIyYmZjYjg3MzE4ZmRmZDNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.759yi_zU1I8rI54JZ9ZqOwrKD1_qf3jgezI2lpYrCwQ"> if you wanna to dump state, then don't use `Geth fast node`, you need full node.
> > 
> > 
> > After downloading the `Geth full node` snapshot instead, I'm able to run the command:
> > `geth dump --datadir /mnt/nvme/geth.full/geth --db.engine=pebble`
> > Which gives the following output, but does nothing afterwards. Ran it for ~4 hours and nothing happened:
> > ```
> > INFO [01-13|17:51:04.964] Using pebble as the backing database
> > INFO [01-13|17:51:04.964] Allocated cache and file handles         database=/mnt/nvme/geth.full/geth/chaindata cache=409.00MiB handles=524,288 "memory table"=102.25MiB
> > INFO [01-13|17:51:07.309] State scheme set to already existing     scheme=hash
> > INFO [01-13|17:51:07.338] Set global gas cap                       cap=50,000,000
> > INFO [01-13|17:51:07.339] Initializing the KZG library             backend=gokzg
> > INFO [01-13|17:51:07.484] Using pebble as the backing database
> > INFO [01-13|17:51:07.484] Allocated cache and file handles         database=/mnt/nvme/geth.full/geth/chaindata cache=409.00MiB handles=524,288 "memory table"=102.25MiB
> > INFO [01-13|17:51:09.711] State dump configured                    block=35,152,552 hash=0xefc5b1d776ef8cbc30a6533743d36c2a42629fd43463d8118904c8ebe55d7a67 skipcode=false skipstorage=false start=0x0000000000000000000000000000000000000000000000000000000000000000 limit=0
> > INFO [01-13|17:51:09.714] State scheme set to already existing     scheme=hash
> > INFO [01-13|17:51:09.714] Trie dumping started                     root=4218a7..cf34dd
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > How am I supposed to get the dumped state?
> 
> It needs lots of time to dump the latest worldstate, not sure the exact time needed, but could far more the 4 houts. But seems there do have a bug to dump state with PBSS + Pebble, we will investigate on it. And maybe we can print some about the dump progress, so user could know if the process is stuck or not.

I tried to dump state with PBSS + Pebble:
./geth  --datadir ./node --state.scheme path --db.engine pebble init genesis.json
./geth dump --datadir ./node --incompletes --db.engine=pebble --state.scheme path
failed with the following logs
```


INFO [01-15|12:30:34.246] Maximum peer count                       ETH=50 total=50
INFO [01-15|12:30:34.248] Using pebble as db engine
INFO [01-15|12:30:34.251] Use CLI state scheme                     CLI=path
INFO [01-15|12:30:34.252] Set global gas cap                       cap=50,000,000
INFO [01-15|12:30:34.252] Initializing the KZG library             backend=gokzg
INFO [01-15|12:30:34.278] Using pebble as the backing database
INFO [01-15|12:30:34.278] Allocated cache and file handles         database=/Users/larry/work/node-deploy/forGeth/testnet/node/geth/chaindata cache=409.00MiB handles=5120 "memory table"=102.25MiB
INFO [01-15|12:30:34.299] Opened ancient database                  database=/Users/larry/work/node-deploy/forGeth/testnet/node/geth/chaindata/ancient/chain readonly=true frozen=0
INFO [01-15|12:30:34.300] State dump configured                    block=2113 hash=0x98e23ea7f20a61ec95d4cc8e243138a3836fae6ce7409737fbf6b119cb66ad51 skipcode=false skipstorage=false start=0x0000000000000000000000000000000000000000000000000000000000000000 limit=0
INFO [01-15|12:30:34.300] Use CLI state scheme                     CLI=path
INFO [01-15|12:30:34.300] State scheme set by user                 scheme=path
INFO [01-15|12:30:34.300] new async node buffer                    limit=0.00B layers=0
WARN [01-15|12:30:34.309] Path-based state scheme is an experimental feature sync=false
INFO [01-15|12:30:34.309] Trie dumping started                     root=c52957..cc8b16
{"root":"0xc529570dfbf10fb9afa60fa3dddafa34288940a18002cbbfaae3d55576cc8b16"}
{"balance":"298650241559000000000","nonce":24,"root":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","codeHash":"0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470","key":"0x017b7e984d3dd37693d3966fc10636542397eedff8ee67f9b8fc2d779e03f2dd"}
{"balance":"0","nonce":33,"root":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","codeHash":"0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470","key":"0x054dee4f08a5440aeb35e5488e89680a1fd825131540198d14787b660a01f383"}
ERROR[01-15|12:30:34.309] Unexpected trie node in disk             owner=5380c7..67312a path=[] expect=161b17..e3aacc got=000000..000000
ERROR[01-15|12:30:34.309] Failed to load storage trie              err="missing trie node 161b17dc76f5c7f260c11e0043f36840dcd629a76c51a953a65dd3dd14e3aacc (owner 5380c7b7ae81a58eb98d9c78de4a1fd7fd9535fc953ed2be602daaa41767312a) (path ) unexpected node, loc: disk, node: (5380c7b7ae81a58eb98d9c78de4a1fd7fd9535fc953ed2be602daaa41767312a []), 161b17dc76f5c7f260c11e0043f36840dcd629a76c51a953a65dd3dd14e3aacc!=0000000000000000000000000000000000000000000000000000000000000000, blob: nil"
{"balance":"1999165916000000000","nonce":1,"root":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","codeHash":"0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470","key":"0x10e776834f1f1fd582ba70219c2f748ec21a255ab4f1894a777b0b865c412e8d"}
{"balance":"10000000000000000000000000","nonce":0,"root":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","codeHash":"0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470","key":"0x12ea3fe21e524c1b5ea56b198810b6aa175aa7bb6b4feeb998d3a2c9a02fb2d0"}
{"balance":"0","nonce":40,"root":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","codeHash":"0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470","key":"0x182d19f5d9ed84c335476b31d0e26e70922f55dd7b7be1dadf9d0dd2ab5eebe1"}
ERROR[01-15|12:30:34.310] Unexpected trie node in disk             owner=5380c7..67312a path=[] expect=e0ff6b..a0bea2 got=000000..000000
...
```

**Comment by sysvm** [comment]
@sns-sem You can use develop branch to compile geth and use `geth dump` to get state data. More info you can refer [#2160](https://github.com/bnb-chain/bsc/pull/2160).
