### ISSUE TITLE
Can you share peers in testnet ?

### ISSUE THREAD

**Issue by mariel-sendblocks** [bnb-chain/bsc#2164]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

My geth node (bsc) in testnet (chain 97) cant find any peers in the last release (1.3.7).
Appreciate if someone can share some peers .

**Comment by deepcrazy** [comment]
Hi there, There is no need of static nodes required to be specified post v1.2.12 release as mentioned over here: https://forum.bnbchain.org/t/try-bootnodes-after-bsc-release-v1-2-12/1998#h-32to-join-the-network-with-bootnodes-5.

In addition to this, If you're running bsc testnet node with v1.3.7, please use config.toml file of latest release (from here: https://github.com/bnb-chain/bsc/releases/tag/v1.3.7) and refer this documentation: https://docs.bnbchain.org/docs/validator/fullnode#steps-to-run-a-fullnode for more details.

**Comment by mariel-sendblocks** [comment]
I followed the docs and update the config.toml but it didnt help.
I started my full node from a snapshot.
my config.toml is very slim : 
```
[Node.LogConfig]
Level = "info"

[Node.P2P]
MaxPeers = 200
NoDiscovery = false
StaticNodes = []
```

I'm running the node as a container and in its entrypoint I provide the other properties :
```
      - --config <relevant path>
      - --networkid=97
      - --metrics
      - --pprof
      - --pprof.addr
      - --tries-verify-mode=local
      - --cache=5000
      - --syncmode=snap
      - --triesInMemory=128
      - --maxpeers=200
      - --verbosity=3

```


The logs are full of failed attempts to find peers and sync : 
```
 | INFO [01-17|21:13:33.572] Looking for peers                        peercount=1 tried=102 static=0
 | ERROR[01-17|21:14:06.520] Bsc extension Handshake failed           peer=c73b7d65 err=EOF
  | INFO [01-17|21:14:32.265] Current status                           table_size=123 pending_size=5  db_size=2,394,429
  | WARN [01-17|21:14:55.672] Snapshot extension registration failed   peer=e9f21729 err="peer connected on snap without compatible eth support"
  | ERROR[01-17|21:15:26.043] Bsc extension Handshake failed           peer=d7a611f0 err="read timeout"
 | INFO [01-17|21:15:32.265] Current status                           table_size=122 pending_size=3  db_size=2,394,429
| WARN [01-17|21:15:37.343] Snapshot extension registration failed   peer=63e0d242 err="peer connected on snap without compatible eth support"
 | INFO [01-17|21:16:32.265] Current status                           table_size=118 pending_size=9  db_size=2,394,429
 | WARN [01-17|21:17:21.442] Snapshot extension registration failed   peer=8cdeb12a err="peer connected on snap without compatible eth support"
 | ERROR[01-17|21:17:29.707] Bsc extension Handshake failed           peer=5951b078 err=EOF
```

**Comment by deepcrazy** [comment]
- Seems like there is mismatch in your config.toml file and latest release config.toml. Please use the latest config.toml file from the v1.3.7 release: https://github.com/bnb-chain/bsc/releases/download/v1.3.7/testnet.zip.
   - Attached is the reference config.toml file: [testnet_v1.3.7.zip](https://github.com/bnb-chain/bsc/files/13969388/testnet_v1.3.7.zip)
- Make sure that you're using the latest snapshot from here: https://github.com/bnb-chain/bsc-snapshots?tab=readme-ov-file#endpoint

In addition to this, make the following changes in your startup command:
- remove `--syncmode=snap` flag or if you want to use this flag, then use this: `--syncmode=full`

After following all of this, change the log level to `debug` and then share the logs if it still doesn't work.

**Comment by zzzckck** [comment]
> Hi there, There is no need of static nodes required to be specified post v1.2.12 release as mentioned over here: https://forum.bnbchain.org/t/try-bootnodes-after-bsc-release-v1-2-12/1998#h-32to-join-the-network-with-bootnodes-5.
> 
> In addition to this, If you're running bsc testnet node with v1.3.7, please use config.toml file of latest release (from here: https://github.com/bnb-chain/bsc/releases/tag/v1.3.7) and refer this documentation: https://docs.bnbchain.org/docs/validator/fullnode#steps-to-run-a-fullnode for more details.

bootnode is only for mainnet, testnet still need to configure the StaticNodes manually, the StaticNodes list is contained in the latest release.
https://github.com/bnb-chain/bsc/releases/download/v1.3.7/testnet.zip.

**Comment by mariel-sendblocks** [comment]
I didnt do any configuration change, just download the snapshot again, start the node and after 3 minutes of peers searching, the node has started importing new chains.

For those of you who might face this issue in the future, a few tips: 
1. Check for configuration issues like wrong chain id, wrong config dir.
2. Dont use bootnodes on testnet, it doesnt required.
3. Deleting the geth/nodes and geth/nodekey file/dir might help
4. Redownload the snapshot and try again.

In my case, 4 was the solution.
