### ISSUE TITLE
eth_getLogs not found

### ISSUE THREAD

**Issue by TehnobitSystems** [bnb-chain/bsc#2179]
Geth version: 1.3.7
OS & Version: Ubuntu 22.04
Bsc-snapshot: Path-Base-State-Scheme (recommand) "geth-pbss-pebble-20240115.tar.lz4"
Running: `geth_linux --config config.toml --datadir /geth --rpc.allow-unprotected-txs --history.transactions 0  --syncmode=full --pruneancient=true --tries-verify-mode none --state.scheme path `

When I try to use the eth_getLogs method, I get an error: 

> WARN [01-24|06:31:48.097] Served eth_getLogs   reqid=1 t="290.571µs" err="pebble: not found"  X-Forwarded-For=nil
> WARN [01-24|06:31:48.097] Served eth_getLogs.  reqid=1 duration="290.091µs" err="pebble: not found"

Please tell me how to use the logs now?

**Comment by zzzckck** [comment]
`--tries-verify-mode none` will delete old blocks and receipts, if you wanna to query old logs(>90K backward), don't use this flag.

**Comment by zzzckck** [comment]
Similar issue: https://github.com/bnb-chain/bsc/issues/2156
close this one, if you have further question, you may reply to the above issue.
