### ISSUE TITLE
BSC-light mode no longer support.

### ISSUE THREAD

**Issue by HHun1** [bnb-chain/bsc#2188]
Hi, can you please tell me if there is a chance that bsc-light mode will be resurrected? The thing is that we use it in our product and now we have to use external services with free api.

**Comment by deepcrazy** [comment]
Hi there, Light mode is not supported now, references: https://github.com/bnb-chain/bsc/issues/1947, https://github.com/bnb-chain/bsc/pull/2098. 
You can instead use fast node: https://docs.bnbchain.org/docs/BSC-fast-node/#steps-to-run-a-fast-node and use the 48Club's snapshot: https://github.com/48Club/bsc-snapshots.

**Comment by zzzckck** [comment]
same as: https://github.com/bnb-chain/bsc/issues/2162
close this one, @HHun1 you may reply to issue #2162
