### ISSUE TITLE
Failing to unregister sync peer which is not registered

### ISSUE THREAD

**Issue by an0nym0us101** [bnb-chain/bsc#220]
Using the latest beta release - v1.1.0 beta

A custom node went out of sync so we checked the logs and it looks like it was trying to drop a bad peer but it couldn't stating that the peer is not registered. We had to manually restart geth to fix the issue. This seems like this problem mentioned here - https://github.com/ethereum/go-ethereum/issues/22077

Attaching the bsc.log file, please advise.

[bsc.log](https://github.com/binance-chain/bsc/files/6477826/bsc.log)

**Comment by knglenn** [comment]
I am running a fullnode and have been seeing the same issue since upgrading to the beta release. The node will periodically stop syncing for several minutes at a time, and when checking the logs the last message logged before syncing stopped will be similar to:
```
t=2021-05-16T13:17:38-0700 lvl=eror msg="Ethereum peer removal failed"          peer=6f221a41 err="peer not registered"
```
Sometimes the issue resolves itself after a few minutes and the node will start syncing again, but on several occasions, I've had to stop the node and restart to fix it. When the issue does resolve without a restart, no log messages are emitted for the duration of the freeze. There are no warning/error messages (aside from the "peer removal failed" messages) when syncing starts again.

**Comment by an0nym0us101** [comment]
For me it doesnt restart syncing automatically, it keeps throwing the error in the bsc.log file I have attached. I have to manually stop geth and restart it. Worst part is it happens randomly at anytime so you have to keep checking if your node is in sync. It has happened twice today already, once after a few hours and once within a few minutes after having restarted geth. On the third run now!

**Comment by JohnsonCaii** [comment]
Same issues here, would like to know how did you finally resolve this?

The node kept logging the `removal failed`, it almost lasts 2 hours before getting back to normal.
```
WARN [06-01|01:30:02.751] Synchronisation failed, dropping peer    peer=83b0745fe580f90960348cad600aae35bbdec49114b43403f3000984fc61bc4f err=timeout
ERROR[06-01|01:30:05.214] Ethereum peer removal failed             peer=83b0745f err="peer not registered"
WARN [06-01|01:30:17.349] Synchronisation failed, dropping peer    peer=d87ebe2bcb14571d81facb84eb4c0b85409768676c69bb6e933eb83b146d2f3b err=timeout
ERROR[06-01|01:30:20.279] Ethereum peer removal failed             peer=d87ebe2b err="peer not registered"
WARN [06-01|01:30:25.497] Synchronisation failed, dropping peer    peer=26f0e86cd539ad23def4c777b60d94bbb4dc0f808e600278a3c008f0072e9dde err=timeout
ERROR[06-01|01:30:28.491] Ethereum peer removal failed             peer=26f0e86c err="peer not registered"
WARN [06-01|01:30:33.118] Synchronisation failed, dropping peer    peer=83b0745fe580f90960348cad600aae35bbdec49114b43403f3000984fc61bc4f err=timeout
ERROR[06-01|01:30:33.421] Ethereum peer removal failed             peer=83b0745f err="peer not registered"
WARN [06-01|01:30:44.699] Synchronisation failed, dropping peer    peer=9b349e73396f0bb90d73bccead0151f8399f6783febce9fb5e0ba04f908ff1af err=timeout
ERROR[06-01|01:30:50.723] Ethereum peer removal failed             peer=9b349e73 err="peer not registered"
WARN [06-01|01:30:54.309] Synchronisation failed, dropping peer    peer=7235f9972b3282bf8e0b96b4b8b4fe2ee44039dc7c07d244e3b17c61d7fc2c6e err=timeout
ERROR[06-01|01:30:55.830] Ethereum peer removal failed             peer=7235f997 err="peer not registered"
WARN [06-01|01:31:03.633] Synchronisation failed, dropping peer    peer=5bec65ef75ae11130c3ba69f5d6a6077a41e0ea3541019ca9a86cf6bff884865 err=timeout
ERROR[06-01|01:31:07.002] Ethereum peer removal failed             peer=5bec65ef err="peer not registered"
WARN [06-01|01:31:14.305] Synchronisation failed, dropping peer    peer=26f0e86cd539ad23def4c777b60d94bbb4dc0f808e600278a3c008f0072e9dde err=timeout
ERROR[06-01|01:31:15.389] Ethereum peer removal failed             peer=26f0e86c err="peer not registered"
WARN [06-01|01:31:22.825] Synchronisation failed, dropping peer    peer=83b0745fe580f90960348cad600aae35bbdec49114b43403f3000984fc61bc4f err=timeout
ERROR[06-01|01:31:22.835] Ethereum peer removal failed             peer=83b0745f err="peer not registered"
```

**Comment by superbeanmr** [comment]
When I was synchronizing the geth test chain, an error was thrown. Can God tell me what to do?
The error log is as follows

INFO [06-01|08:14:52.814] Block synchronisation started
WARN [06-01|08:15:07.814] Checkpoint challenge timed out, dropping id=0d1c47ab5cc6ca4b conn=dyndial addr=135.181.178.19:30403 type=OpenEthereum/oe-node...
ERROR[06-01|08:15:07.814] Ethereum peer removal failed             peer=0d1c47ab err="peer not registered"
WARN [06-01|08:15:52.815] Synchronisation failed, dropping peer    peer=0d1c47ab5cc6ca4be526d81a061c2a2a8ab207cf6b1775148b518acdca007f83 err=timeout
ERROR[06-01|08:15:52.815] Ethereum peer removal failed             peer=0d1c47ab err="peer not registered"
INFO [06-01|08:17:13.587] Writing clean trie cache to disk         path=/mnt/xvdb/eth_test_data/geth/triecache threads=1
INFO [06-01|08:17:13.587] Regenerated local transaction journal    transactions=0 accounts=0
INFO [06-01|08:17:13.596] Persisted the clean trie cache           path=/mnt/xvdb/eth_test_data/geth/triecache elapsed=8.827ms
WARN [06-01|08:20:10.013] Ancestor below allowance                 peer=70da9d0e number=10,253,166 hash=000000..000000 allowance=10,253,166
WARN [06-01|08:20:10.013] Synchronisation failed, dropping peer    peer=70da9d0ebde419826a9f2b59800a161dcb8805b26d1e314010651eb106ca8032 err="retrieved ancestor is invalid"
ERROR[06-01|08:20:10.013] Ethereum peer removal failed             peer=70da9d0e err="peer not registered"
WARN [06-01|08:20:37.564] Ancestor below allowance                 peer=83c3d84a number=10,253,166 hash=000000..000000 allowance=10,253,166
WARN [06-01|08:20:37.564] Synchronisation failed, dropping peer    peer=83c3d84a5cd3e37db4dae6c1d5394189d9f1cf8d0026575b02ba9b45faa8b6e4 err="retrieved ancestor is invalid"
ERROR[06-01|08:20:37.564] Ethereum peer removal failed             peer=83c3d84a err="peer not registered"

**Comment by superbeanmr** [comment]
The version of my geth client is 1.10.3
The start command is
# nohup ./geth --http --http.corsdomain * --datadir /mnt/xvdb/eth_test_data --port 8090 --http.api db,eth,net,web3,personal,admin,miner --allow-insecure-unlock --http.addr 0.0.0.0 --http.port 6666 --allow-insecure-unlock --ropsten --snapshot=false >> /mnt/xvdb/eth_test_data/geth.log &**

**Comment by KyloYang888** [comment]
Hi team. I get the same error in v1.1.8, how is it handled please?

**Comment by Jolly23** [comment]
#856 fixed
