### ISSUE TITLE
make geth error

### ISSUE THREAD

**Issue by mucy0729** [bnb-chain/bsc#2254]
env GO111MODULE=on go run build/ci.go install ./cmd/geth
>>> /usr/local/go/bin/go build -ldflags "-X github.com/ethereum/go-ethereum/internal/version.gitCommit=5ee77bbe8bba2f1e9b7bc9368347fd531891ec7e -X github.com/ethereum/go-ethereum/internal/version.gitDate= -s" -tags urfave_cli_no_docs,ckzg -trimpath -v -o /Users/kk.c/work/jiedian/bsc/build/bin/geth ./cmd/geth
go: github.com/prysmaticlabs/prysm@v0.0.0-20220124113610-e26cde5e091b requires
        github.com/wercker/journalhook@v0.0.0-20180428041537-5d0a5ae867b3: invalid version: unknown revision 5d0a5ae867b3
util.go:48: exit status 1
exit status 1

**Comment by zzzckck** [comment]
what is your Golang version, BSC needs Golang v1.21+ now.

**Comment by zzzckck** [comment]
close it now, since no update for more then 2 weeks, could reopen once more information is provided.
