### ISSUE TITLE
Sync Bug

### ISSUE THREAD

**Issue by du5** [bnb-chain/bsc#2259]
In the latest version, when `tries-verify-mode` value is `none` the node cannot complete synchronization from the genesis block
Multiple tests have been conducted and the bug is stably reproduced. When `tries-verify-mode` value is `local ` This problem does not occur when

**Comment by du5** [comment]
[log.txt](https://github.com/bnb-chain/bsc/files/14525207/log.txt)

**Comment by CocoStarZ** [comment]
Could you pls share your start cmd?

**Comment by du5** [comment]
```
> geth init --db.engine pebble --datadir fast --state.scheme hash genesis.json
> geth --datadir fast --config=config.toml --port=30399 --http.port=19966 --ws.port=19966 --maxpeers=96 --tries-verify-mode=none --db.engine=pebble --state.scheme hash

```

**Comment by du5** [comment]
btw, The situation is the same when state.scheme is set to path.

**Comment by weiihann** [comment]
Snap sync doesn't work with fast nodes for now. By definition, a fast node only keeps the snapshot but not the state trie. On the other hand, snap sync downloads the trie nodes and reconstructs the state trie. So these 2 configurations are not compatible.

We are still experimenting with some syncing methods with fast nodes. But for now, we can't use `tries-verify-mode=none` and `syncmode=snap` together.
