### ISSUE TITLE
Please update site documentation with following correction

### ISSUE THREAD

**Issue by shaunsurfing** [bnb-chain/bsc#2262]
Team, the website docs say the following to get a node started:

./geth --tries-verify-mode none --config ./config.toml --datadir ./node  --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0

However, the --txlookuplimit should be replaced with --history.transactions due to the txlookuplimit deprecation.

Ref: https://docs.bnbchain.org/docs/BSC-fast-node/

msg="The flag --txlookuplimit is deprecated and may cause unexpected performance degradation issues. Please use --history.transactions instead"

This issue is printed to the logs, but if a user is not familiar with the logs or working with geth, it can be challenging to understand why the node looks like it starts and then just terminates abruptly.

Feel free to correct my understanding on--history.transactions, it just worked so I went with it.

**Comment by CocoStarZ** [comment]
Thanks for pointing it out. will fix it soon.

**Comment by zzzckck** [comment]
thx, it is fixed.
