### ISSUE TITLE
highestBlock lower than currentBlock

### ISSUE THREAD

**Issue by fushengyk666** [bnb-chain/bsc#2284]
![1710339238638](https://github.com/bnb-chain/bsc/assets/96592809/84c3e531-9ec7-480b-b90a-6578bea226ab)

I upgraded the fullnode today，what wrong with my fullnode，highestBlock lower than currentBlock

**Comment by fushengyk666** [comment]
I upgraded the fullnode today

**Comment by fushengyk666** [comment]
v1.4.2-alpha encountered this issue, and v1.3.10 was restored to restore it

**Comment by weiihann** [comment]
Regarding the behavior, the highest block is lower than the current block means that the block is the highest block that your node gets from its peers. Meaning that your peers are possibly not synced yet.

Anyways, v1.4.2-alpha is an unstable version. Please do not use it yet. We'll continue to monitor if this is a bug.
