### ISSUE TITLE
Please update site documentation with following correction

### ISSUE THREAD

**Issue by a01cr** [bnb-chain/bsc#2289]
In the NodesBNB Smart Chain Docker documentation (https://docs.bnbchain.org/docs/validator/docker/) the curl command to download BSC Node Config Files for Testnet should be :

`wget   $(curl -s https://api.github.com/repos/bnb-chain/bsc/releases/latest |grep browser_ |grep testnet |cut -d\" -f4)
`

Instead of :

`wget   $(curl -s https://api.github.com/repos/bnb-chain/bsc/releases/latest |grep browser_ |grep mainnet |cut -d\" -f4)
`

**Comment by Mandama06** [comment]
> In the NodesBNB Smart Chain Docker documentation (https://docs.bnbchain.org/docs/validator/docker/) the curl command to download BSC Node Config Files for Testnet should be :
> 
> `wget $(curl -s https://api.github.com/repos/bnb-chain/bsc/releases/latest |grep browser_ |grep testnet |cut -d\" -f4) `
> 
> Instead of :
> 
> `wget $(curl -s https://api.github.com/repos/bnb-chain/bsc/releases/latest |grep browser_ |grep mainnet |cut -d\" -f4) `
