### ISSUE TITLE
geth trace oom

### ISSUE THREAD

**Issue by printhellow** [bnb-chain/bsc#2290]
I traced multiple transactions, but the end result was that the memory took up 100 g until OOM..
This is my own modification of geth but it doesn't seem to be a problem, I don't know where this bloated data comes from↓
![@S~ I6(CS9 1Q0D$ALHJ}RB](https://github.com/bnb-chain/bsc/assets/136660034/8029643d-d2dd-4930-b057-2b6b57c0cdcb)
![E_UC13 KQ CRO($TI0%XGU8](https://github.com/bnb-chain/bsc/assets/136660034/d426736d-11df-460e-bd17-088d5dcc83f8)

**Comment by CocoStarZ** [comment]
What modifications have you done to geth? have you tried the official one and see if the problem is still there?

**Comment by zzzckck** [comment]
Sorry, we do not have resource to check issues of non-official release.
