### ISSUE TITLE
How to convert Path-Base-State-Scheme to archive node.

### ISSUE THREAD

**Issue by 0x1un** [bnb-chain/bsc#2291]
how do I change to archive mode halfway through a full node that is based on pbss and --state.scheme=path? Because I want to get the data of debug_traceBlockByNumber.

**Comment by 0x1un** [comment]
`--gcmode` doesn't seem to support `--state.scheme=path`

**Comment by weiihann** [comment]
PBSS doesn't support archive mode, this is true even for go-ethereum. Also, I'd recommend using other clients like Erigon for archive node (https://github.com/node-real/bsc-erigon) because the hardware requirement is more reasonable.

**Comment by 0x1un** [comment]
if pbss doesn't support archive, will the official bnb archive gradually migrate to erigon too? Will you also be ditching the hash-based geth-archive-node internally?

**Comment by weiihann** [comment]
I don't think we have plans on removing hash-based geth-archive-node, for now. It's just that the hardware requirement is just not feasible. When geth releases PBSS + Archive mode, maybe that'll help reduce the storage requirement for geth-archive node.

**Comment by 0x1un** [comment]
> I don't think we have plans on removing hash-based geth-archive-node, for now. It's just that the hardware requirement is just not feasible. When geth releases PBSS + Archive mode, maybe that'll help reduce the storage requirement for geth-archive node.

@weiihann 
That means pbss+archive is possible in the future?

**Comment by weiihann** [comment]
I believe the geth team is working on it.
<img width="1003" alt="image" src="https://github.com/bnb-chain/bsc/assets/47109095/99aa7648-a4f1-41cd-9d14-b03e744fb0df">
Source: [https://github.com/ethereum/go-ethereum/issues/28253](url)

**Comment by 0x1un** [comment]
@weiihann Thank you very much for your reply, I probably understand it~~

**Comment by weiihann** [comment]
No problem, let us know if you have more questions :)

**Comment by Aracki** [comment]
Is it possible to run Pebble BNB node but with hash state scheme?

**Comment by zzzckck** [comment]
> Is it possible to run Pebble BNB node but with hash state scheme?

you mean `hash state scheme` with PebbleDB? yes, it is possible, but not sure if there is any bug, as it is not the recommend way.

**Comment by soem** [comment]
According to the new release v1.4.13, there will be no **HashSchema** support in the future.

https://github.com/bnb-chain/bsc/releases/tag/v1.4.13
> HashSchema&LevelDB mode will be discontinued after September 30, 2024, will be replaced by PathSchema&PebbleDB mode

Does that mean it is the **PLAN** to remove the hash-based geth archive node?
