### ISSUE TITLE
Inconsistent version reported in v1.3.11

### ISSUE THREAD

**Issue by hazim-j** [bnb-chain/bsc#2303]
Running `geth version` on v1.3.11 will report v1.3.10.

On mac `geth version` returns:

```
Geth
Version: 1.3.10
Git Commit: 9fb0241eab1cbf14cd46be4576d6a97ad57c8064
Architecture: amd64
Go Version: go1.21.7
Operating System: darwin
GOPATH=
GOROOT=
```

Confirmed when built from source too.

**Comment by zjubfd** [comment]
Thanks for report this, we are deciding whether this worth another release..

**Comment by Pjrich1313** [comment]
![lightning-network-capacity-all-1696300010](https://github.com/bnb-chain/bsc/assets/129231067/429e55c7-bbdf-4438-81a0-0e44a5fe034e)

**Comment by zzzckck** [comment]
updated: https://github.com/bnb-chain/bsc/releases/tag/v1.3.12
