### ISSUE TITLE
Geth Freezer functionality underutilized

### ISSUE THREAD

**Issue by DefiDebauchery** [bnb-chain/bsc#233]
#### System information

Geth version: `Geth/v1.1.0-beta-032970b2/linux-amd64/go1.15.5`
OS & Version: Ubuntu Linux

#### Expected behaviour

According to the Ethereum Foundation's post on Geth 1.9 , they had introduced a separation of the database between live and 'ancient' sections, with the threshold being 3 epochs (~90K blocks).
Source: https://blog.ethereum.org/2019/07/10/geth-v1-9-0/ - Section "Freezer"

I had hoped this functionality would have been operational in some usable form.

#### Actual behaviour

`node/geth/chaindata/ancient` is only 119GB, with 1TB continuing to live in the hot LevelDB state. 

Since NVMe is required for live states even for fullnodes, enabling further usage of the freezer could greatly alleviate resource requirements.

**Comment by RenRick** [comment]
Freezer(ancient) is used to keep old block data(header/body/...), not data about contract & account. Most part of the 1TB data in LevelDB is about state data for contract & account. It will be accessed when executing block. So these data can't be put into freezer(ancient).

**Comment by shiziwen** [comment]
So, how many blocks still will be stored in levelDB?
