### ISSUE TITLE
Mined transaction not ordered by gasprice

### ISSUE THREAD

**Issue by nikolinsko** [bnb-chain/bsc#2349]
Just noticed the following behavior on this [block](https://bscscan.com/txs?block=37358767&p=5):

[position 3](https://bscscan.com/tx/0x06dff52dfb3e5c22cdb27d090ee7eb6e926b81e2f6b5036ea785827932a3544d) - 86.22776381  GWEI
[position 4](https://bscscan.com/tx/0xb4b9145644600a410763a093c76444bcf0f21ad19ea61e4a66dc96f2a6af77ea) - 1 GWEI
[position 5](https://bscscan.com/tx/0x0bd08d3d0fe5af5494940b12cc840e369097ea37de21ea3dc4c73033c2f4ded8) - 86.22776381  GWEI

seems to be a clear manipulation of the tx order, or am i missing something?

seems related to: #1170

**Comment by zzzckck** [comment]
it is likely a MEV bundle transaction, it is known and explained in FAQ, close this one.
