### ISSUE TITLE
txpool.pricelimit does not match the description

### ISSUE THREAD

**Issue by rayn316** [bnb-chain/bsc#2351]
#### System information

Geth version: v1.3.9
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
Program help description content
```
    --txpool.pricelimit value      (default: 1)
          Minimum gas price tip to enforce for acceptance into the pool
```
But the actual value obtained through json-rpc eth_gasPrice is 3gwei, not 1gwei

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by rayn316** [comment]
It should be in the configuration file. The default value is caused by returning 3.

**Comment by weiihann** [comment]
If your configuration file looks something like:
```
[Eth.TxPool]
...
PriceLimit = 3000000000
```

change `3000000000` to `1000000000` and try again.

**Comment by rayn316** [comment]
```
[Eth.Miner]
GasPrice = 3000000000
```
The test shows that when this parameter exists in the configuration file, the command line parameter --txpool.pricelimit=1 cannot take effect.
This is a strange effect

**Comment by rayn316** [comment]
This parameter has been removed during testing
```
[Eth.TxPool]
...
PriceLimit = 3000000000
```

**Comment by weiihann** [comment]
Ahh... I'll take a look at it.

**Comment by weiihann** [comment]
I got it mixed up, `eth_gasPrice` is affected by `Eth.Miner.GasPrice`, not `Eth.TxPool.PriceLimit`, they are separate things.

`eth_gasPrice` is determined by the last gas price of the latest block of your node (or default to Eth.Miner.GasPrice, if the node is not synced). `--txpool.pricelimit` is used to enforce a minimum gas price rule for transactions to enter your node's mempool.

**Comment by rayn316** [comment]
I am confused about this. Miner is usually a parameter used by block producers, and the nodes are in a synchronized state, so the gas should follow the market changes, but the display is always 3gwei. It is not until these two configurations are deleted in the configuration file tha 1gwei is returned in the json-rpc.
I agree that pricelimit limits tx from entering the memory pool.

**Comment by weiihann** [comment]
You're right, I'll need to dive deeper into why `eth_gasPrice` is always sticking to the pre-configured gas price rather than following the chain. Please hold on to this issue for a while.

**Comment by zhk101** [comment]
which begs the question - was there a validator vote to slash the gas price from 3 to 1? Noticed it to be 1 since a few days now. Or only some validators are accepting this?
Last year there was a announcement about the gas price slashing but can't find anything about the recent one?

**Comment by zzzckck** [comment]
> I am confused about this. Miner is usually a parameter used by block producers, and the nodes are in a synchronized state, so the gas should follow the market changes, but the display is always 3gwei. It is not until these two configurations are deleted in the configuration file tha 1gwei is returned in the json-rpc. I agree that pricelimit limits tx from entering the memory pool.

yes, it could be a little bit confusing, I will to explain it:
1. txpool.pricelimit: it is the for the TxPool, price bellow will not be reject and the Tx can not enter TxPool.
2. for rpc `eth_gasPrice`, it is mainly related to the GPO module, the GPO has minGasPrice/maxGasPrice configuration:
```
[Eth.GPO]
Blocks = 20   // default 20
Percentile = 60 // default 60
OracleThreshold = 1000 // default: 10000
# Default     // default nil, will use Miner.GasPrice, as the minimum value for `eth_gasPrice`
# MaxPrice    // default: 100Gwei, the maximum value for `eth_gasPrice`
# IgnorePrice   // default: 4Wei
```
<img width="819" alt="image" src="https://github.com/bnb-chain/bsc/assets/152148891/0e33d35d-bd7d-4df7-a105-572fdc99bd6f">
It could be confusing, the Miner.GasPrice is used as the minimum `eth_gasPrice`

**Comment by zzzckck** [comment]
> which begs the question - was there a validator vote to slash the gas price from 3 to 1? Noticed it to be 1 since a few days now. Or only some validators are accepting this? Last year there was a announcement about the gas price slashing from 5 to 3 but can't find anything about the recent one?

AFAIK, there is no such kind of announcement right now, but it is true most validators accept 1Gwei gasprice now.
