### ISSUE TITLE
########## BAD BLOCK ######### Geth/v1.4.3-7f3f72ed-20240321/linux-amd64/go1.21.8

### ISSUE THREAD

**Issue by AlexKNM** [bnb-chain/bsc#2353]
#### System information
 instance=Geth/v1.4.3-7f3f72ed-20240321/linux-amd64/go1.21.8

Geth version:  instance=Geth/v1.4.3-7f3f72ed-20240321/linux-amd64/go1.21.8

OS & Version: Ubuntu 22.04
Commit hash : (if `develop`)
t=2024-03-29T20:34:44+0000 lvl=error msg="\n########## BAD BLOCK #########\nBlock: 37402393 (0x9b13f236f13dc4058835200f8bc1016ad14ba1c7df9ae680ae894509f2fe4f4f)\nMiner: 0x72b61c6014342d914470eC7aC2975bE345796c2b\nError: withdrawals prese
nt in block body\nPlatform: geth (devel) go1.21.8 amd64 linux\nVCS: 7f3f72ed-20240321 (dirty)\nChain config: &params.ChainConfig{ChainID:56, HomesteadBlock:0, DAOForkBlock:<nil>, DAOForkSupport:false, EIP150Block:0, EIP155Block:0, EIP158
Block:0, ByzantiumBlock:0, ConstantinopleBlock:0, PetersburgBlock:0, IstanbulBlock:0, MuirGlacierBlock:0, BerlinBlock:31302048, YoloV3Block:<nil>, CatalystBlock:<nil>, LondonBlock:31302048, ArrowGlacierBlock:<nil>, GrayGlacierBlock:<nil>
, MergeNetsplitBlock:<nil>, ShanghaiTime:(*uint64)(0xc0004ece58), KeplerTime:(*uint64)(0xc0004ece60), FeynmanTime:(*uint64)(nil), FeynmanFixTime:(*uint64)(nil), CancunTime:(*uint64)(nil), PragueTime:(*uint64)(nil), VerkleTime:(*uint64)(n
il), TerminalTotalDifficulty:<nil>, TerminalTotalDifficultyPassed:false, RamanujanBlock:0, NielsBlock:0, MirrorSyncBlock:5184000, BrunoBlock:13082000, EulerBlock:18907621, GibbsBlock:23846001, NanoBlock:21962149, MoranBlock:22107423, Pla
nckBlock:27281024, LubanBlock:29020050, PlatoBlock:30720096, HertzBlock:31302048, HertzfixBlock:34140700, Ethash:(*params.EthashConfig)(nil), Clique:(*params.CliqueConfig)(nil), Parlia:(*params.ParliaConfig)(0x48ce220)}\nReceipts: \n####
##########################\n"

#### Expected behaviour

To not have these blocks.
#### Actual behaviour
Error

#### Steps to reproduce the behaviour
Update geth to the latest version and let it run for a while..

#### Backtrace
A lot of errors like this:
t=2024-03-29T20:39:20+0000 lvl=error msg="\n########## BAD BLOCK #########\nBlock: 37402485 (0xb6c5e140c73f94288aca9ab484ed938248e10407fc3e7758477e0379083ce8de)\nMiner: 0xe2d3A739EFFCd3A99387d015E260eEFAc72EBea1\nError: withdrawals prese
nt in block body\nPlatform: geth (devel) go1.21.8 amd64 linux\nVCS: 7f3f72ed-20240321 (dirty)\nChain config: &params.ChainConfig{ChainID:56, HomesteadBlock:0, DAOForkBlock:<nil>, DAOForkSupport:false, EIP150Block:0, EIP155Block:0, EIP158
Block:0, ByzantiumBlock:0, ConstantinopleBlock:0, PetersburgBlock:0, IstanbulBlock:0, MuirGlacierBlock:0, BerlinBlock:31302048, YoloV3Block:<nil>, CatalystBlock:<nil>, LondonBlock:31302048, ArrowGlacierBlock:<nil>, GrayGlacierBlock:<nil>
, MergeNetsplitBlock:<nil>, ShanghaiTime:(*uint64)(0xc0004ece58), KeplerTime:(*uint64)(0xc0004ece60), FeynmanTime:(*uint64)(nil), FeynmanFixTime:(*uint64)(nil), CancunTime:(*uint64)(nil), PragueTime:(*uint64)(nil), VerkleTime:(*uint64)(n
il), TerminalTotalDifficulty:<nil>, TerminalTotalDifficultyPassed:false, RamanujanBlock:0, NielsBlock:0, MirrorSyncBlock:5184000, BrunoBlock:13082000, EulerBlock:18907621, GibbsBlock:23846001, NanoBlock:21962149, MoranBlock:22107423, Pla
nckBlock:27281024, LubanBlock:29020050, PlatoBlock:30720096, HertzBlock:31302048, HertzfixBlock:34140700, Ethash:(*params.EthashConfig)(nil), Clique:(*params.CliqueConfig)(nil), Parlia:(*params.ParliaConfig)(0x48ce220)}\nReceipts: \n####
##########################\n"

When submitting logs: please submit them as text and not screenshots.

**Comment by CocoStarZ** [comment]
Has you node finished syncing? if yes, you can ignore the bad block messages

**Comment by zzzckck** [comment]
Checked the 2 blocks: 37402393 and 37403574, the `withdrawals` are both nil on my device.
@AlexKNM could you help check:
1.How often do you notice this error message? 
2.Can your node keep syncing after detecting this Bad Block?

**Comment by AlexKNM** [comment]
> Checked the 2 blocks: 37402393 and 37403574, the `withdrawals` are both nil on my device. @AlexKNM could you help check: 1.How often do you notice this error message? 2.Can your node keep syncing after detecting this Bad Block?
1. From time to time. It can be several hours in between and almost always at startup/restart.
2.  Yes.
