### ISSUE TITLE
Questions about transaction ordering

### ISSUE THREAD

**Issue by lmcapp** [bnb-chain/bsc#2354]
This is simply confusing.
I know that the mev relay will sort the arbitrage trading package first, so will the remaining transactions still be sorted by gas price? I have observed that many regular transactions are not sorted by gas price. Have the sorting rules changed?

**Comment by AlexKNM** [comment]
Forget sorting. It is not relevant anymore.

**Comment by zzzckck** [comment]
> This is simply confusing. I know that the mev relay will sort the arbitrage trading package first, so will the remaining transactions still be sorted by gas price? I have observed that many regular transactions are not sorted by gas price. Have the sorting rules changed?

regular transactions should follow the gasPrice rule, do you give more detail? like which block and transaction, we can do some investigation.

**Comment by lmcapp** [comment]
[37910207](https://bscscan.com/block/37910207)
check this block,WTF!!!
