### ISSUE TITLE
how to make transaction with 1 gas 

### ISSUE THREAD

**Issue by kugimiya530** [bnb-chain/bsc#2356]
I saw some ppl can make transaction with 1 gas

like 2~3months ago the specify version can do this

but after i upgrade it's can't now

how to make my node can my own rpc node do this?

**Comment by CocoStarZ** [comment]
bsc gas price is 1gwei now, you can just specify it in your tx

**Comment by kugimiya530** [comment]
> bsc gas price is 1gwei now, you can just specify it in your tx

Hi thx for reply

yes i just try with public rpc and i can specify 1 gas

but if i use my own  fullnode  it's can't specify 1 gas

my geth version is 1.3.10 and running PBSS&PebbleDB

i saw the logs  1.3.10~1.3.12 didn't change anything about this   did u have any idea for this issue?

**Comment by weiihann** [comment]
What's the config for your full node?

**Comment by kugimiya530** [comment]
> What's the config for your full node?

Hi sir it's

./geth --config ./config.toml --datadir ./node --cache 24000 --rpc.allow-unprotected-txs --history.transactions 0 --ws --ws.addr 127.0.0.1 --ws.origins '*' --ws.api eth,net,web3,txpool,debug --http.api eth,net,web3,txpool,debug --syncmode=full --state.scheme=path --rpc.txfeecap 0 --maxpeers 100 --ipcpath /geth.ipc --tries-verify-mode=local --pruneancient --db.engine=pebble

**Comment by kugimiya530** [comment]
can do anything i want, just can't specify 1 gas

**Comment by weiihann** [comment]
Oh I mean the content of your `./config.toml`, could you share it here?

**Comment by kugimiya530** [comment]
[Eth]
NetworkId = 56
LightPeers = 0
TrieTimeout = 150000000000


[Eth.Miner]
GasCeil = 140000000
GasPrice = 3000000000
Recommit = 10000000000

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 3000000000
PriceBump = 10
AccountSlots = 200
GlobalSlots = 8000
AccountQueue = 200
GlobalQueue = 4000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 1000

[Node]
IPCPath = "geth.ipc"
HTTPHost = "127.0.0.1"
InsecureUnlockAllowed = false
HTTPPort = 16666
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia","debug"]
WSPort = 16888
WSModules = ["net", "web3", "eth","txpool","debug"]

[Node.P2P]
MaxPeers = 100
NoDiscovery = false
StaticNodes = []
ListenAddr = ":30311"
EnableMsgEvents = false

[Node.LogConfig]
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""

**Comment by kugimiya530** [comment]
doesn't seems special  O口O

**Comment by weiihann** [comment]
If you're submitting 1Gwei transaction through your node, you need to change `PriceLimit` to `1000000000`.

**Comment by kugimiya530** [comment]
oh!!!!  thx alot

**Comment by kugimiya530** [comment]
that make sense , but i don't remember i was change that before, when i can use it few version ago  haha 

anyway  thx!!
