### ISSUE TITLE
Looking for peers with hundreds peercount

### ISSUE THREAD

**Issue by daron4ever** [bnb-chain/bsc#2362]
#### System information

Geth version: `v1.3.13`
OS & Version: Linux
Commit hash : (if `develop`)

I have more than 300 peerCount and the block is not on the time sync becuse of "Looking for peers".
For eth.syncing: false

```
./geth_linux --config ./config.toml --datadir ./node --syncmode snap --cache 60000 --metrics --verbosity 3 --rpc.allow-unprotected-txs --history.transactions 0 --ws.origins "*" --rpc.txfeecap 0 --maxpeers 500 --ws --ws.api net,web3,eth,admin,debug --snapshot=false --pipecommit

```

![Screenshot 2024-04-02 at 01 46 21](https://github.com/bnb-chain/bsc/assets/18229512/da56c4a7-6797-41a5-b29d-093f5d47fa64)

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by STdevK** [comment]
Are you syncing the node with a snapshot? If yes, which snapshot did you use?

**Comment by weiihann** [comment]
The log seems normal to me, what's the issue here?

The log `Looking for peers` could appear as your maximum number of dialed peers have not been reached yet, so it will continue to look for peers.

`eth.syncing` is `false` is normal behaviour, it means that your node is up to date and is currently not syncing.

**Comment by daron4ever** [comment]
> Are you syncing the node with a snapshot? If yes, which snapshot did you use?

I used snapshot last year so i dont remember exact version and maintain the sync with pruning.

**Comment by daron4ever** [comment]
> The log seems normal to me, what's the issue here?
> 
> The log `Looking for peers` could appear as your maximum number of dialed peers have not been reached yet, so it will continue to look for peers.
> 
> `eth.syncing` is `false` is normal behaviour, it means that your node is up to date and is currently not syncing.

The latest block is few block behind even eth.syicing is false. If you see the timestamp, it has a long latency with new block sync.

[ update]
After I tried to remove /geth/nodes and restart node, i didnt see any peerCount. it showed 0 peerCount.
So I added a staticnode and it sync well with the staticnode only.

However, I still dont see any peerCount. It is 1 peerCount now.

![Screenshot 2024-04-02 at 15 37 21](https://github.com/bnb-chain/bsc/assets/18229512/ef8eab64-e52f-4e5a-bc6c-cea768bdc786)

**Comment by weiihann** [comment]
Wait for a bit (1 or 2 hours) and see if the peer count increases. Do update us here again.

**Comment by daron4ever** [comment]
> Wait for a bit (1 or 2 hours) and see if the peer count increases. Do update us here again.

I still got 1 static peerCount.

**Comment by daron4ever** [comment]
> It might be due to this: <img alt="image" width="809" src="https://private-user-images.githubusercontent.com/47109095/319013019-c9174409-f2e9-4994-a3be-55ea39649a8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzQxNzQsIm5iZiI6MTcxMjEzMzg3NCwicGF0aCI6Ii80NzEwOTA5NS8zMTkwMTMwMTktYzkxNzQ0MDktZjJlOS00OTk0LWEzYmUtNTVlYTM5NjQ5YThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA4NDQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjNmY5YmI3NWVhZGQ1MWVkZjdiZmRlNzI5ZmY5OWFhMzE4NTlkY2RmZTU3NGFmMWQxN2RhZDQ4OTI0Nzc4NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IQ_5I2fbQ52SxN583LMVK95Jp-KBfl5OFJBR5QsFNXg"> Check the [FAQ](https://github.com/bnb-chain/bsc/issues/1947) here.
> 
> Try creating a new nodekey file following the instruction and see if it works for you.

Thanks. I removed nodekey but still 1 peerCount.

**Comment by daron4ever** [comment]
no more issue after i updated version v1.4.6

**Comment by daron4ever** [comment]
> Then it might be caused by some P2P networking issues.

peercount is coming back after i updated version v1.4.6
