### ISSUE TITLE
cant access bnb funds on bnb beacon chain - where can i get support?

### ISSUE THREAD

**Issue by ofiryy** [bnb-chain/bsc#2370]
cant access bnb funds on bnb beacon chain - where can i get support?
i have a trezor with bnb coin on it, but when i try to connect from with your online 3rd party wallet: https://www.bnbchain.org/en/unlock

i get this message:
**“Connect v8 is deprecated. Please ask your DeFi platform/wallet developers (not Trezor) to update to Connect v9.”**

can you please help me or reference me to where i can get tech support for this ?

thanks

**Comment by STdevK** [comment]
1. Please use the Firefox browser.
2. Turned off "enhanced tracking protection" https://forum.trezor.io/t/problems-accessing-binance-dex-with-trezor/14102
3. Install the latest trezor bridge. https://suite.trezor.io/web/bridge/ (skip if you have already done so)

**Comment by ofiryy** [comment]
done what you say, i see improvment, i get my wallet address and confirm on trezor,
but then its "Connecting..." for like 10 minutes and i dont see the funds yet , is that ok ? 
how long the connection should take ?

**Comment by ofiryy** [comment]
now it looks like im connected to "Binance Smart Chain Mainnet", but the "Trade History" still shows nothing,
and im sure this address im conneced to has coins because i checked in the bnb beacon explorer,
how could i see the funds in this wallet ?
could the prblem be im connected  "Binance Smart Chain Mainnet" ?
and if so how can i change it ?
