### ISSUE TITLE
No docker image for 1.4.4-beta version

### ISSUE THREAD

**Issue by tornadocontrib** [bnb-chain/bsc#2372]
cc @zzzckck

**Comment by zzzckck** [comment]
noted, will check.
But v1.4.4-beta is not a stable release yet, need more time for stability test. May I know why you wanna to try v1.4.4-beta?

**Comment by tornadocontrib** [comment]
@zzzckck I need a faster, lighter version of the node which one would be? Also it would be great if the node supports path based state scheme as well.

**Comment by zzzckck** [comment]
> @zzzckck I need a faster, lighter version of the node which one would be? Also it would be great if the node supports path based state scheme as well.

check out: https://github.com/bnb-chain/bsc-snapshots/issues/349
<img width="918" alt="image" src="https://github.com/bnb-chain/bsc/assets/152148891/487728a1-3806-44e7-b27f-45176856be54">
this one is the lightest, only 200GB needed, but it does not have trie, which means it can not be used as validator.

**Comment by tornadocontrib** [comment]
Ah I see.. since I need all the receipts I would have 2TB one instead thank you.

**Comment by zzzckck** [comment]
The docker image for v1.4.4-beta should be ready now, could you help confirm? @tornadocontrib

**Comment by tornadocontrib** [comment]
@zzzckck I think it works now thank you
