### ISSUE TITLE
I am seeing this issue as described in https://github.com/axios/axios/issues/6179

### ISSUE THREAD

**Issue by Pjrich1313** [bnb-chain/bsc#2374]
I am seeing this issue as described in https://github.com/axios/axios/issues/6179

This looks to be regression in 1.15.4 as it both workflows below work in 1.15.3. Whereas in 1.15.4+,

Basically this would return 401 after the redirect as the auth options don't seem to be propagated.
```
await axios.get('url_that_returns_301_and_then_redirects',
        { 
            auth: { 
                username: 'username',
                password: 'password'
            }
        });
```

whereas this works and returns 200:
```
await axios.get('url_that_redirects_and_returns_301',
        headers: {
                'Authorization': 'Basic base64_encoding_of_username_password',
            },
```

Through debugging, I can confirm it gets lost because the below works:
```
await axios.get('url_that_redirects_and_returns_301',
        { 
            auth: { 
                username: 'username',
                password: 'password'
            },
            beforeRedirect: (opts, res) => {
                 opts.auth = 'base64_encoding_of_username_password'
            }
        });
```

_Originally posted by @kevkcc in https://github.com/follow-redirects/follow-redirects/issues/243_

**Comment by zzzckck** [comment]
@Pjrich1313 what is it? anything we can do?
