### ISSUE TITLE
stop node sync on block 37191566

### ISSUE THREAD

**Issue by mtb-pro** [bnb-chain/bsc#2382]
Hello
my node stop on 37191566 after update to v1.3.13
please help to solve it
`> eth.syncing
{
  currentBlock: 37191566,
  healedBytecodeBytes: 0,
  healedBytecodes: 0,
  healedTrienodeBytes: 0,
  healedTrienodes: 0,
  healingBytecode: 0,
  healingTrienodes: 0,
  highestBlock: 37701312,
  startingBlock: 37191625,
  syncedAccountBytes: 0,
  syncedAccounts: 0,
  syncedBytecodeBytes: 0,
  syncedBytecodes: 0,
  syncedStorage: 0,
  syncedStorageBytes: 0
}
`

**Comment by STdevK** [comment]
Can you share the `config.toml` and which snapshot is used for the node?

**Comment by mtb-pro** [comment]
config.toml 

`[Eth]
NetworkId = 56
#SyncMode = "full"
#NoPruning = false
#NoPrefetch = false
LightPeers = 100
##UltraLightFraction = 75
##TrieTimeout = 100000000000
TrieTimeout = 150000000000
#EnablePreimageRecording = false
#EWASMInterpreter = ""
#EVMInterpreter = ""
#DatabaseCache = 32768
#StateHistory = 0
#StateScheme = "path"

[Eth.Miner]
#GasFloor = 30000000
#GasCeil = 40000000
#GasPrice = 1000000000
#Recommit = 10000000000
GasCeil = 140000000
GasPrice = 3000000000
Recommit = 10000000000
##Noverify = false

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
#PriceLimit = 1000000000
#PriceBump = 10
#AccountSlots = 512
#GlobalSlots = 10000
#AccountQueue = 256
#GlobalQueue = 5000
#Lifetime = 10800000000000
PriceLimit = 3000000000
PriceBump = 10
AccountSlots = 200
GlobalSlots = 8000
AccountQueue = 200
GlobalQueue = 4000

[Eth.GPO]
Blocks = 20
Percentile = 60
`

run :

`ExecStart=/data/bsc/geth --syncmode=full --config /data/bsc/config.toml --datadir /data/bsc/node --keystore /data/bsc/keystore/ --rpc.allow-unprotected-txs --maxpeers 100  --nat extip:_._._._  --cache=20480 --snapshot=false  --http --http.addr 0.0.0.0 --http.port 8545 --ws --ws.port 8546  --ws.addr 0.0.0.0 --ws.origins="*"
`

**Comment by zzzckck** [comment]
> Hello my node stop on 37191566 after update to v1.3.13 please help to solve it `> eth.syncing { currentBlock: 37191566, healedBytecodeBytes: 0, healedBytecodes: 0, healedTrienodeBytes: 0, healedTrienodes: 0, healingBytecode: 0, healingTrienodes: 0, highestBlock: 37701312, startingBlock: 37191625, syncedAccountBytes: 0, syncedAccounts: 0, syncedBytecodeBytes: 0, syncedBytecodes: 0, syncedStorage: 0, syncedStorageBytes: 0 } `

could you provide logs of your node?

**Comment by mtb-pro** [comment]
can you send guide to reinstall bsc node again?

**Comment by zzzckck** [comment]
> Can you send the guide to reinstall bsc node? It seems that the settings and setup have changed

You may refer: https://github.com/bnb-chain/bsc?tab=readme-ov-file#running-geth

**Comment by buddh0** [comment]
@epsil0n0 It seems that your node run in pbss mode, but no set in config.toml and setup flags
have ever you set it? which data snapshots in   https://github.com/bnb-chain/bsc-snapshots you use ? 
could you provide more log, especially the log around stop and start?

**Comment by buddh0** [comment]
@mtb-pro @epsil0n0 the most possible reason is that the node is not shutdown well.
how did you shutdown the node? force kill?
the log around stop and start is helpful, pls provide if it still exsits.

**Comment by epsil0n0** [comment]
@buddh0 
I used the Path-Base-State-Scheme snapshot.
I run the noe with this command:
geth --syncmode=full --config /data/bsc/config.toml --datadir /data/bsc/node --keystore /data/bsc/keystore/ --state.scheme=path --maxpeers 100   --cache=20480 --snapshot=false  --http --http.addr 0.0.0.0 --http.port 8545 --ws --ws.port 8546  --ws.addr 0.0.0.0 --ws.origins="*"

**Comment by epsil0n0** [comment]
@buddh0 
full log
[bsc.log](https://github.com/bnb-chain/bsc/files/15007249/bsc.log)

**Comment by buddh0** [comment]
> @buddh0 full log [bsc.log](https://github.com/bnb-chain/bsc/files/15007249/bsc.log)

thanks!

the log about stop is very helpful, I will appreicate if you can provide
