### ISSUE TITLE
transaction underpriced: tip needed 3000000000, tip permitted 1000000000

### ISSUE THREAD

**Issue by adapt7** [bnb-chain/bsc#2387]
After few months I tried to send swap transaction from my node.js app on mainnet and got this error:

```transaction underpriced: tip needed 3000000000, tip permitted 1000000000```

Couldn't find any details quickly - how exactly these tips work? What needs to be added technically to the transaction structure to pass this? What are rules of using the tips? Why I got this error message in the first place - does it mean I cannot send transactions without extra tip from now on?

Appreciate for any links or documents where I can find answers. Thank you.

**Comment by OmarMBNB** [comment]
Hello I hope you're doing well.

Please share the following to assist you better:

1. geth startup command
2. config.toml file
3. [Optional] Peer list, just the "name" will do

If possible, please show the debugging logs as well. Thanks!
