### ISSUE TITLE
 err="retrieved hash chain is invalid: expected tx hash

### ISSUE THREAD

**Issue by wetezos** [bnb-chain/bsc#2392]
My node suddenly reported this error, how should I solve it?

geth version
Geth
Version: 1.3.13
Git Commit: bae7e6b52e31bfca03bfa0a659b3e17911925c6b
Git Commit Date: 20240401
Architecture: amd64
Go Version: go1.21.8
Operating System: linux
GOPATH=
GOROOT=/opt/hostedtoolcache/go/1.21.8/x64

error log:

`Apr 11 14:40:41 Ubuntu-1804-bionic-64-minimal geth[10696]:   143: cumulative: 17379092 gas: 51591 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xcbae66c5de7849dc1f6cfd642c1c8132949833eb83a9256fc7911115d34f4fad logs: [0xc0148cc6e0] bloom: 00000000000000000000000000000040000000088000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000008000000000000080000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000004008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000010000000200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state:
Apr 11 14:40:41 Ubuntu-1804-bionic-64-minimal geth[10696]:   144: cumulative: 17400092 gas: 21000 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x997df3d3f49fb77ae32dee54ddf979645d30092a933fa4794726cf3411f0b601 logs: [] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state:
Apr 11 14:40:41 Ubuntu-1804-bionic-64-minimal geth[10696]:   145: cumulative: 17421092 gas: 21000 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xf06819ba04c83850b0e0890f3263d0080461c993cde71ee0456422425ac87067 logs: [] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state:
Apr 11 14:40:41 Ubuntu-1804-bionic-64-minimal geth[10696]: ##############################
Apr 11 14:40:41 Ubuntu-1804-bionic-64-minimal geth[10696]:  
Apr 11 14:40:41 Ubuntu-1804-bionic-64-minimal geth[10696]: WARN [04-11|14:40:41.782] Synchronisation failed, dropping peer    peer=1b104cdb92cb45e58e9255ddf5abc68fe176c6aeb5f0ac9e6e3c3432fef19271 err="retrieved hash chain is invalid: expected tx hash 0x91a49abdbe0d1bc97361ef1d68970c6cb225703bd1d4708f09a221a39c5ca5a2, get 0x8dd5127db9ff2f03153328a0e7e20fef0f52e5aa67fc944ea8463e4fd5b78391, nonce 151884, to 0x0000000000000000000000000000000000001000, value 31722407257165994, gas 9223372036854775807, gasPrice 0, data f340fa0100000000000000000000000035ebb5849518aff370ca25e19e1072cc1a9fabca"`

**Comment by weiihann** [comment]
Was your node able to continue syncing?
