### ISSUE TITLE
eth.syncing bug?

### ISSUE THREAD

**Issue by baijiahei888** [bnb-chain/bsc#2394]
> eth.syncing
{
  currentBlock: 37879527,
  healedBytecodeBytes: 0,
  healedBytecodes: 0,
  healedTrienodeBytes: 0,
  healedTrienodes: 0,
  healingBytecode: 0,
  healingTrienodes: 0,
  highestBlock: 37879521,
  startingBlock: 37879517,
  syncedAccountBytes: 0,
  syncedAccounts: 0,
  syncedBytecodeBytes: 0,
  syncedBytecodes: 0,
  syncedStorage: 0,
  syncedStorageBytes: 0,
  txIndexFinishedBlocks: 8507835,
  txIndexRemainingBlocks: 29371693
}

currentBlock > highestBlock ？？？

and https://github.com/bnb-chain/bsc/issues/2332    same problem

geth version v1.3.13

--syncmode=full --tries-verify-mode=none --history.transactions=0 --db.engine=pebble

**Comment by baijiahei888** [comment]
@zzzckck

**Comment by baijiahei888** [comment]
func (prog SyncProgress) Done() bool {
	if prog.CurrentBlock <= prog.HighestBlock {
		return false
	}
	return prog.TxIndexRemainingBlocks == 0
}

the function problem

**Comment by zzzckck** [comment]
> func (prog SyncProgress) Done() bool { if prog.CurrentBlock <= prog.HighestBlock { return false } return prog.TxIndexRemainingBlocks == 0 }
> 
> the function problem

noted, I will check.

**Comment by baijiahei888** [comment]
> > func (prog SyncProgress) Done() bool { if prog.CurrentBlock <= prog.HighestBlock { return false } return prog.TxIndexRemainingBlocks == 0 }
> > 功能问题
> 
> 已注明，我会检查。

version develop

**Comment by zzzckck** [comment]
> func (prog SyncProgress) Done() bool { if prog.CurrentBlock <= prog.HighestBlock { return false } return prog.TxIndexRemainingBlocks == 0 }
> 
> the function problem

Seems like this code is ok:
```
// Done returns the indicator if the initial sync is finished or not.
func (prog SyncProgress) Done() bool {
	if prog.CurrentBlock < prog.HighestBlock {
		return false
	}
	return prog.TxIndexRemainingBlocks == 0
}
```
If your node has catch up the remote highest block, there is additional check for TxIndex,  only make sync progress as done when TxIndex is also done.

**Comment by baijiahei888** [comment]
> > func (prog SyncProgress) Done() bool { if prog.CurrentBlock <= prog.HighestBlock { return false } return prog.TxIndexRemainingBlocks == 0 }
> > 功能问题
> 
> 看起来这段代码没问题：
> 
> ```
> // Done returns the indicator if the initial sync is finished or not.
> func (prog SyncProgress) Done() bool {
> 	if prog.CurrentBlock < prog.HighestBlock {
> 		return false
> 	}
> 	return prog.TxIndexRemainingBlocks == 0
> }
> ```
> 
> 如果您的节点已赶上远程最高块，则会对事务索引进行额外检查，仅在索引也完成时将同步进度标记为已完成。
> 
> 事务索引可能需要相当长的时间，因为可能有太多事务需要索引。

OK, thanks.
