### ISSUE TITLE
 Transaction ordering problem

### ISSUE THREAD

**Issue by lmcapp** [bnb-chain/bsc#2397]
https://bscscan.com/block/37910272
Check this block. It is not sorted by gas price at all. For example, the last transaction is 3Gwei, and the sorting in the middle is also messed up. This repeater called blocksmith is totally messed up

**Comment by zzzckck** [comment]
https://github.com/bnb-chain/bsc/issues/1947
It is caused by MEV, as many validators have supported MEV now.
