### ISSUE TITLE
BSC node stop syncing 

### ISSUE THREAD

**Issue by epsil0n0** [bnb-chain/bsc#2410]
I want to run BSC full node using snapshot. But after syncing , i got this error :

t=2024-04-19T11:38:53+0200 lvl=info msg="Skip duplicated bad block"             number=37,815,805 hash=0x97af92f58918e726b15d50a0f4f4d8d2c43405bcbd50f83977c098535a3fe565
t=2024-04-19T11:38:53+0200 lvl=eror msg="\n########## BAD BLOCK #########\nBlock: 37815805 (0x97af92f58918e726b15d50a0f4f4d8d2c43405bcbd50f83977c098535a3fe565)\nMiner: 0xCc8E6d00C17eB431350C6c50d8b8F05176b90b11\nError: could not apply tx 33 [0x9a15937324365b07123953abe2e2b717138e2588168fe3febed8ce6cca2d368f]: nonce too high: address 0xBdeB5D8b6880dA44a7A8015050051F70846b2e2f, tx: 78 state: 0\nPlatform: geth (devel) go1.21.8 amd64 linux\nVCS: bae7e6b5-20240401 (dirty)\nChain config: &params.ChainConfig{ChainID:56, HomesteadBlock:0, DAOForkBlock:<nil>, DAOForkSupport:false, EIP150Block:0, EIP155Block:0, EIP158Block:0, ByzantiumBlock:0, ConstantinopleBlock:0, PetersburgBlock:0, IstanbulBlock:0, MuirGlacierBlock:0, BerlinBlock:31302048, YoloV3Block:<nil>, CatalystBlock:<nil>, LondonBlock:31302048, ArrowGlacierBlock:<nil>, GrayGlacierBlock:<nil>, MergeNetsplitBlock:<nil>, ShanghaiTime:(*uint64)(0xc000015898), KeplerTime:(*uint64)(0xc0000158a0), FeynmanTime:(*uint64)(0xc0000158a8), FeynmanFixTime:(*uint64)(0xc0000158b0), CancunTime:(*uint64)(nil), PragueTime:(*uint64)(nil), VerkleTime:(*uint64)(nil), TerminalTotalDifficulty:<nil>, TerminalTotalDifficultyPassed:false, RamanujanBlock:0, NielsBlock:0, MirrorSyncBlock:5184000, BrunoBlock:13082000, EulerBlock:18907621, GibbsBlock:23846001, NanoBlock:21962149, MoranBlock:22107423, PlanckBlock:27281024, LubanBlock:29020050, PlatoBlock:30720096, HertzBlock:31302048, HertzfixBlock:34140700, Ethash:(*params.EthashConfig)(nil), Clique:(*params.CliqueConfig)(nil), Parlia:(*params.ParliaConfig)(0x48a01d0), IsDevMode:false}\nReceipts: \n##############################\n"
t=2024-04-19T11:38:53+0200 lvl=warn msg="Synchronisation failed, dropping peer" peer=1f3dafdc07212ff4d21de9c7cb8ad71922fc4b245d46565b4e1b169e40642a90 err="retrieved hash chain is invalid: could not apply tx 33 [0x9a15937324365b07123953abe2e2b717138e2588168fe3febed8ce6cca2d368f]: nonce too high: address 0xBdeB5D8b6880dA44a7A8015050051F70846b2e2f, tx: 78 state: 0"

Can anyone help?

**Comment by jellyb0y** [comment]
The same

**Comment by jellyb0y** [comment]
That issue was helpful for me https://github.com/bnb-chain/bsc/issues/507
I rolled back 1000 blocks and afterwards the issue was solved
