### ISSUE TITLE
Is it possible to `hard fork bsc network` to launch my own public blockchain?

### ISSUE THREAD

**Issue by kasrakhamesi** [bnb-chain/bsc#2421]
I want to launch my own public blockchain, and I want it to be a hard fork of the Binance Smart Chain blockchain. Is that possible? If yes, could you please provide guidance or a specific path for the tasks I need to perform

**Comment by zzzckck** [comment]
> I want to launch my own public blockchain, and I want it to be a hard fork of the Binance Smart Chain blockchain. Is that possible? If yes, could you please provide guidance or a specific path for the tasks I need to perform

hard fork of BSC? you mean you wanna the whole state of current BSC and create your own chain based on it?
I am afraid we don't provide such kind of service.

**Comment by kasrakhamesi** [comment]
> > I want to launch my own public blockchain, and I want it to be a hard fork of the Binance Smart Chain blockchain. Is that possible? If yes, could you please provide guidance or a specific path for the tasks I need to perform
> 
> 
> 
> hard fork of BSC? you mean you wanna the whole state of current BSC and create your own chain based on it?
> 
> I am afraid we don't provide such kind of service.


No.I mean create new blockchain with bsc source code.but change chainID ( set new chainId ) and chain name.for example change from bsc to another name.and sync from 0 block.

**Comment by zzzckck** [comment]
> > > I want to launch my own public blockchain, and I want it to be a hard fork of the Binance Smart Chain blockchain. Is that possible? If yes, could you please provide guidance or a specific path for the tasks I need to perform
> > 
> > 
> > hard fork of BSC? you mean you wanna the whole state of current BSC and create your own chain based on it?
> > I am afraid we don't provide such kind of service.
> 
> No.I mean create new blockchain with bsc source code.but change chainID ( set new chainId ) and chain name.for example change from bsc to another name.and sync from 0 block.

Em, I think it is possible, the code is quite simple. but needs lots of works to let the community recognize the chainID. You just create a new chain from scratch.

**Comment by kasrakhamesi** [comment]
> > > > I want to launch my own public blockchain, and I want it to be a hard fork of the Binance Smart Chain blockchain. Is that possible? If yes, could you please provide guidance or a specific path for the tasks I need to perform
> 
> > > 
> 
> > > 
> 
> > > hard fork of BSC? you mean you wanna the whole state of current BSC and create your own chain based on it?
> 
> > > I am afraid we don't provide such kind of service.
> 
> > 
> 
> > No.I mean create new blockchain with bsc source code.but change chainID ( set new chainId ) and chain name.for example change from bsc to another name.and sync from 0 block.
> 
> 
> 
> Em, I think it is possible, the code is quite simple. but needs lots of works to let the community recognize the chainID. You just create a new chain from scratch.
> 
> But BSC does not provide any guide to do it, basically it is similar to Ethereum.

can you give me docs in eth for that?

**Comment by zzzckck** [comment]
> > > > > I want to launch my own public blockchain, and I want it to be a hard fork of the Binance Smart Chain blockchain. Is that possible? If yes, could you please provide guidance or a specific path for the tasks I need to perform
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > hard fork of BSC? you mean you wanna the whole state of current BSC and create your own chain based on it?
> > 
> > 
> > > > I am afraid we don't provide such kind of service.
> > 
> > 
> > > 
> > 
> > 
> > > No.I mean create new blockchain with bsc source code.but change chainID ( set new chainId ) and chain name.for example change from bsc to another name.and sync from 0 block.
> > 
> > 
> > Em, I think it is possible, the code is quite simple. but needs lots of works to let the community recognize the chainID. You just create a new chain from scratch.
> > But BSC does not provide any guide to do it, basically it is similar to Ethereum.
> 
> can you give me docs in eth for that?

I don't have the link and not sure if Ethereum provide any doc. you may search by yourself.
