### ISSUE TITLE
Node stuck at certain block for long period of time

### ISSUE THREAD

**Issue by stillLearning03** [bnb-chain/bsc#2422]
Geth version: `1.3.13`
OS & Version: Linux Ubuntu

Ever since updating my geth node to the new 1.3.13 version my node goes through times of complete pause, misses multiple blocks then catches up and same repeat.

the only new messages i see on my logs are: `WARN [04-23|19:10:27.628] BlockHeader at current voteBlockNumber is nil targetNumber=38,116,879 targetHash=470a98..36f357`

`WARN [04-23|19:16:39.447] Served eth_coinbase                      conn=194.67.206.49:47440  reqid=2  t="15.199µs"  err="etherbase must be explicitly specified" X-Forwarded-For=nil`

as you can see in the image sometimes it is all good quickly detecting new blocks but in other cases it is stuck for over 20 seconds..
![blocks](https://github.com/bnb-chain/bsc/assets/144373612/d916b276-6787-4452-864b-7c29eb43d889)

**Comment by stillLearning03** [comment]
also in the logs it is fine logging infos each block and then all of a sudden over 30 seconds of nothing. this never happened before i updated

![image](https://github.com/bnb-chain/bsc/assets/144373612/b7d5e89a-a1c9-4d0d-9270-93a787750781)

**Comment by zzzckck** [comment]
```
WARN [04-23|19:10:27.628] BlockHeader at current voteBlockNumber is nil targetNumber=38,116,879 targetHash=470a98..36f357
```
For the above message, you need to specify your public address for block mining rewards, with this flag:
--miner.etherbase <0x....>

**Comment by zzzckck** [comment]
**Q1: it is stuck for over 20 seconds.**
do you mean the period between: block 38116898 -> block 38116906?
![image](https://github.com/bnb-chain/bsc/assets/152148891/66462d95-99f4-46bd-a55d-01efc7353e6c)
Once your node has produced a valid block, it will be marked as recently signed and can not produce blocks. It need to wait a certain time(ValidatorSize/2), to exit the recently signed state and produce block again.

**Q2: all of a sudden over 30 seconds of nothing**
Could you provide more logs, seems like your node did not import blocks for 30s? It could be caused by connecting to unstable peers?

And could you try v1.4.5, v1.3.x will no longer be supported. v1.4.5 is the latest stable release.

**Comment by stillLearning03** [comment]
yes that is it, the node is not fetching new blocks for certain amount of time. here is some more logs : 

`Apr 24 13:31:19 Ubuntu-2004-focal-64-minimal-hwe bash[1904932]: INFO [04-24|13:31:19.312] Imported new chain segment               number=38,138,871 hash=d8855d..bbd74b miner=0xCc8E6d00C17eB431350C6c50d8b8F05176b90b11 blocks=1     txs=146   mgas=17.170   elapsed=39.021ms    mgasps=440.011  triedirty=0.00B
Apr 24 13:31:22 Ubuntu-2004-focal-64-minimal-hwe bash[1904932]: INFO [04-24|13:31:22.348] Imported new chain segment               number=38,138,872 hash=f09d2c..6cc068 miner=0xD1d6bF74282782B0b3eb1413c901D6eCF02e8e28 blocks=1     txs=258   mgas=39.424   elapsed=73.773ms    mgasps=534.397  triedirty=0.00B
Apr 24 13:31:24 Ubuntu-2004-focal-64-minimal-hwe bash[1904932]: INFO [04-24|13:31:24.395] Imported new chain segment               number=38,138,873 hash=627be9..194f51 miner=0xe2d3A739EFFCd3A99387d015E260eEFAc72EBea1 blocks=1     txs=150   mgas=14.848   elapsed=37.115ms    mgasps=400.056  triedirty=0.00B
Apr 24 13:31:28 Ubuntu-2004-focal-64-minimal-hwe bash[1904932]: INFO [04-24|13:31:28.035] Imported new chain segment               number=38,138,874 hash=87c79c..a53ffc miner=0xE9AE3261a475a27Bb1028f140bc2a7c843318afD blocks=1     txs=115   mgas=15.643   elapsed=33.179ms    mgasps=471.458  triedirty=0.00B
Apr 24 13:31:39 Ubuntu-2004-focal-64-minimal-hwe bash[1904932]: INFO [04-24|13:31:39.989] Imported new chain segment               number=38,138,878 hash=947b8b..b3fa99 miner=0x2465176C461AfB316ebc773C61fAEe85A6515DAA blocks=4     txs=614   mgas=89.315   elapsed=184.701ms   mgasps=483.568  triedirty=0.00B
Apr 24 13:31:42 Ubuntu-2004-focal-64-minimal-hwe bash[1904932]: INFO [04-24|13:31:42.467] Imported new chain segment               number=38,138,879 hash=0e4985..54e094 miner=0x295e26495CEF6F69dFA69911d9D8e4F3bBadB89B blocks=1     txs=161   mgas=20.708   elapsed=46.644ms    mgasps=443.950  triedirty=0.00B
Apr 24 13:31:45 Ubuntu-2004-focal-64-minimal-hwe bash[1904932]: INFO [04-24|13:31:45.724] Imported new chain segment               number=38,138,880 hash=d0c437..7e7664 miner=0x2D4C407BBe49438ED859fe965b140dcF1aaB71a9 blocks=1     txs=110   mgas=11.889   elapsed=29.064ms    mgasps=409.052  triedirty=0.00B
Apr 24 13:31:52 Ubuntu-2004-focal-64-minimal-hwe bash[1904932]: INFO [04-24|13:31:52.654] Imported new chain segment               number=38,138,882 hash=ddb564..748584 miner=0x460A252B4fEEFA821d3351731220627D7B7d1F3d blocks=2     txs=319   mgas=41.125   elapsed=81.058ms    mgasps=507.353  triedirty=0.00B
Apr 24 13:31:54 Ubuntu-2004-focal-64-minimal-hwe bash[1904932]: INFO [04-24|13:31:54.868] Imported new chain segment               number=38,138,883 hash=d805e9..bdfde6 miner=0x61Dd481A114A2E761c554B641742C973867899D3 blocks=1     txs=140   mgas=19.908   elapsed=32.381ms    mgasps=614.817  triedirty=0.00B
Apr 24 13:31:59 Ubuntu-2004-focal-64-minimal-hwe bash[1904932]: INFO [04-24|13:31:59.821] Deep froze chain segment                 blocks=19    elapsed=1.117ms     number=38,048,883 hash=ef79db..f473a1
Apr 24 13:32:08 Ubuntu-2004-focal-64-minimal-hwe bash[1904932]: INFO [04-24|13:32:08.469] Imported new chain segment               number=38,138,887 hash=965cfc..7f60b2 miner=0x8b6C8fd93d6F4CeA42Bbb345DBc6F0DFdb5bEc73 blocks=4     txs=824   mgas=108.931  elapsed=217.185ms   mgasps=501.557  triedirty=0.00B
Apr 24 13:32:09 Ubuntu-2004-focal-64-minimal-hwe bash[1904932]: INFO [04-24|13:32:09.812] Imported new chain segment               number=38,138,888 hash=a48249..f25218 miner=0xa6f79B60359f141df90A0C745125B131cAAfFD12 blocks=1     txs=241   mgas=33.008   elapsed=68.382ms    mgasps=482.699  triedirty=0.00B
Apr 24 13:32:12 Ubuntu-2004-focal-64-minimal-hwe bash[1904932]: INFO [04-24|13:32:12.396] Imported new chain segment               number=38,138,889 hash=59ab95..e1575b miner=0xb218C5D6aF1F979aC42BC68d98A5A0D796C6aB01 blocks=1     txs=187   mgas=21.461   elapsed=48.492ms    mgasps=442.557  triedirty=0.00B
Apr 24 13:32:39 Ubuntu-2004-focal-64-minimal-hwe bash[1904932]: INFO [04-24|13:32:39.604] Imported new chain segment               number=38,138,897 hash=0852d3..e6ba69 miner=0xee226379dB83CfFC681495730c11fDDE79BA4c0C blocks=8     txs=1685  mgas=171.671  elapsed=350.513ms   mgasps=489.769  triedirty=0.00B ignored=1
Apr 24 13:32:39 Ubuntu-2004-focal-64-minimal-hwe bash[1904932]: INFO [04-24|13:32:39.643] Imported new chain segment               number=38,138,898 hash=d84bb2..2cbc01 miner=0x1cFDBd2dFf70C6e2e30df5012726F87731F38164 blocks=1     txs=80    mgas=8.072    elapsed=26.558ms    mgasps=303.944  triedirty=0.00B
Apr 24 13:32:42 Ubuntu-2004-focal-64-minimal-hwe bash[1904932]: INFO [04-24|13:32:42.849] Imported new chain segment               number=38,138,899 hash=990bc4..a89ba2 miner=0x2465176C461AfB316ebc773C61fAEe85A6515DAA blocks=1     txs=244   mgas=30.558   elapsed=54.956ms    mgasps=556.041  triedirty=0.00B
Apr 24 13:32:45 Ubuntu-2004-focal-64-minimal-hwe bash[1904932]: INFO [04-24|13:32:45.320] Imported new chain segment               number=38,138,900 hash=f3774f..36266f miner=0x295e26495CEF6F69dFA69911d9D8e4F3bBadB89B blocks=1     txs=165   mgas=21.292   elapsed=43.155ms    mgasps=493.383  triedirty=0.00B`

you can see from 13:31:19 to 13:31:59 it seems to be ok, then a 9 second pause of no new blocks, and then from 13:32:12 to 13:32:39 nothing.. no blocks for nearly 30 seconds something is wrong

ill update to the version you suggested and check if there are similar issues

**Comment by stillLearning03** [comment]
updating to 1.4.5 version has seemed to resolve the issue, thank you
