### ISSUE TITLE
Is v1.4.6 mainnet ready?

### ISSUE THREAD

**Issue by andreclaro** [bnb-chain/bsc#2434]
We are still running `v1.3.13` on mainnet. Can we upgrade to `v1.4.6`?

https://github.com/bnb-chain/bsc/releases/tag/v1.4.6

**Comment by CocoStarZ** [comment]
Yes, you could upgrade and try it.

**Comment by zzzckck** [comment]
> We are still running `v1.3.13` on mainnet. Can we upgrade to `v1.4.6`?
> 
> https://github.com/bnb-chain/bsc/releases/tag/v1.4.6

yes, you can try v1.4.6, there is no big change about the usage, suppose you can just upgrade the binary.
gradually we will switch to v1.4.x, v1.3.13 will no longer be supported

**Comment by andreclaro** [comment]
So this is the first 1.14.x release supporting mainnet, right? Did you already try in your nodes?

**Comment by zzzckck** [comment]
> So this is the first 1.14.x release supporting mainnet, right? Did you already try in your nodes?

the first stable release of v1.4.x is v1.4.5, it supports mainnet.
Many of our nodes have been running with v1.4.5 for quite a while. And for v1.4.6, it is released yesterday, we have tried on a few nodes and will update more in the future.

**Comment by andreclaro** [comment]
the [release notes for 1.4.5](https://github.com/bnb-chain/bsc/releases/tag/v1.4.5) is confusing:
`It is mainly for Testnet, if you wanna upgrade your node for mainnet Feynman hard fork, you'd better try [v1.3.13](https://github.com/bnb-chain/bsc/releases/tag/v1.3.13).`

**Comment by zzzckck** [comment]
> the [release notes for 1.4.5](https://github.com/bnb-chain/bsc/releases/tag/v1.4.5) is confusing: `It is mainly for Testnet, if you wanna upgrade your node for mainnet Feynman hard fork, you'd better try [v1.3.13](https://github.com/bnb-chain/bsc/releases/tag/v1.3.13).`

yes, that's because Feynman HF is quite important, most of the previous HF tests are based on v1.3.x, so we have more confidence for users to try v1.3.13 for the Hardfork.
As v1.4.5 passed the mainnet Feynman HF successfully, I will remove this notes, as now we will mainly support v1.4.x
