### ISSUE TITLE
Sync change of behavior 

### ISSUE THREAD

**Issue by zhk101** [bnb-chain/bsc#2436]
Geth version:
Version: 1.4.6
Git Commit: https://github.com/bnb-chain/bsc/commit/43b2ffa63ba242437bcf19ee9bccf9595be0763a
Git Commit Date: 20240429
Architecture: amd64
Go Version: go1.21.6
Operating System: linux

cmd
```
geth --history.transactions=0 --syncmode=full --tries-verify-mode=none --db.engine=pebble --metrics --metrics.addr "0.0.0.0" --http --graphql --cache=16384 --config conf.toml
```
conf.toml
```
[Eth]
NetworkId = 56
SyncMode = "full"
DiffBlock = 5000
TransactionHistory = 0
LightPeers = 100
TrieTimeout = 150000000000
TriesVerifyMode = "none"

[Eth.Miner]
GasCeil = 140000000
GasPrice = 1000000000
Recommit = 10000000000

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 200
GlobalSlots = 8000
AccountQueue = 200
GlobalQueue = 4000

[Eth.GPO]
Blocks = 20
Percentile = 60
MaxHeaderHistory = 5
MaxBlockHistory = 5
OracleThreshold = 1000

[Node]
DataDir = "geth.fast"
IPCPath = "geth.ipc"
InsecureUnlockAllowed = false
DBEngine = "pebble"


[Node.P2P]
MaxPeers = 512
MaxPeersPerIP = 512
NoDiscovery = false
StaticNodes = []
EnableMsgEvents = false
```

Starting node from BNB48 snapshot:
[38198925](https://bscscan.com/block/38198925) (Apr-26-2024 01:38:27 PM +UTC)
https://snapshots.48.club/geth.fast.38198925.tar.zst

This is relates to #2394 
Looks like the `sync` subscription now returns sync=false only when `prog.CurrentBlock >= prog.HighestBlock` and  `txIndexRemainingBlocks == 0`.

Using `eth.syncing` in geth console, `txIndexRemainingBlocks` never seem to change on my node, even when it reached a state of `prog.CurrentBlock >= prog.HighestBlock` resulting in the sync subscription still returning syncing=true.
Is this something that will always happen on a fast-node (using the fast-node BNB48 snapshot). Will this value eventually go down?

Previous to 1.4.X, this never seem to be an issue, and the node managed to sync correctly

**Comment by zhk101** [comment]
Actually, when reading the state a mentioned above, and trying to submit a transaction, my node fails with the following:

```
lvl=warn msg="Served eth_getTransactionReceipt" reqid=115094 duration=50.845µs err="transaction indexing is in progress" errdata="transaction indexing is in progress"
```

And looking at `eth.syncing` in the console, I still get the same unchanged `txIndexRemainingBlocks: 33602365`
Is this a behavior that started since `1.4.5`?

**Comment by zhk101** [comment]
Wondering if this is not an issue with the BNB snapshot.
Could not compare the directory tree with the previous one (as in, pre-1.4.X) as I deleted it.
The latest one currently available for 1.4.5 has its tree as follow

```
geth.fast
└── geth
    └── chaindata
        ├── 1310998.sst
        ├── 2805807.sst
        ├── 2805981.sst
		├── .... lots of SST files
        ├── 3627842.sst
        ├── 3627843.sst
        ├── 768406.sst
        ├── 861467.sst
        ├── 861670.sst
        ├── ancien
        │   └── chain
        │       ├── bodies.0000.cdat
        │       ├── bodies.cidx
        │       ├── bodies.meta
        │       ├── diffs.0000.rdat
        │       ├── diffs.meta
        │       ├── diffs.ridx
        │       ├── FLOCK
        │       ├── hashes.0000.rdat
        │       ├── hashes.meta
        │       ├── hashes.ridx
        │       ├── headers.0000.cdat
        │       ├── headers.cidx
        │       ├── headers.meta
        │       ├── receipts.0000.cdat
        │       ├── receipts.cidx
        │       └── receipts.meta
        ├── ancient
        │   └── chain
        │       ├── bodies.0000.cdat
        │       ├── bodies.cidx
        │       ├── bodies.meta
        │       ├── diffs.0000.rdat
        │       ├── diffs.meta
        │       ├── diffs.ridx
        │       ├── FLOCK
        │       ├── hashes.0000.rdat
        │       ├── hashes.meta
        │       ├── hashes.ridx
        │       ├── headers.0000.cdat
        │       ├── headers.cidx
        │       ├── headers.meta
        │       ├── PRUNEFLOCKBACK
        │       ├── receipts.0000.cdat
        │       ├── receipts.cidx
        │       └── receipts.meta
        ├── bodies.0000.cdat
        ├── bodies.cidx
        ├── bodies.meta
        ├── CURRENT
        ├── datadir.ancient
        │   └── chain
        │       ├── bodies.0000.cdat
        │       ├── bodies.cidx
        │       ├── bodies.meta
        │       ├── diffs.0000.rdat
        │       ├── diffs.meta
        │       ├── diffs.ridx
        │       ├── FLOCK
        │       ├── hashes.0000.rdat
        │       ├── hashes.meta
        │       ├── hashes.ridx
        │       ├── headers.0000.cdat
        │       ├── headers.cidx
        │       ├── headers.meta
        │       ├── receipts.0000.cdat
        │       ├── receipts.cidx
        │       └── receipts.meta
        ├── diffs.0000.rdat
        ├── diffs.meta
        ├── diffs.ridx
        ├── FLOCK
        ├── hashes.0000.rdat
        ├── hashes.meta
        ├── hashes.ridx
        ├── headers.0000.cdat
        ├── headers.cidx
        ├── headers.meta
        ├── LOCK
        ├── MANIFEST-3627807
        ├── MANIFEST-3627831
        ├── OPTIONS-3627832
        ├── receipts.0000.cdat
        ├── receipts.cidx
        └── receipts.meta

9 directories, 6232 files
```

I noticed a directory called `ancien` and another one called `ancient`.  I remember having seen the `ancien` on the previous snapshot tho.
There is one called `datadir.ancient` which seem new to me.
Have little clue as to what the directory tree is supposed to look like, hope this helps.

**Comment by zzzckck** [comment]
> it has been reported as well in one of the closed issues of the bnb48 snapshot repo, here [48Club/bsc-snapshots#150 (comment)](https://github.com/48Club/bsc-snapshots/issues/150#issue-2261308800) I do see the same value `txIndexRemainingBlocks: 33602365` in my node and that value doesn't change at all. `txIndexFinishedBlocks` keeps on increasing tho.

could you try --history.transactions=90000?
the snapshot of 48Club may only contain the most recent 90K blocks, it could failed the tx index process.

**Comment by zhk101** [comment]
I did try yes but that `txIndexRemainingBlocks` doesn't budge.

I switched to using the full node (the 800gb one) with pbss (instead of hash-based) and it works fine. Also changed trie-verify-node to none instead of the default local value for that snapshot

Still feels like there is a regression here as I've been using the fast node snapshot without issues prior to 1.4.x

**Comment by codegist** [comment]
Btw, I was using the BNB48 fast snapshot that was done with `1.4.5`, on my `1.4.6` node.
Yesterday saw this https://github.com/48Club/bsc-snapshots/issues/151#issuecomment-2102135151 
And also, this might be related to https://github.com/bnb-chain/bsc/issues/2394

**Comment by zhk101** [comment]
Btw, I was using the BNB48 fast snapshot that was done with 1.4.5, on my 1.4.6 node.
Yesterday saw this https://github.com/48Club/bsc-snapshots/issues/151#issuecomment-2102135151
And also, this might be related to https://github.com/bnb-chain/bsc/issues/2394

**Comment by sysvm** [comment]
> Btw, I was using the BNB48 fast snapshot that was done with 1.4.5, on my 1.4.6 node. Yesterday saw this [48Club/bsc-snapshots#151 (comment)](https://github.com/48Club/bsc-snapshots/issues/151#issuecomment-2102135151) And also, this might be related to #2437

Do you mean it's ok in geth v1.4.5, but not work in geth v1.4.6?

**Comment by zhk101** [comment]
Just assuming here, pointing at a comment I saw from the BNB48 snapshot publisher explicitly saying the need to use 1.4.5 for the snapshot. I haven't tried tbh, thought it might give you guys some clues.

**Comment by du5** [comment]
in v1.4.6 same as pbss node, 

`geth --config config_pbss.toml  --history.transactions=[90000|0] --syncmode=full --tries-verify-mode=local --db.engine=pebble --datadir geth.pbss `

pbss prune command 

`geth snapshot prune-block --datadir PATH --datadir.ancient PATH/geth/chaindata/ancient/chain`

Same error with different history.transactions parameters

```
t=2024-05-12T05:05:39+0200 lvl=info msg="Use config state scheme" config=path
t=2024-05-12T05:05:39+0200 lvl=info msg="Set global gas cap" cap=50000000
t=2024-05-12T05:05:39+0200 lvl=info msg="Initializing the KZG library" backend=gokzg
t=2024-05-12T05:05:39+0200 lvl=info msg="Using pebble as the backing database"
t=2024-05-12T05:05:39+0200 lvl=info msg="Allocated cache and file handles" database=/opt/geth.pbss/geth/chaindata cache="1.60 GiB" handles=524288 "memory table"="409.50 MiB"
t=2024-05-12T05:05:39+0200 lvl=info msg="Opened ancient database" database=/opt/geth.pbss/geth/chaindata/ancient/chain readonly=false frozen=38646039
t=2024-05-12T05:05:39+0200 lvl=info msg="State scheme set by user" scheme=path
t=2024-05-12T05:05:39+0200 lvl=info msg="Capped dirty cache size" provided="1024.00 MiB" adjusted="256.00 MiB"
t=2024-05-12T05:05:39+0200 lvl=info msg="Clean cache size" provided="614.00 MiB"
t=2024-05-12T05:05:39+0200 lvl=info msg="Allocated trie memory caches" clean="614.00 MiB" dirty="256.00 MiB"
t=2024-05-12T05:05:39+0200 lvl=info msg=Parlia chainConfig="{ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Berlin: 31302048, YOLO v3: <nil>, CatalystBlock: <nil>, London: 31302048, ArrowGlacier: <nil>, MergeFork:<nil>, Euler: 18907621, Gibbs: 23846001, Nano: 21962149, Moran: 22107423, Planck: 27281024,Luban: 29020050, Plato: 30720096, Hertz: 31302048, Hertzfix: 34140700, ShanghaiTime: 1705996800, KeplerTime: 1705996800, FeynmanTime: 1713419340, FeynmanFixTime: 1713419340, CancunTime: <nil>, Engine: parlia}"
t=2024-05-12T05:05:39+0200 lvl=info msg="Initialising Ethereum protocol" network=56 dbversion=8
t=2024-05-12T05:05:39+0200 lvl=info msg="New journal reader" path=/opt/geth.pbss/geth/chaindata/trie.journal journalType=0
t=2024-05-12T05:05:41+0200 lvl=info msg="New async node buffer" limit="256.00 MiB" layers=348
t=2024-05-12T05:06:17+0200 lvl=info msg="Loaded layer journal" diskroot=0xe22bc392c9c238f1411e3c6d82a377f8c89a5bfbe55ac2f7a61be1b004b423ea diffhead=0x714b974d37d7823dc0a91a447f127e6b513a302f475830d8e83a738a88d273a6 elapsed=37.846s
t=2024-05-12T05:06:17+0200 lvl=info msg="Opened ancient database" database=/opt/geth.pbss/geth/chaindata/ancient/state readonly=false frozen=38645337
t=2024-05-12T05:06:17+0200 lvl=info msg="Initialised chain configuration" config="{ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Berlin: 31302048, YOLO v3: <nil>, CatalystBlock: <nil>, London: 31302048, ArrowGlacier: <nil>, MergeFork:<nil>, Euler: 18907621, Gibbs: 23846001, Nano: 21962149, Moran: 22107423, Planck: 27281024,Luban: 29020050, Plato: 30720096, Hertz: 31302048, Hertzfix: 34140700, ShanghaiTime: 1705996800, KeplerTime: 1705996800, FeynmanTime: 1713419340, FeynmanFixTime: 1713419340, CancunTime: <nil>, Engine: parlia}"
t=2024-05-12T05:06:17+0200 lvl=error msg="Unexpected error when getting snapshot" error="unknown ancestor" blockNumber=38646040 blockHash=0x5a0c042239e031aa280fb1dc95d6abf40fdc97998a4d3ffd610ce16dbb9f0ac3
t=2024-05-12T05:06:17+0200 lvl=error msg="Unexpected error when getting snapshot" error="unknown ancestor" blockNumber=38646040 blockHash=0x5a0c042239e031aa280fb1dc95d6abf40fdc97998a4d3ffd610ce16dbb9f0ac3
t=2024-05-12T05:06:17+0200 lvl=error msg="Unexpected error when getting snapshot" error="unknown ancestor" blockNumber=38646040 blockHash=0x5a0c042239e031aa280fb1dc95d6abf40fdc97998a4d3ffd610ce16dbb9f0ac3
t=2024-05-12T05:06:17+0200 lvl=error msg="Unexpected error when getting snapshot" error="unknown ancestor" blockNumber=38646040 blockHash=0x5a0c042239e031aa280fb1dc95d6abf40fdc97998a4d3ffd610ce16dbb9f0ac3
t=2024-05-12T05:06:17+0200 lvl=error msg="Unexpected error when getting snapshot" error="unknown ancestor" blockNumber=38646040 blockHash=0x5a0c042239e031aa280fb1dc95d6abf40fdc97998a4d3ffd610ce16dbb9f0ac3
t=2024-05-12T05:06:17+0200 lvl=error msg="Unexpected error when getting snapshot" error="unknown ancestor" blockNumber=38646040 blockHash=0x5a0c042239e031aa280fb1dc95d6abf40fdc97998a4d3ffd610ce16dbb9f0ac3
t=2024-05-12T05:06:17+0200 lvl=info msg="Loaded most recent local block" number=38646040 hash=0x5a0c042239e031aa280fb1dc95d6abf40fdc97998a4d3ffd610ce16dbb9f0ac3 root=0x714b974d37d7823dc0a91a447f127e6b513a302f475830d8e83a738a88d273a6 td=76779906 age=8m36s
t=2024-05-12T05:06:17+0200 lvl=error msg="Unexpected error when getting snapshot" error="unknown ancestor" blockNumber=38646040 blockHash=0x5a0c042239e031aa280fb1dc95d6abf40fdc97998a4d3ffd610ce16dbb9f0ac3
t=2024-05-12T05:06:17+0200 lvl=info msg="Loaded last snap-sync pivot marker" number=35629523
t=2024-05-12T05:06:18+0200 lvl=info msg="Snapshot loaded" diskRoot=0x3629850b3a306281a6af67088360e32e836295c92d9c697f7a247cec2ec4cc3a root=0x714b974d37d7823dc0a91a447f127e6b513a302f475830d8e83a738a88d273a6
t=2024-05-12T05:06:18+0200 lvl=info msg="Initialized transaction indexer" range="last 90000 blocks"
t=2024-05-12T05:06:18+0200 lvl=warn msg="Sanitizing invalid txpool lifetime" provided=0s updated=3h0m0s
t=2024-05-12T05:06:18+0200 lvl=warn msg="Sanitizing invalid txpool reannounce time" provided=0s updated=1m0s
t=2024-05-12T05:06:18+0200 lvl=info msg="Create votePool successfully"
t=2024-05-12T05:06:18+0200 lvl=warn msg="Sanitizing invalid gasprice oracle price cap" provided=<nil> updated=100000000000
t=2024-05-12T05:06:18+0200 lvl=warn msg="Sanitizing invalid gasprice oracle ignore price" provided=<nil> updated=4
t=2024-05-12T05:06:18+0200 lvl=warn msg="Sanitizing invalid gasprice oracle max header history" provided=0 updated=1
t=2024-05-12T05:06:18+0200 lvl=warn msg="Sanitizing invalid gasprice oracle max block history" provided=0 updated=1
t=2024-05-12T05:06:18+0200 lvl=info msg="Starting peer-to-peer node" instance=Geth/v1.4.6-43b2ffa6-20240429/linux-amd64/go1.22.2
t=2024-05-12T05:06:18+0200 lvl=info msg="New local node record" seq=1710680001985 id=54b65069de3d07bac7213c2f73d95c35ed22b2abcc6fc684d0167a35b5e9d2c9 ip=127.0.0.1 udp=30311 tcp=30311
t=2024-05-12T05:06:18+0200 lvl=info msg="IPC endpoint opened" url=/opt/geth.pbss/geth.ipc
t=2024-05-12T05:06:18+0200 lvl=info msg="HTTP server started" endpoint=127.0.0.1:8545 auth=false prefix="" cors="" vhosts=localhost
t=2024-05-12T05:06:18+0200 lvl=info msg="Started P2P networking" self=enode://2c9dfdfb60bb2e5a3c626021d2d995a88c46747baa510c626f2c928cc1e4f663872d69bffaadc34558893b4c7441a0194faba4ae100d52fdfacbb6f407116d85@127.0.0.1:30311
t=2024-05-12T05:06:19+0200 lvl=info msg="New local node record" seq=1710680001986 id=54b65069de3d07bac7213c2f73d95c35ed22b2abcc6fc684d0167a35b5e9d2c9 ip=65.108.237.216 udp=30311 tcp=30311
t=2024-05-12T05:06:26+0200 lvl=error msg="Unexpected error when getting snapshot" error="unknown ancestor" blockNumber=38646040 blockHash=0x5a0c042239e031aa280fb1dc95d6abf40fdc97998a4d3ffd610ce16dbb9f0ac3
t=2024-05-12T05:06:28+0200 lvl=info msg="Looking for peers" peercount=2 tried=241 static=0
```

**Comment by sysvm** [comment]
> same as pbss node in v1.4.6,
> 
> `geth --config config_pbss.toml --history.transactions=[90000|0] --syncmode=full --tries-verify-mode=local --db.engine=pebble --datadir geth.pbss `
> 
> pbss prune command
> 
> `geth snapshot prune-block --datadir PATH --datadir.ancient PATH/geth/chaindata/ancient/chain`
> 
> Same error with different history.transactions parameters
> 
> ```
> t=2024-05-12T05:05:39+0200 lvl=info msg="Use config state scheme" config=path
> t=2024-05-12T05:05:39+0200 lvl=info msg="Set global gas cap" cap=50000000
> t=2024-05-12T05:05:39+0200 lvl=info msg="Initializing the KZG library" backend=gokzg
> t=2024-05-12T05:05:39+0200 lvl=info msg="Using pebble as the backing database"
> t=2024-05-12T05:05:39+0200 lvl=info msg="Allocated cache and file handles" database=/opt/geth.pbss/geth/chaindata cache="1.60 GiB" handles=524288 "memory table"="409.50 MiB"
> t=2024-05-12T05:05:39+0200 lvl=info msg="Opened ancient database" database=/opt/geth.pbss/geth/chaindata/ancient/chain readonly=false frozen=38646039
> t=2024-05-12T05:05:39+0200 lvl=info msg="State scheme set by user" scheme=path
> t=2024-05-12T05:05:39+0200 lvl=info msg="Capped dirty cache size" provided="1024.00 MiB" adjusted="256.00 MiB"
> t=2024-05-12T05:05:39+0200 lvl=info msg="Clean cache size" provided="614.00 MiB"
> t=2024-05-12T05:05:39+0200 lvl=info msg="Allocated trie memory caches" clean="614.00 MiB" dirty="256.00 MiB"
> t=2024-05-12T05:05:39+0200 lvl=info msg=Parlia chainConfig="{ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Berlin: 31302048, YOLO v3: <nil>, CatalystBlock: <nil>, London: 31302048, ArrowGlacier: <nil>, MergeFork:<nil>, Euler: 18907621, Gibbs: 23846001, Nano: 21962149, Moran: 22107423, Planck: 27281024,Luban: 29020050, Plato: 30720096, Hertz: 31302048, Hertzfix: 34140700, ShanghaiTime: 1705996800, KeplerTime: 1705996800, FeynmanTime: 1713419340, FeynmanFixTime: 1713419340, CancunTime: <nil>, Engine: parlia}"
> t=2024-05-12T05:05:39+0200 lvl=info msg="Initialising Ethereum protocol" network=56 dbversion=8
> t=2024-05-12T05:05:39+0200 lvl=info msg="New journal reader" path=/opt/geth.pbss/geth/chaindata/trie.journal journalType=0
> t=2024-05-12T05:05:41+0200 lvl=info msg="New async node buffer" limit="256.00 MiB" layers=348
> t=2024-05-12T05:06:17+0200 lvl=info msg="Loaded layer journal" diskroot=0xe22bc392c9c238f1411e3c6d82a377f8c89a5bfbe55ac2f7a61be1b004b423ea diffhead=0x714b974d37d7823dc0a91a447f127e6b513a302f475830d8e83a738a88d273a6 elapsed=37.846s
> t=2024-05-12T05:06:17+0200 lvl=info msg="Opened ancient database" database=/opt/geth.pbss/geth/chaindata/ancient/state readonly=false frozen=38645337
> t=2024-05-12T05:06:17+0200 lvl=info msg="Initialised chain configuration" config="{ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Berlin: 31302048, YOLO v3: <nil>, CatalystBlock: <nil>, London: 31302048, ArrowGlacier: <nil>, MergeFork:<nil>, Euler: 18907621, Gibbs: 23846001, Nano: 21962149, Moran: 22107423, Planck: 27281024,Luban: 29020050, Plato: 30720096, Hertz: 31302048, Hertzfix: 34140700, ShanghaiTime: 1705996800, KeplerTime: 1705996800, FeynmanTime: 1713419340, FeynmanFixTime: 1713419340, CancunTime: <nil>, Engine: parlia}"
> t=2024-05-12T05:06:17+0200 lvl=error msg="Unexpected error when getting snapshot" error="unknown ancestor" blockNumber=38646040 blockHash=0x5a0c042239e031aa280fb1dc95d6abf40fdc97998a4d3ffd610ce16dbb9f0ac3
> t=2024-05-12T05:06:17+0200 lvl=error msg="Unexpected error when getting snapshot" error="unknown ancestor" blockNumber=38646040 blockHash=0x5a0c042239e031aa280fb1dc95d6abf40fdc97998a4d3ffd610ce16dbb9f0ac3
> t=2024-05-12T05:06:17+0200 lvl=error msg="Unexpected error when getting snapshot" error="unknown ancestor" blockNumber=38646040 blockHash=0x5a0c042239e031aa280fb1dc95d6abf40fdc97998a4d3ffd610ce16dbb9f0ac3
> t=2024-05-12T05:06:17+0200 lvl=error msg="Unexpected error when getting snapshot" error="unknown ancestor" blockNumber=38646040 blockHash=0x5a0c042239e031aa280fb1dc95d6abf40fdc97998a4d3ffd610ce16dbb9f0ac3
> t=2024-05-12T05:06:17+0200 lvl=error msg="Unexpected error when getting snapshot" error="unknown ancestor" blockNumber=38646040 blockHash=0x5a0c042239e031aa280fb1dc95d6abf40fdc97998a4d3ffd610ce16dbb9f0ac3
> t=2024-05-12T05:06:17+0200 lvl=error msg="Unexpected error when getting snapshot" error="unknown ancestor" blockNumber=38646040 blockHash=0x5a0c042239e031aa280fb1dc95d6abf40fdc97998a4d3ffd610ce16dbb9f0ac3
> t=2024-05-12T05:06:17+0200 lvl=info msg="Loaded most recent local block" number=38646040 hash=0x5a0c042239e031aa280fb1dc95d6abf40fdc97998a4d3ffd610ce16dbb9f0ac3 root=0x714b974d37d7823dc0a91a447f127e6b513a302f475830d8e83a738a88d273a6 td=76779906 age=8m36s
> t=2024-05-12T05:06:17+0200 lvl=error msg="Unexpected error when getting snapshot" error="unknown ancestor" blockNumber=38646040 blockHash=0x5a0c042239e031aa280fb1dc95d6abf40fdc97998a4d3ffd610ce16dbb9f0ac3
> t=2024-05-12T05:06:17+0200 lvl=info msg="Loaded last snap-sync pivot marker" number=35629523
> t=2024-05-12T05:06:18+0200 lvl=info msg="Snapshot loaded" diskRoot=0x3629850b3a306281a6af67088360e32e836295c92d9c697f7a247cec2ec4cc3a root=0x714b974d37d7823dc0a91a447f127e6b513a302f475830d8e83a738a88d273a6
> t=2024-05-12T05:06:18+0200 lvl=info msg="Initialized transaction indexer" range="last 90000 blocks"
> t=2024-05-12T05:06:18+0200 lvl=warn msg="Sanitizing invalid txpool lifetime" provided=0s updated=3h0m0s
> t=2024-05-12T05:06:18+0200 lvl=warn msg="Sanitizing invalid txpool reannounce time" provided=0s updated=1m0s
> t=2024-05-12T05:06:18+0200 lvl=info msg="Create votePool successfully"
> t=2024-05-12T05:06:18+0200 lvl=warn msg="Sanitizing invalid gasprice oracle price cap" provided=<nil> updated=100000000000
> t=2024-05-12T05:06:18+0200 lvl=warn msg="Sanitizing invalid gasprice oracle ignore price" provided=<nil> updated=4
> t=2024-05-12T05:06:18+0200 lvl=warn msg="Sanitizing invalid gasprice oracle max header history" provided=0 updated=1
> t=2024-05-12T05:06:18+0200 lvl=warn msg="Sanitizing invalid gasprice oracle max block history" provided=0 updated=1
> t=2024-05-12T05:06:18+0200 lvl=info msg="Starting peer-to-peer node" instance=Geth/v1.4.6-43b2ffa6-20240429/linux-amd64/go1.22.2
> t=2024-05-12T05:06:18+0200 lvl=info msg="New local node record" seq=1710680001985 id=54b65069de3d07bac7213c2f73d95c35ed22b2abcc6fc684d0167a35b5e9d2c9 ip=127.0.0.1 udp=30311 tcp=30311
> t=2024-05-12T05:06:18+0200 lvl=info msg="IPC endpoint opened" url=/opt/geth.pbss/geth.ipc
> t=2024-05-12T05:06:18+0200 lvl=info msg="HTTP server started" endpoint=127.0.0.1:8545 auth=false prefix="" cors="" vhosts=localhost
> t=2024-05-12T05:06:18+0200 lvl=info msg="Started P2P networking" self=enode://2c9dfdfb60bb2e5a3c626021d2d995a88c46747baa510c626f2c928cc1e4f663872d69bffaadc34558893b4c7441a0194faba4ae100d52fdfacbb6f407116d85@127.0.0.1:30311
> t=2024-05-12T05:06:19+0200 lvl=info msg="New local node record" seq=1710680001986 id=54b65069de3d07bac7213c2f73d95c35ed22b2abcc6fc684d0167a35b5e9d2c9 ip=65.108.237.216 udp=30311 tcp=30311
> t=2024-05-12T05:06:26+0200 lvl=error msg="Unexpected error when getting snapshot" error="unknown ancestor" blockNumber=38646040 blockHash=0x5a0c042239e031aa280fb1dc95d6abf40fdc97998a4d3ffd610ce16dbb9f0ac3
> t=2024-05-12T05:06:28+0200 lvl=info msg="Looking for peers" peercount=2 tried=241 static=0
> ```

@du5 Can you give me the detailed info about the snapshot version that you are using?

**Comment by du5** [comment]
> Hi @du5 , Could you answer the following questions to help us locate the issue:
> 
> * Can you provide the specific config.yaml & run cmd to reproduce issue [[BUG] Unexpected error when getting snapshot after prune #2437](https://github.com/bnb-chain/bsc/issues/2437) , such as which snapshot was used, what commands were executed specifically, and what the exact run instructions were?
> * Do both hash and pbss have the same issue after snapshot prune-block?
> * Why close [[BUG] Unexpected error when getting snapshot after prune #2437](https://github.com/bnb-chain/bsc/issues/2437) and move the replies here?

After testing, I reproduced the problem, it's not related to #2437. At first I thought it was prune that caused the failure to synchronize. #2437 is solved now

**Comment by zhk101** [comment]
Ok so tried again with the latest fast node snapshot @du5 just released yersterday, on the same configuration mentioned above and the node is still synching for-ever because of `txIndexRemainingBlocks: 33602365`
`
> eth.syncing
{
  currentBlock: 38769531,
  healedBytecodeBytes: 0,
  healedBytecodes: 0,
  healedTrienodeBytes: 0,
  healedTrienodes: 0,
  healingBytecode: 0,
  healingTrienodes: 0,
  highestBlock: 38769471,
  startingBlock: 38769467,
  syncedAccountBytes: 0,
  syncedAccounts: 0,
  syncedBytecodeBytes: 0,
  syncedBytecodes: 0,
  syncedStorage: 0,
  syncedStorageBytes: 0,
  txIndexFinishedBlocks: 5167167,
  txIndexRemainingBlocks: 33602365
}
`

**Comment by zhk101** [comment]
Ok so for the sake of it I tried again what @zzzckck mentioned about specifying `--history.transactions=90000`. I could swear I tried at the time without success.
Anyway, restart the node changing `--history.transactions=0` with `--history.transactions=90000` and then I could see a log saying `Unindexing transactions`. Once it picked up again the few last blocks, the node finally managed to sync up correctly! 🙌
@du5 maybe this is something you should now change in the node params for the fast node in the BNB48 README?
