### ISSUE TITLE
Infinite loading on bsc testnet faucet

### ISSUE THREAD

**Issue by locki13freja** [bnb-chain/bsc#2444]
Steps to reproduce:
1)Go to https://www.bnbchain.org/en/testnet-faucet
2)Select 0.3 BNB
3)Enter wallet address
5)Click on button with text "Send 0.3 BNB"
4)Complete the captcha
5)Get infinite loading

**Comment by zzzckck** [comment]
thx, the device was down, it is recovered now.

**Comment by tuan-jason** [comment]
@zzzckck It's down again. 
Could you please help check?

Thanks.

**Comment by zzzckck** [comment]
> u please help che

yea, restart the node just recovered. 
Seems not quite stable, we will do some investigation.
