### ISSUE TITLE
Custom prefix for env vars

### ISSUE THREAD

**Issue by exodus-justinz** [bnb-chain/bsc#2456]
# Rationale

Currently, we have `GETH_` prefix for all env vars. It may cause some conflicts with [k8s service env vars](https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables) if there's a `geth` service on the same namespace. 

An example would be
```
GETH_PORT=tcp:<IP>:<PORT>
```

# Implementation

On [./cmd/geth/main.go](https://github.com/bnb-chain/bsc/blob/master/cmd/geth/main.go#L288), we have the following 
```
flags.AutoEnvVars(app.Flags, "GETH")
```

Maybe we can get the prefix from an environment variable with `GETH` as default?

**Comment by zzzckck** [comment]
Ethereum should have same issue, right, is there any feedback from their side?

**Comment by zzzckck** [comment]
In which case would the env vars conflict? could you provide more detail?
And is it possible to avoid the conflict from k8s side? Like, not use the `GETH` prefix?

**Comment by exodus-justinz** [comment]
>In which case would the env vars conflict? could you provide more detail?

Sure thing. This happens when we have a service name called `geth` on k8s. It will automatically inject environment variables on all pods in the same namespace, and one of these env var is `GETH_PORT`.

>And is it possible to avoid the conflict from k8s side? Like, not use the GETH prefix?

It is possible, we do have some options to do this:
- Rename the service and update all references to it.
- Disable the env var injection by setting `enableServiceLinks: false`. 

But we're looking if it's possible to do this on `geth` side

**Comment by zzzckck** [comment]
> > In which case would the env vars conflict? could you provide more detail?
> 
> Sure thing. This happens when we have a service name called `geth` on k8s. It will automatically inject environment variables on all pods in the same namespace, and one of these env var is `GETH_PORT`.
> 
> > And is it possible to avoid the conflict from k8s side? Like, not use the GETH prefix?
> 
> It is possible, we do have some options to do this:
> 
> * Rename the service and update all references to it.
> * Disable the env var injection by setting `enableServiceLinks: false`.
> 
> But we're looking if it's possible to do this on `geth` side

noted, we can discuss with Geth team in your issue to reach an agreement first.
