### ISSUE TITLE
encountering an OOM problem

### ISSUE THREAD

**Issue by sn00wman** [bnb-chain/bsc#2464]
#### System information

Geth version:  geth v1.4.6 
OS & Version: AWS Amazon Linux x86, with 32GB of memory

Our machine running the BSC full node gets its BSC process killed after running for several days. Checking the system message logs shows an OOM error. Below is the memory profile graph we observed using pprof.

<img width="640" alt="image" src="https://github.com/bnb-chain/bsc/assets/4339529/dc37f77c-402e-443d-8c33-5be1060b8248">

<img width="1919" alt="image" src="https://github.com/bnb-chain/bsc/assets/4339529/b7160686-d6d0-4019-a492-6bf56c051c8c">

The memory was still increasing when using pprof. Could you please let me know the typical maximum memory usage of a BSC full node? Is it possible that the machine does not have enough memory?

**Comment by OmarMBNB** [comment]
Try not specify the body cache and batch size: --bodies.cache=214748364800 --batchSize=4096M.
These 2 flags will bring heavy to RAM caches. Similar issue: https://github.com/node-real/bsc-erigon/issues/39

**Comment by zzzckck** [comment]
> #### System information
> Geth version: geth v1.4.6 OS & Version: AWS Amazon Linux x86, with 32GB of memory
> 
> Our machine running the BSC full node gets its BSC process killed after running for several days. Checking the system message logs shows an OOM error. Below is the memory profile graph we observed using pprof.
> 
> <img alt="image" width="640" src="https://private-user-images.githubusercontent.com/4339529/330784849-dc37f77c-402e-443d-8c33-5be1060b8248.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjUzNjYsIm5iZiI6MTcxNTgyNTA2NiwicGF0aCI6Ii80MzM5NTI5LzMzMDc4NDg0OS1kYzM3Zjc3Yy00MDJlLTQ0M2QtOGMzMy01YmUxMDYwYjgyNDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTZUMDIwNDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTk5Mzk4NmI0M2IzMTA1ZDljODRlMmMzN2YyY2NlYjA3NDI4NzI3MjE5Mzc0MjlkMTE1NTU1ODI0YzUwMzYzZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mBN_eozo5H6sAbMk_vKOmCOuTyrArJSdqm5krmzF-18"> <img alt="image" width="1919" src="https://private-user-images.githubusercontent.com/4339529/330785363-b7160686-d6d0-4019-a492-6bf56c051c8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjUzNjYsIm5iZiI6MTcxNTgyNTA2NiwicGF0aCI6Ii80MzM5NTI5LzMzMDc4NTM2My1iNzE2MDY4Ni1kNmQwLTQwMTktYTQ5Mi02YmY1NmMwNTFjOGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTZUMDIwNDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWNhMjhkZDIxZDc4MDQyNjM0ZTBlYWNmOGQxODlhYmU2YjRmZDUwNDcxN2YzMDRhOGY4NDZmMjgxMWI4YWFhZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ue1cFKQBUXHZK5A8BicHEOFuMPeQgFkcmFkHaNdbDY8">
> The memory was still increasing when using pprof. Could you please let me know the typical maximum memory usage of a BSC full node? Is it possible that the machine does not have enough memory?

I think BSC full node will generally take ~20GB. Could u provide your config.toml and cmd line? We can check if there is any unexpected memory usage.

**Comment by zzzckck** [comment]
based the your pprof file, seems like the `knownTxs.Add()` occupies lots of memory, was your node connected to lots of peers with large pending transaction needs to be broadcasted.
But the pprof is quite low level, while Golang would have GC to release the temporary memory of `knownTxs.Add()`, so this pprof may not that accurate.

**Comment by sn00wman** [comment]
thank you , i find the config.yaml 
<img width="103" alt="image" src="https://github.com/bnb-chain/bsc/assets/4339529/b603e928-648c-451b-8cad-5008fb733929">
the max peer maybe too large 5000
amd our geth connect too many peer 
<img width="512" alt="image" src="https://github.com/bnb-chain/bsc/assets/4339529/d1360847-5f53-47c9-b2c0-50bcfe87000f">

i will try change MaxPeers less than 100
