### ISSUE TITLE
Faucet infinite loop ( don't send tbnb) 

### ISSUE THREAD

**Issue by sealflysaladpeanuts** [bnb-chain/bsc#2465]
-> Reproduction
- go on https://www.bnbchain.org/en/testnet-faucet
- enter metamask wallet 
- select 0.3 BNB
- click on ' send 0.3 BNB'
and get an infinite loop on the button

**Comment by zzzckck** [comment]
it is recovered now, faucet is unstable recently, we will check.

**Comment by emailtovamos** [comment]
It seems to be currently happening due to DOS attack from certain particular ips. 
There's no obvious mechanism in place right now to stop it in the short term but we will add some in the future.
