### ISSUE TITLE
bsc tx revert, error the invalid opcode mcopy

### ISSUE THREAD

**Issue by alexanderhawl** [bnb-chain/bsc#2471]
#### System information
bsc mainet
solidity version 0.8.25

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
tx will execute successfully

#### Actual behaviour
revert, the error says invalid opcode

#### Steps to reproduce the behaviour
find the smart contract 0xf57651F64505D544ac50E1a28c5034db2A00FCa9 in bsc mainet 
callthe Claim function

#### Backtrace
![Uploading Screenshot_20240517_002639.png…]()

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by alexanderhawl** [comment]
Error Message: invalid opcode: MCOPY
(bool success, bytes memory res) = token.call{value: 0}(abi.encodeWithSignature("balanceOf(address)", address(this)));
in private_swap_test

**Comment by zzzckck** [comment]
This opcode is introduced by Ethereum Cancun hard fork, BSC testnet has supported it, but mainnet is not ready, target date mid of June, you may refer: https://forum.bnbchain.org/t/bnb-chain-upgrades-mainnet/936#h-3tycho-wip-24
<img width="749" alt="image" src="https://github.com/bnb-chain/bsc/assets/152148891/e43f762e-0eb2-49a1-a796-508927b76cdc">
