### ISSUE TITLE
 Sync failed

### ISSUE THREAD

**Issue by www7805455** [bnb-chain/bsc#2474]
geth version: Geth/v1.4.7-f45305b1-20240517/linux-amd64/go1.21.10
Snapshot : Geth fast : https://snapshots.48.club/geth.fast.38778735.tar.zst
config:
[Eth]
NetworkId = 56
LightPeers = 100
TrieTimeout = 150000000000

[Eth.Miner]
GasCeil = 140000000
GasPrice = 3000000000
Recommit = 10000000000

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 3000000000
PriceBump = 10
AccountSlots = 200
GlobalSlots = 8000
AccountQueue = 200
GlobalQueue = 4000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 1000

[Node]
IPCPath = "geth.ipc"
HTTPHost = "localhost"
InsecureUnlockAllowed = false
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 200
NoDiscovery = false
StaticNodes = []
ListenAddr = ":30311"
EnableMsgEvents = false

[Node.LogConfig]
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""

ERROR:
t=2024-05-17T14:30:36+0200 lvl=error msg="Unexpected error when getting snapshot" error="unknown ancestor" blockNumber=38778735 blockHash=0x00a6c8111eff0169bcafa297b2a816b51fb3fe2d66e86d1618f84c008d2a020d
t=2024-05-17T14:30:36+0200 lvl=error msg="Unexpected error when getting snapshot" error="unknown ancestor" blockNumber=38778594 blockHash=0xdd012fe4cd2e917b79287a8dc4cfdd782fa87803ffa9d0d21f121fdf74d54857
t=2024-05-17T14:30:36+0200 lvl=error msg="Unexpected error when getting snapshot" error="unknown ancestor" blockNumber=38778594 blockHash=0xdd012fe4cd2e917b79287a8dc4cfdd782fa87803ffa9d0d21f121fdf74d54857
t=2024-05-17T14:30:36+0200 lvl=error msg="Unexpected error when getting snapshot" error="unknown ancestor" blockNumber=38778735 blockHash=0x00a6c8111eff0169bcafa297b2a816b51fb3fe2d66e86d1618f84c008d2a020d
t=2024-05-17T14:30:36+0200 lvl=error msg="Unexpected error when getting snapshot" error="unknown ancestor" blockNumber=38778735 blockHash=0x00a6c8111eff0169bcafa297b2a816b51fb3fe2d66e86d1618f84c008d2a020d
t=2024-05-17T14:30:36+0200 lvl=error msg="Canonical hash missing, can't freeze" number=38688727
t=2024-05-17T14:30:36+0200 lvl=error msg="Canonical hash missing, can't freeze" number=38688728
t=2024-05-17T14:30:36+0200 lvl=error msg="Canonical hash missing, can't freeze" number=38688729
t=2024-05-17T14:30:36+0200 lvl=error msg="Canonical hash missing, can't freeze" number=38688730
t=2024-05-17T14:30:36+0200 lvl=error msg="Canonical hash missing, can't freeze" number=38688731
t=2024-05-17T14:30:36+0200 lvl=error msg="Canonical hash missing, can't freeze" number=38688732
t=2024-05-17T14:30:36+0200 lvl=error msg="Canonical hash missing, can't freeze" number=38688733
t=2024-05-17T14:30:36+0200 lvl=error msg="Canonical hash missing, can't freeze" number=38688734
t=2024-05-17T14:30:36+0200 lvl=error msg="Canonical hash missing, can't freeze" number=38688735

It has been running for several hours without syncing.

**Comment by du5** [comment]
#2437

**Comment by www7805455** [comment]
geth-1-4-8 --config ./config.toml --datadir ./geth1/  --history.transactions=90000 --block-amount-reserved=90000  --syncmode=full  --tries-verify-mode=none --pruneancient --db.engine=pebble

**Comment by du5** [comment]
It is concluded from the log that your db is broken and it is recommended that you download it again.

**Comment by www7805455** [comment]
> It is concluded from the log that your db is broken and it is recommended that you download it again.
I just downloaded the latest one

**Comment by www7805455** [comment]
> I just downloaded the latest one

So I don't think the data is corrupted

**Comment by tuleibing** [comment]
> Unexpected error when getting snapshot
I also downloaded this Snapshot and encountered the same problem.

**Comment by tuleibing** [comment]
> It is concluded from the log that your db is broken and it is recommended that you download it again.

Is there any problem with Snapshot about fast node?

**Comment by zhk101** [comment]
You could try removing `--pruneancient`

**Comment by www7805455** [comment]
I tried using other snapshots and the problem was solved. I didn't check the specific reasons in detail.
