### ISSUE TITLE
Request a BUG refund

### ISSUE THREAD

**Issue by greyireland** [bnb-chain/bsc#2493]
Yesterday, due to my personal reasons, my robot had a serious bug, causing multiple bundles to use the gas_price that reached the limit of my wallet, resulting in a large loss of BNB. These BNBs have entered the validator's wallet. I wonder if it is possible to return these BNBs. Although this money is not much for you, it is my savings for many years. I hope to retrieve these BNBs!!!

BNB48(https://www.48.club/)

验证者：0xb218C5D6aF1F979aC42BC68d98A5A0D796C6aB01（Validator: Alan Turing）（9.9BNB）
https://bscscan.com/tx/0x837500f15a385e7a33a6804ccb768dbca9c206a37fd2528f6e9f751f3d8b486b
https://bscscan.com/tx/0x22cc2140ee7e613324b8a6d0f72dbf4ae65c590122a2524a19d97516d8e0ac63

验证者：0x9bb56C2B4DBE5a06d79911C9899B6f817696ACFc（9.9BNB）
https://bscscan.com/tx/0xf91548ea7e255fe3fc3c5240ac6f7219a2fc3fc69ecb0b50dc666fff20a9f54d
https://bscscan.com/tx/0x71e31890bab47cc1be08b2c4cc610043de5ff0685d52c844bff944da5d719860

验证者：0x38944092685a336CB6B9ea58836436709a2adC89（4.9BNB）
https://bscscan.com/tx/0xaba0d2854634d3347378ee39bc9a16de45a2175fdb2b43099ddd84a1f07a8e9a

验证者：0xCcB42A9b8d6C46468900527Bc741938E78AB4577（7.9BNB）
https://bscscan.com/tx/0xae070895cc7018ca969f7ad7b566de4c9996a10ca0bd51a32c849c8ecd1b18f0
https://bscscan.com/tx/0x59dc434c708d936e1ce845d37f732ba6aa3e2fdd6209c30a7124f03ee92d39b8

Blocksmith(https://blocksmith.org/)

验证者：0x58567F7A51a58708C8B40ec592A38bA64C0697De（9.9BNB）
https://bscscan.com/tx/0x4e5d30531d03ad1a40abcd75c1424a50278267d7419a70bb73d26553a1464448
https://bscscan.com/tx/0x80c9fded72cb0ec36b65181a96f28d5cc4cf6a2c0bd7c3779459a8d275d54145
https://bscscan.com/tx/0x201f9028e52612d86985026992506632f83b392b6c095a54b2487df3bdc24fea
https://bscscan.com/tx/0x000f1e7c68f7dfd504d9c4ec1ca852a66fd690a3249af418de0e179fd4bc5bd9

验证者：0xCa503a7eD99eca485da2E875aedf7758472c378C（4.9BNB）
https://bscscan.com/tx/0x8f69ff5f156d377f8bb56c7c971173a632e84c0510e157073c7831783ac4a8a4
https://bscscan.com/tx/0xe1f20c6776bb5994ab8dbe1493247b6efde4a83a487b1a9a1bc50c6285bb0c09

验证者：0x1cFDBd2dFf70C6e2e30df5012726F87731F38164（4.9BNB）
https://bscscan.com/tx/0x7c5c9da4a25aac2e34d182d1a2e9ac3549a60bff4a3b0fe363856edb540c7591
https://bscscan.com/tx/0x1483c2411f284d6b689fcceaacfb83bedbac3306239a9de95666bf55199cd40a

**Comment by greyireland** [comment]
If it is possible to refund, I hope it can be returned to the original wallet (0x97dA894370C249623d3c643F75620578801F7a9b).

**Comment by iGio90** [comment]
:people_hugging:

**Comment by STdevK** [comment]
BNB Chain is a decentralised network, it is difficult to coordinate with so many anonymous delegators

**Comment by greyireland** [comment]
Due to the mechanism of BSC, most of the gas is distributed to the pledgers, and the validators can only get a small share. With the help of 48club's lan, I got a partial refund. I am very grateful for the help of 48Club, and special thanks to @48ClubIan.You are my hero~
