### ISSUE TITLE
trnascation not complete

### ISSUE THREAD

**Issue by ashu1211** [bnb-chain/bsc#2504]
geth version is 1.4.8
transcation not complete..giving following log
info msg="Submitted transaction" hash=0xe3ebb3e0fbade64b83d869bc423aeb191521ac646b57b764633eb583a3c5feef from=0xe1B16df896c83997fdbD48852Efae7Ff3Be14FA7 nonce=22 recipient=0x523BCc3b3f26c803Eb04902EfD90895e1992932B value=10000000000000 x-forward-ip=<nil>
![Screenshot from 2024-05-31 16-22-03](https://github.com/bnb-chain/bsc/assets/48590507/a9e0544e-b07f-4ee4-87f4-9e0bbf6413de)

**Comment by galaio** [comment]
It seems a tx on testnet, and pls make sure your tx has been broadcast to other p2p peers, and with a suggested gas price too.

I also cannot find your tx in bscscan, https://testnet.bscscan.com/tx/0xe3ebb3e0fbade64b83d869bc423aeb191521ac646b57b764633eb583a3c5feef.

**Comment by ashu1211** [comment]
yes i have send again with 3X gas price... why i need to send 3X gas price

**Comment by ashu1211** [comment]
this is

**Comment by zzzckck** [comment]
> d 3X gas price

Maybe your transaction get lost or dangled due to some unknown reason. It is abnormal, but could happen in some corner case. In such case, change to a new RPC node or re-send your TX with gasPrice pump 10% may work.
