### ISSUE TITLE
How do I determine which validator the next block is?

### ISSUE THREAD

**Issue by keenlysoft** [bnb-chain/bsc#2506]
How do I determine which validator the next block is?
https://github.com/bnb-chain/bsc/issues/1123
I've seen it stated here that it is, polling by blocks of 200, who the next verifier will be. But when I open the block of 400, when I look at 401, it's not Validator 1 to pack, why is this what?
<img width="1190" alt="image" src="https://github.com/bnb-chain/bsc/assets/38453834/dac836f4-f400-4760-81fd-6b3fc56cf858">

<img width="1630" alt="image" src="https://github.com/bnb-chain/bsc/assets/38453834/150eb518-8d30-47ee-9bd2-5e23ac666e5a">

**Comment by galaio** [comment]
Hi, the `ValidatorSet` will be selected in the epoch block, but it will delay the effect after `len(lastEpochValidators)/2` blocks.
ref: https://github.com/bnb-chain/bsc/blob/f5ba30ed4782c23f8e895f15f24d6e495d74bcff/consensus/parlia/snapshot.go#L271

So the 401 block also use the last epoch `ValidatorSet`.

**Comment by Jayanring** [comment]
The `lastEpochValidators` should be 21, right? Then the expected delay is 10 blocks, but I found that the actual delay is 45 blocks. The `ValidatorSet` selected at height `46901000` starts to take effect from `46901045`.
