### ISSUE TITLE
UX: remove flag --chapel

### ISSUE THREAD

**Issue by zzzckck** [bnb-chain/bsc#2521]
# Rationale
network can be read from the config.toml file, seems no need to add this extra flag.

# Implementation
NA

**Comment by buddh0** [comment]
> # Rationale
> network can be read from the config.toml file, seems no need to add this extra flag.
> 
> # Implementation
> NA

some commands not support using config.toml
such as `importHistory`

other few scenarios,  some actions happened before reading config.toml
such as `func prepare(ctx *cli.Context)`

and in addition, '--chapel' is totally following the geth
```
	NetworkIdFlag = &cli.Uint64Flag{
		Name:     "networkid",
		Usage:    "Explicitly set network id (integer)(For testnets: use --goerli, --sepolia, --holesky instead)",
		Value:    ethconfig.Defaults.NetworkId,
		Category: flags.EthCategory,
	}
```

I think we can support removing '--chapel' and read the networkId from config.toml when we do a sync, 
but not removing `--chapel` totally.
