### ISSUE TITLE
The "BAD BLOCK" log is output every few minutes.

### ISSUE THREAD

**Issue by fatminer** [bnb-chain/bsc#2522]
#### System information

Geth version: `geth version`

Geth
Version: 1.4.8
Git Commit: f5ba30ed4782c23f8e895f15f24d6e495d74bcff
Architecture: amd64
Go Version: go1.21.9
Operating System: linux
GOPATH=
GOROOT=/usr/local/go

OS & Version: Windows/Linux/OSX

Linux 5.15.0-1036-aws #40~20.04.1-Ubuntu SMP Mon Apr 24 00:21:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

#### Expected behaviour

Do not output logs indicating bad blocks if the blocks are valid.

#### Actual behaviour

The "BAD BLOCK" log is output every few minutes.
However, when I make a "getBlockByNumber" request for the corresponding block, the response comes back without any problems.

For example, the bad blocks in the following log can be seen in Explorer.
I'm confused because they are bad block but also valid block.

t=2024-06-20T08:13:45+0000 lvl=error msg="\n########## BAD BLOCK #########\nBlock: 39772307 (0x24f665aefa6a7266438a4a51a2ef56c95b0801a20931572e47f66a55ba70fae5)\nMiner: 0x75B851a27D7101438F45fce31816501193239A83\nError: missing withdrawals in block body\nPlatform: geth (devel) go1.21.9 amd64 linux\nVCS: f5ba30ed-\nChain config: &params.ChainConfig{ChainID:56, HomesteadBlock:0, DAOForkBlock:<nil>, DAOForkSupport:false, EIP150Block:0, EIP155Block:0, EIP158Block:0, ByzantiumBlock:0, ConstantinopleBlock:0, PetersburgBlock:0, IstanbulBlock:0, MuirGlacierBlock:0, BerlinBlock:31302048, YoloV3Block:<nil>, CatalystBlock:<nil>, LondonBlock:31302048, ArrowGlacierBlock:<nil>, GrayGlacierBlock:<nil>, MergeNetsplitBlock:<nil>, ShanghaiTime:(*uint64)(0xc000131f28), KeplerTime:(*uint64)(0xc000131f30), FeynmanTime:(*uint64)(0xc000131f38), FeynmanFixTime:(*uint64)(0xc000131f40), CancunTime:(*uint64)(0xc000131f48), HaberTime:(*uint64)(0xc000131f50), PragueTime:(*uint64)(nil), VerkleTime:(*uint64)(nil), TerminalTotalDifficulty:<nil>, TerminalTotalDifficultyPassed:false, RamanujanBlock:0, NielsBlock:0, MirrorSyncBlock:5184000, BrunoBlock:13082000, EulerBlock:18907621, GibbsBlock:23846001, NanoBlock:21962149, MoranBlock:22107423, PlanckBlock:27281024, LubanBlock:29020050, PlatoBlock:30720096, HertzBlock:31302048, HertzfixBlock:34140700, Ethash:(*params.EthashConfig)(nil), Clique:(*params.CliqueConfig)(nil), Parlia:(*params.ParliaConfig)(0x46fbd30)}\nReceipts: \n##############################\n"

This seems to happen every time this validator generates a block.
0x75B851a27D7101438F45fce31816501193239A83 

#### Steps to reproduce the behaviour
Occurs if it is running

**Comment by madhan5447** [comment]
Hi Team,
Am also facing same issue am using same version, i have checked,1.4.7,1.4.8 and 1.4.9  all the version same issue occur
Kindly share the solution for this issue

**Comment by AlexKNM** [comment]
t=2024-06-20T12:39:42+0000 lvl=warn msg="Inserted known block" number=39777496 hash=0x90ddb49a6c82cc2cdac268b1753fd3dac692ac19cd4379c1fd5f4646abb0eb3d uncles=0 txs=18
4 gas=25521021 root=0x9d18da8c9c84ca5b3903e80f75226ea264e906de98d7248d24e4abf41c4f2e00
t=2024-06-20T12:39:42+0000 lvl=error msg="Please file an issue, skip known block execution without receipt" hash=0x90ddb49a6c82cc2cdac268b1753fd3dac692ac19cd4379c1fd5
f4646abb0eb3d number=39777496

**Comment by fatminer** [comment]
For example, this BAD BLOCK has the same block hash as the block information on BSCScan.

> ########## BAD BLOCK #########
> Block: 39772307 (0x24f665aefa6a7266438a4a51a2ef56c95b0801a20931572e47f66a55ba70fae5)

https://bscscan.com/block/39772307

Does this mean that BSCScan is correct in BAD BLOCK?
or maybe Erigon clients are transferring the correct block as BAD BLOCK?

**Comment by ngotchac** [comment]
> It is caused by bad Erigon clients

Why is the block with a given hash considered bad, but successfully imported right after?

**Comment by zzzckck** [comment]
> For example, this BAD BLOCK has the same block hash as the block information on BSCScan.
> 
> > ########## BAD BLOCK #########
> > Block: 39772307 (0x24f665aefa6a7266438a4a51a2ef56c95b0801a20931572e47f66a55ba70fae5)
> 
> https://bscscan.com/block/39772307
> 
> Does this mean that BSCScan is correct in BAD BLOCK? or maybe Erigon clients are transferring the correct block as BAD BLOCK?

@fatminer yea, the block hash is ok, but the block body has been polluted.
Validator generated block with Empty wthdraws, but after the block was processed by old Geth version, it changed the block body, set the WithDraws to nil, "EmptyArray != nil". It is a known bug, fixed in v1.4.5, but there are still many BSC client not upgrade yet.

<img width="850" alt="image" src="https://github.com/bnb-chain/bsc/assets/152148891/74f34df5-d50a-4291-bd63-e05d494ebb91">

**Comment by madhan5447** [comment]
> PeerFilterPatterns = ["^erigon/v1.2.5.*|^Geth/v1.4.4.*"]

I tried this but didn't help for me kindly give the solution

**Comment by zzzckck** [comment]
> > PeerFilterPatterns = ["^erigon/v1.2.5._|^Geth/v1.4.4._"]
> 
> I tried this but didn't help for me kindly give the solution

we have a hot fix PR: https://github.com/bnb-chain/bsc/pull/2525, you may try the latest develop.
And we will release v1.4.10 for it, or you may wait for it, expected today.

**Comment by fatminer** [comment]
thanks!
