### ISSUE TITLE
Synchronization BSC node has stopped

### ISSUE THREAD

**Issue by Nik-1989** [bnb-chain/bsc#2523]
#### System information

Geth
Version: 1.4.9
Git Commit: 4566ac7659d2de1e6b90523c4ff7f77c73e04fc6
Git Commit Date: 20240611
Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-112-generic x86_64)

Hello, 
Today my node stopped synchronizing. Has anyone encountered such a problem?

`Synchronisation failed, dropping peer" peer=a687b584b5348fbdad40e4f957e85092028b037ea2de81b2b1eb8936a6c9cf7f err=timeout

t=2024-06-20T09:52:43+0000 lvl=info msg="Starting peer-to-peer node" instance=Geth/v1.4.5-a0572458-20240410/linux-amd64/go1.22.2
t=2024-06-20T09:52:43+0000 lvl=info msg="New local node record" seq=1706011557970 id=89bd73d83ea3f0f1e205dc62f34ee4872ad3f22cf401c4b533e5af9725990976 ip=127.0.0.1 udp=30311 tcp=30311
t=2024-06-20T09:52:43+0000 lvl=info msg="IPC endpoint opened" url=/root/node_bsc/geth.ipc
t=2024-06-20T09:52:43+0000 lvl=info msg="HTTP server started" endpoint=127.0.0.1:14367 auth=false prefix="" cors="" vhosts=localhost
t=2024-06-20T09:52:43+0000 lvl=info msg="Started P2P networking" self=enode://5e8377611432b7325964d36eadc48b992635967ac55a8f0fa57a879d4cc35b27307c12d30e08134a4398404643f6c65e40d9c2d658e261250551a4d53037ff58@127.0.0.1:30311
t=2024-06-20T09:52:43+0000 lvl=info msg="New local node record" seq=1706011557971 id=89bd73d83ea3f0f1e205dc62f34ee4872ad3f22cf401c4b533e5af9725990976 ip=xx.xxx.xxx.xxx udp=30311 tcp=30311
t=2024-06-20T09:53:57+0000 lvl=error msg="Bsc extension Handshake failed" peer=e950bf32 err=EOF
t=2024-06-20T09:53:57+0000 lvl=error msg="Bsc extension Handshake failed" peer=eef4e1e8 err=EOF
t=2024-06-20T09:53:58+0000 lvl=error msg="Bsc extension Handshake failed" peer=3dff2759 err=EOF
t=2024-06-20T09:53:58+0000 lvl=error msg="Bsc extension Handshake failed" peer=2efd5859 err=EOF
t=2024-06-20T09:53:58+0000 lvl=error msg="Bsc extension Handshake failed" peer=dacbfb38 err=EOF

I understand this is due to a hard fork on the network.

**Comment by STdevK** [comment]
If I understand your logs correctly, the logs are only showing Bsc extension Handshake failed and nothing else? If that's the case, there might be a deadlock somewhere. Could you change the Level = `"info"` in the config file to Level = `"trace"`, restart your node and share the trace logs here? It'll be easier to debug in this case.

**Comment by Nik-1989** [comment]
[bsc_copy.txt](https://github.com/user-attachments/files/15912759/bsc_copy.txt)


> If I understand your logs correctly, the logs are only showing `Bsc extension Handshake failed` and nothing else? If that's the case, there might be a deadlock somewhere. Could you change the `Level = "info"` in the config file to `Level = "trace"`, restart your node and share the trace logs here? It'll be easier to debug in this case.

**Comment by Nik-1989** [comment]
> admin.nodeInfo
{
  enode: "enode://5e8377611432b7325964d36eadc48b992635967ac55a8f0fa57a879d4cc35b27307c12d30e08134a4398404643f6c65e40d9c2d658e261250551a4d53037ff58@xx.xxx.xxx.xxx:30311",
  enr: "enr:-KK4QHEIRHSPoGAFM-aTdX3dKC5CryiY_kPv7x0SmPrHc4CuOpR8Te4NWj6h5g2IOFE8CD7sQaAd7kQ_m67xPmvK50KGAY02NoBZg2JzY8CDZXRox8aEe2_1C4CCaWSCdjSCaXCEF22QlIlzZWNwMjU2azGhAl6Dd2EUMrcyWWTTbq3Ei5kmNZZ6xVqPD6V6h51Mw1sng3RjcIJ2Z4N1ZHCCdmc",
  id: "89bd73d83ea3f0f1e205dc62f34ee4872ad3f22cf401c4b533e5af9725990976",
  ip: "xx.xxx.xxx.xxx",
  listenAddr: "[::]:30311",
  name: "Geth/v1.4.5-a0572458-20240410/linux-amd64/go1.22.2",
  ports: {
    discovery: 30311,
    listener: 30311
  },
  protocols: {
    bsc: {},
    eth: {
      config: {
        berlinBlock: 31302048,
        brunoBlock: 13082000,
        byzantiumBlock: 0,
        chainId: 56,
        constantinopleBlock: 0,
        eip150Block: 0,
        eip155Block: 0,
        eip158Block: 0,
        eulerBlock: 18907621,
        feynmanFixTime: 1713419340,
        feynmanTime: 1713419340,
        gibbsBlock: 23846001,
        hertzBlock: 31302048,
        hertzfixBlock: 34140700,
        homesteadBlock: 0,
        istanbulBlock: 0,
        keplerTime: 1705996800,
        londonBlock: 31302048,
        lubanBlock: 29020050,
        mirrorSyncBlock: 5184000,
        moranBlock: 22107423,
        muirGlacierBlock: 0,
        nanoBlock: 21962149,
        nielsBlock: 0,
        parlia: {...},
        petersburgBlock: 0,
        planckBlock: 27281024,
        platoBlock: 30720096,
        ramanujanBlock: 0,
        shanghaiTime: 1705996800
      },
      difficulty: 79010754,
      genesis: "0x0d21840abff46b96c84b2ac9e10e4f5cdaeb5693cb665db62a2f3b02d2d57b5b",
      head: "0x85f6afcb7542bda2f701e769eeb650e3d15ba4760ce3c16cb15eb3e934ebb329",
      network: 56
    }
  }
}

**Comment by yulms** [comment]
Same issue after updating from 1.3.* to latest 1.4.9.

[bsc.log.zip](https://github.com/user-attachments/files/15913926/bsc.log.zip)

**Comment by Nik-1989** [comment]
The problem was solved, I connected the old geth file

**Comment by Nik-1989** [comment]
> Same issue after updating from 1.3.* to latest 1.4.9.
> 
> [bsc.log.zip](https://github.com/user-attachments/files/15913926/bsc.log.zip)

Try downloading 1.4.8

wget https://github.com/bnb-chain/bsc/releases/download/v1.4.8/geth_linux
mv geth_linux geth
chmod -v u+x geth

**Comment by zzzckck** [comment]
@Nik-1989 ok to close this issue?

**Comment by yulms** [comment]
I don’t know what happened, but it worked for me as it should
