### ISSUE TITLE
Served eth_getRawTransactionByHash" reqid=1718886337922 t=149.051µs err="transaction indexing is in progress" X-Forwarded-For=<nil>

### ISSUE THREAD

**Issue by AlexKNM** [bnb-chain/bsc#2524]
#### System information

Geth version: instance=Geth/v1.4.9-4566ac76-20240611/linux-amd64/go1.22.1
OS & Version: Ubuntu
Commit hash : (if `develop`)

#### Expected behaviour
Return a transaction with no error like previous versions.

#### Actual behaviour
t=2024-06-20T12:25:37+0000 lvl=warn msg="Served eth_getRawTransactionByHash" reqid=1718886337922 t=149.051µs err="transaction indexing is in progress" X-Forwarded-For=<nil>
t=2024-06-20T12:25:37+0000 lvl=warn msg="Served eth_getRawTransactionByHash" reqid=1718886337922 duration=148.5µs err="transaction indexing is in progress" errdata="transaction indexing is in progress"

#### Steps to reproduce the behaviour
Requedst eth_getRawTransactionByHash

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by zzzckck** [comment]
seems like your node has not synced yet, it is in tx index phase.

**Comment by zzzckck** [comment]
@AlexKNM is your node ok now?

**Comment by zzzckck** [comment]
close this one, track in https://github.com/bnb-chain/bsc/issues/2531
