### ISSUE TITLE
ERROR Unexpected error when getting snapshot   error="unknown ancestor" blockNumber=39,378,510 blockHash=5a9470..0f6f68

### ISSUE THREAD

**Issue by osizadmin** [bnb-chain/bsc#2529]
I install new wallet in new server with version ubuntu 22 & bsc Releases v1.4.10. its showing this error.

Error Alert: Some nodes on the Binance Smart Chain (BSC) network are encountering unexpected errors related to block decoding and an "unknown ancestor" issue. Here are the details:
Error Message: ERROR[06-21|14:46:02.948] Unexpected error when getting snapshot error="unknown ancestor" blockNumber=39,378,603 blockHash=e5401d..7bbb2d
Additional Errors: WARN [06-21|14:46:03.020] Failed to decode block body block=39,288,647 error=EOF

WARN [06-21|14:46:03.130] Unclean shutdown detected                booted=2024-06-21T12:21:44+0000 age=2h24m19s

Please let me know how to resolve this

**Comment by osizadmin** [comment]
Hello Team,

Now currentBlock: 39970716
highestBlock: 39970455,

> eth.syncing.highestBlock - eth.syncing.currentBlock
-302

currentBlock (39970716) is greater than highestBlock

please let me know how to resolve this?

**Comment by zzzckck** [comment]
https://github.com/bnb-chain/bsc/pull/862/files#diff-3c2d807e8f58e4a69928b183eb41bdf8f33b758bc87be98b5821dbb0887bb5eeR456
<img width="1081" alt="image" src="https://github.com/bnb-chain/bsc/assets/152148891/c601aedc-e4d4-4ac5-b269-25657c1847e8">
@joeylichang

**Comment by zzzckck** [comment]
fixed in: https://github.com/bnb-chain/bsc/pull/2562

**Comment by zzzckck** [comment]
> https://github.com/bnb-chain/bsc/pull/862/files#diff-3c2d807e8f58e4a69928b183eb41bdf8f33b758bc87be98b5821dbb0887bb5eeR456 <img alt="image" width="1081" src="https://private-user-images.githubusercontent.com/152148891/346400308-c601aedc-e4d4-4ac5-b269-25657c1847e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2Mzk0MDEsIm5iZiI6MTcyMTYzOTEwMSwicGF0aCI6Ii8xNTIxNDg4OTEvMzQ2NDAwMzA4LWM2MDFhZWRjLWU0ZDQtNGFjNS1iMjY5LTI1NjU3YzE4NDdlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQwOTA1MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xN2JhZThiMzA0MGFlMTJhY2YxYTA5OTZjOTc3ZTU3YTRmNzQzZGY3Njg2ZTgyODc2OWViMWFmZjJmMmFmYTJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._NVMAiSXCpihRh27lkZeRJqc6G2QWbI0sLQPobVl5m8"> @joeylichang can we just remove the following part of code in function: `gcKVStore(...)`?
> 
> ```
> // Step into the future and delete and dangling side chains
> if frozen > 0 {
> ...
> }
> ```

removed in this PR: https://github.com/bnb-chain/bsc/pull/2582/files
