### ISSUE TITLE
stability: skip sign off-turn block, if validators is about to be in turn.

### ISSUE THREAD

**Issue by zzzckck** [bnb-chain/bsc#2530]
# Rationale
take this scenario for example:
1.block N+1:       in-turn, by validator#1 
2.block N+2: validator#2 missed it, several off-turn block
  2.1. off-turn, by validator#3
  2.2. off-turn, by validator#4 // it was accepted by the majority of the validators,
3.block N+3: validator#3 has to reorg and sign the block, but it is could be too later
  3.2. off-turn, by validator#5 and slashed validator#3

Will draft a diagram to make it easier to understand.

And ,IMO off-turn block is bad, it could make the network unstable and have more off-turn blocks, we can a design to eliminate the off-turn block, if 2/3 validator failed to receive the block in time. They can vote to reject the block, the next proposer only need to mine a in-turn block with these reject-votes.
# Implementation
NA

**Comment by NathanBSC** [comment]
only one validator in every height can produce blocks, that's BTF-like algos, It's a big change

**Comment by buddh0** [comment]
> # Rationale
> take this scenario for example: 1.block N+1: in-turn, by validator#1 2.block N+2: validator#2 missed it, several off-turn block 2.1. off-turn, by validator#3 2.2. off-turn, by validator#4 // it was accepted by the majority of the validators, 3.block N+3: validator#3 has to reorg and sign the block, but it is could be too later 3.2. off-turn, by validator#5 and slashed validator#3
> 
> Will draft a diagram to make it easier to understand.
> 
> And ,IMO off-turn block is bad, it could make the network unstable and have more off-turn blocks, we can a design to eliminate the off-turn block, if 2/3 validator failed to receive the block in time. They can vote to reject the block, the next proposer only need to mine a in-turn block with these reject-votes.
> 
> # Implementation
> NA

reorg not cost much, 
validator#3 has 3 seconds to import block 2.2, and create it's in-turn blocks

**Comment by zzzckck** [comment]
![image](https://github.com/bnb-chain/bsc/assets/152148891/c686c3af-6139-42c4-94ef-a842b9ba7fdc)
Can not find the related log yet, draft the diagram to demonstrate the potential case, but seems not a bit issue, so close it.
