### ISSUE TITLE
highestBlock lessthan currentBlock, rpc error: transaction indexing is in progress.

### ISSUE THREAD

**Issue by siwenHT** [bnb-chain/bsc#2531]
> eth.syncing
{
  currentBlock: 39843864,
  healedBytecodeBytes: 0,
  healedBytecodes: 0,
  healedTrienodeBytes: 0,
  healedTrienodes: 0,
  healingBytecode: 0,
  healingTrienodes: 0,
  highestBlock: 39843824,
  startingBlock: 39843804,
  syncedAccountBytes: 0,
  syncedAccounts: 0,
  syncedBytecodeBytes: 0,
  syncedBytecodes: 0,
  syncedStorage: 0,
  syncedStorageBytes: 0,
  txIndexFinishedBlocks: "0x9fcaec",
  txIndexRemainingBlocks: "0x1c02d2d"
}

**Comment by zzzckck** [comment]
> txIndexFinishedBlocks: "0x9fcaec",
> txIndexRemainingBlocks: "0x1c02d2d"
====
txIndex is in progress, so it is not synced yet. txIndex could take a few hours. Is it ok now? @siwenHT

**Comment by zzzckck** [comment]
close this one, track in: https://github.com/bnb-chain/bsc/issues/2533
