### ISSUE TITLE
########## BAD BLOCK #########

### ISSUE THREAD

**Issue by epsil0n0** [bnb-chain/bsc#2554]
I got this error on BSC node: (geth_1.3.13)

t=2024-06-28T11:52:10+0200 lvl=error msg="validate state failed" error="invalid gas used (remote: 38315741 local: 38143163)"
t=2024-06-28T11:52:10+0200 lvl=error msg="\n########## BAD BLOCK #########\nBlock: 39954864 (0x7497259d3390ff97bf8ed4632a7e109df6a6627631a5fbca6f86022422395a62)\nMiner: 0x8A239732871AdC8829EA2f47e94087C5FBad47b6\nError: invalid gas used (remote: 38315741 local: 38143163)\nPlatform: geth (devel) go1.21.11 amd64 linux\nVCS: 71941255-20240627 (dirty)\nChain config: &params.ChainConfig{ChainID:56, HomesteadBlock:0, DAOForkBlock:<nil>, DAOForkSupport:false, EIP150Block:0, EIP155Block:0, EIP158Block:0, ByzantiumBlock:0, ConstantinopleBlock:0, PetersburgBlock:0, IstanbulBlock:0, MuirGlacierBlock:0, BerlinBlock:31302048, YoloV3Block:<nil>, CatalystBlock:<nil>, LondonBlock:31302048, ArrowGlacierBlock:<nil>, GrayGlacierBlock:<nil>, MergeNetsplitBlock:<nil>, ShanghaiTime:(*uint64)(0xc00013daf8), KeplerTime:(*uint64)(0xc00013db00), FeynmanTime:(*uint64)(0xc00013db08), FeynmanFixTime:(*uint64)(0xc00013db10), CancunTime:(*uint64)(0xc00013db18), HaberTime:(*uint64)(0xc00013db20), HaberFixTime:(*uint64)(nil), BohrTime:(*uint64)(nil), PragueTime:(*uint64)(nil), VerkleTime:(*uint64)(nil), TerminalTotalDifficulty:<nil>, TerminalTotalDifficultyPassed:false, RamanujanBlock:0, NielsBlock:0, MirrorSyncBlock:5184000, BrunoBlock:13082000, EulerBlock:18907621, GibbsBlock:23846001, NanoBlock:21962149, MoranBlock:22107423, PlanckBlock:27281024, LubanBlock:29020050, PlatoBlock:30720096, HertzBlock:31302048, HertzfixBlock:34140700, Ethash:(*params.EthashConfig)(nil), Clique:(*params.CliqueConfig)(nil), Parlia:(*params.ParliaConfig)(0x4979130)}\nReceipts: \n  0: cumulative: 23032 gas: 23032 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x671a5e0bdada7e24b900bfdd673372d83328899d041d6e570de64f170411b9d2 logs: [] bloom: 

I updated the BSC to latest version (1.4.11),  but the error not resolved. The full log attached here.

[bsc.log](https://github.com/user-attachments/files/16027785/bsc.log)

**Comment by galaio** [comment]
<img width="1239" alt="image" src="https://github.com/bnb-chain/bsc/assets/12880651/66774915-23be-4d1f-ac57-db2046b61d93">

**Comment by epsil0n0** [comment]
Hi
Thank you
The full log attached here:
[full-log.txt](https://github.com/user-attachments/files/16048153/full-log.txt)

I am downloading the snapshot to test it.

**Comment by galaio** [comment]
Hi, how's it going now? Is there anything else I can help you with?
