### ISSUE TITLE
Question regarding pbss and pruning

### ISSUE THREAD

**Issue by zhk101** [bnb-chain/bsc#2555]
A few weeks back I read some issues related to pruning not working anymore or causing issues with the latest version of geth.
I've recently saw some commit around fixing pruning (eg: #2481).
Also read (https://www.bnbchain.org/en/blog/optimizing-blockchain-storage-bscs-path-based-storage-system) that `PBSS, introduced in BSC's V1.3.1-beta release, addresses these concerns by introducing an online state prune feature`

My node is using a path-based (pbss) snapshot from bnb48. I've removed a while ago the prunestate parameter to my node startup params.
Can it be added back now? Is it still needed? Also, if a node has been running for long without that flag, can it be added later on and would it prune its backlog?

**Comment by zzzckck** [comment]
I've removed a while ago the prunestate parameter to my node startup params.
====
what is the params? do you mean "--pruneancient"?

**Comment by zhk101** [comment]
> what is the params? do you mean "--pruneancient"?

yes, that one

**Comment by zzzckck** [comment]
> > what is the params? do you mean "--pruneancient"?
> 
> yes, that one

There is some potential issue regarding to this flag: "--pruneancient", we are working on it, better not use this flag right now.
But for nodes that are already running with flag, it is fine, no need to switch it off.
