### ISSUE TITLE
BNB Faucet Testnet Keep Loading After Bypassing Recaptcha

### ISSUE THREAD

**Issue by ghtest2522** [bnb-chain/bsc#2560]
Hey guys, I have been obtaining tokens using the testnet but yesterday and today, it stopped working. keeps on loading. last time i was able to obtain a token was 3 days ago. 

whenever i bypass recaptcha it keeps on loading

![image](https://github.com/bnb-chain/bsc/assets/97832714/17335f33-a4b0-47da-adca-743e1949edba)

I tried from other devices, same issue

**Comment by zzzckck** [comment]
recovered, there is a stability bug in faucet.
