### ISSUE TITLE
BNB Faucet not working

### ISSUE THREAD

**Issue by klynch999** [bnb-chain/bsc#2577]
BNB faucet is not working. I'm having the exact same issue as the closed issue described here: https://github.com/bnb-chain/bsc/issues/2560

**Comment by jhonessantos** [comment]
I'm on the same issue. Could you guys send me tBNB?
0xDDA622C95B7195010B377c51885F5f89A33E79cB

**Comment by klynch999** [comment]
my wallet is 0xb61C4e7b70AEF8f8B66Dad43d3BB3302c5A2f140 i would appreciate some tBNB also.

**Comment by saad662** [comment]
If someone can send me some tBNB it would be great, 0x958143a251EBBF42b287B782BC5B255f36aCDB59

**Comment by cpsjk11** [comment]
Hello, I am a junior blockchain developer. I also have the same problem and am in a difficult testing environment. If anyone can send me tBNB please send it thanks 0x7b19f0B156a5E199B298110e0BFE94eAF42c1AE0

**Comment by zzzckck** [comment]
should worked now, pls try.

**Comment by KangTHecat** [comment]
@zzzckck request has been pending for hours. The faucet is not working again.
