### ISSUE TITLE
Finality has stalled on Bsc Tesnet

### ISSUE THREAD

**Issue by Wizdave97** [bnb-chain/bsc#2590]
#### Expected behaviour
Blocks should have aggregated BLS signature of validators

#### Actual behaviour

Finality has stalled on BSC testnet for some epochs, this issue can be seen in block 42156200-42161872
There are no BLS signatures in any block beyond this point.

#### Steps to reproduce the behaviour
Check the extra data of all blocks in this range https://testnet.bscscan.com/block/42161853 - https://testnet.bscscan.com/block/42161872

**Comment by STdevK** [comment]
We are checking on the issue

**Comment by zzzckck** [comment]
thx for your feedback, there is an incident for BSC testnet during that time, some validator got migrated to new devices and their vote keys failed to set up during that period.
It has recovered now.
