### ISSUE TITLE
BSC RPC endpoint returning null values

### ISSUE THREAD

**Issue by chriscollinsgit** [bnb-chain/bsc#2592]
Since Saturday the BSC RPC endpoint has been returning many frequent null values. I notice this especially with the eth_getBlockByNumber function. This issue is occurring regardless of which public node I connect to.

#### Expected behaviour

It should return a json with lots of block information like below.

`curl -X POST 'https://rpc.ankr.com/bsc' \
-H 'Content-Type: application/json' \
-d '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x16efa24",true],"id":83}'
{"id":83,"jsonrpc":"2.0","result":{"difficulty":"0x2","extraData":"0xd983010112846765746889676f312e31372e3133856c696e757800005b7663b582ae54bdc2baf7863ad62683ae8af39cdfa1a2717b12d2c28045b84338f58f1a79d95e62431d4d1e06064b00619f146dd56297d3d8f ..............`

#### Actual behaviour
However, it is frequently returning a null value

`curl -X POST 'https://rpc.ankr.com/bsc' \
-H 'Content-Type: application/json' \
-d '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x16efa24",true],"id":83}'
{"id":83,"jsonrpc":"2.0","result":null}%`

I am not sure if this is the correct place to report the issue. If not can you provide guidance as to where the correct place might be.

**Comment by zzzckck** [comment]
```
curl -X POST https://rpc.ankr.com/bsc -H 'Content-Type: application/json'  -d '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x16efa24",true],"id":83}'
```
I just tried 10 times, it works for me.
Is there any steps to reproduce your issue?

I think `https://rpc.ankr.com/bsc` is provided by [ankr](https://www.ankr.com/)
Maybe you can try this rpc url: `https://bsc-dataseed-public.bnbchain.org`, it works for me as well.
