### ISSUE TITLE
Are there any endpoints that are provided free of charge?

### ISSUE THREAD

**Issue by junghyun0783** [bnb-chain/bsc#2593]
I have a question.

https://docs.bnbchain.org/bnb-smart-chain/developers/rpc/
If you go to the link here, you will find the JSON-RPC Endpoint.

Is this endpoint available for free and unlimited use?
Or will it be paid based on the number of requests?

I would like to ask for answers from experts!
thank you

**Comment by STdevK** [comment]
You can check out the third-party service provider for a higher request rate.
https://docs.bnbchain.org/bnb-smart-chain/developers/rpc/#rpc-providers

**Comment by zzzckck** [comment]
> I have a question.
> 
> https://docs.bnbchain.org/bnb-smart-chain/developers/rpc/ If you go to the link here, you will find the JSON-RPC Endpoint.
> 
> Is this endpoint available for free and unlimited use? Or will it be paid based on the number of requests?
> 
> I would like to ask for answers from experts! thank you

these RPC endpoint are free, but with rate limit.
