### ISSUE TITLE
BSC light mode

### ISSUE THREAD

**Issue by crypt0inf0** [bnb-chain/bsc#2594]
@zzzckck I know light node is deprecated, Is there is a way to run the node with low storage space like 5GB because I have dapps talking to the paid wss (websocket) provider.

I don't want any ancient block data only the latest 5000 blocks will work fine for my requirements.

**Comment by zzzckck** [comment]
> @zzzckck I know light node is deprecated, Is there is a way to run the node with low storage space like 5GB because I have dapps talking to the paid wss (websocket) provider.
> 
> I don't want any ancient block data only the latest 5000 blocks will work fine for my requirements.

5GB? I'm afraid even light mode could take more then 5GB.
I am sorry that it is not supported currently

**Comment by zzzckck** [comment]
@crypt0inf0 let me know, if u need this support strongly, otherwise we have no plan to support.

**Comment by zzzckck** [comment]
> @zzzckck If many developers needs to subscribe to the light weight node then providing a support for it is a good thing.

yea, do you know how Ethereum handle such kind of request? As Geth no longer support light client as well.

**Comment by crypt0inf0** [comment]
Check out,
https://github.com/ethereum/go-ethereum/issues/29367 
https://github.com/ethereum/go-ethereum/issues?q=beacon%2Flight 
https://github.com/ethereum/go-ethereum/issues/28499
