### ISSUE TITLE
There are some typo issues on the BNB Smart Chain Documentation

### ISSUE THREAD

**Issue by DevGoatX** [bnb-chain/bsc#2609]
![The space issue](https://github.com/user-attachments/assets/6adb4388-fb3b-42a8-9b29-1e05d04fabcb)
![typo1](https://github.com/user-attachments/assets/54c6c44f-7866-4434-a17a-74a12f1d8d94)
![typo2](https://github.com/user-attachments/assets/290374c4-234b-4a6c-aa43-9f7130bd84b3)
![typo3](https://github.com/user-attachments/assets/5cdff69c-d229-461b-b100-4d8b9a59add4)

**Comment by STdevK** [comment]
Thank you for sharing, changes will be made shortly

**Comment by Kerrypinny** [comment]
Hello @DevGoatX 
You're experiencing transcript error. It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID BNB07638
Please see the link below to our dedicated support line:
[BNB Support Requests ](https://dappscustomersupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat

**Comment by zzzckck** [comment]
fixed in https://github.com/bnb-chain/bnb-chain.github.io/pull/420
