### ISSUE TITLE
I want to get the data of Internal Txns.

### ISSUE THREAD

**Issue by junghyun0783** [bnb-chain/bsc#2625]
Hello!
I have a question.
I want to use debug_traceBlockByHash, debug_traceTransaction RPC in BNB, but when I make a request, the value is

request :  
{
    "jsonrpc": "2.0", 
    "id": "1",                    
    "method": "debug_traceBlockByHash",
    "params": ["0xb384412cb17ef410f6f14a19832641e42dbc933875bd83014fe7a0ac95570775", {"tracer": "callTracer"}]
}
response : 
{
"jsonrpc": "2.0",
"id": "1",
"error": {
"code": -32000,
"message": "missing trie node"
}
}

This is what I get.
The endpoint is "https://bsc-testnet-dataseed.bnbchain.org".
Why doesn't it work?
I want to get the data of Internal Txns.
Is there an RPC that can get the data of Internal Txns?
Please help me, experts!!!!

**Comment by zzzckck** [comment]
try this endpoint: https://bsc-prebsc-dataseed.bnbchain.org, it may work. but as it is not an archive node, you can only trace the most recent 128 blocks

**Comment by junghyun0783** [comment]
@zzzckck 
Thanks for your kind reply.
Is there any endpoint that provides archive nodes?
I need to query blocks older than 128 blocks.

**Comment by zzzckck** [comment]
> @zzzckck Thanks for your kind reply. Is there any endpoint that provides archive nodes? I need to query blocks older than 128 blocks.

sorry, there is no free archive node service right now, but there is a charged one provided by meganode, refer: https://nodereal.io/meganode
