### ISSUE TITLE
I have a question, how do I determine whether I am using PathSchema&PebbleDB or HashSchema&LevelDB?

### ISSUE THREAD

**Issue by astrid19981112** [bnb-chain/bsc#2639]
cat config.toml 
[Eth]
NetworkId = 56
LightPeers = 100
TrieTimeout = 150000000000
[Eth.Miner]
GasCeil = 140000000
GasPrice = 3000000000
Recommit = 10000000000

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 3000000000
PriceBump = 10
AccountSlots = 200
GlobalSlots = 8000
AccountQueue = 200
GlobalQueue = 4000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 1000

[Node]
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
InsecureUnlockAllowed = false
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 200
NoDiscovery = false
StaticNodes = []
ListenAddr = ":30311"
EnableMsgEvents = false

[Node.LogConfig]
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""

The command to run is this
/data/geth_linux --config ./config.toml --datadir ./geth/ --cache 8000 --rpc.allow-unprotected-txs --tries-verify-mode none --history.transactions=0 --syncmode=full --tries-verify-mode=local --pruneancient --db.engine=pebble

**Comment by zzzckck** [comment]
pls refer: https://forum.bnbchain.org/t/faq-pbss-pebbledb/2260#p-3633-q2-how-to-check-nodes-running-mode-6

**Comment by astrid19981112** [comment]
OK Then the fact that I printed this log shows that my node is using the PBSS and PebbleDB modes normally, right?
![image](https://github.com/user-attachments/assets/e851cbbf-5ecb-4b29-bf16-d27677d165e1)

**Comment by astrid19981112** [comment]
OK Then the fact that I printed this log shows that my node is using the PBSS and PebbleDB modes normally, right?

cat bsc.log.2024-08-16_* |grep -E "scheme|backing database"
t=2024-08-16T09:30:57+0800 lvl=info msg="Using pebble as the backing database"
t=2024-08-16T09:30:57+0800 lvl=info msg="State scheme set to already existing disk db" scheme=path
t=2024-08-16T09:30:57+0800 lvl=info msg="Allocated memory caches" state_scheme=path trie_clean_cache="2.88 GiB" trie_dirty_cache="256.00 MiB" snapshot_cache="1.56 GiB"
t=2024-08-16T09:46:07+0800 lvl=info msg="Using pebble as the backing database"
t=2024-08-16T09:46:14+0800 lvl=info msg="State scheme set to already existing disk db" scheme=path
t=2024-08-16T09:46:14+0800 lvl=info msg="Allocated memory caches" state_scheme=path trie_clean_cache="2.88 GiB" trie_dirty_cache="256.00 MiB" snapshot_cache="1.56 GiB"

**Comment by Ahmedalmmm** [comment]
Abooalm@yahoo.com

**Comment by zzzckck** [comment]
> OK Then the fact that I printed this log shows that my node is using the PBSS and PebbleDB modes normally, right?
> 
> cat bsc.log.2024-08-16_* |grep -E "scheme|backing database" t=2024-08-16T09:30:57+0800 lvl=info msg="Using pebble as the backing database" t=2024-08-16T09:30:57+0800 lvl=info msg="State scheme set to already existing disk db" scheme=path t=2024-08-16T09:30:57+0800 lvl=info msg="Allocated memory caches" state_scheme=path trie_clean_cache="2.88 GiB" trie_dirty_cache="256.00 MiB" snapshot_cache="1.56 GiB" t=2024-08-16T09:46:07+0800 lvl=info msg="Using pebble as the backing database" t=2024-08-16T09:46:14+0800 lvl=info msg="State scheme set to already existing disk db" scheme=path t=2024-08-16T09:46:14+0800 lvl=info msg="Allocated memory caches" state_scheme=path trie_clean_cache="2.88 GiB" trie_dirty_cache="256.00 MiB" snapshot_cache="1.56 GiB"

yes, your node is already running with PBSS and PebbleDB mode
