### ISSUE TITLE
use Geth fast node with pbss error  BAD BLOCK

### ISSUE THREAD

**Issue by yuanwj210** [bnb-chain/bsc#2642]
#### System information

Geth version: `geth 1.4.13`
OS & Version: ubuntu 22.04
 
```ERROR[08-12|13:39:18.520] 
########## BAD BLOCK #########
Block: 40892675 (0xeb02fffb1f8b620ed6e52a73903ecc3892a1b4d5e2c7156b3d2742bf49ef864c)
Miner: 0x502aECFE253E6AA0e8D2A06E12438FFeD0Fe16a0
Error: could not apply tx 7 [0x7a39eee295e3aea5b65867235f28baf03464d91cff0ecadd010c5d70eb5cb77d]: nonce too high: address 0xD7fAfE7B9A291D62Dd01E31A85936B72F1B2284d, tx: 37150 state: 0
Platform: geth (devel) go1.21.12 amd64 linux
VCS: 26a4d4fd-20240808 (dirty)
Chain config: &params.ChainConfig{ChainID:56, HomesteadBlock:0, DAOForkBlock:<nil>, DAOForkSupport:false, EIP150Block:0, EIP155Block:0, EIP158Block:0, ByzantiumBlock:0, ConstantinopleBlock:0, PetersburgBlock:0, IstanbulBlock:0, MuirGlacierBlock:0, BerlinBlock:31302048, YoloV3Block:<nil>, CatalystBlock:<nil>, LondonBlock:31302048, ArrowGlacierBlock:<nil>, GrayGlacierBlock:<nil>, MergeNetsplitBlock:<nil>, ShanghaiTime:(*uint64)(0xc000131c98), KeplerTime:(*uint64)(0xc000131ca0), FeynmanTime:(*uint64)(0xc000131ca8), FeynmanFixTime:(*uint64)(0xc000131cb0), CancunTime:(*uint64)(0xc000131cb8), HaberTime:(*uint64)(0xc000131cc0), HaberFixTime:(*uint64)(nil), BohrTime:(*uint64)(nil), PragueTime:(*uint64)(nil), VerkleTime:(*uint64)(nil), TerminalTotalDifficulty:<nil>, TerminalTotalDifficultyPassed:false, RamanujanBlock:0, NielsBlock:0, MirrorSyncBlock:5184000, BrunoBlock:13082000, EulerBlock:18907621, GibbsBlock:23846001, NanoBlock:21962149, MoranBlock:22107423, PlanckBlock:27281024, LubanBlock:29020050, PlatoBlock:30720096, HertzBlock:31302048, HertzfixBlock:34140700, Ethash:(*params.EthashConfig)(nil), Clique:(*params.CliqueConfig)(nil), Parlia:(*params.ParliaConfig)(0x4a050b0)}

**Comment by yuanwj210** [comment]
ERROR[08-13|02:19:31.205] Error in block freeze operation          err="canonical hash missing, can't freeze block 120000"

**Comment by zzzckck** [comment]
@yuanwj210 could you provide may information about:
1.which snapshot do you use?
2.how do you start your node, the arguments.

**Comment by yuanwj210** [comment]
> @yuanwj210您能否提供以下信息： 1. 您使用哪个快照？ 2. 如何启动节点，参数是什么。
@zzzckck 
snap:https://snapshots.48.club/pbss.fast.40684478.tar.zst
Startup parameter:`--tries-verify-mode none  --cache 28000  --history.transactions 90000 -syncmode=full --db.engine=pebble --rpc.allow-unprotected-txs --diffblock=5000 --pruneancient=true `
I removed the pruneancient parameter and now the block can catch up, but there is still an error as follows: ERROR[08-13|02:19:31.205] Error in block freeze operation err="canonical hash missing, can't freeze block 120000" Error in block freeze operation Err =" Canonical hash missing, can't freeze block 120000",I don't know if this error can be ignored

**Comment by buddh0** [comment]
> diffblock



> > @yuanwj210您能否提供以下信息： 1. 您使用哪个快照？ 2. 如何启动节点，参数是什么。
> > @zzzckck
> > snap:https://snapshots.48.club/pbss.fast.40684478.tar.zst
> > Startup parameter:`--tries-verify-mode none  --cache 28000  --history.transactions 90000 -syncmode=full --db.engine=pebble --rpc.allow-unprotected-txs --diffblock=5000 --pruneancient=true `
> > I removed the pruneancient parameter and now the block can catch up, but there is still an error as follows: ERROR[08-13|02:19:31.205] Error in block freeze operation err="canonical hash missing, can't freeze block 120000" ,I don't know if this error can be ignored.

`but there is still an error `, this error reported periodically？
I tried to reproduce the error log locally, but not successfully.
can you show your config.toml? thx

**Comment by buddh0** [comment]
the reason has been found
a release in next weel will include a fix for it

the error won‘t destroy any data.
