### ISSUE TITLE
Migrating from leveldb to pebbledb. How to enable pebble db backend?

### ISSUE THREAD

**Issue by qezz** [bnb-chain/bsc#2647]
We were running `v1.4.10` on hash+leveldb.

Following the https://forum.bnbchain.org/t/faq-pbss-pebbledb/2260
>  As it is already the default mode, you don’t need extra configuration to use PBSS + PebbleDB.

I fetched the snapshot from https://github.com/48Club/bsc-snapshots?tab=readme-ov-file#geth-full-node-with-pbss, replaced the previous data dir with this one. 

I didnt change any args, as it says in the https://forum.bnbchain.org/t/faq-pbss-pebbledb/2260

After I started the node, I see 

```
Aug 14 09:47:52 geth[88073]: INFO [08-14|09:47:52.454] Using leveldb as the backing database
Aug 14 09:47:52 geth[88117]: INFO [08-14|09:47:52.918] Using leveldb as the backing database
Aug 14 09:47:57 geth[88117]: INFO [08-14|09:47:57.314] Using LevelDB as the backing database
Aug 14 09:47:57 geth[88117]: INFO [08-14|09:47:57.360] State scheme set to default              scheme=path
Aug 14 09:47:57 geth[88117]: INFO [08-14|09:47:57.360] Allocated memory caches                  state_scheme=path trie_clean_cache=33.32GiB trie_dirty_cache=256.00MiB snapshot_cache=16.78GiB
```

Moreover the database dir (chaindata) was automatically wiped by the process, and it's now trying to fetch data from 4y ago.

What am I doing wrong?

**Comment by zzzckck** [comment]
@qezz could you provide the arguments of how to run your node?
And I will double check with 48Club, seems like they provide the snapshot with Path & LevelDB mode.

**Comment by qezz** [comment]
@zzzckck here are the args we use

```
ExecStart=/opt/validators/bsc/bin/1.4.10/geth \
         --datadir /opt/validators/bsc/data \
         --config /opt/validators/bsc/config/config.toml \
         --monitor.doublesign \
         --history.transactions=0 \
         --syncmode=full --tries-verify-mode=none --pruneancient=true --diffblock=5000 \
         --cache 98304 --metrics --metrics.addr="0.0.0.0"
```

**Comment by qezz** [comment]
To clarify, before restart I switched the binary to the "latest stable release", which is 1.4.13

**Comment by buddh0** [comment]
@qezz 
1. how does your datadir looks like?
/opt/validators/bsc/data/chaindata or /opt/validators/bsc/data/geth/chaindata? the later is right.
2. maybe you configured `DBEngine = leveldb` in config.toml, if so please remove it

**Comment by qezz** [comment]
@buddh0 

1

```
root@rpc05:/opt/validators/bsc# realpath data/geth/chaindata/
/opt/validators/bsc/data/geth/chaindata
```

2

```
root@rpc05:/opt/validators/bsc# cat config/config.toml | grep -Ei DBEngine | wc -l
0
```

**Comment by buddh0** [comment]
I tried many times locally, not find the same issue
I think your action `replaced the previous data dir with this one` maybe not execute correctly
you can do more check,
1. before restart with new data, 
      are there. any '*.ldb' files in `data/geth/chaindata/`? or '*.sst' exist? 
     '*.ldb' indacate the leveldb, and  '*.sst' files indacate the pebble db.
2. check the size before restart
      `du -sh /opt/validators/bsc/data/geth`

**Comment by NathanBSC** [comment]
if no other people report the same issue, this issue will be closed 3 days later (08/23)

**Comment by qezz** [comment]
By any chance, is there a flag to force the db backend to be the pebbledb? So we don't need to guess if it's applied properly or not

**Comment by zzzckck** [comment]
> By any chance, is there a flag to force the db backend to be the pebbledb? So we don't need to guess if it's applied properly or not

I am afraid there is no such flag, the database will be determined since genesis block and can not be changed after that.

**Comment by qezz** [comment]
@zzzckck just to clarify then, what is this option? 
<img width="535" alt="image" src="https://github.com/user-attachments/assets/6adf000e-d211-4647-8267-af3487bf4484">

**Comment by zzzckck** [comment]
> @zzzckck just to clarify then, what is this option? <img alt="image" width="535" src="https://private-user-images.githubusercontent.com/5172876/360543253-6adf000e-d211-4647-8267-af3487bf4484.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNzE5NDMsIm5iZiI6MTcyNDM3MTY0MywicGF0aCI6Ii81MTcyODc2LzM2MDU0MzI1My02YWRmMDAwZS1kMjExLTQ2NDctODI2Ny1hZjM0ODdiZjQ0ODQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMDAwNzIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjE2MDA3MGI2YzU5ZjVhMzUzYjJmYmQzOWY0ZGFmMzZjYWI0YTg5ZGZiZjRmNzdmY2RmNDU3MWQxNDFmNzQ1NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lHu-svPrg0S8q-2g5-UyPG9RsvfGhL1Y45IzIfynlBg">

this option try to use PebbleDB, and it will report error if the underlying database format is LevelDB. It can not covert the database, but indicate user wanna use PebbleDB, but it is not the case, it will fail.

**Comment by qezz** [comment]
> this option try to use PebbleDB, and it will report error if the underlying database format is LevelDB. 

That's exactly what I need, thanks.

**Comment by qezz** [comment]
It seems to help or whatever.
Difference was:
- fetched a fresh snapshot
- provided the `--db.engine=pebble` flag
