### ISSUE TITLE
Support compilation with Go 1.23

### ISSUE THREAD

**Issue by yorickdowne** [bnb-chain/bsc#2648]
# Issue

Currently, compilation with Go 1.23 - the current version of Go - fails. Go 1.22 works.

```
151.2 github.com/prysmaticlabs/prysm/v5/validator/accounts
151.4 github.com/ethereum/go-ethereum/cmd/geth
153.1 # github.com/ethereum/go-ethereum/cmd/geth
153.1 link: github.com/fjl/memsize: invalid reference to runtime.stopTheWorld
153.4 util.go:48: exit status 1
153.4 exit status 1
153.5 make: *** [Makefile:16: geth] Error 1
```

**Comment by yorickdowne** [comment]
Upstream: https://github.com/fjl/memsize/issues/5

**Comment by yorickdowne** [comment]
Go team rejected the memsize author’s proposal to make memsize work with Go 1.23.

Upstream go-ethereum fixed this by removing memsize in this patch: https://github.com/ethereum/go-ethereum/commit/e4675771eda550e7eeb63a8884816982c1980644

**Comment by zzzckck** [comment]
> Go team rejected the memsize author’s proposal to make memsize work with Go 1.23.
> 
> Upstream go-ethereum fixed this by removing memsize in this patch: [ethereum/go-ethereum@e467577](https://github.com/ethereum/go-ethereum/commit/e4675771eda550e7eeb63a8884816982c1980644)

@yorickdowne thank your feedback, we can pick this PR as well.
