### ISSUE TITLE
Failed to decode block body, Rpc error: transaction indexing is in progress

### ISSUE THREAD

**Issue by gaiyaa** [bnb-chain/bsc#2650]
Two days ago, I ran the node through the fast snapshot, and the information is as follows:

_8c 16g  500g NVME_
Geth Version: `1.4.13`

Snapshot: _https://snapshots.48.club/pbss.fast.40684478.tar.zst_

Command: `geth_linux --tries-verify-mode none --config ./config.toml --datadir ./data/ --cache 5000 --rpc.allow-unprotected-txs --syncmode=full --db.engine=pebble --history.transactions 0 --pruneancient=true`

eth.syncing:
```
{
  currentBlock: 41374314,
  healedBytecodeBytes: 0,
  healedBytecodes: 0,
  healedTrienodeBytes: 0,
  healedTrienodes: 0,
  healingBytecode: 0,
  healingTrienodes: 0,
  highestBlock: 41374106,
  startingBlock: 41374051,
  syncedAccountBytes: 0,
  syncedAccounts: 0,
  syncedBytecodeBytes: 0,
  syncedBytecodes: 0,
  syncedStorage: 0,
  syncedStorageBytes: 0,
  txIndexFinishedBlocks: 780070,
  txIndexRemainingBlocks: 40594245
}

```
Log Failed to decode block body: 
```
t=2024-08-15T11:49:55+0800 lvl=info msg="Imported new chain segment" number=41374478 hash=0x48755951e302c75079163e0bab1faf9ac1f38f7842894e0d649af8bcec418af7 miner=0x502aECFE253E6AA0e8D2A06E12438FFeD0Fe16a0 blocks=1 txs=118 blobs=0 mgas=11.083233 elapsed=60.542ms mgasps=183.06436062725982 snapdiffs="4.17 MiB" triedirty="0.00 B" trieimutabledirty="0.00 B"
t=2024-08-15T11:49:55+0800 lvl=warn msg="Failed to decode block body" block=40594243 error=EOF
t=2024-08-15T11:49:55+0800 lvl=warn msg="Failed to decode block body" block=40594244 error=EOF
t=2024-08-15T11:49:55+0800 lvl=warn msg="Failed to decode block body" block=40594240 error=EOF
t=2024-08-15T11:49:55+0800 lvl=warn msg="Failed to decode block body" block=40594239 error=EOF
t=2024-08-15T11:49:55+0800 lvl=warn msg="Failed to decode block body" block=40594238 error=EOF
t=2024-08-15T11:49:55+0800 lvl=warn msg="Failed to decode block body" block=40594242 error=EOF
t=2024-08-15T11:49:55+0800 lvl=warn msg="Failed to decode block body" block=40594241 error=EOF
t=2024-08-15T11:49:55+0800 lvl=warn msg="Failed to decode block body" block=40594237 error=EOF
t=2024-08-15T11:49:55+0800 lvl=info msg="Indexed transactions" blocks=0 txs=0 tail=40594245 elapsed=4.443ms
t=2024-08-15T11:49:58+0800 lvl=info msg="Imported new chain segment" number=41374479 hash=0xddd84a065816c415f6fc41beb823ff80f28b9c0d70c02b6477e7aabc6a442e3a miner=0x58567F7A51a58708C8B40ec592A38bA64C0697De blocks=1 txs=109 blobs=0 mgas=12.385677 elapsed=101.170ms mgasps=122.42382120903605 snapdiffs="4.20 MiB" triedirty="0.00 B" trieimutabledirty="0.00 B"
t=2024-08-15T11:49:58+0800 lvl=warn msg="Failed to decode block body" block=40594243 error=EOF
t=2024-08-15T11:49:58+0800 lvl=warn msg="Failed to decode block body" block=40594244 error=EOF
t=2024-08-15T11:49:58+0800 lvl=warn msg="Failed to decode block body" block=40594241 error=EOF
t=2024-08-15T11:49:58+0800 lvl=warn msg="Failed to decode block body" block=40594242 error=EOF
t=2024-08-15T11:49:58+0800 lvl=warn msg="Failed to decode block body" block=40594239 error=EOF
t=2024-08-15T11:49:58+0800 lvl=warn msg="Failed to decode block body" block=40594238 error=EOF
t=2024-08-15T11:49:58+0800 lvl=warn msg="Failed to decode block body" block=40594240 error=EOF
t=2024-08-15T11:49:58+0800 lvl=warn msg="Failed to decode block body" block=40594237 error=EOF
t=2024-08-15T11:49:58+0800 lvl=info msg="Indexed transactions" blocks=0 txs=0 tail=40594245 elapsed=1.630ms
t=2024-08-15T11:50:00+0800 lvl=info msg="Imported new chain segment" number=41374480 hash=0xd3ad3062abaf35f78f7e92bf59a993c92be1a0057c9965bb4e362aeea80f071c miner=0x75B851a27D7101438F45fce31816501193239A83 blocks=1 txs=89 blobs=0 mgas=8.399558 elapsed=154.194ms mgasps=54.47386210127988 snapdiffs="4.22 MiB" triedirty="0.00 B" trieimutabledirty="0.00 B"
t=2024-08-15T11:50:00+0800 lvl=warn msg="Failed to decode block body" block=40594237 error=EOF
t=2024-08-15T11:50:00+0800 lvl=warn msg="Failed to decode block body" block=40594244 error=EOF
t=2024-08-15T11:50:00+0800 lvl=warn msg="Failed to decode block body" block=40594243 error=EOF
t=2024-08-15T11:50:00+0800 lvl=warn msg="Failed to decode block body" block=40594242 error=EOF
t=2024-08-15T11:50:00+0800 lvl=warn msg="Failed to decode block body" block=40594241 error=EOF
t=2024-08-15T11:50:00+0800 lvl=warn msg="Failed to decode block body" block=40594240 error=EOF
t=2024-08-15T11:50:00+0800 lvl=warn msg="Failed to decode block body" block=40594239 error=EOF
t=2024-08-15T11:50:00+0800 lvl=warn msg="Failed to decode block body" block=40594238 error=EOF
t=2024-08-15T11:50:00+0800 lvl=info msg="Indexed transactions" blocks=0 txs=0 tail=40594245 elapsed=1.669ms
```

My question:

**"Failed to decode block body", Does this mistake matter?
Is there any way to speed up the 'txIndex is in progress', which feels slow**

The next day the value changes so little, when will it end?
 `txIndexFinishedBlocks: 808110`

**Comment by buddh0** [comment]
which snapshot do you use?
https://snapshots.48.club/geth.fast.40554701.tar.zst ?

**Comment by gaiyaa** [comment]
> which snapshot do you use?

https://snapshots.48.club/pbss.fast.40684478.tar.zst

**Comment by buddh0** [comment]
<img width="962" alt="image" src="https://github.com/user-attachments/assets/b044c9a2-edec-4a4e-ae96-cd5ac88a4582">
the snapssnapshots provided by club48 has only about 90000 recent blocks

<img width="744" alt="image" src="https://github.com/user-attachments/assets/221aba1b-73d6-42a6-b720-26355fd61952">

so please change the following flag value:

```
--history.transactions 0 --> --history.transactions 90000
```

**Comment by gaiyaa** [comment]
> <img alt="image" width="962" src="https://private-user-images.githubusercontent.com/7995985/358504518-b044c9a2-edec-4a4e-ae96-cd5ac88a4582.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3OTQzMTcsIm5iZiI6MTcyMzc5NDAxNywicGF0aCI6Ii83OTk1OTg1LzM1ODUwNDUxOC1iMDQ0YzlhMi1lZGVjLTRhNGUtYWU5Ni1jZDVhYzg4YTQ1ODIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTZUMDc0MDE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzRhOTI3NzU1NmU5YmJhMDAzZjk0N2U3ZTkwNmZmOTVkMmQ0OTU0MDA5ZWFlY2I2MDk0Y2I0MmM5MjI5YTkwYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZhqT30gvlK4_n_2C-yC4L87EXIqSsrED8iqK8C37fUI"> the snapssnapshots provided by club48 has only about 90000 recent blocks <img alt="image" width="744" src="https://private-user-images.githubusercontent.com/7995985/358504863-221aba1b-73d6-42a6-b720-26355fd61952.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3OTQzMTcsIm5iZiI6MTcyMzc5NDAxNywicGF0aCI6Ii83OTk1OTg1LzM1ODUwNDg2My0yMjFhYmExYi03M2Q2LTQyYTYtYjcyMC0yNjM1NWZkNjE5NTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTZUMDc0MDE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmEwNGViZjIyNjk4YmQwZmYzM2QyYjQ2ZTQ5OWEzZmYzYjk3MjBmZTk1YjFiYjFiZjBlYmUxZGMwY2IxMmZjNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.te8kSxPVvc25BlZrDT2DFSdt2yaO6uNhohJgprPxFwM">
> so please change the following flag value:
> 
> ```
> --history.transactions 0 --> --history.transactions 90000
> ```

**I see. Thank you. That's all right**
