### ISSUE TITLE
ERROR[08-13|02:19:31.205] Error in block freeze operation          err="canonical hash missing, can't freeze block 120000"

### ISSUE THREAD

**Issue by Ahmedalmmm** [bnb-chain/bsc#2652]
ERROR[08-13|02:19:31.205] Error in block freeze operation          err="canonical hash missing, can't freeze block 120000"

_Originally posted by @yuanwj210 in https://github.com/bnb-chain/bsc/issues/2642#issuecomment-2285218162_
            100us

**Comment by Ahmedalm22** [comment]
God 100

**Comment by buddh0** [comment]
checking
