### ISSUE TITLE
skip known block execution without receipt

### ISSUE THREAD

**Issue by jessson** [bnb-chain/bsc#2674]
#### System information

Geth version: 1.4.14
OS & Version: Ubuntu 22.04

#### Logs
t=2024-08-29T03:22:04+0000 lvl=warn msg="Inserted known block" number=41775801 hash=0x9c453f43a6ca964894c67f90ed8673af3026fe2529fe1994e2394eb5be85959d uncles=0 txs=111 gas=11813193 root=0xdec3997132c8c120b155d39ec54a29b717eceb3fde759a8a6ce59e53b4082c32
t=2024-08-29T03:22:04+0000 lvl=error msg="Please file an issue, skip known block execution without receipt" hash=0x9c453f43a6ca964894c67f90ed8673af3026fe2529fe1994e2394eb5be85959d number=41775801
t=2024-08-29T03:22:04+0000 lvl=warn msg="Inserted known block" number=41775802 hash=0x33ab83438451aa1437e7e7eb46b6f86ff76bbdeff16991d85b3404eb90a2b658 uncles=0 txs=128 gas=11354226 root=0x4776382cbf27861260d9afeccf45082971bcd4660f67123a93a692c3b58d648a
t=2024-08-29T03:22:04+0000 lvl=error msg="Please file an issue, skip known block execution without receipt" hash=0x33ab83438451aa1437e7e7eb46b6f86ff76bbdeff16991d85b3404eb90a2b658 number=41775802
t=2024-08-29T03:22:04+0000 lvl=warn msg="Inserted known block" number=41775803 hash=0xedd670fcf730e59c0a7b24600441f35db39c3f7d96f8f9364cc411690d3de5fb uncles=0 txs=136 gas=9366193 root=0x44a8ee013da3761d54e93f027406c1c155bb90349650462db4795c905b21b997
t=2024-08-29T03:22:04+0000 lvl=error msg="Please file an issue, skip known block execution without receipt" hash=0xedd670fcf730e59c0a7b24600441f35db39c3f7d96f8f9364cc411690d3de5fb number=41775803
t=2024-08-29T03:22:04+0000 lvl=warn msg="Inserted known block" number=41775804 hash=0xf29bd215cd13c6795b416b4c475de2152769856264347fae715e898065d39c18 uncles=0 txs=112 gas=11558331 root=0x2a744fd6b6911c2d678c77c2c6cd594866f58971dfbf13e5dca0913dd6e47a16
t=2024-08-29T03:22:04+0000 lvl=error msg="Please file an issue, skip known block execution without receipt" hash=0xf29bd215cd13c6795b416b4c475de2152769856264347fae715e898065d39c18 number=41775804
t=2024-08-29T03:22:04+0000 lvl=warn msg="Inserted known block" number=41775805 hash=0xd3258c42008d50958d4549f292cd122d161c4f02f5c3bc34ea76d042c163e9e0 uncles=0 txs=88 gas=7586878 root=0xd112a25c5607fd2565131141e3550886f24d4c29514637aeba14e3b5e8c92175
t=2024-08-29T03:22:04+0000 lvl=error msg="Please file an issue, skip known block execution without receipt" hash=0xd3258c42008d50958d4549f292cd122d161c4f02f5c3bc34ea76d042c163e9e0 number=41775805

**Comment by buddh0** [comment]
please give more information:
1. the start flag you use and special fields in your config.toml
2. which bsc snapshot you are using?
3. your action against bsc client before this issue happened

thx!

**Comment by jessson** [comment]
1. [Eth]
NetworkId = 56
LightPeers = 100
TrieTimeout = 150000000000

[Eth.Miner]
GasCeil = 140000000
GasPrice = 1000000000
Recommit = 10000000000

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 200
GlobalSlots = 8000
AccountQueue = 200
GlobalQueue = 4000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 1000

[Node.P2P]
MaxPeers = 300
NoDiscovery = false
StaticNodes = []
ListenAddr = ":30311"
EnableMsgEvents = false

[Node.LogConfig]
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""


2.  https://snapshots.48.club/geth.fast.41743263.tar.zst
3.  only syncing

**Comment by STdevK** [comment]
Please sync with the latest snapshot https://snapshots.48.club/geth.fast.41907864.tar.zst

**Comment by NathanBSC** [comment]
@jessson pls follow suggestion form @STdevK 
in addition, if you still get some issue, please also provided the `start flag` at the same time with the error, thx!

**Comment by jessson** [comment]
thx
