### ISSUE TITLE
Transactions stuck in mempool since days/months/years

### ISSUE THREAD

**Issue by iGio90** [bnb-chain/bsc#2699]
Hi :wave: 
I'm sure other mev bot / block builder developers noticed this as well.
There are transactions flying around since a lot of time (even years) which are never being mined. 
I'm genuinely curious to understand what is the problem with such transactions as it is impacting building performances (simulated over and over and attempts to commit in current states).

My current workaround is discarding transactions that I received > 30s, as I see no reason for transactions to not being mined in 6 seconds (2 blocks). When i went deeper into it, im sure some of those were meeting nonce/gas limit constraints (otherwise why is my mempool promoting them?).
Adding code to also purge them from my mempool is not enough as they would get broadcasted again by other peers.

cc @Jolly23 

here are some examples:
https://bscscan.com/tx/0x47bce3e6ab37c0a8078d66da2a2e8fd6094bc458383775b717594bd741a39da3
https://bscscan.com/tx/0x8becb5f51553402b7fde3826a03905a78d79dcdfc20c9eb905f3588930f70079
https://bscscan.com/tx/0x786766fe215cfcfa2559af0aadd669401357f05910ce736ba9a42f5a4c7561f4
https://bscscan.com/tx/0x8015827a969e42b6db1504bc1a0e97f68e84b6139d1206b1b1a7f105cfa836f8
https://bscscan.com/tx/0x93f5063951780295d225d6526dfab8757bc36d07ff3c2e022c72c4a25babb2a1
https://bscscan.com/tx/0x3d3c377d7c692150f93f195d90683f7df02b199deba323613a7c97613fc8f698

but there are many more.

**Comment by zzzckck** [comment]
this is due to its high GasLimit, currently max GasLimit on BSC mainnet is 120000000, it has been addressed by PR https://github.com/bnb-chain/bsc/pull/2680, will be included in next release.
take this tx for example: https://bscscan.com/tx/0x47bce3e6ab37c0a8078d66da2a2e8fd6094bc458383775b717594bd741a39da3
```
    0x3893b383492dfDe3C777ee4f18EaB006998703b9: {
      330: "0x3893b383492dfDe3C777ee4f18EaB006998703b9: 0 wei + 133000000 gas × 3000000000 wei"
    },
```
these transaction will be discarded in the future, as they will never be accepted by validator.

**Comment by iGio90** [comment]
ok cool! please wait to close this. I want to add logs to make sure that those txs have really a high gas limit. As far as i remember when i checked into them, some of them were ok. Give me ~20 minutes

**Comment by iGio90** [comment]
```
tx https://bscscan.com/tx/0xfe192403cb2a18d5d2a36193149e0d332268049ee1478d80aacccbf6144aa813 is too old - gas: 392920
tx https://bscscan.com/tx/0x7c688fbc23891fb0ea583611b3c2edf3db68ab31ffb83c476fc1dbb11f2b7858 is too old - gas: 392920
tx https://bscscan.com/tx/0xb28ec1a42482524cc0d350da4d5d22e5531a5da60d0f9eb59cfadae4e6f59a17 is too old - gas: 392920
tx https://bscscan.com/tx/0xa955bcae9ef922ae9b0036a423ba6f3dc2be982245e01850ddf77a4c3ec8276f is too old - gas: 392920
tx https://bscscan.com/tx/0x41b926bb7dede0374956d7ebf35503aba0c8071ee6df8a34ae8ca58173efc4a2 is too old - gas: 392920
tx https://bscscan.com/tx/0xf355e833420444b6501e2a6e89b67070180106bf20506d3025869c310537ff4f is too old - gas: 420641
tx https://bscscan.com/tx/0xd0b20f8074e5cbb4cff3e47792adf490c2aade9f7b0e174a85e6aeacbed2e383 is too old - gas: 420641
tx https://bscscan.com/tx/0x1e14d56057857e3cb9b37a04208a460252c13fd43a591ecf750e859547e3f851 is too old - gas: 420641
tx https://bscscan.com/tx/0x1178be4b1b77ee5ff9cee2ed261d5c1ecd011345942da95537dcaa0ebe1ee2bd is too old - gas: 420641
tx https://bscscan.com/tx/0xf83d99451e308eaf798a971271750b483e3e97ef875284c6adacd5e4c39a3f08 is too old - gas: 47223
tx https://bscscan.com/tx/0xe6f6e61568c1a01c894d824adb2d731f2c935bc8cdb2c8825218e14ed65c1166 is too old - gas: 132478448
tx https://bscscan.com/tx/0xdfba2ebca0f9a9dc6899a17b6b66b22322355925fb7d737ae75a5cdfd36c2dc1 is too old - gas: 78769
tx https://bscscan.com/tx/0xd0338651d180df93de7e77d9ed42e3cfba2bc662ce1c68c0abbc55b396b30181 is too old - gas: 78769
tx https://bscscan.com/tx/0x336d5763ff4705914422670e383215aaca13f740dc4612ab0ab6ae45e89cc990 is too old - gas: 78769
tx https://bscscan.com/tx/0xb35f88b91d668a40cb992429db86ab153483640a2af899f22d0cb3f7fa46d79c is too old - gas: 78769
tx https://bscscan.com/tx/0x2523c87c126c03d4b904f59429621f040dab35b27328e2035c171b280b90d2fd is too old - gas: 78769
tx https://bscscan.com/tx/0x33db2ad0ec0dd31876ca43cd288a01be096e58bfa0c8d6997fba395fd2dfe752 is too old - gas: 132480469
tx https://bscscan.com/tx/0xbbf325ddb2892efe75a600ba00a1cbacdf2d2c446a394bc2c5ac8ed6759e08ac is too old - gas: 133000000
tx https://bscscan.com/tx/0x26e0734d4646831946451d04091dface3cf1f817b256b3844cda9de36c5d56ae is too old - gas: 133000000
tx https://bscscan.com/tx/0x4759b2a4c8c4d58d70040974850b18461712897244ae9bfebdf9829aab4bc9f4 is too old - gas: 9999999
tx https://bscscan.com/tx/0x1301479ebc43b9e6e34109b261de775afbd6d22ad865ea22bc8e672ad1970095 is too old - gas: 132476426
tx https://bscscan.com/tx/0xd42478572de053f45be7cdb79a255af0405189778729f57cae1b47db052f20c6 is too old - gas: 67454
tx https://bscscan.com/tx/0x0d39869d4c5a0544f72a13cdadf5595aa74168244c4fde805f85c8f09be85c8b is too old - gas: 67454
tx https://bscscan.com/tx/0xd1cb730f2cfa4622074f3010a53e6872ac324562a04a4b2febc565cde95e6651 is too old - gas: 67454
tx https://bscscan.com/tx/0xe4149bdaea11185120987fb96f9bfaf2cc4d40e38baa89aa5473d7d884c43190 is too old - gas: 67454
tx https://bscscan.com/tx/0x30dbd7a3b9d9d0f1c8634633a1eaf891526e44f25deff31181d5a0df8585563f is too old - gas: 85322
tx https://bscscan.com/tx/0x09d4cc4edd2e72dd183ef29c1d027191dee32cedf6e9b7de943ca00cddc91b83 is too old - gas: 132480469
tx https://bscscan.com/tx/0x4643f0f1426698cea0ec4d32971ba4fce61d4f46a0840575ad41103675ff2eb7 is too old - gas: 132478448
tx https://bscscan.com/tx/0xd589a9c5acc02138363eeec84583bbdc82d3de8a9519fcde77ce6c9f8506a4df is too old - gas: 132997969
tx https://bscscan.com/tx/0x7197a398049a9f187c6ee051c3e9165acd238fa9e326ac3569e16183d8562b65 is too old - gas: 434685
tx https://bscscan.com/tx/0x7fe2d7583f37c166f25bfc28789449b1f27a8dfca40e2a1e215e1be79c4ef0f7 is too old - gas: 434685
tx https://bscscan.com/tx/0x1013a3e32841e4a7dfae7c7785116941898cfeaaf4a8ca0859564e26fa9de906 is too old - gas: 120718
tx https://bscscan.com/tx/0xe2305a774f55aee096670c919d7ede9c760cb4da7bd21dddd85faed9d5375df1 is too old - gas: 120718
tx https://bscscan.com/tx/0x6daf669a01a1e9bd2cd99478ca42584fcfe12493a5d96657240595a52a05001a is too old - gas: 77440
tx https://bscscan.com/tx/0xf7419afda9b7f7b85e6bcdad4274c52240126b4cd225b6ba50bd2bd9f0d724be is too old - gas: 133000000
tx https://bscscan.com/tx/0x9ab33791f261ddbe48368e1d1fa9c35d909e1b346d954b73ad6ab76ee49dc087 is too old - gas: 133000000
tx https://bscscan.com/tx/0x3d089e1d5d85250fa0fe20e86022de33d084e9a7ad57b8595a3af2410a695201 is too old - gas: 133000000
```

**Comment by zzzckck** [comment]
> ```
> tx https://bscscan.com/tx/0xfe192403cb2a18d5d2a36193149e0d332268049ee1478d80aacccbf6144aa813 is too old - gas: 392920
> tx https://bscscan.com/tx/0x7c688fbc23891fb0ea583611b3c2edf3db68ab31ffb83c476fc1dbb11f2b7858 is too old - gas: 392920
> tx https://bscscan.com/tx/0xb28ec1a42482524cc0d350da4d5d22e5531a5da60d0f9eb59cfadae4e6f59a17 is too old - gas: 392920
> tx https://bscscan.com/tx/0xa955bcae9ef922ae9b0036a423ba6f3dc2be982245e01850ddf77a4c3ec8276f is too old - gas: 392920
> tx https://bscscan.com/tx/0x41b926bb7dede0374956d7ebf35503aba0c8071ee6df8a34ae8ca58173efc4a2 is too old - gas: 392920
> tx https://bscscan.com/tx/0xf355e833420444b6501e2a6e89b67070180106bf20506d3025869c310537ff4f is too old - gas: 420641
> tx https://bscscan.com/tx/0xd0b20f8074e5cbb4cff3e47792adf490c2aade9f7b0e174a85e6aeacbed2e383 is too old - gas: 420641
> tx https://bscscan.com/tx/0x1e14d56057857e3cb9b37a04208a460252c13fd43a591ecf750e859547e3f851 is too old - gas: 420641
> tx https://bscscan.com/tx/0x1178be4b1b77ee5ff9cee2ed261d5c1ecd011345942da95537dcaa0ebe1ee2bd is too old - gas: 420641
> tx https://bscscan.com/tx/0xf83d99451e308eaf798a971271750b483e3e97ef875284c6adacd5e4c39a3f08 is too old - gas: 47223
> tx https://bscscan.com/tx/0xe6f6e61568c1a01c894d824adb2d731f2c935bc8cdb2c8825218e14ed65c1166 is too old - gas: 132478448
> tx https://bscscan.com/tx/0xdfba2ebca0f9a9dc6899a17b6b66b22322355925fb7d737ae75a5cdfd36c2dc1 is too old - gas: 78769
> tx https://bscscan.com/tx/0xd0338651d180df93de7e77d9ed42e3cfba2bc662ce1c68c0abbc55b396b30181 is too old - gas: 78769
> tx https://bscscan.com/tx/0x336d5763ff4705914422670e383215aaca13f740dc4612ab0ab6ae45e89cc990 is too old - gas: 78769
> tx https://bscscan.com/tx/0xb35f88b91d668a40cb992429db86ab153483640a2af899f22d0cb3f7fa46d79c is too old - gas: 78769
> tx https://bscscan.com/tx/0x2523c87c126c03d4b904f59429621f040dab35b27328e2035c171b280b90d2fd is too old - gas: 78769
> tx https://bscscan.com/tx/0x33db2ad0ec0dd31876ca43cd288a01be096e58bfa0c8d6997fba395fd2dfe752 is too old - gas: 132480469
> tx https://bscscan.com/tx/0xbbf325ddb2892efe75a600ba00a1cbacdf2d2c446a394bc2c5ac8ed6759e08ac is too old - gas: 133000000
> tx https://bscscan.com/tx/0x26e0734d4646831946451d04091dface3cf1f817b256b3844cda9de36c5d56ae is too old - gas: 133000000
> tx https://bscscan.com/tx/0x4759b2a4c8c4d58d70040974850b18461712897244ae9bfebdf9829aab4bc9f4 is too old - gas: 9999999
> tx https://bscscan.com/tx/0x1301479ebc43b9e6e34109b261de775afbd6d22ad865ea22bc8e672ad1970095 is too old - gas: 132476426
> tx https://bscscan.com/tx/0xd42478572de053f45be7cdb79a255af0405189778729f57cae1b47db052f20c6 is too old - gas: 67454
> tx https://bscscan.com/tx/0x0d39869d4c5a0544f72a13cdadf5595aa74168244c4fde805f85c8f09be85c8b is too old - gas: 67454
> tx https://bscscan.com/tx/0xd1cb730f2cfa4622074f3010a53e6872ac324562a04a4b2febc565cde95e6651 is too old - gas: 67454
> tx https://bscscan.com/tx/0xe4149bdaea11185120987fb96f9bfaf2cc4d40e38baa89aa5473d7d884c43190 is too old - gas: 67454
> tx https://bscscan.com/tx/0x30dbd7a3b9d9d0f1c8634633a1eaf891526e44f25deff31181d5a0df8585563f is too old - gas: 85322
> tx https://bscscan.com/tx/0x09d4cc4edd2e72dd183ef29c1d027191dee32cedf6e9b7de943ca00cddc91b83 is too old - gas: 132480469
> tx https://bscscan.com/tx/0x4643f0f1426698cea0ec4d32971ba4fce61d4f46a0840575ad41103675ff2eb7 is too old - gas: 132478448
> tx https://bscscan.com/tx/0xd589a9c5acc02138363eeec84583bbdc82d3de8a9519fcde77ce6c9f8506a4df is too old - gas: 132997969
> tx https://bscscan.com/tx/0x7197a398049a9f187c6ee051c3e9165acd238fa9e326ac3569e16183d8562b65 is too old - gas: 434685
> tx https://bscscan.com/tx/0x7fe2d7583f37c166f25bfc28789449b1f27a8dfca40e2a1e215e1be79c4ef0f7 is too old - gas: 434685
> tx https://bscscan.com/tx/0x1013a3e32841e4a7dfae7c7785116941898cfeaaf4a8ca0859564e26fa9de906 is too old - gas: 120718
> tx https://bscscan.com/tx/0xe2305a774f55aee096670c919d7ede9c760cb4da7bd21dddd85faed9d5375df1 is too old - gas: 120718
> tx https://bscscan.com/tx/0x6daf669a01a1e9bd2cd99478ca42584fcfe12493a5d96657240595a52a05001a is too old - gas: 77440
> tx https://bscscan.com/tx/0xf7419afda9b7f7b85e6bcdad4274c52240126b4cd225b6ba50bd2bd9f0d724be is too old - gas: 133000000
> tx https://bscscan.com/tx/0x9ab33791f261ddbe48368e1d1fa9c35d909e1b346d954b73ad6ab76ee49dc087 is too old - gas: 133000000
> tx https://bscscan.com/tx/0x3d089e1d5d85250fa0fe20e86022de33d084e9a7ad57b8595a3af2410a695201 is too old - gas: 133000000
> ```

once the first transaction from the account triggered this issue, its following transaction will be pending as well, even they has smaller GasLimit, take addr: 0x8c6Db404C9f25134103075030e8b776be1F6E868 for example
```
    0x8c6Db404C9f25134103075030e8b776be1F6E868: {
      1160: "0xd058feF7392691769F4d7615EFC0b1466b8C5449: 0 wei + 132997969 gas × 1000000000 wei",
      1161: "0xd058feF7392691769F4d7615EFC0b1466b8C5449: 0 wei + 434685 gas × 1000000000 wei",
      1162: "0xd058feF7392691769F4d7615EFC0b1466b8C5449: 0 wei + 434685 gas × 1000000000 wei",
      1163: "0x8c6Db404C9f25134103075030e8b776be1F6E868: 0 wei + 120718 gas × 3630000000 wei",
      1164: "0x7F05675f1d26d98cFAe513217954347Ab3f4c749: 0 wei + 120718 gas × 3300000000 wei",
      1165: "0x55d398326f99059fF775485246999027B3197955: 0 wei + 77440 gas × 3300000000 wei"
    },
```

```
tx https://bscscan.com/tx/0x6daf669a01a1e9bd2cd99478ca42584fcfe12493a5d96657240595a52a05001a is too old - gas: 77440
```
this transaction is from 0x8c6Db404C9f25134103075030e8b776be1F6E868, with nonce 1165

**Comment by iGio90** [comment]
ok  cool and make sense. Thanks for explaination and sorry for your time loss on this <3
