### ISSUE TITLE
BSC lacks gas price and transaction fee limits

### ISSUE THREAD

**Issue by MockY-B** [bnb-chain/bsc#2720]
# Rationale

Users maybe mistakenly set high gas prices, leading to inflated transaction fees and potential financial losses

# Implementation
To enhance safety and usability, BSC should implement maximum gas price and transaction fee caps.
A BSC testnet transaction example shows a fee of 8.7436 BNB with a 200,000 Gwei gas price at: https://testnet.bscscan.com/tx/0xf914d1ab8ae607b1c8bad37ca48454caf7ebff4891c95c85f44ad6a8325df658.

**Comment by zzzckck** [comment]
but sometime, users are on purpose to send transaction with huge gasPrice, like an auction
