### ISSUE TITLE
bind.ContractTransactor/ethclient.SendTransactionConditional  use a internal struct

### ISSUE THREAD

**Issue by RelicOfTesla** [bnb-chain/bsc#2722]
https://github.com/bnb-chain/bsc/blob/ec318b9c9789eb91904b9c6fbc5e3a91c64e3d21/accounts/abi/bind/backend.go#L104
https://github.com/bnb-chain/bsc/blob/ec318b9c9789eb91904b9c6fbc5e3a91c64e3d21/accounts/abi/bind/backend.go#L27

https://github.com/bnb-chain/bsc/blob/ec318b9c9789eb91904b9c6fbc5e3a91c64e3d21/ethclient/ethclient.go#L740
https://github.com/bnb-chain/bsc/blob/ec318b9c9789eb91904b9c6fbc5e3a91c64e3d21/ethclient/ethclient.go#L32

Can not call SendTransactionConditional , or derive ethclient class.

I need to make some modifications to this interface, such as log or frequency limiting and other, I will derive new classes, and then pass in erc20.NewErc20(..., WrapEthClient{})  // var _ bind.ContractBackend = WrapEthClient{}

**Comment by 0xbundler** [comment]
Sorry, I cannot understand your issue, you can attach your compile error here.

It's suggested to wrap Go struct as a field and add more functions on it.

```go
type WrapEthClient struct {
    inner *ethclient.Client
}
func (ec *WrapEthClient) SendTransactionConditional(ctx context.Context, tx *types.Transaction, opts ethapi.TransactionOpts) error {
	// do some costume logics
	return ec.inner.SendTransactionConditional(ctx, tx, opts)
}
```

Another suggestion is to fork the BSC repo, and costume by yourself.

**Comment by RelicOfTesla** [comment]
```go
import "github.com/ethereum/go-ethereum/internal/ethapi"
var _ bind.ContractBackend = WrapEthClient{}
```

ethclient2\wrap.go:8:2: use of internal package github.com/ethereum/go-ethereum/internal/ethapi not allowed

Golang does not allow importing 'internal' packages in external modules

**Comment by 0xbundler** [comment]
Got it, may @galaio could fix it quickly, If you are in a hurry you can manually call `eth_sendRawTransactionConditional` using JSON-RPC.
