### ISSUE TITLE
ERROR[09-27|12:05:59.519] Error in block freeze operation          err="canonical hash missing, can't freeze block 120000"

### ISSUE THREAD

**Issue by yuanwj210** [bnb-chain/bsc#2725]
version:geth_1.4.15

ERROR[09-27|12:06:59.520] Error in block freeze operation          err="canonical hash missing, can't freeze block 120000"
WARN [09-27|12:07:00.790] Synchronisation failed, dropping peer    peer=24dfc44397a336880a8708e3df188bc4bc64e53ce92c04857e6ad6f4be661e03 name=Geth/v1.4.14-2199e88...           td=84,663,288 err="retrieved hash chain is invalid: no peers available or all tried for download"
WARN [09-27|12:07:14.996] Multiple headers for single request      peer=a5970d1a headers=0
WARN [09-27|12:07:14.996] Synchronisation failed, dropping peer    peer=a5970d1a327098aea2c88e3d5d3494176ffcce7358da48a422eb7270d31f42b2 name=Geth/v1.4.15/linux-a...           td=84,663,298 err="action from bad peer ignored: multiple headers (0) for single request"

**Comment by zzzckck** [comment]
could you provide more background? "block 120000" is quite an early block, did you sync from scratch?

**Comment by Ahmedalmmm** [comment]
هل يمكن أن نتواصل على الواتس اب +0204098191689
