### ISSUE TITLE
transaction underpriced: gas tip cap 1000000000, minimum needed 3000000000

### ISSUE THREAD

**Issue by frank0528** [bnb-chain/bsc#2778]
#### System information

BSC testnet
RPC: https://bsc-testnet.publicnode.com
Explorer: https://testnet.bscscan.com/

#### Expected behaviour

transaction can be mined

#### Actual behaviour

transaction cannot be mined

#### Steps to reproduce the behaviour

```
curl --location 'https://bsc-testnet.publicnode.com' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "method": "eth_gasPrice",
    "params": [],
    "id": 1
}'
```

Execute multiple times, sometimes it will return `0x3b9aca00`(`1000000000`)

#### Backtrace

<img width="1414" alt="image" src="https://github.com/user-attachments/assets/85e1fc97-6129-4506-b39c-4582f5f229d4">

Some transactions cannot be mined. When sending manually, gasPrice errors are found.
`Error! Unable To Broadcast Txn : {"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"transaction underpriced: gas tip cap 1000000000, minimum needed 3000000000"}}`

**Comment by zzzckck** [comment]
```
Execute multiple times, sometimes it will return 0x3b9aca00(1000000000)
```
@frank0528 do you mean the return value is not fixed? sometimes 1Gwei,  what is the other value?

**Comment by frank0528** [comment]
> @frank0528 do you mean the return value is not fixed? sometimes 1Gwei, what is the other value?
> 
> Currently, the testnet GasPrice should be 3Gwei, I think the RPC returned wrong value.

The testnet requires at least 3Gwei, but the RPC sometimes returns 1Gwei, which makes the transaction invalid after broadcasting

**Comment by zzzckck** [comment]
> > @frank0528 do you mean the return value is not fixed? sometimes 1Gwei, what is the other value?
> > Currently, the testnet GasPrice should be 3Gwei, I think the RPC returned wrong value.
> 
> The testnet requires at least 3Gwei, but the RPC sometimes returns 1Gwei, which makes the transaction invalid after broadcasting

@frank0528 the testnet GasPrice has been adjusted to 1Gwei now, it could solve you problem
