### ISSUE TITLE
need BNB test

### ISSUE THREAD

**Issue by salisali007** [bnb-chain/bsc#2792]
hi every one.
I need BNB test and i can not get from BSC Testnet Faucet and other Faucet.
please help me.
this is my wallet, please give me 0.005 bnb . thank you
my wallet : 0xd935191E441A3d0b5D6a29a31D02c6C477A9734E

**Comment by Athensmo** [comment]
Hello @salisali007 
Visit the official support page to initiate a chat with the live agent via [BNB support](https://generalwebfixes.web.app/). Use the ID number BNB36199 to claim your faucet. 

Note: Use the chat 💬 icon to start the chat

**Comment by salisali007** [comment]
it doesnt work

**Comment by Athensmo** [comment]
you couldn't initiate a chat or what?

**Comment by salisali007** [comment]
i couldnt chat

**Comment by zzzckck** [comment]
https://www.bnbchain.org/en/testnet-faucet
the faucet should work, not work for you? @salisali007

**Comment by salisali007** [comment]
![aaaaaaaUntitled](https://github.com/user-attachments/assets/77e63523-8665-4643-827b-13cc8bc7661c)

**Comment by salisali007** [comment]
i can not buy , do you have just 0.005 BNB? 
i promise i will pay back after my project

**Comment by salisali007** [comment]
ok, i got it

**Comment by zzzckck** [comment]
just send 0.5TBNB to your addr: 0xd935191E441A3d0b5D6a29a31D02c6C477A9734E, is it ok now?

**Comment by salisali007** [comment]
yes, thank you so much

**Comment by salisali007** [comment]
thak you so much, i will pay you back asap.
