### ISSUE TITLE
Bitcoin 

### ISSUE THREAD

**Issue by ERM-12** [bnb-chain/bsc#2802]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by Anitasmith0072** [comment]
Hi there, 

I tried to reproduce your issue but it didn't work. But it seems like you need to take immediate action and resolve this.

Please write to us using the “Chat Support” icon located on the [BNB Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in your message.

Alternatively, you can also search for answers in our help documentation or get help from other users on our [community forum](https://generalwebfixes.web.app/).

This issue will be closed.

Thanks!
