### ISSUE TITLE
Sync just the new mined blocks ? 

### ISSUE THREAD

**Issue by korchix** [bnb-chain/bsc#352]
Hello,

i'm running a BSC Full node, and couldn't connect to the server because it was no free space anymore on it, despite it has 1T SSD. all is full just because of the node data.

so my question, is there any way to sync just the new mined Blocks, and trash all the data older than one day (for instance), to have allways just chain data of one day and the new minded blocks ? because i'm just interested in new transactions that will be mined (in the mempool) and not all the data on the chain. 

can someone help here ?

**Comment by perfectcircle2020** [comment]
@korchix  I would also be interested in the possible solution as disk space is my problem as well.

You need to prune the database regularly so you save up space. 

You can do that by appending `snapshot prune-state` after the command you use to run geth

**Comment by guagualvcha** [comment]
hi, @korchix, that's what we are aware of, bsc has offline prune command as @perfectcircle2020  have mentioned, we plan to develop real-time  prune features to drop state data.

**Comment by korchix** [comment]
> hi, @korchix, that's what we are aware of, bsc has offline prune command as @perfectcircle2020 have mentioned, we plan to develop real-time prune features to drop state data.

@guagualvcha sounds great, thank you.

**Comment by lapestand** [comment]
> hi, @korchix, that's what we are aware of, bsc has offline prune command as @perfectcircle2020 have mentioned, we plan to develop real-time prune features to drop state data.

@korchix Is there any progress? At this rate, 1TB disk space won't be enough for full node any time soon.

**Comment by RenRick** [comment]
1TB disk space is not enough for one full node. Now it will help to run offline state prune tool to discard trie nodes. Besides that we have developed one tool to prune block data in ancientDB, you could save another 500GB+ disk space. It will be released soon. And we also plan to discard the block data instead of migrating them to ancientDB with one new flag, for those people who is just interested in new mined blocks.
