### ISSUE TITLE
Strange Bursts of CPU Usage

### ISSUE THREAD

**Issue by perfectcircle2020** [bnb-chain/bsc#354]
There is something strange I noticed lately by observing `htop` while running the node.

My hardware is I would say high end as it has 60 GB Ram and 10 Cores of CPU 1.8 T SSD, what I am noticing is that the CPU is not really used constantly;

What I want to say it that the CPU has rarely spikes when all 10 Cores are used 100%, most of the time only 2 or 3 cores are used. 

So I want to understand why is it so? I imagine the moment all 10 Cores are used at 100% for a moment is when a task has to be done quickly enough for the node to stay in sync with the network, but could this task have been started before, so no bursts of CPU power are needed to able to catch with the network?

Before having this machine I had a machine with the following specs:

30 GB of RAM 
8 Cores
800GB SSD

And when that happened the node had a really difficult time catching up with network.

Hope we can solve this issue

**Comment by brian-man** [comment]
With 16 cores and 32 GB of RAM and a dedicated PCIe4 NVMe, my node hasn't been able to sync for over a week now.  I've turned it off (given up) after several attempts at trying to make it happy again.

The CPU usage burst thing is not new -- it worked like this in July for me when my local node was sync'd reliably.  The CPUs and disk were and (before I gave up) are idle most of the time.

It really feels like their are some efficiency optimizations that need to be done to make the nodes support the recent load.


In contrast, I have a VM with 2 BCH, 1 BTC, and 1 LTC nodes that happily runs along with 8 GB of RAM and 4 vCPU with no drama at all.  I know it's not comparable but figured it might be worth mentioning.

**Comment by guagualvcha** [comment]
@perfectcircle2020 Because the blockchain has to execute the transaction serially, this is the limitation that it can not full use the multi CPU core all the time.

**Comment by brian-man** [comment]
> @perfectcircle2020 Because the blockchain has to execute the transaction serially, this is the limitation that it can not fully use the multi CPU core all the time.

If that's "always" rather than "sometimes", then that explains a lot.

**Comment by h3k1ru** [comment]
i9 9900k

**Comment by sonhn1988** [comment]
I am facing same issue. you can see as picture.
![Screenshot from 2021-08-18 23-19-53](https://user-images.githubusercontent.com/34534964/129935575-6ef95f67-3f31-4bb6-be78-72ab43ac30b5.png)

my CPU spike every 30 second and at this time, "mgpsc" slows down below 100 and elapsed increases from "milisecond" to second. 
This lead to sync low on my computer. 
Is there any way to set up cache clean or something like that to solve it?
My cpu:
10 C/20T, 96gb ram, cache set to 40000.
thanks

**Comment by bnb-tw** [comment]
closed due to inactivity.
