### ISSUE TITLE
Windows node setup / configuration documentation

### ISSUE THREAD

**Issue by brian-man** [bnb-chain/bsc#371]
Some recent commits by guagualvcha suggest that at least a handful of people are running BSC nodes on Windows, but I didn't have much luck finding setup/configuration documentation.

Is there such documentation?  If not, where/how should I contribute such documentation if I figure it out myself and want to share the learnings and tips?

**Comment by billyadelphia** [comment]
+1 ..
I need this also, currently struggle try to build it from source for Windows

**Comment by RumeelHussainbnb** [comment]
We are on it and soon we will publish it.
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain

**Comment by bytrislasis** [comment]
> Üzerinde çalışıyoruz ve yakında yayınlayacağız. [Lütfen https://discord.com/invite/binancesmartchain](https://discord.com/invite/binancesmartchain) adresindeki daha fazla tartışma için Discord kanalımıza katılmaya devam edin.[](https://discord.com/invite/binancesmartchain)

it shouldn't be this hard :)

**Comment by bytrislasis** [comment]
> We are on it and soon we will publish it. Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain


it shouldn't be this hard :)

**Comment by bnb-tw** [comment]
Windows is not really a supported platform to run the BSC node.
