### ISSUE TITLE
Recurrent crashes

### ISSUE THREAD

**Issue by joseddg92** [bnb-chain/bsc#388]
#### System information

Geth version: 
Geth
Version: 1.1.1
Git Commit: 03f7b318d9e19d0477bf3ffe6d6f85a681048dae
Git Commit Date: 20210813
Architecture: amd64
Go Version: go1.17
Operating System: linux
GOPATH=
GOROOT=go

OS & Version: Centos 8
Commit hash :  v1.1.1 (precompiled)

#### Expected behaviour
No Crash

#### Actual behaviour
2021/08/26 23:59:41 worker exits from a panic: runtime error: invalid memory address or nil pointer dereference
2021/08/26 23:59:41 worker exits from panic: goroutine 16259830 [running]:
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
        github.com/panjf2000/ants/v2@v2.4.5/worker.go:58 +0x10c
panic({0x1293c60, 0x23b09c0})
        runtime/panic.go:1038 +0x215
github.com/ethereum/go-ethereum/eth/filters.(*PublicFilterAPI).NewPendingTransactionFilter.func1()
        github.com/ethereum/go-ethereum/eth/filters/api.go:129 +0x13a
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
        github.com/panjf2000/ants/v2@v2.4.5/worker.go:70 +0x97
created by github.com/panjf2000/ants/v2.(*goWorker).run
        github.com/panjf2000/ants/v2@v2.4.5/worker.go:48 +0x68

#### Steps to reproduce the behaviour
Just running the node. A process is connected via IPC getting the latest transactions.

#### Backtrace

````
2021/08/26 23:59:41 worker exits from a panic: runtime error: invalid memory address or nil pointer dereference
2021/08/26 23:59:41 worker exits from panic: goroutine 16259830 [running]:
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
        github.com/panjf2000/ants/v2@v2.4.5/worker.go:58 +0x10c
panic({0x1293c60, 0x23b09c0})
        runtime/panic.go:1038 +0x215
github.com/ethereum/go-ethereum/eth/filters.(*PublicFilterAPI).NewPendingTransactionFilter.func1()
        github.com/ethereum/go-ethereum/eth/filters/api.go:129 +0x13a
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
        github.com/panjf2000/ants/v2@v2.4.5/worker.go:70 +0x97
created by github.com/panjf2000/ants/v2.(*goWorker).run
        github.com/panjf2000/ants/v2@v2.4.5/worker.go:48 +0x68
````

When submitting logs: please submit them as text and not screenshots.

**Comment by eyooooo** [comment]
My BSC-GETH node v1.1.2 also crashes for no reason

```
panic: runtime error: invalid memory address or nil pointer dereference                                                                                                                                
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xf624b5]                                                                                                                               
```

**Comment by guagualvcha** [comment]
hi, @joseddg92  this is an known issue, we will try to fix it ASAP.

**Comment by tino-web** [comment]
Same here:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xf624b5]

**Comment by gogopro-dev** [comment]
Here with NewPendingTransactionFilter
2021/10/03 11:05:10 worker exits from panic: goroutine 52226 [running]:
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1(0xc049174960)
   github.com/panjf2000/ants/v2@v2.4.5/worker.go:58 +0x177
panic(0x14e5900, 0x2591960)
   runtime/panic.go:969 +0x1b9
github.com/ethereum/go-ethereum/eth/filters.(*PublicFilterAPI).NewPendingTransactionFilter.func1()
   github.com/ethereum/go-ethereum/eth/filters/api.go:129 +0x205
github.com/panjf2000/ants/v2.(*goWorker).run.func1(0xc049174960)
   github.com/panjf2000/ants/v2@v2.4.5/worker.go:70 +0x94
created by github.com/panjf2000/ants/v2.(*goWorker).run
github.com/panjf2000/ants/v2@v2.4.5/worker.go:48 +0x4c
