### ISSUE TITLE
Out-Of-Memory

### ISSUE THREAD

**Issue by pepsi1k** [bnb-chain/bsc#419]
Hello everyone! I'm new to a deep understanding of blockchain node, but I need to deploy a bsc node.
The problem is that it fills up all the RAM and restarts every 8 hours. After 7 days, the node synchronize the latest block, but still looking at the graph we can say the node will soon fall

Can you help me figure out the problem, maybe I'm missing some configuration

![oom](https://user-images.githubusercontent.com/36175709/133055490-d86b7d16-8e39-4911-9b75-d8421cf1f2fe.jpg)

I use aws instance: c5.4xlarge
Disk: 2Tb, 6k IOPS, gp3, nvme 

run geth with this options: 
```
geth \
  --config config.toml \
  --datadir /data/geth \
  --port 30311 --cache 18000 \
  --syncmode full \
  --http --http.addr 0.0.0.0 --http.port 8545 \
  --http.vhosts=* --http.api personal,web3,eth \
  --ws --ws.addr 0.0.0.0 --ws.port 8546 \
  --ws.origins=* --ws.api personal,web3,eth \
  --allow-insecure-unlock \
  --txlookuplimit 0 \
  --nousb
```

config.toml:
```
[Eth]
NetworkId = 56
NoPruning = false
NoPrefetch = false
LightPeers = 100
UltraLightFraction = 75
DatabaseFreezer = ""
TrieTimeout = 2500000000000
TrieCleanCache = 256
TrieDirtyCache = 256
EnablePreimageRecording = false
EWASMInterpreter = ""
EVMInterpreter = ""


[Eth.TxPool]
Locals = []
NoLocals = false
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 512
GlobalSlots = 10000
AccountQueue = 256
GlobalQueue = 5000
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 1000

[Node]
HTTPHost = "0.0.0.0"
NoUSB = true
InsecureUnlockAllowed = false
IPCPath = "geth.ipc"
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 300
NoDiscovery = false
BootstrapNodes = ...
StaticNodes = ...
ListenAddr = ":30311"
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000
```

**Comment by perfectcircle2020** [comment]
You can try to sliglty decrease the` --cache` value and exepriment with that.

**Comment by 0fuz** [comment]
In some previous geth builds <1.1.2 I saw that im passing --cache 10000 but somewhy it uses 20000 MB ram
In geth 1.1.2 --cache working as expected. 10 000 = 10 000

**Comment by pepsi1k** [comment]
My node was restarted 1 time after synchronization, now it has been working stable for 6 days.
I will reduce the "-- cache " and give you report if it falls again

**Comment by guagualvcha** [comment]
Usually, the suggested setting is 1/3 of the size of system RAM

**Comment by pepsi1k** [comment]
![image](https://user-images.githubusercontent.com/36175709/144030480-f3baf774-ee7c-4d03-9a28-3a98d07c6d9a.png)

I'm already tired of this node and I want to forget it like a bad dream.

I have tried all the --cache configurations starting from [5000, 6000...20000]. My conclusion is no matter how much cache is allocated, it will still eat as much as it wants. 

**11/24 - 11/25** - For some reason geth-data was using 4T of disk space, I couldn't clear it with `snapshot prune`, issue #556. I decided to delete the current geth-data and download a snapshot.
**11/25** - After downloading a new snapshot, I was surprised how fast it syncs, but after ~4h you can see OOM again, after which the sync was no longer so fast
**11/26 - 11/29** - On this day I added --rpc.allow-unprotected-txs. You can see that node was no longer falling as usual, but it was very slow to synchronize and in 3 days it could not synchronize 30000 blocks
**11/29 - 11/30** - Update bsc 1.1.5 -> 1.1.6, add `--txpool.reannouncetime 5m` option. Blockchain still behind 30000 blocks

**Comment by KeefeL** [comment]
> ![image](https://user-images.githubusercontent.com/36175709/144030480-f3baf774-ee7c-4d03-9a28-3a98d07c6d9a.png)
> 
> I'm already tired of this node and I want to forget it like a bad dream.
> 
> I have tried all the --cache configurations starting from [5000, 6000...20000]. My conclusion is no matter how much cache is allocated, it will still eat as much as it wants.
> 
> **11/24 - 11/25** - For some reason geth-data was using 4T of disk space, I couldn't clear it with `snapshot prune`, issue #556. I decided to delete the current geth-data and download a snapshot. **11/25** - After downloading a new snapshot, I was surprised how fast it syncs, but after ~4h you can see OOM again, after which the sync was no longer so fast **11/26 - 11/29** - On this day I added --rpc.allow-unprotected-txs. You can see that node was no longer falling as usual, but it was very slow to synchronize and in 3 days it could not synchronize 30000 blocks **11/29 - 11/30** - Update bsc 1.1.5 -> 1.1.6, add `--txpool.reannouncetime 5m` option. Blockchain still behind 30000 blocks

Because there are 4T data in your disk, the storage performance will be degraded, you should do prune first, otherwise you can't catch up the new blocks anymore.

**Comment by pepsi1k** [comment]
@KeefeL Yes, I've already taken a snapshot of prune. Node was able to synchronize 30,000 blocks in a week, but it falls again due to OOM
![image](https://user-images.githubusercontent.com/36175709/146522206-17e1f32a-a3f4-4771-8661-e2ec429b8258.png)

Now my bsc node is **synced** but fails every 5-7 days

**Comment by RumeelHussainbnb** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days. 
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain

**Comment by pepsi1k** [comment]
@RumeelHussainbnb The question is still open. It is unclear why the node is falling due to OOM

**Comment by bnb-tw** [comment]
@pepsi1k is this still an issue for you?

**Comment by pepsi1k** [comment]
@bnb-tw yep, every two weeks it just goes down.
![image](https://github.com/bnb-chain/bsc/assets/36175709/fef49f4b-7f7a-4124-9a72-ef5625f4aa4c)

**Comment by kashirin-dm** [comment]
I'm encountering a similar problem!

**I launched my current node from a snapshot with the following settings:**
```
nohup ./geth --config ./config.toml --syncmode full --tries-verify-mode none --cache 20998 --metrics.addr 0.0.0.0 --metrics --rpc.allow-unprotected-txs --txlookuplimit 0 --maxpeers 6000 --nat extip:X.X.X.X --pipecommit --diffblock 5000 --rpc.evmtimeout 20s --datadir /data >> /data/bsc.log &
```

**Geth version:** v1.2.4.

**As of today, I have the following hardware:**
**CPU:** Xeon E5-2695v3 14c/28t 2.3-3.3GHz
**RAM:** 64GB DDR4 2133MHz
**SSD:** 2 x 1.2TB SSD RAID 0 (~500mb/s for 4k blocks)

I also made similar runs on hardware with different amounts of cores and memory (except for 128GB), as well as on different drives, including NVMe and different providers, AWS and Bare Metal.
**Used Geth versions:** v1.1.23, v1.1.21.

I also tried different cache settings, decreased and increased them and this did not affect memory consumption.
The different number of peers also did not generally set any memory limit, sooner or later it ran out.

![dash](https://github.com/bnb-chain/bsc/assets/40428935/d6bdb300-a14c-49e6-8a65-0dd81f10012f)


![ram](https://github.com/bnb-chain/bsc/assets/40428935/0d27e0cf-b559-4e71-9311-c277c95bf323)
