### ISSUE TITLE
最后几个块同步不上去

### ISSUE THREAD

**Issue by LyyDandelion** [bnb-chain/bsc#459]
同步：fullnode
配置： 8核 32G 1T SSD固态硬盘 带宽10M
问题：从10月14号开始同步，16号就只相差不到100块，到今天18号了，仍然没有追上去

使用的bsc版本是二进制v1.1.2版本。
![image](https://user-images.githubusercontent.com/33171640/137653212-7e4c3743-53a0-42ed-9414-a9e1a802f4e1.png)

**Comment by FAvE01** [comment]
Why

**Comment by tangbinyeer** [comment]
同步完成后停止了程序，修改配置的http.addr后再次启动，就一直跟不上进度了

**Comment by LyyDandelion** [comment]
通过快照同步可以成功！ 可能他们的节点不支持从头同步吧
