### ISSUE TITLE
Steps to sync geth node of bsc mainnet through snapshot

### ISSUE THREAD

**Issue by lokeshratnam09** [bnb-chain/bsc#524]
Please anybody give me proper steps to how to sync geth node through snapshot with commands and every thing.
because i failed to sync through genesis and fast sync command.
and don't have any idea how to sync through snapshot.
so please guide me. 
thanks for advance.

**Comment by cyberskycat** [comment]
this repo ,follow the guide
https://github.com/binance-chain/bsc-snapshots

**Comment by Marijus** [comment]
> this repo ,follow the guide https://github.com/binance-chain/bsc-snapshots

This references that before moving data the node should already be running. Should it be started with regular fast sync command? After data is copied into the datadir - should the node be started with sync or snap mode?

**Comment by cyberskycat** [comment]
> > this repo ,follow the guide https://github.com/binance-chain/bsc-snapshots
> 
> This references that before moving data the node should already be running. Should it be started with regular fast sync command? After data is copied into the datadir - should the node be started with sync or snap mode?

1.the node should not running before moving  data 
2.after perpare the data just start the geth client  with fast or snap mode
3. the snapshot data is just presyncing data,not the same meaing in the command line

**Comment by lokeshratnam09** [comment]
@cyberskycat  please give the proper instructions with command  how to sync geth node through sync mode.

**Comment by cyberskycat** [comment]
i run bsc node with this command ,you shouold prepare your snapshot data in datadir(for me it's chaindata)
`
./geth_linux --datadir chaindata/ --config ./config.toml --http --http.addr  127.0.0.1 --http.port 8545 --http.api  "eth,net,web3" --http.vhosts=* --txlookuplimit=0 --cache 10000   --diffsync --snapshot="true" --syncmode=snap
`

> @cyberskycat please give the proper instructions with command how to sync geth node through sync mode.

**Comment by berktaylan** [comment]
shall we generate genesis before run it ?

**Comment by Marijus** [comment]
> shall we generate genesis before run it ?

I was struggling with this question too.

What has worked for me is downloading the snapshot and starting node with snapshot data copied over into data dir without the genesis block

**Comment by lokeshratnam09** [comment]
@cyberskycat by using above command how many days to get synced geth node and which version of geth you will take it for  .??

**Comment by lokeshratnam09** [comment]
@cyberskycat after download the snapshot you use that above command..??

**Comment by cyberskycat** [comment]
> @cyberskycat after download the snapshot you use that above command..??

yes, about 1 day to sync full

**Comment by nilampatel-engineer** [comment]
> > shall we generate genesis before run it ?
> 
> I was struggling with this question too.
> 
> What has worked for me is downloading the snapshot and starting node with snapshot data copied over into data dir without the genesis block

so you mean you have not downloaded config and genesis file, not initialised the genesis.json etccc.?
only ran command to download and extract snapshot worked for you?

**Comment by RumeelHussainbnb** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days. 
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain
