### ISSUE TITLE
After the synchronization of my bsc node is completed, it will often appear to be behind by about 5 blocks

### ISSUE THREAD

**Issue by kissing009** [bnb-chain/bsc#642]
After the synchronization of my bsc node is completed, it will often appear to be behind by about 5 blocks, 
and then it can be synchronized again after 1 minute, and after a few minutes, it will appear to be behind by about 5 blocks. 
Transactions sent out are often delayed.

Running the command "eth.syncing" for the first time will output a result like "false".

After a few minutes, enter the command "eth.syncing" and the following result will be output
> eth.syncing
{
   currentBlock: 13287525,
   highestBlock: 13287528,
   knownStates: 624553666,
   pulledStates: 624553666,
   startingBlock: 13287525
}

**Comment by 790228724** [comment]
brother, what kind of configuration do you have, and the binance program running?

**Comment by kissing009** [comment]
> brother, what kind of configuration do you have, and the binance program running?

thanks for your reply. 

the node is running, but sometimes, the block of my node is lower than the latest block.

**Comment by overload-ak** [comment]
+1

**Comment by psdlt** [comment]
@kissing009 it depends on the hardware you use and quality of your peers. Most likely you need faster hardware.

**Comment by kissing009** [comment]
>

> @kissing009 it depends on the hardware you use and quality of your peers. Most likely you need faster hardware.

I do not think so, please check the picture.
<img width="852" alt="aaa" src="https://user-images.githubusercontent.com/95626561/145193559-825346e5-c163-485e-bb13-7d1b7c7b2417.png">

**Comment by jlinzhou** [comment]
+1

**Comment by psdlt** [comment]
@kissing009 cpu and ram is not as important as fast NVME drives.

**Comment by atrinitytv** [comment]
> > 
> 
> > @kissing009 it depends on the hardware you use and quality of your peers. Most likely you need faster hardware.
> 
> I do not think so, please check the picture. <img alt="ddddddd" width="873" src="https://user-images.githubusercontent.com/95626561/145193699-5dd11ced-ac0e-40b5-b528-192f58f44230.png">

What monitor is that?

**Comment by kissing009** [comment]
> @kissing009 cpu and ram is not as important as fast NVME drives.

yes, but I think my NVME is good.

![image](https://user-images.githubusercontent.com/95626561/145322802-7ec8a9cc-abe4-48a0-afab-a7879392fb6f.png)

![image](https://user-images.githubusercontent.com/95626561/145323012-4ae92513-683e-4239-9c5e-83615ead6409.png)

**Comment by kissing009** [comment]
> > > 
> > 
> > 
> > > @kissing009 it depends on the hardware you use and quality of your peers. Most likely you need faster hardware.
> > 
> > 
> > I do not think so, please check the picture. <img alt="ddddddd" width="873" src="https://user-images.githubusercontent.com/95626561/145193699-5dd11ced-ac0e-40b5-b528-192f58f44230.png">
> 
> What monitor is that?

it is the cpu utilization and memory utilization of my node.

**Comment by psdlt** [comment]
@kissing009 what data center / instance is this on? I still think this is your hardware issue.

**Comment by kissing009** [comment]
> @kissing009 what data center / instance is this on? I still think this is your hardware issue.

aliyun

thanks!

**Comment by ascunha** [comment]
> > @kissing009 what data center / instance is this on? I still think this is your hardware issue.
> 
> aliyun
> 
> thanks!

which region? 
and how about your peers?

**Comment by kissing009** [comment]
> > > @kissing009 what data center / instance is this on? I still think this is your hardware issue.
> > 
> > 
> > aliyun
> > thanks!
> 
> which region? and how about your peers?

china.
about 160 peers.
![image](https://user-images.githubusercontent.com/95626561/145492248-1c0097c9-18be-4d24-9514-79a9b0a2b7e2.png)

**Comment by ascunha** [comment]
> > > > @kissing009 what data center / instance is this on? I still think this is your hardware issue.
> > > 
> > > 
> > > aliyun
> > > thanks!
> > 
> > 
> > which region? and how about your peers?
> 
> china. about 160 peers. ![image](https://user-images.githubusercontent.com/95626561/145492248-1c0097c9-18be-4d24-9514-79a9b0a2b7e2.png)

So, I had similar issues (stop while doing nothing, not even waiting for IO) when (I guess) my peers were not so good... increasing peers often improved, but I'm not sure about that too. 
Running inside china I would also look if my p2p port is reachable all the time and if ali is not scanning it, since opening public ports in the mainland can be problematic... I would try HK if I had to run a node in china, but this is based on personal experience only in dealing with publicly accessible things in here, not a universal fact. 

When I had hardware problems, they would manifest differently, with an identifiable subsystem not keeping up to the rest.

**Comment by kissing009** [comment]
> > > > > @kissing009 what data center / instance is this on? I still think this is your hardware issue.
> > > > 
> > > > 
> > > > aliyun
> > > > thanks!
> > > 
> > > 
> > > which region? and how about your peers?
> > 
> > 
> > china. about 160 peers. ![image](https://user-images.githubusercontent.com/95626561/145492248-1c0097c9-18be-4d24-9514-79a9b0a2b7e2.png)
> 
> So, I had similar issues (stop while doing nothing, not even waiting for IO) when (I guess) my peers were not so good... increasing peers often improved, but I'm not sure about that too. Running inside china I would also look if my p2p port is reachable all the time and if ali is not scanning it, since opening public ports in the mainland can be problematic... I would try HK if I had to run a node in china, but this is based on personal experience only in dealing with publicly accessible things in here, not a universal fact.
> 
> When I had hardware problems, they would manifest differently, with an identifiable subsystem not keeping up to the rest.

thanks so much, brother.

**Comment by DreamLxq** [comment]
你成功了吗,兄弟....我在华为里都没有成功...

**Comment by kissing009** [comment]
> 你成功了吗,兄弟....我在华为里都没有成功...

没有，一直还是有这个同步差几个区块的问题。

**Comment by netmebtc** [comment]
Brother, I guess you have to consider using foreign servers. I also want to install a full node now. I'm hesitating whether to use VPS or dedicated server? I don't know if any brothers have successfully solved it with VPS?

**Comment by kissing009** [comment]
> Brother, I guess you have to consider using foreign servers. I also want to install a full node now. I'm hesitating whether to use VPS or dedicated server? I don't know if any brothers have successfully solved it with VPS?

thanks.

**Comment by DreamLxq** [comment]
> > 你成功了，兄弟……我在华为里都没有成功……
> 
> 没有，一直有这个同步几个几个的问题。
![image](https://user-images.githubusercontent.com/41785209/145848621-70538a18-b585-4a7d-a714-2bc4d63307b5.png)
老哥...我在我家里同步成功了,普通宽带.云服务器太垃圾了.我同步了两个节点来备用,你哪个应该是硬盘的问题!我这是两个盘组阵列的!

**Comment by DreamLxq** [comment]
这是另一个节点
![image](https://user-images.githubusercontent.com/41785209/145848858-51aa2e62-2bf4-4717-8fb0-94ffef9e72b5.png)

**Comment by kissing009** [comment]
> > > 你成功了，兄弟……我在华为里都没有成功……
> > 
> > 
> > 没有，一直有这个同步几个几个的问题。
> > ![image](https://user-images.githubusercontent.com/41785209/145848621-70538a18-b585-4a7d-a714-2bc4d63307b5.png)
> > 老哥...我在我家里同步成功了,普通宽带.云服务器太垃圾了.我同步了两个节点来备用,你哪个应该是硬盘的问题!我这是两个盘组阵列的!

兄弟，谢谢！我现在正在用硅谷的服务器试试看，我目前的阿里云服务器带宽应该不是瓶颈，硬盘我觉得也不应该是问题，硬盘速率明显还够用。同时我这里遇到的问题不是同步不完成，而是同步完成之后，间歇性出现差几个区块，然后又同步完成，然后又差几个区块，这种现象不断出现。  自己搭建的服务器的话，成本也不低吧？特别是带宽这块，是不是需要牵一根专线？

**Comment by DreamLxq** [comment]
> 

我这两个有一个是家庭宽带,一个是企业专线..都还挺不错.

**Comment by xiangjie256329** [comment]
我也遇到这个问题,我用过aws美国华盛顿和aws东京的,看来阿里云也不行,我感觉是硬盘的问题,用过自己的物理服务器这个问题看起来不明显,等同步完我再试试

**Comment by xiangjie256329** [comment]
下一步准备换ucloud美国的,你们要是解决了这个告诉下我哈,省得老是换节点,同步贼麻烦

**Comment by xiangjie256329** [comment]
和peer关系貌似没那么大,我同步的时候peer超过500反而会慢,后来发现官方的那个默认30还好用点,我设置成100,目前同步倒是追的比较大,就是不稳定,时不时差几个块,这个差的块还不是syncing,它总显示false,而实际上是遍历官方的13个节点,发现没最新区块和官方的一比较经常差的比较多

**Comment by xiangjie256329** [comment]
我觉得如果节点和验证者(产块)节点近,则有可能效果会更好一点,但是就是不知道验证者在哪,我觉得aws_美国_弗吉尼亚的概率很大,但是aws 3000u/月的机器实在不咋地

**Comment by DreamLxq** [comment]
> 

没有那一说.我直接四川电信同步得很好.

**Comment by DreamLxq** [comment]
这几天BSC的夹子都在闹....验证者给夹子开特权.

**Comment by xiangjie256329** [comment]
你确定?你有写程序去看吗,手动显示false一点用都没有

**Comment by xiangjie256329** [comment]
你跑全节点是干啥用的呢?

**Comment by kissing009** [comment]
> 和peer关系貌似没那么大,我同步的时候peer超过500反而会慢,后来发现官方的那个默认30还好用点,我设置成100,目前同步倒是追的比较大,就是不稳定,时不时差几个块,这个差的块还不是syncing,它总显示false,而实际上是遍历官方的13个节点,发现没最新区块和官方的一比较经常差的比较多

哥们，看来你的经验相当丰富啊，我这两天搞了一个硅谷的节点，还是出现一样的问题。看来这是一个比较普遍的问题，基本上没法解决了。ETH节点不会出现这个问题，估计是bsc出块时间太短了。

如下是我1秒钟抓取一次，抓到的同步状态。还是时不时出现同步没完成的情况。

![image](https://user-images.githubusercontent.com/95626561/146180509-ede6ae32-394f-4204-9beb-e5524dbd28bc.png)

**Comment by xiangjie256329** [comment]
嗯,我这边研究的是节点有70%是美国aws的,其中有40%是aws_美国_弗吉尼亚的,选东京是因为官方结点查的是东京aws,后面想了下,其实要看验证者节点在哪会比较好,感觉弗吉尼亚的概率挺大的,但是这种云主机硬盘的延时就是高导致同步老是不及时,独享的太贵了,不知道有没有啥折中的方案,国内的同步重启容易出现追不上

**Comment by kissing009** [comment]
> 嗯,我这边研究的是节点有70%是美国aws的,其中有40%是aws_美国_弗吉尼亚的,选东京是因为官方结点查的是东京aws,后面想了下,其实要看验证者节点在哪会比较好,感觉弗吉尼亚的概率挺大的,但是这种云主机硬盘的延时就是高导致同步老是不及时,独享的太贵了,不知道有没有啥折中的方案,国内的同步重启容易出现追不上

你们一直说的硬盘导致延迟，确实是官方也说了硬盘是瓶颈，但是我用的阿里云的云盘，我看了远远没有达到峰值啊，不知道为什么还是出现这个问题。

下图是我云盘的IOPS，性能是5万
![image](https://user-images.githubusercontent.com/95626561/146182609-459934ed-e696-4db5-ad1e-7d0572d100fd.png)

这个图是我目前硬盘的IOPS情况

![image](https://user-images.githubusercontent.com/95626561/146182686-a5577f66-5d1b-4156-a8f3-92900a8cd8bd.png)

感觉完全没问题的样子。

**Comment by mentalrob** [comment]
I'm experiencing the same issue, is there any workaround or fix for this ?

**Comment by ascunha** [comment]
> > 嗯,我这边研究的是节点有70%是美国aws的,其中有40%是aws_美国_弗吉尼亚的,选东京是因为官方结点查的是东京aws,后面想了下,其实要看验证者节点在哪会比较好,感觉弗吉尼亚的概率挺大的,但是这种云主机硬盘的延时就是高导致同步老是不及时,独享的太贵了,不知道有没有啥折中的方案,国内的同步重启容易出现追不上
> 
> 你们一直说的硬盘导致延迟，确实是官方也说了硬盘是瓶颈，但是我用的阿里云的云盘，我看了远远没有达到峰值啊，不知道为什么还是出现这个问题。
> 
> 下图是我云盘的IOPS，性能是5万 ![image](https://user-images.githubusercontent.com/95626561/146182609-459934ed-e696-4db5-ad1e-7d0572d100fd.png)
> 
> 这个图是我目前硬盘的IOPS情况
> 
> ![image](https://user-images.githubusercontent.com/95626561/146182686-a5577f66-5d1b-4156-a8f3-92900a8cd8bd.png)
> 
> 感觉完全没问题的样子。

aya... it's always the same "your disk not good" thing... 
maybe after 1 month they will say you need the tianhe-2 to run a bsc node...
Maybe after they release their port of erigon things will be better.

**Comment by funsplay** [comment]
兄弟，你的节点同步成功了吗
