### ISSUE TITLE
Ethereum peer removal failed    peer=-------- err="peer not registered"

### ISSUE THREAD

**Issue by nilampatel-engineer** [bnb-chain/bsc#670]
bsc node has downloaded snapshot and now syncing from chain after a while suddenly started showing above error, can some one help pls

**Comment by Undead8** [comment]
I don't know what the error mean, but it's normal. It shows up all the time and it doesn't mean anything is wrong.

**Comment by nilampatel-engineer** [comment]
but the syncing has stopped from last few hours...

**Comment by Undead8** [comment]
Probably not related to that error.

**Comment by RumeelHussainbnb** [comment]
Can you please share the logs and please check its simillar to your issue it might be solve your problem https://github.com/ethereum/go-ethereum/issues/22077
if not please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain

**Comment by tculig** [comment]
I'm having the same issue where it says "Ethereum peer removal failed" and the sync just stops dead.

**Comment by forcodedancing** [comment]
@nilampatel-engineer @tculig  We think this could be a potential bug, and we will look into it. Are your nodes recovered? If not, please let us know if we can help. Thanks.

**Comment by forcodedancing** [comment]
Linked to #220

**Comment by tculig** [comment]
My node recovered, thank you @forcodedancing.

**Comment by nilampatel-engineer** [comment]
> My node recovered, thank you @forcodedancing. Took about 20 restarts, but in the end it managed to pull the entire history. Still importing block entries though, can't get it to fully sync. But that's a topic for another thread..

how did you resolved?

**Comment by tculig** [comment]
> > My node recovered, thank you @forcodedancing. Took about 20 restarts, but in the end it managed to pull the entire history. Still importing block entries though, can't get it to fully sync. But that's a topic for another thread..
> 
> how did you resolved?

Just kept restarting the node whenever it crashed :/

**Comment by nilampatel-engineer** [comment]
I have snapshot downloaded and it is crashing on whem chain start syncing and giving me this error about peer removal failed

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by namlt3820** [comment]
Same problem here. I got it after pruning the snapshot. Now I have to manually check and restart the node everyday. My other node without any pruning is running just fine.

**Comment by zarakiftw** [comment]
@forcodedancing  Any update on this? My node keeps dropping blocks because of the above issue

**Comment by White-Rabbit-7** [comment]
I am having this exact same issue constantly.

 _ERROR[03-09|03:52:05.913] Ethereum peer removal failed             peer=7946a12b err="peer not registered"_

**Comment by KyloYang888** [comment]
I am having this exact same issue constantly.

```
t=2022-03-10T03:38:59+0000 lvl=warn msg="Synchronisation failed, dropping peer" peer=570daaa966a5a500cbe0c41d985a49550e5e65fab99fa57eccea30989a1cff02 err=timeout
t=2022-03-10T03:38:59+0000 lvl=eror msg="Ethereum peer removal failed"          peer=570daaa9 err="peer not registered"
```

**Comment by lpf763827726** [comment]
same issue
```
t=2022-03-30T04:06:33+0000 lvl=info msg="Downloader queue stats"                 receiptTasks=0 blockTasks=380 itemSize="4.45 KiB" throttle=8192
t=2022-03-30T04:06:38+0000 lvl=eror msg="Snapshot extension registration failed" peer=51071016 err="peer connected on snap without compatible eth support"
```

**Comment by taweesakpintakam** [comment]
เมื่อ 30 มี.ค. 2022 11:07 "DouCrazy" ***@***.***> เขียนว่า

**Comment by Jolly23** [comment]
#856 fixed

**Comment by IronSight87** [comment]
How can I fix this problem while waiting for new release?

**Comment by Jolly23** [comment]
> How can I fix this problem while waiting for new release?
> 
> btw: Problem occurred after calling geth snapshot prune-block

Actually it’s not a big problem. It occurs because the removePeer was called twice. It doesn’t matter with snapSync. The problem you mentioned here is about the quality of peers you connected. They haven’t provide sync data so the sync manager  removes it.

**Comment by IronSight87** [comment]
> > How can I fix this problem while waiting for new release?
> > btw: Problem occurred after calling geth snapshot prune-block
> 
> Actually it’s not a big problem. It occurs because the removePeer was called twice. It doesn’t matter with snapSync. The problem you mentioned here is about the quality of peers you connected. They haven’t provide sync data so the sync manager removes it.

Cheers for your reply.
in this case geth snapshot prune-block must have caused another issue.
The node is not running and my logs are full of

```
t=2022-04-23T14:52:35+0200 lvl=eror msg="Ethereum peer removal failed"           peer=62a7164c err="peer not registered"
t=2022-04-23T14:52:36+0200 lvl=info msg="Initializing state bloom"               items=804,513,358 errorrate=0.000 elapsed=18m56.507s
t=2022-04-23T14:52:44+0200 lvl=info msg="Initializing state bloom"               items=820,252,893 errorrate=0.000 elapsed=19m4.507s
t=2022-04-23T14:52:52+0200 lvl=info msg="Initializing state bloom"               items=836,066,859 errorrate=0.000 elapsed=19m12.507s
t=2022-04-23T14:52:54+0200 lvl=eror msg="Snapshot extension registration failed" peer=d35b2e1a err="peer connected on snap without compatible eth support"
t=2022-04-23T14:53:00+0200 lvl=info msg="Initializing state bloom"               items=852,059,160 errorrate=0.000 elapsed=19m20.507s
t=2022-04-23T14:53:03+0200 lvl=eror msg="Snapshot extension registration failed" peer=a01a2abb err="peer connected on snap without compatible eth support"
t=2022-04-23T14:53:08+0200 lvl=info msg="Initializing state bloom"               items=868,036,330 errorrate=0.000 elapsed=19m28.507s
```

Any idea?
