### ISSUE TITLE
Generating state snapshot takes forever

### ISSUE THREAD

**Issue by ai323** [bnb-chain/bsc#749]
Hey, I was trying to get my full node up and running. Now I'm stuck at the state generation step and it seems takes forever. Here is a screenshot of my bsc.log file:

`t=2022-02-02T14:45:35+0100 lvl=info msg="Generating state snapshot"              root=0x82273676d2e6d80953dc3aa7d0ab08993d7b7c32e6bee78dd29861a79f6ead1f at=0x07ad0f07a13c0504ce0ebfe49b2179ae49f954ba7082790595a1b9e811881a5b accounts=4,253,034 slots=15,128,329 storage="1.37 GiB"    elapsed=38h54m57.064s eta=1258h57m12.165s
t=2022-02-02T14:45:36+0100 lvl=eror msg="Snapshot extension registration failed" peer=caf6d7f1 err="peer connected on snap without compatible eth support"
t=2022-02-02T14:45:43+0100 lvl=info msg="Generating state snapshot"              root=0x82273676d2e6d80953dc3aa7d0ab08993d7b7c32e6bee78dd29861a79f6ead1f at=0x07adb35c49288a862e610bdbbc7e3e153c5e3887c09cc286a4c000d686eecfd5 accounts=4,254,471 slots=15,128,714 storage="1.37 GiB"    elapsed=38h55m5.075s  eta=1258h36m5.449s
t=2022-02-02T14:45:52+0100 lvl=info msg="Generating state snapshot"              root=0x82273676d2e6d80953dc3aa7d0ab08993d7b7c32e6bee78dd29861a79f6ead1f at=0x07ae5aabfaa12a9899aa20732203b73c7038099c484f7e37e422d5e5bc23e165 accounts=4,255,880 slots=15,129,076 storage="1.37 GiB"    elapsed=38h55m13.081s eta=1258h14m31.742s
t=2022-02-02T14:46:00+0100 lvl=info msg="Generating state snapshot"              root=0x82273676d2e6d80953dc3aa7d0ab08993d7b7c32e6bee78dd29861a79f6ead1f at=0x07aeebb256403f87009e968ba47da18504cbe1cf30e38ea6c93537f86b1e70de accounts=4,257,134 slots=15,129,594 storage="1.37 GiB"    elapsed=38h55m21.086s eta=1257h56m25.487s
t=2022-02-02T14:46:08+0100 lvl=info msg="Generating state snapshot"              root=0x82273676d2e6d80953dc3aa7d0ab08993d7b7c32e6bee78dd29861a79f6ead1f at=0x07af8821e87a5fb314bd4692bdee9e75902dfbc4de1dfa7e26228540d77178c0 accounts=4,258,407 slots=15,129,849 storage="1.37 GiB"    elapsed=38h55m29.108s eta=1257h36m34.657s
t=2022-02-02T14:46:12+0100 lvl=eror msg="Snapshot extension registration failed" peer=26167de9 err="peer connected on snap without compatible eth support"
t=2022-02-02T14:46:16+0100 lvl=info msg="Generating state snapshot"              root=0x82273676d2e6d80953dc3aa7d0ab08993d7b7c32e6bee78dd29861a79f6ead1f at=0x07b02370bf329d7fd6b90f1684bdf51a06bcbfda21ea5453f5979fa2abf60b43 accounts=4,259,699 slots=15,130,159 storage="1.37 GiB"    elapsed=38h55m37.141s eta=1257h16m55.364s
t=2022-02-02T14:46:24+0100 lvl=info msg="Generating state snapshot"              root=0x82273676d2e6d80953dc3aa7d0ab08993d7b7c32e6bee78dd29861a79f6ead1f in=0x07b062e5d38e25b78408cf53632230dc4cda1d4ad1195ec7324c67f188d69219 at=0x07f62712fec791b7d70127e5aadbbad9912c057b72cc93d5e7126905ba2a212f accounts=4,260,203 slots=15,131,141 storage="1.37 GiB"    elapsed=38h55m45.160s eta=1257h11m26.695s
t=2022-02-02T14:46:25+0100 lvl=eror msg="Snapshot extension registration failed" peer=08a3fb33 err="peer connected on snap without compatible eth support"
t=2022-02-02T14:46:32+0100 lvl=info msg="Generating state snapshot"              root=0x82273676d2e6d80953dc3aa7d0ab08993d7b7c32e6bee78dd29861a79f6ead1f in=0x07b062e5d38e25b78408cf53632230dc4cda1d4ad1195ec7324c67f188d69219 at=0xf05e34439f13775c4c39c272a9bbfa986911c5f8f297104ceb67859621050248 accounts=4,260,203 slots=15,132,681 storage="1.37 GiB"    elapsed=38h55m53.173s eta=1257h15m45.469s
t=2022-02-02T14:46:40+0100 lvl=info msg="Generating state snapshot"              root=0x82273676d2e6d80953dc3aa7d0ab08993d7b7c32e6bee78dd29861a79f6ead1f at=0x07b0f2d1e3618370e5ceb9401fb0dac765b9523f920afb7ece08866e0b25abc9 accounts=4,261,418 slots=15,133,045 storage="1.37 GiB"    elapsed=38h56m1.180s  eta=1256h57m51.6s
t=2022-02-02T14:46:40+0100 lvl=eror msg="Snapshot extension registration failed" peer=d7bc93fb err="peer connected on snap without compatible eth support"
t=2022-02-02T14:46:43+0100 lvl=eror msg="Snapshot extension registration failed" peer=9199cc6c err="peer connected on snap without compatible eth support"
t=2022-02-02T14:46:48+0100 lvl=info msg="Generating state snapshot"              root=0x82273676d2e6d80953dc3aa7d0ab08993d7b7c32e6bee78dd29861a79f6ead1f in=0x07b12e78abb89e627a88c567d5b19730efd936c31c399d928c5d7a32a6de80f9 at=0x6b4f9ffd6cce4dcd621095d8d6932efca6a3f7960f542cf90a5bfe005b7bb46f accounts=4,261,957 slots=15,134,021 storage="1.37 GiB"    elapsed=38h56m9.184s  eta=1256h52m57.937s`

**Comment by RumeelHussainbnb** [comment]
Its normal behaviour and randomly happen when you connect to some peer that not compatible with your geth vesion.
If its stuck on this for a long. maybe restart geth or check your firewall. Which version you are using please try with upgraded version https://github.com/binance-chain/bsc/releases/tag/v1.1.8.

Please proceed to join our Discord channel for more discussion at https://discord.com/invite/buildnbuild

**Comment by ai323** [comment]
> Its normal behaviour and randomly happen when you connect to some peer that not compatible with your geth vesion. If its stuck on this for a long. maybe restart geth or check your firewall. Which version you are using please try with upgraded version https://github.com/binance-chain/bsc/releases/tag/v1.1.8.
> 
> Please proceed to join our Discord channel for more discussion at https://discord.com/invite/buildnbuild

Hey, thanks for the reply. I'm using the latest geth.

**Comment by ai323** [comment]
> Its normal behaviour and randomly happen when you connect to some peer that not compatible with your geth vesion. If its stuck on this for a long. maybe restart geth or check your firewall. Which version you are using please try with upgraded version https://github.com/binance-chain/bsc/releases/tag/v1.1.8.
> 
> Please proceed to join our Discord channel for more discussion at https://discord.com/invite/buildnbuild

Look

**Comment by KeefeL** [comment]
> 

Hi, Have your problem solved now? @ai323

**Comment by KeefeL** [comment]
Since there is no further information, I'm going to close this issue.
