### ISSUE TITLE
No attribute "status" in eth_getTransactionReceipt but "root"

### ISSUE THREAD

**Issue by vsmelov** [bnb-chain/bsc#753]
I have run my own BSC-like private network.
When I call eth_getTransactionReceipt
I receive in the response "root" attribute instead of "status", it looks like the node works in pre-Byzantium mode
according to https://www.quicknode.com/docs/ethereum/eth_getTransactionReceipt

My problem is that I cannot work with the node using the eth-brownie framework (for python), it parses the receipt using the status attribute.

How can I force the node to return the "status" attribute?

**Comment by vsmelov** [comment]
@KeefeL how can I force my node to work in Byzantium mode?

**Comment by KeefeL** [comment]
I'm sorry, I have no idea about Byzantium mode, after I go through the code, I found once the transaction successful, it's root won't be nil, so it always returns `root` attribute not `status` attribute.

<img width="689" alt="image" src="https://user-images.githubusercontent.com/90749943/153121529-aaa0a19c-6ae2-4242-881c-9a32dd781232.png">

<img width="901" alt="image" src="https://user-images.githubusercontent.com/90749943/153121576-cbb9f509-c780-4ba4-9d41-1ceaba752a40.png">

**Comment by vsmelov** [comment]
@KeefeL it's quite strange because as far as I understood the node should return status field for successful and failed transactions.
This is the way how bsc node and bsc-test node works if you send them a request. They always return status

**Comment by KeefeL** [comment]
> @KeefeL it's quite strange because as far as I understood the node should return status field for successful and failed transactions. This is the way how bsc node and bsc-test node works if you send them a request. They always return status

I think `always` maybe not true, it depends on the API you call.
