### ISSUE TITLE
Will the official BSC team consider maintaining BSC Erigon?

### ISSUE THREAD

**Issue by netquery** [bnb-chain/bsc#754]
Whether the official BSC team will consider maintaining BSC Erigon.  Using Go-Ethereum to sync BSC Archive nodes requires about 25+ TB, but Erigon only needs 4.5 TB.

**Comment by masayil** [comment]
+1 . BSC Erigon Long time no update.  still stay 2021.11.3-alpha

**Comment by KeefeL** [comment]
You can refer to the official Erigon, Erigon now can support bsc network, and the later PR will be directly submitted to the official repo, so the BSC Erigon repo won't be maintained temporarily.

**Comment by masayil** [comment]
`https://github.com/ledgerwatch/erigon`
This can run an bsc nodes now?

**Comment by masayil** [comment]
> You can refer to the official Erigon, Erigon now can support bsc network, and the later PR will be directly submitted to the official repo, so the BSC Erigon repo won't be maintained temporarily.

https://github.com/ledgerwatch/erigon
This can run an bsc nodes now?
