### ISSUE TITLE
GET  fatal error: concurrent map iteration and map write   when pipecommit enabled

### ISSUE THREAD

**Issue by masayil** [bnb-chain/bsc#757]
![image](https://user-images.githubusercontent.com/65291464/153204893-4f2bafb9-f1c2-4bcf-9d1f-f03bf1069053.png)
What cause it ?

**Comment by guagualvcha** [comment]
hi, can you do `geth version`, and paste the info here?

**Comment by masayil** [comment]
command: `geth_linux --config /root/bsc-arch/config.toml --datadir /root/bsc-arch/node --allow-insecure-unlock  --cache 64000 --rpc.allow-unprotected-txs --txlookuplimit 0 --verbosity 3 --gcmode archive --syncmode full --pipecommit --txpool.reannouncetime 5m --snapshot=true`

geth version:
Geth
Version: 1.1.8
Git Commit: 859186f299fa94fada3e92608db1392be1a45599
Architecture: amd64
Go Version: go1.16.13
Operating System: linux
GOPATH=
GOROOT=go

**Comment by masayil** [comment]
`--pipecommit`  enabled

**Comment by masayil** [comment]
> hi, can you do `geth version`, and paste the info here?

--pipecommit enabled

**Comment by masayil** [comment]
> hi, can you do `geth version`, and paste the info here?

geth version:
Geth
Version: 1.1.8
Git Commit: https://github.com/binance-chain/bsc/commit/859186f299fa94fada3e92608db1392be1a45599
Architecture: amd64
Go Version: go1.16.13
Operating System: linux
GOPATH=
GOROOT=go

**Comment by masayil** [comment]
Pipecommit is still an experimental feature. Maybe I should remove `--pipecommit `  and add `--diffsync` to accelerate .  The  pipe commit won't work in diffsync mode.

**Comment by guagualvcha** [comment]
It will be fixed in this PR.

**Comment by masayil** [comment]
> It will be fixed in this PR: #797

thanks
