### ISSUE TITLE
--cache problem

### ISSUE THREAD

**Issue by kugimiya530** [bnb-chain/bsc#758]
Hi i'd like to know what  --cache size difference

i saw  bsc fullnode doc show  --cache 8000

but there is some guide from other people  --cache 18000 or higher

if i synchronize already
and I want node update to highest block ASAP  future should i  modify this vaule higher or lower

**Comment by nilampatel-engineer** [comment]
--cache value should be half of the RAM.

**Comment by Zaczero** [comment]
@nilampatel-engineer How do you know that?

Personally, I set it to the highest amount I am willing to give away to my full node. 8GB-32GB value range seems reasonable to me.

**Comment by ko0f** [comment]
According to geth command line help, `--cache   Megabytes of memory allocated to internal caching`. That includes database, trie, gc and snapshot caches. 

But even with `--cache=10000` it uses 20GB of memory. Either they've added cache that's not included, or they ignore this arg.

**Comment by dgdeivid** [comment]
I put --cache=40000  on a 128GB server and the node takes up all the memory until it crashes.

**Comment by Zaczero** [comment]
While I can see a higher than `--cache` requested RAM usage _(probably some additional non-cache-related stuff)_ on both ETH and BSC nodes, it's been pretty stable. Never had any OOM issues. And I suppose that's how GETH clients tend to be.

![image](https://user-images.githubusercontent.com/10835147/155271444-279b7b11-c973-41e6-8035-2dd84e96766b.png)
_[RES] column is the actual physical memory being used._

**Comment by KeefeL** [comment]
> Hi i'd like to know what --cache size difference
> 
> i saw bsc fullnode doc show --cache 8000
> 
> but there is some guide from other people --cache 18000 or higher
> 
> if i synchronize already and I want node update to highest block ASAP future should i modify this vaule higher or lower

If you have larger memory, you can specify a larger --cache number, it is fine, I will recommend you to specify the number no larger than half of your total memory.

The --cache isn't all the memory that the BSC process uses, it just means the trie cache, so you can see a larger memory use of your process than the --cache value you specify.
