### ISSUE TITLE
Ringit

### ISSUE THREAD

**Issue by Crypdiy** [bnb-chain/bsc#760]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by Loverush** [comment]
Please describe your issue in detail

**Comment by KeefeL** [comment]
It seems a useless issue, i'm going to close this.
