### ISSUE TITLE
"Not allowed to propose block" err="unauthorized validator"

### ISSUE THREAD

**Issue by HungChu** [bnb-chain/bsc#761]
I built my local bsc network with 3 nodes. After that I run 4th node:
./build/bin/geth --identity "node4" --datadir node4 --networkid 332211 --allow-insecure-unlock --nat extip:0.0.0.0 --port 30306 --http --rpcaddr "0.0.0.0" --rpcport 9548 --rpcapi="personal,debug,eth,net,web3,txpool,parlia" --rpccorsdomain "" --rpcvhosts "" --syncmode 'full' --mine --miner.threads=1 --miner.etherbase="0x" --unlock 0x --password password.txt
then i got exactly this error: "Not allowed to propose block" err="unauthorized validator"
Please give me an advice to fix it

**Comment by Zaczero** [comment]
Duplicate: https://github.com/binance-chain/bsc/issues/718
