### ISSUE TITLE
BSC archive node sync slowed down.

### ISSUE THREAD

**Issue by vshybalov** [bnb-chain/bsc#766]
I am trying to run BSC archive node, I started sync from genesis block, at start sync speed was good, and node was constantly decreasing number of blocks left to be fully synced.

However, more it syncs, slower it gets. Right now I am at the point, when my node is syncing slower than new blocks appear in the network, which means it will never sync.

At this moment node synced 9773530 blocks.

From what i see the logs, it is constantly compacting database,

`t=2022-02-08T15:03:15+0100 lvl=warn msg="Database compacting, degraded performance" database=/srv/bsc/data/geth/chaindata`

This is continues process, it syncs, than it compacts, then it syncs again. So the recent speed of sync were around 2000 blocks per day, which is super slow. And now it is even slower than new blocks appear, so it will not catchup.

On the server I use nvme disks for 4TB each in the LVM setup with the ext4 filesystem.

Processor is AMD EPYC 7502P 32-Core Processor

So at this point I do not know why it syncs so slow, and does anyone has the same issues. The current db size is 9.3T.

I will be grateful to anyone who can assist me to figure out whats going wrong, and how can I get BSC archive node to be fully synced.

I tried to search info in the google, asked for assistance at public chats and https://ethereum.stackexchange.com/, no luck =(

**Comment by masayil** [comment]
sync archive nodes from the genesis block and then complete the sync. I think it is impossible now.

**Comment by KeefeL** [comment]
Maintaining an archive node is quite challenging, because it need quite large storage, while the disk usage grow, the performance decrease, so in general, if you run an archive nodes, you should segment your data, use several nodes to deal with different height blocks.

Considering its complexity, I recommend you to use archive service provided by binance official or some other providers.

**Comment by masayil** [comment]
https://github.com/ledgerwatch/erigon
You can try to use this client.
BUT bsc chain still work in progress and bsc support is in "devel" branch only for now

**Comment by vshybalov** [comment]
> Maintaining an archive node is quite challenging, because it needs quite large storage, while the disk usage grows, the performance decreases, so in general, if you run an archive nodes, you should segment your data, use several nodes to deal with different height blocks.
> 
> Considering its complexity, I recommend you to use archive service provided by binance official or some other providers.

Is it possible to segment data ? I thought bsc will check for db integrity, and will start sync from scratch if any info missing. 

I really want to support bsc archive node. 

Could you please give more info so I will move in right direction. How can I make bsc to work with different db parts in different places ? 

Do you mean something like nfs solution  ?

**Comment by KeefeL** [comment]
I mean segment data is to part different height blocks to different nodes, for example you can archive 1-10000 blocks to the first node, and 10001-20000 to second node, etc. When you access you archive service, you can route to the right node according to the block height.

Try erigon that @masayil  mentioned might be a good choice.

**Comment by blissend** [comment]
You can compile the binary with the compaction level0 turned down/off in ethdb/leveldb/leveldb.go under the new constructor. However from what I'm seeing, isn't the solution. Data size is massive and still doesn't sync fast enough even on specs far beyond what it needs.
