### ISSUE TITLE
fullnode currentblock not equal highestblock

### ISSUE THREAD

**Issue by razorJhon** [bnb-chain/bsc#767]
i installed a binance full node on a 32GB ram , 4TB nvme hard drive , 1GB connection unlimited but the problem that the node currentblock is missing about 100 blocks from the highestblock , it keeps syncing for 2 days now and it is still the same , the node was working perfectly until i rebooted the server now the node keep syncing and its not working also is that normal that the current block is lower 100 blocks from the highest block ?

**Comment by Zaczero** [comment]
What I usually do (and recommend to others) is reset the node and use the official BSC snapshot for the initial sync https://github.com/binance-chain/bsc-snapshots (source: https://github.com/binance-chain/bsc/issues/502).
