### ISSUE TITLE
What are all the things that a delegator and validator can vote for in Binance smart chain?

### ISSUE THREAD

**Issue by Codegigi** [bnb-chain/bsc#771]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

**Comment by KeefeL** [comment]
Delegators and validators can use cli cmd in https://github.com/bnb-chain/node-binary/tree/master/cli/prod to submit proposal and vote, all the exported system parameters can be governed through this cli cmd, maybe not easy to use for users temporarily.

![image](https://user-images.githubusercontent.com/90749943/154439789-51aa763e-ed30-4635-b31b-efe582d00770.png)

**Comment by Codegigi** [comment]
But I'm still confused about the way that binance consensus and voting is used by delegators. Can delegator's voting power be changed after election? Do they even have anything to vote for in the first place?

**Comment by KeefeL** [comment]
Sorry for making you confused.

Can delegator's voting power be changed after election?
For this question, I think if you delegate your BNB to validators, your voting power will be moved from you to the validator you delegate to, once you withdraw them, you get back your voting power. 

For the consensus part, delegators staking BNB to validators, the validators get more votes have more possibility to be elected as active validators, so they can produce block and then get BNB rewards, some of the rewards will distributed to delegators. Vote for existing validators is just want to get the BNB rewards from producing new blocks, it is a little bit different from voting for government proposals.

Do they even have anything to vote for in the first place?
This is what I talk about in the above comment, each BNB holder can use cli cmd to vote for the existing proposals.

**Comment by Codegigi** [comment]
Yeah thanks for the explanation, any information for posa (proof of staked authority) consensus is hardly found on the web. All they have explained it are proposals and not their voting mechanism

**Comment by KeefeL** [comment]
Actually, there are 21 active validators, and the validators will be reelected everyday, all BNB holders can vote for the validators they trust.

**Comment by Codegigi** [comment]
Thanks @KeefeL do you know if there any documentation or reference I can refer to for understanding voting mechanism of bsc? That way I can move further with it

**Comment by KeefeL** [comment]
You can refer to https://docs.binance.org/smart-chain/guides/bsc-intro.html staking part

**Comment by Codegigi** [comment]
Thanks @KeefeL . I'll check it out :)
