### ISSUE TITLE
[ Testnet ] Don't sync data , Snapshot extension registration failed

### ISSUE THREAD

**Issue by julia-light** [bnb-chain/bsc#776]
#### System information

Geth version: `1.1.8`
OS & Version: `Linux`
Git Commit : `859186f299fa94fada3e92608db1392be1a45599`
Go Version:  `go1.17.1`

#### Expected behaviour
Synchronizing with the network

#### Actual behaviour
Always looking for peers. And err="peer connected on snap without compatible eth support"

**Log**

> t=2022-02-18T03:10:24+0000 lvl=info msg="HTTP server started"                    endpoint=[::]:8575 prefix= cors= vhosts=*
t=2022-02-18T03:10:24+0000 lvl=info msg="WebSocket enabled"                      url=ws://[::]:8576
t=2022-02-18T03:10:24+0000 lvl=info msg="Started P2P networking"                 self=enode://7a8ab318c4c30fe22a0d6a4878f2e1148af83d1ec5c4e1c65030d9326d343b1dfeabbf307d0b207
cf46ed61f93512cbd4c982490b16fd28d6fbbf2b6bc6b76a4@127.0.0.1:30303
t=2022-02-18T03:10:24+0000 lvl=info msg="Generated state snapshot"               accounts=8893 slots=0 storage="409.64 KiB" elapsed=150.977ms
t=2022-02-18T03:10:24+0000 lvl=info msg="Initialized state bloom"                items=12356 errorrate=0.000 elapsed=292.476ms
t=2022-02-18T03:10:25+0000 lvl=info msg="New local node record"                  seq=2 id=cc2ae383f0a3bc3c0ff915354ac5ac7cca4d5fb827770f6ba3fd04e635c7e7d6 ip=13.214.148.33 u
dp=30303 tcp=30303
t=2022-02-18T03:10:26+0000 lvl=eror msg="Snapshot extension registration failed" peer=a6c868a1 err="peer connected on snap without compatible eth support"
t=2022-02-18T03:10:27+0000 lvl=eror msg="Snapshot extension registration failed" peer=89027a8b err="peer connected on snap without compatible eth support"
t=2022-02-18T03:10:35+0000 lvl=info msg="Looking for peers"                      peercount=0 tried=125 static=6
t=2022-02-18T03:10:45+0000 lvl=info msg="Looking for peers"                      peercount=0 tried=93  static=6
t=2022-02-18T03:10:55+0000 lvl=info msg="Looking for peers"                      peercount=0 tried=82  static=6
t=2022-02-18T03:11:06+0000 lvl=info msg="Looking for peers"                      peercount=0 tried=67  static=6
t=2022-02-18T03:11:16+0000 lvl=info msg="Looking for peers"                      peercount=0 tried=75  static=6
t=2022-02-18T03:11:29+0000 lvl=info msg="Looking for peers"                      peercount=0 tried=106 static=6
t=2022-02-18T03:11:40+0000 lvl=info msg="Looking for peers"                      peercount=0 tried=135 static=6
t=2022-02-18T03:11:50+0000 lvl=info msg="Looking for peers"                      peercount=0 tried=68  static=6
t=2022-02-18T03:12:00+0000 lvl=info msg="Looking for peers"                      peercount=0 tried=118 static=6
t=2022-02-18T03:12:05+0000 lvl=eror msg="Snapshot extension registration failed" peer=07ba74b6 err="peer connected on snap without compatible eth support"
t=2022-02-18T03:12:06+0000 lvl=eror msg="Snapshot extension registration failed" peer=c2340321 err="peer connected on snap without compatible eth support"
t=2022-02-18T03:12:10+0000 lvl=info msg="Looking for peers"                      peercount=2 tried=113 static=6
t=2022-02-18T03:12:21+0000 lvl=info msg="Looking for peers"                      peercount=0 tried=84  static=6
t=2022-02-18T03:12:31+0000 lvl=info msg="Looking for peers"                      peercount=0 tried=148 static=6
t=2022-02-18T03:12:41+0000 lvl=info msg="Looking for peers"                      peercount=0 tried=129 static=6
t=2022-02-18T03:12:51+0000 lvl=info msg="Looking for peers"                      peercount=0 tried=87  static=6
t=2022-02-18T03:12:57+0000 lvl=eror msg="Snapshot extension registration failed" peer=c2340321 err="peer connected on snap without compatible eth support"
t=2022-02-18T03:13:02+0000 lvl=info msg="Looking for peers"                      peercount=0 tried=69  static=6
t=2022-02-18T03:13:12+0000 lvl=info msg="Looking for peers"                      peercount=1 tried=91  static=6
t=2022-02-18T03:13:22+0000 lvl=info msg="Looking for peers"                      peercount=2 tried=146 static=6
t=2022-02-18T03:13:42+0000 lvl=info msg="Looking for peers"                      peercount=0 tried=49  static=6
t=2022-02-18T03:13:52+0000 lvl=info msg="Looking for peers"                      peercount=1 tried=132 static=6
t=2022-02-18T03:14:03+0000 lvl=info msg="Looking for peers"                      peercount=0 tried=55  static=6

**Config**
[wget https://github.com/binance-chain/bsc/releases/download/v1.1.8/testnet.zip](url)

>[Node]
DataDir = "node"
InsecureUnlockAllowed = false
NoUSB = true
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8575
HTTPVirtualHosts = ["*"]
HTTPModules = ["debug","eth", "net", "web3", "txpool", "parlia"]
WSHost = "0.0.0.0"
WSPort = 8576
WSModules = ["net", "web3", "eth"]
WSOrigins = ["*"]

#### Steps to reproduce the behaviour

**Start Command**
`/workspace/bsc/build/bin/geth --config /workspace/config/config.toml --datadir /workspace/bsc-data`

**I see the testnet start seems to require a snapshot, but I can't find it.**

**Comment by NZOleg** [comment]
I have exact same issue with mainnet!

`INFO [02-18|07:10:41.669] Starting Geth on Ethereum mainnet... 
WARN [02-18|07:10:41.669] Config field is deprecated and won't have an effect name=ethconfig.Config.EVMInterpreter
WARN [02-18|07:10:41.669] Config field is deprecated and won't have an effect name=ethconfig.Config.EWASMInterpreter
INFO [02-18|07:10:41.671] Maximum peer count                       ETH=30 LES=0 total=30
INFO [02-18|07:10:41.671] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [02-18|07:10:41.671] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable 
INFO [02-18|07:10:41.671] Set global gas cap                       cap=50,000,000
INFO [02-18|07:10:41.671] Allocated trie memory caches             clean=1.17GiB dirty=1.95GiB
INFO [02-18|07:10:41.671] Allocated cache and file handles         database=/home/ubuntu/bsc/node/geth/chaindata cache=3.91GiB handles=524,288
INFO [02-18|07:10:42.006] Opened ancient database                  database=/home/ubuntu/bsc/node/geth/chaindata/ancient readonly=false
INFO [02-18|07:10:42.006] Initialised chain configuration          config="{ChainID: 96 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Berlin: <nil>, London: <nil>, Arrow Glacier: <nil>, MergeFork: <nil>, Engine: unknown}"
INFO [02-18|07:10:42.007] Disk storage enabled for ethash caches   dir=/home/ubuntu/bsc/node/geth/ethash count=3
INFO [02-18|07:10:42.007] Disk storage enabled for ethash DAGs     dir=/home/ubuntu/.ethash              count=2
INFO [02-18|07:10:42.007] Initialising Ethereum protocol           network=56 dbversion=8
INFO [02-18|07:10:42.008] Loaded most recent local header          number=0 hash=3c7b3a..d18cce td=1 age=1y10mo1w
INFO [02-18|07:10:42.008] Loaded most recent local full block      number=0 hash=3c7b3a..d18cce td=1 age=1y10mo1w
INFO [02-18|07:10:42.008] Loaded most recent local fast block      number=0 hash=3c7b3a..d18cce td=1 age=1y10mo1w
INFO [02-18|07:10:42.008] Unprotected transactions allowed 
WARN [02-18|07:10:42.008] Sanitizing invalid gasprice oracle price cap provided=<nil> updated=500,000,000,000
WARN [02-18|07:10:42.008] Sanitizing invalid gasprice oracle ignore price provided=<nil> updated=2
WARN [02-18|07:10:42.008] Sanitizing invalid gasprice oracle max header history provided=0     updated=1
WARN [02-18|07:10:42.008] Sanitizing invalid gasprice oracle max block history provided=0     updated=1
INFO [02-18|07:10:42.008] Starting peer-to-peer node               instance=Geth/v1.10.16-stable-20356e57/linux-amd64/go1.17.5
INFO [02-18|07:10:42.034] New local node record                    seq=1,645,167,419,210 id=0a49914ec985d56a ip=127.0.0.1 udp=30311 tcp=30311
INFO [02-18|07:10:42.035] Started P2P networking                   self=enode://9bd63a183d7afd46d931d43783926823dc5f4699073b571827316dfcdaa655455c9c03d427adc505eee73b255483d01939898af467e6900bcc441d3035073863@127.0.0.1:30311
INFO [02-18|07:10:42.036] IPC endpoint opened                      url=/home/ubuntu/bsc/node/geth.ipc
ERROR[02-18|07:10:42.036] Unavailable modules in HTTP API list     unavailable=[parlia] available="[admin debug web3 eth txpool personal ethash miner net]"
INFO [02-18|07:10:42.036] HTTP server started                      endpoint=127.0.0.1:8545 prefix= cors= vhosts=localhost
INFO [02-18|07:10:44.727] New local node record                    seq=1,645,167,419,211 id=0a49914ec985d56a ip=54.255.205.238 udp=30311 tcp=30311
INFO [02-18|07:10:54.559] Looking for peers                        peercount=0 tried=128 static=10
INFO [02-18|07:11:06.527] Looking for peers                        peercount=0 tried=129 static=10
INFO [02-18|07:11:16.798] Looking for peers                        peercount=0 tried=90  static=10
INFO [02-18|07:11:29.695] Looking for peers                        peercount=0 tried=119 static=10
ERROR[02-18|07:11:33.291] Snapshot extension registration failed   peer=f60d40cf err="peer connected on snap without compatible eth support"
INFO [02-18|07:11:39.904] Looking for peers                        peercount=0 tried=110 static=10
INFO [02-18|07:11:49.918] Looking for peers                        peercount=0 tried=109 static=10
INFO [02-18|07:11:59.968] Looking for peers                        peercount=1 tried=72  static=10
ERROR[02-18|07:12:06.231] Snapshot extension registration failed   peer=1125cc47 err="peer connected on snap without compatible eth support"
INFO [02-18|07:12:09.986] Looking for peers                        peercount=1 tried=133 static=10
`

**Comment by Art-Mas** [comment]
Same...

**Comment by realuncle** [comment]
If you do not do init genesis on BSC, it will use the default ethereum mainnet genesis block and eventually cause peer to peer handshake error.

**Comment by julia-light** [comment]
> If you do not do init genesis on BSC, it will use the default ethereum mainnet genesis block and eventually cause peer to peer handshake error.

Thanks ! your suggestion is very correct and my problem has been solved
