### ISSUE TITLE
Is there a way to add an external node to the active validator set in bsc? Are there any specific functions for doing so?

### ISSUE THREAD

**Issue by Codegigi** [bnb-chain/bsc#779]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

**Comment by Loverush** [comment]
Hello @Codegigi, I'm afraid there's no way to add an external node to the validator set manually.

**Comment by Codegigi** [comment]
How about the second part of the question ie of existing / built-in functions?

**Comment by Loverush** [comment]
@Codegigi No
