### ISSUE TITLE
Is there a way to add a external node to the validator set in bsc? Does BSC have a built- in function for it(if so , then which function is called for the same?) ?

### ISSUE THREAD

**Issue by Codegigi** [bnb-chain/bsc#780]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

**Comment by Loverush** [comment]
Same as #779.
