### ISSUE TITLE
gas required exceeds allowance (8000000)

### ISSUE THREAD

**Issue by msak222** [bnb-chain/bsc#781]
Hello everyone, my smart contract runs normally on ganache and the public test network, but in the private chain built by myself, it always prompts gas required exceeds allowance (8000000)

![image](https://user-images.githubusercontent.com/19371846/155087516-68362212-b380-4517-8f6b-5233d7391fa1.png)

source code：
      
![image](https://user-images.githubusercontent.com/19371846/155087767-e5f1474d-17fd-429c-8a83-cc13e2d7948b.png)

**Comment by Loverush** [comment]
Hello @msak222. You can try to add below lines to `/config/config-bsc-rpc.toml`.
```
[Eth.Miner]
GasFloor = 30000000
GasCeil = 40000000
GasPrice = 5000000000
Recommit = 10000000000
Noverify = false
```
