### ISSUE TITLE
does bsc support eip-2930

### ISSUE THREAD

**Issue by CryptoidsWorld** [bnb-chain/bsc#784]
I send bnb from my contract to my gnosis-safe wallet, it does not work. Then I found this [stackoverflow](https://ethereum.stackexchange.com/questions/122347/transferring-eth-from-contract-to-safe), but it seems doesn't work on bsc. any one can help me? thank you!

**Comment by Loverush** [comment]
Hello @CryptoidsWorld. Sorry bsc doesn't support eip-2930. And we have no plans to do that in the near future.

**Comment by CryptoidsWorld** [comment]
@Loverush thank your for reply, I made a mistake, the bnb locked in the contract now. So will bsc support it in the future？

**Comment by ihorbond** [comment]
This sucks... has this changed by any chance since then @Pythonberg1997 ? thanks
