### ISSUE TITLE
BSC (Binance Smart Chain) local testnet

### ISSUE THREAD

**Issue by shvmjn** [bnb-chain/bsc#788]
Hello,
i am trying to start a local testnet/private network for binance smart chain just like ganache/geth-dev mode.
In official docs  https://docs.binance.org/smart-chain/developer/deploy/local.html  it is extremely unclear how to do so, they have started geth local node which has native currency ETH and not BNB and also PoW consensus mechanism, i'm highly confused about that or maybe i'm missing something (i know its ethereum hard-fork)

Thanks.

**Comment by Loverush** [comment]
Hello @shvmjn, you can refer to https://docs.binance.org/smart-chain/developer/fullnode.html and #502

**Comment by shvmjn** [comment]
@Loverush i already referred it, ran 'make geth' command, but still it has many problems like it did not mine contract deployment transactions (currently i'm running it in --dev mode which is more like ethereum geth node with network id 1337 and not 1000 and is working when contracts are deployed to it, but i feel its wrong). 

That link didn't help also #502 is about production bsc node.

**Comment by Loverush** [comment]
If you wanna "mine contract deployment transactions", you have to run a validator node.

**Comment by shvmjn** [comment]
i tried that but found no difference between running full node and validator node, on both, compiled with truffle or even hardhat the error is same "No Contract at Address 0x812...7h45fe" and sometimes "The transaction is not mined within 750 seconds" 

so the problem is only that the geth 1.1.8 with genesis configuration as follows: 

{
     "config": {
       "chainId": 1000,
       "homesteadBlock": 0,
       "eip155Block": 0,
       "eip158Block": 0
                },
     "nonce": "0x0000000000000061",
     "timestamp": "0x0",
     "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
     "gasLimit": "0x8000000",
     "difficulty": "0x100",
     "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
     "coinbase": "0x3333333333333333333333333333333333333333",
     "alloc": {}
}

(same as provided by the guide https://docs.binance.org/smart-chain/developer/deploy/local.html) not mining contract deployment transactions.

**Comment by realuncle** [comment]
```
> personal.newAccount()
> personal.unlockAccount( eth.accounts[0] )
> miner.start(1)
```

Do you start the miner, otherwise the node can not produce blocks to validate the transaction?

**Comment by shvmjn** [comment]
@realuncle of'course i started the miner, transaction like transfer of eth are being mined from one account to another using geth console command but contract deployment transactions are not being mined.

**Comment by hacdias** [comment]
I have a similar issue here. Even using other consensus protocol, like PoA, it takes much more time to mine anything compared to the original `go-ethereum`, which is a bummer. I'm working on comparing different consensus protocols, but this is a very large difference to make sense.

**Comment by Loverush** [comment]
Sorry for the long delay in responding to you. I have tried to reproduce the problem you encountered but failed. In fact, if you follow the doc of https://docs.binance.org/smart-chain/developer/deploy/local.html, it indeeds start a node of Pow as no validator account be unlock. You can try follow this repo https://github.com/bnb-chain/bsc-docker to start a local node. @hacdias @shvmjn
