### ISSUE TITLE
Testnet can't be added to metamask 

### ISSUE THREAD

**Issue by zby810** [bnb-chain/bsc#789]
I failed to add binance smart chain testnet to metamask, following https://docs.binance.org/smart-chain/developer/rpc.html. 
All RPC has been tried and none works. Metamask erro notice "Could not fetch chain ID. Is your RPC URL correct?"

Talked to Metamask support team and they tried every solution from their side and problem can't be solved. 

Can anybody here help?

**Comment by cosinlink** [comment]
you should set Chain ID to `97` for testnet
