### ISSUE TITLE
how to segment data for archive node

### ISSUE THREAD

**Issue by blissend** [bnb-chain/bsc#790]
Hi, I saw the posts in https://github.com/bnb-chain/bsc/issues/766 from @KeefeL about segmenting your node to do an archive. How does one do that? We have an archive and I would like to see how to break it up into segments (for example block 1 - 1,000,000 for one node and block 1,000,001 - 3,000,000 for another).

**Comment by kakelyo** [comment]
我试过这样可行：
1、用archive模式从0同步到600万块高（大概2.5T）
2、然后停止全节点，把 整个全节点复制一份，复制到新的机器上，这台新的机器的全节点启动时，带上参数--nodiscover，这样新节点就不会同步区块了，永远停留在600万块高。
3、老的那个节点，执行geth snapshot prune-state 命令，清理老的区块，清理后，chaindata只剩200G大小
4、启动老的节点，老的节点就可以从600万块高开始继续同步，而且同步速度是1秒2个区块以上，很快

以此类推，每当全节点超过2T，就停止，复制一份，然后清理老区块，同步速度就可以一直很快了

**Comment by KeefeL** [comment]
> 清理

This is what I want to say. If you still feel complicated, you can try some archive service, such as https://docs.nodereal.io/nodereal/meganode/archive-node
