### ISSUE TITLE
txpool_contentfrom 

### ISSUE THREAD

**Issue by kejinxun** [bnb-chain/bsc#793]
# Rationale

go-ethereum have already had.I think this is for reducing txpool pressure.  So that developers can better pay attention to txPool changes  

# Implementation

Do you have ideas regarding the implementation of this feature?
Are you willing to implement this feature?

**Comment by SolidityGo** [comment]
Got it, we are checking that, thank you.
If there are any updates, I will keep up with them here.

**Comment by SolidityGo** [comment]
We are merging the relevant code into BSC
