### ISSUE TITLE
we can't query the historical block information

### ISSUE THREAD

**Issue by KyloYang888** [bnb-chain/bsc#804]
Hi team. After I run the snapshot with v1.1.8 node, the node is running fine, but we can't query the historical block information. Does anyone know what is the reason for this? Thanks

#### System information

Geth version: `v1.1.8`
OS & Version: CentOS

#### Actual behaviour

admin@ip-172-30-34-83:~$ curl --location --request POST 'http://127.0.0.1:8545' \
--header 'Content-Type: application/json' \
--data-raw '{
     "jsonrpc":"2.0",
     "method":"eth_getBlockByNumber",
     "params":[
         "0x3d0902", 
         true
     ],
     "id":1
 }'
{"jsonrpc":"2.0","id":1,"result":null}

**Comment by masayil** [comment]
I think `eth_getBlockByNumber` is not the historical block information.

**Comment by KyloYang888** [comment]
> Which snapshot do you dowland? If you want to get earlier block information ,do not dowland the `Database after Ancient Data Prune` snapshot

Hi @masayil, thank you for your answer . I downloaded the snapshot from [](https://github.com/bnb-chain/bsc-snapshots) . I think this is the Database after Ancient Data Prune.  Why can't download the data from this URL?  Where should I go to download the full snapshot of the date?  Thanks.

**Comment by masayil** [comment]
> > Which snapshot do you dowland? If you want to get earlier block information ,do not dowland the `Database after Ancient Data Prune` snapshot
> 
> Hi @masayil, thank you for your answer . I downloaded the snapshot from https://github.com/bnb-chain/bsc-snapshots . I think this is the Database after Ancient Data Prune. Why can't download the data from this URL? Where should I go to download the full snapshot of the date? Thanks.

![image](https://user-images.githubusercontent.com/65291464/158972515-9ab500be-d4d9-44c8-92ad-fff90ad4433a.png)

**Comment by masayil** [comment]
> > Which snapshot do you dowland? If you want to get earlier block information ,do not dowland the `Database after Ancient Data Prune` snapshot
> 
> Hi @masayil, thank you for your answer . I downloaded the snapshot from https://github.com/bnb-chain/bsc-snapshots . I think this is the Database after Ancient Data Prune. Why can't download the data from this URL? Where should I go to download the full snapshot of the date? Thanks.

![image](https://user-images.githubusercontent.com/65291464/158973249-1fb877b0-ae58-4c51-8485-8f972c39ab54.png)
The url is right. But in this repo ,there are two diffrent snapshot. The second one is the full snapshot of the data.

**Comment by KyloYang888** [comment]
> > > 你下载哪个快照？如果您想获取更早的区块信息，请不要下载`Database after Ancient Data Prune`快照
> > 
> > 
> > 嗨@masayil，谢谢你的回答。[我从https://github.com/bnb-chain/bsc-snapshots](https://github.com/bnb-chain/bsc-snapshots)下载了快照。我认为这是古代数据修剪后的数据库。为什么不能从这个 URL 下载数据？我应该去哪里下载日期的完整快照？谢谢。
> 
> 网址是对的。但是在这个 repo 中，有两个不同的快照。第二个是数据的完整快照。 你下载的快照大小是多少？数据的完整快照应该是~1Tb ![图片](https://user-images.githubusercontent.com/65291464/158973249-1fb877b0-ae58-4c51-8485-8f972c39ab54.png)

Hi @masayil . I downloaded the snapshot from the screenshot, I will try again with the new snapshot data. Thanks again.

**Comment by cshintov** [comment]
I don't see pruned databases there!
Where can I get a snapshot with historical data?
