### ISSUE TITLE
Error: "Propagated block has invalid body"

### ISSUE THREAD

**Issue by m-e-r-k-l-e-root** [bnb-chain/bsc#811]
All of my nodes (version 1.1.8) are running (presumably) fine, i.e. they're fully synced to head state, have zero issues staying fully synced, etc., etc. But recently I've noticed this error appear every now and then amongst my nodes logs:

**_Propagated block has invalid body_**

Can this error be ignored? Or is it something to be worried about?

Thanks.

**Comment by yutianwu** [comment]
You can ignore this if your node can catch up
