### ISSUE TITLE
how to be validator in private bsc network

### ISSUE THREAD

**Issue by huahuayu** [bnb-chain/bsc#813]
Hi, I want start a private bsc network for test purpose, in etherem I can simply use `--mine` flag to set the node be a miner, but it's not working in bsc.

I searched the issues and read the documents, it seems a `bnbcli` command can be used, but it's for production. Could you please provide some guidelines?

It's very simple in ethereum https://github.com/huahuayu/ethereum-local-private-network

**Comment by huahuayu** [comment]
Hi @steventranjs is there a straightforward way to create a validator and run it.

**Comment by huahuayu** [comment]
Hi @yutianwu I need a local test env which can lunch within mins and have fullly control so i can test things out. Without validator no block be produced.

**Comment by yutianwu** [comment]
you can set up a private ethereum node, it's the same

**Comment by huahuayu** [comment]
I made some changes for bsc node to speed up the trading, so I'd like to use bsc node to test. I think you do have benchmark tests besides mainnet?

**Comment by haliliceylan** [comment]
> Hi, I want start a private bsc network for test purpose, in etherem I can simply use `--mine` flag to set the node be a miner, but it's not working in bsc.
> 
> I searched the issues and read the documents, it seems a `bnbcli` command can be used, but it's for production. Could you please provide some guidelines?
> 
> It's very simple in ethereum https://github.com/huahuayu/ethereum-local-private-network

the git repository you mentioned has a bsc branch, does this work?

**Comment by huahuayu** [comment]
> > Hi, I want start a private bsc network for test purpose, in etherem I can simply use `--mine` flag to set the node be a miner, but it's not working in bsc.
> > I searched the issues and read the documents, it seems a `bnbcli` command can be used, but it's for production. Could you please provide some guidelines?
> > It's very simple in ethereum https://github.com/huahuayu/ethereum-local-private-network
> 
> the git repository you mentioned has a bsc branch, does this work?

yes, it works, it can start a three-node network, one miner two peers, but the network is not same as bsc production.

**Comment by yutianwu** [comment]
> > > Hi, I want start a private bsc network for test purpose, in etherem I can simply use `--mine` flag to set the node be a miner, but it's not working in bsc.
> > > I searched the issues and read the documents, it seems a `bnbcli` command can be used, but it's for production. Could you please provide some guidelines?
> > > It's very simple in ethereum https://github.com/huahuayu/ethereum-local-private-network
> > 
> > 
> > the git repository you mentioned has a bsc branch, does this work?
> 
> yes, it works, it can start a three-node network, one miner two peers, but the network is not same as bsc production.

what do you mean by as bsc production, chain id or something else

**Comment by huahuayu** [comment]
Basically, the genesis config is different, and there's no validator, I just use --miner flag.

**Comment by Davincible** [comment]
Would be nice to have some clear docs on this

**Comment by bnb-tw** [comment]
This is a current issue for us as well.  We have started the process of documenting how we setup local devnets for BSC that run parlia consensus, and the new fast finality mechanism. I'll assign myself to this issue so I can track it.

**Comment by zzzckck** [comment]
Try this one, should work: https://github.com/bnb-chain/node-deploy
