### ISSUE TITLE
Txpool Detect slow in my own node

### ISSUE THREAD

**Issue by kugimiya530** [bnb-chain/bsc#814]
i have compiler a exe to test txpool detect speed

https://youtu.be/xAw4qKCnbzU

the first one object is "quicknode"

second and third is my own node

is there any setting  in geth will cause this problem?

how can i improve it

from my vps to node has 0~2ms latency only

below is my command-line

------------

./geth --config ./config.toml --datadir ./node --cache 40000 --nousb --diffsync --pipecommit --rpc.allow-unprotected-txs --txlookuplimit 0 --ws --ws.addr 0.0.0.0 --ws.origins '*' --ws.api eth,net,web3,txpool,debug --snapshot=false

**Comment by yutianwu** [comment]
sorry, this is out of our scope to help.
