### ISSUE TITLE
[Fullnode] What is the current "knownStates" of synced node?

### ISSUE THREAD

**Issue by itadakimatsu97** [bnb-chain/bsc#824]
I set up a node on AWS:
- m5zn.3xlarge
- SSD gp3 4000 Gib with 12000 IOps and 250 Mb/s

Commnad:
`./geth --config ./config.toml --datadir ./node --diffsync --cache 25000 --rpc.allow-unprotected-txs --txlookuplimit 0`

After 3 days syncing:
![image](https://user-images.githubusercontent.com/63501822/160957067-3e13e357-2030-48b9-97cf-7736d510d10e.png)

Status of VPS during sycing:
![image](https://user-images.githubusercontent.com/63501822/160957641-34169cb6-4bce-435a-b73b-60c56c8ea3fd.png)
It takes a bit power of the CPU. So why does BSC recommend to use m5zn.3xlarge?

What is the current "knownStates" of synced node?
How long I must wait for synced state approximately?

Thank you!

Edited: All steps i followed.

```
1. Download binary
wget   $(curl -s https://api.github.com/repos/bnb-chain/bsc/releases/latest |grep browser_ |grep geth_linux |cut -d\" -f4)
wget   $(curl -s https://api.github.com/repos/bnb-chain/bsc/releases/latest |grep browser_ |grep mainnet |cut -d\" -f4)
unzip [mainnet.zip](http://mainnet.zip/)

2. Init folder structure
./geth --datadir node init genesis.json

3. Download snapshot
sudo wget -q -O - "link" | sudo tar -I lz4 -xvf -


4. Move snapshot data:
mv -v server1/data-seed/geth/chaindata node/geth/chaindata
mv -v server1/data-seed/geth/triecache node/geth/triecache

5. Run geth
./geth --config ./config.toml --datadir ./node --diffsync --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0

6. Check status:
geth attach http://127.0.0.1:8545
eth.syncing
```

**Comment by yutianwu** [comment]
you need to sync from the snapshot, pls refer to this https://docs.binance.org/smart-chain/developer/fullnode.html

**Comment by itadakimatsu97** [comment]
> you need to sync from the snapshot, pls refer to this https://docs.binance.org/smart-chain/developer/fullnode.html

I used a snapshot. Is my behavior unusual?

**Comment by itadakimatsu97** [comment]
Got this issue!
