### ISSUE TITLE
How do I handle this node warning

### ISSUE THREAD

**Issue by acswap** [bnb-chain/bsc#825]
The log report enters the following warning, which has never occurred on any other node
t=2022-03-31T10:12:56+0800 lvl=warn msg="Failed to decode block body"            block=1  error=EOF
t=2022-03-31T10:12:56+0800 lvl=warn msg="Failed to decode block body"            block=2  error=EOF
t=2022-03-31T10:12:56+0800 lvl=warn msg="Failed to decode block body"            block=3  error=EOF
t=2022-03-31T10:12:56+0800 lvl=warn msg="Failed to decode block body"            block=4  error=EOF
t=2022-03-31T10:12:56+0800 lvl=warn msg="Failed to decode block body"            block=5  error=EOF
t=2022-03-31T10:12:56+0800 lvl=warn msg="Failed to decode block body"            block=6  error=EOF
t=2022-03-31T10:12:56+0800 lvl=warn msg="Failed to decode block body"            block=7  error=EOF
t=2022-03-31T10:12:56+0800 lvl=warn msg="Failed to decode block body"            block=8  error=EOF
t=2022-03-31T10:12:56+0800 lvl=warn msg="Failed to decode block body"            block=9  error=EOF
t=2022-03-31T10:12:56+0800 lvl=warn msg="Failed to decode block body"            block=11 error=EOF
t=2022-03-31T10:12:56+0800 lvl=warn msg="Failed to decode block body"            block=10 error=EOF
t=2022-03-31T10:12:56+0800 lvl=warn msg="Failed to decode block body"            block=12 error=EOF
t=2022-03-31T10:12:56+0800 lvl=warn msg="Failed to decode block body"            block=13 error=EOF
t=2022-03-31T10:12:56+0800 lvl=warn msg="Failed to decode block body"            block=14 error=EOF
t=2022-03-31T10:12:56+0800 lvl=warn msg="Failed to decode block body"            block=15 error=EOF
t=2022-03-31T10:12:56+0800 lvl=warn msg="Failed to decode block body"            block=16 error=EOF

What do I need to do about it?

**Comment by yutianwu** [comment]
can you refer to this https://docs.binance.org/smart-chain/developer/fullnode.html and start over again

**Comment by guagualvcha** [comment]
I believe you have done block prune on this node. It is a bug of the prune tools.
`./geth snapshot prune-block --datadir ./node --datadir.ancient ./chaindata/ancient --block-amount-reserved 1024`

--block-amount-reserved  is a must for block prune, now you have to start over again, sorry about the trouble, this bug will be fixed in next release.
