### ISSUE TITLE
Why can't the nApplyForBox function be found in the contract ? 

### ISSUE THREAD

**Issue by chenhonghe** [bnb-chain/bsc#826]
**Why can't the nApplyForBox function be found in the contract ?**  

[https://bscscan.com/tx/0xd6935295182bc658bdf9dce9ccfaa39797b4f0648af5abd05476ec5247467bf4](https://bscscan.com/tx/0xd6935295182bc658bdf9dce9ccfaa39797b4f0648af5abd05476ec5247467bf4)

![1975656367](https://user-images.githubusercontent.com/3805951/160965605-f2e44b77-d2d9-423a-9894-df3747bf044a.jpg)

**Comment by taweesakpintakam** [comment]
Reply

**Comment by yutianwu** [comment]
pls ask for help from the mbox community, thx

**Comment by taweesakpintakam** [comment]
Active bscscan txn .approve

เมื่อ 31 มี.ค. 2022 09:44 "chenhonghe" ***@***.***> เขียนว่า
