### ISSUE TITLE
Node installation: NO INIT 

### ISSUE THREAD

**Issue by animosi** [bnb-chain/bsc#831]
#### System information
https://github.com/bnb-chain/bsc/releases
Geth version: 1.1.8.   TESTNET config/genesis
OS & Version: Linux
Commit hash :

#### Expected behaviour
INIT, allocate cache, init Chain config

#### Actual behaviour

Node does NOT init. 

root@ip-10-0-101-244:/home/ubuntu/bsc# ./build/bin/geth --config ./config.toml --datadir /data --cache 18000 --rpc.allow-unprotected-txs --txlookuplimit 0
INFO [04-01|07:26:27.212] Starting Geth on Ethereum mainnet... 
INFO [04-01|07:26:27.216] Maximum peer count                       ETH=50 LES=0 total=50
INFO [04-01|07:26:27.216] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [04-01|07:26:27.216] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable 

ISSUE: log output stops from here, no init. 

#### Steps to reproduce the behaviour

-deploy AWS EC2
-inbound ports allow all traffic 30311, 8575, outbound allow ALL 
-download geth 1.1.8.   TESTNET config/genesis
-build from source
-configure genesis block with --datadir /data  ***SUCCESS***
-edit config.toml dir path /data HTTPPort set to 0.0.0.0 ALL fields default from github
-run geth with custom config

**SNAPSHOT SKIPPED 
NODE does not init.

Starting geth with NO --config flag WORKS OK 
INIT and sync peers

#### Backtrace

````
[backtrace]
````

**Comment by guagualvcha** [comment]
hi @animosi  the log is on the file system, please check `/data/bsc.log`

**Comment by animosi** [comment]
Yes. Thank u. Wasted a day lol
