### ISSUE TITLE
Static Peers and MaxPeers

### ISSUE THREAD

**Issue by James19903** [bnb-chain/bsc#833]
I have the default Static Nodes set up in the config.toml file but when I attach to geth and use this command:
admin.peers(), it doesn't show me any these, how can I see which Static Nodes am connected to?

**Comment by James19903** [comment]
> 

No it has finished syncing, I am getting the newest blocks

**Comment by yutianwu** [comment]
are you sure you can not see peers when syncing, can you confirm that
