### ISSUE TITLE
Problem. Chaindata directory is too big.

### ISSUE THREAD

**Issue by amiDMast** [bnb-chain/bsc#836]
In the system requirements is written that the node: `IMPORTANT 2T GB of free disk space`.
At the moment, I have 2.7T chaindata...
`root@bsc-node /var/lib/bsc/data/geth # du -hs chaindata/`
`2,7T	chaindata/`

Tell me please what can be done, the disk space is running out...

`geth --config /etc/bsc/config.toml --allow-insecure-unlock --cache=13384 --datadir /var/lib/bsc/data --txlookuplimit=0 --snapshot=true  --diffsync`

```root@bsc-node /var/lib/bsc # geth version
Geth
Version: 1.1.8
Git Commit: 859186f299fa94fada3e92608db1392be1a45599
Architecture: amd64
Go Version: go1.16.13
Operating System: linux
GOPATH=
GOROOT=go```

**Comment by yutianwu** [comment]
You can stop your node and prune. you can refer to this https://docs.binance.org/smart-chain/developer/fullnode.html. 

`nohup geth snapshot prune-state --datadir {the data dir of your bsc node} &`

**Comment by loganbonsignore** [comment]
I am having this same issue. I downloaded the latest snapshot and am in the process of un-compressing. So far I am at 3TB and no signs of slowing down. Is that normal?

**Comment by amiDMast** [comment]
> You can stop your node and prune. you can refer to this https://docs.binance.org/smart-chain/developer/fullnode.html.
> 
> `nohup geth snapshot prune-state --datadir {the data dir of your bsc node} &`

Thank you! It helped me! Execution time 15 hours, pruned=1.38TiB

**Comment by Lippertt** [comment]
Obrigado ,mais pela dedicação
Quero conversar com vc !

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
