### ISSUE TITLE
debug_traceCall not working

### ISSUE THREAD

**Issue by berktaylan** [bnb-chain/bsc#839]
When i try to call debug_traceCall , its not working.

This is the response 

`{
  id: 1,
  error: {
    code: -32601,
    message: 'Invalid method',
    data: 'got unsupported method name: debug_traceCall'
  },
  jsonrpc: '2.0'
}
`

This is the geth parameters
`ExecStart=/data/geth --config /data/config.toml --datadir /data/node --cache 80000 --rpc.allow-unprotected-txs --txlookuplimit 0 --http --http.api eth,debug --ws --ws.api debug,eth --syncmode=full --diffsync --snapshot=true`

**Comment by forcodedancing** [comment]
Hello @berktaylan, may I ask which BSC version you are using?

I tested v1.1.8 in my local environment, it actually works.

Example request:
`{
    "method": "debug_traceCall",
    "params": [
        {
            "from": null,
            "to": "0x6b175474e89094c44da98b954eedeac495271d0f",
            "data": "0x70a082310000000000000000000000006E0d01A76C3Cf4288372a29124A26D4353EE51BE"
        },
        "latest"
    ],
    "id": 1,
    "jsonrpc": "2.0"
}`

Example response:
`{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "gas": 21432,
        "failed": false,
        "returnValue": "",
        "structLogs": []
    }
}`

My config file:
`
...
[Node]
IPCPath = "geth.ipc"
HTTPHost = "localhost"
NoUSB = true
InsecureUnlockAllowed = false
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia", "debug"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]
...
`

Could try it again? If there still is any issue, please share your request and we can further check. Thanks.
