### ISSUE TITLE
What will happen when the pruned database exceeds the optimal working size?

### ISSUE THREAD

**Issue by dgdeivid** [bnb-chain/bsc#840]
Currently it is recommended that the node's database does not exceed 1.5 TB as above that size the node's performance decays very quickly : _According to the test, the performance of a fullnode will degrade when the storage size exceeds 1.5T. We suggest the fullnode always keeps light storage by pruning the storage._ (https://github.com/bnb-chain/bsc/issues/502)

Currently the size of the pruned database is more than 1.3 TB and continues to increase each time more transactions are created.

What will happen when the pruned database size is over 1.5 TB, BSC will stop working?

**Comment by forcodedancing** [comment]
Hello @dgdeivid , I think you can prune blocks by using the following command. And when the space usage becomes big you can run it again.
`./geth snapshot prune-block --datadir ./node --datadir.ancient ./chaindata/ancient --block-amount-reserved 1024` 
Note: please change the paths/values based on your settings/preference.

Even the pruned database size is over 1.5 TB, BSC can continually work. Thanks.

**Comment by dgdeivid** [comment]
Hello, I know what I can do prune. That is not my question.

You indicate that BSC will continue to function when the pruned size exceeds 1.5 TB. But @guagualvcha points out that in the tests carried out, the performance falls above 1.5 TB.

I have been able to verify the same thing, in my nodes, if I do not do a prune when the storage is above 1.5TB, the node slows down a lot and the blocks and transactions take much longer to process. 

The question is, **what measures are going to be taken to avoid that when the pruned size reaches 1.5 TB, the BSC performance drops enormously?** In addition, it seems that the performance decay above 1.5 TB is not a fixed value, but rather that the more the size increases, the performance still worsens. Therefore I think there should be a plan to fix this problem and if this problem does not exist I would appreciate it if someone explained in detail why they think this problem does not exist.

**Comment by forcodedancing** [comment]
Hello @dgdeivid Sorry, I did not make my point clear.
Block pruning is a kind of quick action at the moment to make sure your disk is under the value. More importantly, there are teams/contributors working on the performance improvement  (e.g., 1.1.9 release), which should be the direct answer to this. Hopefully, we can get more updates in the following days/weeks...
