### ISSUE TITLE
sha256 mismatch on published asset

### ISSUE THREAD

**Issue by jakeo** [bnb-chain/bsc#841]
The sha on `mainnet.zip` in [v1.1.8](https://github.com/bnb-chain/bsc/releases/tag/v1.1.8) doesn't match what's published.

Published sha:
`5527293b313781ad86f186279083f55be909a3257d0919a4d838b0522ed41a37`

mainnet.zip sha:
`6dd6976b9c8d407e95ed99cd46f7badfa410f3f374ea3e360defab0f63fa3ed2`

Where did this `mainnet.zip` come from?

**Comment by forcodedancing** [comment]
Hello @jakeo , you are right. The correct sha should be `6dd6976b9c8d407e95ed99cd46f7badfa410f3f374ea3e360defab0f63fa3ed2`. We had updated the release not to reflect this. Thanks a lot for your reporting.

**Comment by jakeo** [comment]
Thx @forcodedancing!

Still curious as to how the zip was updated, I tried tracing the action which uploaded and computed the sha for `mainnet.zip` but was unsuccessful in finding this.
