### ISSUE TITLE
$$$

### ISSUE THREAD

**Issue by Lippertt** [bnb-chain/bsc#845]
I am using a light node v1.1.7, when sending requests to GetBalance, the following error occurs:
WARN [01-06|17:29:47.817] Served eth_getBalance reqid=1 t=3.0091902s err="getDeleteStateObject (295e26495cef6f69dfa69911d9d8e4f3bbadb89a) error: no suitable peers available"

before that there were such errors:
WARN [01-06|14:33:28.035] Served eth_call reqid=1 t=21.046081163s err="execution aborted (timeout = 5s)" X-Forwarded-For=nil

net.peerCount returns 16.
firewall is inactive.

started geth with arguments:
--config=D:\config.toml --metrics --metrics.addr 0.0.0.0 --cache 8192 --syncmode light --diffsync

**Comment by madhan5447** [comment]
@Lippertt 

> I am using a light node v1.1.7, when sending requests to GetBalance, the following error occurs: WARN [01-06|17:29:47.817] Served eth_getBalance reqid=1 t=3.0091902s err="getDeleteStateObject (295e26495cef6f69dfa69911d9d8e4f3bbadb89a) error: no suitable peers available"
> 
> before that there were such errors: WARN [01-06|14:33:28.035] Served eth_call reqid=1 t=21.046081163s err="execution aborted (timeout = 5s)" X-Forwarded-For=nil
> 
> net.peerCount returns 16. firewall is inactive.
> 
> started geth with arguments: --config=D:\config.toml --metrics --metrics.addr 0.0.0.0 --cache 8192 --syncmode light --diffsync

are you fix this issue
