### ISSUE TITLE
Disk Space Running Out - Possible to Move Ancient DB?

### ISSUE THREAD

**Issue by SharpKai** [bnb-chain/bsc#847]
I'm running Geth 1.1.8 and started a full node from the snapshot provided.

Current disk space is running at 1.6TB, but this particular NVME drive is only 2TB so I'm looking for ways to reduce NVME storage requirements.

Is it possible to relocate any part of the blockchain data to the HDD without compromising performance?  I've read elsewhere that the Ancient DB might be a good candidate.  If so, how can that be accomplished and what would the implications be?

I know I can prune the DB, but I thought the downloaded snapshot was already pruned (https://github.com/bnb-chain/bsc-snapshots), so I'm not sure what the benefits would be.

Thanks in advance!

**Comment by forcodedancing** [comment]
Hello @SharpKai I think you can consider the following options:
1) Prune old block data
`
./geth snapshot prune-block --datadir ./node --datadir.ancient ./chaindata/ancient --block-amount-reserved 1024
` 
Please change the dir to the correct ones based on your settings.

2) Move ancient db
You can use `--datadir.ancient` CLI flag to achieve this. For more details, you can refer to https://blog.ethereum.org/2019/07/10/geth-v1-9-0/

Hopefully this can help you. Thanks.

**Comment by SharpKai** [comment]
Thanks @forcodedancing ! Are there any performance penalties for moving the ancient db to a different drive?

**Comment by forcodedancing** [comment]
> Thanks @forcodedancing ! Are there any performance penalties for moving the ancient db to a different drive?

It could be slow for querying/accessing the historical blocks/txs. If you do not care about these old blocks/txs, then it should not have performance impact on your business.

**Comment by nyllewin** [comment]
> Hello @SharpKai I think you can consider the following options:
> 
> 1. Prune old block data
>    `./geth snapshot prune-block --datadir ./node --datadir.ancient ./chaindata/ancient --block-amount-reserved 1024`
>    Please change the dir to the correct ones based on your settings.
> 2. Move ancient db
>    You can use `--datadir.ancient` CLI flag to achieve this. For more details, you can refer to https://blog.ethereum.org/2019/07/10/geth-v1-9-0/
> 
> Hopefully this can help you. Thanks.

Hello, I've tried this earlier with changing the dirs according to my folder structure but got greeted with 
 datadir.ancient not abs path 

which happens because of https://github.com/bnb-chain/bsc/search?q=datadir.ancient+not+abs+path&type=code

Is the example wrong? Am I doing something wrong?

**Comment by SharpKai** [comment]
> Hello @forcodedancing, I've tried method 1 earlier with changing the dirs according to my folder structure but got greeted with datadir.ancient not abs path
> 
> which happens because of https://github.com/bnb-chain/bsc/search?q=datadir.ancient+not+abs+path&type=code
> 
> Is the example wrong? Am I doing something wrong?
@nyllewin,
I got it work by using absolute paths instead of relative paths.

**Comment by forcodedancing** [comment]
Yes, can you try with absolute paths? @nyllewin

**Comment by nyllewin** [comment]
oh my I needed to put both as absolute paths, yea. sorry my bad. new to this 👍  all good!

**Comment by wangtsiao** [comment]
can't access the freezer or it's empty, abor

> Hello @SharpKai I think you can consider the following options:
> 
> 1. Prune old block data
>    `./geth snapshot prune-block --datadir ./node --datadir.ancient ./chaindata/ancient --block-amount-reserved 1024`
>    Please change the dir to the correct ones based on your settings.
> 2. Move ancient db
>    You can use `--datadir.ancient` CLI flag to achieve this. For more details, you can refer to https://blog.ethereum.org/2019/07/10/geth-v1-9-0/
> 
> Hopefully this can help you. Thanks.

Hello @forcodedancing , I've tried method 1 with changing the dirs according to my folder structure but got with
```
can't access the freezer or it's empty, abort
```

Am I doing something wrong?
