### ISSUE TITLE
Total node count.

### ISSUE THREAD

**Issue by berktaylan** [bnb-chain/bsc#853]
How can we see or detect total node count ( synced ) on bsc network ?

**Comment by ktrout1111** [comment]
There isn't really a function to do that. Even if you could, the number you got would be meaningless, since at least 80% of the "nodes" on BSC are "fake" - just tx spammers for bot owners.

**Comment by forcodedancing** [comment]
There is no such function yet. Hello @berktaylan  why do you want this?
