### ISSUE TITLE
Metrics used to monitor validator status

### ISSUE THREAD

**Issue by jennyhys** [bnb-chain/bsc#857]
Is there any built-in metrics that can be used to monitor status/performance of a validator?Examples included the number of blocks missed by the validator when it's being selected, the number of blocks that the validator being selected, the number of blocks it has signed/validated

**Comment by forcodedancing** [comment]
Hello @jennyhys there is no such built-in metrics for validator status. Thanks.

**Comment by jennyhys** [comment]
@forcodedancing Thanks for the prompt response! Other than the logs and the explorer, is there a way to verify a validator is signing blocks then?

**Comment by forcodedancing** [comment]
@jennyhys Based on my understanding, I don't think there are other metrics for this.
