### ISSUE TITLE
How To Use PoS in a Local Network

### ISSUE THREAD

**Issue by hacdias** [bnb-chain/bsc#861]
Hi!

I'm working on a project where I am supposed to compare the performance of different consensus mechanisms. For simplicity, I wanted to use bsc because it is compatible with `go-ethereum` and it provides Parlia for the PoS mechanism.

However, I'm having a hard time figuring out how to run a local test network with Parlia. I could not find any documentation explaining how to build the genesis file for Parlia. I understand that for Clique, we have to add the validators on the `extraData` field, but what about Parlia?

I tried partially copying the `genesis.json` provided int the releases page and make some modifications. It works for a while and then I start getting `unauthorized validator`.

Here's the genesis file I am using for the local network: https://gist.github.com/hacdias/4dae661f287e764315107cb8ff5b5b2f

Is there any documentation or direction on how to correctly setup Parlia?

**Comment by forcodedancing** [comment]
Hello @hacdias have you checked this https://docs.binance.org/smart-chain/developer/deploy/local.html ?

**Comment by hacdias** [comment]
@forcodedancing I did. However, those docs don't mention which consensus algorithm is being used. The genesis.json file provided there looks like a PoW genesis file.

**Comment by forcodedancing** [comment]
@hacdias thanks for the feedback. I see, I suggest you to user other forks to conduct the PoS test. For setting up private Parlia, you need to init many genesis contracts (BSC have them for private now, I believe), it could be not easy.

**Comment by hacdias** [comment]
@forcodedancing do you know of any other forks using PoS? That'd be useful!

**Comment by forcodedancing** [comment]
> @forcodedancing do you know of any other forks using PoS? That'd be useful!

Sorry, I don't know any other forks using PoS right now.
