### ISSUE TITLE
same config and command but different result

### ISSUE THREAD

**Issue by kugimiya530** [bnb-chain/bsc#869]
i has 3  server to build fullnode

they are in same location and has same spec.  (gigabit network, nvme , 128G ram  16+ Cpu)

one of them always sync faster than others like 0.5 ~1s to latest block

./geth --config ./config.toml --datadir ./node --cache 60000 --nousb --maxpeers 300 --pipecommit --rpc.allow-unprotected-txs --txlookuplimit 0 --ws --ws.addr localhost --ws.origins '*' --ws.api eth,net,web3 --snapshot=false --rpc.txfeecap 0 

------------------------------------------------additional information----------------------------------------------

try to modify other's  server 's  command
but looks useless 

ex: using --diffsync  instead of --pipecommit
      
     increase --maxpeers
    
     modify --cache
---------------------------------------------additional information--------------------------------------------------
anyone has good tip or command or information for improve node's performance?

i heard from some people  , there is  modified geth 

is that truth?

**Comment by kugimiya530** [comment]
.

**Comment by Loverush** [comment]
Hello @kugimiya530 , we don't recommend to use modified geth instead of our released version.
