### ISSUE TITLE
Node stuck at beginning

### ISSUE THREAD

**Issue by x64x48** [bnb-chain/bsc#876]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

Hi there,

I used macOS and try to run bscchain. After I initialize the genesis file with testnet config, the node always stuck at beginning.

Here is the screenshot:
<img width="437" alt="Screen Shot 2022-04-26 at 9 19 55 PM" src="https://user-images.githubusercontent.com/81462372/165310665-1643f57a-2f01-49e4-8841-301b6d7fe541.png">

The cpu and memory is too low, so I think it got stuck somewhere. The doc I read: https://docs.binance.org/smart-chain/developer/fullnode.html

Thanks!

**Comment by Loverush** [comment]
Hello @x64x48 , it's not stuck. You can check `bsc.log` for running log.
