### ISSUE TITLE
Doubt there's a Race Condition in MatcherSession

### ISSUE THREAD

**Issue by Mercybudda** [bnb-chain/bsc#878]
#### System information

Geth
Version: 1.1.9
Git Commit: 74ecbf271dc0d32cbc459f83a271408b8485b2c4
Architecture: amd64
Go Version: go1.15.5
Operating System: linux
GOROOT=go

#### Actual behaviour
![image](https://user-images.githubusercontent.com/25290445/165468804-819a5084-268b-4c4a-bc0d-e80aecb458b8.png)

There's frequent problem in testnet recently as above image even after reboot the node, after looking into the log, seemed stored of type value mismatch, I doubt that's because of race condition without acquiring lock to access the same field `err` in struct, source code as below:
<img width="501" alt="image" src="https://user-images.githubusercontent.com/25290445/165470060-2afaa2b5-d304-4d27-b581-4b47ed1e1f58.png">

#### Steps to reproduce the behaviour
Run the same version geth in testnet

When submitting logs: please submit them as text and not screenshots.

**Comment by Loverush** [comment]
It's interesting to report this error. Did you ever modify your node geth binary yourself?
