### ISSUE TITLE
prune-state Execution takes longer than usual

### ISSUE THREAD

**Issue by mycarlos26** [bnb-chain/bsc#880]
good morning my question is the following.
Why has it taken so long to run the command ./geth snapshot prune-state --datadir ./node --datadir.ancient /ancient/ancient I ran it yesterday and it still has not completed.
attached image
thank you
![prune](https://user-images.githubusercontent.com/11149480/165772054-450604ce-1361-4914-b353-e34000f155e8.png)

**Comment by Lippertt** [comment]
Boa tarde a todos seguinte tava precisando que alguém fizesse esse trabalho por mim e eu dar uma boa quantia para fazer trabalho que eu não tô tendo tempo

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
From: mycarlos26 ***@***.***>
Sent: Thursday, April 28, 2022 11:15:21 AM
To: bnb-chain/bsc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bnb-chain/bsc] prune-state Execution takes longer than usual (Issue #880)


good morning my question is the following.
Why has it taken so long to run the command ./geth snapshot prune-state --datadir ./node --datadir.ancient /ancient/ancient I ran it yesterday and it still has not completed.
attached image
thank you
[prune]<https://user-images.githubusercontent.com/11149480/165772054-450604ce-1361-4914-b353-e34000f155e8.png>

**Comment by mycarlos26** [comment]
INFO [04-28|01:05:11.695] Pruned state data                        nodes=124,152,516 size=33.28GiB  elapsed=2h18m28.271s
INFO [04-28|01:05:11.897] Compacting database                      range=0x00-0x10 elapsed="117.18µs"
INFO [04-28|01:26:19.164] Compacting database                      range=0x10-0x20 elapsed=21m7.267s
INFO [04-28|01:52:41.571] Compacting database                      range=0x20-0x30 elapsed=47m29.674s
INFO [04-28|02:18:59.046] Compacting database                      range=0x30-0x40 elapsed=1h13m47.149s
INFO [04-28|02:56:54.530] Compacting database                      range=0x40-0x50 elapsed=1h51m42.633s
INFO [04-28|03:38:25.003] Compacting database                      range=0x50-0x60 elapsed=2h33m13.106s
INFO [04-28|04:16:29.241] Compacting database                      range=0x60-0x70 elapsed=3h11m17.344s
INFO [04-28|07:52:19.973] Compacting database                      range=0x70-0x80 elapsed=6h47m8.076s
INFO [04-28|08:35:42.369] Compacting database                      range=0x80-0x90 elapsed=7h30m30.471s
INFO [04-28|09:13:37.747] Compacting database                      range=0x90-0xa0 elapsed=8h8m25.849s
INFO [04-28|09:51:01.182] Compacting database                      range=0xa0-0xb0 elapsed=8h45m49.285s
INFO [04-28|10:28:00.071] Compacting database                      range=0xb0-0xc0 elapsed=9h22m48.174s
INFO [04-28|11:04:25.342] Compacting database                      range=0xc0-0xd0 elapsed=9h59m13.444s
INFO [04-28|11:40:49.475] Compacting database                      range=0xd0-0xe0 elapsed=10h35m37.577s
INFO [04-28|12:16:31.438] Compacting database                      range=0xe0-0xf0 elapsed=11h11m19.541s
INFO [04-28|12:51:02.318] Compacting database                      range=0xf0-     elapsed=11h45m50.421s
INFO [04-28|13:30:15.089] Database compaction finished             elapsed=12h25m3.192s
INFO [04-28|13:30:15.089] State pruning successful                 pruned=33.28GiB elapsed=15h51m42.761s
