### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by charliedimaggio** [bnb-chain/bsc#881]
#### System information

Geth version: `1.1.9`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
Not crashing

#### Actual behaviour
Apr 12 16:02:53 bash[61319]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 14 16:19:41 bash[328529]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 14 21:41:59 bash[42545]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 15 03:07:16 bash[450170]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 15 17:43:06 bash[860095]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 16 10:18:07 bash[1980240]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 16 13:58:36 bash[3186710]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 16 16:50:11 bash[3375191]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 16 18:14:13 bash[3569441]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 17 06:01:29 bash[3666037]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 18 20:27:39 bash[2372706]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 25 02:41:50 bash[4165608]: panic: runtime error: invalid memory address or nil pointer dereference

#### Backtrace
I can provide backtraces for these crashes if they are of value, but I think these are known bugs. I just do not want to have to rebuild geth again.
````
[backtrace]
````
I rolled back to 1.1.8 hoping that I would find that to be more stable, but now I am getting these crashes:
`fatal error: concurrent map iteration and map write`
which seem to corrupt the database when they occur.

**Comment by Loverush** [comment]
Hello @charliedimaggio ,try to upgrade to the newest version of master branch

**Comment by charliedimaggio** [comment]
> 

Hi @Loverush I did exactly that last night as I could see that a fix for a panic had been merged with master, but I wanted to provide feedback as I hadn't seen anyone else report that they are suffering with this issue.

**Comment by Loverush** [comment]
Sure, thank you!

**Comment by charliedimaggio** [comment]
> Sure, thank you!
Hi @Loverush that commit doesn't seem to have resolved this particular crash I am experiencing. I have provided the backtrace. Are there any other details that would help?

#### System information

Geth version: `1.1.9`
OS & Version: Linux
Git Commit: `0f5a4c87dbb5a7223d21fa6cc9d7020f676dfa05`
Git Commit Date: 20220425

#### Actual behaviour
`panic: runtime error: invalid memory address or nil pointer dereference`

#### Backtrace
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7bf189]
goroutine 55807923 [running]:
github.com/ethereum/go-ethereum/core/state.(*triePrefetcher).close(0xc23e50a7e0)
        github.com/ethereum/go-ethereum/core/state/trie_prefetcher.go:123 +0x2e9
github.com/ethereum/go-ethereum/core/state.(*StateDB).StopPrefetcher(0xc2381a9680)
        github.com/ethereum/go-ethereum/core/state/statedb.go:219 +0x90
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain.func2()
        github.com/ethereum/go-ethereum/core/blockchain.go:2049 +0x2a
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc036328000, {0xc3723dc470, 0x1, 0x1}, 0x1)
        github.com/ethereum/go-ethereum/core/blockchain.go:2229 +0x38c0
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc036328000, {0xc3723dc470, 0x1, 0x1})
        github.com/ethereum/go-ethereum/core/blockchain.go:1906 +0xb34
github.com/ethereum/go-ethereum/eth.newHandler.func3({0xc3723dc470, 0xc10bea8200, 0xfa3755186f71e53f})
        github.com/ethereum/go-ethereum/eth/handler.go:237 +0x5f8
github.com/ethereum/go-ethereum/eth/fetcher.(*BlockFetcher).importBlocks.func1()
        github.com/ethereum/go-ethereum/eth/fetcher/block_fetcher.go:858 +0x922
created by github.com/ethereum/go-ethereum/eth/fetcher.(*BlockFetcher).importBlocks
        github.com/ethereum/go-ethereum/eth/fetcher/block_fetcher.go:829 +0x40f
