### ISSUE TITLE
Big changes in mgasps and CPU usage

### ISSUE THREAD

**Issue by James19903** [bnb-chain/bsc#892]
Recently I have seen my node fluctuate massively when Importing new chain segments, I haven't changed anything to it, just let it run.
For some reason my CPU % will drop to 20% and my mgasps will also be sometimes as low as 40, previously it was almost 150.
Any reason for this?

Also, what is this? 
t=2022-05-04T03:33:05+0200 lvl=eror msg="do light process err at block"          num=17,497,633 err="missing code, account 0xXXXXXXXXXXXXX"

**Comment by bnb-tw** [comment]
@James19903 is this still an issue for you?
