### ISSUE TITLE
Any one can please fix Binance Smart Chain Faucet ?

### ISSUE THREAD

**Issue by parthindia47** [bnb-chain/bsc#899]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour

Binance faucet is not working as it should : https://testnet.binance.org/faucet-smart

#### Actual behaviour

Binance faucet should fund BNB on testnet

#### Steps to reproduce the behaviour
1. go to : https://testnet.binance.org/faucet-smart
2. enter any bsc chain address
3. try to fund 1 bnb

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by jjjachyty** [comment]
same with,cannot take bnb ,insufficient funds for gas * price + value,plz fix it,thx!!

**Comment by whowantsmoneyman** [comment]
yes ive tried to get some test BNB to my wallet and got the following error - 

insufficient funds for gas * price + value

**Comment by frabazz** [comment]
any idea on when are they going to fix it? It's been almost 2 days since the problem.

**Comment by Lecs-90** [comment]
+1

**Comment by frabazz** [comment]
UPDATE: They fixed the problem at https://testnet.binance.org/faucet-smart

**Comment by guagualvcha** [comment]
fixed.

**Comment by jeyadevlink** [comment]
again it stopped working how we can fix it

**Comment by Tran-Minh23** [comment]
I got the same problem, is there any way to get TBNB?

**Comment by jaynishb** [comment]
Any update? Please fix this, not be able to test without getting BEP-20 token to test!
