### ISSUE TITLE
Binance Smart Chain Faucet ERROR.. insufficient to funds test account

### ISSUE THREAD

**Issue by tengty** [bnb-chain/bsc#900]
insufficient funds for gas * price + value

**CAN ANYONE FIX THIS PROBLEM, NO GAS FEES in faucet to fund TOKEN. PLEASE HELP!!!!**

**Comment by jjjachyty** [comment]
+1

**Comment by jjjachyty** [comment]
@guagualvcha @karalabe

**Comment by tengty** [comment]
https://testnet.binance.org/faucet-smart not working... unable to fund test wallet. Binance shutting down??? Can some on fix the bsc faucet?

**Comment by thaobacoor** [comment]
Do the team has any updates?

**Comment by AnPhung542** [comment]
fix pls

**Comment by ASHKARAN** [comment]
+1

**Comment by alantorrisi** [comment]
+1

**Comment by ZagatoBruno** [comment]
+1

**Comment by zoand** [comment]
+1

**Comment by Lecs-90** [comment]
+1

is this today's error? never had this one before...

**Comment by tengty** [comment]
It has been more than 2 days this error. Unable receive BNB token from BSC faucet... testnet run out of BNB binance no intension to fix this problem??

**Comment by mpefaur** [comment]
+1

**Comment by guagualvcha** [comment]
fixed

**Comment by Najmul59** [comment]
Very strong project

**Comment by KayAlbertus** [comment]
This is happening again is anyone else experiencing the same ?

**Comment by adeojoemmanuelimm** [comment]
+1

**Comment by mysteryon88** [comment]
+

**Comment by mysteryon88** [comment]
+1

**Comment by tjzango** [comment]
+1

**Comment by redmouseindia** [comment]
This is happening again.

**Comment by redmouseindia** [comment]
erro "insufficient funds for gas * price + value" in bnb testnet Faucet

**Comment by boxingcoder00** [comment]
Im getting both  "insufficient funds for gas * price + value and "your a robot" errors

**Comment by naviinkapoor** [comment]
Same problem again. Can some one send me some test BNB to 0xab455dEdda67D671Be9e1aA27Be0BEe21f45A6aC

**Comment by SonderRill** [comment]
the same problem, I can't get test tokens to any of the wallets 
![image](https://github.com/bnb-chain/bsc/assets/49909245/19e92e31-0c40-4b00-a6de-c987fe87579f)

**Comment by gadfil** [comment]
+1

**Comment by seewanrdd** [comment]
0x9CD61dBACfCf32C9b1f0eB1B648413BdB4aBc282 please send some
