### ISSUE TITLE
debug_ rpc methods missing 

### ISSUE THREAD

**Issue by joleeee** [bnb-chain/bsc#903]
Recently tried the newest release and found some debug methods to be missing. Were they moved or something?

#### System information

Geth version: `Version: 1.1.10`
OS & Version: Alpine, kernel 5.10

#### Expected behaviour
debug.peers, debug.nodeInfo, debug.addPeer should work

#### Actual behaviour
```sh
$ geth attach /node/geth.ipc --exec 'debug.peers'
undefined
```

**Comment by cryyl** [comment]
This three functions are under admin content. You can use admin.peers, admin.nodeInfo and admin.addPeer.

**Comment by joleeee** [comment]
How embarrasing, thank you
