### ISSUE TITLE
allow for flag configured timeouts for eth_call

### ISSUE THREAD

**Issue by masayil** [bnb-chain/bsc#912]
![image](https://user-images.githubusercontent.com/65291464/168524207-32d911f1-80c7-4baf-87a8-313012183761.png)

Ethereum has already added this feature.Is it possible for BSC to add this feature？
https://github.com/ethereum/go-ethereum/pull/23645

**Comment by j75689** [comment]
Hi @masayil , we are currently working on merging go-ethereum v1.10.15 into BSC, this feature can be used after we merged.
