### ISSUE TITLE
Related to Gas charge

### ISSUE THREAD

**Issue by speqtovijay** [bnb-chain/bsc#917]
hello everyone can anyone guide me how to change (reduce or increase) gas, gas price, gas for Transaction from blockchain

**Comment by j75689** [comment]
Hi @speqtovijay , gas is calculated by EVM module, if you want to reduce the gas cost, you can try to simplify the smart contract that you called.
The gas price and gas limit of the transaction are set when you submit the transaction.

**Comment by owen-reorg** [comment]
Here is a guide for metamask: <https://metaschool.so/articles/set-gas-fees-metamask-wallet/>

For other wallets, you should check the manual.

Feel free to reopen the issue if you have any further questions.
