### ISSUE TITLE
Transaction validation time

### ISSUE THREAD

**Issue by James19903** [bnb-chain/bsc#918]
Has BSC always been 2 blocks to validate a transaction?
Whenever I send a TX through my node, it will be validated around 2 blocks after, regardless of GWEI etc, is there anyway to reduce this to 1 block?

**Comment by psdlt** [comment]
@James19903 yes, it was always 2 blocks and there is no way to reduce it.

**Comment by speqtovijay** [comment]
@psdlt can you suggest me how i can reduce gas price for deploy and transaction?  is any wwy from blockchain code to change gas price

**Comment by psdlt** [comment]
@speqtovijay minimum gas price on BSC is 5gwei

**Comment by speqtovijay** [comment]
@psdlt is it fixed?

**Comment by psdlt** [comment]
@speqtovijay minimum is 5gwei, there is no upper limit.

**Comment by speqtovijay** [comment]
@psdlt can i change in blockchain code when i setup on local machine for testing purpose

**Comment by psdlt** [comment]
@speqtovijay locally you can do whatever you want :)

**Comment by speqtovijay** [comment]
@psdlt how can change in which module can you help in out

**Comment by speqtovijay** [comment]
@psdlt i tried but never changed can you help me from where we can change

**Comment by speqtovijay** [comment]
anyone can guide me how to customise gas fee on local Machine?
