### ISSUE TITLE
avg block mining time too much

### ISSUE THREAD

**Issue by rizwanahmad00** [bnb-chain/bsc#919]
At the time blockchain taking 3 sec on local machine in block generation but over my live server  taking **12 sec** ,this is too much 
is the any option to reduce time .
kindly help me
Thanks in advance 
@atoulme @reds @ryanschneider @evertonfraga

**Comment by j75689** [comment]
Hi @rizwanahmad00 may I know whether you are using parlia engine?

**Comment by guagualvcha** [comment]
close this since no further discussion.
