### ISSUE TITLE
AWS Instance?

### ISSUE THREAD

**Issue by James19903** [bnb-chain/bsc#921]
I want to run a Node on AWS but I'm not sure which instance I need, there is so many of them. It says here (https://docs.binance.org/smart-chain/developer/fullnode.html) that a m5zn.3xlarge is recommended but it seems a little outdated for the current chain.

16 vCPU's and 128 GiB is enough?
Is EBS Volume enough (with high IOPS) or do I need an attached NVMe?
Anything else I should know while setting it up?

Thanks!

**Comment by TheSlackOne** [comment]
Trying to get synced with `m5zn.3xlarge`, it does not get synced, oscillates 60-120 blocks from last. Not sure if its due to specs.

**Comment by j75689** [comment]
Hi @James19903 , maybe you can refer these docs 
https://github.com/bnb-chain/bsc/issues/502

**Comment by TheSlackOne** [comment]
Finally got synced with the `m5zn.3xlarge` instance, storage 8000 iops and 250 troughtputs. I had to use the [snapshots](https://github.com/bnb-chain/bsc-snapshots).
