### ISSUE TITLE
https://etherscan.io/chartsync/chaindefault < is it provided for BSC side ?

### ISSUE THREAD

**Issue by blackerhot** [bnb-chain/bsc#922]
I saw some drop for eth chain, BNB chain still keep growing in everyminute.
Yes its reall hard to get full sync with and also really hard to handle for the resources case.

Is it in your plan to reduce the current size ? and do some real time chart like eth ?

**Comment by j75689** [comment]
We are planning some features to reduce the hardware requirements for running nodes, some features will be launched in the near future, please wait patiently for the features to be released

We will discuss with the BSCScan team whether can support this chart

thanks
