### ISSUE TITLE
AWS EC2 instance specs

### ISSUE THREAD

**Issue by TheSlackOne** [bnb-chain/bsc#925]
I'm trying to get my full node synced with a `m5zn.3xlarge`, as the [documentation describes](https://docs.binance.org/smart-chain/developer/fullnode.html), but it does not get synced, it oscillates 60-120 blocks from last. Not sure if its due to specs.

**Comment by seonggwonyoon** [comment]
I recommend the i3en.2xlarge.

**Comment by TheSlackOne** [comment]
Finally got synced with the `m5zn.3xlarge` instance, storage 8000 iops and 250 troughtputs. I had to use the [snapshots](https://github.com/bnb-chain/bsc-snapshots). Took about ~4 days.

**Comment by seonggwonyoon** [comment]
I used two nvme disks mounted on i3en.2xlarge, which has better performance than aws ebs, in raid0.
It took a day to complete the sync.

**Comment by TheSlackOne** [comment]
Aren't nvme physical disks?

**Comment by seonggwonyoon** [comment]
> > I used two nvme disks mounted on i3en.2xlarge, which has better performance than aws ebs, in raid0. It took a day to complete the sync. Also use the snapshots.
> 
> Aren't nvme physical disks?

I'm not sure if it's a physical disk or not.

However, it is much faster than ebs.
