### ISSUE TITLE
EIP-3074: AUTH and AUTHCALL opcodes

### ISSUE THREAD

**Issue by bertho-zero** [bnb-chain/bsc#929]
Will we see [EIP-3074](https://eips.ethereum.org/EIPS/eip-3074) implemented here?

This adds the `AUTH` and `AUTHCALL` opcodes.

**Comment by owen-reorg** [comment]
Not in the current plan.
We will do some research and reply to you later.

**Comment by guagualvcha** [comment]
@bertho-zero  We do not have plan to include EIP-3074 recently.
