### ISSUE TITLE
why eth_call & debug_traceCall always return opcode 0xfe not defined

### ISSUE THREAD

**Issue by ZRory** [bnb-chain/bsc#930]
hello,
i want use debug_traceCall to test a transaction but i got 0xfe always,i don't know why.

this is my parma,the transaction can execute

{"jsonrpc":"2.0","method":"eth_call","params":[{"from":"0xdc9173569d2c0801f90f1529f7c4de0e422394a0","gas":"0x27005","gasPrice":"0x12a05f200","hash":"0x7c0b7f547a677ea2ee2224f687b55dd0168f8029b5ee1ab51817753d00984f9e","input":"0x7ff36ab500000000000000000000000000000000000000000000000000000005b35e09d20000000000000000000000000000000000000000000000000000000000000080000000000000000000000000dc9173569d2c0801f90f1529f7c4de0e422394a00000000000000000000000000000000000000000000000000000000062918ae30000000000000000000000000000000000000000000000000000000000000002000000000000000000000000bb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c000000000000000000000000156ab3346823b651294766e23e6cf87254d68962","nonce":"0x1ab","to":"0x10ed43c718714eb63d5aa57b78b54704e256024e","value":"0x2386f26fc10000","type":"0x0","v":"0x94","r":"0x4bb085acf823317362bec7b68e8dfc215ab4d568bf34d3b96e2bb9b4b4c4cfbe","s":"0x26f5f4e465cef6ff1f305cce8fbedb87baeac9f9cfe60194a7b825e68063bda6"}, "pending"],"id":1124124}

**Comment by berktaylan** [comment]
Can you share your run parameters and config

**Comment by ZRory** [comment]
> 

my params:
{"jsonrpc":"2.0","method":"eth_call","params":[{"from":"0xdc9173569d2c0801f90f1529f7c4de0e422394a0","gas":"0x27005","gasPrice":"0x12a05f200","input":"0x7ff36ab500000000000000000000000000000000000000000000000000000005b35e09d20000000000000000000000000000000000000000000000000000000000000080000000000000000000000000dc9173569d2c0801f90f1529f7c4de0e422394a00000000000000000000000000000000000000000000000000000000062918ae30000000000000000000000000000000000000000000000000000000000000002000000000000000000000000bb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c000000000000000000000000156ab3346823b651294766e23e6cf87254d68962","to":"0x10ed43c718714eb63d5aa57b78b54704e256024e","value":"0x2386f26fc10000"}, "pending"],"id":1124124}

**Comment by ZRory** [comment]
it's send to pancakeswap router, always return 
{
    "jsonrpc": "2.0",
    "id": 1124124,
    "error": {
        "code": -32000,
        "message": "invalid opcode: opcode 0xfe not defined"
    }
}

**Comment by owen-reorg** [comment]
It seems the transaction is an existing transaction on chain.

```
{"jsonrpc":"2.0","method":"eth_call","params":[{"from":"0xdc9173569d2c0801f90f1529f7c4de0e422394a0","gas":"0x27005","gasPrice":"0x12a05f200","input":"0x7ff36ab500000000000000000000000000000000000000000000000000000005b35e09d20000000000000000000000000000000000000000000000000000000000000080000000000000000000000000dc9173569d2c0801f90f1529f7c4de0e422394a00000000000000000000000000000000000000000000000000000000062918ae30000000000000000000000000000000000000000000000000000000000000002000000000000000000000000bb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c000000000000000000000000156ab3346823b651294766e23e6cf87254d68962","to":"0x10ed43c718714eb63d5aa57b78b54704e256024e","value":"0x2386f26fc10000"}, "0x11573df"],"id":1124124}
```

When I changed the block height of `eth_call`, I got

```
{
    "error": {
        "code": -32000,
        "message": "err: insufficient funds for gas * price + value: address 0xdC9173569D2C0801F90F1529F7C4de0E422394A0 have 0 want 798745000000000 (supplied gas 159749)"
    },
    "id": 1124124,
    "jsonrpc": "2.0"
}
```

But with latest height, the result is

```
{
    "error": {
        "code": -32000,
        "message": "invalid opcode: opcode 0xfe not defined"
    },
    "id": 1124124,
    "jsonrpc": "2.0"
}
```

I believe it's not the problem of chain or API, it's the problem of the contracts state.

You might try to debug it with [hardhat forking](https://hardhat.org/hardhat-network/guides/mainnet-forking).

**Comment by ZRory** [comment]
Sorry, I entered the wrong parameters, now it works fine, and you can turn off this issue,thanks
