### ISSUE TITLE
[Please help me] eth.pendingTransaction return null

### ISSUE THREAD

**Issue by tranductinh94** [bnb-chain/bsc#939]
System information
Geth version: 1.1.0
OS & Version: Ubuntu

Expected behaviour
I'm subscribing to the pending transaction via websocket and getting the transaction with the hashes
Actual behaviour
The get transaction is returning null instead for all the pending transaction hashes. My txpool.status not data
![Screenshot_1](https://user-images.githubusercontent.com/42437812/172032201-ff7c0b2e-f10f-4853-9399-72e4607b8153.png)

Run geth with the following config:
geth --config ./config.toml --datadir ./node --cache 18000 --rpc.allow-unprotected-txs --txlookuplimit 0 --http --rpc --maxpeers 100 --ws --syncmode=full

File config.toml
[config.toml.txt](https://github.com/bnb-chain/bsc/files/8839208/config.toml.txt)

Did i miss any configuration. Please help me.

**Comment by yarzc0de** [comment]
it's not fully synced

**Comment by owen-reorg** [comment]
Does it work after fully synced?

**Comment by PPianAIC** [comment]
Excuse me, it's not fully synced, can I restart full synced from 0? How to set starting from 0?
