### ISSUE TITLE
Transaction stuck in my BSC node but works perfect with public node

### ISSUE THREAD

**Issue by kgcdream2019** [bnb-chain/bsc#941]
#### System information

Geth version: `geth 1.1.10`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
Normally transaction should be confirmed within limited amount of time

#### Actual behaviour
I submitted transaction and it works before.
But I found some transactions stuck and wait permanently
I verified gas limit and gas price is normal : gas price 7.5 GWEI, gas limit = 200% 
if I use public node RPC, then all transaction works perfect.
The node is synced and there are no problem in reading of blockchain data

#### Steps to reproduce the behaviour
When I restart node, it is fine.
transaction not confirmed after several days later

**Comment by owen-reorg** [comment]
What's the response of `getTransaction` in your local node and public API after you submitted the transaction?

> When I restart node, it is fine.

Does it mean the stuck transactions got confirmed after restart or new transactions after restart will not be stuck?

**Comment by kgcdream2019** [comment]
Thanks for you reply, 
In my javascript code, I use ethers library, the transaction is waiting permanently when I use my node rpc.
If I switch to public node RPC, then all is fine

**Comment by owen-reorg** [comment]
Does your node run a local dev network or is connected to the public network?

In the local dev network, you should turn on the `miner` function in config.

In the public network, you can compare the latest height of your node with the public network to confirm that your node is connected to the public network and fully synced.

**Comment by kgcdream2019** [comment]
My node is connected to public nodes and its height is latest.

**Comment by kashirin-dm** [comment]
I have a similar issue. When I send a transaction through my node using the IPC interface, it is broadcasted quite slowly and might be included in a block after several minutes. 
But for comparison, I also sent transactions through two public providers with a private RPC point, and their transactions are delivered instantly.

I have good hardware and a good connection, and I've experimented with different hardware and different hosting options, including AWS, but sending transactions through my node is always slow.

This thread hasn't been active for a while, perhaps the author has found a solution to the problem? I can provide additional data if needed.

**Comment by bnb-tw** [comment]
@kgcdream2019 is this still an issue for you?
