### ISSUE TITLE
Some newbie questions regarding running a full node

### ISSUE THREAD

**Issue by jurgenBE** [bnb-chain/bsc#944]
Hi, I've setup a full node an Ubuntu machine with 3.2 T nVME drives,and I got it up and running in Seattle :

1. If I compare my 'pending transactions' with for example Moralis - i find that mine are only as fast as Moralis, sometimes even slower and a lot less tx's than them. So it has no added value other than free calls for an expensive server, do you all have this too, or are you faster than these public nodes like Moralis,quicknode,etc ... Any tips then if Yes ?

2. I use web3 and my metamask account with private key to send a signed transaction - it doesn't seem faster than on my local computer with no local full node server. I read something about broadcasting your tx from your local server, but don't know how to do it other than by web3. Any suggestions, tips how to make it faster on this local full node server

Many thanx from this newbie ...

**Comment by owen-reorg** [comment]
The transactions are received by a full node(either local or remote) via HTTP request first and then broadcast to the whole network via P2P protocol.
It's expected to be faster in the first step but in the view of the transaction being mined, there is no apparent difference between them. It depends on the network.

If you want to speed up the confirmation time of your transaction in a crowded network, you should consider increasing your gas price.
