### ISSUE TITLE
testnet is very slow

### ISSUE THREAD

**Issue by zacintosh** [bnb-chain/bsc#945]
It has been especially slow for the last couple of days.
I can't deploy or send token.
I can't develop with this!

**Comment by guagualvcha** [comment]
@zacintosh  the first endpoint do have some issues, please try use following endpoints:
```
https://data-seed-prebsc-2-s1.binance.org:8545/
https://data-seed-prebsc-1-s2.binance.org:8545/
https://data-seed-prebsc-2-s2.binance.org:8545/
https://data-seed-prebsc-1-s3.binance.org:8545/
```

**Comment by zacintosh** [comment]
@guagualvcha thank you. Connected.

But this time [https://testnet.bscscan.com](https://testnet.bscscan.com) returned 522 Error.
The testnet is very unstable.

Please close this ticket for now.
