### ISSUE TITLE
bsc节点可以随意冻结合约执行？

### ISSUE THREAD

**Issue by metafootball** [bnb-chain/bsc#951]
我们为了捕捉 bsc 上的抢跑机器人
做了一个 token 合约在交易时冻结抢跑的买入订单
该合约没有进行任何推广，仅是自己的地址买入
上线后有两个抢跑机器人买入后被冻结
随后该合约 代币 便无法转入 lp
直至现在 合约无法进行任何交易
合约地址 0x11fd1db37e597c094001be80a93c0840912a9db2

作为一个去中心化网络需要明确如下问题：
1. 节点是否有黑名单机制？
2. 如果有，黑名单触发机制是什么规则，需要明确规则拒绝黑箱操作
3. 如何解除黑名单，明确规则

**Comment by smithdodo** [comment]
Just did a quick check on your contract. It seems that the problem occured after the following tx:
 `0x13ec532024d34b8291c7d83ac2049f2c5df6cbf8a0e297a77c4620a2e824300c` 

I can confirm that before this tx
- Transfer from one of your addr `0x2bd09e...` works fine
- LP burn from `0xa2696f...` works fine

After that tx all transfers will fail with revert msg - "can not trade"

It is problably not a bsc related issue. Most likely the tx mentioned above triggered some state changes in your antibot contract, which lead to current situation.

I hope you still can somehow fix/configure your contracts and withdraw the token sitting in the pair.

**Comment by metafootball** [comment]
谢谢，lp 已全部取出
