### ISSUE TITLE
How to run this docker images ???please

### ISSUE THREAD

**Issue by zhaoxiangjunupi** [bnb-chain/bsc#957]
https://hub.docker.com/r/dysnix/bsc/tags

**Comment by zhaoxiangjunupi** [comment]
how to run this images??
eg:docker run .....

**Comment by Loverush** [comment]
You can refer to https://github.com/bnb-chain/bsc-docker

**Comment by zhaoxiangjunupi** [comment]
> You can refer to https://github.com/bnb-chain/bsc-docker


There is no docker run parameter here.

**Comment by zhaoxiangjunupi** [comment]
> try:
> 
> 1. docker pull dysnix/bsc:latest
> 2. docker run -it -d dysnix/bsc
>    This worked for me.


Is this too simple, no parameters are specified, and the API cannot be accessed

**Comment by Loverush** [comment]
> > You can refer to https://github.com/bnb-chain/bsc-docker
> 
> There is no docker run parameter here.

If you wanna run a private node locally, you can just follow above repo step by step

**Comment by zhaoxiangjunupi** [comment]
> > > You can refer to https://github.com/bnb-chain/bsc-docker
> > 
> > 
> > There is no docker run parameter here.
> 
> If you wanna run a private node locally, you can just follow above repo step by step


I want to use docker run images + specific parameters...
do you have any idea？？please
