### ISSUE TITLE
Transaction speed question.

### ISSUE THREAD

**Issue by Traianik** [bnb-chain/bsc#965]
Hello! I have a problem and i don't know from which side is the problem. I made a transaction instantly when a token was launched, at time 06:00:08 PM , however, my transaction was only confirmed after 2 blocks at time 06:00:14 PM, but the first transaction with this token was made exactly at the launch at 06:00:08, from here what is the problem? That I got delay from node or blockchain is taking this long to confirm the transaction, if it's from blockchain then how the first transaction on the token was exactly at the token launch? 
Both transactions have the same amount of gas.
My transaction - https://bscscan.com/tx/0x0767d345ee6b614bb8e3df94fe17db9e854c37ee214cee20c07fe61afb44e8e6
First transaction - https://bscscan.com/tx/0x829ade3f6fcb6efef90d2fec22081ff032e6e95a2b2f76db556b2ecdcb321077

**Comment by Loverush** [comment]
Nodes have their right to choose which txs to broadcast. In general, if you want to be fast, you have to run your own node.

**Comment by Traianik** [comment]
> Nodes have their right to choose which txs to broadcast. In general, if you want to be fast, you have to run your own node.

Ok, but how it is possible that the first transaction is in the same block when liquidity is added, I thought when you broadcast a transaction it should take like 2 blocks to approve..
