### ISSUE TITLE
The node cannot be started properly

### ISSUE THREAD

**Issue by bhswap** [bnb-chain/bsc#968]
Linux / CentOS 
Geth version v1.1.11
Failed to start the node after the snapshot pruning is complete. 
Pruned both nodes and encountered the same problem
Tried to roll back versions V1.1.9 and V1.1.10. Is void.

geth \
--config "./config.toml" \
--datadir "./data"  \
--cache "36000" \
--http.corsdomain "*" \
--http.vhosts "*" \
--ws.origins "*" \
--diffsync \
--snapshot="true" \
--rpc.allow-unprotected-txs \
--txlookuplimit=0 \
--txpool.reannouncetime 5m \
&

 Error message

t=2022-06-28T11:22:52+0800 lvl=warn msg="Unclean shutdown detected"             booted=2021-04-29T13:12:22+0800 age=1y2mo4d
t=2022-06-28T11:22:52+0800 lvl=warn msg="Unclean shutdown detected"             booted=2021-04-29T13:37:18+0800 age=1y2mo4d
t=2022-06-28T11:22:52+0800 lvl=warn msg="Unclean shutdown detected"             booted=2021-05-12T11:03:56+0800 age=1y1mo3w
t=2022-06-28T11:22:52+0800 lvl=warn msg="Unclean shutdown detected"             booted=2021-05-18T15:51:15+0800 age=1y1mo2w
t=2022-06-28T11:22:52+0800 lvl=info msg="Starting peer-to-peer node"            instance=Geth/v1.1.11-70d08a57/linux-amd64/go1.15.3
t=2022-06-28T11:22:52+0800 lvl=info msg="New local node record"                 seq=32 id=d15952fc2036143eee0ec3a7bd1cd74a205eabb762116af2a440effbac9da9be ip=127.0.0.1 udp=30311 tcp=30311
t=2022-06-28T11:22:52+0800 lvl=info msg="Started P2P networking"                self=enode://8c19730fefeddd80eccf938d583f945c40a1c32692e512ac9e6858404eb986c13372f6d4a68e97cd17b707962f09067a1645d255b609026e17547a3fbb47048e@127.0.0.1:30311
t=2022-06-28T11:22:52+0800 lvl=info msg="IPC endpoint opened"                   url=/root/node/data/geth.ipc
t=2022-06-28T11:22:52+0800 lvl=info msg="HTTP server started"                   endpoint=[::]:8545 prefix= cors=* vhosts=*
t=2022-06-28T11:22:52+0800 lvl=info msg="WebSocket enabled"                     url=ws://[::]:8546
t=2022-06-28T11:22:58+0800 lvl=info msg="New local node record"                 seq=33 id=d15952fc2036143eee0ec3a7bd1cd74a205eabb762116af2a440effbac9da9be ip=1 udp=30311 tcp=30311
t=2022-06-28T11:23:01+0800 lvl=info msg="Block synchronisation started"
t=2022-06-28T11:23:03+0800 lvl=eror msg="Snapshot extension registration failed" peer=35f2159c err="peer connected on snap without compatible eth support"
t=2022-06-28T11:23:29+0800 lvl=eror msg="Snapshot extension registration failed" peer=bc8af532 err="peer connected on snap without compatible eth support"
t=2022-06-28T11:24:01+0800 lvl=warn msg="Synchronisation failed, dropping peer"  peer=06bbf0c47873f2bc92614cdc219406aaf21ca08b4b4356147bcedd9cba264a03 err=timeout
t=2022-06-28T11:24:06+0800 lvl=info msg="Downloader queue stats"                 receiptTasks=0 blockTasks=0 itemSize="6.66 KiB" throttle=8192
t=2022-06-28T11:24:06+0800 lvl=info msg="Skip duplicated bad block"              number=18,905,023 hash=0xe0eea619a625643e18d6de15152f5fd490c1c6f6a9ff8f59c93c659e06e46c2b
t=2022-06-28T11:24:06+0800 lvl=eror msg="\n########## BAD BLOCK #########\nChain config: {ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Berlin: <nil>, YOLO v3: <nil>, Euler: 18907621, Engine: parlia}\n\nNumber: 18905023\nHash: 0xe0eea619a625643e18d6de15152f5fd490c1c6f6a9ff8f59c93c659e06e46c2b\n\n\nError: could not apply tx 0 [0x45241a92863419dfab3c7c6b25352600880557ad0f2bf682d08c1fc24f787bdd]: nonce too high: address 0x05070f90B34FcE76d63EC1Ad2F3BAc5DD7a67EEA, tx: 88890 state: 0\n##############################\n"
t=2022-06-28T11:24:06+0800 lvl=warn msg="Synchronisation failed, dropping peer"  peer=edc97b378675f687a925590c9641a70cdf800fe80448afb494200859016902a3 err="retrieved hash chain is invalid: could not apply tx 0 [0x45241a92863419dfab3c7c6b25352600880557ad0f2bf682d08c1fc24f787bdd]: nonce too high: address 0x05070f90B34FcE76d63EC1Ad2F3BAc5DD7a67EEA, tx: 88890 state: 0"
t=2022-06-28T11:25:04+0800 lvl=eror msg="Snapshot extension registration failed" peer=4dfa8e8a err="peer connected on snap without compatible eth support"
t=2022-06-28T11:25:06+0800 lvl=warn msg="Synchronisation failed, dropping peer"  peer=edc97b378675f687a925590c9641a70cdf800fe80448afb494200859016902a3 err=timeout
t=2022-06-28T11:25:07+0800 lvl=warn msg="Multiple headers for single request"    peer=4d060f21 headers=0
t=2022-06-28T11:25:07+0800 lvl=warn msg="Synchronisation failed, dropping peer"  peer=4d060f217025e92ebd8b1f3911a4a1f2eff521e3cf48f6d534367ea9ab5223b5 err="action from bad peer ignored: multiple headers (0) for single request"
t=2022-06-28T11:25:07+0800 lvl=warn msg="Synchronisation failed, retrying"       err="peer is unknown or unhealthy"
t=2022-06-28T11:25:07+0800 lvl=warn msg="Multiple headers for single request"    peer=35bcdd16 headers=0
t=2022-06-28T11:25:07+0800 lvl=warn msg="Synchronisation failed, dropping peer"  peer=35bcdd160ce5e8ea2ab0804b5d0abcae7a691e0dc2684d485e9bb568ed72b549 err="action from bad peer ignored: multiple headers (0) for single request"
t=2022-06-28T11:26:05+0800 lvl=warn msg="Synchronisation failed, dropping peer"  peer=35bcdd160ce5e8ea2ab0804b5d0abcae7a691e0dc2684d485e9bb568ed72b549 err=timeout
t=2022-06-28T11:26:07+0800 lvl=info msg="Downloader queue stats"                 receiptTasks=0 blockTasks=210 itemSize="25.63 KiB" throttle=2558
t=2022-06-28T11:26:07+0800 lvl=info msg="Skip duplicated bad block"              number=18,905,023 hash=0xe0eea619a625643e18d6de15152f5fd490c1c6f6a9ff8f59c93c659e06e46c2b
t=2022-06-28T11:26:07+0800 lvl=eror msg="\n########## BAD BLOCK #########\nChain config: {ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Berlin: <nil>, YOLO v3: <nil>, Euler: 18907621, Engine: parlia}\n\nNumber: 18905023\nHash: 0xe0eea619a625643e18d6de15152f5fd490c1c6f6a9ff8f59c93c659e06e46c2b\n\n\nError: could not apply tx 0 [0x45241a92863419dfab3c7c6b25352600880557ad0f2bf682d08c1fc24f787bdd]: nonce too high: address 0x05070f90B34FcE76d63EC1Ad2F3BAc5DD7a67EEA, tx: 88890 state: 0\n##############################\n"
t=2022-06-28T11:26:07+0800 lvl=warn msg="Synchronisation failed, dropping peer"  peer=990675ebedb8d859bc4c179611f88d123bc888e9aae499c7703339c8d797ebf8 err="retrieved hash chain is invalid: could not apply tx 0 [0x45241a92863419dfab3c7c6b25352600880557ad0f2bf682d08c1fc24f787bdd]: nonce too high: address 0x05070f90B34FcE76d63EC1Ad2F3BAc5DD7a67EEA, tx: 88890 state: 0"
t=2022-06-28T11:26:07+0800 lvl=warn msg="Synchronisation failed, retrying"       err="peer is unknown or unhealthy"
t=2022-06-28T11:26:07+0800 lvl=warn msg="Synchronisation failed, retrying"       err="peer is unknown or unhealthy"
t=2022-06-28T11:26:08+0800 lvl=warn msg="Synchronisation failed, dropping peer"  peer=907e381725fed461394ada237d416a32904257ef7ff28dfad88eefd6c9cd43a3 err="action from bad peer ignored: returned headers 192 != requested 1"
t=2022-06-28T11:27:03+0800 lvl=warn msg="Synchronisation failed, dropping peer"  peer=907e381725fed461394ada237d416a32904257ef7ff28dfad88eefd6c9cd43a3 err=timeout
t=2022-06-28T11:27:31+0800 lvl=info msg="Downloader queue stats"                 receiptTasks=0 blockTasks=0   itemSize="53.14 KiB" throttle=1234
t=2022-06-28T11:27:31+0800 lvl=info msg="Skip duplicated bad block"              number=18,905,023 hash=0xe0eea619a625643e18d6de15152f5fd490c1c6f6a9ff8f59c93c659e06e46c2b
t=2022-06-28T11:27:31+0800 lvl=eror msg="\n########## BAD BLOCK #########\nChain config: {ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Berlin: <nil>, YOLO v3: <nil>, Euler: 18907621, Engine: parlia}\n\nNumber: 18905023\nHash: 0xe0eea619a625643e18d6de15152f5fd490c1c6f6a9ff8f59c93c659e06e46c2b\n\n\nError: could not apply tx 0 [0x45241a92863419dfab3c7c6b25352600880557ad0f2bf682d08c1fc24f787bdd]: nonce too high: address 0x05070f90B34FcE76d63EC1Ad2F3BAc5DD7a67EEA, tx: 88890 state: 0\n##############################\n"
t=2022-06-28T11:27:31+0800 lvl=warn msg="Synchronisation failed, dropping peer"  peer=990675ebedb8d859bc4c179611f88d123bc888e9aae499c7703339c8d797ebf8 err="retrieved hash chain is invalid: could not apply tx 0 [0x45241a92863419dfab3c7c6b25352600880557ad0f2bf682d08c1fc24f787bdd]: nonce too high: address 0x05070f90B34FcE76d63EC1Ad2F3BAc5DD7a67EEA, tx: 88890 state: 0"
t=2022-06-28T11:27:32+0800 lvl=warn msg="Multiple headers for single request"    peer=9b59e9ea headers=0
t=2022-06-28T11:27:32+0800 lvl=warn msg="Synchronisation failed, dropping peer"  peer=9b59e9eae5c889f3223253289fc11ce6dbb9a9d59ab62dbbf6ea72b9c276e6b9 err="action from bad peer ignored: multiple headers (0) for single request"
t=2022-06-28T11:27:54+0800 lvl=warn msg="Synchronisation failed, dropping peer"  peer=9b59e9eae5c889f3223253289fc11ce6dbb9a9d59ab62dbbf6ea72b9c276e6b9 err=timeout
t=2022-06-28T11:28:00+0800 lvl=info msg="Skip duplicated bad block"              number=18,905,023 hash=0xe0eea619a625643e18d6de15152f5fd490c1c6f6a9ff8f59c93c659e06e46c2b
t=2022-06-28T11:28:00+0800 lvl=eror msg="\n########## BAD BLOCK #########\nChain config: {ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Berlin: <nil>, YOLO v3: <nil>, Euler: 18907621, Engine: parlia}\n\nNumber: 18905023\nHash: 0xe0eea619a625643e18d6de15152f5fd490c1c6f6a9ff8f59c93c659e06e46c2b\n\n\nError: could not apply tx 0 [0x45241a92863419dfab3c7c6b25352600880557ad0f2bf682d08c1fc24f787bdd]: nonce too high: address 0x05070f90B34FcE76d63EC1Ad2F3BAc5DD7a67EEA, tx: 88890 state: 0\n##############################\n"
t=2022-06-28T11:28:00+0800 lvl=warn msg="Synchronisation failed, dropping peer"  peer=5df25a822cd19cd570470086125258e0ad745da27adcfa36a23bde23cee8ee33 err="retrieved hash chain is invalid: could not apply tx 0 [0x45241a92863419dfab3c7c6b25352600880557ad0f2bf682d08c1fc24f787bdd]: nonce too high: address 0x05070f90B34FcE76d63EC1Ad2F3BAc5DD7a67EEA, tx: 88890 state: 0"
t=2022-06-28T11:28:00+0800 lvl=warn msg="Synchronisation failed, retrying"       err="peer is unknown or unhealthy"
t=2022-06-28T11:28:00+0800 lvl=warn msg="Synchronisation failed, retrying"       err="peer is unknown or unhealthy"
t=2022-06-28T11:28:00+0800 lvl=warn msg="Synchronisation failed, retrying"       err="peer is unknown or unhealthy"
t=2022-06-28T11:28:00+0800 lvl=warn msg="Synchronisation failed, retrying"       err="peer is unknown or unhealthy"
t=2022-06-28T11:28:00+0800 lvl=warn msg="Synchronisation failed, retrying"       err="peer is unknown or unhealthy"
t=2022-06-28T11:28:00+0800 lvl=warn msg="Synchronisation failed, retrying"       err="peer is unknown or unhealthy"
t=2022-06-28T11:28:00+0800 lvl=warn msg="Synchronisation failed, retrying"       err="peer is unknown or unhealthy"
t=2022-06-28T11:28:00+0800 lvl=warn msg="Synchronisation failed, retrying"       err="peer is unknown or unhealthy"
t=2022-06-28T11:28:00+0800 lvl=warn msg="Synchronisation failed, retrying"       err="peer is unknown or unhealthy"
t=2022-06-28T11:28:00+0800 lvl=warn msg="Synchronisation failed, retrying"       err="peer is unknown or unhealthy"
t=2022-06-28T11:28:00+0800 lvl=warn msg="Synchronisation failed, retrying"       err="peer is unknown or unhealthy"
t=2022-06-28T11:28:00+0800 lvl=warn msg="Synchronisation failed, retrying"       err="peer is unknown or unhealthy"
t=2022-06-28T11:28:00+0800 lvl=warn msg="Synchronisation failed, retrying"       err="peer is unknown or unhealthy"
t=2022-06-28T11:28:00+0800 lvl=warn msg="Synchronisation failed, dropping peer"  peer=fb9c2df3bcbbe05fc96e05e47d5ccc00f7f1fcd70548e69e04fb5214ada02e92 err="action from bad peer ignored: returned headers 192 != requested 1"
t=2022-06-28T11:28:10+0800 lvl=warn msg="Synchronisation failed, dropping peer"  peer=fb9c2df3bcbbe05fc96e05e47d5ccc00f7f1fcd70548e69e04fb5214ada02e92 err=timeout
t=2022-06-28T11:28:12+0800 lvl=info msg="Skip duplicated bad block"              number=18,905,023 hash=0xe0eea619a625643e18d6de15152f5fd490c1c6f6a9ff8f59c93c659e06e46c2b
t=2022-06-28T11:28:12+0800 lvl=eror msg="\n########## BAD BLOCK #########\nChain config: {ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Berlin: <nil>, YOLO v3: <nil>, Euler: 18907621, Engine: parlia}\n\nNumber: 18905023\nHash: 0xe0eea619a625643e18d6de15152f5fd490c1c6f6a9ff8f59c93c659e06e46c2b\n\n\nError: could not apply tx 0 [0x45241a92863419dfab3c7c6b25352600880557ad0f2bf682d08c1fc24f787bdd]: nonce too high: address 0x05070f90B34FcE76d63EC1Ad2F3BAc5DD7a67EEA, tx: 88890 state: 0\n##############################\n"
t=2022-06-28T11:28:12+0800 lvl=warn msg="Synchronisation failed, dropping peer"  peer=991e28ca94f08e1967f9dd8a36691fe37ad48eb8cc837275fe4cebde2e5ffcbd err="retrieved hash chain is invalid: could not apply tx 0 [0x45241a92863419dfab3c7c6b25352600880557ad0f2bf682d08c1fc24f787bdd]: nonce too high: address 0x05070f90B34FcE76d63EC1Ad2F3BAc5DD7a67EEA, tx: 88890 state: 0"

**Comment by Marijus** [comment]
having same issue. please let me know if you manage to resolve it.

**Comment by bhswap** [comment]
> having same issue. please let me know if you manage to resolve it.

Delete the existing data, download the snapshot from this address for resynchronization, follow the steps above
https://github.com/BNB48Club/bsc-snapshots
