### ISSUE TITLE
Cannot fetch historical transactions even with txlookuplimit 0 

### ISSUE THREAD

**Issue by tpalaz** [bnb-chain/bsc#970]
I've successfully setup and ran my fullnode using BNB48Club's snapshots and have been able to get it to sync.

I'm facing is that historic transactions aren't able to be retreived via RPC calls. Specifically, eth_getTransaction and getTransactionReceipt return null, and any other data / logs older than 4 days doesn't work. Whereas if the transaction was recent (before 4 days ago), the node has no problem serving it. 

From my experiementation, it seems that any TX older than ~4 days ago doesn't work. The maximum block range for which I was able to get a receipt/transaction from was block 18940000 - at the time of writing, the current block is 19089352.

Is this due to the snapshot that was downloaded? Or could it be configuration of the node? For reference, my startup parameters are:

`--config ./config.toml --datadir ./mainnet --cache 32000 --rpc.allow-unprotected-txs --txlookuplimit 0 --http --maxpeers 100 --ws --syncmode=full --snapshot=true --diffsync --http.api eth,net,web3,debug
`

IOPS and mgasps are exceeding (averaging around 300 mgasps) and the node is fully synced. 

Likewise, my config file is here:
```

[Unit]
Description=BSC Full Node

[Service]
User=geth
Type=simple
WorkingDirectory=/home/geth
ExecStart=/bin/bash /home/geth/start.sh
Restart=on-failure
RestartSec=30
TimeoutSec=300
IOWeight=8000
CPUWeight=8000

[Install]
WantedBy=default.target
```

Any advice on how to fix this issue? The only possible thing I could think of was the snapshot not having the correct indexes - which doesn't make a ton of sense and probably wouldn't even allow sync. 

Any block past 18940000 at the time of writing **does not work to get transactions/logs from**.

**Comment by unlimittt** [comment]
> I've successfully setup and ran my fullnode using BNB48Club's snapshots and have been able to get it to sync.
> 
> I'm facing is that historic transactions aren't able to be retreived via RPC calls. Specifically, eth_getTransaction and getTransactionReceipt return null, and any other data / logs older than 4 days doesn't work. Whereas if the transaction was recent (before 4 days ago), the node has no problem serving it.
> 
> From my experiementation, it seems that any TX older than ~4 days ago doesn't work. The maximum block range for which I was able to get a receipt/transaction from was block 18940000 - at the time of writing, the current block is 19089352.
> 
> Is this due to the snapshot that was downloaded? Or could it be configuration of the node? For reference, my startup parameters are:
> 
> `--config ./config.toml --datadir ./mainnet --cache 32000 --rpc.allow-unprotected-txs --txlookuplimit 0 --http --maxpeers 100 --ws --syncmode=full --snapshot=true --diffsync --http.api eth,net,web3,debug `
> 
> IOPS and mgasps are exceeding (averaging around 300 mgasps) and the node is fully synced.
> 
> Likewise, my config file is here:
> 
> ```
> 
> [Unit]
> Description=BSC Full Node
> 
> [Service]
> User=geth
> Type=simple
> WorkingDirectory=/home/geth
> ExecStart=/bin/bash /home/geth/start.sh
> Restart=on-failure
> RestartSec=30
> TimeoutSec=300
> IOWeight=8000
> CPUWeight=8000
> 
> [Install]
> WantedBy=default.target
> ```
> 
> Any advice on how to fix this issue? The only possible thing I could think of was the snapshot not having the correct indexes - which doesn't make a ton of sense and probably wouldn't even allow sync.
> 
> Any block past 18940000 at the time of writing **does not work to get transactions/logs from**.

So what was the decision to get transaction receipts?
