### ISSUE TITLE
Pending transactions not found in mempool

### ISSUE THREAD

**Issue by fomotrader** [bnb-chain/bsc#973]
#### System information

Geth Version: 1.1.11
Git Commit: 70d08a5791d0650322e79591ac1fb869df607586
Git Commit Date: 20220608
Architecture: amd64
Go Version: go1.17.2
Operating System: linux
GOPATH=/root/go
GOROOT=go

#### Expected behaviour
Mempool should have pending transactions

#### Actual behaviour
Mempool has no pending transactions, the node just mines a ton of blocks and that's it

#### Steps to reproduce the behaviour
All I did was upgrade my version of GETH from an old one to the latest release

#### Backtrace
Not sure how to provide more valuable feedback

When submitting logs: please submit them as text and not screenshots.

**Comment by fomotrader** [comment]
https://gist.github.com/fomotrader/b7be33b03de17ce9560606e0cd673380

`/geth --config /root/config.toml --datadir /root/server/data-seed/geth/ --cache=54000 --pcscdpath=""`

**Comment by cosinlink** [comment]
You need to confirm that the block height is the latest, otherwise you really cannot receive the latest transaction, it is possible that your node machine is poor, so you may fall behind the latest height of BSC

**Comment by fomotrader** [comment]
Here's a script that compares my block height to bscscan 

<img width="617" alt="image" src="https://user-images.githubusercontent.com/82184770/177819542-a02aca0a-7bf3-49c3-95f7-a974bb500074.png">

**Comment by atlaschiew** [comment]
hi @fomotrader is ur issue same as me? https://github.com/bnb-chain/bsc/issues/984

**Comment by fomotrader** [comment]
No I don't think so as my mempool has 0 transactions most of the time

**Comment by bnb-tw** [comment]
@fomotrader is this still an issue for you?

**Comment by CocoStarZ** [comment]
No more respond, close the issue for now
