### ISSUE TITLE
What happened in v1.1.11 that it can't find peers ?

### ISSUE THREAD

**Issue by freaker2k7** [bnb-chain/bsc#974]
Since I upgrade to v1.1.11 it now takes hours for the node to find peers in contrast to the previous versions when it connected almost instantly.

I tried downloading the latest `config.toml` hoping you updated the bootnodes and the static ones, but no change, my nodes now take hours to find peers.

I see it tries hundreds of nodes but can't connect to any:
```
t=2022-07-03T12:23:36+0200 lvl=info msg="Looking for peers"                     peercount=0 tried=35 static=36
t=2022-07-03T12:23:47+0200 lvl=info msg="Looking for peers"                     peercount=0 tried=1  static=36
t=2022-07-03T12:24:07+0200 lvl=info msg="Looking for peers"                     peercount=0 tried=0  static=36
t=2022-07-03T12:24:07+0200 lvl=warn msg="Synchronisation failed, retrying"      err="peer is unknown or unhealthy"
t=2022-07-03T12:24:17+0200 lvl=info msg="Looking for peers"                     peercount=0 tried=29 static=36
t=2022-07-03T12:24:28+0200 lvl=info msg="Looking for peers"                     peercount=0 tried=1  static=36
t=2022-07-03T12:24:42+0200 lvl=info msg="Looking for peers"                     peercount=0 tried=9  static=36
t=2022-07-03T12:24:53+0200 lvl=info msg="Looking for peers"                     peercount=0 tried=38 static=36
t=2022-07-03T12:25:03+0200 lvl=info msg="Looking for peers"                     peercount=0 tried=1  static=36
t=2022-07-03T12:25:20+0200 lvl=info msg="Looking for peers"                     peercount=0 tried=0  static=36
t=2022-07-03T12:25:30+0200 lvl=info msg="Looking for peers"                     peercount=0 tried=28 static=36
t=2022-07-03T12:25:44+0200 lvl=info msg="Looking for peers"                     peercount=0 tried=1  static=36
t=2022-07-03T12:25:46+0200 lvl=warn msg="Synchronisation failed, dropping peer" peer=9086a4586d53f611243af7a12510fb4918808b5783e0668567dcd108c43658f4 err=timeout
t=2022-07-03T12:25:55+0200 lvl=info msg="Looking for peers"                     peercount=0 tried=9  static=36
t=2022-07-03T12:26:19+0200 lvl=info msg="Looking for peers"                     peercount=0 tried=36 static=36
t=2022-07-03T12:26:30+0200 lvl=info msg="Looking for peers"                     peercount=0 tried=0  static=36
t=2022-07-03T12:26:41+0200 lvl=info msg="Looking for peers"                     peercount=0 tried=27 static=36
t=2022-07-03T12:26:51+0200 lvl=info msg="Looking for peers"                     peercount=0 tried=1  static=36
t=2022-07-03T12:27:05+0200 lvl=info msg="Looking for peers"                     peercount=0 tried=10 static=36
t=2022-07-03T12:27:29+0200 lvl=info msg="Looking for peers"                     peercount=0 tried=36 static=36
t=2022-07-03T12:27:31+0200 lvl=warn msg="Synchronisation failed, dropping peer" peer=68036bd21a3aa984516accf98d67294ff5ffd30e65a794d50a6775b4b45096ff err=timeout
t=2022-07-03T12:27:40+0200 lvl=info msg="Looking for peers"                     peercount=0 tried=0  static=36
t=2022-07-03T12:27:50+0200 lvl=info msg="Looking for peers"                     peercount=0 tried=29 static=36
t=2022-07-03T12:28:01+0200 lvl=info msg="Looking for peers"                     peercount=0 tried=0  static=36
t=2022-07-03T12:28:15+0200 lvl=info msg="Looking for peers"                     peercount=0 tried=10 static=36
t=2022-07-03T12:28:25+0200 lvl=info msg="Looking for peers"                     peercount=0 tried=27 static=36
t=2022-07-03T12:28:45+0200 lvl=info msg="Looking for peers"                     peercount=0 tried=11 static=36
t=2022-07-03T12:28:49+0200 lvl=warn msg="Synchronisation failed, dropping peer" peer=0e8faf860dce288213e055a2c3efee9b3db5190465d6bdc9333b9a8178ffebda err=timeout
t=2022-07-03T12:28:59+0200 lvl=info msg="Looking for peers"                     peercount=0 tried=26 static=36
t=2022-07-03T12:29:09+0200 lvl=info msg="Looking for peers"                     peercount=0 tried=3  static=36
t=2022-07-03T12:29:20+0200 lvl=info msg="Looking for peers"                     peercount=0 tried=0  static=36
t=2022-07-03T12:29:40+0200 lvl=info msg="Looking for peers"                     peercount=0 tried=36 static=36
```

Any suggestions ?

**Comment by freaker2k7** [comment]
@du5  Tried, same behavior.

My servers are in Germany and Finland BTW...

**Comment by freaker2k7** [comment]
@du5 Thank you very much.
Currently it magically found some peers, so I'll let it be, but I'll have to restart soon and update you on how it goes.

**Comment by kugimiya530** [comment]
> "enode://5fa5c9d8c49d8066ff1090ff84dcfd3fbdb327d2be240518b062e5626d46452fe218d0c57c07958a42a2fcde2f6893eae895c55aba9ee807187c028b46b2f6d0@54.194.111.140:30311"

where did u find this 

https://api.binance.org/v1/discovery/peers  ?

**Comment by freaker2k7** [comment]
@kugimiya530 du5's list doesn't work.

**Comment by cosinlink** [comment]
> 

In some cases, it may take hours to find available nodes without stopping them

**Comment by freaker2k7** [comment]
In Germany 3 nodes of mine are still looking for peers the 7'th day....

**Comment by kugimiya530** [comment]
> > @cosinlink In Germany 3 nodes of mine are still looking for peers the 7'th day....
> 
> try to replace `StaticNodes` to this in `config.toml`
> 
> ```
> 
> StaticNodes = [
> "enode://6c575b4deb87f9f0015043fc5659342903ad6d2cec6242f0880c3cf8dc2f43b62264f8fe35f95a2e283e116cc4f5fa9278f607898cb52bf16c43bfa55695b8da@54.75.74.232:30311",
> 
> "enode://5f200471faf212bacdd698e237e96bb737bd701d73e7817b12482c45e5c9e86e80126f33513328d6c8cfc9080fba12a84256130a3af2f7f8405fe7cb830c12a0@52.17.2.216:30311",
> 
> "enode://710ed272e03b92c803cd165e5fa071da015815d312f17d107a43ad3b12b0f05c830c58ced2df7547294f5365fe76cdcf1a58f923ee5612d247a6d5b80cfe16a8@34.245.31.55:30311",
> 
> "enode://760b5fde9bc14155fa2a87e56cf610701ad6c1adcf44555a7b839baf71f86f11cdadcaf925e50b17c98cc28e20e0df3c3463caad7c6658a76ab68389af639f33@34.243.1.225:30311",
> 
> "enode://3c13113538f3ca7d898d99f9656e0939451558758fd9c9475cff29f020187a56e8140bd24bd57164b07c3d325fc53e1ef622f793851d2648ed93d9d5a7ce975c@34.254.238.155:30311",
> 
> "enode://760b5fde9bc14155fa2a87e56cf610701ad6c1adcf44555a7b839baf71f86f11cdadcaf925e50b17c98cc28e20e0df3c3463caad7c6658a76ab68389af639f33@34.243.1.225:30311",
> 
> "enode://cc6e84983505ce10271a840132f180ccf47b13406b8c3682fb1a7854f57911d70b7f7d110d025b8d27fa9ef0ec9ea9a0802ed53c8670ee46fe91e40cda1202e7@52.51.86.21:30311",
> 
> "enode://5d9e15ad695649c41a2ba4170ea8f9dd03d9319de8cb4b9cc95c5e42efaf7d4883835e8929b0164c1ad006bc2da74b94d59fdb8b8b6899af6eb88004182e3c11@54.155.69.195:30311",
> 
> "enode://41d57b0f00d83016e1bb4eccff0f3034aa49345301b7be96c6bb23a0a852b9b87b9ed11827c188ad409019fb0e578917d722f318665f198340b8a15ae8beff36@34.252.87.229:30311"
> 
> ]
> ```

where did you find those new static node

**Comment by freaker2k7** [comment]
@cosinlink this list doesn't work.

@kugimiya530 what is this magic link - https://api.binance.org/v1/discovery/peers ?
Google results screenshot - https://i.imgur.com/Mhau7bO.png

**Comment by kugimiya530** [comment]
Uh.. i saw it in bsc offical guide, you cant enter this website?

Evgeny Kolyakov ***@***.***> 於 2022年7月5日 週二 下午7:47 寫道：

**Comment by freaker2k7** [comment]
Wow!!!! I ran `curl -XGET "https://api.binance.org/v1/discovery/peers"` on the machine (just for safety, maybe it's geo dependent 🤷‍♂️) and just appended that list to the original `config.toml` (both to static & bootnodes) and it connected right away !!!!

Thank you!!!.

**Comment by kugimiya530** [comment]
can u share ur geth's startup parameter?

**Comment by freaker2k7** [comment]
@kugimiya530 sure.

So I build it in a docker:
`docker build --tag bsc --build-arg VERSION=1.1.11 --network host https://github.com/freaker2k7/binance-smart-chain-node.git`

I fixed some issues in my fork, tried to PR, but no response from the dev of the original `binance-smart-chain-node` repo.
Also, my machine is strong enough to run a miner in a docker and not "feel" it at all and I got 6T of space, so that's not an issue as well.

Then I load the data from the latest snapshot (I run the docker [see at the bottom] for 30 seconds and then kill it using `docker rm -f bsc` , for it to create all it's folders and...):

```bash
mkdir -p /data/tmp
cd /data/tmp
wget -q -O - $(curl -sL "https://raw.githubusercontent.com/binance-chain/bsc-snapshots/main/README.md" | grep -A 4 'EU Endpoint' | tail -n1 | cut -c3-) | tar -I lz4 -xvf -
rm -rf /data/bsc/geth/LOCK /data/bsc/geth/*chaindata
mv /data/tmp/server/data-seed/geth/* /data/bsc/geth/.
rm -rf /data/tmp
```

And then I run it as so:

`docker run -d --restart=always --log-driver json-file --log-opt max-size=10m --log-opt max-file=3 -v /data/bsc:/root/.ethereum --name bsc -p 0.0.0.0:8545:8545 -p 0.0.0.0:8546:8546 bsc --syncmode full --cache 18000 --allow-insecure-unlock --rpc.txfeecap=0 --ws --ws.addr="0.0.0.0" --ws.origins "*" --ws.api eth,net,txpool,web3 --txlookuplimit 0 --verbosity=3 --rpc --http.corsdomain="*" --rpcaddr="0.0.0.0"`

(Yes, I need `--txlookuplimit 0` for my own reasons)

It ran wonderfully until I updated to 1.1.11 because all of my nodes got "Bad blocks".

Beforehand I didn't have to touch `config.toml` at all.

**Comment by kugimiya530** [comment]
Did u using snapshot?

Maybe u can download or redownload it and add parameter

--snapshot=false , i was have same problem few days ago, and solve by this

Evgeny Kolyakov ***@***.***> 於 2022年7月6日 週三 下午3:48 寫道：

**Comment by freaker2k7** [comment]
1. `Did you use`
2. I clearly wrote I'm using a snapshot
3. Why should I redownload it if I just downloaded it ?!
4. `add a parameter`
5. Where to add ? what to add ?
6. Please don't write "I guess" answers.

**Comment by kugimiya530** [comment]
Ok, just trying to figure, cuz i meet this problem and solve, if u dont
want me guess i will be quiet, cuz i am not user thx

Evgeny Kolyakov ***@***.***> 於 2022年7月6日 週三 下午4:01 寫道：

**Comment by cosinlink** [comment]
Have you fixed this issue ?

**Comment by cosinlink** [comment]
> 

we will update new `StaticNodes` after a while, it maybe help for this issue
