### ISSUE TITLE
Pending in txpool always show 1

### ISSUE THREAD

**Issue by atlaschiew** [bnb-chain/bsc#984]
Hello, anyone here knows why my pending counter always show 1 while queued counter is keep increasing?

![image](https://user-images.githubusercontent.com/45816141/177917502-16438d10-bca0-4f85-9960-d81caba41d40.png)

my [Eth.TxPool] setting in config.toml 
```
[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 512
GlobalSlots = 75000
AccountQueue = 256
GlobalQueue = 5000
Lifetime = 10800000000000
```

geth version 1.1.11

**Comment by SolidityGo** [comment]
Could you check the latest height compared other nodes  ?

**Comment by atlaschiew** [comment]
> Could you check the latest height compared other nodes ?

i have latest height compared to other nodes. 

my terminal keep showing `ERROR[07-08|13:09:23.397] Snapshot extension registration failed   peer=3ce52055 err="peer connected on snap without compatible eth support"` , but i dun think it matters my case.

it seems like tx is coming to my txpool, but it cant be promoted to pending. will it caused by some bugs of v1.1.11?

**Comment by atlaschiew** [comment]
and my node cannot shut down properly, most of tijme i have to execute `pkill -HUP geth`

**Comment by atlaschiew** [comment]
> and my node cannot shut down properly, most of time i have to execute `pkill -HUP geth`. i feel that this caused by ` Waiting background transaction indexer to exit`

**Comment by atlaschiew** [comment]
sorry, my bad, i created a new module then occur channel blocking through subscribing newTxsEvent`
