### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by lvmingliang** [bnb-chain/bsc#987]
#### System information

Geth version: `1.1.11`
OS & Version:Linux
Commit hash : (if `develop`)

#### Expected behaviour

goroutine 1930776 [select]:
github.com/ethereum/go-ethereum/core/state.(*subfetcher).loop(0xc2e64ce9c0)
        github.com/ethereum/go-ethereum/core/state/trie_prefetcher.go:328 +0x1e5
created by github.com/ethereum/go-ethereum/core/state.newSubfetcher
        github.com/ethereum/go-ethereum/core/state/trie_prefetcher.go:259 +0x185

goroutine 1930576 [select]:
github.com/ethereum/go-ethereum/core/state.(*subfetcher).loop(0xc2e3d67860)
        github.com/ethereum/go-ethereum/core/state/trie_prefetcher.go:328 +0x1e5
created by github.com/ethereum/go-ethereum/core/state.newSubfetcher
        github.com/ethereum/go-ethereum/core/state/trie_prefetcher.go:259 +0x185

goroutine 1930731 [select]:
github.com/ethereum/go-ethereum/core/state.(*subfetcher).loop(0xc2492b0000)
        github.com/ethereum/go-ethereum/core/state/trie_prefetcher.go:328 +0x1e5
created by github.com/ethereum/go-ethereum/core/state.newSubfetcher
        github.com/ethereum/go-ethereum/core/state/trie_prefetcher.go:259 +0x185

goroutine 1930760 [select]:
github.com/ethereum/go-ethereum/core/state.(*subfetcher).loop(0xc224ed5110)
        github.com/ethereum/go-ethereum/core/state/trie_prefetcher.go:328 +0x1e5
created by github.com/ethereum/go-ethereum/core/state.newSubfetcher
        github.com/ethereum/go-ethereum/core/state/trie_prefetcher.go:259 +0x185

goroutine 1757113 [select, 8 minutes]:
github.com/ethereum/go-ethereum/eth/protocols/diff.(*Peer).broadcastDiffLayers(0xc2e592f980)
        github.com/ethereum/go-ethereum/eth/protocols/diff/peer.go:47 +0xab
created by github.com/ethereum/go-ethereum/eth/protocols/diff.NewPeer
        github.com/ethereum/go-ethereum/eth/protocols/diff/peer.go:41 +0x2f0

goroutine 1930775 [select]:
github.com/ethereum/go-ethereum/core/state.(*subfetcher).loop(0xc2e64ce8f0)
        github.com/ethereum/go-ethereum/core/state/trie_prefetcher.go:328 +0x1e5
created by github.com/ethereum/go-ethereum/core/state.newSubfetcher
        github.com/ethereum/go-ethereum/core/state/trie_prefetcher.go:259 +0x185

goroutine 1926444 [select, 1 minutes]:
net.(*netFD).connect.func2(0x1b4ab28, 0xc34f2a7b00, 0xc22557a800, 0xc34f293b00, 0xc34f293aa0)
        net/fd_unix.go:118 +0x8a
created by net.(*netFD).connect
        net/fd_unix.go:117 +0x253
#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by cosinlink** [comment]
checking

**Comment by brilliant-lx** [comment]
Based on the provided backtrack, `trie_prefetcher `is waiting for messages, it worked normally.
Pls more the whole backtrace.
And one more thing, did you use the v1.1.11 released version?

**Comment by brilliant-lx** [comment]
pls provide the full backtrace log or how to reproduce.
