### ISSUE TITLE
Re-enable pending block access without --mine parameter

### ISSUE THREAD

**Issue by billyadelphia** [bnb-chain/bsc#997]
Based on my question #778 and this issue #358 
Even with --mine parameter, I still can't access pending block somehow.
# Rationale

Why should this feature exist?
Because it's enabled by default on any other EVM blockchain, a lot of us needed this.

# Implementation

Do you have ideas regarding the implementation of this feature?
I have tried, but gave up. It doesn't have to enabled by default, like adding new param like `--enable-pending-block` or else

Are you willing to implement this feature?
No

**Comment by yutianwu** [comment]
There was a performance issue related to the `--mine` flag, so we disabled it. There is no plan to add it back recently.

**Comment by yutianwu** [comment]
We disabled this feature in https://github.com/bnb-chain/bsc/pull/358, you can refer to this.

**Comment by dawnkie** [comment]
> @yutianwu if you want to enable it, which line of code would you change ?
> 
> I have tried to change the `PendingBlock` function on `miner.go` file based on the original geth (for ethereum), compile it myself, but it just throw some weird error.



> @yutianwu if you want to enable it, which line of code would you change ?
> 
> I have tried to change the `PendingBlock` function on `miner.go` file based on the original geth (for ethereum), compile it myself, but it just throw some weird error.

How do you solve it now?

**Comment by dawnkie** [comment]
> We disabled this feature in #358, you can refer to this.

How to config to re-enable pending function?

**Comment by ofarukcaki** [comment]
This is the reason I started learning go and my go knowledge is limited, any help regarding to re-enable this feature is appreciated. Currently I'm checking go-ethereum and the #358 together but no luck so far
